GRINS-0.7.0: GRINSTesting::TestingUtils Class Reference
GRINSTesting::TestingUtils Class Reference
#include <testing_utils.h>
Static Public Member Functions
static libMesh::Real abs_tol_from_rel_tol (libMesh::Real exact, libMesh::Real rel_tol)
Get absolute tolerance from input relative tol.
static libMesh::Real epsilon ()
Convenience function.
Detailed Description
Definition at line 36 of file testing_utils.h.
Member Function Documentation
static libMesh::Real GRINSTesting::TestingUtils::abs_tol_from_rel_tol (libMesh::Real exact, libMesh::Real rel_tol) inline static
Get absolute tolerance from input relative tol.
CppUnit uses absolute tolerance for double tests. This will let the user input a relative tolerance and an exact value to get back the corresponding absolute tolerance.
Definition at line 44 of file testing_utils.h.
Referenced by GRINSTesting::NASAThermoTestBase::test_cp_common(), GRINSTesting::NASAThermoTestBase::test_h_common(), and GRINSTesting::KineticsTestBase::test_omega_dot_common().
     {
       return std::abs(exact)*rel_tol;
     }
static libMesh::Real GRINSTesting::TestingUtils::epsilon () inline static
Convenience function.
Definition at line 50 of file testing_utils.h.
Referenced by GRINSTesting::AntiochAirNASA9ThermoTest::test_cp(), GRINSTesting::AntiochAirNASA9ThermoTest::test_hs(), and GRINSTesting::AntiochAirNASA9KineticsTest::test_omega_dot().
     {
       return std::numeric_limits<libMesh::Real>::epsilon();
     }
The documentation for this class was generated from the following file:
test/common/testing_utils.h