GRINS-0.7.0: GRINS::CachedValues Class Reference
GRINS::CachedValues Class Reference
#include <cached_values.h>
Public Member Functions
CachedValues ()
~CachedValues ()
void add_quantity (unsigned int quantity)
void add_quantities (const std::set< unsigned int > &cache_list)
void clear ()
bool is_active (unsigned int quantity)
void set_values (unsigned int quantity, std::vector< libMesh::Number > &values)
void set_gradient_values (unsigned int quantity, std::vector< libMesh::Gradient > &values)
void set_vector_values (unsigned int quantity, std::vector< std::vector< libMesh::Number > > &values)
void set_vector_gradient_values (unsigned int quantity, std::vector< std::vector< libMesh::Gradient > > &values)
const std::vector< libMesh::Number > & get_cached_values (unsigned int quantity) const
const std::vector< libMesh::Gradient > & get_cached_gradient_values (unsigned int quantity) const
const std::vector< std::vector< libMesh::Number > > & get_cached_vector_values (unsigned int quantity) const
const std::vector< std::vector< libMesh::Gradient > > & get_cached_vector_gradient_values (unsigned int quantity) const
unsigned int size () const
Protected Attributes
std::set< unsigned int > _cache_list
std::map< unsigned int, std::vector< libMesh::Number > > _cached_values
std::map< unsigned int, std::vector< libMesh::Gradient > > _cached_gradient_values
std::map< unsigned int, std::vector< std::vector< libMesh::Number > > > _cached_vector_values
std::map< unsigned int, std::vector< std::vector< libMesh::Gradient > > > _cached_vector_gradient_values
Detailed Description
Definition at line 43 of file cached_values.h.
Constructor & Destructor Documentation
GRINS::CachedValues::CachedValues ()
Definition at line 30 of file cached_values.C.
   {
     return;
   }
GRINS::CachedValues::~CachedValues ()
Definition at line 35 of file cached_values.C.
   {
     return;
   }
Member Function Documentation
void GRINS::CachedValues::add_quantities (const std::set< unsigned int > & cache_list)
Definition at line 46 of file cached_values.C.
References _cache_list.
   {
     _cache_list.insert(cache_list.begin(), cache_list.end());
     return;
   }
void GRINS::CachedValues::add_quantity (unsigned int quantity)
Definition at line 40 of file cached_values.C.
References _cache_list.
Referenced by main().
   {
     _cache_list.insert(quantity);
     return;
   }
void GRINS::CachedValues::clear ()
Definition at line 52 of file cached_values.C.
References _cached_gradient_values, _cached_values, _cached_vector_gradient_values, and _cached_vector_values.
   {
     _cached_values.clear();
     _cached_gradient_values.clear();
     _cached_vector_values.clear();
     _cached_vector_gradient_values.clear();
     return;
   }
const std::vector< libMesh::Gradient > & GRINS::CachedValues::get_cached_gradient_values (unsigned int quantity) const
Definition at line 105 of file cached_values.C.
References _cached_gradient_values.
Referenced by GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::assemble_energy_time_deriv(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::assemble_mass_time_deriv(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::assemble_momentum_time_deriv(), and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::element_time_derivative().
   {
     libmesh_assert( _cached_gradient_values.find(quantity) != _cached_gradient_values.end() );
     return _cached_gradient_values.find(quantity)->second;
   }
const std::vector< libMesh::Number > & GRINS::CachedValues::get_cached_values (unsigned int quantity) const
Definition at line 99 of file cached_values.C.
References _cached_values.
Referenced by GRINS::GasRecombinationCatalyticWall< Chemistry >::apply_fluxes(), GRINS::GasSolidCatalyticWall< Chemistry >::apply_fluxes(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::assemble_energy_time_deriv(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::assemble_mass_time_deriv(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::assemble_momentum_time_deriv(), and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::element_time_derivative().
   {
     libmesh_assert( _cached_values.find(quantity) != _cached_values.end() );
     return _cached_values.find(quantity)->second;
   }
const std::vector< std::vector< libMesh::Gradient > > & GRINS::CachedValues::get_cached_vector_gradient_values (unsigned int quantity) const
Definition at line 117 of file cached_values.C.
References _cached_vector_gradient_values.
Referenced by GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::element_time_derivative().
   {
     libmesh_assert( _cached_vector_gradient_values.find(quantity) != _cached_vector_gradient_values.end() );
     return _cached_vector_gradient_values.find(quantity)->second;
   }
const std::vector< std::vector< libMesh::Number > > & GRINS::CachedValues::get_cached_vector_values (unsigned int quantity) const
Definition at line 111 of file cached_values.C.
References _cached_vector_values.
Referenced by GRINS::GasRecombinationCatalyticWall< Chemistry >::apply_fluxes(), GRINS::GasSolidCatalyticWall< Chemistry >::apply_fluxes(), and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::element_time_derivative().
   {
     libmesh_assert( _cached_vector_values.find(quantity) != _cached_vector_values.end() );
     return _cached_vector_values.find(quantity)->second;
   }
bool GRINS::CachedValues::is_active (unsigned int quantity)
Definition at line 62 of file cached_values.C.
References _cache_list.
   {
     bool value = false;
     if( _cache_list.find(quantity) != _cache_list.end() )
       value = true;
     return value;
   }
void GRINS::CachedValues::set_gradient_values (unsigned int quantity, std::vector< libMesh::Gradient > & values)
Definition at line 78 of file cached_values.C.
References _cached_gradient_values.
Referenced by GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::compute_element_time_derivative_cache(), and GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::compute_element_time_derivative_cache().
   {
     // Using insert() breaks here. Not entirely sure why...
     _cached_gradient_values[quantity] = values;
     return;
   }
void GRINS::CachedValues::set_values (unsigned int quantity, std::vector< libMesh::Number > & values)
Definition at line 72 of file cached_values.C.
References _cached_values.
Referenced by GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::compute_element_time_derivative_cache(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::compute_element_time_derivative_cache(), and main().
   {
     _cached_values.insert( std::make_pair( quantity, values ) );
     return;
   }
void GRINS::CachedValues::set_vector_gradient_values (unsigned int quantity, std::vector< std::vector< libMesh::Gradient > > & values)
Definition at line 86 of file cached_values.C.
References _cached_vector_gradient_values.
Referenced by GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::compute_element_time_derivative_cache().
   {
     _cached_vector_gradient_values[quantity] = values;
     return;
   }
void GRINS::CachedValues::set_vector_values (unsigned int quantity, std::vector< std::vector< libMesh::Number > > & values)
Definition at line 93 of file cached_values.C.
References _cached_vector_values.
Referenced by GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::compute_element_time_derivative_cache(), and main().
   {
     _cached_vector_values[quantity] =  values;
     return;
   }
unsigned int GRINS::CachedValues::size () const inline
Definition at line 91 of file cached_values.h.
References _cache_list.
   {
     return _cache_list.size();
   }
Member Data Documentation
std::set<unsigned int> GRINS::CachedValues::_cache_list protected
Definition at line 81 of file cached_values.h.
Referenced by add_quantities(), add_quantity(), is_active(), and size().
std::map<unsigned int,std::vector<libMesh::Gradient> > GRINS::CachedValues::_cached_gradient_values protected
Definition at line 84 of file cached_values.h.
Referenced by clear(), get_cached_gradient_values(), and set_gradient_values().
std::map<unsigned int,std::vector<libMesh::Number> > GRINS::CachedValues::_cached_values protected
Definition at line 83 of file cached_values.h.
Referenced by clear(), get_cached_values(), and set_values().
std::map<unsigned int,std::vector<std::vector<libMesh::Gradient> > > GRINS::CachedValues::_cached_vector_gradient_values protected
Definition at line 86 of file cached_values.h.
Referenced by clear(), get_cached_vector_gradient_values(), and set_vector_gradient_values().
std::map<unsigned int,std::vector<std::vector<libMesh::Number> > > GRINS::CachedValues::_cached_vector_values protected
Definition at line 85 of file cached_values.h.
Referenced by clear(), get_cached_vector_values(), and set_vector_values().
The documentation for this class was generated from the following files:
src/utilities/include/grins/cached_values.h
src/utilities/src/cached_values.C