GRINS-0.7.0: GRINS::HeatConduction< Conductivity > Class Template Reference
GRINS::HeatConduction< Conductivity > Class Template Reference
#include <heat_conduction.h>
Public Member Functions
HeatConduction (const GRINS::PhysicsName &physics_name, const GetPot &input)
~HeatConduction ()
virtual void init_variables (libMesh::FEMSystem *system)
Initialize variables for this physics.
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Set which variables are time evolving.
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for element interiors.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Public Member Functions inherited from GRINS::Physics
Physics (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~Physics ()
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void damping_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Damping matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_damping_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
ICHandlingBase * get_ic_handler ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
Protected Attributes
unsigned int _dim
PrimitiveTempFEVariables _temp_vars
libMesh::Number _rho
libMesh::Number _Cp
Conductivity _k
Conductivity.
Protected Attributes inherited from GRINS::Physics
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
Private Member Functions
HeatConduction ()
void register_variables ()
Additional Inherited Members
Static Public Member Functions inherited from GRINS::Physics
static void set_is_axisymmetric (bool is_axisymmetric)
Set whether we should treat the problem as axisymmetric.
static bool is_axisymmetric ()
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Member Functions inherited from GRINS::Physics
libMesh::UniquePtr< libMesh::FEGenericBase< libMesh::Real > > build_new_fe (const libMesh::Elem *elem, const libMesh::FEGenericBase< libMesh::Real > *fe, const libMesh::Point p)
void parse_enabled_subdomains (const GetPot &input, const std::string &physics_name)
Static Protected Attributes inherited from GRINS::Physics
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
static bool _is_axisymmetric = false
Caches whether we are solving an axisymmetric problem or not.
Detailed Description
template<class Conductivity>
class GRINS::HeatConduction< Conductivity >
Definition at line 36 of file heat_conduction.h.
Constructor & Destructor Documentation
template<class K > GRINS::HeatConduction< K >::HeatConduction (const GRINS::PhysicsName & physics_name, const GetPot & input)
Definition at line 47 of file heat_conduction.C.
References GRINS::HeatConduction< Conductivity >::_Cp, GRINS::Physics::_ic_handler, GRINS::HeatConduction< Conductivity >::_rho, GRINS::PhysicsNaming::heat_conduction(), GRINS::MaterialsParsing::read_density(), GRINS::MaterialsParsing::read_specific_heat(), and GRINS::HeatConduction< Conductivity >::register_variables().
     : Physics(physics_name,input),
       _temp_vars(input,PhysicsNaming::heat_conduction()),
       _rho(0.0),
       _Cp(0.0),
       _k(input,MaterialsParsing::material_name(input,PhysicsNaming::heat_conduction()))
   {
     MaterialsParsing::read_density( PhysicsNaming::heat_conduction(), input, (*this), this->_rho );
     MaterialsParsing::read_specific_heat( PhysicsNaming::heat_conduction(), input, (*this), this->_Cp );
     this->register_variables();
     // This is deleted in the base class
     this->_ic_handler = new GenericICHandler( physics_name, input );
   }
template<class K > GRINS::HeatConduction< K >::~HeatConduction ()
Definition at line 65 of file heat_conduction.C.
   {
     return;
   }
template<class Conductivity > GRINS::HeatConduction< Conductivity >::HeatConduction () private
Member Function Documentation
template<class K > void GRINS::HeatConduction< K >::element_time_derivative (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Time dependent part(s) of physics for element interiors.
Reimplemented from GRINS::Physics.
Definition at line 117 of file heat_conduction.C.
   {
     // The number of local degrees of freedom in each variable.
     const unsigned int n_T_dofs = context.get_dof_indices(_temp_vars.T()).size();
     // We get some references to cell-specific data that
     // will be used to assemble the linear system.
     // Element Jacobian * quadrature weights for interior integration.
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(_temp_vars.T())->get_JxW();
     // The temperature shape function gradients (in global coords.)
     // at interior quadrature points.
     const std::vector<std::vector<libMesh::RealGradient> >& T_gradphi =
       context.get_element_fe(_temp_vars.T())->get_dphi();
     // The subvectors and submatrices we need to fill:
     //
     // K_{\alpha \beta} = R_{\alpha},{\beta} = \partial{ R_{\alpha} } / \partial{ {\beta} } (where R denotes residual)
     // e.g., for \alpha = T and \beta = v we get: K_{Tu} = R_{T},{u}
     //
     libMesh::DenseSubMatrix<libMesh::Number> &KTT = context.get_elem_jacobian(_temp_vars.T(), _temp_vars.T()); // R_{T},{T}
     libMesh::DenseSubVector<libMesh::Number> &FT = context.get_elem_residual(_temp_vars.T()); // R_{T}
     // Now we will build the element Jacobian and residual.
     // Constructing the residual requires the solution and its
     // gradient from the previous timestep.  This must be
     // calculated at each quadrature point by summing the
     // solution degree-of-freedom values by the appropriate
     // weight functions.
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     for (unsigned int qp=0; qp != n_qpoints; qp++)
       {
         // Compute the solution & its gradient at the old Newton iterate.
         libMesh::Gradient grad_T;
         grad_T = context.interior_gradient(_temp_vars.T(), qp);
         // Compute the conductivity at this qp
         libMesh::Real _k_qp = this->_k(context, qp);
         // First, an i-loop over the  degrees of freedom.
         for (unsigned int i=0; i != n_T_dofs; i++)
           {
             FT(i) += JxW[qp]*(-_k_qp*(T_gradphi[i][qp]*grad_T));
             if (compute_jacobian)
               {
                 for (unsigned int j=0; j != n_T_dofs; j++)
                   {
                     // TODO: precompute some terms like:
                     //   _rho*_Cp*T_phi[i][qp]*(vel_phi[j][qp]*T_grad_phi[j][qp])
                     KTT(i,j) += JxW[qp] * context.get_elem_solution_derivative() *
                       ( -_k_qp*(T_gradphi[i][qp]*T_gradphi[j][qp]) ); // diffusion term
                   } // end of the inner dof (j) loop
               } // end - if (compute_jacobian && context.get_elem_solution_derivative())
           } // end of the outer dof (i) loop
       } // end of the quadrature point (qp) loop
     return;
   }
template<class K > void GRINS::HeatConduction< K >::init_context (AssemblyContext & context) virtual
Initialize context for added physics variables.
Reimplemented from GRINS::Physics.
Definition at line 98 of file heat_conduction.C.
   {
     // We should prerequest all the data
     // we will need to build the linear system
     // or evaluate a quantity of interest.
     context.get_element_fe(_temp_vars.T())->get_JxW();
     context.get_element_fe(_temp_vars.T())->get_phi();
     context.get_element_fe(_temp_vars.T())->get_dphi();
     context.get_element_fe(_temp_vars.T())->get_xyz();
     context.get_side_fe(_temp_vars.T())->get_JxW();
     context.get_side_fe(_temp_vars.T())->get_phi();
     context.get_side_fe(_temp_vars.T())->get_dphi();
     context.get_side_fe(_temp_vars.T())->get_xyz();
     return;
   }
template<class K > void GRINS::HeatConduction< K >::init_variables (libMesh::FEMSystem * system) virtual
Initialize variables for this physics.
Implements GRINS::Physics.
Definition at line 78 of file heat_conduction.C.
   {
     // Get libMesh to assign an index for each variable
     this->_dim = system->get_mesh().mesh_dimension();
     _temp_vars.init(system);
     return;
   }
template<class K > void GRINS::HeatConduction< K >::mass_residual (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
Reimplemented from GRINS::Physics.
Definition at line 188 of file heat_conduction.C.
   {
     // First we get some references to cell-specific data that
     // will be used to assemble the linear system.
     // Element Jacobian * quadrature weights for interior integration
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(_temp_vars.T())->get_JxW();
     // The shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& phi =
       context.get_element_fe(_temp_vars.T())->get_phi();
     // The number of local degrees of freedom in each variable
     const unsigned int n_T_dofs = context.get_dof_indices(_temp_vars.T()).size();
     // The subvectors and submatrices we need to fill:
     libMesh::DenseSubVector<libMesh::Real> &F =
       context.get_elem_residual(_temp_vars.T());
     libMesh::DenseSubMatrix<libMesh::Real> &M =
       context.get_elem_jacobian(_temp_vars.T(), _temp_vars.T());
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     for (unsigned int qp = 0; qp != n_qpoints; ++qp)
       {
         // For the mass residual, we need to be a little careful.
         // The time integrator is handling the time-discretization
         // for us so we need to supply M(u_fixed)*u' for the residual.
         // u_fixed will be given by the fixed_interior_value function
         // while u' will be given by the interior_rate function.
         libMesh::Real T_dot;
         context.interior_rate(_temp_vars.T(), qp, T_dot);
         for (unsigned int i = 0; i != n_T_dofs; ++i)
           {
             F(i) -= JxW[qp]*(_rho*_Cp*T_dot*phi[i][qp] );
             if( compute_jacobian )
               {
                 for (unsigned int j=0; j != n_T_dofs; j++)
                   {
                     // We're assuming rho, cp are constant w.r.t. T here.
                     M(i,j) -=
                       context.get_elem_solution_rate_derivative()
                         * JxW[qp]*_rho*_Cp*phi[j][qp]*phi[i][qp] ;
                   }
               }// End of check on Jacobian
           } // End of element dof loop
       } // End of the quadrature point loop
     return;
   }
template<class K > void GRINS::HeatConduction< K >::register_parameter (const std::string & param_name, libMesh::ParameterMultiAccessor< libMesh::Number > & param_pointer) const virtual
Each subclass will register its copy of an independent.
Reimplemented from GRINS::ParameterUser.
Definition at line 249 of file heat_conduction.C.
References GRINS::ParameterUser::register_parameter().
   {
     ParameterUser::register_parameter(param_name, param_pointer);
     _k.register_parameter(param_name, param_pointer);
   }
template<class K > void GRINS::HeatConduction< K >::register_variables () private
Definition at line 71 of file heat_conduction.C.
References GRINS::GRINSPrivate::VariableWarehouse::check_and_register_variable(), and GRINS::VariablesParsing::temperature_section().
Referenced by GRINS::HeatConduction< Conductivity >::HeatConduction().
   {
     GRINSPrivate::VariableWarehouse::check_and_register_variable(VariablesParsing::temperature_section(),
                                                                  this->_temp_vars);
   }
template<class K > void GRINS::HeatConduction< K >::set_time_evolving_vars (libMesh::FEMSystem * system) virtual
Set which variables are time evolving.
Set those variables which evolve in time (as opposed to variables that behave like constraints). This is done separately from init_variables() because the MultiphysicsSystem must initialize its base class before time_evolving variables can be set. Default implementation is no time evolving variables.
Reimplemented from GRINS::Physics.
Definition at line 89 of file heat_conduction.C.
   {
     // Tell the system to march temperature forward in time
     system->time_evolving(_temp_vars.T());
     return;
   }
Member Data Documentation
template<class Conductivity > libMesh::Number GRINS::HeatConduction< Conductivity >::_Cp protected
Definition at line 77 of file heat_conduction.h.
Referenced by GRINS::HeatConduction< Conductivity >::HeatConduction().
template<class Conductivity > unsigned int GRINS::HeatConduction< Conductivity >::_dim protected
Definition at line 73 of file heat_conduction.h.
template<class Conductivity > Conductivity GRINS::HeatConduction< Conductivity >::_k protected
Conductivity.
Definition at line 80 of file heat_conduction.h.
template<class Conductivity > libMesh::Number GRINS::HeatConduction< Conductivity >::_rho protected
Definition at line 77 of file heat_conduction.h.
Referenced by GRINS::HeatConduction< Conductivity >::HeatConduction().
template<class Conductivity > PrimitiveTempFEVariables GRINS::HeatConduction< Conductivity >::_temp_vars protected
Definition at line 75 of file heat_conduction.h.
The documentation for this class was generated from the following files:
src/physics/include/grins/heat_conduction.h
src/physics/src/heat_conduction.C