GRINS-0.7.0: GRINS::ParsedFunctionNeumannBCFactoryHelper< FunctionType > Class Template Reference
GRINS::ParsedFunctionNeumannBCFactoryHelper< FunctionType > Class Template Reference
#include <parsed_function_neumann_bc_factory_helper.h>
Public Member Functions
ParsedFunctionNeumannBCFactoryHelper ()
~ParsedFunctionNeumannBCFactoryHelper ()
Protected Member Functions
SharedPtr< NeumannBCAbstract > build_neumman_func_common (const GetPot &input, MultiphysicsSystem &system, const FEVariablesBase &fe_var, const std::string &flux_input)
Helper function containing common code.
SharedPtr< NeumannBCAbstract > build_parsed_neumann_func (MultiphysicsSystem &system, const std::string &expression, VariableIndex var_idx)
Helper function that builds the right BC object depending on the FunctionType.
SharedPtr< NeumannBCAbstract > build_composite_parsed_neumann_func (MultiphysicsSystem &system, const std::vector< std::string > &expressions, const std::vector< VariableIndex > &var_indices)
Helper function that builds the right CompositeBC object depending on the FunctionType.
template<>
SharedPtr< NeumannBCAbstract > build_parsed_neumann_func (MultiphysicsSystem &, const std::string &expression, VariableIndex var_idx)
template<>
SharedPtr< NeumannBCAbstract > build_parsed_neumann_func (MultiphysicsSystem &system, const std::string &expression, VariableIndex var_idx)
template<>
SharedPtr< NeumannBCAbstract > build_composite_parsed_neumann_func (MultiphysicsSystem &, const std::vector< std::string > &expressions, const std::vector< VariableIndex > &var_indices)
template<>
SharedPtr< NeumannBCAbstract > build_composite_parsed_neumann_func (MultiphysicsSystem &system, const std::vector< std::string > &expressions, const std::vector< VariableIndex > &var_indices)
Detailed Description
template<typename FunctionType>
class GRINS::ParsedFunctionNeumannBCFactoryHelper< FunctionType >
Definition at line 48 of file parsed_function_neumann_bc_factory_helper.h.
Constructor & Destructor Documentation
template<typename FunctionType > GRINS::ParsedFunctionNeumannBCFactoryHelper< FunctionType >::ParsedFunctionNeumannBCFactoryHelper () inline
Definition at line 52 of file parsed_function_neumann_bc_factory_helper.h.
 {};
template<typename FunctionType > GRINS::ParsedFunctionNeumannBCFactoryHelper< FunctionType >::~ParsedFunctionNeumannBCFactoryHelper () inline
Definition at line 54 of file parsed_function_neumann_bc_factory_helper.h.
 {};
Member Function Documentation
template<typename FunctionType > SharedPtr<NeumannBCAbstract> GRINS::ParsedFunctionNeumannBCFactoryHelper< FunctionType >::build_composite_parsed_neumann_func (MultiphysicsSystem & system, const std::vector< std::string > & expressions, const std::vector< VariableIndex > & var_indices) protected
Helper function that builds the right CompositeBC object depending on the FunctionType.
template<> SharedPtr< NeumannBCAbstract > GRINS::ParsedFunctionNeumannBCFactoryHelper< libMesh::FunctionBase< libMesh::Number > >::build_composite_parsed_neumann_func (MultiphysicsSystem & , const std::vector< std::string > & expressions, const std::vector< VariableIndex > & var_indices) protected
Definition at line 91 of file parsed_function_neumann_bc_factory_helper.C.
   {
     return SharedPtr<NeumannBCAbstract>( new CompositeParsedNeumannBC<libMesh::Number>(expressions,var_indices) );
   }
template<> SharedPtr< NeumannBCAbstract > GRINS::ParsedFunctionNeumannBCFactoryHelper< libMesh::FEMFunctionBase< libMesh::Number > >::build_composite_parsed_neumann_func (MultiphysicsSystem & system, const std::vector< std::string > & expressions, const std::vector< VariableIndex > & var_indices) protected
Definition at line 100 of file parsed_function_neumann_bc_factory_helper.C.
   {
     return SharedPtr<NeumannBCAbstract>( new CompositeParsedFEMNeumannBC<libMesh::Number>(expressions,var_indices,system) );
   }
template<typename FunctionType > SharedPtr< NeumannBCAbstract > GRINS::ParsedFunctionNeumannBCFactoryHelper< FunctionType >::build_neumman_func_common (const GetPot & input, MultiphysicsSystem & system, const FEVariablesBase & fe_var, const std::string & flux_input) protected
Helper function containing common code.
This way, it's easy to add a new flux variable name to be parsed from input.
Definition at line 38 of file parsed_function_neumann_bc_factory_helper.C.
References GRINS::FEVariablesBase::active_var_names(), and GRINS::FEVariablesBase::var_indices().
Referenced by GRINS::ParsedFunctionNeumannBCFactory< FunctionType >::build_neumann_func().
   {
     const std::vector<std::string>& var_names = fe_var.active_var_names();
     SharedPtr<NeumannBCAbstract> func;
     // Use "standard" parsed version if there's only one variable
     if( var_names.size() == 1 )
       {
         libmesh_assert_equal_to( fe_var.var_indices().size(), 1 );
         std::string expression = input(flux_input,std::string("DIE!"));
         func = this->build_parsed_neumann_func(system,expression,fe_var.var_indices()[0]);
       }
     // Otherwise, use the composite versions
     else
       {
         libmesh_assert_equal_to( fe_var.var_indices().size(), var_names.size() );
         // We already checked size consistency for flux input and var_names
         // so just use var_names for the size
         std::vector<std::string> expressions(var_names.size());
         for( unsigned int i = 0; i < var_names.size(); i++ )
           expressions[i] = input(flux_input,std::string("DIE!"),i);
         func = this->build_composite_parsed_neumann_func(system,expressions,fe_var.var_indices());
       }
     return func;
   }
template<typename FunctionType > SharedPtr<NeumannBCAbstract> GRINS::ParsedFunctionNeumannBCFactoryHelper< FunctionType >::build_parsed_neumann_func (MultiphysicsSystem & system, const std::string & expression, VariableIndex var_idx) protected
Helper function that builds the right BC object depending on the FunctionType.
template<> SharedPtr< NeumannBCAbstract > GRINS::ParsedFunctionNeumannBCFactoryHelper< libMesh::FunctionBase< libMesh::Number > >::build_parsed_neumann_func (MultiphysicsSystem & , const std::string & expression, VariableIndex var_idx) protected
Definition at line 75 of file parsed_function_neumann_bc_factory_helper.C.
   {
     return SharedPtr<NeumannBCAbstract>( new ParsedNeumannBC<libMesh::Number>(expression,var_idx) );
   }
template<> SharedPtr< NeumannBCAbstract > GRINS::ParsedFunctionNeumannBCFactoryHelper< libMesh::FEMFunctionBase< libMesh::Number > >::build_parsed_neumann_func (MultiphysicsSystem & system, const std::string & expression, VariableIndex var_idx) protected
Definition at line 83 of file parsed_function_neumann_bc_factory_helper.C.
   {
     return SharedPtr<NeumannBCAbstract>( new ParsedFEMNeumannBC<libMesh::Number>(expression,system,var_idx) );
   }
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/parsed_function_neumann_bc_factory_helper.h
src/boundary_conditions/src/parsed_function_neumann_bc_factory_helper.C