GRINS-0.7.0: GRINS::SpalartAllmarasStabilizationBase< Viscosity > Class Template Reference
GRINS::SpalartAllmarasStabilizationBase< Viscosity > Class Template Reference
#include <spalart_allmaras_stab_base.h>
Public Member Functions
SpalartAllmarasStabilizationBase (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~SpalartAllmarasStabilizationBase ()
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
virtual void init_variables (libMesh::FEMSystem *system)
Initialize variables for this physics.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Public Member Functions inherited from GRINS::SpalartAllmaras< Viscosity >
SpalartAllmaras (const std::string &physics_name, const GetPot &input)
~SpalartAllmaras ()
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Sets velocity variables to be time-evolving.
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &)
Time dependent part(s) of physics for element interiors.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
Public Member Functions inherited from GRINS::TurbulenceModelsBase< Viscosity >
TurbulenceModelsBase (const std::string &physics_name, const GetPot &input)
~TurbulenceModelsBase ()
Public Member Functions inherited from GRINS::Physics
Physics (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~Physics ()
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void damping_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Damping matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_damping_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
ICHandlingBase * get_ic_handler ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
Protected Attributes
SpalartAllmarasStabilizationHelper _stab_helper
Protected Attributes inherited from GRINS::SpalartAllmaras< Viscosity >
VelocityFEVariables _flow_vars
PressureFEVariable _press_var
TurbulenceFEVariables _turbulence_vars
SpalartAllmarasHelper _spalart_allmaras_helper
SpalartAllmarasParameters _sa_params
Object handling the plethora of parameters.
std::set< libMesh::boundary_id_type > _wall_ids
unsigned int _no_of_walls
bool _infinite_distance
Protected Attributes inherited from GRINS::TurbulenceModelsBase< Viscosity >
unsigned int _dim
Physical dimension of problem.
libMesh::Number _rho
Material parameters, read from input.
Viscosity _mu
Viscosity object.
Protected Attributes inherited from GRINS::Physics
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
Private Member Functions
SpalartAllmarasStabilizationBase ()
Additional Inherited Members
Static Public Member Functions inherited from GRINS::Physics
static void set_is_axisymmetric (bool is_axisymmetric)
Set whether we should treat the problem as axisymmetric.
static bool is_axisymmetric ()
Public Attributes inherited from GRINS::SpalartAllmaras< Viscosity >
libMesh::UniquePtr< DistanceFunction > distance_function
libMesh::UniquePtr< libMesh::SerialMesh > boundary_mesh
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Member Functions inherited from GRINS::Physics
libMesh::UniquePtr< libMesh::FEGenericBase< libMesh::Real > > build_new_fe (const libMesh::Elem *elem, const libMesh::FEGenericBase< libMesh::Real > *fe, const libMesh::Point p)
void parse_enabled_subdomains (const GetPot &input, const std::string &physics_name)
Static Protected Attributes inherited from GRINS::Physics
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
static bool _is_axisymmetric = false
Caches whether we are solving an axisymmetric problem or not.
Detailed Description
template<class Viscosity>
class GRINS::SpalartAllmarasStabilizationBase< Viscosity >
Definition at line 36 of file spalart_allmaras_stab_base.h.
Constructor & Destructor Documentation
template<class Mu > GRINS::SpalartAllmarasStabilizationBase< Mu >::SpalartAllmarasStabilizationBase (const GRINS::PhysicsName & physics_name, const GetPot & input)
Definition at line 40 of file spalart_allmaras_stab_base.C.
     : SpalartAllmaras<Mu>(physics_name,input),
       _stab_helper( physics_name+"StabHelper", input )
   {
     return;
   }
template<class Mu > GRINS::SpalartAllmarasStabilizationBase< Mu >::~SpalartAllmarasStabilizationBase () virtual
Definition at line 49 of file spalart_allmaras_stab_base.C.
   {
     return;
   }
template<class Viscosity > GRINS::SpalartAllmarasStabilizationBase< Viscosity >::SpalartAllmarasStabilizationBase () private
Member Function Documentation
template<class Mu > void GRINS::SpalartAllmarasStabilizationBase< Mu >::init_context (AssemblyContext & context) virtual
Initialize context for added physics variables.
Reimplemented from GRINS::SpalartAllmaras< Viscosity >.
Definition at line 55 of file spalart_allmaras_stab_base.C.
References GRINS::SpalartAllmaras< Viscosity >::init_context().
   {
     // First call base class
     SpalartAllmaras<Mu>::init_context(context);
     // We also need second derivatives, so initialize those.
     context.get_element_fe(this->_turbulence_vars.nu())->get_d2phi();
     return;
   }
template<class Mu > void GRINS::SpalartAllmarasStabilizationBase< Mu >::init_variables (libMesh::FEMSystem * system) virtual
Initialize variables for this physics.
Reimplemented from GRINS::SpalartAllmaras< Viscosity >.
Reimplemented in GRINS::SpalartAllmarasSPGSMStabilization< Viscosity >.
Definition at line 67 of file spalart_allmaras_stab_base.C.
References GRINS::SpalartAllmaras< Viscosity >::init_variables().
Referenced by GRINS::SpalartAllmarasSPGSMStabilization< Viscosity >::init_variables().
   {
     // First call base class
     SpalartAllmaras<Mu>::init_variables(system);
     _stab_helper.init(*system);
     return;
   }
template<class Mu > void GRINS::SpalartAllmarasStabilizationBase< Mu >::register_parameter (const std::string & param_name, libMesh::ParameterMultiAccessor< libMesh::Number > & param_pointer) const virtual
Each subclass will register its copy of an independent.
Reimplemented from GRINS::SpalartAllmaras< Viscosity >.
Reimplemented in GRINS::SpalartAllmarasSPGSMStabilization< Viscosity >.
Definition at line 79 of file spalart_allmaras_stab_base.C.
References GRINS::SpalartAllmaras< Viscosity >::register_parameter().
Referenced by GRINS::SpalartAllmarasSPGSMStabilization< Viscosity >::register_parameter().
   {
     SpalartAllmaras<Mu>::register_parameter(param_name, param_pointer);
     this->_stab_helper.register_parameter(param_name, param_pointer);
   }
Member Data Documentation
template<class Viscosity > SpalartAllmarasStabilizationHelper GRINS::SpalartAllmarasStabilizationBase< Viscosity >::_stab_helper protected
Definition at line 59 of file spalart_allmaras_stab_base.h.
The documentation for this class was generated from the following files:
src/physics/include/grins/spalart_allmaras_stab_base.h
src/physics/src/spalart_allmaras_stab_base.C