GRINS-0.7.0: GRINS::PostProcessedQuantities< NumericType > Class Template Reference
GRINS::PostProcessedQuantities< NumericType > Class Template Reference
#include <multiphysics_sys.h>
Public Member Functions
PostProcessedQuantities (const GetPot &input)
virtual ~PostProcessedQuantities ()
virtual void init_context (const libMesh::FEMContext &context)
virtual libMesh::UniquePtr< libMesh::FEMFunctionBase< NumericType > > clone () const
virtual NumericType operator() (const libMesh::FEMContext &context, const libMesh::Point &p, const libMesh::Real time=0.)
virtual void operator() (const libMesh::FEMContext &context, const libMesh::Point &p, const libMesh::Real time, libMesh::DenseVector< NumericType > &output)
virtual NumericType component (const libMesh::FEMContext &context, unsigned int i, const libMesh::Point &p, libMesh::Real time=0.)
unsigned int register_quantity (std::string name)
Register quantity to be postprocessed.
virtual void initialize (MultiphysicsSystem &system, libMesh::EquationSystems &equation_systems)
virtual void update_quantities (libMesh::EquationSystems &equation_systems)
Protected Attributes
std::map< std::string, unsigned int > _quantity_name_index_map
std::map< VariableIndex, unsigned int > _quantity_index_var_map
MultiphysicsSystem * _multiphysics_sys
SharedPtr< AssemblyContext > _multiphysics_context
Private Member Functions
PostProcessedQuantities ()
Detailed Description
template<class NumericType>
class GRINS::PostProcessedQuantities< NumericType >
Definition at line 61 of file multiphysics_sys.h.
Constructor & Destructor Documentation
template<class NumericType > GRINS::PostProcessedQuantities< NumericType >::PostProcessedQuantities (const GetPot & input)
Definition at line 34 of file postprocessed_quantities.C.
     : libMesh::FEMFunctionBase<NumericType>()
   {
     if( input.have_variable("vis-options/output_vars") )
       {
         std::cerr << "================================================================================" << std::endl
                   << "WARNING: Detected input variable 'vis-options/output_vars." << std::endl
                   << "WARNING: THIS IS OUTDATED. output_vars is now input within" << std::endl
                   << "WARNING: each Physics section." << std::endl
                   << "         Erroring out to make you aware." << std::endl
                   << "================================================================================" << std::endl;
         libmesh_error();
       }
     return;
   }
template<class NumericType > GRINS::PostProcessedQuantities< NumericType >::~PostProcessedQuantities () virtual
Definition at line 52 of file postprocessed_quantities.C.
   {
     return;
   }
template<class NumericType> GRINS::PostProcessedQuantities< NumericType >::PostProcessedQuantities () private
Referenced by GRINS::PostProcessedQuantities< NumericType >::clone().
Member Function Documentation
template<class NumericType> virtual libMesh::UniquePtr<libMesh::FEMFunctionBase<NumericType> > GRINS::PostProcessedQuantities< NumericType >::clone () const inline virtual
Definition at line 51 of file postprocessed_quantities.h.
References GRINS::PostProcessedQuantities< NumericType >::PostProcessedQuantities().
     {
       return libMesh::UniquePtr<libMesh::FEMFunctionBase<NumericType> >
         ( new PostProcessedQuantities(*this) );
     }
template<class NumericType > NumericType GRINS::PostProcessedQuantities< NumericType >::component (const libMesh::FEMContext & context, unsigned int i, const libMesh::Point & p, libMesh::Real time = 0.) virtual
Definition at line 116 of file postprocessed_quantities.C.
   {
     // Check if the Elem is the same between the incoming context and the cached one.
     // If not, reinit the cached MultiphysicsSystem context
     if(context.has_elem() && _multiphysics_context->has_elem())
       {
         if( &(context.get_elem()) != &(_multiphysics_context->get_elem()) )
           {
             _multiphysics_context->pre_fe_reinit(*_multiphysics_sys,&context.get_elem());
             _multiphysics_context->elem_fe_reinit();
           }
       }
     else if( !context.has_elem() && _multiphysics_context->has_elem() )
       {
         // Incoming context has NULL elem ==> SCALAR variables
         _multiphysics_context->pre_fe_reinit(*_multiphysics_sys,NULL);
         _multiphysics_context->elem_fe_reinit();
       }
     else if( context.has_elem() && !_multiphysics_context->has_elem() )
       {
         _multiphysics_context->pre_fe_reinit(*_multiphysics_sys,&context.get_elem());
         _multiphysics_context->elem_fe_reinit();
       }
     //else
     /* If has_elem() is false for both contexts, we're still dealing with SCALAR variables
        and therefore don't need to reinit. */
     libMesh::Real value = 0.0;
     // Quantity we want had better be there.
     libmesh_assert(_quantity_index_var_map.find(component) != _quantity_index_var_map.end());
     unsigned int quantity_index = _quantity_index_var_map.find(component)->second;
     _multiphysics_sys->compute_postprocessed_quantity( quantity_index,
                                                        *(this->_multiphysics_context),
                                                        p, value );
     return value;
   }
template<class NumericType > void GRINS::PostProcessedQuantities< NumericType >::init_context (const libMesh::FEMContext & context) virtual
Todo:
I believe this is redundant because it's done in the project_vector call. Double check.
Definition at line 160 of file postprocessed_quantities.C.
   {
     // Make sure we prepare shape functions for our output variables.
     for( typename std::map<VariableIndex,unsigned int>::const_iterator it = _quantity_index_var_map.begin();
          it != _quantity_index_var_map.end(); it++ )
       {
         libMesh::FEBase* elem_fe = NULL;
         context.get_element_fe( it->first, elem_fe );
         elem_fe->get_phi();
         elem_fe->get_dphi();
         elem_fe->get_JxW();
         elem_fe->get_xyz();
         libMesh::FEBase* side_fe = NULL;
         context.get_side_fe( it->first, side_fe );
         side_fe->get_phi();
         side_fe->get_dphi();
         side_fe->get_JxW();
         side_fe->get_xyz();
       }
     // Create the context we'll be using to compute MultiphysicsSystem quantities
     _multiphysics_context.reset( new AssemblyContext( *_multiphysics_sys ) );
     _multiphysics_sys->init_context(*_multiphysics_context);
     return;
   }
template<class NumericType > void GRINS::PostProcessedQuantities< NumericType >::initialize (MultiphysicsSystem & system, libMesh::EquationSystems & equation_systems) virtual
Definition at line 78 of file postprocessed_quantities.C.
   {
     // Only need to initialize if the user requested any output quantities.
     if( !_quantity_name_index_map.empty() )
       {
         // Need to cache the MultiphysicsSystem
         _multiphysics_sys = &system;
         libMesh::System& output_system = equation_systems.add_system<libMesh::System>("interior_output");
         for( std::map<std::string, unsigned int>::const_iterator it = _quantity_name_index_map.begin();
              it != _quantity_name_index_map.end();
              ++it )
           {
             unsigned int var = output_system.add_variable( it->first, libMesh::FIRST );
             _quantity_index_var_map.insert( std::make_pair(var,it->second) );
           }
       }
     return;
   }
template<class NumericType > NumericType GRINS::PostProcessedQuantities< NumericType >::operator() (const libMesh::FEMContext & context, const libMesh::Point & p, const libMesh::Real time = 0.) virtual
Definition at line 201 of file postprocessed_quantities.C.
   {
     libmesh_error();
     return 0.0; //dummy
   }
template<class NumericType > void GRINS::PostProcessedQuantities< NumericType >::operator() (const libMesh::FEMContext & context, const libMesh::Point & p, const libMesh::Real time, libMesh::DenseVector< NumericType > & output) virtual
Definition at line 189 of file postprocessed_quantities.C.
   {
     for( unsigned int i = 0; i != output.size(); i++ )
       {
         output(i) = this->component(context,i,p,time);
       }
     return;
   }
template<class NumericType > unsigned int GRINS::PostProcessedQuantities< NumericType >::register_quantity (std::string name)
Register quantity to be postprocessed.
This method returns an index that will correspond to the name provided. Note that this assumes all quantities are scalar. Thus, if there's a gradient quantity, each component will need to be separately registered.
Definition at line 58 of file postprocessed_quantities.C.
Referenced by GRINS::ElasticMembrane< StressStrainLaw >::register_postprocessing_vars(), GRINS::ElasticCable< StressStrainLaw >::register_postprocessing_vars(), GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::register_postprocessing_vars(), GRINS::HeatTransfer< Conductivity >::register_postprocessing_vars(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::register_postprocessing_vars(), GRINS::IncompressibleNavierStokes< Viscosity >::register_postprocessing_vars(), GRINS::AveragedFan< Viscosity >::register_postprocessing_vars(), GRINS::VelocityPenalty< Viscosity >::register_postprocessing_vars(), and GRINS::ParsedVelocitySource< Viscosity >::register_postprocessing_vars().
   {
     // Check if this quantity has already been registered
     if( _quantity_name_index_map.find(name) != _quantity_name_index_map.end() )
       {
         std::cerr << "Error: trying to add existing quantity: " << name << std::endl;
         libmesh_error();
       }
     /* We add 1 so that the locally cached indices in each of the Physics
        can safely initialize the index to zero. In particular this ensures
        we count starting from 1. */
     unsigned int new_index = _quantity_name_index_map.size()+1;
     _quantity_name_index_map.insert( std::make_pair( name, new_index ) );
     return new_index;
   }
template<class NumericType > void GRINS::PostProcessedQuantities< NumericType >::update_quantities (libMesh::EquationSystems & equation_systems) virtual
Definition at line 102 of file postprocessed_quantities.C.
   {
     // Only do the projection if the user actually added any quantities to compute.
     if( !_quantity_name_index_map.empty() )
       {
         libMesh::System& output_system = equation_systems.get_system<libMesh::System>("interior_output");
         output_system.project_solution(this);
       }
     return;
   }
Member Data Documentation
template<class NumericType> SharedPtr<AssemblyContext> GRINS::PostProcessedQuantities< NumericType >::_multiphysics_context protected
Definition at line 92 of file postprocessed_quantities.h.
template<class NumericType> MultiphysicsSystem* GRINS::PostProcessedQuantities< NumericType >::_multiphysics_sys protected
Definition at line 91 of file postprocessed_quantities.h.
template<class NumericType> std::map<VariableIndex, unsigned int> GRINS::PostProcessedQuantities< NumericType >::_quantity_index_var_map protected
Definition at line 89 of file postprocessed_quantities.h.
template<class NumericType> std::map<std::string, unsigned int> GRINS::PostProcessedQuantities< NumericType >::_quantity_name_index_map protected
Definition at line 88 of file postprocessed_quantities.h.
The documentation for this class was generated from the following files:
src/physics/include/grins/multiphysics_sys.h
src/visualization/include/grins/postprocessed_quantities.h
src/visualization/src/postprocessed_quantities.C