GRINS-0.7.0: GRINSTesting::AirKineticsTestBase Class Reference
GRINSTesting::AirKineticsTestBase Class Reference
Public Member Functions
void init_air_kinetics ()
Public Member Functions inherited from GRINSTesting::KineticsTestBase
template<typename ThermoMixture , typename ThermoEvaluator >
void test_omega_dot_common (ThermoMixture &mixture, NASAThermoTestBase &thermo_funcs, const std::vector< libMesh::Real > &Y, libMesh::Real rel_tol)
Public Member Functions inherited from GRINSTesting::SpeciesTestBase
SpeciesTestBase ()
libMesh::Real molar_mass (unsigned int idx)
libMesh::Real R_species (unsigned int idx)
Public Member Functions inherited from GRINSTesting::AirTestBase
void init_air_test (unsigned int &N2_idx, unsigned int &O2_idx, unsigned int &N_idx, unsigned int &O_idx, unsigned int &NO_idx, std::vector< unsigned int > &active_species)
Additional Inherited Members
Protected Attributes inherited from GRINSTesting::KineticsTestBase
unsigned int _n_reactions
std::vector< libMesh::Real > _Ea_coeffs
std::vector< libMesh::Real > _preexp_coeffs
std::vector< libMesh::Real > _temp_exp_coeffs
std::vector< std::vector< libMesh::Real > > _three_body_coeffs
std::vector< bool > _is_three_body_rxn
std::vector< std::vector< libMesh::Real > > _reactant_stoich_coeffs
std::vector< std::vector< libMesh::Real > > _product_stoich_coeffs
Protected Attributes inherited from GRINSTesting::SpeciesTestBase
unsigned int _N2_idx
unsigned int _O2_idx
unsigned int _O_idx
unsigned int _N_idx
unsigned int _NO_idx
std::vector< unsigned int > _active_species
Detailed Description
Definition at line 82 of file air_5sp.C.
Member Function Documentation
void GRINSTesting::AirKineticsTestBase::init_air_kinetics () inline
Definition at line 87 of file air_5sp.C.
References GRINSTesting::SpeciesTestBase::_active_species, GRINSTesting::KineticsTestBase::_Ea_coeffs, GRINSTesting::KineticsTestBase::_is_three_body_rxn, GRINSTesting::SpeciesTestBase::_N2_idx, GRINSTesting::SpeciesTestBase::_N_idx, GRINSTesting::KineticsTestBase::_n_reactions, GRINSTesting::SpeciesTestBase::_NO_idx, GRINSTesting::SpeciesTestBase::_O2_idx, GRINSTesting::SpeciesTestBase::_O_idx, GRINSTesting::KineticsTestBase::_preexp_coeffs, GRINSTesting::KineticsTestBase::_product_stoich_coeffs, GRINSTesting::KineticsTestBase::_reactant_stoich_coeffs, GRINSTesting::KineticsTestBase::_temp_exp_coeffs, GRINSTesting::KineticsTestBase::_three_body_coeffs, and GRINSTesting::AirTestBase::init_air_test().
Referenced by GRINSTesting::AntiochAirNASA9KineticsTest::setUp(), and GRINSTesting::CanteraAirNASA9KineticsTest::setUp().
     {
       this->init_air_test( _N2_idx, _O2_idx, _N_idx, _O_idx, _NO_idx,
                            _active_species );
       _n_reactions = 5;
       unsigned int n_species = _active_species.size();
       // All in cal/mol
       _Ea_coeffs.resize(_n_reactions);
       _Ea_coeffs[0] = 224801.3;
       _Ea_coeffs[1] = 117881.7;
       _Ea_coeffs[2] = 149943.0;
       _Ea_coeffs[3] = 85269.6;
       _Ea_coeffs[4] = 38526.0;
       // Convert to J/kmol (since this is what GRINS::Constants::R_universal is in)
       for( unsigned int r = 0; r < _n_reactions; r++ )
         _Ea_coeffs[r] *= 1000.0*4.1868;
       // m^3/kmol
       _preexp_coeffs.resize(_n_reactions);
       _preexp_coeffs[0] = 7.e+18;
       _preexp_coeffs[1] = 2.e+18;
       _preexp_coeffs[2] = 5.e+12;
       _preexp_coeffs[3] = 5.7e+9;
       _preexp_coeffs[4] = 8.4e+09;
       _temp_exp_coeffs.resize(_n_reactions);
       _temp_exp_coeffs[0] = -1.6;
       _temp_exp_coeffs[1] = -1.5;
       _temp_exp_coeffs[2] = 0.0;
       _temp_exp_coeffs[3] = 0.42;
       _temp_exp_coeffs[4] = 0.0;
       _three_body_coeffs.resize(_n_reactions);
       _is_three_body_rxn.resize(_n_reactions,false);
       _is_three_body_rxn[0] = true;
       _three_body_coeffs[0].resize(n_species, 1.0);
       _three_body_coeffs[0][_N_idx] = 4.2857;
       _three_body_coeffs[0][_O_idx] = 4.2857;
       _is_three_body_rxn[1] = true;
       _three_body_coeffs[1].resize(n_species, 1.0);
       _three_body_coeffs[1][_N_idx] = 5.0;
       _three_body_coeffs[1][_O_idx] = 5.0;
       _is_three_body_rxn[2] = true;
       _three_body_coeffs[2].resize(n_species, 1.0);
       _three_body_coeffs[2][_N_idx]  = 22.0;
       _three_body_coeffs[2][_O_idx]  = 22.0;
       _three_body_coeffs[2][_NO_idx] = 22.0;
       _reactant_stoich_coeffs.resize(_n_reactions);
       _product_stoich_coeffs.resize(_n_reactions);
       // N_2 + M <=> 2N + M
       _reactant_stoich_coeffs[0].resize(n_species, 0.0);
       _product_stoich_coeffs[0].resize(n_species, 0.0);
       _reactant_stoich_coeffs[0][_N2_idx] = 1.0;
       _product_stoich_coeffs[0][_N_idx] = 2.0;
       // O_2 + M <=> 2O + M
       _reactant_stoich_coeffs[1].resize(n_species, 0.0);
       _product_stoich_coeffs[1].resize(n_species, 0.0);
       _reactant_stoich_coeffs[1][_O2_idx] = 1.0;
       _product_stoich_coeffs[1][_O_idx] = 2.0;
       // NO + M <=> N + O + M
       _reactant_stoich_coeffs[2].resize(n_species, 0.0);
       _product_stoich_coeffs[2].resize(n_species, 0.0);
       _reactant_stoich_coeffs[2][_NO_idx] = 1.0;
       _product_stoich_coeffs[2][_O_idx] = 1.0;
       _product_stoich_coeffs[2][_N_idx] = 1.0;
       // N2 + 0 <=> NO + N
       _reactant_stoich_coeffs[3].resize(n_species, 0.0);
       _product_stoich_coeffs[3].resize(n_species, 0.0);
       _reactant_stoich_coeffs[3][_N2_idx] = 1.0;
       _reactant_stoich_coeffs[3][_O_idx] = 1.0;
       _product_stoich_coeffs[3][_NO_idx] = 1.0;
       _product_stoich_coeffs[3][_N_idx] = 1.0;
       // NO + 0 <=> O2 + N
       _reactant_stoich_coeffs[4].resize(n_species, 0.0);
       _product_stoich_coeffs[4].resize(n_species, 0.0);
       _reactant_stoich_coeffs[4][_NO_idx] = 1.0;
       _reactant_stoich_coeffs[4][_O_idx] = 1.0;
       _product_stoich_coeffs[4][_O2_idx] = 1.0;
       _product_stoich_coeffs[4][_N_idx] = 1.0;
     }
The documentation for this class was generated from the following file:
test/interface/air_5sp.C