GRINS-0.7.0: GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity > Class Template Reference
GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity > Class Template Reference
Physics class for Incompressible Navier-Stokes.
#include <low_mach_navier_stokes_base.h>
Public Member Functions
LowMachNavierStokesBase (const PhysicsName &physics_name, const std::string &core_physics_name, const GetPot &input)
~LowMachNavierStokesBase ()
virtual void init_variables (libMesh::FEMSystem *system)
Initialize variables for this physics.
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Sets velocity variables to be time-evolving.
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
libMesh::Real T (const libMesh::Point &p, const AssemblyContext &c) const
libMesh::Real rho (libMesh::Real T, libMesh::Real p0) const
libMesh::Real d_rho_dT (libMesh::Real T, libMesh::Real p0) const
libMesh::Real get_p0_steady (const AssemblyContext &c, unsigned int qp) const
libMesh::Real get_p0_steady_side (const AssemblyContext &c, unsigned int qp) const
libMesh::Real get_p0_steady (const AssemblyContext &c, const libMesh::Point &p) const
libMesh::Real get_p0_transient (AssemblyContext &c, unsigned int qp) const
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Public Member Functions inherited from GRINS::Physics
Physics (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~Physics ()
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for element interiors.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void damping_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Damping matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_damping_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
ICHandlingBase * get_ic_handler ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
Protected Attributes
libMesh::Number _p0_over_R
Thermodynamic pressure divided by gas constant.
libMesh::Number _p0
libMesh::Number _R
libMesh::Number _T0
unsigned int _dim
Physical dimension of problem.
VelocityFEVariables _flow_vars
PressureFEVariable _press_var
PrimitiveTempFEVariables _temp_vars
libMesh::UniquePtr< ThermoPressureFEVariable > _p0_var
Viscosity _mu
Viscosity object.
SpecificHeat _cp
Specific heat object.
ThermalConductivity _k
Thermal conductivity object.
libMesh::Point _g
Gravity vector.
bool _enable_thermo_press_calc
Flag to enable thermodynamic pressure calculation.
Protected Attributes inherited from GRINS::Physics
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
Private Member Functions
LowMachNavierStokesBase ()
void read_input_options (const GetPot &input)
Read options from GetPot input file.
void register_variables ()
Additional Inherited Members
Static Public Member Functions inherited from GRINS::Physics
static void set_is_axisymmetric (bool is_axisymmetric)
Set whether we should treat the problem as axisymmetric.
static bool is_axisymmetric ()
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Member Functions inherited from GRINS::Physics
libMesh::UniquePtr< libMesh::FEGenericBase< libMesh::Real > > build_new_fe (const libMesh::Elem *elem, const libMesh::FEGenericBase< libMesh::Real > *fe, const libMesh::Point p)
void parse_enabled_subdomains (const GetPot &input, const std::string &physics_name)
Static Protected Attributes inherited from GRINS::Physics
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
static bool _is_axisymmetric = false
Caches whether we are solving an axisymmetric problem or not.
Detailed Description
template<class Viscosity, class SpecificHeat, class ThermalConductivity>
class GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >
Physics class for Incompressible Navier-Stokes.
This physics class implements the classical Incompressible Navier-Stokes equations.
Definition at line 51 of file low_mach_navier_stokes_base.h.
Constructor & Destructor Documentation
template<class Mu , class SH , class TC > GRINS::LowMachNavierStokesBase< Mu, SH, TC >::LowMachNavierStokesBase (const PhysicsName & physics_name, const std::string & core_physics_name, const GetPot & input)
Definition at line 48 of file low_mach_navier_stokes_base.C.
References GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_enable_thermo_press_calc, GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_p0_var, GRINS::PhysicsNaming::low_mach_navier_stokes(), GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::read_input_options(), and GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::register_variables().
     : Physics(physics_name, input),
       _flow_vars(input, core_physics_name),
       _press_var(input,core_physics_name, true /*is_constraint_var*/),
       _temp_vars(input, core_physics_name),
       _mu(input,MaterialsParsing::material_name(input,core_physics_name)),
       _cp(input,MaterialsParsing::material_name(input,core_physics_name)),
       _k(input,MaterialsParsing::material_name(input,core_physics_name))
   {
     _enable_thermo_press_calc = input("Physics/"+PhysicsNaming::low_mach_navier_stokes()+"/enable_thermo_press_calc", false );
     if( _enable_thermo_press_calc )
       _p0_var.reset( new ThermoPressureFEVariable(input,core_physics_name, true /*is_constraint_var*/) );
     this->read_input_options(input);
     this->register_variables();
   }
template<class Viscosity , class SpecificHeat , class ThermalConductivity > GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::~LowMachNavierStokesBase () inline
Definition at line 57 of file low_mach_navier_stokes_base.h.
 {};
template<class Viscosity , class SpecificHeat , class ThermalConductivity > GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokesBase () private
Member Function Documentation
template<class V , class SH , class TC > libMesh::Real GRINS::LowMachNavierStokesBase< V, SH, TC >::d_rho_dT (libMesh::Real T, libMesh::Real p0) const inline
Definition at line 146 of file low_mach_navier_stokes_base.h.
   {
     return -p0/(this->_R*(T*T));
   }
template<class V , class SH , class TC > libMesh::Real GRINS::LowMachNavierStokesBase< V, SH, TC >::get_p0_steady (const AssemblyContext & c, unsigned int qp) const inline
Definition at line 153 of file low_mach_navier_stokes_base.h.
   {
     libMesh::Real p0;
     if( this->_enable_thermo_press_calc )
       {
         p0 = c.interior_value( _p0_var->p0(), qp );
       }
     else
       {
         p0 = _p0;
       }
     return p0;
   }
template<class V , class SH , class TC > libMesh::Real GRINS::LowMachNavierStokesBase< V, SH, TC >::get_p0_steady (const AssemblyContext & c, const libMesh::Point & p) const inline
Definition at line 187 of file low_mach_navier_stokes_base.h.
   {
     libMesh::Real p0;
     if( this->_enable_thermo_press_calc )
       {
         p0 = c.point_value( _p0_var->p0(), p );
       }
     else
       {
         p0 = _p0;
       }
     return p0;
   }
template<class V , class SH , class TC > libMesh::Real GRINS::LowMachNavierStokesBase< V, SH, TC >::get_p0_steady_side (const AssemblyContext & c, unsigned int qp) const inline
Definition at line 170 of file low_mach_navier_stokes_base.h.
   {
     libMesh::Real p0;
     if( this->_enable_thermo_press_calc )
       {
         p0 = c.side_value( _p0_var->p0(), qp );
       }
     else
       {
         p0 = _p0;
       }
     return p0;
   }
template<class V , class SH , class TC > libMesh::Real GRINS::LowMachNavierStokesBase< V, SH, TC >::get_p0_transient (AssemblyContext & c, unsigned int qp) const inline
Definition at line 204 of file low_mach_navier_stokes_base.h.
   {
     libMesh::Real p0;
     if( this->_enable_thermo_press_calc )
       {
         p0 = c.fixed_interior_value( _p0_var->p0(), qp );
       }
     else
       {
         p0 = _p0;
       }
     return p0;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokesBase< Mu, SH, TC >::init_context (AssemblyContext & context) virtual
Initialize context for added physics variables.
Reimplemented from GRINS::Physics.
Reimplemented in GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, and GRINS::LowMachNavierStokesStabilizationBase< Viscosity, SpecificHeat, ThermalConductivity >.
Definition at line 157 of file low_mach_navier_stokes_base.C.
Referenced by GRINS::LowMachNavierStokesStabilizationBase< Viscosity, SpecificHeat, ThermalConductivity >::init_context(), and GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::init_context().
   {
     // We should prerequest all the data
     // we will need to build the linear system
     // or evaluate a quantity of interest.
     context.get_element_fe(_flow_vars.u())->get_JxW();
     context.get_element_fe(_flow_vars.u())->get_phi();
     context.get_element_fe(_flow_vars.u())->get_dphi();
     context.get_element_fe(_flow_vars.u())->get_xyz();
     context.get_element_fe(_temp_vars.T())->get_JxW();
     context.get_element_fe(_temp_vars.T())->get_phi();
     context.get_element_fe(_temp_vars.T())->get_dphi();
     context.get_element_fe(_temp_vars.T())->get_xyz();
     context.get_element_fe(_press_var.p())->get_phi();
     context.get_element_fe(_press_var.p())->get_xyz();
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokesBase< Mu, SH, TC >::init_variables (libMesh::FEMSystem * system) virtual
Initialize variables for this physics.
Implements GRINS::Physics.
Definition at line 119 of file low_mach_navier_stokes_base.C.
   {
     // Get libMesh to assign an index for each variable
     this->_dim = system->get_mesh().mesh_dimension();
     this->_flow_vars.init(system);
     this->_press_var.init(system);
     this->_temp_vars.init(system);
     /* If we need to compute the thermodynamic pressure, we force this to be a first
        order scalar variable. */
     if( _enable_thermo_press_calc )
       _p0_var->init(system);
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokesBase< Mu, SH, TC >::read_input_options (const GetPot & input) private
Read options from GetPot input file.
Definition at line 82 of file low_mach_navier_stokes_base.C.
References GRINS::PhysicsNaming::low_mach_navier_stokes(), and GRINS::MaterialsParsing::read_property().
Referenced by GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokesBase().
   {
     // Read thermodynamic state info
     MaterialsParsing::read_property( input,
                                      "Physics/"+PhysicsNaming::low_mach_navier_stokes()+"/p0",
                                      "ThermodynamicPressure",
                                      PhysicsNaming::low_mach_navier_stokes(),
                                      (*this),
                                      _p0 );
     MaterialsParsing::read_property( input,
                                      "Physics/"+PhysicsNaming::low_mach_navier_stokes()+"/T0",
                                      "ReferenceTemperature",
                                      PhysicsNaming::low_mach_navier_stokes(),
                                      (*this),
                                      _T0 );
     MaterialsParsing::read_property( input,
                                      "Physics/"+PhysicsNaming::low_mach_navier_stokes()+"/R",
                                      "GasConstant",
                                      PhysicsNaming::low_mach_navier_stokes(),
                                      (*this),
                                      _R );
     _p0_over_R = _p0/_R;
     // Read gravity vector
     unsigned int g_dim = input.vector_variable_size("Physics/"+PhysicsNaming::low_mach_navier_stokes()+"/g");
     _g(0) = input("Physics/"+PhysicsNaming::low_mach_navier_stokes()+"/g", 0.0, 0 );
     _g(1) = input("Physics/"+PhysicsNaming::low_mach_navier_stokes()+"/g", 0.0, 1 );
     if( g_dim == 3)
       _g(2) = input("Physics/"+PhysicsNaming::low_mach_navier_stokes()+"/g", 0.0, 2 );
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokesBase< Mu, SH, TC >::register_parameter (const std::string & param_name, libMesh::ParameterMultiAccessor< libMesh::Number > & param_pointer) const virtual
Each subclass will register its copy of an independent.
Reimplemented from GRINS::ParameterUser.
Definition at line 180 of file low_mach_navier_stokes_base.C.
References GRINS::ParameterUser::register_parameter().
   {
     ParameterUser::register_parameter(param_name, param_pointer);
     _mu.register_parameter(param_name, param_pointer);
     _cp.register_parameter(param_name, param_pointer);
     _k.register_parameter(param_name, param_pointer);
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokesBase< Mu, SH, TC >::register_variables () private
Definition at line 68 of file low_mach_navier_stokes_base.C.
References GRINS::GRINSPrivate::VariableWarehouse::check_and_register_variable(), GRINS::VariablesParsing::pressure_section(), GRINS::VariablesParsing::temperature_section(), GRINS::VariablesParsing::thermo_pressure_section(), and GRINS::VariablesParsing::velocity_section().
Referenced by GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokesBase().
   {
     GRINSPrivate::VariableWarehouse::check_and_register_variable(VariablesParsing::pressure_section(),
                                                                  this->_press_var);
     GRINSPrivate::VariableWarehouse::check_and_register_variable(VariablesParsing::velocity_section(),
                                                                  this->_flow_vars);
     GRINSPrivate::VariableWarehouse::check_and_register_variable(VariablesParsing::temperature_section(),
                                                                  this->_temp_vars);
     if( this->_enable_thermo_press_calc )
       GRINSPrivate::VariableWarehouse::check_and_register_variable(VariablesParsing::thermo_pressure_section(),
                                                                    *(this->_p0_var));
   }
template<class V , class SH , class TC > libMesh::Real GRINS::LowMachNavierStokesBase< V, SH, TC >::rho (libMesh::Real T, libMesh::Real p0) const inline
Definition at line 139 of file low_mach_navier_stokes_base.h.
   {
     return p0/(this->_R*T);
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokesBase< Mu, SH, TC >::set_time_evolving_vars (libMesh::FEMSystem * system) virtual
Sets velocity variables to be time-evolving.
Reimplemented from GRINS::Physics.
Definition at line 137 of file low_mach_navier_stokes_base.C.
   {
     const unsigned int dim = system->get_mesh().mesh_dimension();
     system->time_evolving(_flow_vars.u());
     system->time_evolving(_flow_vars.v());
     if (dim == 3)
       system->time_evolving(_flow_vars.w());
     system->time_evolving(_temp_vars.T());
     system->time_evolving(_press_var.p());
     if( _enable_thermo_press_calc )
       system->time_evolving(_p0_var->p0());
     return;
   }
template<class V , class SH , class TC > libMesh::Real GRINS::LowMachNavierStokesBase< V, SH, TC >::T (const libMesh::Point & p, const AssemblyContext & c) const inline
Definition at line 132 of file low_mach_navier_stokes_base.h.
   {
     return c.point_value(_temp_vars.T(),p);
   }
Member Data Documentation
template<class Viscosity , class SpecificHeat , class ThermalConductivity > SpecificHeat GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_cp protected
Specific heat object.
Definition at line 108 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > unsigned int GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_dim protected
Physical dimension of problem.
Definition at line 96 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > bool GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_enable_thermo_press_calc protected
Flag to enable thermodynamic pressure calculation.
Definition at line 117 of file low_mach_navier_stokes_base.h.
Referenced by GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokesBase().
template<class Viscosity , class SpecificHeat , class ThermalConductivity > VelocityFEVariables GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_flow_vars protected
Definition at line 98 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > libMesh::Point GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_g protected
Gravity vector.
Definition at line 114 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > ThermalConductivity GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_k protected
Thermal conductivity object.
Definition at line 111 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > Viscosity GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_mu protected
Viscosity object.
Definition at line 105 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > libMesh::Number GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_p0 protected
Definition at line 93 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > libMesh::Number GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_p0_over_R protected
Thermodynamic pressure divided by gas constant.
Definition at line 91 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > libMesh::UniquePtr<ThermoPressureFEVariable> GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_p0_var protected
Definition at line 102 of file low_mach_navier_stokes_base.h.
Referenced by GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokesBase().
template<class Viscosity , class SpecificHeat , class ThermalConductivity > PressureFEVariable GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_press_var protected
Definition at line 99 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > libMesh::Number GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_R protected
Definition at line 93 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > libMesh::Number GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_T0 protected
Definition at line 93 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > PrimitiveTempFEVariables GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_temp_vars protected
Definition at line 100 of file low_mach_navier_stokes_base.h.
The documentation for this class was generated from the following files:
src/physics/include/grins/low_mach_navier_stokes_base.h
src/physics/src/low_mach_navier_stokes_base.C