GRINS-0.7.0: GRINS::HookesLaw Class Reference
GRINS::HookesLaw Class Reference
Elasticity tensor for Hooke's law.
#include <hookes_law.h>
Public Member Functions
HookesLaw (const GetPot &input)
HookesLaw (const GetPot &input, const std::string &material)
virtual ~HookesLaw ()
Public Member Functions inherited from GRINS::StressStrainLaw< HookesLaw >
StressStrainLaw ()
virtual ~StressStrainLaw ()
void compute_stress (unsigned int dim, const libMesh::TensorValue< libMesh::Real > &g_contra, const libMesh::TensorValue< libMesh::Real > &g_cov, const libMesh::TensorValue< libMesh::Real > &G_contra, const libMesh::TensorValue< libMesh::Real > &G_cov, libMesh::TensorValue< libMesh::Real > &stress)
void compute_stress_and_elasticity (unsigned int dim, const libMesh::TensorValue< libMesh::Real > &g_contra, const libMesh::TensorValue< libMesh::Real > &g_cov, const libMesh::TensorValue< libMesh::Real > &G_contra, const libMesh::TensorValue< libMesh::Real > &G_cov, libMesh::TensorValue< libMesh::Real > &stress, ElasticityTensor &C)
libMesh::Real compute_33_stress (const libMesh::TensorValue< libMesh::Real > &g_contra, const libMesh::TensorValue< libMesh::Real > &g_cov, const libMesh::TensorValue< libMesh::Real > &G_contra, const libMesh::TensorValue< libMesh::Real > &G_cov)
This is primarily a helper function for the plane stress cases.
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Private Member Functions
HookesLaw ()
void read_input_options (const GetPot &input)
Parse properties from input.
void compute_stress_imp (unsigned int dim, const libMesh::TensorValue< libMesh::Real > &g_contra, const libMesh::TensorValue< libMesh::Real > &g_cov, const libMesh::TensorValue< libMesh::Real > &G_contra, const libMesh::TensorValue< libMesh::Real > &G_cov, libMesh::TensorValue< libMesh::Real > &stress)
void compute_stress_and_elasticity_imp (unsigned int dim, const libMesh::TensorValue< libMesh::Real > &g_contra, const libMesh::TensorValue< libMesh::Real > &g_cov, const libMesh::TensorValue< libMesh::Real > &G_contra, const libMesh::TensorValue< libMesh::Real > &G_cov, libMesh::TensorValue< libMesh::Real > &stress, ElasticityTensor &C)
libMesh::Real compute_33_stress_imp (const libMesh::TensorValue< libMesh::Real > &g_contra, const libMesh::TensorValue< libMesh::Real > &g_cov, const libMesh::TensorValue< libMesh::Real > &G_contra, const libMesh::TensorValue< libMesh::Real > &G_cov)
Private Attributes
ElasticityTensor _C
libMesh::Real _lambda
Lam\'{e} constant.
libMesh::Real _mu
Lam\'{e} constant.
Friends
class StressStrainLaw< HookesLaw >
Additional Inherited Members
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Detailed Description
Elasticity tensor for Hooke's law.
Uses Lam\'{e} constants, but can parse Young's modulus and Poisson's ratio if desired. By default, is constructed for Cartesian coordinate systems. If working with curvilinear coordinate systems, the user should call the set_deformation method before calling operator().
Definition at line 46 of file hookes_law.h.
Constructor & Destructor Documentation
GRINS::HookesLaw::HookesLaw (const GetPot & input)
Definition at line 38 of file hookes_law.C.
References grins_warning, and read_input_options().
     : StressStrainLaw<HookesLaw>(),
       ParameterUser("HookesLaw"),
       _C(),
       _lambda(0.0),
       _mu(0.0)
   {
     // Warning about this constructor being deprecated
     {
       std::string warning = "WARNING: Use of this constructor is DEPRECATED.\n";
       warning += "         Please update to use constructor with input material name.\n";
       grins_warning(warning);
     }
     this->read_input_options(input);
     return;
   }
GRINS::HookesLaw::HookesLaw (const GetPot & input, const std::string & material)
Todo:
we'll need a special accessor to give ParameterUser access to these
Todo:
we'll need a special accessor to give ParameterUser access to these
Definition at line 57 of file hookes_law.C.
References _lambda, _mu, GRINS::MaterialsParsing::dep_input_warning(), GRINS::MaterialsParsing::duplicate_input_test(), grins_warning, and GRINS::ParameterUser::set_parameter().
     : StressStrainLaw<HookesLaw>(),
       ParameterUser("HookesLaw"),
       _C(),
       _lambda(0.0),
       _mu(0.0)
   {
     MaterialsParsing::duplicate_input_test(input,
                                            "Materials/"+material+"/StressStrainLaw/HookesLaw/lambda",
                                            "Physics/HookesLaw/lambda");
     MaterialsParsing::duplicate_input_test(input,
                                            "Materials/"+material+"/StressStrainLaw/HookesLaw/mu",
                                            "Physics/HookesLaw/mu");
     MaterialsParsing::duplicate_input_test(input,
                                            "Materials/"+material+"/StressStrainLaw/HookesLaw/E",
                                            "Physics/HookesLaw/E");
     MaterialsParsing::duplicate_input_test(input,
                                            "Materials/"+material+"/StressStrainLaw/HookesLaw/nu",
                                            "Physics/HookesLaw/nu");
     // Parse the new version
     if( input.have_variable("Materials/"+material+"/StressStrainLaw/HookesLaw/lambda") &&
         input.have_variable("Materials/"+material+"/StressStrainLaw/HookesLaw/mu") )
       {
         this->set_parameter
           (_lambda, input, "Materials/"+material+"/StressStrainLaw/HookesLaw/lambda", 0.0);
         this->set_parameter
           (_mu, input, "Materials/"+material+"/StressStrainLaw/HookesLaw/mu", 0.0);
       }
     else if( input.have_variable("Materials/"+material+"/StressStrainLaw/HookesLaw/E") &&
              input.have_variable("Materials/"+material+"/StressStrainLaw/HookesLaw/nu") )
       {
         libMesh::Real E  = input("Materials/"+material+"/StressStrainLaw/HookesLaw/E", 0.0);
         libMesh::Real nu = input("Materials/"+material+"/StressStrainLaw/HookesLaw/nu", 0.0);
         _lambda = nu*E/( (1+nu)*(1-2*nu) );
         _mu = E/(2*(1+nu));
       }
     // Parse the old version
     else if( input.have_variable("Physics/HookesLaw/lambda") &&
              input.have_variable("Physics/HookesLaw/mu") )
       {
         MaterialsParsing::dep_input_warning( "Physics/HookesLaw/lambda",
                                              "StressStrainLaw/HookesLaw/lambda" );
         MaterialsParsing::dep_input_warning( "Physics/HookesLaw/mu",
                                              "StressStrainLaw/HookesLaw/mu" );
         this->set_parameter
           (_lambda, input, "Physics/HookesLaw/lambda", 0.0);
         this->set_parameter
           (_mu, input, "Physics/HookesLaw/mu", 0.0);
       }
     else if( input.have_variable("Physics/HookesLaw/E") &&
               input.have_variable("Physics/HookesLaw/nu") )
       {
         MaterialsParsing::dep_input_warning( "Physics/HookesLaw/E",
                                              "StressStrainLaw/HookesLaw/E" );
         MaterialsParsing::dep_input_warning( "Physics/HookesLaw/nu",
                                              "StressStrainLaw/HookesLaw/nu" );
         libMesh::Real E  = input("Physics/HookesLaw/E", 0.0);
         libMesh::Real nu = input("Physics/HookesLaw/nu", 0.0);
         _lambda = nu*E/( (1+nu)*(1-2*nu) );
         _mu = E/(2*(1+nu));
       }
     else
       {
         libmesh_error_msg("ERROR: Could not find consistent HookesLaw input!");
       }
     // mu should be positive
     if( _mu <= 0.0 )
       libmesh_error_msg("ERROR: Detected non-positive shear modulus!");
     // Technically, lambda can be negative, but it's weird. Let's warn about it.
     if( _lambda <= 0.0 )
       {
         std::string warning = "WARNING: Detected non-positive Lame parameter";
         grins_warning(warning);
       }
   }
GRINS::HookesLaw::~HookesLaw () virtual
Definition at line 140 of file hookes_law.C.
   {
     return;
   }
GRINS::HookesLaw::HookesLaw () private
Member Function Documentation
libMesh::Real GRINS::HookesLaw::compute_33_stress_imp (const libMesh::TensorValue< libMesh::Real > & g_contra, const libMesh::TensorValue< libMesh::Real > & g_cov, const libMesh::TensorValue< libMesh::Real > & G_contra, const libMesh::TensorValue< libMesh::Real > & G_cov) private
Definition at line 226 of file hookes_law.C.
References _lambda, and _mu.
   {
     libMesh::Real sigma_33 = 0.0;
     for( unsigned int k = 0; k < 3; k++ )
       {
         for( unsigned int l = 0; l < 3; l++ )
           {
             libMesh::Real strain_kl = 0.5*(G_cov(k,l) - g_cov(k,l));
             libMesh::Real C = _lambda*g_contra(2,2)*g_contra(k,l) +
               _mu*(g_contra(2,k)*g_contra(2,l) + g_contra(2,l)*g_contra(2,k));
             sigma_33 += C*strain_kl;
           }
       }
     return sigma_33;
   }
void GRINS::HookesLaw::compute_stress_and_elasticity_imp (unsigned int dim, const libMesh::TensorValue< libMesh::Real > & g_contra, const libMesh::TensorValue< libMesh::Real > & g_cov, const libMesh::TensorValue< libMesh::Real > & G_contra, const libMesh::TensorValue< libMesh::Real > & G_cov, libMesh::TensorValue< libMesh::Real > & stress, ElasticityTensor & C) private
Definition at line 211 of file hookes_law.C.
References _C, and compute_stress_imp().
   {
     this->compute_stress_imp(dim,g_contra,g_cov,G_contra,G_cov,stress);
     C = _C;
     return;
   }
void GRINS::HookesLaw::compute_stress_imp (unsigned int dim, const libMesh::TensorValue< libMesh::Real > & g_contra, const libMesh::TensorValue< libMesh::Real > & g_cov, const libMesh::TensorValue< libMesh::Real > & G_contra, const libMesh::TensorValue< libMesh::Real > & G_cov, libMesh::TensorValue< libMesh::Real > & stress) private
Definition at line 180 of file hookes_law.C.
References _C, _lambda, and _mu.
Referenced by compute_stress_and_elasticity_imp().
   {
     stress.zero();
     for( unsigned int i = 0; i < dim; i++ )
       {
         for( unsigned int j = 0; j < dim; j++ )
           {
             for( unsigned int k = 0; k < dim; k++ )
               {
                 for( unsigned int l = 0; l < dim; l++ )
                   {
                     libMesh::Real strain_kl = 0.5*(G_cov(k,l) - g_cov(k,l));
                     _C(i,j,k,l) = _lambda*g_contra(i,j)*g_contra(k,l) +
                                   _mu*(g_contra(i,k)*g_contra(j,l) + g_contra(i,l)*g_contra(j,k));
                     stress(i,j) += _C(i,j,k,l)*strain_kl;
                   }
               }
           }
       }
     return;
   }
void GRINS::HookesLaw::read_input_options (const GetPot & input) private
Parse properties from input.
Definition at line 145 of file hookes_law.C.
References _lambda, _mu, and GRINS::ParameterUser::set_parameter().
Referenced by HookesLaw().
   {
     // We'd better have either Lam\'{e} constants or E and nu
     if( ( !input.have_variable("Physics/HookesLaw/lambda") ||
           !input.have_variable("Physics/HookesLaw/mu") ) &&
         ( !input.have_variable("Physics/HookesLaw/E") ||
           !input.have_variable("Physics/HookesLaw/nu") ) )
       {
         std::cerr << "Error: Must specify either Lame constants lambda and mu or" << std::endl
                   << "       Young's modulus and Poisson's ratio." << std::endl;
         libmesh_error();
       }
     if( input.have_variable("Physics/HookesLaw/lambda") )
       this->set_parameter
         (_lambda, input, "Physics/HookesLaw/lambda", 0.0);
     if( input.have_variable("Physics/HookesLaw/mu") )
       this->set_parameter
         (_mu, input, "Physics/HookesLaw/mu", 0.0);
     if( input.have_variable("Physics/HookesLaw/E") &&
         input.have_variable("Physics/HookesLaw/nu") )
       {
         // FIXME - we'll need a special accessor to give parameter
         // access to these
         libMesh::Real E  = input("Physics/HookesLaw/E", 0.0);
         libMesh::Real nu = input("Physics/HookesLaw/nu", 0.0);
         _lambda = nu*E/( (1+nu)*(1-2*nu) );
         _mu = E/(2*(1+nu));
       }
     return;
   }
Friends And Related Function Documentation
friend class StressStrainLaw< HookesLaw > friend
Definition at line 58 of file hookes_law.h.
Member Data Documentation
ElasticityTensor GRINS::HookesLaw::_C private
Definition at line 87 of file hookes_law.h.
Referenced by compute_stress_and_elasticity_imp(), and compute_stress_imp().
libMesh::Real GRINS::HookesLaw::_lambda private
Lam\'{e} constant.
Definition at line 90 of file hookes_law.h.
Referenced by compute_33_stress_imp(), compute_stress_imp(), HookesLaw(), and read_input_options().
libMesh::Real GRINS::HookesLaw::_mu private
Lam\'{e} constant.
Definition at line 93 of file hookes_law.h.
Referenced by compute_33_stress_imp(), compute_stress_imp(), HookesLaw(), and read_input_options().
The documentation for this class was generated from the following files:
src/properties/include/grins/hookes_law.h
src/properties/src/hookes_law.C