GRINS-0.7.0: GRINS::ViscosityBase Class Reference
GRINS::ViscosityBase Class Reference
Base class for viscosity models.
#include <viscosity_base.h>
Public Member Functions
ViscosityBase ()
virtual ~ViscosityBase ()
Protected Member Functions
void check_input_consistency (const GetPot &input, const std::string &material) const
void old_mu_warning () const
Detailed Description
Base class for viscosity models.
Any commonality for all viscosity models goes here.
Definition at line 39 of file viscosity_base.h.
Constructor & Destructor Documentation
GRINS::ViscosityBase::ViscosityBase () inline
Definition at line 42 of file viscosity_base.h.
 {};
virtual GRINS::ViscosityBase::~ViscosityBase () inline virtual
Definition at line 43 of file viscosity_base.h.
 {};
Member Function Documentation
void GRINS::ViscosityBase::check_input_consistency (const GetPot & input, const std::string & material) const protected
Definition at line 37 of file viscosity_base.C.
References GRINS::MaterialsParsing::duplicate_input_test().
Referenced by GRINS::ConstantViscosity::ConstantViscosity(), and GRINS::ParsedViscosity::ParsedViscosity().
   {
     // We can't have both the materials version and the old versions
     MaterialsParsing::duplicate_input_test(input,
                                            "Materials/"+material+"/Viscosity/value",
                                            "Materials/Viscosity/mu" );
     // If the material section exists, but not the variable, this is an error
     if( input.have_section("Materials/"+material+"/Viscosity") &&
         !input.have_variable("Materials/"+material+"/Viscosity/value") )
       {
         libmesh_error_msg("Error: Found section Materials/"+material+"/Viscosity, but not variable value.");
       }
     return;
   }
void GRINS::ViscosityBase::old_mu_warning () const protected
Definition at line 54 of file viscosity_base.C.
References grins_warning.
Referenced by GRINS::ConstantViscosity::ConstantViscosity(), and GRINS::ParsedViscosity::ParsedViscosity().
   {
     std::string warning = "WARNING: Use of Materials/Viscosity/mu is DEPRECATED.\n";
     warning += "         Please update to use  Materials/MATERIAL_NAME/Viscosity/value,\n";
     warning += "         where MATERIAL_NAME is given by Physics/PHYSICS_CLASS/material.\n";
     grins_warning(warning);
     return;
   }
The documentation for this class was generated from the following files:
src/properties/include/grins/viscosity_base.h
src/properties/src/viscosity_base.C