GRINS-0.7.0: GRINS::AveragedTurbineBase< Viscosity > Class Template Reference
GRINS::AveragedTurbineBase< Viscosity > Class Template Reference
#include <averaged_turbine_base.h>
Public Member Functions
AveragedTurbineBase (const std::string &physics_name, const GetPot &input)
~AveragedTurbineBase ()
virtual void init_variables (libMesh::FEMSystem *system)
Initialization of variables.
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Sets turbine_speed and velocity variables to be time-evolving.
bool compute_force (const libMesh::Point &point, const libMesh::Real time, const libMesh::NumberVectorValue &U, libMesh::Number s, libMesh::NumberVectorValue &U_B_1, libMesh::NumberVectorValue &F, libMesh::NumberTensorValue *dFdU=NULL, libMesh::NumberVectorValue *dFds=NULL)
VariableIndex fan_speed_var () const
Public Member Functions inherited from GRINS::IncompressibleNavierStokesBase< Viscosity >
IncompressibleNavierStokesBase (const std::string &my_physics_name, const std::string &core_physics_name, const GetPot &input)
~IncompressibleNavierStokesBase ()
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
libMesh::Real get_viscosity_value (AssemblyContext &context, unsigned int qp) const
Public Member Functions inherited from GRINS::Physics
Physics (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~Physics ()
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for element interiors.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void damping_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Damping matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_damping_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
ICHandlingBase * get_ic_handler ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
Protected Attributes
libMesh::ParsedFunction< libMesh::Number > base_velocity_function
libMesh::ParsedFunction< libMesh::Number > local_vertical_function
libMesh::ParsedFunction< libMesh::Number > lift_function
libMesh::ParsedFunction< libMesh::Number > drag_function
libMesh::ParsedFunction< libMesh::Number > torque_function
libMesh::Number moment_of_inertia
libMesh::Number initial_speed
libMesh::ParsedFunction< libMesh::Number > chord_function
libMesh::ParsedFunction< libMesh::Number > area_swept_function
libMesh::ParsedFunction< libMesh::Number > aoa_function
VariableIndex _fan_speed_var
std::string _fan_speed_var_name
Protected Attributes inherited from GRINS::IncompressibleNavierStokesBase< Viscosity >
unsigned int _dim
Physical dimension of problem.
VelocityFEVariables _flow_vars
PressureFEVariable _press_var
libMesh::Number _rho
Material parameters, read from input.
Viscosity _mu
Viscosity object.
Protected Attributes inherited from GRINS::Physics
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
Private Member Functions
void read_input_options (const GetPot &input)
Read options from GetPot input file.
AveragedTurbineBase ()
Additional Inherited Members
Static Public Member Functions inherited from GRINS::Physics
static void set_is_axisymmetric (bool is_axisymmetric)
Set whether we should treat the problem as axisymmetric.
static bool is_axisymmetric ()
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Member Functions inherited from GRINS::Physics
libMesh::UniquePtr< libMesh::FEGenericBase< libMesh::Real > > build_new_fe (const libMesh::Elem *elem, const libMesh::FEGenericBase< libMesh::Real > *fe, const libMesh::Point p)
void parse_enabled_subdomains (const GetPot &input, const std::string &physics_name)
Static Protected Attributes inherited from GRINS::Physics
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
static bool _is_axisymmetric = false
Caches whether we are solving an axisymmetric problem or not.
Detailed Description
template<class Viscosity>
class GRINS::AveragedTurbineBase< Viscosity >
Definition at line 45 of file averaged_turbine_base.h.
Constructor & Destructor Documentation
template<class Mu > GRINS::AveragedTurbineBase< Mu >::AveragedTurbineBase (const std::string & physics_name, const GetPot & input)
Definition at line 36 of file averaged_turbine_base.C.
References GRINS::AveragedTurbineBase< Viscosity >::read_input_options().
     : IncompressibleNavierStokesBase<Mu>(physics_name,
                                          PhysicsNaming::incompressible_navier_stokes(), /* "core" Physics name */
                                          input),
       base_velocity_function(""),
       local_vertical_function(""),
       lift_function(""),
       drag_function(""),
       torque_function(""),
       chord_function(""),
       area_swept_function(""),
       aoa_function("")
   {
     this->read_input_options(input);
   }
template<class Viscosity > GRINS::AveragedTurbineBase< Viscosity >::~AveragedTurbineBase () inline
Definition at line 51 of file averaged_turbine_base.h.
 {};
template<class Viscosity > GRINS::AveragedTurbineBase< Viscosity >::AveragedTurbineBase () private
Member Function Documentation
template<class Mu > bool GRINS::AveragedTurbineBase< Mu >::compute_force (const libMesh::Point & point, const libMesh::Real time, const libMesh::NumberVectorValue & U, libMesh::Number s, libMesh::NumberVectorValue & U_B_1, libMesh::NumberVectorValue & F, libMesh::NumberTensorValue * dFdU = NULL, libMesh::NumberVectorValue * dFds = NULL)
Definition at line 157 of file averaged_turbine_base.C.
   {
     // Find base velocity of moving fan at this point
     libMesh::DenseVector<libMesh::Number> output_vec(3);
     base_velocity_function(point, time, output_vec);
     U_B_1(0) = output_vec(0);
     U_B_1(1) = output_vec(1);
     U_B_1(2) = output_vec(2);
     const libMesh::NumberVectorValue U_B = U_B_1 * s;
     const libMesh::Number U_B_size = U_B.size();
     // If there's no base velocity there's no fan
     if (!U_B_size)
       return false;
     // Normal in fan velocity direction
     const libMesh::NumberVectorValue N_B =
       libMesh::NumberVectorValue(U_B/U_B_size);
     local_vertical_function(point, time, output_vec);
     // Normal in fan vertical direction
     const libMesh::NumberVectorValue N_V(output_vec(0),
                                          output_vec(1),
                                          output_vec(2));
     // Normal in radial direction (or opposite radial direction,
     // for fans turning clockwise!)
     const libMesh::NumberVectorValue N_R = N_B.cross(N_V);
     // Fan-wing-plane component of local relative velocity
     const libMesh::NumberVectorValue U_P = U - (U*N_R)*N_R - U_B;
     const libMesh::Number U_P_size = U_P.size();
     // If there's no flow in the fan's frame of reference, there's no
     // lift or drag.  FIXME - should we account for drag in the
     // out-of-plane direction?
     if (!U_P_size)
       return false;
     // Direction opposing drag
     const libMesh::NumberVectorValue N_drag =
       libMesh::NumberVectorValue(-U_P/U_P_size);
     // Direction opposing lift
     const libMesh::NumberVectorValue N_lift = N_drag.cross(N_R);
     // "Forward" velocity
     const libMesh::Number u_fwd = -(U_P * N_B);
     // "Upward" velocity
     const libMesh::Number u_up = U_P * N_V;
     // If there's no forward or upward velocity we should have already
     // returned false
     libmesh_assert (u_up || u_fwd);
     // Angle WRT fan velocity direction
     const libMesh::Number part_angle = std::atan2(u_up, u_fwd);
     // Angle WRT fan chord
     const libMesh::Number angle = part_angle +
       aoa_function(point, time);
     const libMesh::Number C_lift  = lift_function(point, angle);
     const libMesh::Number C_drag  = drag_function(point, angle);
     const libMesh::Number chord = chord_function(point, time);
     const libMesh::Number area  = area_swept_function(point, time);
     const libMesh::Number v_sq = U_P*U_P;
     const libMesh::Number LDfactor = 0.5 * this->_rho * v_sq * chord / area;
     const libMesh::Number lift = C_lift * LDfactor;
     const libMesh::Number drag = C_drag * LDfactor;
     // Force
     F = lift * N_lift + drag * N_drag;
     if (dFdU)
       {
         const libMesh::NumberVectorValue LDderivfactor =
           (N_lift*C_lift+N_drag*C_drag) *
           this->_rho * chord / area;
         const libMesh::Number sfactor = -(U_P*U_B_1);
         (*dFds) = LDderivfactor * sfactor;
         for (unsigned int i=0; i != 3; ++i)
           for (unsigned int j=0; j != 3; ++j)
             (*dFdU)(i,j) = LDderivfactor(i) * U_P(j);
       }
     return true;
   }
template<class Viscosity > VariableIndex GRINS::AveragedTurbineBase< Viscosity >::fan_speed_var () const inline
Definition at line 72 of file averaged_turbine_base.h.
References GRINS::AveragedTurbineBase< Viscosity >::_fan_speed_var.
 { return _fan_speed_var; }
template<class Mu > void GRINS::AveragedTurbineBase< Mu >::init_variables (libMesh::FEMSystem * system) virtual
Initialization of variables.
Add turbine_speed variable to system; call base function to initialize Navier-Stokes variables.
Reimplemented from GRINS::IncompressibleNavierStokesBase< Viscosity >.
Definition at line 53 of file averaged_turbine_base.C.
References GRINS::IncompressibleNavierStokesBase< Viscosity >::init_variables().
   {
     this->_fan_speed_var = system->add_variable(_fan_speed_var_name,
                                                 libMesh::FIRST,
                                                 libMesh::SCALAR);
     IncompressibleNavierStokesBase<Mu>::init_variables(system);
   }
template<class Mu > void GRINS::AveragedTurbineBase< Mu >::read_input_options (const GetPot & input) private
Read options from GetPot input file.
Definition at line 72 of file averaged_turbine_base.C.
References GRINS::PhysicsNaming::averaged_turbine(), and GRINS::fan_speed_var_name_default.
Referenced by GRINS::AveragedTurbineBase< Viscosity >::AveragedTurbineBase().
   {
     this->set_parameter(base_velocity_function, input,
                         "Physics/"+PhysicsNaming::averaged_turbine()+"/base_velocity",
                         this->zero_vector_function);
     if (base_velocity_function.expression() == this->zero_vector_function)
       libmesh_error_msg("Error! Zero AveragedTurbine specified!" <<
                         std::endl);
     this->set_parameter(local_vertical_function, input,
                         "Physics/"+PhysicsNaming::averaged_turbine()+"/local_vertical",
                         this->zero_vector_function);
     if (local_vertical_function.expression() == this->zero_vector_function)
       libmesh_error_msg("Error! Zero LocalVertical specified!" <<
                         std::endl);
     this->set_parameter(lift_function, input,
                         "Physics/"+PhysicsNaming::averaged_turbine()+"/lift",
                         "0");
     if (lift_function.expression() == "0")
       std::cout << "Warning! Zero lift function specified!" << std::endl;
     this->set_parameter(drag_function, input,
                         "Physics/"+PhysicsNaming::averaged_turbine()+"/drag",
                         "0");
     if (drag_function.expression() == "0")
       std::cout << "Warning! Zero drag function specified!" << std::endl;
     this->set_parameter(chord_function, input,
                         "Physics/"+PhysicsNaming::averaged_turbine()+"/chord_length",
                         "0");
     if (chord_function.expression() == "0")
       libmesh_error_msg("Error! Zero chord function specified!" <<
                         std::endl);
     this->set_parameter(area_swept_function, input,
                         "Physics/"+PhysicsNaming::averaged_turbine()+"/area_swept",
                         "0");
     if (area_swept_function.expression() == "0")
       libmesh_error_msg("Error! Zero area_swept_function specified!" <<
                         std::endl);
     this->set_parameter(aoa_function, input,
                         "Physics/"+PhysicsNaming::averaged_turbine()+"/angle_of_attack",
                         "00000");
     if (aoa_function.expression() == "00000")
       libmesh_error_msg("Error! No angle-of-attack specified!" <<
                         std::endl);
     this->set_parameter(torque_function, input,
                         "Physics/"+PhysicsNaming::averaged_turbine()+"/torque",
                         "0");
     if (torque_function.expression() == "0")
       std::cout << "Warning! Zero torque function specified!" << std::endl;
     this->set_parameter
       (this->moment_of_inertia, input,
        "Physics/"+PhysicsNaming::averaged_turbine()+"/moment_of_inertia",
        libMesh::Number(0));
     if (!moment_of_inertia)
       libmesh_error_msg(
         "Error! Zero AveragedTurbine moment of inertia specified!" <<
         std::endl);
     this->set_parameter
       (this->initial_speed, input,
        "Physics/"+PhysicsNaming::averaged_turbine()+"/initial_speed",
        libMesh::Number(0));
     this->_fan_speed_var_name = input("Physics/VariableNames/fan_speed",
                                       fan_speed_var_name_default);
   }
template<class Mu > void GRINS::AveragedTurbineBase< Mu >::set_time_evolving_vars (libMesh::FEMSystem * system) virtual
Sets turbine_speed and velocity variables to be time-evolving.
Reimplemented from GRINS::IncompressibleNavierStokesBase< Viscosity >.
Definition at line 63 of file averaged_turbine_base.C.
References GRINS::IncompressibleNavierStokesBase< Viscosity >::set_time_evolving_vars().
   {
     system->time_evolving(this->fan_speed_var());
     IncompressibleNavierStokesBase<Mu>::set_time_evolving_vars(system);
   }
Member Data Documentation
template<class Viscosity > VariableIndex GRINS::AveragedTurbineBase< Viscosity >::_fan_speed_var protected
Definition at line 135 of file averaged_turbine_base.h.
Referenced by GRINS::AveragedTurbineBase< Viscosity >::fan_speed_var().
template<class Viscosity > std::string GRINS::AveragedTurbineBase< Viscosity >::_fan_speed_var_name protected
Definition at line 137 of file averaged_turbine_base.h.
template<class Viscosity > libMesh::ParsedFunction<libMesh::Number> GRINS::AveragedTurbineBase< Viscosity >::aoa_function protected
Definition at line 133 of file averaged_turbine_base.h.
template<class Viscosity > libMesh::ParsedFunction<libMesh::Number> GRINS::AveragedTurbineBase< Viscosity >::area_swept_function protected
Definition at line 128 of file averaged_turbine_base.h.
template<class Viscosity > libMesh::ParsedFunction<libMesh::Number> GRINS::AveragedTurbineBase< Viscosity >::base_velocity_function protected
Definition at line 83 of file averaged_turbine_base.h.
template<class Viscosity > libMesh::ParsedFunction<libMesh::Number> GRINS::AveragedTurbineBase< Viscosity >::chord_function protected
Definition at line 123 of file averaged_turbine_base.h.
template<class Viscosity > libMesh::ParsedFunction<libMesh::Number> GRINS::AveragedTurbineBase< Viscosity >::drag_function protected
Definition at line 95 of file averaged_turbine_base.h.
template<class Viscosity > libMesh::Number GRINS::AveragedTurbineBase< Viscosity >::initial_speed protected
Definition at line 119 of file averaged_turbine_base.h.
template<class Viscosity > libMesh::ParsedFunction<libMesh::Number> GRINS::AveragedTurbineBase< Viscosity >::lift_function protected
Definition at line 94 of file averaged_turbine_base.h.
template<class Viscosity > libMesh::ParsedFunction<libMesh::Number> GRINS::AveragedTurbineBase< Viscosity >::local_vertical_function protected
Definition at line 87 of file averaged_turbine_base.h.
template<class Viscosity > libMesh::Number GRINS::AveragedTurbineBase< Viscosity >::moment_of_inertia protected
Definition at line 115 of file averaged_turbine_base.h.
template<class Viscosity > libMesh::ParsedFunction<libMesh::Number> GRINS::AveragedTurbineBase< Viscosity >::torque_function protected
Definition at line 111 of file averaged_turbine_base.h.
The documentation for this class was generated from the following files:
src/physics/include/grins/averaged_turbine_base.h
src/physics/src/averaged_turbine_base.C