GRINS-0.6.0: GRINS::CanteraKinetics Class Reference
GRINS::CanteraKinetics Class Reference
#include <cantera_kinetics.h>
Public Member Functions
CanteraKinetics (CanteraMixture &mixture)
~CanteraKinetics ()
void omega_dot (const CachedValues &cache, unsigned int qp, std::vector< libMesh::Real > &omega_dot) const
void omega_dot_TPY (const libMesh::Real T, const libMesh::Real P, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &omega_dot) const
void omega_dot_TRY (const libMesh::Real &T, const libMesh::Real rho, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &omega_dot) const
Protected Attributes
Cantera::IdealGasMix & _cantera_gas
Private Member Functions
CanteraKinetics ()
Detailed Description
Definition at line 54 of file cantera_kinetics.h.
Constructor & Destructor Documentation
GRINS::CanteraKinetics::CanteraKinetics (CanteraMixture & mixture)
Definition at line 48 of file cantera_kinetics.C.
     :  _cantera_gas( mixture.get_chemistry() )
   {
     return;
   }
GRINS::CanteraKinetics::~CanteraKinetics ()
Definition at line 54 of file cantera_kinetics.C.
   {
     return;
   }
GRINS::CanteraKinetics::CanteraKinetics () private
Member Function Documentation
void GRINS::CanteraKinetics::omega_dot (const CachedValues & cache, unsigned int qp, std::vector< libMesh::Real > & omega_dot) const
Definition at line 59 of file cantera_kinetics.C.
References GRINS::CachedValues::get_cached_values(), GRINS::CachedValues::get_cached_vector_values(), GRINS::Cache::MASS_FRACTIONS, omega_dot_TPY(), GRINS::Cache::TEMPERATURE, and GRINS::Cache::THERMO_PRESSURE.
Referenced by main(), and GRINS::CanteraEvaluator::omega_dot().
   {
     const libMesh::Real T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     const libMesh::Real P = cache.get_cached_values(Cache::THERMO_PRESSURE)[qp];
     const std::vector<libMesh::Real>& Y = cache.get_cached_vector_values(Cache::MASS_FRACTIONS)[qp];
     this->omega_dot_TPY( T, P, Y, omega_dot );
     return;
   }
void GRINS::CanteraKinetics::omega_dot_TPY (const libMesh::Real T, const libMesh::Real P, const std::vector< libMesh::Real > & mass_fractions, std::vector< libMesh::Real > & omega_dot) const
Todo:
Need to make sure this will work in a threaded environment. Not sure if we will get thread lock here or not.
Definition at line 72 of file cantera_kinetics.C.
References _cantera_gas.
Referenced by main(), and omega_dot().
   {
     libmesh_assert_equal_to( mass_fractions.size(), omega_dot.size() );
     libmesh_assert_equal_to( mass_fractions.size(), _cantera_gas.nSpecies() );
     libmesh_assert_greater(T,0.0);
     libmesh_assert_greater(P,0.0);
     {
       libMesh::Threads::spin_mutex::scoped_lock lock(cantera_mutex);
       try
         {
           _cantera_gas.setState_TPY(T, P, &mass_fractions[0]);
           _cantera_gas.getNetProductionRates(&omega_dot[0]);
         }
       catch(Cantera::CanteraError)
         {
           Cantera::showErrors(std::cerr);
           libmesh_error();
         }
     }
 #ifdef DEBUG
     for( unsigned int s = 0; s < omega_dot.size(); s++ )
       {
         if( libMesh::libmesh_isnan(omega_dot[s]) )
           {
             std::cout << "T = " << T << std::endl
                       << "P = " << P << std::endl;
             for( unsigned int s = 0; s < omega_dot.size(); s++ )
               {
                 std::cout << "Y[" << s << "] = " << mass_fractions[s] << std::endl;
               }
             for( unsigned int s = 0; s < omega_dot.size(); s++ )
               {
                 std::cout << "omega_dot[" << s << "] = " << omega_dot[s] << std::endl;
               }
             libmesh_error();
           }
       }
 #endif
     for( unsigned int s = 0; s < omega_dot.size(); s++ )
       {
         // convert [kmol/m^3-s] to [kg/m^3-s]
         omega_dot[s] *= this->_cantera_gas.molecularWeight(s);
       }
     return;
   }
void GRINS::CanteraKinetics::omega_dot_TRY (const libMesh::Real & T, const libMesh::Real rho, const std::vector< libMesh::Real > & mass_fractions, std::vector< libMesh::Real > & omega_dot) const
Todo:
Need to make sure this will work in a threaded environment. Not sure if we will get thread lock here or not.
Definition at line 128 of file cantera_kinetics.C.
References _cantera_gas.
Referenced by GRINS::CanteraEvaluator::omega_dot().
   {
     libmesh_assert_equal_to( mass_fractions.size(), omega_dot.size() );
     libmesh_assert_equal_to( mass_fractions.size(), _cantera_gas.nSpecies() );
     libmesh_assert_greater(T,0.0);
     libmesh_assert_greater(rho,0.0);
     {
       libMesh::Threads::spin_mutex::scoped_lock lock(cantera_mutex);
       try
         {
           _cantera_gas.setState_TRY(T, rho, &mass_fractions[0]);
           _cantera_gas.getNetProductionRates(&omega_dot[0]);
         }
       catch(Cantera::CanteraError)
         {
           Cantera::showErrors(std::cerr);
           libmesh_error();
         }
     }
     for( unsigned int s = 0; s < omega_dot.size(); s++ )
       {
         // convert [kmol/m^3-s] to [kg/m^3-s]
         omega_dot[s] *= this->_cantera_gas.molecularWeight(s);
       }
     return;
   }
Member Data Documentation
Cantera::IdealGasMix& GRINS::CanteraKinetics::_cantera_gas protected
Definition at line 74 of file cantera_kinetics.h.
Referenced by omega_dot_TPY(), and omega_dot_TRY().
The documentation for this class was generated from the following files:
src/properties/include/grins/cantera_kinetics.h
src/properties/src/cantera_kinetics.C