GRINS-0.6.0: AxiConCylBCFactory Class Reference
AxiConCylBCFactory Class Reference
Public Member Functions
AxiConCylBCFactory ()
~AxiConCylBCFactory ()
std::multimap< GRINS::PhysicsName, GRINS::DBCContainer > build_dirichlet ()
Builds all required libMesh::DirichletBoundary objects and adds them to DofMap.
virtual std::map< GRINS::PhysicsName, GRINS::NBCContainer > build_neumann (libMesh::EquationSystems &equation_system)
Builds all Neumann boundary condition function objects needed.
Detailed Description
Definition at line 58 of file test_axi_ns_con_cyl_flow.C.
Constructor & Destructor Documentation
AxiConCylBCFactory::AxiConCylBCFactory () inline
Definition at line 62 of file test_axi_ns_con_cyl_flow.C.
     : GRINS::BoundaryConditionsFactory()
   { return; };
AxiConCylBCFactory::~AxiConCylBCFactory () inline
Definition at line 66 of file test_axi_ns_con_cyl_flow.C.
 {return;};
Member Function Documentation
std::multimap< GRINS::PhysicsName, GRINS::DBCContainer > AxiConCylBCFactory::build_dirichlet () virtual
Builds all required libMesh::DirichletBoundary objects and adds them to DofMap.
This needs to be done for all the physics in the simulation, for all "special" dirichlet boundary conditions.
Reimplemented from GRINS::BoundaryConditionsFactory.
Definition at line 170 of file test_axi_ns_con_cyl_flow.C.
References GRINS::DBCContainer::add_bc_id(), GRINS::DBCContainer::add_var_name(), GRINS::incompressible_navier_stokes, and GRINS::DBCContainer::set_func().
 {
   GRINS::DBCContainer cont;
   cont.add_var_name( "z_vel" );
   cont.add_bc_id( 0 );
   cont.add_bc_id( 2 );
   std::tr1::shared_ptr<libMesh::FunctionBase<libMesh::Number> > vel_func( new GRINS::ConcentricCylinderProfile );
   cont.set_func( vel_func );
   GRINS::DBCContainer cont2;
   cont2.add_var_name( "z_vel" );
   cont2.add_bc_id( 0 );
   cont2.add_bc_id( 2 );
   std::tr1::shared_ptr<libMesh::FunctionBase<libMesh::Number> >
     vel_func2( new libMesh::ZeroFunction<libMesh::Number> );
   cont2.set_func( vel_func2 );
   std::multimap< GRINS::PhysicsName, GRINS::DBCContainer > mymap;
   mymap.insert( std::pair<GRINS::PhysicsName, GRINS::DBCContainer >(GRINS::incompressible_navier_stokes,  cont) );
   mymap.insert( std::pair<GRINS::PhysicsName, GRINS::DBCContainer >(GRINS::incompressible_navier_stokes,  cont2) );
   return mymap;
 }
std::map< PhysicsName, NBCContainer > GRINS::BoundaryConditionsFactory::build_neumann (libMesh::EquationSystems & equation_system) virtual inherited
Builds all Neumann boundary condition function objects needed.
This is done for each physics. Thus, the container returned maps between each physics and set of Neumann boundary conditions for that physics.
Reimplemented in GRINS::ThermallyDrivenFlowTestBCFactory.
Definition at line 47 of file bc_factory.C.
   {
     return std::map< PhysicsName, NBCContainer >();
   }
The documentation for this class was generated from the following file:
test/test_axi_ns_con_cyl_flow.C