GRINS-0.6.0: GRINS::LowMachNavierStokesStabilizationHelper Class Reference
GRINS::LowMachNavierStokesStabilizationHelper Class Reference
#include <low_mach_navier_stokes_stab_helper.h>
Public Member Functions
LowMachNavierStokesStabilizationHelper (const std::string &helper_name, const GetPot &input)
~LowMachNavierStokesStabilizationHelper ()
libMesh::Real compute_tau_energy (AssemblyContext &c, unsigned int qp, libMesh::RealGradient &g, libMesh::RealTensor &G, libMesh::Real rho, libMesh::Gradient U, libMesh::Real k, libMesh::Real cp, bool is_steady) const
void init (libMesh::FEMSystem &system)
libMesh::Real compute_tau_continuity (libMesh::Real tau_C, libMesh::RealGradient &g) const
void compute_tau_continuity_and_derivs (libMesh::Real tau_M, libMesh::Real d_tau_M_d_rho, libMesh::Gradient d_tau_M_d_U, libMesh::RealGradient &g, libMesh::Real &tau_C, libMesh::Real &d_tau_C_d_rho, libMesh::Gradient &d_tau_C_d_U) const
libMesh::Real compute_tau_momentum (AssemblyContext &c, unsigned int qp, libMesh::RealGradient &g, libMesh::RealTensor &G, libMesh::Real rho, libMesh::Gradient U, libMesh::Real mu, bool is_steady) const
void compute_tau_momentum_and_derivs (AssemblyContext &c, unsigned int qp, libMesh::RealGradient &g, libMesh::RealTensor &G, libMesh::Real rho, libMesh::Gradient U, libMesh::Real T, libMesh::Real &tau_M, libMesh::Real &d_tau_M_d_rho, libMesh::Gradient &d_tau_M_d_U, bool is_steady) const
libMesh::Real compute_tau (AssemblyContext &c, unsigned int qp, libMesh::Real mat_prop_sq, libMesh::RealGradient &g, libMesh::RealTensor &G, libMesh::Real rho, libMesh::Gradient U, bool is_steady) const
void compute_tau_and_derivs (AssemblyContext &c, unsigned int qp, libMesh::Real mat_prop_sq, libMesh::RealGradient &g, libMesh::RealTensor &G, libMesh::Real rho, libMesh::Gradient U, libMesh::Real &tau, libMesh::Real &d_tau_d_rho, libMesh::Gradient &d_tau_d_U, bool is_steady) const
libMesh::Real compute_res_continuity (AssemblyContext &context, unsigned int qp) const
void compute_res_continuity_and_derivs (AssemblyContext &context, unsigned int qp, libMesh::Real &res_C, libMesh::Tensor &d_res_C_dgradU) const
libMesh::RealGradient compute_res_momentum_steady (AssemblyContext &context, unsigned int qp, const libMesh::Real rho, const libMesh::Real mu) const
void compute_res_momentum_steady_and_derivs (AssemblyContext &context, unsigned int qp, const libMesh::Real rho, const libMesh::Real mu, libMesh::Gradient &res_M, libMesh::Tensor &d_res_M_dgradp, libMesh::Tensor &d_res_M_dU, libMesh::Gradient &d_res_Muvw_dgraduvw, libMesh::Tensor &d_res_Muvw_dhessuvw) const
libMesh::RealGradient compute_res_momentum_transient (AssemblyContext &context, unsigned int qp, const libMesh::Real rho) const
void compute_res_momentum_transient_and_derivs (AssemblyContext &context, unsigned int qp, const libMesh::Real rho, libMesh::RealGradient &res_M, libMesh::Real &d_res_Muvw_duvw) const
libMesh::RealGradient UdotGradU (libMesh::Gradient &U, libMesh::Gradient &grad_u, libMesh::Gradient &grad_v) const
libMesh::RealGradient UdotGradU (libMesh::Gradient &U, libMesh::Gradient &grad_u, libMesh::Gradient &grad_v, libMesh::Gradient &grad_w) const
libMesh::RealGradient div_GradU (libMesh::RealTensor &hess_u, libMesh::RealTensor &hess_v) const
libMesh::RealGradient div_GradU (libMesh::RealTensor &hess_u, libMesh::RealTensor &hess_v, libMesh::RealTensor &hess_w) const
libMesh::RealGradient div_GradU_T (libMesh::RealTensor &hess_u, libMesh::RealTensor &hess_v) const
libMesh::RealGradient div_GradU_T (libMesh::RealTensor &hess_u, libMesh::RealTensor &hess_v, libMesh::RealTensor &hess_w) const
libMesh::RealGradient div_divU_I (libMesh::RealTensor &hess_u, libMesh::RealTensor &hess_v) const
libMesh::RealGradient div_divU_I (libMesh::RealTensor &hess_u, libMesh::RealTensor &hess_v, libMesh::RealTensor &hess_w) const
libMesh::RealGradient compute_g (libMesh::FEBase *fe, AssemblyContext &c, unsigned int qp) const
libMesh::RealTensor compute_G (libMesh::FEBase *fe, AssemblyContext &c, unsigned int qp) const
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiPointer< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Attributes
libMesh::Real _C
libMesh::Real _tau_factor
PrimitiveFlowVariables _flow_vars
Detailed Description
Definition at line 33 of file low_mach_navier_stokes_stab_helper.h.
Constructor & Destructor Documentation
GRINS::LowMachNavierStokesStabilizationHelper::LowMachNavierStokesStabilizationHelper (const std::string & helper_name, const GetPot & input)
Definition at line 33 of file low_mach_navier_stokes_stab_helper.C.
     : IncompressibleNavierStokesStabilizationHelper(helper_name, input)
   {
     return;
   }
GRINS::LowMachNavierStokesStabilizationHelper::~LowMachNavierStokesStabilizationHelper ()
Definition at line 40 of file low_mach_navier_stokes_stab_helper.C.
   {
     return;
   }
Member Function Documentation
libMesh::RealGradient GRINS::StabilizationHelper::compute_g (libMesh::FEBase * fe, AssemblyContext & c, unsigned int qp) const inherited
Todo:
Should we inline this?
Definition at line 47 of file stab_helper.C.
   {
     libMesh::RealGradient g( fe->get_dxidx()[qp] + fe->get_detadx()[qp],
                              fe->get_dxidy()[qp] + fe->get_detady()[qp] );
     if( c.get_dim() == 3 )
       {
         g(0) += fe->get_dzetadx()[qp];
         g(1) += fe->get_dzetady()[qp];
         g(2) = fe->get_dxidz()[qp] + fe->get_detadz()[qp] + fe->get_dzetadz()[qp];
       }
     return g;
   }
libMesh::RealTensor GRINS::StabilizationHelper::compute_G (libMesh::FEBase * fe, AssemblyContext & c, unsigned int qp) const inherited
Todo:
Should we inline this?
Definition at line 64 of file stab_helper.C.
   {
     libMesh::Real dxidx = fe->get_dxidx()[qp];
     libMesh::Real dxidy = fe->get_dxidy()[qp];
     libMesh::Real detadx = fe->get_detadx()[qp];
     libMesh::Real detady = fe->get_detady()[qp];
     libMesh::RealTensor G( dxidx*dxidx + detadx*detadx,
                            dxidx*dxidy + detadx*detady,
                            0.0,
                            dxidy*dxidx + detady*detadx,
                            dxidy*dxidy + detady*detady,
                            0.0 );
     if( c.get_dim() == 3 )
       {
         libMesh::Real dxidz = fe->get_dxidz()[qp];
         libMesh::Real detadz = fe->get_detadz()[qp];
         libMesh::Real dzetadx = fe->get_dzetadx()[qp];
         libMesh::Real dzetady = fe->get_dzetady()[qp];
         libMesh::Real dzetadz = fe->get_dzetadz()[qp];
         G(0,0) += dzetadx*dzetadx;
         G(0,1) += dzetadx*dzetady;
         G(0,2) = dxidx*dxidz + detadx*detadz + dzetadx*dzetadz;
         G(1,0) += dzetady*dzetadx;
         G(1,1) += dzetady*dzetady;
         G(1,2) = dxidy*dxidz + detady*detadz + dzetady*dzetadz;
         G(2,0) = dxidz*dxidx + detadz*detadx + dzetadz*dzetadx;
         G(2,1) = dxidz*dxidy + detadz*detady + dzetadz*dzetady;
         G(2,2) = dxidz*dxidz + detadz*detadz + dzetadz*dzetadz;
       }
     return G;
   }
libMesh::Real GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_continuity (AssemblyContext & context, unsigned int qp) const inherited
Definition at line 137 of file inc_navier_stokes_stab_helper.C.
References GRINS::IncompressibleNavierStokesStabilizationHelper::_flow_vars, GRINS::PrimitiveFlowVariables::u_var(), GRINS::PrimitiveFlowVariables::v_var(), and GRINS::PrimitiveFlowVariables::w_var().
   {
     libMesh::RealGradient grad_u, grad_v;
     grad_u = context.fixed_interior_gradient(this->_flow_vars.u_var(), qp);
     grad_v = context.fixed_interior_gradient(this->_flow_vars.v_var(), qp);
     libMesh::Real divU = grad_u(0) + grad_v(1);
     if( context.get_system().get_mesh().mesh_dimension() == 3 )
       {
         divU += (context.fixed_interior_gradient(this->_flow_vars.w_var(), qp))(2);
       }
     return divU;
   }
void GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_continuity_and_derivs (AssemblyContext & context, unsigned int qp, libMesh::Real & res_C, libMesh::Tensor & d_res_C_dgradU) const inherited
Definition at line 156 of file inc_navier_stokes_stab_helper.C.
   {
     libMesh::RealGradient grad_u, grad_v;
     grad_u = context.fixed_interior_gradient(this->_flow_vars.u_var(), qp);
     grad_v = context.fixed_interior_gradient(this->_flow_vars.v_var(), qp);
     libMesh::Real divU = grad_u(0) + grad_v(1);
     d_res_C_dgradU = 0;
     d_res_C_dgradU(0,0) = 1;
     d_res_C_dgradU(1,1) = 1;
     if( context.get_system().get_mesh().mesh_dimension() == 3 )
       {
         divU += (context.fixed_interior_gradient(this->_flow_vars.w_var(), qp))(2);
         d_res_C_dgradU(2,2) = 1;
       }
     res_C = divU;
   }
libMesh::RealGradient GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady (AssemblyContext & context, unsigned int qp, const libMesh::Real rho, const libMesh::Real mu) const inherited
Definition at line 181 of file inc_navier_stokes_stab_helper.C.
References GRINS::IncompressibleNavierStokesStabilizationHelper::_flow_vars, GRINS::IncompressibleNavierStokesStabilizationHelper::div_GradU(), GRINS::PrimitiveFlowVariables::p_var(), GRINS::PrimitiveFlowVariables::u_var(), GRINS::IncompressibleNavierStokesStabilizationHelper::UdotGradU(), GRINS::PrimitiveFlowVariables::v_var(), and GRINS::PrimitiveFlowVariables::w_var().
   {
     libMesh::RealGradient U( context.fixed_interior_value(this->_flow_vars.u_var(), qp),
                              context.fixed_interior_value(this->_flow_vars.v_var(), qp) );
     if(context.get_system().get_mesh().mesh_dimension() == 3)
       U(2) = context.fixed_interior_value(this->_flow_vars.w_var(), qp);
     libMesh::RealGradient grad_p = context.fixed_interior_gradient(this->_flow_vars.p_var(), qp);
     libMesh::RealGradient grad_u = context.fixed_interior_gradient(this->_flow_vars.u_var(), qp);
     libMesh::RealGradient grad_v = context.fixed_interior_gradient(this->_flow_vars.v_var(), qp);
     libMesh::RealTensor hess_u = context.fixed_interior_hessian(this->_flow_vars.u_var(), qp);
     libMesh::RealTensor hess_v = context.fixed_interior_hessian(this->_flow_vars.v_var(), qp);
     libMesh::RealGradient rhoUdotGradU;
     libMesh::RealGradient divGradU;
     if( context.get_system().get_mesh().mesh_dimension() < 3 )
       {
         rhoUdotGradU = rho*this->UdotGradU( U, grad_u, grad_v );
         divGradU  = this->div_GradU( hess_u, hess_v );
       }
     else
       {
         libMesh::RealGradient grad_w = context.fixed_interior_gradient(this->_flow_vars.w_var(), qp);
         libMesh::RealTensor hess_w = context.fixed_interior_hessian(this->_flow_vars.w_var(), qp);
         rhoUdotGradU = rho*this->UdotGradU( U, grad_u, grad_v, grad_w );
         divGradU  = this->div_GradU( hess_u, hess_v, hess_w );
       }
     return rhoUdotGradU + grad_p - mu*divGradU;
   }
void GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady_and_derivs (AssemblyContext & context, unsigned int qp, const libMesh::Real rho, const libMesh::Real mu, libMesh::Gradient & res_M, libMesh::Tensor & d_res_M_dgradp, libMesh::Tensor & d_res_M_dU, libMesh::Gradient & d_res_Muvw_dgraduvw, libMesh::Tensor & d_res_Muvw_dhessuvw) const inherited
Definition at line 219 of file inc_navier_stokes_stab_helper.C.
   {
     libMesh::RealGradient U( context.fixed_interior_value(this->_flow_vars.u_var(), qp),
                              context.fixed_interior_value(this->_flow_vars.v_var(), qp) );
     if(context.get_system().get_mesh().mesh_dimension() == 3)
       U(2) = context.fixed_interior_value(this->_flow_vars.w_var(), qp);
     libMesh::RealGradient grad_p = context.fixed_interior_gradient(this->_flow_vars.p_var(), qp);
     libMesh::RealGradient grad_u = context.fixed_interior_gradient(this->_flow_vars.u_var(), qp);
     libMesh::RealGradient grad_v = context.fixed_interior_gradient(this->_flow_vars.v_var(), qp);
     libMesh::RealTensor hess_u = context.fixed_interior_hessian(this->_flow_vars.u_var(), qp);
     libMesh::RealTensor hess_v = context.fixed_interior_hessian(this->_flow_vars.v_var(), qp);
     libMesh::RealGradient rhoUdotGradU;
     libMesh::RealGradient divGradU;
     if( context.get_system().get_mesh().mesh_dimension() < 3 )
       {
         rhoUdotGradU = rho*this->UdotGradU( U, grad_u, grad_v );
         divGradU  = this->div_GradU( hess_u, hess_v );
       }
     else
       {
         libMesh::RealGradient grad_w = context.fixed_interior_gradient(this->_flow_vars.w_var(), qp);
         libMesh::RealTensor hess_w = context.fixed_interior_hessian(this->_flow_vars.w_var(), qp);
         rhoUdotGradU = rho*this->UdotGradU( U, grad_u, grad_v, grad_w );
         divGradU  = this->div_GradU( hess_u, hess_v, hess_w );
         d_res_M_dU(0,2) = rho * grad_u(2);
         d_res_M_dU(1,2) = rho * grad_v(2);
         d_res_Muvw_dgraduvw(2) = rho * U(2);
         d_res_M_dgradp(2,2) = 1;
         d_res_Muvw_dhessuvw(2,2) = mu;
         d_res_M_dU(2,0) = rho * grad_w(0);
         d_res_M_dU(2,1) = rho * grad_w(1);
         d_res_M_dU(2,2) = rho * grad_w(2);
       }
     res_M = rhoUdotGradU + grad_p - mu*divGradU;
     d_res_M_dU(0,0) = rho * grad_u(0);
     d_res_M_dU(0,1) = rho * grad_u(1);
     d_res_M_dU(1,0) = rho * grad_v(0);
     d_res_M_dU(1,1) = rho * grad_v(1);
     d_res_Muvw_dgraduvw(0) = rho * U(0);
     d_res_Muvw_dgraduvw(1) = rho * U(1);
     d_res_M_dgradp(0,0) = 1;
     d_res_M_dgradp(1,1) = 1;
     d_res_Muvw_dhessuvw(0,0) = mu;
     d_res_Muvw_dhessuvw(1,1) = mu;
   }
libMesh::RealGradient GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_transient (AssemblyContext & context, unsigned int qp, const libMesh::Real rho) const inherited
Definition at line 288 of file inc_navier_stokes_stab_helper.C.
References GRINS::IncompressibleNavierStokesStabilizationHelper::_flow_vars, GRINS::PrimitiveFlowVariables::u_var(), and GRINS::PrimitiveFlowVariables::v_var().
   {
     libMesh::RealGradient u_dot;
     context.interior_rate(this->_flow_vars.u_var(), qp, u_dot(0));
     context.interior_rate(this->_flow_vars.v_var(), qp, u_dot(1));
     if(context.get_system().get_mesh().mesh_dimension() == 3)
       context.interior_rate(this->_flow_vars.w_var(), qp, u_dot(2));
     return rho*u_dot;
   }
void GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_transient_and_derivs (AssemblyContext & context, unsigned int qp, const libMesh::Real rho, libMesh::RealGradient & res_M, libMesh::Real & d_res_Muvw_duvw) const inherited
Definition at line 301 of file inc_navier_stokes_stab_helper.C.
   {
     libMesh::RealGradient u_dot;
     context.interior_rate(this->_flow_vars.u_var(), qp, u_dot(0));
     context.interior_rate(this->_flow_vars.v_var(), qp, u_dot(1));
     if(context.get_system().get_mesh().mesh_dimension() == 3)
       context.interior_rate(this->_flow_vars.w_var(), qp, u_dot(2));
     res_M = rho*u_dot;
     d_res_Muvw_duvw = rho;
   }
libMesh::Real GRINS::IncompressibleNavierStokesStabilizationHelper::compute_tau (AssemblyContext & c, unsigned int qp, libMesh::Real mat_prop_sq, libMesh::RealGradient & g, libMesh::RealTensor & G, libMesh::Real rho, libMesh::Gradient U, bool is_steady) const inline inherited
Definition at line 238 of file inc_navier_stokes_stab_helper.h.
References GRINS::IncompressibleNavierStokesStabilizationHelper::_C, and GRINS::IncompressibleNavierStokesStabilizationHelper::_tau_factor.
Referenced by compute_tau_energy(), and GRINS::IncompressibleNavierStokesStabilizationHelper::compute_tau_momentum().
   {
     libMesh::Real tau = (rho*U)*(G*(rho*U)) + this->_C*mat_prop_sq*G.contract(G);
     if(!is_steady)
       tau += (2.0*rho/c.get_deltat_value())*(2.0*rho/c.get_deltat_value());
     return this->_tau_factor/std::sqrt(tau);
   }
void GRINS::IncompressibleNavierStokesStabilizationHelper::compute_tau_and_derivs (AssemblyContext & c, unsigned int qp, libMesh::Real mat_prop_sq, libMesh::RealGradient & g, libMesh::RealTensor & G, libMesh::Real rho, libMesh::Gradient U, libMesh::Real & tau, libMesh::Real & d_tau_d_rho, libMesh::Gradient & d_tau_d_U, bool is_steady) const inline inherited
Definition at line 258 of file inc_navier_stokes_stab_helper.h.
   {
     libMesh::Gradient rhoU = rho*U;
     libMesh::Gradient GrhoU = G*rhoU;
     libMesh::Real rhoUGrhoU = rhoU * GrhoU;
     libMesh::Real GG = G.contract(G);
     tau = rhoUGrhoU + this->_C*mat_prop_sq*GG;
     d_tau_d_rho = rhoUGrhoU*2/rho;
     d_tau_d_U = 2*rho*GrhoU;
     if(!is_steady)
       {
         libMesh::Real two_rho_over_dt = 2*rho/c.get_deltat_value();
         tau += two_rho_over_dt * two_rho_over_dt;
         d_tau_d_rho += 4*two_rho_over_dt/c.get_deltat_value();
       }
     // But what we've computed so far isn't tau; we need
     // tau = _tau_factor/ sqrt(our_tau)
     libMesh::Real root_oldtau = std::sqrt(tau);
     libMesh::Real d_tau_d_oldtau = -this->_tau_factor / (tau*root_oldtau) / 2;
     d_tau_d_rho         = d_tau_d_oldtau * d_tau_d_rho;
     d_tau_d_U           = d_tau_d_oldtau * d_tau_d_U;
     tau = this->_tau_factor / root_oldtau;
   }
libMesh::Real GRINS::IncompressibleNavierStokesStabilizationHelper::compute_tau_continuity (libMesh::Real tau_C, libMesh::RealGradient & g) const inline inherited
Definition at line 181 of file inc_navier_stokes_stab_helper.h.
References GRINS::IncompressibleNavierStokesStabilizationHelper::_tau_factor.
   {
     return this->_tau_factor/(tau_M*(g*g));
   }
void GRINS::IncompressibleNavierStokesStabilizationHelper::compute_tau_continuity_and_derivs (libMesh::Real tau_M, libMesh::Real d_tau_M_d_rho, libMesh::Gradient d_tau_M_d_U, libMesh::RealGradient & g, libMesh::Real & tau_C, libMesh::Real & d_tau_C_d_rho, libMesh::Gradient & d_tau_C_d_U) const inline inherited
Definition at line 189 of file inc_navier_stokes_stab_helper.h.
   {
     tau_C = this->_tau_factor/(tau_M*(g*g));
     libMesh::Real d_tau_C_d_tau_M = -tau_C/tau_M;
     d_tau_C_d_rho = d_tau_C_d_tau_M * d_tau_M_d_rho;
     d_tau_C_d_U = d_tau_C_d_tau_M * d_tau_M_d_U;
   }
libMesh::Real GRINS::LowMachNavierStokesStabilizationHelper::compute_tau_energy (AssemblyContext & c, unsigned int qp, libMesh::RealGradient & g, libMesh::RealTensor & G, libMesh::Real rho, libMesh::Gradient U, libMesh::Real k, libMesh::Real cp, bool is_steady) const inline
Definition at line 57 of file low_mach_navier_stokes_stab_helper.h.
References GRINS::IncompressibleNavierStokesStabilizationHelper::compute_tau().
   {
     /*
     libMesh::Real tau = (rho*U)*(G*(rho*U)) + this->_C*k*k*G.contract(G);
     if(!is_steady)
       tau += (2.0*rho/c.get_deltat_value())*(2.0*rho/c.get_deltat_value());
     return this->_tau_factor/std::sqrt(tau);
     */
     return this->compute_tau( c, qp, k*k, g, G, rho*cp, U, is_steady );
   }
libMesh::Real GRINS::IncompressibleNavierStokesStabilizationHelper::compute_tau_momentum (AssemblyContext & c, unsigned int qp, libMesh::RealGradient & g, libMesh::RealTensor & G, libMesh::Real rho, libMesh::Gradient U, libMesh::Real mu, bool is_steady) const inline inherited
Definition at line 205 of file inc_navier_stokes_stab_helper.h.
References GRINS::IncompressibleNavierStokesStabilizationHelper::compute_tau().
   {
     return this->compute_tau( c, qp, mu*mu, g, G, rho, U, is_steady );
   }
void GRINS::IncompressibleNavierStokesStabilizationHelper::compute_tau_momentum_and_derivs (AssemblyContext & c, unsigned int qp, libMesh::RealGradient & g, libMesh::RealTensor & G, libMesh::Real rho, libMesh::Gradient U, libMesh::Real T, libMesh::Real & tau_M, libMesh::Real & d_tau_M_d_rho, libMesh::Gradient & d_tau_M_d_U, bool is_steady) const inline inherited
Definition at line 219 of file inc_navier_stokes_stab_helper.h.
   {
     this->compute_tau_and_derivs( c, qp, mu*mu, g, G, rho, U, tau_M,
                                   d_tau_M_d_rho, d_tau_M_d_U,
                                   is_steady );
   }
libMesh::RealGradient GRINS::IncompressibleNavierStokesStabilizationHelper::div_divU_I (libMesh::RealTensor & hess_u, libMesh::RealTensor & hess_v) const inherited
Todo:
Should we inline this?
Definition at line 121 of file inc_navier_stokes_stab_helper.C.
   {
     return libMesh::RealGradient( hess_u(0,0) + hess_v(1,0),
                                   hess_u(0,1) + hess_v(1,1) );
   }
libMesh::RealGradient GRINS::IncompressibleNavierStokesStabilizationHelper::div_divU_I (libMesh::RealTensor & hess_u, libMesh::RealTensor & hess_v, libMesh::RealTensor & hess_w) const inherited
Todo:
Should we inline this?
Definition at line 128 of file inc_navier_stokes_stab_helper.C.
   {
     return libMesh::RealGradient( hess_u(0,0) + hess_v(1,0) + hess_w(2,0),
                                   hess_u(0,1) + hess_v(1,1) + hess_w(2,1),
                                   hess_u(0,2) + hess_v(1,2) + hess_w(2,2) );
   }
libMesh::RealGradient GRINS::IncompressibleNavierStokesStabilizationHelper::div_GradU (libMesh::RealTensor & hess_u, libMesh::RealTensor & hess_v) const inherited
Todo:
Should we inline this?
Definition at line 89 of file inc_navier_stokes_stab_helper.C.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady().
   {
     return libMesh::RealGradient( hess_u(0,0) + hess_u(1,1),
                                   hess_v(0,0) + hess_v(1,1) );
   }
libMesh::RealGradient GRINS::IncompressibleNavierStokesStabilizationHelper::div_GradU (libMesh::RealTensor & hess_u, libMesh::RealTensor & hess_v, libMesh::RealTensor & hess_w) const inherited
Todo:
Should we inline this?
Definition at line 96 of file inc_navier_stokes_stab_helper.C.
   {
     return libMesh::RealGradient( hess_u(0,0) + hess_u(1,1) + hess_u(2,2),
                                   hess_v(0,0) + hess_v(1,1) + hess_v(2,2),
                                   hess_w(0,0) + hess_w(1,1) + hess_w(2,2) );
   }
libMesh::RealGradient GRINS::IncompressibleNavierStokesStabilizationHelper::div_GradU_T (libMesh::RealTensor & hess_u, libMesh::RealTensor & hess_v) const inherited
Todo:
Should we inline this?
Definition at line 105 of file inc_navier_stokes_stab_helper.C.
   {
     return libMesh::RealGradient( hess_u(0,0) + hess_v(0,1),
                                   hess_u(1,0) + hess_v(1,1) );
   }
libMesh::RealGradient GRINS::IncompressibleNavierStokesStabilizationHelper::div_GradU_T (libMesh::RealTensor & hess_u, libMesh::RealTensor & hess_v, libMesh::RealTensor & hess_w) const inherited
Todo:
Should we inline this?
Definition at line 112 of file inc_navier_stokes_stab_helper.C.
   {
     return libMesh::RealGradient( hess_u(0,0) + hess_v(0,1) + hess_w(0,2),
                                   hess_u(1,0) + hess_v(1,1) + hess_w(1,2),
                                   hess_u(2,0) + hess_v(2,1) + hess_w(2,2) );
   }
void GRINS::IncompressibleNavierStokesStabilizationHelper::init (libMesh::FEMSystem & system) inherited
Definition at line 67 of file inc_navier_stokes_stab_helper.C.
References GRINS::IncompressibleNavierStokesStabilizationHelper::_flow_vars, and GRINS::PrimitiveFlowVariables::init().
   {
     _flow_vars.init(&system);
     return;
   }
void GRINS::ParameterUser::register_parameter (const std::string & param_name, libMesh::ParameterMultiPointer< libMesh::Number > & param_pointer) const virtual inherited
Each subclass will register its copy of an independent.
Reimplemented in GRINS::AxisymmetricHeatTransfer< Conductivity >, GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::IncompressibleNavierStokesBase< Viscosity >, GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >, GRINS::HeatConduction< Conductivity >, GRINS::HeatTransferBase< Conductivity >, and GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >.
Definition at line 50 of file parameter_user.C.
Referenced by GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::register_parameter(), GRINS::HeatTransferBase< Conductivity >::register_parameter(), GRINS::HeatConduction< Conductivity >::register_parameter(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::register_parameter(), GRINS::IncompressibleNavierStokesBase< Viscosity >::register_parameter(), GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::register_parameter(), and GRINS::AxisymmetricHeatTransfer< Conductivity >::register_parameter().
   {
     std::map<std::string, libMesh::Number*>::const_iterator it =
       _my_parameters.find(param_name);
     if (it != _my_parameters.end())
       {
         std::cout << _my_name << " uses parameter " << param_name
                   << std::endl;
         param_pointer.push_back(it->second);
       }
   }
void GRINS::ParameterUser::set_parameter (libMesh::Number & param_variable, const GetPot & input, const std::string & param_name, libMesh::Number param_default) virtual inherited
Each subclass can simultaneously read a parameter value from.
Definition at line 35 of file parameter_user.C.
References GRINS::ParameterUser::_my_name, and GRINS::ParameterUser::_my_parameters.
Referenced by GRINS::AveragedFanAdjointStabilization< Viscosity >::AveragedFanAdjointStabilization(), GRINS::AveragedTurbineAdjointStabilization< Viscosity >::AveragedTurbineAdjointStabilization(), GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::BoussinesqBuoyancyAdjointStabilization(), GRINS::BoussinesqBuoyancyBase::BoussinesqBuoyancyBase(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::BoussinesqBuoyancySPGSMStabilization(), GRINS::ConstantConductivity::ConstantConductivity(), GRINS::ConstantPrandtlConductivity::ConstantPrandtlConductivity(), GRINS::ConstantSourceFunction::ConstantSourceFunction(), GRINS::ConstantSourceTerm::ConstantSourceTerm(), GRINS::ConstantSpecificHeat::ConstantSpecificHeat(), GRINS::ConstantViscosity::ConstantViscosity(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticCableConstantGravity::ElasticCableConstantGravity(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransferBase< Conductivity >::HeatTransferBase(), GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase(), GRINS::AverageNusseltNumber::init(), GRINS::MooneyRivlin::MooneyRivlin(), GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase(), GRINS::HookesLaw1D::read_input_options(), GRINS::HookesLaw::read_input_options(), GRINS::AxisymmetricBoussinesqBuoyancy::read_input_options(), and GRINS::VelocityDragAdjointStabilization< Viscosity >::VelocityDragAdjointStabilization().
   {
     param_variable = input(param_name, param_default);
     libmesh_assert_msg(!_my_parameters.count(param_name),
       "ERROR: " << _my_name << " double-registered parameter " <<
       param_name);
     _my_parameters[param_name] = &param_variable;
   }
libMesh::RealGradient GRINS::IncompressibleNavierStokesStabilizationHelper::UdotGradU (libMesh::Gradient & U, libMesh::Gradient & grad_u, libMesh::Gradient & grad_v) const inherited
Todo:
Should we inline this?
Definition at line 74 of file inc_navier_stokes_stab_helper.C.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady().
   {
     return libMesh::RealGradient( U*grad_u, U*grad_v );
   }
libMesh::RealGradient GRINS::IncompressibleNavierStokesStabilizationHelper::UdotGradU (libMesh::Gradient & U, libMesh::Gradient & grad_u, libMesh::Gradient & grad_v, libMesh::Gradient & grad_w) const inherited
Todo:
Should we inline this?
Definition at line 81 of file inc_navier_stokes_stab_helper.C.
   {
     return libMesh::RealGradient( U*grad_u, U*grad_v, U*grad_w );
   }
Member Data Documentation
libMesh::Real GRINS::IncompressibleNavierStokesStabilizationHelper::_C protected inherited
Definition at line 172 of file inc_navier_stokes_stab_helper.h.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_tau().
PrimitiveFlowVariables GRINS::IncompressibleNavierStokesStabilizationHelper::_flow_vars protected inherited
Definition at line 174 of file inc_navier_stokes_stab_helper.h.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_continuity(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_transient(), and GRINS::IncompressibleNavierStokesStabilizationHelper::init().
libMesh::Real GRINS::IncompressibleNavierStokesStabilizationHelper::_tau_factor protected inherited
Definition at line 172 of file inc_navier_stokes_stab_helper.h.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_tau(), and GRINS::IncompressibleNavierStokesStabilizationHelper::compute_tau_continuity().
The documentation for this class was generated from the following files:
src/physics/include/grins/low_mach_navier_stokes_stab_helper.h
src/physics/src/low_mach_navier_stokes_stab_helper.C