GRINS-0.6.0: GRINS::SimulationBuilder Class Reference
GRINS::SimulationBuilder Class Reference
#include <simulation_builder.h>
Public Member Functions
SimulationBuilder ()
virtual ~SimulationBuilder ()
std::tr1::shared_ptr< libMesh::UnstructuredMesh > build_mesh (const GetPot &input, const libMesh::Parallel::Communicator &comm LIBMESH_CAN_DEFAULT_TO_COMMWORLD)
GRINS::PhysicsList build_physics (const GetPot &input)
std::tr1::shared_ptr< GRINS::Solver > build_solver (const GetPot &input)
std::tr1::shared_ptr< GRINS::Visualization > build_vis (const GetPot &input, const libMesh::Parallel::Communicator &comm LIBMESH_CAN_DEFAULT_TO_COMMWORLD)
std::multimap< GRINS::PhysicsName, GRINS::DBCContainer > build_dirichlet_bcs ()
std::map< GRINS::PhysicsName, GRINS::NBCContainer > build_neumann_bcs (libMesh::EquationSystems &equation_system)
std::tr1::shared_ptr< CompositeQoI > build_qoi (const GetPot &input)
std::tr1::shared_ptr< PostProcessedQuantities< libMesh::Real > > build_postprocessing (const GetPot &input)
std::tr1::shared_ptr< libMesh::ErrorEstimator > build_error_estimator (const GetPot &input, const libMesh::QoISet &qoi_set)
void attach_physics_factory (std::tr1::shared_ptr< PhysicsFactory > physics_factory)
void attach_solver_factory (std::tr1::shared_ptr< SolverFactory > solver_factory)
void attach_mesh_builder (std::tr1::shared_ptr< MeshBuilder > mesh_builder)
void attach_vis_factory (std::tr1::shared_ptr< VisualizationFactory > vis_factory)
void attach_bc_factory (std::tr1::shared_ptr< BoundaryConditionsFactory > bc_factory)
void attach_qoi_factory (std::tr1::shared_ptr< QoIFactory > qoi_factory)
void attach_postprocessing_factory (std::tr1::shared_ptr< PostprocessingFactory > postprocessing_factory)
void attach_error_estimator_factory (std::tr1::shared_ptr< ErrorEstimatorFactory > error_estimator_factory)
const MeshBuilder & mesh_builder () const
Protected Attributes
std::tr1::shared_ptr< PhysicsFactory > _physics_factory
std::tr1::shared_ptr< MeshBuilder > _mesh_builder
std::tr1::shared_ptr< SolverFactory > _solver_factory
std::tr1::shared_ptr< VisualizationFactory > _vis_factory
std::tr1::shared_ptr< BoundaryConditionsFactory > _bc_factory
std::tr1::shared_ptr< QoIFactory > _qoi_factory
std::tr1::shared_ptr< PostprocessingFactory > _postprocessing_factory
std::tr1::shared_ptr< ErrorEstimatorFactory > _error_estimator_factory
Detailed Description
Definition at line 41 of file simulation_builder.h.
Constructor & Destructor Documentation
GRINS::SimulationBuilder::SimulationBuilder ()
Definition at line 35 of file simulation_builder.C.
     : _physics_factory( new PhysicsFactory ),
       _mesh_builder( new MeshBuilder ),
       _solver_factory( new SolverFactory ),
       _vis_factory( new VisualizationFactory ),
       _bc_factory( new BoundaryConditionsFactory ),
       _qoi_factory( new QoIFactory ),
       _postprocessing_factory( new PostprocessingFactory ),
       _error_estimator_factory( new ErrorEstimatorFactory )
   {
     return;
   }
GRINS::SimulationBuilder::~SimulationBuilder () virtual
Definition at line 48 of file simulation_builder.C.
   {
     return;
   }
Member Function Documentation
void GRINS::SimulationBuilder::attach_bc_factory (std::tr1::shared_ptr< BoundaryConditionsFactory > bc_factory)
Definition at line 77 of file simulation_builder.C.
References _bc_factory.
Referenced by main().
   {
     this->_bc_factory = bc_factory;
     return;
   }
void GRINS::SimulationBuilder::attach_error_estimator_factory (std::tr1::shared_ptr< ErrorEstimatorFactory > error_estimator_factory)
Definition at line 93 of file simulation_builder.C.
References _error_estimator_factory.
   {
     this->_error_estimator_factory = error_estimator_factory;
   }
void GRINS::SimulationBuilder::attach_mesh_builder (std::tr1::shared_ptr< MeshBuilder > mesh_builder)
Definition at line 65 of file simulation_builder.C.
References _mesh_builder, and mesh_builder().
   {
     this->_mesh_builder = mesh_builder;
     return;
   }
void GRINS::SimulationBuilder::attach_physics_factory (std::tr1::shared_ptr< PhysicsFactory > physics_factory)
Definition at line 53 of file simulation_builder.C.
References _physics_factory.
   {
     this->_physics_factory = physics_factory;
     return;
   }
void GRINS::SimulationBuilder::attach_postprocessing_factory (std::tr1::shared_ptr< PostprocessingFactory > postprocessing_factory)
Definition at line 88 of file simulation_builder.C.
References _postprocessing_factory.
   {
     this->_postprocessing_factory = postprocessing_factory;
   }
void GRINS::SimulationBuilder::attach_qoi_factory (std::tr1::shared_ptr< QoIFactory > qoi_factory)
Definition at line 83 of file simulation_builder.C.
References _qoi_factory.
   {
     this->_qoi_factory = qoi_factory;
   }
void GRINS::SimulationBuilder::attach_solver_factory (std::tr1::shared_ptr< SolverFactory > solver_factory)
Definition at line 59 of file simulation_builder.C.
References _solver_factory.
   {
     this->_solver_factory = solver_factory;
     return;
   }
void GRINS::SimulationBuilder::attach_vis_factory (std::tr1::shared_ptr< VisualizationFactory > vis_factory)
Definition at line 71 of file simulation_builder.C.
References _vis_factory.
   {
     this->_vis_factory = vis_factory;
     return;
   }
std::multimap< GRINS::PhysicsName, GRINS::DBCContainer > GRINS::SimulationBuilder::build_dirichlet_bcs ()
Definition at line 122 of file simulation_builder.C.
References _bc_factory.
Referenced by GRINS::Simulation::init_multiphysics_system().
   {
     return (this->_bc_factory)->build_dirichlet();
   }
std::tr1::shared_ptr< libMesh::ErrorEstimator > GRINS::SimulationBuilder::build_error_estimator (const GetPot & input, const libMesh::QoISet & qoi_set)
Definition at line 143 of file simulation_builder.C.
References _error_estimator_factory.
    {
      return (this->_error_estimator_factory)->build(input,qoi_set);
    }
std::tr1::shared_ptr< libMesh::UnstructuredMesh > GRINS::SimulationBuilder::build_mesh (const GetPot & input, const libMesh::Parallel::Communicator &comm LIBMESH_CAN_DEFAULT_TO_COMMWORLD)
Definition at line 99 of file simulation_builder.C.
   {
     return (this->_mesh_builder)->build(input, comm);
   }
std::map< GRINS::PhysicsName, GRINS::NBCContainer > GRINS::SimulationBuilder::build_neumann_bcs (libMesh::EquationSystems & equation_system)
Definition at line 127 of file simulation_builder.C.
References _bc_factory.
Referenced by GRINS::Simulation::init_multiphysics_system().
   {
     return (this->_bc_factory)->build_neumann(equation_system);
   }
GRINS::PhysicsList GRINS::SimulationBuilder::build_physics (const GetPot & input)
Definition at line 105 of file simulation_builder.C.
References _physics_factory.
Referenced by GRINS::Simulation::init_multiphysics_system().
   {
     return (this->_physics_factory)->build(input);
   }
std::tr1::shared_ptr< PostProcessedQuantities< libMesh::Real > > GRINS::SimulationBuilder::build_postprocessing (const GetPot & input)
Definition at line 138 of file simulation_builder.C.
References _postprocessing_factory.
   {
     return (this->_postprocessing_factory)->build(input);
   }
std::tr1::shared_ptr< CompositeQoI > GRINS::SimulationBuilder::build_qoi (const GetPot & input)
Definition at line 132 of file simulation_builder.C.
References _qoi_factory.
Referenced by GRINS::Simulation::init_qois().
   {
     return (this->_qoi_factory)->build(input);
   }
std::tr1::shared_ptr< GRINS::Solver > GRINS::SimulationBuilder::build_solver (const GetPot & input)
Definition at line 110 of file simulation_builder.C.
References _solver_factory.
   {
     return (this->_solver_factory)->build(input);
   }
std::tr1::shared_ptr< GRINS::Visualization > GRINS::SimulationBuilder::build_vis (const GetPot & input, const libMesh::Parallel::Communicator &comm LIBMESH_CAN_DEFAULT_TO_COMMWORLD)
Definition at line 116 of file simulation_builder.C.
   {
     return (this->_vis_factory)->build(input, comm);
   }
const MeshBuilder & GRINS::SimulationBuilder::mesh_builder () const
Definition at line 149 of file simulation_builder.C.
References _mesh_builder.
Referenced by attach_mesh_builder(), and GRINS::Simulation::init_restart().
   {
     return *_mesh_builder;
   }
Member Data Documentation
std::tr1::shared_ptr<BoundaryConditionsFactory> GRINS::SimulationBuilder::_bc_factory protected
Definition at line 97 of file simulation_builder.h.
Referenced by attach_bc_factory(), build_dirichlet_bcs(), and build_neumann_bcs().
std::tr1::shared_ptr<ErrorEstimatorFactory> GRINS::SimulationBuilder::_error_estimator_factory protected
Definition at line 100 of file simulation_builder.h.
Referenced by attach_error_estimator_factory(), and build_error_estimator().
std::tr1::shared_ptr<MeshBuilder> GRINS::SimulationBuilder::_mesh_builder protected
Definition at line 94 of file simulation_builder.h.
Referenced by attach_mesh_builder(), and mesh_builder().
std::tr1::shared_ptr<PhysicsFactory> GRINS::SimulationBuilder::_physics_factory protected
Definition at line 93 of file simulation_builder.h.
Referenced by attach_physics_factory(), and build_physics().
std::tr1::shared_ptr<PostprocessingFactory> GRINS::SimulationBuilder::_postprocessing_factory protected
Definition at line 99 of file simulation_builder.h.
Referenced by attach_postprocessing_factory(), and build_postprocessing().
std::tr1::shared_ptr<QoIFactory> GRINS::SimulationBuilder::_qoi_factory protected
Definition at line 98 of file simulation_builder.h.
Referenced by attach_qoi_factory(), and build_qoi().
std::tr1::shared_ptr<SolverFactory> GRINS::SimulationBuilder::_solver_factory protected
Definition at line 95 of file simulation_builder.h.
Referenced by attach_solver_factory(), and build_solver().
std::tr1::shared_ptr<VisualizationFactory> GRINS::SimulationBuilder::_vis_factory protected
Definition at line 96 of file simulation_builder.h.
Referenced by attach_vis_factory().
The documentation for this class was generated from the following files:
src/solver/include/grins/simulation_builder.h
src/solver/src/simulation_builder.C