GRINS-0.6.0: GRINS::CompositeQoI Class Reference
GRINS::CompositeQoI Class Reference
#include <composite_qoi.h>
Public Member Functions
CompositeQoI ()
virtual ~CompositeQoI ()
virtual libMesh::AutoPtr< libMesh::DifferentiableQoI > clone ()
Required to provide clone for adding QoI object to libMesh objects.
virtual void add_qoi (const QoIBase &qoi)
unsigned int n_qois () const
void register_parameter (const std::string &param_name, libMesh::ParameterMultiPointer< libMesh::Number > &param_pointer) const
Each QoI will register its copy(s) of an independent variable.
virtual void init (const GetPot &input, const MultiphysicsSystem &system)
Method to allow QoI to cache any system information needed for QoI calculation, for example, solution variable indices.
virtual void init_qoi (std::vector< libMesh::Number > &sys_qoi)
Method to allow QoI to resize libMesh::System storage of QoI computations.
virtual void init_context (libMesh::DiffContext &context)
virtual void element_qoi (libMesh::DiffContext &context, const libMesh::QoISet &qoi_indices)
Compute the qoi value for element interiors.
virtual void element_qoi_derivative (libMesh::DiffContext &context, const libMesh::QoISet &qoi_indices)
Compute the qoi derivative with respect to the solution on element interiors.
virtual void side_qoi (libMesh::DiffContext &context, const libMesh::QoISet &qoi_indices)
Compute the qoi value on the domain boundary.
virtual void side_qoi_derivative (libMesh::DiffContext &context, const libMesh::QoISet &qois)
Compute the qoi derivative with respect to the solution on the domain boundary.
virtual void parallel_op (const libMesh::Parallel::Communicator &communicator, std::vector< libMesh::Number > &sys_qoi, std::vector< libMesh::Number > &local_qoi, const libMesh::QoISet &qoi_indices)
Operation to accumulate the QoI from multiple MPI processes.
virtual void thread_join (std::vector< libMesh::Number > &qoi, const std::vector< libMesh::Number > &other_qoi, const libMesh::QoISet &qoi_indices)
Operation to accumulate the QoI from multiple MPI processes.
void output_qoi (std::ostream &out) const
Basic output for computed QoI's.
libMesh::Number get_qoi_value (unsigned int qoi_index) const
Accessor for value of QoI for given qoi_index.
const QoIBase & get_qoi (unsigned int qoi_index) const
Protected Attributes
std::vector< QoIBase * > _qois
Detailed Description
Definition at line 56 of file composite_qoi.h.
Constructor & Destructor Documentation
GRINS::CompositeQoI::CompositeQoI ()
Definition at line 37 of file composite_qoi.C.
Referenced by clone().
     : libMesh::DifferentiableQoI()
   {
     // We initialize these to false and then reset as needed by each QoI
     assemble_qoi_sides = false;
     assemble_qoi_elements = false;
     return;
   }
GRINS::CompositeQoI::~CompositeQoI () virtual
Definition at line 47 of file composite_qoi.C.
References _qois.
   {
     for( std::vector<QoIBase*>::iterator qoi = _qois.begin();
          qoi != _qois.end(); ++qoi )
       {
         delete (*qoi);
       }
     return;
   }
Member Function Documentation
void GRINS::CompositeQoI::add_qoi (const QoIBase & qoi) virtual
Definition at line 70 of file composite_qoi.C.
References _qois, GRINS::QoIBase::assemble_on_interior(), GRINS::QoIBase::assemble_on_sides(), and GRINS::QoIBase::clone().
Referenced by clone().
   {
     _qois.push_back( qoi.clone() );
     if( qoi.assemble_on_interior() )
       {
         this->assemble_qoi_elements = true;
       }
     if( qoi.assemble_on_sides() )
       {
         this->assemble_qoi_sides = true;
       }
     return;
   }
libMesh::AutoPtr< libMesh::DifferentiableQoI > GRINS::CompositeQoI::clone () virtual
Required to provide clone for adding QoI object to libMesh objects.
Note that we do a deep copy here since the previous object might get destroyed and wipe out the objects being pointed to in _qois.
Definition at line 58 of file composite_qoi.C.
References add_qoi(), CompositeQoI(), get_qoi(), and n_qois().
   {
     CompositeQoI* clone = new CompositeQoI;
     for( unsigned int q = 0; q < this->n_qois(); q++ )
       {
         clone->add_qoi( this->get_qoi(q) );
       }
     return libMesh::AutoPtr<libMesh::DifferentiableQoI>(clone);
   }
void GRINS::CompositeQoI::element_qoi (libMesh::DiffContext & context, const libMesh::QoISet & qoi_indices) virtual
Compute the qoi value for element interiors.
Definition at line 127 of file composite_qoi.C.
References _qois.
   {
     AssemblyContext& c = libMesh::libmesh_cast_ref<AssemblyContext&>(context);
     for( unsigned int q = 0; q < _qois.size(); q++ )
       {
         (*_qois[q]).element_qoi(c,q);
       }
     return;
   }
void GRINS::CompositeQoI::element_qoi_derivative (libMesh::DiffContext & context, const libMesh::QoISet & qoi_indices) virtual
Compute the qoi derivative with respect to the solution on element interiors.
Definition at line 140 of file composite_qoi.C.
References _qois.
   {
     AssemblyContext& c = libMesh::libmesh_cast_ref<AssemblyContext&>(context);
     for( unsigned int q = 0; q < _qois.size(); q++ )
       {
         (*_qois[q]).element_qoi_derivative(c,q);
       }
     return;
   }
const QoIBase & GRINS::CompositeQoI::get_qoi (unsigned int qoi_index) const inline
Definition at line 144 of file composite_qoi.h.
References _qois, and n_qois().
Referenced by clone(), GRINS::SteadyVisualization::output_adjoint(), and GRINS::UnsteadyVisualization::output_adjoint().
   {
     libmesh_assert_less( qoi_index, this->n_qois() );
     return (*_qois[qoi_index]);
   }
libMesh::Number GRINS::CompositeQoI::get_qoi_value (unsigned int qoi_index) const
Accessor for value of QoI for given qoi_index.
Definition at line 215 of file composite_qoi.C.
References _qois.
Referenced by GRINS::Simulation::get_qoi_value().
   {
     return (*_qois[qoi_index]).value();
   }
void GRINS::CompositeQoI::init (const GetPot & input, const MultiphysicsSystem & system) virtual
Method to allow QoI to cache any system information needed for QoI calculation, for example, solution variable indices.
Definition at line 94 of file composite_qoi.C.
References _qois.
   {
     for( std::vector<QoIBase*>::iterator qoi = _qois.begin();
          qoi != _qois.end(); ++qoi )
       {
         (*qoi)->init(input,system);
       }
     return;
   }
void GRINS::CompositeQoI::init_context (libMesh::DiffContext & context) virtual
Definition at line 105 of file composite_qoi.C.
References _qois.
   {
     AssemblyContext& c = libMesh::libmesh_cast_ref<AssemblyContext&>(context);
     for( std::vector<QoIBase*>::iterator qoi = _qois.begin();
          qoi != _qois.end(); ++qoi )
       {
         (*qoi)->init_context(c);
       }
     return;
   }
void GRINS::CompositeQoI::init_qoi (std::vector< libMesh::Number > & sys_qoi) virtual
Method to allow QoI to resize libMesh::System storage of QoI computations.
Definition at line 87 of file composite_qoi.C.
References _qois.
   {
     sys_qoi.resize(_qois.size(), 0.0);
     return;
   }
unsigned int GRINS::CompositeQoI::n_qois () const inline
Definition at line 138 of file composite_qoi.h.
References _qois.
Referenced by clone(), get_qoi(), GRINS::SteadyVisualization::output_adjoint(), and GRINS::UnsteadyVisualization::output_adjoint().
   {
     return _qois.size();
   }
void GRINS::CompositeQoI::output_qoi (std::ostream & out) const
Basic output for computed QoI's.
Definition at line 204 of file composite_qoi.C.
References _qois.
Referenced by GRINS::Simulation::run(), and GRINS::SteadyMeshAdaptiveSolver::solve().
   {
     for( std::vector<QoIBase*>::const_iterator qoi = _qois.begin();
          qoi != _qois.end(); ++qoi )
       {
         (*qoi)->output_qoi(out);
       }
     return;
   }
void GRINS::CompositeQoI::parallel_op (const libMesh::Parallel::Communicator & communicator, std::vector< libMesh::Number > & sys_qoi, std::vector< libMesh::Number > & local_qoi, const libMesh::QoISet & qoi_indices) virtual
Operation to accumulate the QoI from multiple MPI processes.
Calls each QoI's parallel_op function.
Definition at line 179 of file composite_qoi.C.
References _qois.
   {
     for( unsigned int q = 0; q < _qois.size(); q++ )
       {
         (*_qois[q]).parallel_op( communicator, sys_qoi[q], local_qoi[q] );
       }
     return;
   }
void GRINS::CompositeQoI::register_parameter (const std::string & param_name, libMesh::ParameterMultiPointer< libMesh::Number > & param_pointer) const
Each QoI will register its copy(s) of an independent variable.
Definition at line 119 of file composite_qoi.C.
Referenced by GRINS::ParameterManager::initialize().
   {
     for( unsigned int q = 0; q < _qois.size(); q++ )
       (*_qois[q]).register_parameter(param_name, param_pointer);
   }
void GRINS::CompositeQoI::side_qoi (libMesh::DiffContext & context, const libMesh::QoISet & qoi_indices) virtual
Compute the qoi value on the domain boundary.
Definition at line 153 of file composite_qoi.C.
References _qois.
   {
     AssemblyContext& c = libMesh::libmesh_cast_ref<AssemblyContext&>(context);
     for( unsigned int q = 0; q < _qois.size(); q++ )
       {
         (*_qois[q]).side_qoi(c,q);
       }
     return;
   }
void GRINS::CompositeQoI::side_qoi_derivative (libMesh::DiffContext & context, const libMesh::QoISet & qois) virtual
Compute the qoi derivative with respect to the solution on the domain boundary.
Definition at line 166 of file composite_qoi.C.
References _qois.
   {
     AssemblyContext& c = libMesh::libmesh_cast_ref<AssemblyContext&>(context);
     for( unsigned int q = 0; q < _qois.size(); q++ )
       {
         (*_qois[q]).side_qoi_derivative(c,q);
       }
     return;
   }
void GRINS::CompositeQoI::thread_join (std::vector< libMesh::Number > & qoi, const std::vector< libMesh::Number > & other_qoi, const libMesh::QoISet & qoi_indices) virtual
Operation to accumulate the QoI from multiple MPI processes.
Calls each QoI's thread_join function.
Definition at line 192 of file composite_qoi.C.
References _qois.
   {
     for( unsigned int q = 0; q < _qois.size(); q++ )
       {
         (*_qois[q]).thread_join( qoi[q], other_qoi[q] );
       }
     return;
   }
Member Data Documentation
std::vector<QoIBase*> GRINS::CompositeQoI::_qois protected
Definition at line 133 of file composite_qoi.h.
Referenced by add_qoi(), element_qoi(), element_qoi_derivative(), get_qoi(), get_qoi_value(), init(), init_context(), init_qoi(), n_qois(), output_qoi(), parallel_op(), side_qoi(), side_qoi_derivative(), thread_join(), and ~CompositeQoI().
The documentation for this class was generated from the following files:
src/qoi/include/grins/composite_qoi.h
src/qoi/src/composite_qoi.C