GRINS-0.6.0: GRINS::AntiochConstantTransportMixture< Conductivity > Class Template Reference
GRINS::AntiochConstantTransportMixture< Conductivity > Class Template Reference
Wrapper class for storing state for constant transport properties, including Antioch::ConstantLewisDiffusivity.
#include <antioch_constant_transport_mixture.h>
Public Types
typedef AntiochChemistry ChemistryParent
Public Member Functions
AntiochConstantTransportMixture (const GetPot &input)
virtual ~AntiochConstantTransportMixture ()
libMesh::Real mu () const
const Conductivity & conductivity () const
const Antioch::ConstantLewisDiffusivity< libMesh::Real > & diffusivity () const
const Antioch::ReactionSet< libMesh::Real > & reaction_set () const
const Antioch::CEAThermoMixture< libMesh::Real > & cea_mixture () const
libMesh::Real h_stat_mech_ref_correction (unsigned int species) const
libMesh::Real M (unsigned int species) const
Species molar mass (molecular weight), [kg/mol].
libMesh::Real M_mix (const std::vector< libMesh::Real > &mass_fractions) const
Mixture molar mass (molecular weight), [kg/mol].
libMesh::Real R (unsigned int species) const
Species gas constant, [J/kg-K].
libMesh::Real R_mix (const std::vector< libMesh::Real > &mass_fractions) const
Mixture gas constant, [J/kg-K].
libMesh::Real X (unsigned int species, libMesh::Real M, libMesh::Real mass_fraction) const
Species mole fraction, unitless.
void X (libMesh::Real M, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &mole_fractions) const
Mole fraction for all species, unitless.
libMesh::Real molar_density (const unsigned int species, const libMesh::Real rho, const libMesh::Real mass_fraction) const
Species molar density, [mol/m^3].
void molar_densities (const libMesh::Real rho, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &molar_densities) const
Molar density for all species, [mol/m^3].
unsigned int n_species () const
unsigned int species_index (const std::string &species_name) const
std::string species_name (unsigned int species_index) const
const Antioch::ChemicalMixture< libMesh::Real > & chemical_mixture () const
Accessor to underlying Antioch object.
const AntiochChemistry & chemistry () const
Accessor for this class.
Protected Member Functions
void build_conductivity (const GetPot &input)
void build_stat_mech_ref_correction ()
Protected Attributes
libMesh::Real _mu
boost::scoped_ptr< Conductivity > _conductivity
boost::scoped_ptr< Antioch::ConstantLewisDiffusivity< libMesh::Real > > _diffusivity
boost::scoped_ptr< Antioch::ReactionSet< libMesh::Real > > _reaction_set
boost::scoped_ptr< Antioch::CEAThermoMixture< libMesh::Real > > _cea_mixture
std::vector< libMesh::Real > _h_stat_mech_ref_correction
boost::scoped_ptr< Antioch::ChemicalMixture< libMesh::Real > > _antioch_gas
Private Member Functions
AntiochConstantTransportMixture ()
void specialized_build_conductivity (const GetPot &input, boost::scoped_ptr< ConstantConductivity > &conductivity, conductivity_type< ConstantConductivity >)
void specialized_build_conductivity (const GetPot &input, boost::scoped_ptr< ConstantPrandtlConductivity > &conductivity, conductivity_type< ConstantPrandtlConductivity >)
Detailed Description
template<typename Conductivity>
class GRINS::AntiochConstantTransportMixture< Conductivity >
Wrapper class for storing state for constant transport properties, including Antioch::ConstantLewisDiffusivity.
This class is expected to be constructed before threads have been forked and will live during the whole program. By default, Antioch is working in SI units. Note that this documentation will always be built regardless if Antioch is included in the GRINS build or not. Check configure output to confirm that Antioch was included in the build.
Definition at line 57 of file antioch_constant_transport_mixture.h.
Member Typedef Documentation
template<typename Conductivity> typedef AntiochChemistry GRINS::AntiochConstantTransportMixture< Conductivity >::ChemistryParent
Definition at line 71 of file antioch_constant_transport_mixture.h.
Constructor & Destructor Documentation
template<typename Thermo > GRINS::AntiochConstantTransportMixture< Thermo >::AntiochConstantTransportMixture (const GetPot & input)
Definition at line 35 of file antioch_constant_transport_mixture.C.
References GRINS::AntiochConstantTransportMixture< Conductivity >::build_conductivity().
     : AntiochMixture(input),
       _mu( input("Materials/Viscosity/mu", 0.0) ),
       _conductivity(NULL),
       _diffusivity( new Antioch::ConstantLewisDiffusivity<libMesh::Real>( input("Physics/Antioch/Le", 0.0) ) )
   {
     if( !input.have_variable("Materials/Viscosity/mu") )
       {
         std::cerr << "Error: Must specify viscosity value for constant viscosity model!" << std::endl;
         libmesh_error();
       }
     if( !input.have_variable("Physics/Antioch/Le") )
       {
         std::cerr << "Error: Must provide Lewis number for constant_lewis diffusivity model."
                   << std::endl;
         libmesh_error();
       }
     this->build_conductivity(input);
     return;
   }
template<typename Thermo > GRINS::AntiochConstantTransportMixture< Thermo >::~AntiochConstantTransportMixture () virtual
Definition at line 60 of file antioch_constant_transport_mixture.C.
   {
     return;
   }
template<typename Conductivity> GRINS::AntiochConstantTransportMixture< Conductivity >::AntiochConstantTransportMixture () private
Member Function Documentation
template<typename Conductivity> void GRINS::AntiochConstantTransportMixture< Conductivity >::build_conductivity (const GetPot & input) inline protected
Definition at line 85 of file antioch_constant_transport_mixture.h.
References GRINS::AntiochConstantTransportMixture< Conductivity >::specialized_build_conductivity().
Referenced by GRINS::AntiochConstantTransportMixture< Conductivity >::AntiochConstantTransportMixture().
     { specialized_build_conductivity( input, _conductivity, conductivity_type<Conductivity>() ); }
void GRINS::AntiochMixture::build_stat_mech_ref_correction () protected inherited
Definition at line 71 of file antioch_mixture.C.
References GRINS::AntiochChemistry::_antioch_gas, GRINS::AntiochMixture::_h_stat_mech_ref_correction, and GRINS::AntiochChemistry::n_species().
Referenced by GRINS::AntiochMixture::AntiochMixture().
   {
     Antioch::StatMechThermodynamics<libMesh::Real> thermo( *(this->_antioch_gas.get()) );
     _h_stat_mech_ref_correction.resize(this->n_species());
     for( unsigned int s = 0; s < this->n_species(); s++ )
       {
         _h_stat_mech_ref_correction[s] = -thermo.h_tot( s, 298.15 ) + thermo.e_0(s);
       }
     return;
   }
const Antioch::CEAThermoMixture< libMesh::Real > & GRINS::AntiochMixture::cea_mixture () const inline inherited
Definition at line 101 of file antioch_mixture.h.
References GRINS::AntiochMixture::_cea_mixture.
Referenced by GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_thermo(), and GRINS::AntiochEvaluator< Thermo >::specialized_build_thermo().
   {
     return *_cea_mixture.get();
   }
const Antioch::ChemicalMixture< libMesh::Real > & GRINS::AntiochChemistry::chemical_mixture () const inline inherited
Accessor to underlying Antioch object.
Definition at line 178 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
Referenced by GRINS::AntiochEvaluator< Thermo >::specialized_build_thermo().
   {
     return *_antioch_gas.get();
   }
const AntiochChemistry & GRINS::AntiochChemistry::chemistry () const inline inherited
Accessor for this class.
Definition at line 201 of file antioch_chemistry.h.
   {
     return *this;
   }
template<typename Conductivity > const Conductivity & GRINS::AntiochConstantTransportMixture< Conductivity >::conductivity () const inline
Definition at line 120 of file antioch_constant_transport_mixture.h.
   {
     return *_conductivity.get();
   }
template<typename Conductivity > const Antioch::ConstantLewisDiffusivity< libMesh::Real > & GRINS::AntiochConstantTransportMixture< Conductivity >::diffusivity () const inline
Definition at line 127 of file antioch_constant_transport_mixture.h.
   {
     return *_diffusivity.get();
   }
libMesh::Real GRINS::AntiochMixture::h_stat_mech_ref_correction (unsigned int species) const inline inherited
Definition at line 107 of file antioch_mixture.h.
References GRINS::AntiochMixture::_h_stat_mech_ref_correction.
   {
     return _h_stat_mech_ref_correction[species];
   }
libMesh::Real GRINS::AntiochChemistry::M (unsigned int species) const inline inherited
Species molar mass (molecular weight), [kg/mol].
Definition at line 122 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
   {
     return _antioch_gas->M(species);
   }
libMesh::Real GRINS::AntiochChemistry::M_mix (const std::vector< libMesh::Real > & mass_fractions) const inline inherited
Mixture molar mass (molecular weight), [kg/mol].
Definition at line 128 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
Referenced by main().
   {
     return _antioch_gas->M(mass_fractions);
   }
void GRINS::AntiochChemistry::molar_densities (const libMesh::Real rho, const std::vector< libMesh::Real > & mass_fractions, std::vector< libMesh::Real > & molar_densities) const inline inherited
Molar density for all species, [mol/m^3].
Definition at line 192 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
Referenced by GRINS::AntiochKinetics::omega_dot().
   {
     _antioch_gas->molar_densities( rho, mass_fractions, molar_densities );
     return;
   }
libMesh::Real GRINS::AntiochChemistry::molar_density (const unsigned int species, const libMesh::Real rho, const libMesh::Real mass_fraction) const inline inherited
Species molar density, [mol/m^3].
Definition at line 184 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
   {
     return _antioch_gas->molar_density( species, rho, mass_fraction );
   }
template<typename Conductivity > libMesh::Real GRINS::AntiochConstantTransportMixture< Conductivity >::mu () const inline
Definition at line 113 of file antioch_constant_transport_mixture.h.
   {
     return _mu;
   }
unsigned int GRINS::AntiochChemistry::n_species () const inline inherited
Definition at line 162 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
Referenced by GRINS::AntiochChemistry::AntiochChemistry(), GRINS::AntiochMixture::build_stat_mech_ref_correction(), do_transport_eval(), main(), and GRINS::AntiochKinetics::omega_dot().
   {
     return _antioch_gas->n_species();
   }
libMesh::Real GRINS::AntiochChemistry::R (unsigned int species) const inline inherited
Species gas constant, [J/kg-K].
R_universal/M(species)
Definition at line 134 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
   {
     return _antioch_gas->R(species);
   }
libMesh::Real GRINS::AntiochChemistry::R_mix (const std::vector< libMesh::Real > & mass_fractions) const inline inherited
Mixture gas constant, [J/kg-K].
Definition at line 140 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
Referenced by main(), and test_evaluator().
   {
     return _antioch_gas->R(mass_fractions);
   }
const Antioch::ReactionSet< libMesh::Real > & GRINS::AntiochMixture::reaction_set () const inline inherited
Definition at line 95 of file antioch_mixture.h.
References GRINS::AntiochMixture::_reaction_set.
   {
     return *_reaction_set.get();
   }
template<typename Conductivity> void GRINS::AntiochConstantTransportMixture< Conductivity >::specialized_build_conductivity (const GetPot & input, boost::scoped_ptr< ConstantConductivity > & conductivity, conductivity_type< ConstantConductivity >) inline private
Definition at line 92 of file antioch_constant_transport_mixture.h.
Referenced by GRINS::AntiochConstantTransportMixture< Conductivity >::build_conductivity().
     {
       conductivity.reset( new ConstantConductivity(input) );
       return;
     }
template<typename Conductivity> void GRINS::AntiochConstantTransportMixture< Conductivity >::specialized_build_conductivity (const GetPot & input, boost::scoped_ptr< ConstantPrandtlConductivity > & conductivity, conductivity_type< ConstantPrandtlConductivity >) inline private
Definition at line 100 of file antioch_constant_transport_mixture.h.
     {
       conductivity.reset( new ConstantPrandtlConductivity(input) );
       return;
     }
unsigned int GRINS::AntiochChemistry::species_index (const std::string & species_name) const inline inherited
Definition at line 168 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
   {
 #if ANTIOCH_MAJOR_VERSION < 1 && ANTIOCH_MINOR_VERSION < 3
     return _antioch_gas->active_species_name_map().find(species_name)->second;
 #else
     return _antioch_gas->species_name_map().find(species_name)->second;
 #endif
   }
std::string GRINS::AntiochChemistry::species_name (unsigned int species_index) const inherited
Definition at line 65 of file antioch_chemistry.C.
References GRINS::AntiochChemistry::_antioch_gas.
Referenced by do_transport_eval(), main(), and test_evaluator().
   {
     libmesh_assert_less(species_index, _antioch_gas->n_species());
 #if ANTIOCH_MAJOR_VERSION < 1 && ANTIOCH_MINOR_VERSION < 3
     std::string name = "dummy";
     for( std::map<std::string,unsigned int>::const_iterator it = _antioch_gas->active_species_name_map().begin();
          it != _antioch_gas->active_species_name_map().end(); it++ )
       {
         if( it->second == species_index )
           {
             name = it->first;
           }
       }
     if( name == std::string("dummy") )
       {
         std::cerr << "Error: Could not find a species name for the given index!"
                   << std::endl;
         libmesh_error();
       }
     return name;
 #else
     return _antioch_gas->species_inverse_name_map().find(species_index)->second;
 #endif
   }
libMesh::Real GRINS::AntiochChemistry::X (unsigned int species, libMesh::Real M, libMesh::Real mass_fraction) const inline inherited
Species mole fraction, unitless.
Definition at line 146 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
Referenced by main().
   {
     return _antioch_gas->X(species,M,mass_fraction);
   }
void GRINS::AntiochChemistry::X (libMesh::Real M, const std::vector< libMesh::Real > & mass_fractions, std::vector< libMesh::Real > & mole_fractions) const inline inherited
Mole fraction for all species, unitless.
Definition at line 153 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
   {
     _antioch_gas->X(M,mass_fractions,mole_fractions);
     return;
   }
Member Data Documentation
boost::scoped_ptr<Antioch::ChemicalMixture<libMesh::Real> > GRINS::AntiochChemistry::_antioch_gas protected inherited
Definition at line 112 of file antioch_chemistry.h.
Referenced by GRINS::AntiochChemistry::AntiochChemistry(), GRINS::AntiochMixture::build_stat_mech_ref_correction(), GRINS::AntiochChemistry::chemical_mixture(), GRINS::AntiochChemistry::M(), GRINS::AntiochChemistry::M_mix(), GRINS::AntiochChemistry::molar_densities(), GRINS::AntiochChemistry::molar_density(), GRINS::AntiochChemistry::n_species(), GRINS::AntiochChemistry::R(), GRINS::AntiochChemistry::R_mix(), GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_thermo(), GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_viscosity(), GRINS::AntiochChemistry::species_index(), GRINS::AntiochChemistry::species_name(), and GRINS::AntiochChemistry::X().
boost::scoped_ptr<Antioch::CEAThermoMixture<libMesh::Real> > GRINS::AntiochMixture::_cea_mixture protected inherited
Definition at line 81 of file antioch_mixture.h.
Referenced by GRINS::AntiochMixture::AntiochMixture(), and GRINS::AntiochMixture::cea_mixture().
template<typename Conductivity> boost::scoped_ptr<Conductivity> GRINS::AntiochConstantTransportMixture< Conductivity >::_conductivity protected
Definition at line 77 of file antioch_constant_transport_mixture.h.
template<typename Conductivity> boost::scoped_ptr<Antioch::ConstantLewisDiffusivity<libMesh::Real> > GRINS::AntiochConstantTransportMixture< Conductivity >::_diffusivity protected
Definition at line 79 of file antioch_constant_transport_mixture.h.
std::vector<libMesh::Real> GRINS::AntiochMixture::_h_stat_mech_ref_correction protected inherited
Definition at line 83 of file antioch_mixture.h.
Referenced by GRINS::AntiochMixture::build_stat_mech_ref_correction(), and GRINS::AntiochMixture::h_stat_mech_ref_correction().
template<typename Conductivity> libMesh::Real GRINS::AntiochConstantTransportMixture< Conductivity >::_mu protected
Definition at line 75 of file antioch_constant_transport_mixture.h.
boost::scoped_ptr<Antioch::ReactionSet<libMesh::Real> > GRINS::AntiochMixture::_reaction_set protected inherited
Definition at line 79 of file antioch_mixture.h.
Referenced by GRINS::AntiochMixture::AntiochMixture(), and GRINS::AntiochMixture::reaction_set().
The documentation for this class was generated from the following files:
src/properties/include/grins/antioch_constant_transport_mixture.h
src/properties/src/antioch_constant_transport_mixture.C