GRINS-0.6.0: GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity > Class Template Reference
GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity > Class Template Reference
Physics class for Incompressible Navier-Stokes.
#include <low_mach_navier_stokes.h>
Public Member Functions
LowMachNavierStokes (const PhysicsName &physics_name, const GetPot &input)
~LowMachNavierStokes ()
virtual void read_input_options (const GetPot &input)
Read options from GetPot input file.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register postprocessing variables for LowMachNavierStokes.
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for element interiors.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
virtual void init_variables (libMesh::FEMSystem *system)
Initialize variables for this physics.
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Sets velocity variables to be time-evolving.
libMesh::Real T (const libMesh::Point &p, const AssemblyContext &c) const
libMesh::Real rho (libMesh::Real T, libMesh::Real p0) const
libMesh::Real d_rho_dT (libMesh::Real T, libMesh::Real p0) const
libMesh::Real get_p0_steady (const AssemblyContext &c, unsigned int qp) const
libMesh::Real get_p0_steady (const AssemblyContext &c, const libMesh::Point &p) const
libMesh::Real get_p0_steady_side (const AssemblyContext &c, unsigned int qp) const
libMesh::Real get_p0_transient (AssemblyContext &c, unsigned int qp) const
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiPointer< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_bcs (libMesh::FEMSystem *system)
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
void attach_neumann_bound_func (GRINS::NBCContainer &neumann_bcs)
void attach_dirichlet_bound_func (const GRINS::DBCContainer &dirichlet_bc)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
BCHandlingBase * get_bc_handler ()
ICHandlingBase * get_ic_handler ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
Protected Member Functions
void assemble_mass_time_deriv (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Helper function.
void assemble_momentum_time_deriv (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Helper function.
void assemble_energy_time_deriv (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Helper function.
void assemble_continuity_mass_residual (bool compute_jacobian, AssemblyContext &c)
Helper function.
void assemble_momentum_mass_residual (bool compute_jacobian, AssemblyContext &c)
Helper function.
void assemble_energy_mass_residual (bool compute_jacobian, AssemblyContext &c)
Helper function.
void assemble_thermo_press_elem_time_deriv (bool compute_jacobian, AssemblyContext &c)
void assemble_thermo_press_side_time_deriv (bool compute_jacobian, AssemblyContext &c)
void assemble_thermo_press_mass_residual (bool compute_jacobian, AssemblyContext &c)
Protected Attributes
bool _pin_pressure
Enable pressure pinning.
PressurePinning _p_pinning
unsigned int _rho_index
Cache index for density post-processing.
libMesh::Number _p0_over_R
Thermodynamic pressure divided by gas constant.
libMesh::Number _p0
libMesh::Number _R
libMesh::Number _T0
unsigned int _dim
Physical dimension of problem.
VariableIndex _u_var
Indices for each (owned) variable;.
VariableIndex _v_var
VariableIndex _w_var
VariableIndex _p_var
VariableIndex _T_var
VariableIndex _p0_var
std::string _u_var_name
Names of each (owned) variable in the system.
std::string _v_var_name
std::string _w_var_name
std::string _p_var_name
std::string _T_var_name
std::string _p0_var_name
GRINSEnums::FEFamily _V_FE_family
Element type, read from input.
GRINSEnums::FEFamily _P_FE_family
GRINSEnums::FEFamily _T_FE_family
GRINSEnums::Order _V_order
Element orders, read from input.
GRINSEnums::Order _P_order
GRINSEnums::Order _T_order
Viscosity _mu
Viscosity object.
SpecificHeat _cp
Specific heat object.
ThermalConductivity _k
Thermal conductivity object.
libMesh::Point _g
Gravity vector.
bool _enable_thermo_press_calc
Flag to enable thermodynamic pressure calculation.
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::BCHandlingBase * _bc_handler
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
bool _is_axisymmetric
Static Protected Attributes
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
Private Member Functions
LowMachNavierStokes ()
Detailed Description
template<class Viscosity, class SpecificHeat, class ThermalConductivity>
class GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >
Physics class for Incompressible Navier-Stokes.
This physics class implements the classical Incompressible Navier-Stokes equations.
Definition at line 41 of file low_mach_navier_stokes.h.
Constructor & Destructor Documentation
template<class Mu , class SH , class TC > GRINS::LowMachNavierStokes< Mu, SH, TC >::LowMachNavierStokes (const PhysicsName & physics_name, const GetPot & input)
Definition at line 46 of file low_mach_navier_stokes.C.
References GRINS::Physics::_bc_handler, GRINS::Physics::_ic_handler, and GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::read_input_options().
     : LowMachNavierStokesBase<Mu,SH,TC>(physics_name,input),
       _p_pinning(input,physics_name),
       _rho_index(0) // Initialize to zero
   {
     this->read_input_options(input);
     // This is deleted in the base class
     this->_bc_handler = new LowMachNavierStokesBCHandling( physics_name, input );
     this->_ic_handler = new GenericICHandler( physics_name, input );
     return;
   }
template<class Mu , class SH , class TC > GRINS::LowMachNavierStokes< Mu, SH, TC >::~LowMachNavierStokes ()
Definition at line 61 of file low_mach_navier_stokes.C.
   {
     return;
   }
template<class Viscosity , class SpecificHeat , class ThermalConductivity > GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokes () private
Member Function Documentation
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::assemble_continuity_mass_residual (bool compute_jacobian, AssemblyContext & c) protected
Helper function.
Definition at line 739 of file low_mach_navier_stokes.C.
   {
     // Element Jacobian * quadrature weights for interior integration
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(this->_u_var)->get_JxW();
     // The shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& p_phi =
       context.get_element_fe(this->_p_var)->get_phi();
     // The number of local degrees of freedom in each variable
     const unsigned int n_p_dofs = context.get_dof_indices(this->_p_var).size();
     // The subvectors and submatrices we need to fill:
     libMesh::DenseSubVector<libMesh::Real> &F_p = context.get_elem_residual(this->_p_var);
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     for (unsigned int qp = 0; qp != n_qpoints; ++qp)
       {
         // For the mass residual, we need to be a little careful.
         // The time integrator is handling the time-discretization
         // for us so we need to supply M(u_fixed)*u' for the residual.
         // u_fixed will be given by the fixed_interior_value function
         // while u' will be given by the interior_rate function.
         libMesh::Real T_dot;
         context.interior_rate(this->_T_var, qp, T_dot);
         libMesh::Real T = context.fixed_interior_value(this->_T_var, qp);
         for (unsigned int i = 0; i != n_p_dofs; ++i)
           {
             F_p(i) -= T_dot/T*p_phi[i][qp]*JxW[qp];
           } // End DoF loop i
       } // End quadrature loop qp
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::assemble_energy_mass_residual (bool compute_jacobian, AssemblyContext & c) protected
Helper function.
Definition at line 860 of file low_mach_navier_stokes.C.
   {
     // Element Jacobian * quadrature weights for interior integration
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(this->_T_var)->get_JxW();
     // The shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& T_phi =
       context.get_element_fe(this->_T_var)->get_phi();
     // The number of local degrees of freedom in each variable
     const unsigned int n_T_dofs = context.get_dof_indices(this->_T_var).size();
     // The subvectors and submatrices we need to fill:
     libMesh::DenseSubVector<libMesh::Real> &F_T = context.get_elem_residual(this->_T_var);
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     for (unsigned int qp = 0; qp != n_qpoints; ++qp)
       {
         // For the mass residual, we need to be a little careful.
         // The time integrator is handling the time-discretization
         // for us so we need to supply M(u_fixed)*u' for the residual.
         // u_fixed will be given by the fixed_interior_value function
         // while u will be given by the interior_rate function.
         libMesh::Real T_dot;
         context.interior_rate(this->_T_var, qp, T_dot);
         libMesh::Real T = context.fixed_interior_value(this->_T_var, qp);
         libMesh::Real cp = this->_cp(T);
         libMesh::Number rho = this->rho(T, this->get_p0_transient(context, qp));
         for (unsigned int i = 0; i != n_T_dofs; ++i)
           {
             F_T(i) -= rho*cp*T_dot*T_phi[i][qp]*JxW[qp];
           } // End DoF loop i
       } // End quadrature loop qp
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::assemble_energy_time_deriv (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) protected
Helper function.
Definition at line 627 of file low_mach_navier_stokes.C.
References GRINS::CachedValues::get_cached_gradient_values(), GRINS::CachedValues::get_cached_values(), GRINS::Cache::TEMPERATURE, GRINS::Cache::TEMPERATURE_GRAD, GRINS::Cache::THERMO_PRESSURE, GRINS::Cache::X_VELOCITY, GRINS::Cache::Y_VELOCITY, and GRINS::Cache::Z_VELOCITY.
   {
     // The number of local degrees of freedom in each variable.
     const unsigned int n_T_dofs = context.get_dof_indices(this->_T_var).size();
     const unsigned int n_u_dofs = context.get_dof_indices(this->_u_var).size();
     // Element Jacobian * quadrature weights for interior integration.
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(this->_T_var)->get_JxW();
     // The temperature shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& T_phi =
       context.get_element_fe(this->_T_var)->get_phi();
     const std::vector<std::vector<libMesh::Real> >& u_phi =
       context.get_element_fe(this->_u_var)->get_phi();
     // The temperature shape functions gradients at interior quadrature points.
     const std::vector<std::vector<libMesh::RealGradient> >& T_gradphi =
       context.get_element_fe(this->_T_var)->get_dphi();
     libMesh::DenseSubVector<libMesh::Number> &FT = context.get_elem_residual(this->_T_var); // R_{T}
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     for (unsigned int qp=0; qp != n_qpoints; qp++)
       {
                 libMesh::Number u, v, T, p0;
                 u = cache.get_cached_values(Cache::X_VELOCITY)[qp];
                 v = cache.get_cached_values(Cache::Y_VELOCITY)[qp];
                 T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
                 p0 = cache.get_cached_values(Cache::THERMO_PRESSURE)[qp];
                 libMesh::Gradient grad_T = cache.get_cached_gradient_values(Cache::TEMPERATURE_GRAD)[qp];
                 libMesh::NumberVectorValue U(u,v);
                 if (this->_dim == 3)
                   U(2) = cache.get_cached_values(Cache::Z_VELOCITY)[qp]; // w
                 libMesh::DenseSubMatrix<libMesh::Number> &KTu = context.get_elem_jacobian(this->_T_var, this->_u_var); // R_{u},{u}
                 libMesh::DenseSubMatrix<libMesh::Number> &KTv = context.get_elem_jacobian(this->_T_var, this->_v_var); // R_{u},{u}
                         libMesh::DenseSubMatrix<libMesh::Number>* KTw = NULL;
                 libMesh::DenseSubMatrix<libMesh::Number> &KTT = context.get_elem_jacobian(this->_T_var, this->_T_var); // R_{u},{u}
                 if( this->_dim == 3 )
                   {
                     KTw = &context.get_elem_jacobian(this->_T_var, this->_w_var); // R_{u},{w}
                   }
                 libMesh::Number k = this->_k(T);
                 libMesh::Number dk_dT = this->_k.deriv(T);
                 libMesh::Number cp = this->_cp(T);
                 libMesh::Number d_cp = this->_cp.deriv(T);
                 libMesh::Number rho = this->rho( T, p0 );
                 libMesh::Number d_rho = this->d_rho_dT( T, p0 );
                 // Now a loop over the pressure degrees of freedom.  This
                 // computes the contributions of the continuity equation.
                 for (unsigned int i=0; i != n_T_dofs; i++)
                   {
                         FT(i) += ( -rho*cp*U*grad_T*T_phi[i][qp] // convection term
                                    - k*grad_T*T_gradphi[i][qp]            // diffusion term
                                    )*JxW[qp];
                          if(compute_jacobian)
{
                                         for (unsigned int j=0; j!=n_u_dofs; j++)
{
                                                         //pre-compute repeated term
                                                         libMesh::Number r0 = rho*cp*T_phi[i][qp]*u_phi[j][qp];
                                                         KTu(i,j) += JxW[qp]*
                                                                         -r0*grad_T(0);
                                                                         //-rho*cp*u_phi[j][qp]*grad_T(0)*T_phi[i][qp];
                                                         KTv(i,j) += JxW[qp]*
                                                                         -r0*grad_T(1);
                                                                         //-rho*cp*u_phi[j][qp]*grad_T(1)*T_phi[i][qp];
                                                         if (this->_dim == 3)
{
                                                                         (*KTw)(i,j) += JxW[qp]*
                                                                                         -r0*grad_T(2);
                                                                                         //-rho*cp*u_phi[j][qp]*grad_T(2)*T_phi[i][qp];
                                                                 }
                                                 } // end u_dofs loop (j)
                                         for (unsigned int j=0; j!=n_T_dofs; j++)
{
                                                     KTT(i,j) += JxW[qp]* (
                                                                                 -rho*(
                                                                                         cp*U*T_phi[i][qp]*T_gradphi[j][qp]
                                                                                         + U*grad_T*T_phi[i][qp]*d_cp*T_phi[j][qp]
                                                                                          )
                                                                                 -cp*U*grad_T*T_phi[i][qp]*d_rho*T_phi[j][qp]
                                                                                 -k*T_gradphi[i][qp]*T_gradphi[j][qp]
                                                                                 -grad_T*T_gradphi[i][qp]*dk_dT*T_phi[j][qp]
                                                                                             );
                                             } // end T_dofs loop (j)
                                 } // end if compute_jacobian
                   } // end outer T_dofs loop (i)
       } //end qp loop
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::assemble_mass_time_deriv (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) protected
Helper function.
Definition at line 205 of file low_mach_navier_stokes.C.
References GRINS::CachedValues::get_cached_gradient_values(), GRINS::CachedValues::get_cached_values(), GRINS::Cache::TEMPERATURE, GRINS::Cache::TEMPERATURE_GRAD, GRINS::Cache::X_VELOCITY, GRINS::Cache::X_VELOCITY_GRAD, GRINS::Cache::Y_VELOCITY, GRINS::Cache::Y_VELOCITY_GRAD, GRINS::Cache::Z_VELOCITY, and GRINS::Cache::Z_VELOCITY_GRAD.
   {
     // The number of local degrees of freedom in each variable.
     const unsigned int n_p_dofs = context.get_dof_indices(this->_p_var).size();
     // Element Jacobian * quadrature weights for interior integration.
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(this->_u_var)->get_JxW();
     // The pressure shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& p_phi =
       context.get_element_fe(this->_p_var)->get_phi();
     // The velocity shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& u_phi =
       context.get_element_fe(this->_u_var)->get_phi();
     // The velocity shape function gradients (in global coords.)
     // at interior quadrature points.
     const std::vector<std::vector<libMesh::RealGradient> >& u_gradphi =
       context.get_element_fe(this->_u_var)->get_dphi();
     // The temperature shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& T_phi =
       context.get_element_fe(this->_T_var)->get_phi();
     // The temperature shape function gradients (in global coords.)
     // at interior quadrature points.
     const std::vector<std::vector<libMesh::RealGradient> >& T_gradphi =
       context.get_element_fe(this->_T_var)->get_dphi();
     libMesh::DenseSubVector<libMesh::Number> &Fp = context.get_elem_residual(this->_p_var); // R_{p}
     unsigned int n_qpoints = context.get_element_qrule().n_points();
      // The number of local degrees of freedom in each variable.
     const unsigned int n_t_dofs = context.get_dof_indices(this->_T_var).size();
      // The number of local degrees of freedom in each variable.
     const unsigned int n_u_dofs = context.get_dof_indices(this->_u_var).size();
     // Check number of dofs is same for _u_var, v_var and w_var.
     libmesh_assert (n_u_dofs == context.get_dof_indices(this->_v_var).size());
     if (this->_dim == 3)
       libmesh_assert (n_u_dofs == context.get_dof_indices(this->_w_var).size());
     for (unsigned int qp=0; qp != n_qpoints; qp++)
       {
         libMesh::Number u, v, T;
         u = cache.get_cached_values(Cache::X_VELOCITY)[qp];
         v = cache.get_cached_values(Cache::Y_VELOCITY)[qp];
         T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
         libMesh::Gradient grad_u = cache.get_cached_gradient_values(Cache::X_VELOCITY_GRAD)[qp];
         libMesh::Gradient grad_v = cache.get_cached_gradient_values(Cache::Y_VELOCITY_GRAD)[qp];
         libMesh::Gradient grad_T = cache.get_cached_gradient_values(Cache::TEMPERATURE_GRAD)[qp];
         libMesh::NumberVectorValue U(u,v);
         if (this->_dim == 3)
           U(2) = cache.get_cached_values(Cache::Z_VELOCITY)[qp]; // w
         libMesh::Number divU = grad_u(0) + grad_v(1);
         if (this->_dim == 3)
           {
             libMesh::Gradient grad_w = cache.get_cached_gradient_values(Cache::Z_VELOCITY_GRAD)[qp];
             divU += grad_w(2);
           }
     libMesh::DenseSubMatrix<libMesh::Number> &KPu = context.get_elem_jacobian(this->_p_var, this->_u_var);
     libMesh::DenseSubMatrix<libMesh::Number> &KPv = context.get_elem_jacobian(this->_p_var, this->_v_var);
     libMesh::DenseSubMatrix<libMesh::Number> &KPT = context.get_elem_jacobian(this->_p_var, this->_T_var);
     libMesh::DenseSubMatrix<libMesh::Number>* KPw = NULL;
     if( this->_dim == 3 )
       {
         KPw = &context.get_elem_jacobian(this->_p_var, this->_w_var);
       }
         // Now a loop over the pressure degrees of freedom.  This
         // computes the contributions of the continuity equation.
         for (unsigned int i=0; i != n_p_dofs; i++)
           {
             Fp(i) += (-U*grad_T/T + divU)*p_phi[i][qp]*JxW[qp];
             if (compute_jacobian)
                 {
                         for (unsigned int j=0; j!=n_u_dofs; j++)
{
                                         KPu(i,j) += JxW[qp]*(
                                                                 +u_gradphi[j][qp](0)*p_phi[i][qp]
                                                                 -u_phi[j][qp]*p_phi[i][qp]*grad_T(0)/T
                                                                 );
                                         KPv(i,j) += JxW[qp]*(
                                                                 +u_gradphi[j][qp](1)*p_phi[i][qp]
                                                                 -u_phi[j][qp]*p_phi[i][qp]*grad_T(1)/T
                                                                 );
                                         if (this->_dim == 3)
{
                                                         (*KPw)(i,j) += JxW[qp]*(
                                                                                 +u_gradphi[j][qp](2)*p_phi[i][qp]
                                                                                 -u_phi[j][qp]*p_phi[i][qp]*grad_T(2)/T
                                                                                 );
                                                 }
                                 }
                         for (unsigned int j=0; j!=n_t_dofs; j++)
{
                                         KPT(i,j) += JxW[qp]*(
                                                         -T_gradphi[j][qp]*U*p_phi[i][qp]/T
                                                         +U*p_phi[i][qp]*grad_T*T_phi[j][qp])/(T*T);
                                 }
             } // end if compute_jacobian
           } // end p_dofs loop
       } // end qp loop
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::assemble_momentum_mass_residual (bool compute_jacobian, AssemblyContext & c) protected
Helper function.
Definition at line 781 of file low_mach_navier_stokes.C.
   {
     // Element Jacobian * quadrature weights for interior integration
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(this->_u_var)->get_JxW();
     // The shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& u_phi =
       context.get_element_fe(this->_u_var)->get_phi();
     // The number of local degrees of freedom in each variable
     const unsigned int n_u_dofs = context.get_dof_indices(this->_u_var).size();
     // for convenience
     if (this->_dim != 3)
       this->_w_var = this->_u_var;
     // The subvectors and submatrices we need to fill:
     libMesh::DenseSubVector<libMesh::Real> &F_u = context.get_elem_residual(this->_u_var);
     libMesh::DenseSubVector<libMesh::Real> &F_v = context.get_elem_residual(this->_v_var);
     libMesh::DenseSubVector<libMesh::Real> &F_w = context.get_elem_residual(this->_w_var);
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     for (unsigned int qp = 0; qp != n_qpoints; ++qp)
       {
         // For the mass residual, we need to be a little careful.
         // The time integrator is handling the time-discretization
         // for us so we need to supply M(u_fixed)*u' for the residual.
         // u_fixed will be given by the fixed_interior_value function
         // while u' will be given by the interior_rate function.
         libMesh::Real u_dot, v_dot, w_dot = 0.0;
         context.interior_rate(this->_u_var, qp, u_dot);
         context.interior_rate(this->_v_var, qp, v_dot);
         if( this->_dim == 3 )
           context.interior_rate(this->_w_var, qp, w_dot);
         libMesh::Real T = context.fixed_interior_value(this->_T_var, qp);
         libMesh::Number rho = this->rho(T, this->get_p0_transient(context, qp));
         for (unsigned int i = 0; i != n_u_dofs; ++i)
           {
             F_u(i) -= rho*u_dot*u_phi[i][qp]*JxW[qp];
             F_v(i) -= rho*v_dot*u_phi[i][qp]*JxW[qp];
             if( this->_dim == 3 )
               F_w(i) -= rho*w_dot*u_phi[i][qp]*JxW[qp];
             /*
               if( compute_jacobian )
               {
               for (unsigned int j=0; j != n_u_dofs; j++)
               {
               // Assuming rho is constant w.r.t. u, v, w
               // and T (if Boussinesq added).
               libMesh::Real value = JxW[qp]*_rho*u_phi[i][qp]*u_phi[j][qp];
               M_uu(i,j) += value;
               M_vv(i,j) += value;
               if( _dim == 3)
               {
               M_ww(i,j) += value;
               }
               } // End DoF loop j
               } // End Jacobian check
             */
           } // End DoF loop i
       } // End quadrature loop qp
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::assemble_momentum_time_deriv (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) protected
Helper function.
Definition at line 339 of file low_mach_navier_stokes.C.
References GRINS::CachedValues::get_cached_gradient_values(), GRINS::CachedValues::get_cached_values(), GRINS::Cache::PRESSURE, GRINS::Cache::TEMPERATURE, GRINS::Cache::THERMO_PRESSURE, GRINS::Cache::X_VELOCITY, GRINS::Cache::X_VELOCITY_GRAD, GRINS::Cache::Y_VELOCITY, GRINS::Cache::Y_VELOCITY_GRAD, GRINS::Cache::Z_VELOCITY, and GRINS::Cache::Z_VELOCITY_GRAD.
   {
     // The number of local degrees of freedom in each variable.
     const unsigned int n_u_dofs = context.get_dof_indices(this->_u_var).size();
     const unsigned int n_p_dofs = context.get_dof_indices(this->_p_var).size();
     const unsigned int n_T_dofs = context.get_dof_indices(this->_T_var).size();
     // Check number of dofs is same for _u_var, v_var and w_var.
     libmesh_assert (n_u_dofs == context.get_dof_indices(this->_v_var).size());
     if (this->_dim == 3)
       libmesh_assert (n_u_dofs == context.get_dof_indices(this->_w_var).size());
     // Element Jacobian * quadrature weights for interior integration.
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(this->_u_var)->get_JxW();
     // The pressure shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& u_phi =
       context.get_element_fe(this->_u_var)->get_phi();
     const std::vector<std::vector<libMesh::Real> >& p_phi =
       context.get_element_fe(this->_p_var)->get_phi();
       const std::vector<std::vector<libMesh::Real> >& T_phi =
       context.get_element_fe(this->_T_var)->get_phi();
     // The velocity shape function gradients at interior quadrature points.
     const std::vector<std::vector<libMesh::RealGradient> >& u_gradphi =
       context.get_element_fe(this->_u_var)->get_dphi();
     libMesh::DenseSubVector<libMesh::Number> &Fu = context.get_elem_residual(this->_u_var); // R_{u}
     libMesh::DenseSubVector<libMesh::Number> &Fv = context.get_elem_residual(this->_v_var); // R_{v}
     libMesh::DenseSubVector<libMesh::Number> &Fw = context.get_elem_residual(this->_w_var); // R_{w}
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     for (unsigned int qp=0; qp != n_qpoints; qp++)
       {
         libMesh::Number u, v, p, p0, T;
         u = cache.get_cached_values(Cache::X_VELOCITY)[qp];
         v = cache.get_cached_values(Cache::Y_VELOCITY)[qp];
         T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
         p = cache.get_cached_values(Cache::PRESSURE)[qp];
         p0 = cache.get_cached_values(Cache::THERMO_PRESSURE)[qp];
         libMesh::Gradient grad_u = cache.get_cached_gradient_values(Cache::X_VELOCITY_GRAD)[qp];
         libMesh::Gradient grad_v = cache.get_cached_gradient_values(Cache::Y_VELOCITY_GRAD)[qp];
         libMesh::Gradient grad_w;
         if (this->_dim == 3)
           grad_w = cache.get_cached_gradient_values(Cache::Z_VELOCITY_GRAD)[qp];
         libMesh::NumberVectorValue grad_uT( grad_u(0), grad_v(0) );
         libMesh::NumberVectorValue grad_vT( grad_u(1), grad_v(1) );
         libMesh::NumberVectorValue grad_wT;
         if( this->_dim == 3 )
           {
             grad_uT(2) = grad_w(0);
             grad_vT(2) = grad_w(1);
             grad_wT = libMesh::NumberVectorValue( grad_u(2), grad_v(2), grad_w(2) );
           }
         libMesh::NumberVectorValue U(u,v);
         if (this->_dim == 3)
           U(2) = cache.get_cached_values(Cache::Z_VELOCITY)[qp]; // w
         libMesh::Number divU = grad_u(0) + grad_v(1);
         if (this->_dim == 3)
           divU += grad_w(2);
         libMesh::Number rho = this->rho( T, p0 );
         libMesh::Number d_rho = this->d_rho_dT( T, p0 );
         libMesh::Number d_mu = this->_mu.deriv(T);
         libMesh::DenseSubMatrix<libMesh::Number> &Kuu = context.get_elem_jacobian(this->_u_var, this->_u_var); // R_{u},{u}
     libMesh::DenseSubMatrix<libMesh::Number> &Kuv = context.get_elem_jacobian(this->_u_var, this->_v_var); // R_{u},{v}
     libMesh::DenseSubMatrix<libMesh::Number>* Kuw = NULL;
     libMesh::DenseSubMatrix<libMesh::Number> &Kvu = context.get_elem_jacobian(this->_v_var, this->_u_var); // R_{v},{u}
     libMesh::DenseSubMatrix<libMesh::Number> &Kvv = context.get_elem_jacobian(this->_v_var, this->_v_var); // R_{v},{v}
     libMesh::DenseSubMatrix<libMesh::Number>* Kvw = NULL;
     libMesh::DenseSubMatrix<libMesh::Number>* Kwu = NULL;
     libMesh::DenseSubMatrix<libMesh::Number>* Kwv = NULL;
     libMesh::DenseSubMatrix<libMesh::Number>* Kww = NULL;
     libMesh::DenseSubMatrix<libMesh::Number> &Kup = context.get_elem_jacobian(this->_u_var, this->_p_var); // R_{u},{p}
     libMesh::DenseSubMatrix<libMesh::Number> &Kvp = context.get_elem_jacobian(this->_v_var, this->_p_var); // R_{v},{p}
     libMesh::DenseSubMatrix<libMesh::Number>* Kwp = NULL;
     libMesh::DenseSubMatrix<libMesh::Number> &KuT = context.get_elem_jacobian(this->_u_var, this->_T_var); // R_{u},{p}
     libMesh::DenseSubMatrix<libMesh::Number> &KvT = context.get_elem_jacobian(this->_v_var, this->_T_var); // R_{v},{p}
     libMesh::DenseSubMatrix<libMesh::Number>* KwT = NULL;
     if( this->_dim == 3 )
       {
         Kuw = &context.get_elem_jacobian(this->_u_var, this->_w_var); // R_{u},{w}
         Kvw = &context.get_elem_jacobian(this->_v_var, this->_w_var); // R_{v},{w}
         Kwu = &context.get_elem_jacobian(this->_w_var, this->_u_var); // R_{w},{u};
         Kwv = &context.get_elem_jacobian(this->_w_var, this->_v_var); // R_{w},{v};
         Kww = &context.get_elem_jacobian(this->_w_var, this->_w_var); // R_{w},{w}
         Kwp = &context.get_elem_jacobian(this->_w_var, this->_p_var); // R_{w},{p}
         KwT = &context.get_elem_jacobian(this->_w_var, this->_T_var); // R_{w},{T}
       }
         // Now a loop over the pressure degrees of freedom.  This
         // computes the contributions of the continuity equation.
         for (unsigned int i=0; i != n_u_dofs; i++)
           {
             Fu(i) += ( -rho*U*grad_u*u_phi[i][qp]                 // convection term
                        + p*u_gradphi[i][qp](0)                           // pressure term
                        - this->_mu(T)*(u_gradphi[i][qp]*grad_u + u_gradphi[i][qp]*grad_uT
                                        - 2.0/3.0*divU*u_gradphi[i][qp](0) )    // diffusion term
                        + rho*this->_g(0)*u_phi[i][qp]                 // hydrostatic term
                        )*JxW[qp];
             Fv(i) += ( -rho*U*grad_v*u_phi[i][qp]                 // convection term
                        + p*u_gradphi[i][qp](1)                           // pressure term
                        - this->_mu(T)*(u_gradphi[i][qp]*grad_v + u_gradphi[i][qp]*grad_vT
                                        - 2.0/3.0*divU*u_gradphi[i][qp](1) )    // diffusion term
                        + rho*this->_g(1)*u_phi[i][qp]                 // hydrostatic term
                        )*JxW[qp];
             if (this->_dim == 3)
               {
                 Fw(i) += ( -rho*U*grad_w*u_phi[i][qp]                 // convection term
                            + p*u_gradphi[i][qp](2)                           // pressure term
                            - this->_mu(T)*(u_gradphi[i][qp]*grad_w + u_gradphi[i][qp]*grad_wT
                                            - 2.0/3.0*divU*u_gradphi[i][qp](2) )    // diffusion term
                            + rho*this->_g(2)*u_phi[i][qp]                 // hydrostatic term
                            )*JxW[qp];
               }
               if (compute_jacobian && context.get_elem_solution_derivative())
                 {
               libmesh_assert (context.get_elem_solution_derivative() == 1.0);
               for (unsigned int j=0; j != n_u_dofs; j++)
{
                                   //precompute repeated terms
                                   libMesh::Number r0 = rho*U*u_phi[i][qp]*u_gradphi[j][qp];
                                   libMesh::Number r1 = u_gradphi[i][qp]*u_gradphi[j][qp];
                                   libMesh::Number r2 = rho*u_phi[i][qp]*u_phi[j][qp];
                                   Kuu(i,j) += JxW[qp]*(
                                                                 -r0
                                                                 //-rho*U*u_gradphi[j][qp]*u_phi[i][qp]
                                                                 -r2*grad_u(0)
                                                                 //-rho*u_phi[i][qp]*grad_u(0)*u_phi[j][qp]
                                                                 -this->_mu(T)*(
                                                                         r1
                                                                         //u_gradphi[i][qp]*u_gradphi[j][qp]
                                                                         + u_gradphi[i][qp](0)*u_gradphi[j][qp](0) // transpose
                                                                         - 2.0/3.0*u_gradphi[i][qp](0)*u_gradphi[j][qp](0)
                                                                                                 ));
                                   Kvv(i,j) += JxW[qp]*(
                                                                 -r0
                                                                 //-rho*U*u_gradphi[j][qp]*u_phi[i][qp]
                                                                 -r2*grad_v(1)
                                                                 //-rho*u_phi[i][qp]*grad_v(1)*u_phi[j][qp]
                                                                 -this->_mu(T)*(
                                                                         r1
                                                                         //u_gradphi[i][qp]*u_gradphi[j][qp]
                                                                         + u_gradphi[i][qp](1)*u_gradphi[j][qp](1) // transpose
                                                                         - 2.0/3.0*u_gradphi[i][qp](1)*u_gradphi[j][qp](1)
                                                                                                 ));
                                   Kuv(i,j) += JxW[qp]*(
                                                                 +2.0/3.0*this->_mu(T)*u_gradphi[i][qp](0)*u_gradphi[j][qp](1)
                                                                 -this->_mu(T)*u_gradphi[i][qp](1)*u_gradphi[j][qp](0)
                                                                 -r2*grad_u(1)
                                                                 //-rho*u_phi[i][qp]*u_phi[j][qp]*grad_u(1));
                                                                                 );
                                   Kvu(i,j) += JxW[qp]*(
                                                                 +2.0/3.0*this->_mu(T)*u_gradphi[i][qp](1)*u_gradphi[j][qp](0)
                                                                 -this->_mu(T)*u_gradphi[i][qp](0)*u_gradphi[j][qp](1)
                                                                 -r2*grad_v(0)
                                                                 //-rho*u_phi[i][qp]*u_phi[j][qp]*grad_v(0));
                                                                                 );
                                   if (this->_dim == 3)
{
                                                 (*Kuw)(i,j) += JxW[qp]*(
                                                                                 +2.0/3.0*this->_mu(T)*u_gradphi[i][qp](0)*u_gradphi[j][qp](2)
                                                                                 -this->_mu(T)*u_gradphi[i][qp](2)*u_gradphi[j][qp](0)
                                                                                 -r2*grad_u(2)
                                                                                 //-rho*u_phi[i][qp]*u_phi[j][qp]*grad_u(2)
                                                                                         );
                                                 (*Kvw)(i,j) += JxW[qp]*(
                                                                                 +2.0/3.0*this->_mu(T)*u_gradphi[i][qp](1)*u_gradphi[j][qp](2)
                                                                                 -this->_mu(T)*u_gradphi[i][qp](2)*u_gradphi[j][qp](1)
                                                                                 -r2*grad_v(2)
                                                                                 //-rho*u_phi[i][qp]*u_phi[j][qp]*grad_v(2)
                                                                                                 );
                                                 (*Kwu)(i,j) += JxW[qp]*(
                                                                                 +2.0/3.0*this->_mu(T)*u_gradphi[i][qp](2)*u_gradphi[j][qp](0)
                                                                                 -this->_mu(T)*u_gradphi[i][qp](0)*u_gradphi[j][qp](2)
                                                                                 -r2*grad_w(0)
                                                                                 //-rho*u_phi[i][qp]*u_phi[j][qp]*grad_w(0)
                                                                                                 );
                                                 (*Kwv)(i,j) += JxW[qp]*(
                                                                                 +2.0/3.0*this->_mu(T)*u_gradphi[i][qp](2)*u_gradphi[j][qp](1)
                                                                                 -this->_mu(T)*u_gradphi[i][qp](1)*u_gradphi[j][qp](2)
                                                                                 -r2*grad_w(1)
                                                                                 //-rho*u_phi[i][qp]*u_phi[j][qp]*grad_w(1)
                                                                                                 );
                                                 (*Kww)(i,j) += JxW[qp]*(
                                                                                 -r0
                                                                                 //-rho*U*u_gradphi[j][qp]*u_phi[i][qp]
                                                                                 -r2*grad_w(2)
                                                                                 //-rho*u_phi[i][qp]*grad_w(2)*u_phi[j][qp]
                                                                                 -this->_mu(T)*(
                                                                                         r1
                                                                                         //u_gradphi[i][qp]*u_gradphi[j][qp]
                                                                                         + u_gradphi[i][qp](2)*u_gradphi[j][qp](2) // transpose
                                                                                         - 2.0/3.0*u_gradphi[i][qp](2)*u_gradphi[j][qp](2)
                                                                                                 ));
                                         } // end if _dim==3
                         } // end of the inner dof (j) loop
                                 for (unsigned int j=0; j!=n_T_dofs; j++)
{
                                                 //precompute repeated term
                                                 libMesh:: Number r3 = d_rho*u_phi[i][qp]*T_phi[j][qp];
                                                 // Analytical Jacobains
                                                 KuT(i,j) += JxW[qp]*(
                                                         -r3*U*grad_u
                                                         //-d_rho*T_phi[j][qp]*U*grad_u*u_phi[i][qp]
                                                         -d_mu*T_phi[j][qp]*grad_u*u_gradphi[i][qp]
                                                         -d_mu*T_phi[j][qp]*grad_u(0)*u_gradphi[i][qp](0) // transpose
                                                         +2.0/3.0*d_mu*T_phi[j][qp]*divU*u_gradphi[i][qp](0)
                                                         +r3*this->_g(0)
                                                         //+d_rho*T_phi[j][qp]*this->_g(0)*u_phi[i][qp]
                                                                                         );
                                                  KvT(i,j) += JxW[qp]*(
                                                         -r3*U*grad_v
                                                         //-d_rho*T_phi[j][qp]*U*grad_v*u_phi[i][qp]
                                                         -d_mu*T_phi[j][qp]*grad_v*u_gradphi[i][qp]
                                                         -d_mu*T_phi[j][qp]*grad_v(1)*u_gradphi[i][qp](1) // transpose
                                                         +2.0/3.0*d_mu*T_phi[j][qp]*divU*u_gradphi[i][qp](1)
                                                         +r3*this->_g(1)
                                                         //+d_rho*T_phi[j][qp]*this->_g(1)*u_phi[i][qp]
                                                                                         );
                                                 if (this->_dim == 3)
{
                                                                 (*KwT)(i,j) += JxW[qp]*(
                                                                                 -r3*U*grad_w
                                                                                 //-d_rho*T_phi[j][qp]*U*grad_v*u_phi[i][qp]
                                                                                 -d_mu*T_phi[j][qp]*grad_w*u_gradphi[i][qp]
                                                                                 -d_mu*T_phi[j][qp]*grad_w(2)*u_gradphi[i][qp](2) // transpose
                                                                                 +2.0/3.0*d_mu*T_phi[j][qp]*divU*u_gradphi[i][qp](2)
                                                                                 +r3*this->_g(2)
                                                                                 //+d_rho*T_phi[j][qp]*this->_g(2)*u_phi[i][qp]
                                                                                         );
                                                         } // end if _dim==3
                                         } // end T_dofs loop
                 // Matrix contributions for the up, vp and wp couplings
                 for (unsigned int j=0; j != n_p_dofs; j++)
{
                                   Kup(i,j) += JxW[qp]*p_phi[j][qp]*u_gradphi[i][qp](0);
                                   Kvp(i,j) += JxW[qp]*p_phi[j][qp]*u_gradphi[i][qp](1);
                                   if (this->_dim == 3)
                                         (*Kwp)(i,j) += JxW[qp]*p_phi[j][qp]*u_gradphi[i][qp](2);
                         } // end of the inner dof (j) loop
                 } // end - if (compute_jacobian && context.get_elem_solution_derivative())
               } // end of the outer dof (i) loop
         } // end of the quadrature point (qp) loop
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::assemble_thermo_press_elem_time_deriv (bool compute_jacobian, AssemblyContext & c) protected
Definition at line 906 of file low_mach_navier_stokes.C.
   {
     // Element Jacobian * quadrature weights for interior integration
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(this->_T_var)->get_JxW();
     // The number of local degrees of freedom in each variable
     const unsigned int n_p0_dofs = context.get_dof_indices(this->_p0_var).size();
     // The subvectors and submatrices we need to fill:
     libMesh::DenseSubVector<libMesh::Real> &F_p0 = context.get_elem_residual(this->_p0_var);
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     for (unsigned int qp = 0; qp != n_qpoints; ++qp)
       {
         libMesh::Number T;
         T = context.interior_value(this->_T_var, qp);
         libMesh::Gradient grad_u, grad_v, grad_w;
         grad_u = context.interior_gradient(this->_u_var, qp);
         grad_v = context.interior_gradient(this->_v_var, qp);
         if (this->_dim == 3)
           grad_w = context.interior_gradient(this->_w_var, qp);
         libMesh::Number divU = grad_u(0) + grad_v(1);
         if(this->_dim==3)
           divU += grad_w(2);
         //libMesh::Number cp = this->_cp(T);
         //libMesh::Number cv = cp + this->_R;
         //libMesh::Number gamma = cp/cv;
         //libMesh::Number gamma_ratio = gamma/(gamma-1.0);
         libMesh::Number p0 = context.interior_value( this->_p0_var, qp );
         for (unsigned int i = 0; i != n_p0_dofs; ++i)
           {
             F_p0(i) += (p0/T - this->_p0/this->_T0)*JxW[qp];
             //F_p0(i) -= p0*gamma_ratio*divU*JxW[qp];
           } // End DoF loop i
       }
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::assemble_thermo_press_mass_residual (bool compute_jacobian, AssemblyContext & c) protected
Definition at line 1004 of file low_mach_navier_stokes.C.
   {
     // The number of local degrees of freedom in each variable.
     const unsigned int n_p0_dofs = context.get_dof_indices(this->_p0_var).size();
     const unsigned int n_T_dofs = context.get_dof_indices(this->_T_var).size();
     const unsigned int n_p_dofs = context.get_dof_indices(this->_p_var).size();
     // Element Jacobian * quadrature weights for interior integration
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(this->_T_var)->get_JxW();
     // The temperature shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& T_phi =
       context.get_element_fe(this->_T_var)->get_phi();
     // The temperature shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& p_phi =
       context.get_element_fe(this->_p_var)->get_phi();
     // The subvectors and submatrices we need to fill:
     libMesh::DenseSubVector<libMesh::Real> &F_p0 = context.get_elem_residual(this->_p0_var);
     libMesh::DenseSubVector<libMesh::Real> &F_T = context.get_elem_residual(this->_T_var);
     libMesh::DenseSubVector<libMesh::Real> &F_p = context.get_elem_residual(this->_p_var);
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     for (unsigned int qp = 0; qp != n_qpoints; ++qp)
       {
         libMesh::Number T;
         T = context.fixed_interior_value(this->_T_var, qp);
         libMesh::Number cp = this->_cp(T);
         libMesh::Number cv = cp + this->_R;
         libMesh::Number gamma = cp/cv;
         libMesh::Number one_over_gamma = 1.0/(gamma-1.0);
         libMesh::Number p0_dot;
         context.interior_rate(this->_p0_var, qp, p0_dot);
         libMesh::Number p0 = context.fixed_interior_value(this->_p0_var, qp );
         for (unsigned int i=0; i != n_p0_dofs; i++)
           {
             F_p0(i) -= p0_dot*one_over_gamma*JxW[qp];
           }
         for (unsigned int i=0; i != n_T_dofs; i++)
           {
             F_T(i) += p0_dot*T_phi[i][qp]*JxW[qp];
           }
         for (unsigned int i=0; i != n_p_dofs; i++)
           {
             F_p(i) += p0_dot/p0*p_phi[i][qp]*JxW[qp];
           }
       }
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::assemble_thermo_press_side_time_deriv (bool compute_jacobian, AssemblyContext & c) protected
Definition at line 954 of file low_mach_navier_stokes.C.
   {
     // The number of local degrees of freedom in each variable.
     const unsigned int n_p0_dofs = context.get_dof_indices(this->_p0_var).size();
     // Element Jacobian * quadrature weight for side integration.
     //const std::vector<libMesh::Real> &JxW_side = context.get_side_fe(this->_T_var)->get_JxW();
     //const std::vector<Point> &normals = context.get_side_fe(this->_T_var)->get_normals();
     //libMesh::DenseSubVector<libMesh::Number> &F_p0 = context.get_elem_residual(this->_p0_var); // residual
     // Physical location of the quadrature points
     //const std::vector<libMesh::Point>& qpoint = context.get_side_fe(this->_T_var)->get_xyz();
     unsigned int n_qpoints = context.get_side_qrule().n_points();
     for (unsigned int qp=0; qp != n_qpoints; qp++)
       {
         /*
         libMesh::Number T = context.side_value( this->_T_var, qp );
         libMesh::Gradient U = ( context.side_value( this->_u_var, qp ),
                                 context.side_value( this->_v_var, qp ) );
         libMesh::Gradient grad_T = context.side_gradient( this->_T_var, qp );
         libMesh::Number p0 = context.side_value( this->_p0_var, qp );
         libMesh::Number k = this->_k(T);
         libMesh::Number cp = this->_cp(T);
         libMesh::Number cv = cp + this->_R;
         libMesh::Number gamma = cp/cv;
         libMesh::Number gamma_ratio = gamma/(gamma-1.0);
         */
         //std::cout << "U = " << U << std::endl;
         //std::cout << "x = " << qpoint[qp] << ", grad_T = " << grad_T << std::endl;
         for (unsigned int i=0; i != n_p0_dofs; i++)
           {
             //F_p0(i) += (k*grad_T*normals[qp] - p0*gamma_ratio*U*normals[qp]  )*JxW_side[qp];
           }
       }
     return;
   }
void GRINS::Physics::attach_dirichlet_bound_func (const GRINS::DBCContainer & dirichlet_bc) inherited
Definition at line 150 of file physics.C.
References GRINS::Physics::_bc_handler, and GRINS::BCHandlingBase::attach_dirichlet_bound_func().
   {
     _bc_handler->attach_dirichlet_bound_func( dirichlet_bc );
     return;
   }
void GRINS::Physics::attach_neumann_bound_func (GRINS::NBCContainer & neumann_bcs) inherited
Definition at line 144 of file physics.C.
References GRINS::Physics::_bc_handler, and GRINS::BCHandlingBase::attach_neumann_bound_func().
   {
     _bc_handler->attach_neumann_bound_func( neumann_bcs );
     return;
   }
void GRINS::Physics::auxiliary_init (MultiphysicsSystem & system) virtual inherited
Any auxillary initialization a Physics class may need.
This is called after all variables are added, so this method can safely query the MultiphysicsSystem about variable information.
Definition at line 113 of file physics.C.
   {
     return;
   }
void GRINS::Physics::compute_element_constraint_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 185 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::element_constraint().
   {
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::compute_element_time_derivative_cache (const AssemblyContext & context, CachedValues & cache) virtual
Reimplemented from GRINS::Physics.
Definition at line 1066 of file low_mach_navier_stokes.C.
References GRINS::Cache::PRESSURE, GRINS::CachedValues::set_gradient_values(), GRINS::CachedValues::set_values(), GRINS::Cache::TEMPERATURE, GRINS::Cache::TEMPERATURE_GRAD, GRINS::Cache::THERMO_PRESSURE, GRINS::Cache::X_VELOCITY, GRINS::Cache::X_VELOCITY_GRAD, GRINS::Cache::Y_VELOCITY, GRINS::Cache::Y_VELOCITY_GRAD, GRINS::Cache::Z_VELOCITY, and GRINS::Cache::Z_VELOCITY_GRAD.
   {
     const unsigned int n_qpoints = context.get_element_qrule().n_points();
     std::vector<libMesh::Real> u, v, w, T, p, p0;
     u.resize(n_qpoints);
     v.resize(n_qpoints);
     if( this->_dim > 2 )
       w.resize(n_qpoints);
     T.resize(n_qpoints);
     p.resize(n_qpoints);
     p0.resize(n_qpoints);
     std::vector<libMesh::Gradient> grad_u, grad_v, grad_w, grad_T;
     grad_u.resize(n_qpoints);
     grad_v.resize(n_qpoints);
     if( this->_dim > 2 )
       grad_w.resize(n_qpoints);
     grad_T.resize(n_qpoints);
     for (unsigned int qp = 0; qp != n_qpoints; ++qp)
       {
         u[qp] = context.interior_value(this->_u_var, qp);
         v[qp] = context.interior_value(this->_v_var, qp);
         grad_u[qp] = context.interior_gradient(this->_u_var, qp);
         grad_v[qp] = context.interior_gradient(this->_v_var, qp);
         if( this->_dim > 2 )
           {
             w[qp] = context.interior_value(this->_w_var, qp);
             grad_w[qp] = context.interior_gradient(this->_w_var, qp);
           }
         T[qp] = context.interior_value(this->_T_var, qp);
         grad_T[qp] = context.interior_gradient(this->_T_var, qp);
         p[qp] = context.interior_value(this->_p_var, qp);
         p0[qp] = this->get_p0_steady(context, qp);
       }
     cache.set_values(Cache::X_VELOCITY, u);
     cache.set_values(Cache::Y_VELOCITY, v);
     cache.set_gradient_values(Cache::X_VELOCITY_GRAD, grad_u);
     cache.set_gradient_values(Cache::Y_VELOCITY_GRAD, grad_v);
     if(this->_dim > 2)
       {
         cache.set_values(Cache::Z_VELOCITY, w);
         cache.set_gradient_values(Cache::Z_VELOCITY_GRAD, grad_w);
       }
     cache.set_values(Cache::TEMPERATURE, T);
     cache.set_gradient_values(Cache::TEMPERATURE_GRAD, grad_T);
     cache.set_values(Cache::PRESSURE, p);
     cache.set_values(Cache::THERMO_PRESSURE, p0);
     return;
   }
void GRINS::Physics::compute_mass_residual_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 203 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::mass_residual().
   {
     return;
   }
void GRINS::Physics::compute_nonlocal_constraint_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 197 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_constraint().
   {
     return;
   }
void GRINS::Physics::compute_nonlocal_mass_residual_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 209 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_mass_residual().
   {
     return;
   }
void GRINS::Physics::compute_nonlocal_time_derivative_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 179 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_time_derivative().
   {
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext & context, const libMesh::Point & point, libMesh::Real & value) virtual
Reimplemented from GRINS::Physics.
Definition at line 1130 of file low_mach_navier_stokes.C.
   {
     if( quantity_index == this->_rho_index )
       {
         libMesh::Real T = this->T(point,context);
         libMesh::Real p0 = this->get_p0_steady(context,point);
         value = this->rho( T, p0 );
       }
     return;
   }
void GRINS::Physics::compute_side_constraint_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 191 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::side_constraint().
   {
     return;
   }
void GRINS::Physics::compute_side_time_derivative_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Reimplemented in GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >.
Definition at line 173 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::side_time_derivative().
   {
     return;
   }
template<class V , class SH , class TC > libMesh::Real GRINS::LowMachNavierStokesBase< V, SH, TC >::d_rho_dT (libMesh::Real T, libMesh::Real p0) const inline inherited
Definition at line 151 of file low_mach_navier_stokes_base.h.
   {
     return -p0/(this->_R*(T*T));
   }
void GRINS::Physics::element_constraint (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Constraint part(s) of physics for element interiors.
Reimplemented in GRINS::IncompressibleNavierStokes< Viscosity >, GRINS::AveragedTurbineAdjointStabilization< Viscosity >, GRINS::VelocityDragAdjointStabilization< Viscosity >, GRINS::AveragedFanAdjointStabilization< Viscosity >, GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >, GRINS::ElasticMembrane< StressStrainLaw >, GRINS::Stokes< Viscosity >, GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >, GRINS::ParsedVelocitySourceAdjointStabilization< Viscosity >, GRINS::VelocityPenaltyAdjointStabilization< Viscosity >, GRINS::IncompressibleNavierStokesAdjointStabilization< Viscosity >, and GRINS::IncompressibleNavierStokesSPGSMStabilization< Viscosity >.
Definition at line 236 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::element_constraint().
   {
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::element_time_derivative (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Time dependent part(s) of physics for element interiors.
Reimplemented from GRINS::Physics.
Definition at line 130 of file low_mach_navier_stokes.C.
   {
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->BeginTimer("LowMachNavierStokes::element_time_derivative");
 #endif
     this->assemble_mass_time_deriv( compute_jacobian, context, cache );
     this->assemble_momentum_time_deriv( compute_jacobian, context, cache );
     this->assemble_energy_time_deriv( compute_jacobian, context, cache );
     if( this->_enable_thermo_press_calc )
       this->assemble_thermo_press_elem_time_deriv( compute_jacobian, context );
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->EndTimer("LowMachNavierStokes::element_time_derivative");
 #endif
     return;
   }
bool GRINS::Physics::enabled_on_elem (const libMesh::Elem * elem) virtual inherited
Find if current physics is active on supplied element.
Definition at line 83 of file physics.C.
References GRINS::Physics::_enabled_subdomains.
   {
     // Check if enabled_subdomains flag has been set and if we're
     // looking at a real element (rather than a nonlocal evaluation)
     if( !elem || _enabled_subdomains.empty() )
       return true;
     // Check if current physics is enabled on elem
     if( _enabled_subdomains.find( elem->subdomain_id() ) == _enabled_subdomains.end() )
       return false;
     return true;
   }
BCHandlingBase * GRINS::Physics::get_bc_handler () inline inherited
Definition at line 282 of file physics.h.
References GRINS::Physics::_bc_handler.
   {
     return _bc_handler;
   }
ICHandlingBase * GRINS::Physics::get_ic_handler () inline inherited
Definition at line 288 of file physics.h.
References GRINS::Physics::_ic_handler.
   {
     return _ic_handler;
   }
template<class V , class SH , class TC > libMesh::Real GRINS::LowMachNavierStokesBase< V, SH, TC >::get_p0_steady (const AssemblyContext & c, unsigned int qp) const inline inherited
Definition at line 158 of file low_mach_navier_stokes_base.h.
   {
     libMesh::Real p0;
     if( this->_enable_thermo_press_calc )
       {
         p0 = c.interior_value( _p0_var, qp );
       }
     else
       {
         p0 = _p0;
       }
     return p0;
   }
template<class V , class SH , class TC > libMesh::Real GRINS::LowMachNavierStokesBase< V, SH, TC >::get_p0_steady (const AssemblyContext & c, const libMesh::Point & p) const inline inherited
Definition at line 192 of file low_mach_navier_stokes_base.h.
   {
     libMesh::Real p0;
     if( this->_enable_thermo_press_calc )
       {
         p0 = c.point_value( _p0_var, p );
       }
     else
       {
         p0 = _p0;
       }
     return p0;
   }
template<class V , class SH , class TC > libMesh::Real GRINS::LowMachNavierStokesBase< V, SH, TC >::get_p0_steady_side (const AssemblyContext & c, unsigned int qp) const inline inherited
Definition at line 175 of file low_mach_navier_stokes_base.h.
   {
     libMesh::Real p0;
     if( this->_enable_thermo_press_calc )
       {
         p0 = c.side_value( _p0_var, qp );
       }
     else
       {
         p0 = _p0;
       }
     return p0;
   }
template<class V , class SH , class TC > libMesh::Real GRINS::LowMachNavierStokesBase< V, SH, TC >::get_p0_transient (AssemblyContext & c, unsigned int qp) const inline inherited
Definition at line 209 of file low_mach_navier_stokes_base.h.
   {
     libMesh::Real p0;
     if( this->_enable_thermo_press_calc )
       {
         p0 = c.fixed_interior_value( _p0_var, qp );
       }
     else
       {
         p0 = _p0;
       }
     return p0;
   }
void GRINS::Physics::init_bcs (libMesh::FEMSystem * system) inherited
Definition at line 118 of file physics.C.
References GRINS::Physics::_bc_handler, GRINS::BCHandlingBase::init_bc_data(), GRINS::BCHandlingBase::init_dirichlet_bc_func_objs(), GRINS::BCHandlingBase::init_dirichlet_bcs(), and GRINS::BCHandlingBase::init_periodic_bcs().
   {
     // Only need to init BC's if the physics actually created a handler
     if( _bc_handler )
       {
         _bc_handler->init_bc_data( *system );
         _bc_handler->init_dirichlet_bcs( system );
         _bc_handler->init_dirichlet_bc_func_objs( system );
         _bc_handler->init_periodic_bcs( system );
       }
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::init_context (AssemblyContext & context) virtual
Initialize context for added physics variables.
Reimplemented from GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >.
Definition at line 109 of file low_mach_navier_stokes.C.
References GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::init_context().
   {
     // First call base class
     LowMachNavierStokesBase<Mu,SH,TC>::init_context(context);
     // We also need the side shape functions, etc.
     context.get_side_fe(this->_u_var)->get_JxW();
     context.get_side_fe(this->_u_var)->get_phi();
     context.get_side_fe(this->_u_var)->get_dphi();
     context.get_side_fe(this->_u_var)->get_xyz();
     context.get_side_fe(this->_T_var)->get_JxW();
     context.get_side_fe(this->_T_var)->get_phi();
     context.get_side_fe(this->_T_var)->get_dphi();
     context.get_side_fe(this->_T_var)->get_xyz();
     return;
   }
void GRINS::Physics::init_ics (libMesh::FEMSystem * system, libMesh::CompositeFunction< libMesh::Number > & all_ics) inherited
Definition at line 133 of file physics.C.
References GRINS::Physics::_ic_handler, and GRINS::ICHandlingBase::init_ic_data().
   {
     if( _ic_handler )
       {
         _ic_handler->init_ic_data( *system, all_ics );
       }
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokesBase< Mu, SH, TC >::init_variables (libMesh::FEMSystem * system) virtual inherited
Initialize variables for this physics.
Implements GRINS::Physics.
Definition at line 130 of file low_mach_navier_stokes_base.C.
   {
     // Get libMesh to assign an index for each variable
     this->_dim = system->get_mesh().mesh_dimension();
     _u_var = system->add_variable( _u_var_name, this->_V_order, _V_FE_family);
     _v_var = system->add_variable( _v_var_name, this->_V_order, _V_FE_family);
     if (_dim == 3)
       _w_var = system->add_variable( _w_var_name, this->_V_order, _V_FE_family);
     else
       _w_var = _u_var;
     _p_var = system->add_variable( _p_var_name, this->_P_order, _P_FE_family);
     _T_var = system->add_variable( _T_var_name, this->_T_order, _T_FE_family);
     /* If we need to compute the thermodynamic pressure, we force this to be a first
        order scalar variable. */
     if( _enable_thermo_press_calc )
       _p0_var = system->add_variable( _p0_var_name, libMesh::FIRST, libMesh::SCALAR);
     return;
   }
bool GRINS::Physics::is_steady () const inherited
Returns whether or not this physics is being solved with a steady solver.
Definition at line 103 of file physics.C.
References GRINS::Physics::_is_steady.
Referenced by GRINS::Physics::set_is_steady().
   {
     return _is_steady;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::mass_residual (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
Reimplemented from GRINS::Physics.
Definition at line 188 of file low_mach_navier_stokes.C.
   {
     this->assemble_continuity_mass_residual( compute_jacobian, context );
     this->assemble_momentum_mass_residual( compute_jacobian, context );
     this->assemble_energy_mass_residual( compute_jacobian, context );
     if( this->_enable_thermo_press_calc )
       this->assemble_thermo_press_mass_residual( compute_jacobian, context );
     return;
   }
void GRINS::Physics::nonlocal_constraint (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Constraint part(s) of physics for scalar variables.
Reimplemented in GRINS::ScalarODE.
Definition at line 250 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_constraint().
   {
     return;
   }
void GRINS::Physics::nonlocal_mass_residual (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Mass matrix part(s) for scalar variables.
Reimplemented in GRINS::ScalarODE, and GRINS::AveragedTurbine< Viscosity >.
Definition at line 264 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_mass_residual().
   {
     return;
   }
void GRINS::Physics::nonlocal_time_derivative (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Time dependent part(s) of physics for scalar variables.
Reimplemented in GRINS::AveragedTurbine< Viscosity >, and GRINS::ScalarODE.
Definition at line 229 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_time_derivative().
   {
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::read_input_options (const GetPot & input) virtual
Read options from GetPot input file.
Reimplemented from GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >.
Definition at line 67 of file low_mach_navier_stokes.C.
References GRINS::low_mach_navier_stokes.
Referenced by GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokes().
   {
     // Other quantities read in base class
     // Read pressure pinning information
     this->_pin_pressure = input("Physics/"+low_mach_navier_stokes+"/pin_pressure", false );
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokesBase< Mu, SH, TC >::register_parameter (const std::string & param_name, libMesh::ParameterMultiPointer< libMesh::Number > & param_pointer) const virtual inherited
Each subclass will register its copy of an independent.
Reimplemented from GRINS::ParameterUser.
Definition at line 198 of file low_mach_navier_stokes_base.C.
References GRINS::ParameterUser::register_parameter().
   {
     ParameterUser::register_parameter(param_name, param_pointer);
     _mu.register_parameter(param_name, param_pointer);
     _cp.register_parameter(param_name, param_pointer);
     _k.register_parameter(param_name, param_pointer);
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::register_postprocessing_vars (const GetPot & input, PostProcessedQuantities< libMesh::Real > & postprocessing) virtual
Register postprocessing variables for LowMachNavierStokes.
Reimplemented from GRINS::Physics.
Definition at line 78 of file low_mach_navier_stokes.C.
References GRINS::low_mach_navier_stokes, and GRINS::PostProcessedQuantities< NumericType >::register_quantity().
   {
     std::string section = "Physics/"+low_mach_navier_stokes+"/output_vars";
     if( input.have_variable(section) )
       {
         unsigned int n_vars = input.vector_variable_size(section);
         for( unsigned int v = 0; v < n_vars; v++ )
           {
             std::string name = input(section,"DIE!",v);
             if( name == std::string("rho") )
               {
                 this->_rho_index = postprocessing.register_quantity( name );
               }
             else
               {
                 std::cerr << "Error: Invalue output_vars value for "+low_mach_navier_stokes << std::endl
                           << "       Found " << name << std::endl
                           << "       Acceptable values are: rho" << std::endl;
                 libmesh_error();
               }
           }
       }
     return;
   }
template<class V , class SH , class TC > libMesh::Real GRINS::LowMachNavierStokesBase< V, SH, TC >::rho (libMesh::Real T, libMesh::Real p0) const inline inherited
Definition at line 144 of file low_mach_navier_stokes_base.h.
   {
     return p0/(this->_R*T);
   }
void GRINS::Physics::set_is_steady (bool is_steady) inherited
Sets whether this physics is to be solved with a steady solver or not.
Since the member variable is static, only needs to be called on a single physics.
Definition at line 97 of file physics.C.
References GRINS::Physics::_is_steady, and GRINS::Physics::is_steady().
   {
     _is_steady = is_steady;
     return;
   }
void GRINS::ParameterUser::set_parameter (libMesh::Number & param_variable, const GetPot & input, const std::string & param_name, libMesh::Number param_default) virtual inherited
Each subclass can simultaneously read a parameter value from.
Definition at line 35 of file parameter_user.C.
References GRINS::ParameterUser::_my_name, and GRINS::ParameterUser::_my_parameters.
Referenced by GRINS::AveragedFanAdjointStabilization< Viscosity >::AveragedFanAdjointStabilization(), GRINS::AveragedTurbineAdjointStabilization< Viscosity >::AveragedTurbineAdjointStabilization(), GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::BoussinesqBuoyancyAdjointStabilization(), GRINS::BoussinesqBuoyancyBase::BoussinesqBuoyancyBase(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::BoussinesqBuoyancySPGSMStabilization(), GRINS::ConstantConductivity::ConstantConductivity(), GRINS::ConstantPrandtlConductivity::ConstantPrandtlConductivity(), GRINS::ConstantSourceFunction::ConstantSourceFunction(), GRINS::ConstantSourceTerm::ConstantSourceTerm(), GRINS::ConstantSpecificHeat::ConstantSpecificHeat(), GRINS::ConstantViscosity::ConstantViscosity(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticCableConstantGravity::ElasticCableConstantGravity(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransferBase< Conductivity >::HeatTransferBase(), GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase(), GRINS::AverageNusseltNumber::init(), GRINS::MooneyRivlin::MooneyRivlin(), GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase(), GRINS::HookesLaw1D::read_input_options(), GRINS::HookesLaw::read_input_options(), GRINS::AxisymmetricBoussinesqBuoyancy::read_input_options(), and GRINS::VelocityDragAdjointStabilization< Viscosity >::VelocityDragAdjointStabilization().
   {
     param_variable = input(param_name, param_default);
     libmesh_assert_msg(!_my_parameters.count(param_name),
       "ERROR: " << _my_name << " double-registered parameter " <<
       param_name);
     _my_parameters[param_name] = &param_variable;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokesBase< Mu, SH, TC >::set_time_evolving_vars (libMesh::FEMSystem * system) virtual inherited
Sets velocity variables to be time-evolving.
Reimplemented from GRINS::Physics.
Definition at line 155 of file low_mach_navier_stokes_base.C.
   {
     const unsigned int dim = system->get_mesh().mesh_dimension();
     system->time_evolving(_u_var);
     system->time_evolving(_v_var);
     if (dim == 3)
       system->time_evolving(_w_var);
     system->time_evolving(_T_var);
     system->time_evolving(_p_var);
     if( _enable_thermo_press_calc )
       system->time_evolving(_p0_var);
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::side_constraint (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Constraint part(s) of physics for boundaries of elements on the domain boundary.
Reimplemented from GRINS::Physics.
Definition at line 174 of file low_mach_navier_stokes.C.
   {
     // Pin p = p_value at p_point
     if( this->_pin_pressure )
       {
         this->_p_pinning.pin_value( context, compute_jacobian, this->_p_var);
       }
     return;
   }
template<class Mu , class SH , class TC > void GRINS::LowMachNavierStokes< Mu, SH, TC >::side_time_derivative (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
Reimplemented from GRINS::Physics.
Definition at line 153 of file low_mach_navier_stokes.C.
   {
     if( this->_enable_thermo_press_calc )
       {
 #ifdef GRINS_USE_GRVY_TIMERS
         this->_timer->BeginTimer("LowMachNavierStokes::side_time_derivative");
 #endif
         this->assemble_thermo_press_side_time_deriv( compute_jacobian, context );
 #ifdef GRINS_USE_GRVY_TIMERS
         this->_timer->EndTimer("LowMachNavierStokes::side_time_derivative");
 #endif
       }
     return;
   }
template<class V , class SH , class TC > libMesh::Real GRINS::LowMachNavierStokesBase< V, SH, TC >::T (const libMesh::Point & p, const AssemblyContext & c) const inline inherited
Definition at line 137 of file low_mach_navier_stokes_base.h.
   {
     return c.point_value(_T_var,p);
   }
Member Data Documentation
GRINS::BCHandlingBase* GRINS::Physics::_bc_handler protected inherited
Definition at line 256 of file physics.h.
Referenced by GRINS::Physics::attach_dirichlet_bound_func(), GRINS::Physics::attach_neumann_bound_func(), GRINS::AxisymmetricHeatTransfer< Conductivity >::AxisymmetricHeatTransfer(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::Physics::get_bc_handler(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransfer< Conductivity >::HeatTransfer(), GRINS::IncompressibleNavierStokes< Viscosity >::IncompressibleNavierStokes(), GRINS::Physics::init_bcs(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokes(), GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::ReactingLowMachNavierStokes(), GRINS::SpalartAllmaras< Viscosity >::SpalartAllmaras(), GRINS::Stokes< Viscosity >::Stokes(), and GRINS::Physics::~Physics().
template<class Viscosity , class SpecificHeat , class ThermalConductivity > SpecificHeat GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_cp protected inherited
Specific heat object.
Definition at line 118 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > unsigned int GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_dim protected inherited
Physical dimension of problem.
Definition at line 95 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > bool GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_enable_thermo_press_calc protected inherited
Flag to enable thermodynamic pressure calculation.
Definition at line 127 of file low_mach_navier_stokes_base.h.
std::set<libMesh::subdomain_id_type> GRINS::Physics::_enabled_subdomains protected inherited
Subdomains on which the current Physics class is enabled.
Definition at line 261 of file physics.h.
Referenced by GRINS::Physics::enabled_on_elem(), and GRINS::Physics::read_input_options().
template<class Viscosity , class SpecificHeat , class ThermalConductivity > libMesh::Point GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_g protected inherited
Gravity vector.
Definition at line 124 of file low_mach_navier_stokes_base.h.
GRINS::ICHandlingBase* GRINS::Physics::_ic_handler protected inherited
Definition at line 258 of file physics.h.
Referenced by GRINS::AveragedTurbine< Viscosity >::AveragedTurbine(), GRINS::AxisymmetricHeatTransfer< Conductivity >::AxisymmetricHeatTransfer(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::Physics::get_ic_handler(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransfer< Conductivity >::HeatTransfer(), GRINS::IncompressibleNavierStokes< Viscosity >::IncompressibleNavierStokes(), GRINS::Physics::init_ics(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokes(), GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::ReactingLowMachNavierStokes(), GRINS::ScalarODE::ScalarODE(), GRINS::SpalartAllmaras< Viscosity >::SpalartAllmaras(), GRINS::Stokes< Viscosity >::Stokes(), and GRINS::Physics::~Physics().
bool GRINS::Physics::_is_axisymmetric protected inherited
Definition at line 268 of file physics.h.
Referenced by GRINS::HeatTransfer< Conductivity >::HeatTransfer(), GRINS::IncompressibleNavierStokes< Viscosity >::IncompressibleNavierStokes(), GRINS::Physics::Physics(), and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::ReactingLowMachNavierStokes().
bool GRINS::Physics::_is_steady = false static protected inherited
Caches whether or not the solver that's being used is steady or not.
This is need, for example, in flow stabilization as the tau terms change depending on whether the solver is steady or unsteady.
Definition at line 266 of file physics.h.
Referenced by GRINS::Physics::is_steady(), and GRINS::Physics::set_is_steady().
template<class Viscosity , class SpecificHeat , class ThermalConductivity > ThermalConductivity GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_k protected inherited
Thermal conductivity object.
Definition at line 121 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > Viscosity GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_mu protected inherited
Viscosity object.
Definition at line 115 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > libMesh::Number GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_p0 protected inherited
Definition at line 92 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > libMesh::Number GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_p0_over_R protected inherited
Thermodynamic pressure divided by gas constant.
Definition at line 90 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > VariableIndex GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_p0_var protected inherited
Definition at line 103 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > std::string GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_p0_var_name protected inherited
Definition at line 106 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > GRINSEnums::FEFamily GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_P_FE_family protected inherited
Definition at line 109 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > GRINSEnums::Order GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_P_order protected inherited
Definition at line 112 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > PressurePinning GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::_p_pinning protected
Definition at line 90 of file low_mach_navier_stokes.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > VariableIndex GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_p_var protected inherited
Definition at line 101 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > std::string GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_p_var_name protected inherited
Definition at line 106 of file low_mach_navier_stokes_base.h.
const PhysicsName GRINS::Physics::_physics_name protected inherited
Name of the physics object. Used for reading physics specific inputs.
We use a reference because the physics names are const global objects in GRINS namespace
No, we use a copy, because otherwise as soon as the memory in std::set<std::string> requested_physics gets overwritten we get in trouble.
Definition at line 254 of file physics.h.
Referenced by GRINS::SourceTermBase::parse_var_info(), and GRINS::Physics::read_input_options().
template<class Viscosity , class SpecificHeat , class ThermalConductivity > bool GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::_pin_pressure protected
Enable pressure pinning.
Definition at line 88 of file low_mach_navier_stokes.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > libMesh::Number GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_R protected inherited
Definition at line 92 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > unsigned int GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::_rho_index protected
Cache index for density post-processing.
Definition at line 93 of file low_mach_navier_stokes.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > libMesh::Number GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_T0 protected inherited
Definition at line 92 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > GRINSEnums::FEFamily GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_T_FE_family protected inherited
Definition at line 109 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > GRINSEnums::Order GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_T_order protected inherited
Definition at line 112 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > VariableIndex GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_T_var protected inherited
Definition at line 102 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > std::string GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_T_var_name protected inherited
Definition at line 106 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > VariableIndex GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_u_var protected inherited
Indices for each (owned) variable;.
Definition at line 98 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > std::string GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_u_var_name protected inherited
Names of each (owned) variable in the system.
Definition at line 106 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > GRINSEnums::FEFamily GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_V_FE_family protected inherited
Element type, read from input.
Definition at line 109 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > GRINSEnums::Order GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_V_order protected inherited
Element orders, read from input.
Definition at line 112 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > VariableIndex GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_v_var protected inherited
Definition at line 99 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > std::string GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_v_var_name protected inherited
Definition at line 106 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > VariableIndex GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_w_var protected inherited
Definition at line 100 of file low_mach_navier_stokes_base.h.
template<class Viscosity , class SpecificHeat , class ThermalConductivity > std::string GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::_w_var_name protected inherited
Definition at line 106 of file low_mach_navier_stokes_base.h.
The documentation for this class was generated from the following files:
src/physics/include/grins/low_mach_navier_stokes.h
src/physics/src/low_mach_navier_stokes.C