GRINS-0.6.0: GRINS::PrimitiveTempVariables Class Reference
GRINS::PrimitiveTempVariables Class Reference
#include <primitive_temp_variables.h>
Public Member Functions
PrimitiveTempVariables (const GetPot &input)
~PrimitiveTempVariables ()
virtual void init (libMesh::FEMSystem *system)
VariableIndex T_var () const
Protected Attributes
VariableIndex _T_var
Indices for each variable;.
std::string _T_var_name
Names of each variable in the system.
Private Member Functions
PrimitiveTempVariables ()
Detailed Description
Definition at line 40 of file primitive_temp_variables.h.
Constructor & Destructor Documentation
GRINS::PrimitiveTempVariables::PrimitiveTempVariables (const GetPot & input)
Definition at line 37 of file primitive_temp_variables.C.
     : _T_var(invalid_var_index),
       _T_var_name( input("Physics/VariableNames/Temperature", T_var_name_default ) )
   {
     return;
   }
GRINS::PrimitiveTempVariables::~PrimitiveTempVariables ()
Definition at line 44 of file primitive_temp_variables.C.
   {
     return;
   }
GRINS::PrimitiveTempVariables::PrimitiveTempVariables () private
Member Function Documentation
void GRINS::PrimitiveTempVariables::init (libMesh::FEMSystem * system) virtual
Reimplemented in GRINS::PrimitiveTempFEVariables.
Definition at line 49 of file primitive_temp_variables.C.
References _T_var, and _T_var_name.
Referenced by GRINS::HeatTransferStabilizationHelper::init(), and GRINS::HeatTransferBCHandling::init_bc_data().
   {
     libmesh_assert( system->has_variable(_T_var_name) );
     _T_var = system->variable_number( _T_var_name );
     return;
   }
VariableIndex GRINS::PrimitiveTempVariables::T_var () const inline
Definition at line 66 of file primitive_temp_variables.h.
References _T_var.
Referenced by GRINS::HeatTransferStabilizationHelper::compute_res_energy_steady(), GRINS::HeatTransferStabilizationHelper::compute_res_energy_transient(), GRINS::BoussinesqBuoyancy::element_time_derivative(), GRINS::HeatTransferBCHandling::user_apply_neumann_bcs(), and GRINS::HeatTransferBCHandling::user_init_dirichlet_bcs().
   {
     return _T_var;
   }
Member Data Documentation
VariableIndex GRINS::PrimitiveTempVariables::_T_var protected
Indices for each variable;.
Definition at line 54 of file primitive_temp_variables.h.
Referenced by init(), GRINS::PrimitiveTempFEVariables::init(), and T_var().
std::string GRINS::PrimitiveTempVariables::_T_var_name protected
Names of each variable in the system.
Definition at line 57 of file primitive_temp_variables.h.
Referenced by init(), and GRINS::PrimitiveTempFEVariables::init().
The documentation for this class was generated from the following files:
src/physics/include/grins/primitive_temp_variables.h
src/physics/src/primitive_temp_variables.C