GRINS-0.6.0: GRINS::CanteraTransport Class Reference
GRINS::CanteraTransport Class Reference
Wrapper class for evaluating transport properties using Cantera.
#include <cantera_transport.h>
Public Member Functions
CanteraTransport (CanteraMixture &mixture)
~CanteraTransport ()
libMesh::Real mu (const CachedValues &cache, unsigned int qp) const
libMesh::Real k (const CachedValues &cache, unsigned int qp) const
void D (const CachedValues &cache, unsigned int qp, std::vector< libMesh::Real > &D) const
Protected Attributes
Cantera::IdealGasMix & _cantera_gas
Cantera::Transport & _cantera_transport
Private Member Functions
CanteraTransport ()
Detailed Description
Wrapper class for evaluating transport properties using Cantera.
This class is expected to be constructed after threads have been forked and will only live during the lifetime of the thread. Note that this documentation will always be built regardless if Cantera is included in the GRINS build or not. Check configure output to confirm that Cantera was included in the build if you wish to use it.
Definition at line 63 of file cantera_transport.h.
Constructor & Destructor Documentation
GRINS::CanteraTransport::CanteraTransport (CanteraMixture & mixture)
Definition at line 49 of file cantera_transport.C.
     : _cantera_gas( mixture.get_chemistry() ),
       _cantera_transport( mixture.get_transport() )
   {
     return;
   }
GRINS::CanteraTransport::~CanteraTransport ()
Definition at line 56 of file cantera_transport.C.
   {
     return;
   }
GRINS::CanteraTransport::CanteraTransport () private
Member Function Documentation
void GRINS::CanteraTransport::D (const CachedValues & cache, unsigned int qp, std::vector< libMesh::Real > & D) const
Todo:
Need to make sure this will work in a threaded environment. Not sure if we will get thread lock here or not.
Definition at line 123 of file cantera_transport.C.
References _cantera_gas, _cantera_transport, GRINS::CachedValues::get_cached_values(), GRINS::CachedValues::get_cached_vector_values(), GRINS::Cache::MASS_FRACTIONS, GRINS::Cache::TEMPERATURE, and GRINS::Cache::THERMO_PRESSURE.
Referenced by GRINS::CanteraEvaluator::D(), and main().
   {
     const libMesh::Real T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     const libMesh::Real P = cache.get_cached_values(Cache::THERMO_PRESSURE)[qp];
     const std::vector<libMesh::Real>& Y = cache.get_cached_vector_values(Cache::MASS_FRACTIONS)[qp];
     libmesh_assert_equal_to( Y.size(), D.size() );
     libmesh_assert_equal_to( Y.size(), _cantera_gas.nSpecies() );
     {
       libMesh::Threads::spin_mutex::scoped_lock lock(cantera_mutex);
       try
         {
           _cantera_gas.setState_TPY(T, P, &Y[0]);
           _cantera_transport.getMixDiffCoeffsMass(&D[0]);
         }
       catch(Cantera::CanteraError)
         {
           Cantera::showErrors(std::cerr);
           libmesh_error();
         }
     }
     return;
   }
libMesh::Real GRINS::CanteraTransport::k (const CachedValues & cache, unsigned int qp) const
Todo:
Need to make sure this will work in a threaded environment. Not sure if we will get thread lock here or not.
Definition at line 92 of file cantera_transport.C.
References _cantera_gas, _cantera_transport, GRINS::CachedValues::get_cached_values(), GRINS::CachedValues::get_cached_vector_values(), GRINS::Cache::MASS_FRACTIONS, GRINS::Cache::TEMPERATURE, and GRINS::Cache::THERMO_PRESSURE.
Referenced by GRINS::CanteraEvaluator::k(), main(), and GRINS::CanteraEvaluator::mu_and_k().
   {
     const libMesh::Real T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     const libMesh::Real P = cache.get_cached_values(Cache::THERMO_PRESSURE)[qp];
     const std::vector<libMesh::Real>& Y = cache.get_cached_vector_values(Cache::MASS_FRACTIONS)[qp];
     libmesh_assert_equal_to( Y.size(), _cantera_gas.nSpecies() );
     libMesh::Real k = 0.0;
     {
       libMesh::Threads::spin_mutex::scoped_lock lock(cantera_mutex);
       try
         {
           _cantera_gas.setState_TPY(T, P, &Y[0]);
           k =  _cantera_transport.thermalConductivity();
         }
       catch(Cantera::CanteraError)
         {
           Cantera::showErrors(std::cerr);
           libmesh_error();
         }
     }
     return k;
   }
libMesh::Real GRINS::CanteraTransport::mu (const CachedValues & cache, unsigned int qp) const
Todo:
Need to make sure this will work in a threaded environment. Not sure if we will get thread lock here or not.
Definition at line 61 of file cantera_transport.C.
References _cantera_gas, _cantera_transport, GRINS::CachedValues::get_cached_values(), GRINS::CachedValues::get_cached_vector_values(), GRINS::Cache::MASS_FRACTIONS, GRINS::Cache::TEMPERATURE, and GRINS::Cache::THERMO_PRESSURE.
Referenced by main(), GRINS::CanteraEvaluator::mu(), and GRINS::CanteraEvaluator::mu_and_k().
   {
     const libMesh::Real T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     const libMesh::Real P = cache.get_cached_values(Cache::THERMO_PRESSURE)[qp];
     const std::vector<libMesh::Real>& Y = cache.get_cached_vector_values(Cache::MASS_FRACTIONS)[qp];
     libmesh_assert_equal_to( Y.size(), _cantera_gas.nSpecies() );
     libMesh::Real mu = 0.0;
     {
       libMesh::Threads::spin_mutex::scoped_lock lock(cantera_mutex);
       try
         {
           _cantera_gas.setState_TPY(T, P, &Y[0]);
           mu =  _cantera_transport.viscosity();
         }
       catch(Cantera::CanteraError)
         {
           Cantera::showErrors(std::cerr);
           libmesh_error();
         }
     }
     return mu;
   }
Member Data Documentation
Cantera::IdealGasMix& GRINS::CanteraTransport::_cantera_gas protected
Definition at line 79 of file cantera_transport.h.
Referenced by D(), k(), and mu().
Cantera::Transport& GRINS::CanteraTransport::_cantera_transport protected
Definition at line 81 of file cantera_transport.h.
Referenced by D(), k(), and mu().
The documentation for this class was generated from the following files:
src/properties/include/grins/cantera_transport.h
src/properties/src/cantera_transport.C