GRINS-0.6.0: GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator > Class Template Reference
GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator > Class Template Reference
#include <reacting_low_mach_navier_stokes_base.h>
Public Member Functions
ReactingLowMachNavierStokesBase (const PhysicsName &physics_name, const GetPot &input)
~ReactingLowMachNavierStokesBase ()
virtual void read_input_options (const GetPot &input)
Read options from GetPot input file.
virtual void init_variables (libMesh::FEMSystem *system)
Initialize variables for this physics.
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Sets velocity variables to be time-evolving.
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
unsigned int n_species () const
libMesh::Real T (const libMesh::Point &p, const AssemblyContext &c) const
void mass_fractions (const libMesh::Point &p, const AssemblyContext &c, std::vector< libMesh::Real > &mass_fracs) const
libMesh::Real rho (libMesh::Real T, libMesh::Real p0, libMesh::Real R_mix) const
libMesh::Real get_p0_steady (const AssemblyContext &c, unsigned int qp) const
libMesh::Real get_p0_steady_side (const AssemblyContext &c, unsigned int qp) const
libMesh::Real get_p0_steady (const AssemblyContext &c, const libMesh::Point &p) const
libMesh::Real get_p0_transient (const AssemblyContext &c, unsigned int qp) const
const Mixture & gas_mixture () const
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for element interiors.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_bcs (libMesh::FEMSystem *system)
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
void attach_neumann_bound_func (GRINS::NBCContainer &neumann_bcs)
void attach_dirichlet_bound_func (const GRINS::DBCContainer &dirichlet_bc)
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
BCHandlingBase * get_bc_handler ()
ICHandlingBase * get_ic_handler ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiPointer< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Attributes
Mixture _gas_mixture
libMesh::Number _p0
unsigned int _dim
Physical dimension of problem.
unsigned int _n_species
Number of species.
std::vector< VariableIndex > _species_vars
Indices for each (owned) variable;.
VariableIndex _u_var
VariableIndex _v_var
VariableIndex _w_var
VariableIndex _p_var
VariableIndex _T_var
VariableIndex _p0_var
std::vector< std::string > _species_var_names
Names of each (owned) variable in the system.
std::string _u_var_name
std::string _v_var_name
std::string _w_var_name
std::string _p_var_name
std::string _T_var_name
std::string _p0_var_name
GRINSEnums::FEFamily _species_FE_family
Element type, read from input.
GRINSEnums::FEFamily _V_FE_family
GRINSEnums::FEFamily _P_FE_family
GRINSEnums::FEFamily _T_FE_family
GRINSEnums::Order _species_order
Element orders, read from input.
GRINSEnums::Order _V_order
GRINSEnums::Order _P_order
GRINSEnums::Order _T_order
libMesh::Point _g
Gravity vector.
bool _enable_thermo_press_calc
Flag to enable thermodynamic pressure calculation.
bool _fixed_density
libMesh::Real _fixed_rho_value
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::BCHandlingBase * _bc_handler
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
bool _is_axisymmetric
Static Protected Attributes
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
Private Member Functions
ReactingLowMachNavierStokesBase ()
Detailed Description
template<typename Mixture, typename Evaluator>
class GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >
Definition at line 39 of file reacting_low_mach_navier_stokes_base.h.
Constructor & Destructor Documentation
template<typename Mixture , typename Evaluator > GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase (const PhysicsName & physics_name, const GetPot & input)
Definition at line 46 of file reacting_low_mach_navier_stokes_base.C.
References GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_fixed_rho_value, GRINS::reacting_low_mach_navier_stokes, GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::read_input_options(), and GRINS::ParameterUser::set_parameter().
     : Physics(physics_name, input),
       _gas_mixture(input),
       _fixed_density( input("Physics/"+reacting_low_mach_navier_stokes+"/fixed_density", false ) ),
       _fixed_rho_value(0.0)
   {
     this->set_parameter
       (_fixed_rho_value, input,
        "Physics/"+reacting_low_mach_navier_stokes+"/fixed_rho_value", 0.0 );
     this->read_input_options(input);
     return;
   }
template<typename Mixture , typename Evaluator > GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::~ReactingLowMachNavierStokesBase ()
Definition at line 63 of file reacting_low_mach_navier_stokes_base.C.
   {
     return;
   }
template<typename Mixture, typename Evaluator> GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase () private
Member Function Documentation
void GRINS::Physics::attach_dirichlet_bound_func (const GRINS::DBCContainer & dirichlet_bc) inherited
Definition at line 150 of file physics.C.
References GRINS::Physics::_bc_handler, and GRINS::BCHandlingBase::attach_dirichlet_bound_func().
   {
     _bc_handler->attach_dirichlet_bound_func( dirichlet_bc );
     return;
   }
void GRINS::Physics::attach_neumann_bound_func (GRINS::NBCContainer & neumann_bcs) inherited
Definition at line 144 of file physics.C.
References GRINS::Physics::_bc_handler, and GRINS::BCHandlingBase::attach_neumann_bound_func().
   {
     _bc_handler->attach_neumann_bound_func( neumann_bcs );
     return;
   }
void GRINS::Physics::auxiliary_init (MultiphysicsSystem & system) virtual inherited
Any auxillary initialization a Physics class may need.
This is called after all variables are added, so this method can safely query the MultiphysicsSystem about variable information.
Definition at line 113 of file physics.C.
   {
     return;
   }
void GRINS::Physics::compute_element_constraint_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 185 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::element_constraint().
   {
     return;
   }
void GRINS::Physics::compute_element_time_derivative_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Reimplemented in GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >.
Definition at line 167 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::element_time_derivative().
   {
     return;
   }
void GRINS::Physics::compute_mass_residual_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 203 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::mass_residual().
   {
     return;
   }
void GRINS::Physics::compute_nonlocal_constraint_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 197 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_constraint().
   {
     return;
   }
void GRINS::Physics::compute_nonlocal_mass_residual_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 209 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_mass_residual().
   {
     return;
   }
void GRINS::Physics::compute_nonlocal_time_derivative_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 179 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_time_derivative().
   {
     return;
   }
void GRINS::Physics::compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext & context, const libMesh::Point & point, libMesh::Real & value) virtual inherited
Reimplemented in GRINS::IncompressibleNavierStokes< Viscosity >, GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >, GRINS::HeatTransfer< Conductivity >, GRINS::ParsedVelocitySource< Viscosity >, GRINS::VelocityPenalty< Viscosity >, GRINS::ElasticMembrane< StressStrainLaw >, and GRINS::ElasticCable< StressStrainLaw >.
Definition at line 271 of file physics.C.
   {
     return;
   }
void GRINS::Physics::compute_side_constraint_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 191 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::side_constraint().
   {
     return;
   }
void GRINS::Physics::compute_side_time_derivative_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Reimplemented in GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >.
Definition at line 173 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::side_time_derivative().
   {
     return;
   }
void GRINS::Physics::element_constraint (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Constraint part(s) of physics for element interiors.
Reimplemented in GRINS::IncompressibleNavierStokes< Viscosity >, GRINS::AveragedTurbineAdjointStabilization< Viscosity >, GRINS::VelocityDragAdjointStabilization< Viscosity >, GRINS::AveragedFanAdjointStabilization< Viscosity >, GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >, GRINS::ElasticMembrane< StressStrainLaw >, GRINS::Stokes< Viscosity >, GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >, GRINS::ParsedVelocitySourceAdjointStabilization< Viscosity >, GRINS::VelocityPenaltyAdjointStabilization< Viscosity >, GRINS::IncompressibleNavierStokesAdjointStabilization< Viscosity >, and GRINS::IncompressibleNavierStokesSPGSMStabilization< Viscosity >.
Definition at line 236 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::element_constraint().
   {
     return;
   }
void GRINS::Physics::element_time_derivative (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Time dependent part(s) of physics for element interiors.
Reimplemented in GRINS::SpalartAllmaras< Viscosity >, GRINS::AxisymmetricBoussinesqBuoyancy, GRINS::AxisymmetricHeatTransfer< Conductivity >, GRINS::ParsedVelocitySource< Viscosity >, GRINS::VelocityPenalty< Viscosity >, GRINS::AveragedTurbine< Viscosity >, GRINS::VelocityDrag< Viscosity >, GRINS::AveragedFan< Viscosity >, GRINS::IncompressibleNavierStokes< Viscosity >, GRINS::HeatTransferSource< SourceFunction >, GRINS::BoussinesqBuoyancy, GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::AveragedTurbineAdjointStabilization< Viscosity >, GRINS::HeatTransfer< Conductivity >, GRINS::VelocityDragAdjointStabilization< Viscosity >, GRINS::AveragedFanAdjointStabilization< Viscosity >, GRINS::HeatConduction< Conductivity >, GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >, GRINS::Stokes< Viscosity >, GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >, GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >, GRINS::ElasticCable< StressStrainLaw >, GRINS::ParsedVelocitySourceAdjointStabilization< Viscosity >, GRINS::VelocityPenaltyAdjointStabilization< Viscosity >, GRINS::ElasticMembrane< StressStrainLaw >, GRINS::ParsedSourceTerm, GRINS::SpalartAllmarasSPGSMStabilization< Viscosity >, GRINS::HeatTransferAdjointStabilization< Conductivity >, GRINS::HeatTransferSPGSMStabilization< Conductivity >, GRINS::LowMachNavierStokesBraackStabilization< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::LowMachNavierStokesVMSStabilization< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::ConstantSourceTerm, GRINS::IncompressibleNavierStokesAdjointStabilization< Viscosity >, GRINS::IncompressibleNavierStokesSPGSMStabilization< Viscosity >, GRINS::LowMachNavierStokesSPGSMStabilization< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::ElasticCableConstantGravity, and GRINS::ElasticMembraneConstantPressure.
Definition at line 215 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::element_time_derivative().
   {
     return;
   }
bool GRINS::Physics::enabled_on_elem (const libMesh::Elem * elem) virtual inherited
Find if current physics is active on supplied element.
Definition at line 83 of file physics.C.
References GRINS::Physics::_enabled_subdomains.
   {
     // Check if enabled_subdomains flag has been set and if we're
     // looking at a real element (rather than a nonlocal evaluation)
     if( !elem || _enabled_subdomains.empty() )
       return true;
     // Check if current physics is enabled on elem
     if( _enabled_subdomains.find( elem->subdomain_id() ) == _enabled_subdomains.end() )
       return false;
     return true;
   }
template<typename Mixture , typename Evaluator > const Mixture & GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::gas_mixture () const inline
Definition at line 236 of file reacting_low_mach_navier_stokes_base.h.
   {
     return _gas_mixture;
   }
BCHandlingBase * GRINS::Physics::get_bc_handler () inline inherited
Definition at line 282 of file physics.h.
References GRINS::Physics::_bc_handler.
   {
     return _bc_handler;
   }
ICHandlingBase * GRINS::Physics::get_ic_handler () inline inherited
Definition at line 288 of file physics.h.
References GRINS::Physics::_ic_handler.
   {
     return _ic_handler;
   }
template<typename Mixture , typename Evaluator > libMesh::Real GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::get_p0_steady (const AssemblyContext & c, unsigned int qp) const inline
Definition at line 168 of file reacting_low_mach_navier_stokes_base.h.
   {
     libMesh::Real p0;
     if( this->_enable_thermo_press_calc )
       {
         p0 = c.interior_value( _p0_var, qp );
       }
     else
       {
         p0 = _p0;
       }
     return p0;
   }
template<typename Mixture , typename Evaluator > libMesh::Real GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::get_p0_steady (const AssemblyContext & c, const libMesh::Point & p) const inline
Definition at line 202 of file reacting_low_mach_navier_stokes_base.h.
   {
     libMesh::Real p0;
     if( this->_enable_thermo_press_calc )
       {
         p0 = c.point_value( _p0_var, p );
       }
     else
       {
         p0 = _p0;
       }
     return p0;
   }
template<typename Mixture , typename Evaluator > libMesh::Real GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::get_p0_steady_side (const AssemblyContext & c, unsigned int qp) const inline
Definition at line 185 of file reacting_low_mach_navier_stokes_base.h.
   {
     libMesh::Real p0;
     if( this->_enable_thermo_press_calc )
       {
         p0 = c.side_value( _p0_var, qp );
       }
     else
       {
         p0 = _p0;
       }
     return p0;
   }
template<typename Mixture , typename Evaluator > libMesh::Real GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::get_p0_transient (const AssemblyContext & c, unsigned int qp) const inline
Definition at line 219 of file reacting_low_mach_navier_stokes_base.h.
   {
     libMesh::Real p0;
     if( this->_enable_thermo_press_calc )
       {
         p0 = c.fixed_interior_value( _p0_var, qp );
       }
     else
       {
         p0 = _p0;
       }
     return p0;
   }
void GRINS::Physics::init_bcs (libMesh::FEMSystem * system) inherited
Definition at line 118 of file physics.C.
References GRINS::Physics::_bc_handler, GRINS::BCHandlingBase::init_bc_data(), GRINS::BCHandlingBase::init_dirichlet_bc_func_objs(), GRINS::BCHandlingBase::init_dirichlet_bcs(), and GRINS::BCHandlingBase::init_periodic_bcs().
   {
     // Only need to init BC's if the physics actually created a handler
     if( _bc_handler )
       {
         _bc_handler->init_bc_data( *system );
         _bc_handler->init_dirichlet_bcs( system );
         _bc_handler->init_dirichlet_bc_func_objs( system );
         _bc_handler->init_periodic_bcs( system );
       }
     return;
   }
template<typename Mixture , typename Evaluator > void GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::init_context (AssemblyContext & context) virtual
Initialize context for added physics variables.
Reimplemented from GRINS::Physics.
Reimplemented in GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >.
Definition at line 187 of file reacting_low_mach_navier_stokes_base.C.
Referenced by GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::init_context().
   {
     // We should prerequest all the data
     // we will need to build the linear system
     // or evaluate a quantity of interest.
     context.get_element_fe(_species_vars[0])->get_JxW();
     context.get_element_fe(_species_vars[0])->get_phi();
     context.get_element_fe(_species_vars[0])->get_dphi();
     context.get_element_fe(_species_vars[0])->get_xyz();
     context.get_element_fe(_u_var)->get_JxW();
     context.get_element_fe(_u_var)->get_phi();
     context.get_element_fe(_u_var)->get_dphi();
     context.get_element_fe(_u_var)->get_xyz();
     context.get_element_fe(_T_var)->get_JxW();
     context.get_element_fe(_T_var)->get_phi();
     context.get_element_fe(_T_var)->get_dphi();
     context.get_element_fe(_T_var)->get_xyz();
     context.get_element_fe(_p_var)->get_phi();
     context.get_element_fe(_p_var)->get_xyz();
     return;
   }
void GRINS::Physics::init_ics (libMesh::FEMSystem * system, libMesh::CompositeFunction< libMesh::Number > & all_ics) inherited
Definition at line 133 of file physics.C.
References GRINS::Physics::_ic_handler, and GRINS::ICHandlingBase::init_ic_data().
   {
     if( _ic_handler )
       {
         _ic_handler->init_ic_data( *system, all_ics );
       }
     return;
   }
template<typename Mixture , typename Evaluator > void GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::init_variables (libMesh::FEMSystem * system) virtual
Initialize variables for this physics.
Implements GRINS::Physics.
Definition at line 130 of file reacting_low_mach_navier_stokes_base.C.
   {
     // Get libMesh to assign an index for each variable
     this->_dim = system->get_mesh().mesh_dimension();
     _species_vars.reserve(this->_n_species);
     for( unsigned int i = 0; i < this->_n_species; i++ )
       {
         _species_vars.push_back( system->add_variable( _species_var_names[i],
                                                        this->_species_order, _species_FE_family) );
       }
     _u_var = system->add_variable( _u_var_name, this->_V_order, _V_FE_family);
     _v_var = system->add_variable( _v_var_name, this->_V_order, _V_FE_family);
     if (_dim == 3)
       _w_var = system->add_variable( _w_var_name, this->_V_order, _V_FE_family);
     else
       _w_var = _u_var;
     _p_var = system->add_variable( _p_var_name, this->_P_order, _P_FE_family);
     _T_var = system->add_variable( _T_var_name, this->_T_order, _T_FE_family);
     /* If we need to compute the thermodynamic pressure, we force this to be a first
        order scalar variable. */
     if( _enable_thermo_press_calc )
       _p0_var = system->add_variable( _p0_var_name, libMesh::FIRST, libMesh::SCALAR);
     return;
   }
bool GRINS::Physics::is_steady () const inherited
Returns whether or not this physics is being solved with a steady solver.
Definition at line 103 of file physics.C.
References GRINS::Physics::_is_steady.
Referenced by GRINS::Physics::set_is_steady().
   {
     return _is_steady;
   }
template<typename Mixture , typename Evaluator > void GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::mass_fractions (const libMesh::Point & p, const AssemblyContext & c, std::vector< libMesh::Real > & mass_fracs) const inline
Definition at line 137 of file reacting_low_mach_navier_stokes_base.h.
   {
     libmesh_assert_equal_to(mass_fracs.size(), this->_n_species);
     for( unsigned int var = 0; var < this->_n_species; var++ )
       {
         mass_fracs[var] = c.point_value(_species_vars[var],p);
       }
     return;
   }
void GRINS::Physics::mass_residual (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
Reimplemented in GRINS::AxisymmetricHeatTransfer< Conductivity >, GRINS::IncompressibleNavierStokes< Viscosity >, GRINS::SpalartAllmaras< Viscosity >, GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::HeatTransfer< Conductivity >, GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >, GRINS::Stokes< Viscosity >, GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >, GRINS::ElasticMembrane< StressStrainLaw >, GRINS::ElasticCable< StressStrainLaw >, GRINS::HeatConduction< Conductivity >, GRINS::IncompressibleNavierStokesAdjointStabilization< Viscosity >, GRINS::IncompressibleNavierStokesSPGSMStabilization< Viscosity >, GRINS::SpalartAllmarasSPGSMStabilization< Viscosity >, GRINS::HeatTransferAdjointStabilization< Conductivity >, GRINS::HeatTransferSPGSMStabilization< Conductivity >, GRINS::LowMachNavierStokesBraackStabilization< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::LowMachNavierStokesVMSStabilization< Viscosity, SpecificHeat, ThermalConductivity >, and GRINS::LowMachNavierStokesSPGSMStabilization< Viscosity, SpecificHeat, ThermalConductivity >.
Definition at line 257 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::mass_residual().
   {
     return;
   }
template<typename Mixture , typename Evaluator > unsigned int GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::n_species () const inline
Definition at line 125 of file reacting_low_mach_navier_stokes_base.h.
   { return _n_species; }
void GRINS::Physics::nonlocal_constraint (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Constraint part(s) of physics for scalar variables.
Reimplemented in GRINS::ScalarODE.
Definition at line 250 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_constraint().
   {
     return;
   }
void GRINS::Physics::nonlocal_mass_residual (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Mass matrix part(s) for scalar variables.
Reimplemented in GRINS::ScalarODE, and GRINS::AveragedTurbine< Viscosity >.
Definition at line 264 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_mass_residual().
   {
     return;
   }
void GRINS::Physics::nonlocal_time_derivative (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Time dependent part(s) of physics for scalar variables.
Reimplemented in GRINS::AveragedTurbine< Viscosity >, and GRINS::ScalarODE.
Definition at line 229 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_time_derivative().
   {
     return;
   }
template<typename Mixture , typename Evaluator > void GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::read_input_options (const GetPot & input) virtual
Read options from GetPot input file.
Todo:
Make this prefix string an input option
Reimplemented from GRINS::Physics.
Reimplemented in GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >.
Definition at line 69 of file reacting_low_mach_navier_stokes_base.C.
References GRINS::p_var_name_default, GRINS::reacting_low_mach_navier_stokes, GRINS::T_var_name_default, GRINS::u_var_name_default, GRINS::v_var_name_default, and GRINS::w_var_name_default.
Referenced by GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase().
   {
     // Read FE family info
     this->_species_FE_family = libMesh::Utility::string_to_enum<GRINSEnums::FEFamily>( input("Physics/"+reacting_low_mach_navier_stokes+"/species_FE_family", "LAGRANGE") );
     this->_V_FE_family = libMesh::Utility::string_to_enum<GRINSEnums::FEFamily>( input("Physics/"+reacting_low_mach_navier_stokes+"/V_FE_family", "LAGRANGE") );
     this->_P_FE_family = libMesh::Utility::string_to_enum<GRINSEnums::FEFamily>( input("Physics/"+reacting_low_mach_navier_stokes+"/P_FE_family", "LAGRANGE") );
     this->_T_FE_family = libMesh::Utility::string_to_enum<GRINSEnums::FEFamily>( input("Physics/"+reacting_low_mach_navier_stokes+"/T_FE_family", "LAGRANGE") );
     // Read FE family info
     this->_species_order = libMesh::Utility::string_to_enum<GRINSEnums::Order>( input("Physics/"+reacting_low_mach_navier_stokes+"/species_order", "SECOND") );
     this->_V_order = libMesh::Utility::string_to_enum<GRINSEnums::Order>( input("Physics/"+reacting_low_mach_navier_stokes+"/V_order", "SECOND") );
     this->_P_order = libMesh::Utility::string_to_enum<GRINSEnums::Order>( input("Physics/"+reacting_low_mach_navier_stokes+"/P_order", "FIRST") );
     this->_T_order = libMesh::Utility::string_to_enum<GRINSEnums::Order>( input("Physics/"+reacting_low_mach_navier_stokes+"/T_order", "SECOND") );
     // Read variable naming info
     this->_n_species = input.vector_variable_size("Physics/Chemistry/species");
     _species_var_names.reserve(this->_n_species);
     for( unsigned int i = 0; i < this->_n_species; i++ )
       {
         std::string var_name = "w_"+std::string(input( "Physics/Chemistry/species", "DIE!", i ));
         _species_var_names.push_back( var_name );
       }
     this->_u_var_name = input("Physics/VariableNames/u_velocity", GRINS::u_var_name_default );
     this->_v_var_name = input("Physics/VariableNames/v_velocity", GRINS::v_var_name_default );
     this->_w_var_name = input("Physics/VariableNames/w_velocity", GRINS::w_var_name_default );
     this->_p_var_name = input("Physics/VariableNames/pressure", GRINS::p_var_name_default );
     this->_T_var_name = input("Physics/VariableNames/temperature", GRINS::T_var_name_default );
     // Read thermodynamic state info
     this->set_parameter
       (_p0, input, "Physics/"+reacting_low_mach_navier_stokes+"/p0", 0.0 ); /* thermodynamic pressure */
     _enable_thermo_press_calc = input("Physics/"+reacting_low_mach_navier_stokes+"/enable_thermo_press_calc", false );
     if( _enable_thermo_press_calc )
       {
         _p0_var_name = input("Physics/VariableNames/thermo_presure", "p0" );
       }
     // Read gravity vector
     unsigned int g_dim = input.vector_variable_size("Physics/"+reacting_low_mach_navier_stokes+"/g");
     _g(0) = input("Physics/"+reacting_low_mach_navier_stokes+"/g", 0.0, 0 );
     _g(1) = input("Physics/"+reacting_low_mach_navier_stokes+"/g", 0.0, 1 );
     if( g_dim == 3)
       _g(2) = input("Physics/"+reacting_low_mach_navier_stokes+"/g", 0.0, 2 );
     return;
   }
void GRINS::ParameterUser::register_parameter (const std::string & param_name, libMesh::ParameterMultiPointer< libMesh::Number > & param_pointer) const virtual inherited
Each subclass will register its copy of an independent.
Reimplemented in GRINS::AxisymmetricHeatTransfer< Conductivity >, GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::IncompressibleNavierStokesBase< Viscosity >, GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >, GRINS::HeatConduction< Conductivity >, GRINS::HeatTransferBase< Conductivity >, and GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >.
Definition at line 50 of file parameter_user.C.
Referenced by GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::register_parameter(), GRINS::HeatTransferBase< Conductivity >::register_parameter(), GRINS::HeatConduction< Conductivity >::register_parameter(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::register_parameter(), GRINS::IncompressibleNavierStokesBase< Viscosity >::register_parameter(), GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::register_parameter(), and GRINS::AxisymmetricHeatTransfer< Conductivity >::register_parameter().
   {
     std::map<std::string, libMesh::Number*>::const_iterator it =
       _my_parameters.find(param_name);
     if (it != _my_parameters.end())
       {
         std::cout << _my_name << " uses parameter " << param_name
                   << std::endl;
         param_pointer.push_back(it->second);
       }
   }
void GRINS::Physics::register_postprocessing_vars (const GetPot & input, PostProcessedQuantities< libMesh::Real > & postprocessing) virtual inherited
Register name of postprocessed quantity with PostProcessedQuantities.
Each Physics class will need to cache an unsigned int corresponding to each postprocessed quantity. This will be used in computing the values and putting them in the CachedVariables object.
Reimplemented in GRINS::ParsedVelocitySource< Viscosity >, GRINS::VelocityPenalty< Viscosity >, GRINS::IncompressibleNavierStokes< Viscosity >, GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::HeatTransfer< Conductivity >, GRINS::ElasticCable< StressStrainLaw >, GRINS::ElasticMembrane< StressStrainLaw >, and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >.
Definition at line 161 of file physics.C.
   {
     return;
   }
template<typename Mixture , typename Evaluator > libMesh::Real GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::rho (libMesh::Real T, libMesh::Real p0, libMesh::Real R_mix) const inline
Definition at line 153 of file reacting_low_mach_navier_stokes_base.h.
   {
     libMesh::Real value = 0;
     if( this->_fixed_density )
       value = this->_fixed_rho_value;
     else
       value = p0/(R_mix*T);
     return value;
   }
void GRINS::Physics::set_is_steady (bool is_steady) inherited
Sets whether this physics is to be solved with a steady solver or not.
Since the member variable is static, only needs to be called on a single physics.
Definition at line 97 of file physics.C.
References GRINS::Physics::_is_steady, and GRINS::Physics::is_steady().
   {
     _is_steady = is_steady;
     return;
   }
void GRINS::ParameterUser::set_parameter (libMesh::Number & param_variable, const GetPot & input, const std::string & param_name, libMesh::Number param_default) virtual inherited
Each subclass can simultaneously read a parameter value from.
Definition at line 35 of file parameter_user.C.
References GRINS::ParameterUser::_my_name, and GRINS::ParameterUser::_my_parameters.
Referenced by GRINS::AveragedFanAdjointStabilization< Viscosity >::AveragedFanAdjointStabilization(), GRINS::AveragedTurbineAdjointStabilization< Viscosity >::AveragedTurbineAdjointStabilization(), GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::BoussinesqBuoyancyAdjointStabilization(), GRINS::BoussinesqBuoyancyBase::BoussinesqBuoyancyBase(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::BoussinesqBuoyancySPGSMStabilization(), GRINS::ConstantConductivity::ConstantConductivity(), GRINS::ConstantPrandtlConductivity::ConstantPrandtlConductivity(), GRINS::ConstantSourceFunction::ConstantSourceFunction(), GRINS::ConstantSourceTerm::ConstantSourceTerm(), GRINS::ConstantSpecificHeat::ConstantSpecificHeat(), GRINS::ConstantViscosity::ConstantViscosity(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticCableConstantGravity::ElasticCableConstantGravity(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransferBase< Conductivity >::HeatTransferBase(), GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase(), GRINS::AverageNusseltNumber::init(), GRINS::MooneyRivlin::MooneyRivlin(), GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase(), GRINS::HookesLaw1D::read_input_options(), GRINS::HookesLaw::read_input_options(), GRINS::AxisymmetricBoussinesqBuoyancy::read_input_options(), and GRINS::VelocityDragAdjointStabilization< Viscosity >::VelocityDragAdjointStabilization().
   {
     param_variable = input(param_name, param_default);
     libmesh_assert_msg(!_my_parameters.count(param_name),
       "ERROR: " << _my_name << " double-registered parameter " <<
       param_name);
     _my_parameters[param_name] = &param_variable;
   }
template<typename Mixture , typename Evaluator > void GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::set_time_evolving_vars (libMesh::FEMSystem * system) virtual
Sets velocity variables to be time-evolving.
Reimplemented from GRINS::Physics.
Definition at line 162 of file reacting_low_mach_navier_stokes_base.C.
   {
     const unsigned int dim = system->get_mesh().mesh_dimension();
     for( unsigned int i = 0; i < this->_n_species; i++ )
       {
         system->time_evolving( _species_vars[i] );
       }
     system->time_evolving(_u_var);
     system->time_evolving(_v_var);
     if (dim == 3)
       system->time_evolving(_w_var);
     system->time_evolving(_T_var);
     system->time_evolving(_p_var);
     if( _enable_thermo_press_calc )
       system->time_evolving(_p0_var);
     return;
   }
void GRINS::Physics::side_constraint (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Constraint part(s) of physics for boundaries of elements on the domain boundary.
Reimplemented in GRINS::IncompressibleNavierStokes< Viscosity >, GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >.
Definition at line 243 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::side_constraint().
   {
     return;
   }
void GRINS::Physics::side_time_derivative (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
Reimplemented in GRINS::AxisymmetricHeatTransfer< Conductivity >, GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::HeatTransfer< Conductivity >, GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >, GRINS::ElasticCable< StressStrainLaw >, and GRINS::ElasticMembrane< StressStrainLaw >.
Definition at line 222 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::side_time_derivative().
   {
     return;
   }
template<typename Mixture , typename Evaluator > libMesh::Real GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::T (const libMesh::Point & p, const AssemblyContext & c) const inline
Definition at line 131 of file reacting_low_mach_navier_stokes_base.h.
   { return c.point_value(_T_var,p); }
Member Data Documentation
GRINS::BCHandlingBase* GRINS::Physics::_bc_handler protected inherited
Definition at line 256 of file physics.h.
Referenced by GRINS::Physics::attach_dirichlet_bound_func(), GRINS::Physics::attach_neumann_bound_func(), GRINS::AxisymmetricHeatTransfer< Conductivity >::AxisymmetricHeatTransfer(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::Physics::get_bc_handler(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransfer< Conductivity >::HeatTransfer(), GRINS::IncompressibleNavierStokes< Viscosity >::IncompressibleNavierStokes(), GRINS::Physics::init_bcs(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokes(), GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::ReactingLowMachNavierStokes(), GRINS::SpalartAllmaras< Viscosity >::SpalartAllmaras(), GRINS::Stokes< Viscosity >::Stokes(), and GRINS::Physics::~Physics().
template<typename Mixture, typename Evaluator> unsigned int GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_dim protected
Physical dimension of problem.
Definition at line 83 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> bool GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_enable_thermo_press_calc protected
Flag to enable thermodynamic pressure calculation.
Definition at line 111 of file reacting_low_mach_navier_stokes_base.h.
std::set<libMesh::subdomain_id_type> GRINS::Physics::_enabled_subdomains protected inherited
Subdomains on which the current Physics class is enabled.
Definition at line 261 of file physics.h.
Referenced by GRINS::Physics::enabled_on_elem(), and GRINS::Physics::read_input_options().
template<typename Mixture, typename Evaluator> bool GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_fixed_density protected
Definition at line 113 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> libMesh::Real GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_fixed_rho_value protected
Definition at line 115 of file reacting_low_mach_navier_stokes_base.h.
Referenced by GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase().
template<typename Mixture, typename Evaluator> libMesh::Point GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_g protected
Gravity vector.
Definition at line 108 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> Mixture GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_gas_mixture protected
Definition at line 78 of file reacting_low_mach_navier_stokes_base.h.
Referenced by GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::ReactingLowMachNavierStokes().
GRINS::ICHandlingBase* GRINS::Physics::_ic_handler protected inherited
Definition at line 258 of file physics.h.
Referenced by GRINS::AveragedTurbine< Viscosity >::AveragedTurbine(), GRINS::AxisymmetricHeatTransfer< Conductivity >::AxisymmetricHeatTransfer(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::Physics::get_ic_handler(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransfer< Conductivity >::HeatTransfer(), GRINS::IncompressibleNavierStokes< Viscosity >::IncompressibleNavierStokes(), GRINS::Physics::init_ics(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokes(), GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::ReactingLowMachNavierStokes(), GRINS::ScalarODE::ScalarODE(), GRINS::SpalartAllmaras< Viscosity >::SpalartAllmaras(), GRINS::Stokes< Viscosity >::Stokes(), and GRINS::Physics::~Physics().
bool GRINS::Physics::_is_axisymmetric protected inherited
Definition at line 268 of file physics.h.
Referenced by GRINS::HeatTransfer< Conductivity >::HeatTransfer(), GRINS::IncompressibleNavierStokes< Viscosity >::IncompressibleNavierStokes(), GRINS::Physics::Physics(), and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::ReactingLowMachNavierStokes().
bool GRINS::Physics::_is_steady = false static protected inherited
Caches whether or not the solver that's being used is steady or not.
This is need, for example, in flow stabilization as the tau terms change depending on whether the solver is steady or unsteady.
Definition at line 266 of file physics.h.
Referenced by GRINS::Physics::is_steady(), and GRINS::Physics::set_is_steady().
template<typename Mixture, typename Evaluator> unsigned int GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_n_species protected
Number of species.
Definition at line 86 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> libMesh::Number GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_p0 protected
Definition at line 80 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> VariableIndex GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_p0_var protected
Definition at line 95 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> std::string GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_p0_var_name protected
Definition at line 99 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> GRINSEnums::FEFamily GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_P_FE_family protected
Definition at line 102 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> GRINSEnums::Order GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_P_order protected
Definition at line 105 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> VariableIndex GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_p_var protected
Definition at line 93 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> std::string GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_p_var_name protected
Definition at line 99 of file reacting_low_mach_navier_stokes_base.h.
const PhysicsName GRINS::Physics::_physics_name protected inherited
Name of the physics object. Used for reading physics specific inputs.
We use a reference because the physics names are const global objects in GRINS namespace
No, we use a copy, because otherwise as soon as the memory in std::set<std::string> requested_physics gets overwritten we get in trouble.
Definition at line 254 of file physics.h.
Referenced by GRINS::SourceTermBase::parse_var_info(), and GRINS::Physics::read_input_options().
template<typename Mixture, typename Evaluator> GRINSEnums::FEFamily GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_species_FE_family protected
Element type, read from input.
Definition at line 102 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> GRINSEnums::Order GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_species_order protected
Element orders, read from input.
Definition at line 105 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> std::vector<std::string> GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_species_var_names protected
Names of each (owned) variable in the system.
Definition at line 98 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> std::vector<VariableIndex> GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_species_vars protected
Indices for each (owned) variable;.
Definition at line 89 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> GRINSEnums::FEFamily GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_T_FE_family protected
Definition at line 102 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> GRINSEnums::Order GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_T_order protected
Definition at line 105 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> VariableIndex GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_T_var protected
Definition at line 94 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> std::string GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_T_var_name protected
Definition at line 99 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> VariableIndex GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_u_var protected
Definition at line 90 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> std::string GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_u_var_name protected
Definition at line 99 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> GRINSEnums::FEFamily GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_V_FE_family protected
Definition at line 102 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> GRINSEnums::Order GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_V_order protected
Definition at line 105 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> VariableIndex GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_v_var protected
Definition at line 91 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> std::string GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_v_var_name protected
Definition at line 99 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> VariableIndex GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_w_var protected
Definition at line 92 of file reacting_low_mach_navier_stokes_base.h.
template<typename Mixture, typename Evaluator> std::string GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::_w_var_name protected
Definition at line 99 of file reacting_low_mach_navier_stokes_base.h.
The documentation for this class was generated from the following files:
src/physics/include/grins/reacting_low_mach_navier_stokes_base.h
src/physics/src/reacting_low_mach_navier_stokes_base.C