GRINS-0.6.0: GRINS::TurbulenceVariables Class Reference
GRINS::TurbulenceVariables Class Reference
#include <turbulence_variables.h>
Public Member Functions
TurbulenceVariables (const GetPot &input)
~TurbulenceVariables ()
virtual void init (libMesh::FEMSystem *system)
VariableIndex nu_var () const
Protected Attributes
VariableIndex _nu_var
Indices for each variable;.
std::string _nu_var_name
Names of each variable in the system.
Private Member Functions
TurbulenceVariables ()
Detailed Description
Definition at line 40 of file turbulence_variables.h.
Constructor & Destructor Documentation
GRINS::TurbulenceVariables::TurbulenceVariables (const GetPot & input)
Definition at line 37 of file turbulence_variables.C.
     :  _nu_var(invalid_var_index),
        _nu_var_name( input("Physics/VariableNames/turbulent_viscosity", nu_var_name_default ) )
   {
     return;
   }
GRINS::TurbulenceVariables::~TurbulenceVariables ()
Definition at line 44 of file turbulence_variables.C.
   {
     return;
   }
GRINS::TurbulenceVariables::TurbulenceVariables () private
Member Function Documentation
void GRINS::TurbulenceVariables::init (libMesh::FEMSystem * system) virtual
Reimplemented in GRINS::TurbulenceFEVariables.
Definition at line 49 of file turbulence_variables.C.
References _nu_var, and _nu_var_name.
Referenced by GRINS::SpalartAllmarasStabilizationHelper::init(), and GRINS::SpalartAllmarasBCHandling::init_bc_data().
   {
     libmesh_assert( system->has_variable( _nu_var_name ) );
     _nu_var = system->variable_number( _nu_var_name );
     return;
   }
VariableIndex GRINS::TurbulenceVariables::nu_var () const inline
Definition at line 66 of file turbulence_variables.h.
References _nu_var.
Referenced by GRINS::SpalartAllmarasStabilizationHelper::compute_res_spalart_steady(), and GRINS::SpalartAllmarasStabilizationHelper::compute_res_spalart_transient().
   {
     return _nu_var;
   }
Member Data Documentation
VariableIndex GRINS::TurbulenceVariables::_nu_var protected
Indices for each variable;.
Definition at line 54 of file turbulence_variables.h.
Referenced by init(), GRINS::TurbulenceFEVariables::init(), and nu_var().
std::string GRINS::TurbulenceVariables::_nu_var_name protected
Names of each variable in the system.
Definition at line 57 of file turbulence_variables.h.
Referenced by init(), and GRINS::TurbulenceFEVariables::init().
The documentation for this class was generated from the following files:
src/physics/include/grins/turbulence_variables.h
src/physics/src/turbulence_variables.C