GRINS-0.6.0: GRINS::PrimitiveFlowFEVariables Class Reference
GRINS::PrimitiveFlowFEVariables Class Reference
#include <primitive_flow_fe_variables.h>
Public Member Functions
PrimitiveFlowFEVariables (const GetPot &input, const std::string &physics_name)
~PrimitiveFlowFEVariables ()
virtual void init (libMesh::FEMSystem *system)
VariableIndex u_var () const
VariableIndex v_var () const
VariableIndex w_var () const
VariableIndex p_var () const
Protected Attributes
GRINSEnums::FEFamily _V_FE_family
Element type, read from input.
GRINSEnums::FEFamily _P_FE_family
GRINSEnums::Order _V_order
Element orders, read from input.
GRINSEnums::Order _P_order
VariableIndex _u_var
Indices for each (owned) variable;.
VariableIndex _v_var
VariableIndex _w_var
VariableIndex _p_var
std::string _u_var_name
Names of each (owned) variable in the system.
std::string _v_var_name
std::string _w_var_name
std::string _p_var_name
Private Member Functions
PrimitiveFlowFEVariables ()
Detailed Description
Definition at line 40 of file primitive_flow_fe_variables.h.
Constructor & Destructor Documentation
GRINS::PrimitiveFlowFEVariables::PrimitiveFlowFEVariables (const GetPot & input, const std::string & physics_name)
Definition at line 39 of file primitive_flow_fe_variables.C.
     :  PrimitiveFlowVariables(input),
        _V_FE_family( libMesh::Utility::string_to_enum<GRINSEnums::FEFamily>( input("Physics/"+physics_name+"/V_FE_family", input("Physics/"+physics_name+"/FE_family", "LAGRANGE") ) ) ),
        _P_FE_family( libMesh::Utility::string_to_enum<GRINSEnums::FEFamily>( input("Physics/"+physics_name+"/P_FE_family", input("Physics/"+physics_name+"/FE_family", "LAGRANGE") ) ) ),
        _V_order( libMesh::Utility::string_to_enum<GRINSEnums::Order>( input("Physics/"+physics_name+"/V_order", "SECOND") ) ),
        _P_order( libMesh::Utility::string_to_enum<GRINSEnums::Order>( input("Physics/"+physics_name+"/P_order", "FIRST") ) )
   {
     return;
   }
GRINS::PrimitiveFlowFEVariables::~PrimitiveFlowFEVariables ()
Definition at line 49 of file primitive_flow_fe_variables.C.
   {
     return;
   }
GRINS::PrimitiveFlowFEVariables::PrimitiveFlowFEVariables () private
Member Function Documentation
void GRINS::PrimitiveFlowFEVariables::init (libMesh::FEMSystem * system) virtual
Reimplemented from GRINS::PrimitiveFlowVariables.
Definition at line 54 of file primitive_flow_fe_variables.C.
References _P_FE_family, _P_order, GRINS::PrimitiveFlowVariables::_p_var, GRINS::PrimitiveFlowVariables::_p_var_name, GRINS::PrimitiveFlowVariables::_u_var, GRINS::PrimitiveFlowVariables::_u_var_name, _V_FE_family, _V_order, GRINS::PrimitiveFlowVariables::_v_var, GRINS::PrimitiveFlowVariables::_v_var_name, GRINS::PrimitiveFlowVariables::_w_var, and GRINS::PrimitiveFlowVariables::_w_var_name.
Referenced by GRINS::BoussinesqBuoyancyBase::init_variables().
   {
     _u_var = system->add_variable( _u_var_name, this->_V_order, _V_FE_family);
     _v_var = system->add_variable( _v_var_name, this->_V_order, _V_FE_family);
     if ( system->get_mesh().mesh_dimension() == 3)
       _w_var = system->add_variable( _w_var_name, this->_V_order, _V_FE_family);
     _p_var = system->add_variable( _p_var_name, this->_P_order, _P_FE_family);
     return;
   }
VariableIndex GRINS::PrimitiveFlowVariables::p_var () const inline inherited
Definition at line 92 of file primitive_flow_variables.h.
References GRINS::PrimitiveFlowVariables::_p_var.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady().
   {
     return _p_var;
   }
VariableIndex GRINS::PrimitiveFlowVariables::u_var () const inline inherited
Definition at line 74 of file primitive_flow_variables.h.
References GRINS::PrimitiveFlowVariables::_u_var.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_continuity(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_transient(), GRINS::SpalartAllmarasStabilizationHelper::compute_res_spalart_steady(), GRINS::BoussinesqBuoyancy::element_time_derivative(), GRINS::IncompressibleNavierStokesBCHandling::user_init_dirichlet_bcs(), and GRINS::SpalartAllmarasHelper::vorticity().
   {
     return _u_var;
   }
VariableIndex GRINS::PrimitiveFlowVariables::v_var () const inline inherited
Definition at line 80 of file primitive_flow_variables.h.
References GRINS::PrimitiveFlowVariables::_v_var.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_continuity(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_transient(), GRINS::SpalartAllmarasStabilizationHelper::compute_res_spalart_steady(), GRINS::BoussinesqBuoyancy::element_time_derivative(), GRINS::IncompressibleNavierStokesBCHandling::user_init_dirichlet_bcs(), and GRINS::SpalartAllmarasHelper::vorticity().
   {
     return _v_var;
   }
VariableIndex GRINS::PrimitiveFlowVariables::w_var () const inline inherited
Definition at line 86 of file primitive_flow_variables.h.
References GRINS::PrimitiveFlowVariables::_w_var.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_continuity(), GRINS::HeatTransferStabilizationHelper::compute_res_energy_steady(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady(), GRINS::SpalartAllmarasStabilizationHelper::compute_res_spalart_steady(), GRINS::BoussinesqBuoyancy::element_time_derivative(), GRINS::IncompressibleNavierStokesBCHandling::user_init_dirichlet_bcs(), and GRINS::SpalartAllmarasHelper::vorticity().
   {
     return _w_var;
   }
Member Data Documentation
GRINSEnums::FEFamily GRINS::PrimitiveFlowFEVariables::_P_FE_family protected
Definition at line 52 of file primitive_flow_fe_variables.h.
Referenced by init().
GRINSEnums::Order GRINS::PrimitiveFlowFEVariables::_P_order protected
Definition at line 55 of file primitive_flow_fe_variables.h.
Referenced by init().
VariableIndex GRINS::PrimitiveFlowVariables::_p_var protected inherited
Definition at line 62 of file primitive_flow_variables.h.
Referenced by init(), GRINS::PrimitiveFlowVariables::init(), and GRINS::PrimitiveFlowVariables::p_var().
std::string GRINS::PrimitiveFlowVariables::_p_var_name protected inherited
Definition at line 65 of file primitive_flow_variables.h.
Referenced by init(), and GRINS::PrimitiveFlowVariables::init().
VariableIndex GRINS::PrimitiveFlowVariables::_u_var protected inherited
Indices for each (owned) variable;.
Definition at line 59 of file primitive_flow_variables.h.
Referenced by init(), GRINS::PrimitiveFlowVariables::init(), and GRINS::PrimitiveFlowVariables::u_var().
std::string GRINS::PrimitiveFlowVariables::_u_var_name protected inherited
Names of each (owned) variable in the system.
Definition at line 65 of file primitive_flow_variables.h.
Referenced by init(), and GRINS::PrimitiveFlowVariables::init().
GRINSEnums::FEFamily GRINS::PrimitiveFlowFEVariables::_V_FE_family protected
Element type, read from input.
Definition at line 52 of file primitive_flow_fe_variables.h.
Referenced by init().
GRINSEnums::Order GRINS::PrimitiveFlowFEVariables::_V_order protected
Element orders, read from input.
Definition at line 55 of file primitive_flow_fe_variables.h.
Referenced by init().
VariableIndex GRINS::PrimitiveFlowVariables::_v_var protected inherited
Definition at line 60 of file primitive_flow_variables.h.
Referenced by init(), GRINS::PrimitiveFlowVariables::init(), and GRINS::PrimitiveFlowVariables::v_var().
std::string GRINS::PrimitiveFlowVariables::_v_var_name protected inherited
Definition at line 65 of file primitive_flow_variables.h.
Referenced by init(), and GRINS::PrimitiveFlowVariables::init().
VariableIndex GRINS::PrimitiveFlowVariables::_w_var protected inherited
Definition at line 61 of file primitive_flow_variables.h.
Referenced by init(), GRINS::PrimitiveFlowVariables::init(), and GRINS::PrimitiveFlowVariables::w_var().
std::string GRINS::PrimitiveFlowVariables::_w_var_name protected inherited
Definition at line 65 of file primitive_flow_variables.h.
Referenced by init(), and GRINS::PrimitiveFlowVariables::init().
The documentation for this class was generated from the following files:
src/physics/include/grins/primitive_flow_fe_variables.h
src/physics/src/primitive_flow_fe_variables.C