GRINS-0.6.0: GRINS::SolidMechanicsFEVariables Class Reference
GRINS::SolidMechanicsFEVariables Class Reference
#include <solid_mechanics_fe_variables.h>
Public Member Functions
SolidMechanicsFEVariables (const GetPot &input, const std::string &physics_name)
virtual ~SolidMechanicsFEVariables ()
void init (libMesh::FEMSystem *system, bool is_2D, bool is_3D)
Initialize System variables.
void init (libMesh::FEMSystem *system)
Initialize System variables.
bool have_v () const
bool have_w () const
VariableIndex u_var () const
VariableIndex v_var () const
VariableIndex w_var () const
const std::string & u_var_name () const
const std::string & v_var_name () const
const std::string & w_var_name () const
Protected Attributes
GRINSEnums::FEFamily _FE_family
Element type, read from input.
GRINSEnums::Order _order
Element orders, read from input.
bool _have_v
bool _have_w
VariableIndex _u_var
VariableIndex _v_var
VariableIndex _w_var
std::string _u_var_name
std::string _v_var_name
std::string _w_var_name
Private Member Functions
SolidMechanicsFEVariables ()
Detailed Description
Definition at line 39 of file solid_mechanics_fe_variables.h.
Constructor & Destructor Documentation
GRINS::SolidMechanicsFEVariables::SolidMechanicsFEVariables (const GetPot & input, const std::string & physics_name)
Definition at line 40 of file solid_mechanics_fe_variables.C.
     :  SolidMechanicsVariables(input),
        _FE_family( libMesh::Utility::string_to_enum<GRINSEnums::FEFamily>( input("Physics/"+physics_name+"/FE_family", "LAGRANGE") ) ),
        _order( libMesh::Utility::string_to_enum<GRINSEnums::Order>( input("Physics/"+physics_name+"/order", "FIRST") ) )
   {
     return;
   }
GRINS::SolidMechanicsFEVariables::~SolidMechanicsFEVariables () virtual
Definition at line 48 of file solid_mechanics_fe_variables.C.
   {
     return;
   }
GRINS::SolidMechanicsFEVariables::SolidMechanicsFEVariables () private
Member Function Documentation
bool GRINS::SolidMechanicsVariables::have_v () const inline inherited
Definition at line 103 of file solid_mechanics_variables.h.
References GRINS::SolidMechanicsVariables::_have_v.
Referenced by GRINS::SolidMechanicsBCHandling::init_bc_types(), GRINS::SolidMechanicsBCHandling::user_apply_neumann_bcs(), and GRINS::SolidMechanicsBCHandling::user_init_dirichlet_bcs().
   {
     return _have_v;
   }
bool GRINS::SolidMechanicsVariables::have_w () const inline inherited
Definition at line 109 of file solid_mechanics_variables.h.
References GRINS::SolidMechanicsVariables::_have_w.
Referenced by GRINS::SolidMechanicsBCHandling::init_bc_types(), GRINS::SolidMechanicsBCHandling::user_apply_neumann_bcs(), and GRINS::SolidMechanicsBCHandling::user_init_dirichlet_bcs().
   {
     return _have_w;
   }
void GRINS::SolidMechanicsFEVariables::init (libMesh::FEMSystem * system, bool is_2D, bool is_3D)
Initialize System variables.
Additional arguments specify whether the spatial mesh is really 2D or 3D. This is needed for cases such as a 1D beam in 2D (is_2D = true) or 3D (is_3D = true) space or 2D shell manifolds in 3D (is_3D = true).
Definition at line 53 of file solid_mechanics_fe_variables.C.
References _FE_family, GRINS::SolidMechanicsVariables::_have_v, GRINS::SolidMechanicsVariables::_have_w, _order, GRINS::SolidMechanicsVariables::_u_var, GRINS::SolidMechanicsVariables::_u_var_name, GRINS::SolidMechanicsVariables::_v_var, GRINS::SolidMechanicsVariables::_v_var_name, GRINS::SolidMechanicsVariables::_w_var, and GRINS::SolidMechanicsVariables::_w_var_name.
Referenced by GRINS::ElasticMembraneBase::init_variables(), and GRINS::ElasticCableBase::init_variables().
   {
     _u_var = system->add_variable( _u_var_name, this->_order, _FE_family);
     if ( system->get_mesh().mesh_dimension() >= 2 || is_2D || is_3D)
       {
         _have_v = true;
         _v_var = system->add_variable( _v_var_name, this->_order, _FE_family);
       }
     if ( system->get_mesh().mesh_dimension() == 3 || is_3D )
       {
         _have_w = true;
         _w_var = system->add_variable( _w_var_name, this->_order, _FE_family);
       }
     return;
   }
void GRINS::SolidMechanicsVariables::init (libMesh::FEMSystem * system) inherited
Initialize System variables.
Additional arguments specify whether the spatial mesh is really 2D or 3D. This is needed for cases such as a 1D beam in 2D (is_2D = true) or 3D (is_3D = true) space or 2D shell manifolds in 3D (is_3D = true).
Definition at line 55 of file solid_mechanics_variables.C.
References GRINS::SolidMechanicsVariables::_have_v, GRINS::SolidMechanicsVariables::_have_w, GRINS::SolidMechanicsVariables::_u_var, GRINS::SolidMechanicsVariables::_u_var_name, GRINS::SolidMechanicsVariables::_v_var, GRINS::SolidMechanicsVariables::_v_var_name, GRINS::SolidMechanicsVariables::_w_var, and GRINS::SolidMechanicsVariables::_w_var_name.
Referenced by GRINS::SolidMechanicsBCHandling::init_bc_data().
   {
     libmesh_assert( system->has_variable( _u_var_name ) );
     _u_var = system->variable_number( _u_var_name );
     if ( system->has_variable( _v_var_name ) )
       {
         _have_v = true;
         _v_var = system->variable_number( _v_var_name );
       }
     if ( system->has_variable( _w_var_name ) )
       {
         _have_w = true;
         _w_var = system->variable_number( _w_var_name );
       }
     return;
   }
VariableIndex GRINS::SolidMechanicsVariables::u_var () const inline inherited
Definition at line 83 of file solid_mechanics_variables.h.
References GRINS::SolidMechanicsVariables::_u_var.
Referenced by GRINS::ElasticCableConstantGravity::element_time_derivative(), GRINS::ElasticMembraneConstantPressure::element_time_derivative(), GRINS::ElasticMembraneBase::get_fe(), GRINS::ElasticCableBase::get_fe(), GRINS::ElasticMembraneBase::set_time_evolving_vars(), GRINS::ElasticCableBase::set_time_evolving_vars(), GRINS::SolidMechanicsBCHandling::user_apply_neumann_bcs(), and GRINS::SolidMechanicsBCHandling::user_init_dirichlet_bcs().
   {
     return _u_var;
   }
const std::string & GRINS::SolidMechanicsVariables::u_var_name () const inline inherited
Definition at line 115 of file solid_mechanics_variables.h.
References GRINS::SolidMechanicsVariables::_u_var_name.
Referenced by GRINS::SolidMechanicsBCHandling::user_init_dirichlet_bcs().
   {
     return _u_var_name;
   }
VariableIndex GRINS::SolidMechanicsVariables::v_var () const inline inherited
Definition at line 89 of file solid_mechanics_variables.h.
References GRINS::SolidMechanicsVariables::_have_v, and GRINS::SolidMechanicsVariables::_v_var.
Referenced by GRINS::ElasticCableConstantGravity::element_time_derivative(), GRINS::ElasticMembraneConstantPressure::element_time_derivative(), GRINS::ElasticMembraneBase::set_time_evolving_vars(), GRINS::ElasticCableBase::set_time_evolving_vars(), GRINS::SolidMechanicsBCHandling::user_apply_neumann_bcs(), and GRINS::SolidMechanicsBCHandling::user_init_dirichlet_bcs().
   {
     libmesh_assert(_have_v);
     return _v_var;
   }
const std::string & GRINS::SolidMechanicsVariables::v_var_name () const inline inherited
Definition at line 121 of file solid_mechanics_variables.h.
References GRINS::SolidMechanicsVariables::_v_var_name.
Referenced by GRINS::SolidMechanicsBCHandling::user_init_dirichlet_bcs().
   {
     return _v_var_name;
   }
VariableIndex GRINS::SolidMechanicsVariables::w_var () const inline inherited
Definition at line 96 of file solid_mechanics_variables.h.
References GRINS::SolidMechanicsVariables::_have_w, and GRINS::SolidMechanicsVariables::_w_var.
Referenced by GRINS::ElasticCableConstantGravity::element_time_derivative(), GRINS::ElasticMembraneConstantPressure::element_time_derivative(), GRINS::ElasticMembraneBase::set_time_evolving_vars(), GRINS::ElasticCableBase::set_time_evolving_vars(), GRINS::SolidMechanicsBCHandling::user_apply_neumann_bcs(), and GRINS::SolidMechanicsBCHandling::user_init_dirichlet_bcs().
   {
     libmesh_assert(_have_w);
     return _w_var;
   }
const std::string & GRINS::SolidMechanicsVariables::w_var_name () const inline inherited
Definition at line 127 of file solid_mechanics_variables.h.
References GRINS::SolidMechanicsVariables::_w_var_name.
Referenced by GRINS::SolidMechanicsBCHandling::user_init_dirichlet_bcs().
   {
     return _w_var_name;
   }
Member Data Documentation
GRINSEnums::FEFamily GRINS::SolidMechanicsFEVariables::_FE_family protected
Element type, read from input.
Definition at line 57 of file solid_mechanics_fe_variables.h.
Referenced by init().
bool GRINS::SolidMechanicsVariables::_have_v protected inherited
Definition at line 71 of file solid_mechanics_variables.h.
Referenced by GRINS::SolidMechanicsVariables::have_v(), init(), GRINS::SolidMechanicsVariables::init(), and GRINS::SolidMechanicsVariables::v_var().
bool GRINS::SolidMechanicsVariables::_have_w protected inherited
Definition at line 72 of file solid_mechanics_variables.h.
Referenced by GRINS::SolidMechanicsVariables::have_w(), init(), GRINS::SolidMechanicsVariables::init(), and GRINS::SolidMechanicsVariables::w_var().
GRINSEnums::Order GRINS::SolidMechanicsFEVariables::_order protected
Element orders, read from input.
Definition at line 60 of file solid_mechanics_fe_variables.h.
Referenced by init().
VariableIndex GRINS::SolidMechanicsVariables::_u_var protected inherited
Definition at line 74 of file solid_mechanics_variables.h.
Referenced by init(), GRINS::SolidMechanicsVariables::init(), and GRINS::SolidMechanicsVariables::u_var().
std::string GRINS::SolidMechanicsVariables::_u_var_name protected inherited
Definition at line 78 of file solid_mechanics_variables.h.
Referenced by init(), GRINS::SolidMechanicsVariables::init(), and GRINS::SolidMechanicsVariables::u_var_name().
VariableIndex GRINS::SolidMechanicsVariables::_v_var protected inherited
Definition at line 75 of file solid_mechanics_variables.h.
Referenced by init(), GRINS::SolidMechanicsVariables::init(), and GRINS::SolidMechanicsVariables::v_var().
std::string GRINS::SolidMechanicsVariables::_v_var_name protected inherited
Definition at line 78 of file solid_mechanics_variables.h.
Referenced by init(), GRINS::SolidMechanicsVariables::init(), and GRINS::SolidMechanicsVariables::v_var_name().
VariableIndex GRINS::SolidMechanicsVariables::_w_var protected inherited
Definition at line 76 of file solid_mechanics_variables.h.
Referenced by init(), GRINS::SolidMechanicsVariables::init(), and GRINS::SolidMechanicsVariables::w_var().
std::string GRINS::SolidMechanicsVariables::_w_var_name protected inherited
Definition at line 78 of file solid_mechanics_variables.h.
Referenced by init(), GRINS::SolidMechanicsVariables::init(), and GRINS::SolidMechanicsVariables::w_var_name().
The documentation for this class was generated from the following files:
src/physics/include/grins/solid_mechanics_fe_variables.h
src/physics/src/solid_mechanics_fe_variables.C