GRINS-0.6.0: GRINS::SolidMechanicsVariables Class Reference
GRINS::SolidMechanicsVariables Class Reference
#include <solid_mechanics_variables.h>
Public Member Functions
SolidMechanicsVariables (const GetPot &input)
virtual ~SolidMechanicsVariables ()
void init (libMesh::FEMSystem *system)
Initialize System variables.
bool have_v () const
bool have_w () const
VariableIndex u_var () const
VariableIndex v_var () const
VariableIndex w_var () const
const std::string & u_var_name () const
const std::string & v_var_name () const
const std::string & w_var_name () const
Protected Attributes
bool _have_v
bool _have_w
VariableIndex _u_var
VariableIndex _v_var
VariableIndex _w_var
std::string _u_var_name
std::string _v_var_name
std::string _w_var_name
Detailed Description
Definition at line 43 of file solid_mechanics_variables.h.
Constructor & Destructor Documentation
GRINS::SolidMechanicsVariables::SolidMechanicsVariables (const GetPot & input)
Definition at line 37 of file solid_mechanics_variables.C.
     : _have_v(false),
       _have_w(false),
       _u_var(invalid_var_index), // These are unsigned, so initialize to absurdly large value
       _v_var(invalid_var_index),
       _w_var(invalid_var_index),
       _u_var_name( input("Physics/VariableNames/u_displacment", u_disp_name_default ) ),
       _v_var_name( input("Physics/VariableNames/v_displacment", v_disp_name_default ) ),
       _w_var_name( input("Physics/VariableNames/w_displacment", w_disp_name_default ) )
   {
     return;
   }
GRINS::SolidMechanicsVariables::~SolidMechanicsVariables () virtual
Definition at line 50 of file solid_mechanics_variables.C.
   {
     return;
   }
Member Function Documentation
bool GRINS::SolidMechanicsVariables::have_v () const inline
Definition at line 103 of file solid_mechanics_variables.h.
References _have_v.
Referenced by GRINS::SolidMechanicsBCHandling::init_bc_types(), GRINS::SolidMechanicsBCHandling::user_apply_neumann_bcs(), and GRINS::SolidMechanicsBCHandling::user_init_dirichlet_bcs().
   {
     return _have_v;
   }
bool GRINS::SolidMechanicsVariables::have_w () const inline
Definition at line 109 of file solid_mechanics_variables.h.
References _have_w.
Referenced by GRINS::SolidMechanicsBCHandling::init_bc_types(), GRINS::SolidMechanicsBCHandling::user_apply_neumann_bcs(), and GRINS::SolidMechanicsBCHandling::user_init_dirichlet_bcs().
   {
     return _have_w;
   }
void GRINS::SolidMechanicsVariables::init (libMesh::FEMSystem * system)
Initialize System variables.
Additional arguments specify whether the spatial mesh is really 2D or 3D. This is needed for cases such as a 1D beam in 2D (is_2D = true) or 3D (is_3D = true) space or 2D shell manifolds in 3D (is_3D = true).
Definition at line 55 of file solid_mechanics_variables.C.
References _have_v, _have_w, _u_var, _u_var_name, _v_var, _v_var_name, _w_var, and _w_var_name.
Referenced by GRINS::SolidMechanicsBCHandling::init_bc_data().
   {
     libmesh_assert( system->has_variable( _u_var_name ) );
     _u_var = system->variable_number( _u_var_name );
     if ( system->has_variable( _v_var_name ) )
       {
         _have_v = true;
         _v_var = system->variable_number( _v_var_name );
       }
     if ( system->has_variable( _w_var_name ) )
       {
         _have_w = true;
         _w_var = system->variable_number( _w_var_name );
       }
     return;
   }
VariableIndex GRINS::SolidMechanicsVariables::u_var () const inline
Definition at line 83 of file solid_mechanics_variables.h.
References _u_var.
Referenced by GRINS::ElasticCableConstantGravity::element_time_derivative(), GRINS::ElasticMembraneConstantPressure::element_time_derivative(), GRINS::ElasticMembraneBase::get_fe(), GRINS::ElasticCableBase::get_fe(), GRINS::ElasticMembraneBase::set_time_evolving_vars(), GRINS::ElasticCableBase::set_time_evolving_vars(), GRINS::SolidMechanicsBCHandling::user_apply_neumann_bcs(), and GRINS::SolidMechanicsBCHandling::user_init_dirichlet_bcs().
   {
     return _u_var;
   }
const std::string & GRINS::SolidMechanicsVariables::u_var_name () const inline
Definition at line 115 of file solid_mechanics_variables.h.
References _u_var_name.
Referenced by GRINS::SolidMechanicsBCHandling::user_init_dirichlet_bcs().
   {
     return _u_var_name;
   }
VariableIndex GRINS::SolidMechanicsVariables::v_var () const inline
Definition at line 89 of file solid_mechanics_variables.h.
References _have_v, and _v_var.
Referenced by GRINS::ElasticCableConstantGravity::element_time_derivative(), GRINS::ElasticMembraneConstantPressure::element_time_derivative(), GRINS::ElasticMembraneBase::set_time_evolving_vars(), GRINS::ElasticCableBase::set_time_evolving_vars(), GRINS::SolidMechanicsBCHandling::user_apply_neumann_bcs(), and GRINS::SolidMechanicsBCHandling::user_init_dirichlet_bcs().
   {
     libmesh_assert(_have_v);
     return _v_var;
   }
const std::string & GRINS::SolidMechanicsVariables::v_var_name () const inline
Definition at line 121 of file solid_mechanics_variables.h.
References _v_var_name.
Referenced by GRINS::SolidMechanicsBCHandling::user_init_dirichlet_bcs().
   {
     return _v_var_name;
   }
VariableIndex GRINS::SolidMechanicsVariables::w_var () const inline
Definition at line 96 of file solid_mechanics_variables.h.
References _have_w, and _w_var.
Referenced by GRINS::ElasticCableConstantGravity::element_time_derivative(), GRINS::ElasticMembraneConstantPressure::element_time_derivative(), GRINS::ElasticMembraneBase::set_time_evolving_vars(), GRINS::ElasticCableBase::set_time_evolving_vars(), GRINS::SolidMechanicsBCHandling::user_apply_neumann_bcs(), and GRINS::SolidMechanicsBCHandling::user_init_dirichlet_bcs().
   {
     libmesh_assert(_have_w);
     return _w_var;
   }
const std::string & GRINS::SolidMechanicsVariables::w_var_name () const inline
Definition at line 127 of file solid_mechanics_variables.h.
References _w_var_name.
Referenced by GRINS::SolidMechanicsBCHandling::user_init_dirichlet_bcs().
   {
     return _w_var_name;
   }
Member Data Documentation
bool GRINS::SolidMechanicsVariables::_have_v protected
Definition at line 71 of file solid_mechanics_variables.h.
Referenced by have_v(), GRINS::SolidMechanicsFEVariables::init(), init(), and v_var().
bool GRINS::SolidMechanicsVariables::_have_w protected
Definition at line 72 of file solid_mechanics_variables.h.
Referenced by have_w(), GRINS::SolidMechanicsFEVariables::init(), init(), and w_var().
VariableIndex GRINS::SolidMechanicsVariables::_u_var protected
Definition at line 74 of file solid_mechanics_variables.h.
Referenced by GRINS::SolidMechanicsFEVariables::init(), init(), and u_var().
std::string GRINS::SolidMechanicsVariables::_u_var_name protected
Definition at line 78 of file solid_mechanics_variables.h.
Referenced by GRINS::SolidMechanicsFEVariables::init(), init(), and u_var_name().
VariableIndex GRINS::SolidMechanicsVariables::_v_var protected
Definition at line 75 of file solid_mechanics_variables.h.
Referenced by GRINS::SolidMechanicsFEVariables::init(), init(), and v_var().
std::string GRINS::SolidMechanicsVariables::_v_var_name protected
Definition at line 78 of file solid_mechanics_variables.h.
Referenced by GRINS::SolidMechanicsFEVariables::init(), init(), and v_var_name().
VariableIndex GRINS::SolidMechanicsVariables::_w_var protected
Definition at line 76 of file solid_mechanics_variables.h.
Referenced by GRINS::SolidMechanicsFEVariables::init(), init(), and w_var().
std::string GRINS::SolidMechanicsVariables::_w_var_name protected
Definition at line 78 of file solid_mechanics_variables.h.
Referenced by GRINS::SolidMechanicsFEVariables::init(), init(), and w_var_name().
The documentation for this class was generated from the following files:
src/physics/include/grins/solid_mechanics_variables.h
src/physics/src/solid_mechanics_variables.C