GRINS-0.6.0: GRINS::ParameterManager Class Reference
GRINS::ParameterManager Class Reference
Simple class to hold and initialize a ParameterVector.
#include <parameter_manager.h>
Public Member Functions
ParameterManager ()
virtual ~ParameterManager ()
virtual void initialize (const GetPot &input, const std::string &parameters_varname, GRINS::MultiphysicsSystem &system, GRINS::CompositeQoI *qoi)
Public Attributes
std::vector< std::string > parameter_name_list
libMesh::ParameterVector parameter_vector
Detailed Description
Simple class to hold and initialize a ParameterVector.
Allows the user to specify parameters by name in the input file.
Definition at line 49 of file parameter_manager.h.
Constructor & Destructor Documentation
GRINS::ParameterManager::ParameterManager () inline
Definition at line 53 of file parameter_manager.h.
 {}
virtual GRINS::ParameterManager::~ParameterManager () inline virtual
Definition at line 54 of file parameter_manager.h.
 {}
Member Function Documentation
void GRINS::ParameterManager::initialize (const GetPot & input, const std::string & parameters_varname, GRINS::MultiphysicsSystem & system, GRINS::CompositeQoI * qoi) virtual
Definition at line 43 of file parameter_manager.C.
References GRINS::CompositeQoI::register_parameter(), and GRINS::MultiphysicsSystem::register_parameter().
Referenced by GRINS::Simulation::init_params().
   {
     const unsigned int n_parameters =
       input.vector_variable_size(parameters_varname);
     libmesh_assert(n_parameters);
     this->parameter_name_list.resize(n_parameters);
     this->parameter_vector.clear();
     for (unsigned int i=0; i != n_parameters; ++i)
       {
         std::string param_name =
           input(parameters_varname, std::string(), i);
         this->parameter_name_list[i] = param_name;
         libMesh::ParameterMultiPointer<libMesh::Number> *next_param =
           new libMesh::ParameterMultiPointer<libMesh::Number>();
         // We always have Physics solving for u
         system.register_parameter(param_name, *next_param);
         // We don't always have QoIs when solving for du/dp
         if (qoi)
           qoi->register_parameter(param_name, *next_param);
         if (next_param->size() == 0)
           {
             std::cout << "No parameters named " << param_name <<
               " found in active Physics or QoIs" << std::endl;
             libmesh_error();
           }
         this->parameter_vector.push_back
           (libMesh::AutoPtr<libMesh::ParameterAccessor<libMesh::Number> >
            (next_param));
       }
   }
Member Data Documentation
std::vector<std::string> GRINS::ParameterManager::parameter_name_list
Definition at line 64 of file parameter_manager.h.
libMesh::ParameterVector GRINS::ParameterManager::parameter_vector
Definition at line 69 of file parameter_manager.h.
Referenced by GRINS::Simulation::run().
The documentation for this class was generated from the following files:
src/solver/include/grins/parameter_manager.h
src/solver/src/parameter_manager.C