GRINS-0.6.0: GRINS::ConcentricCylinderProfile Class Reference
GRINS::ConcentricCylinderProfile Class Reference
Profile for flow between axially moving concentric cylinders.
#include <concentric_cylinder_profile.h>
Public Member Functions
ConcentricCylinderProfile ()
Default constructor.
ConcentricCylinderProfile (const double u0, const double r0, const double r1)
virtual ~ConcentricCylinderProfile ()
virtual libMesh::AutoPtr< libMesh::FunctionBase< libMesh::Number > > clone () const
virtual libMesh::Number operator() (const libMesh::Point &p, const libMesh::Real time)
virtual void operator() (const libMesh::Point &p, const libMesh::Real time, libMesh::DenseVector< libMesh::Number > &output)
virtual libMesh::Number component (unsigned int i, const libMesh::Point &p, const libMesh::Real time)
Protected Member Functions
double eval (const double u0, const double r0, const double r1, const double r)
Protected Attributes
double _u0
Coefficients defining parabola.
double _r0
double _r1
Detailed Description
Profile for flow between axially moving concentric cylinders.
Profile generated between axially moving concentric cylinders. In this case, we assume the outer cylinder is stationary, and the inner cylinder is moving at speed u0. The profile is given by: where: is the inner cylinder radius and is the outer cylinder radius. Note, that this assumes axisymmetry.
Definition at line 47 of file concentric_cylinder_profile.h.
Constructor & Destructor Documentation
GRINS::ConcentricCylinderProfile::ConcentricCylinderProfile ()
Default constructor.
Default constructor sets parameters for the profile: value =
Definition at line 35 of file concentric_cylinder_profile.C.
Referenced by clone().
     : libMesh::FunctionBase<libMesh::Number>(),
       _u0(2.0),
       _r0(1.0),
       _r1(2.0)
   {
     return;
   }
GRINS::ConcentricCylinderProfile::ConcentricCylinderProfile (const double u0, const double r0, const double r1)
Definition at line 44 of file concentric_cylinder_profile.C.
     : libMesh::FunctionBase<libMesh::Number>(),
       _u0(u0),
       _r0(r0),
       _r1(r1)
   {
     return;
   }
GRINS::ConcentricCylinderProfile::~ConcentricCylinderProfile () virtual
Definition at line 55 of file concentric_cylinder_profile.C.
   {
     return;
   }
Member Function Documentation
libMesh::AutoPtr< libMesh::FunctionBase< libMesh::Number > > GRINS::ConcentricCylinderProfile::clone () const virtual
Definition at line 60 of file concentric_cylinder_profile.C.
References _r0, _r1, _u0, and ConcentricCylinderProfile().
   {
     return libMesh::AutoPtr< libMesh::FunctionBase<libMesh::Number> >( new ConcentricCylinderProfile( _u0, _r0, _r1 ) );
   }
libMesh::Number GRINS::ConcentricCylinderProfile::component (unsigned int i, const libMesh::Point & p, const libMesh::Real time) virtual
Definition at line 84 of file concentric_cylinder_profile.C.
   {
     return (*this)(p, time);
   }
double GRINS::ConcentricCylinderProfile::eval (const double u0, const double r0, const double r1, const double r) inline protected
Definition at line 75 of file concentric_cylinder_profile.h.
Referenced by operator()().
     {
       return u0*std::log(r1/r)/std::log(r1/r0);
     };
libMesh::Number GRINS::ConcentricCylinderProfile::operator() (const libMesh::Point & p, const libMesh::Real time) virtual
Definition at line 65 of file concentric_cylinder_profile.C.
References _r0, _r1, _u0, and eval().
   {
     const double r = p(0);
     return this->eval( _u0, _r0, _r1, r );
   }
void GRINS::ConcentricCylinderProfile::operator() (const libMesh::Point & p, const libMesh::Real time, libMesh::DenseVector< libMesh::Number > & output) virtual
Definition at line 73 of file concentric_cylinder_profile.C.
   {
     for( unsigned int i = 0; i < output.size(); i++ )
       {
         output(i) = (*this)(p, time);
       }
     return;
   }
Member Data Documentation
double GRINS::ConcentricCylinderProfile::_r0 protected
Definition at line 79 of file concentric_cylinder_profile.h.
Referenced by clone(), and operator()().
double GRINS::ConcentricCylinderProfile::_r1 protected
Definition at line 79 of file concentric_cylinder_profile.h.
Referenced by clone(), and operator()().
double GRINS::ConcentricCylinderProfile::_u0 protected
Coefficients defining parabola.
Definition at line 79 of file concentric_cylinder_profile.h.
Referenced by clone(), and operator()().
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/concentric_cylinder_profile.h
src/boundary_conditions/src/concentric_cylinder_profile.C