GRINS-0.6.0: GRINS::PrimitiveFlowVariables Class Reference
GRINS::PrimitiveFlowVariables Class Reference
#include <primitive_flow_variables.h>
Public Member Functions
PrimitiveFlowVariables (const GetPot &input)
~PrimitiveFlowVariables ()
virtual void init (libMesh::FEMSystem *system)
VariableIndex u_var () const
VariableIndex v_var () const
VariableIndex w_var () const
VariableIndex p_var () const
Protected Attributes
VariableIndex _u_var
Indices for each (owned) variable;.
VariableIndex _v_var
VariableIndex _w_var
VariableIndex _p_var
std::string _u_var_name
Names of each (owned) variable in the system.
std::string _v_var_name
std::string _w_var_name
std::string _p_var_name
Private Member Functions
PrimitiveFlowVariables ()
Detailed Description
Definition at line 42 of file primitive_flow_variables.h.
Constructor & Destructor Documentation
GRINS::PrimitiveFlowVariables::PrimitiveFlowVariables (const GetPot & input)
Definition at line 37 of file primitive_flow_variables.C.
     :  _u_var(invalid_var_index),
        _v_var(invalid_var_index),
        _w_var(invalid_var_index),
        _p_var(invalid_var_index),
        _u_var_name( input("Physics/VariableNames/u_velocity", u_var_name_default ) ),
        _v_var_name( input("Physics/VariableNames/v_velocity", v_var_name_default ) ),
        _w_var_name( input("Physics/VariableNames/w_velocity", w_var_name_default ) ),
        _p_var_name( input("Physics/VariableNames/pressure",   p_var_name_default ) )
   {
     return;
   }
GRINS::PrimitiveFlowVariables::~PrimitiveFlowVariables ()
Definition at line 50 of file primitive_flow_variables.C.
   {
     return;
   }
GRINS::PrimitiveFlowVariables::PrimitiveFlowVariables () private
Member Function Documentation
void GRINS::PrimitiveFlowVariables::init (libMesh::FEMSystem * system) virtual
Reimplemented in GRINS::PrimitiveFlowFEVariables.
Definition at line 55 of file primitive_flow_variables.C.
References _p_var, _p_var_name, _u_var, _u_var_name, _v_var, _v_var_name, _w_var, and _w_var_name.
Referenced by GRINS::HeatTransferStabilizationHelper::init(), GRINS::IncompressibleNavierStokesStabilizationHelper::init(), GRINS::SpalartAllmarasStabilizationHelper::init(), GRINS::IncompressibleNavierStokesBCHandling::init_bc_data(), and GRINS::SpalartAllmarasHelper::init_variables().
   {
     libmesh_assert( system->has_variable( _u_var_name ) );
     libmesh_assert( system->has_variable( _v_var_name ) );
     libmesh_assert( system->has_variable( _p_var_name ) );
     _u_var = system->variable_number( _u_var_name );
     _v_var = system->variable_number( _v_var_name );
     if ( system->get_mesh().mesh_dimension() == 3)
       {
         libmesh_assert( system->has_variable( _w_var_name ) );
         _w_var = system->variable_number( _w_var_name );
       }
     _p_var = system->variable_number( _p_var_name );
     return;
   }
VariableIndex GRINS::PrimitiveFlowVariables::p_var () const inline
Definition at line 92 of file primitive_flow_variables.h.
References _p_var.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady().
   {
     return _p_var;
   }
VariableIndex GRINS::PrimitiveFlowVariables::u_var () const inline
Definition at line 74 of file primitive_flow_variables.h.
References _u_var.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_continuity(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_transient(), GRINS::SpalartAllmarasStabilizationHelper::compute_res_spalart_steady(), GRINS::BoussinesqBuoyancy::element_time_derivative(), GRINS::IncompressibleNavierStokesBCHandling::user_init_dirichlet_bcs(), and GRINS::SpalartAllmarasHelper::vorticity().
   {
     return _u_var;
   }
VariableIndex GRINS::PrimitiveFlowVariables::v_var () const inline
Definition at line 80 of file primitive_flow_variables.h.
References _v_var.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_continuity(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_transient(), GRINS::SpalartAllmarasStabilizationHelper::compute_res_spalart_steady(), GRINS::BoussinesqBuoyancy::element_time_derivative(), GRINS::IncompressibleNavierStokesBCHandling::user_init_dirichlet_bcs(), and GRINS::SpalartAllmarasHelper::vorticity().
   {
     return _v_var;
   }
VariableIndex GRINS::PrimitiveFlowVariables::w_var () const inline
Definition at line 86 of file primitive_flow_variables.h.
References _w_var.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_continuity(), GRINS::HeatTransferStabilizationHelper::compute_res_energy_steady(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady(), GRINS::SpalartAllmarasStabilizationHelper::compute_res_spalart_steady(), GRINS::BoussinesqBuoyancy::element_time_derivative(), GRINS::IncompressibleNavierStokesBCHandling::user_init_dirichlet_bcs(), and GRINS::SpalartAllmarasHelper::vorticity().
   {
     return _w_var;
   }
Member Data Documentation
VariableIndex GRINS::PrimitiveFlowVariables::_p_var protected
Definition at line 62 of file primitive_flow_variables.h.
Referenced by GRINS::PrimitiveFlowFEVariables::init(), init(), and p_var().
std::string GRINS::PrimitiveFlowVariables::_p_var_name protected
Definition at line 65 of file primitive_flow_variables.h.
Referenced by GRINS::PrimitiveFlowFEVariables::init(), and init().
VariableIndex GRINS::PrimitiveFlowVariables::_u_var protected
Indices for each (owned) variable;.
Definition at line 59 of file primitive_flow_variables.h.
Referenced by GRINS::PrimitiveFlowFEVariables::init(), init(), and u_var().
std::string GRINS::PrimitiveFlowVariables::_u_var_name protected
Names of each (owned) variable in the system.
Definition at line 65 of file primitive_flow_variables.h.
Referenced by GRINS::PrimitiveFlowFEVariables::init(), and init().
VariableIndex GRINS::PrimitiveFlowVariables::_v_var protected
Definition at line 60 of file primitive_flow_variables.h.
Referenced by GRINS::PrimitiveFlowFEVariables::init(), init(), and v_var().
std::string GRINS::PrimitiveFlowVariables::_v_var_name protected
Definition at line 65 of file primitive_flow_variables.h.
Referenced by GRINS::PrimitiveFlowFEVariables::init(), and init().
VariableIndex GRINS::PrimitiveFlowVariables::_w_var protected
Definition at line 61 of file primitive_flow_variables.h.
Referenced by GRINS::PrimitiveFlowFEVariables::init(), init(), and w_var().
std::string GRINS::PrimitiveFlowVariables::_w_var_name protected
Definition at line 65 of file primitive_flow_variables.h.
Referenced by GRINS::PrimitiveFlowFEVariables::init(), and init().
The documentation for this class was generated from the following files:
src/physics/include/grins/primitive_flow_variables.h
src/physics/src/primitive_flow_variables.C