GRINS-0.6.0: GRINS::NBCContainer Class Reference
GRINS::NBCContainer Class Reference
Simple helper class to setup general Neumann boundary conditions.
#include <nbc_container.h>
Public Member Functions
NBCContainer ()
~NBCContainer ()
void set_bc_id (BoundaryID bc_id)
Add variable for which this boundary condition is to be applied.
void add_var_func_pair (VariableIndex var, std::tr1::shared_ptr< NeumannFuncObj > func)
Add boundary id and corresponding functor object to be applied on that boundary.
BoundaryID get_bc_id () const
std::tr1::shared_ptr< NeumannFuncObj > get_func (VariableIndex var) const
Protected Attributes
BoundaryID _bc_id
std::map< VariableIndex, std::tr1::shared_ptr< NeumannFuncObj > > _funcs
Detailed Description
Simple helper class to setup general Neumann boundary conditions.
This class is to temporarily stash data necessary for setting up GRINS::NeumannFuncObj objects. Actual instantiation of GRINS::NeumannFuncObj object is handled internally by BCHandling objects. This class is structured on a per-bc ID basis. That is, each object works handles functions for one boundary ID at a time, but can handle multiple variable/function pairs. Currently, it is assumed one function per variable.
Definition at line 41 of file nbc_container.h.
Constructor & Destructor Documentation
GRINS::NBCContainer::NBCContainer ()
Definition at line 30 of file nbc_container.C.
   {
     return;
   }
GRINS::NBCContainer::~NBCContainer ()
Definition at line 35 of file nbc_container.C.
   {
     return;
   }
Member Function Documentation
void GRINS::NBCContainer::add_var_func_pair (VariableIndex var, std::tr1::shared_ptr< NeumannFuncObj > func)
Add boundary id and corresponding functor object to be applied on that boundary.
Definition at line 51 of file nbc_container.C.
References _funcs.
Referenced by GRINS::ThermallyDrivenFlowTestBCFactory::build_neumann().
   {
     if( _funcs.find(var) != _funcs.end() )
       {
         std::cerr << "Error: Can only specify one function per variable" << std::endl;
         libmesh_error();
       }
     _funcs.insert( std::make_pair( var, func ) );
     return;
   }
BoundaryID GRINS::NBCContainer::get_bc_id () const
Definition at line 46 of file nbc_container.C.
References _bc_id.
Referenced by GRINS::BCHandlingBase::attach_neumann_bound_func().
   {
     return _bc_id;
   }
std::tr1::shared_ptr< NeumannFuncObj > GRINS::NBCContainer::get_func (VariableIndex var) const
Definition at line 64 of file nbc_container.C.
References _funcs.
   {
     libmesh_assert( _funcs.find(var) != _funcs.end() );
     return _funcs.find(var)->second;
   }
void GRINS::NBCContainer::set_bc_id (BoundaryID bc_id)
Add variable for which this boundary condition is to be applied.
Definition at line 40 of file nbc_container.C.
References _bc_id.
Referenced by GRINS::ThermallyDrivenFlowTestBCFactory::build_neumann().
   {
     _bc_id = bc_id;
     return;
   }
Member Data Documentation
BoundaryID GRINS::NBCContainer::_bc_id protected
Definition at line 60 of file nbc_container.h.
Referenced by get_bc_id(), and set_bc_id().
std::map<VariableIndex,std::tr1::shared_ptr<NeumannFuncObj> > GRINS::NBCContainer::_funcs protected
Definition at line 61 of file nbc_container.h.
Referenced by add_var_func_pair(), and get_func().
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/nbc_container.h
src/boundary_conditions/src/nbc_container.C