GRINS-0.6.0: GRINS::IncompressibleNavierStokesAdjointStabilization< Viscosity > Class Template Reference
GRINS::IncompressibleNavierStokesAdjointStabilization< Viscosity > Class Template Reference
Adds VMS-based stabilization to LowMachNavierStokes physics class.
#include <inc_navier_stokes_adjoint_stab.h>
Public Member Functions
IncompressibleNavierStokesAdjointStabilization (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~IncompressibleNavierStokesAdjointStabilization ()
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for element interiors.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
virtual void init_variables (libMesh::FEMSystem *system)
Initialization of Navier-Stokes variables.
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Sets velocity variables to be time-evolving.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiPointer< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
virtual void read_input_options (const GetPot &input)
Read options from GetPot input file. By default, nothing is read.
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_bcs (libMesh::FEMSystem *system)
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
void attach_neumann_bound_func (GRINS::NBCContainer &neumann_bcs)
void attach_dirichlet_bound_func (const GRINS::DBCContainer &dirichlet_bc)
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
BCHandlingBase * get_bc_handler ()
ICHandlingBase * get_ic_handler ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
Protected Attributes
IncompressibleNavierStokesStabilizationHelper _stab_helper
unsigned int _dim
Physical dimension of problem.
PrimitiveFlowFEVariables _flow_vars
libMesh::Number _rho
Material parameters, read from input.
Viscosity _mu
Viscosity object.
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::BCHandlingBase * _bc_handler
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
bool _is_axisymmetric
Static Protected Attributes
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
Private Member Functions
IncompressibleNavierStokesAdjointStabilization ()
Detailed Description
template<class Viscosity>
class GRINS::IncompressibleNavierStokesAdjointStabilization< Viscosity >
Adds VMS-based stabilization to LowMachNavierStokes physics class.
Definition at line 35 of file inc_navier_stokes_adjoint_stab.h.
Constructor & Destructor Documentation
template<class Mu > GRINS::IncompressibleNavierStokesAdjointStabilization< Mu >::IncompressibleNavierStokesAdjointStabilization (const GRINS::PhysicsName & physics_name, const GetPot & input)
Definition at line 40 of file inc_navier_stokes_adjoint_stab.C.
References GRINS::Physics::read_input_options().
     : IncompressibleNavierStokesStabilizationBase<Mu>(physics_name,input)
   {
     this->read_input_options(input);
     return;
   }
template<class Mu > GRINS::IncompressibleNavierStokesAdjointStabilization< Mu >::~IncompressibleNavierStokesAdjointStabilization () virtual
Definition at line 50 of file inc_navier_stokes_adjoint_stab.C.
   {
     return;
   }
template<class Viscosity > GRINS::IncompressibleNavierStokesAdjointStabilization< Viscosity >::IncompressibleNavierStokesAdjointStabilization () private
Member Function Documentation
void GRINS::Physics::attach_dirichlet_bound_func (const GRINS::DBCContainer & dirichlet_bc) inherited
Definition at line 150 of file physics.C.
References GRINS::Physics::_bc_handler, and GRINS::BCHandlingBase::attach_dirichlet_bound_func().
   {
     _bc_handler->attach_dirichlet_bound_func( dirichlet_bc );
     return;
   }
void GRINS::Physics::attach_neumann_bound_func (GRINS::NBCContainer & neumann_bcs) inherited
Definition at line 144 of file physics.C.
References GRINS::Physics::_bc_handler, and GRINS::BCHandlingBase::attach_neumann_bound_func().
   {
     _bc_handler->attach_neumann_bound_func( neumann_bcs );
     return;
   }
void GRINS::Physics::auxiliary_init (MultiphysicsSystem & system) virtual inherited
Any auxillary initialization a Physics class may need.
This is called after all variables are added, so this method can safely query the MultiphysicsSystem about variable information.
Definition at line 113 of file physics.C.
   {
     return;
   }
void GRINS::Physics::compute_element_constraint_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 185 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::element_constraint().
   {
     return;
   }
void GRINS::Physics::compute_element_time_derivative_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Reimplemented in GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >.
Definition at line 167 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::element_time_derivative().
   {
     return;
   }
void GRINS::Physics::compute_mass_residual_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 203 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::mass_residual().
   {
     return;
   }
void GRINS::Physics::compute_nonlocal_constraint_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 197 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_constraint().
   {
     return;
   }
void GRINS::Physics::compute_nonlocal_mass_residual_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 209 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_mass_residual().
   {
     return;
   }
void GRINS::Physics::compute_nonlocal_time_derivative_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 179 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_time_derivative().
   {
     return;
   }
void GRINS::Physics::compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext & context, const libMesh::Point & point, libMesh::Real & value) virtual inherited
Reimplemented in GRINS::IncompressibleNavierStokes< Viscosity >, GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >, GRINS::HeatTransfer< Conductivity >, GRINS::ParsedVelocitySource< Viscosity >, GRINS::VelocityPenalty< Viscosity >, GRINS::ElasticMembrane< StressStrainLaw >, and GRINS::ElasticCable< StressStrainLaw >.
Definition at line 271 of file physics.C.
   {
     return;
   }
void GRINS::Physics::compute_side_constraint_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 191 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::side_constraint().
   {
     return;
   }
void GRINS::Physics::compute_side_time_derivative_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Reimplemented in GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >.
Definition at line 173 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::side_time_derivative().
   {
     return;
   }
template<class Mu > void GRINS::IncompressibleNavierStokesAdjointStabilization< Mu >::element_constraint (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Constraint part(s) of physics for element interiors.
Reimplemented from GRINS::Physics.
Definition at line 386 of file inc_navier_stokes_adjoint_stab.C.
   {
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->BeginTimer("IncompressibleNavierStokesAdjointStabilization::element_constraint");
 #endif
     // The number of local degrees of freedom in each variable.
     const unsigned int n_p_dofs = context.get_dof_indices(this->_flow_vars.p_var()).size();
     const unsigned int n_u_dofs = context.get_dof_indices(this->_flow_vars.u_var()).size();
     // Element Jacobian * quadrature weights for interior integration.
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(this->_flow_vars.u_var())->get_JxW();
     // The pressure shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::RealGradient> >& p_dphi =
       context.get_element_fe(this->_flow_vars.p_var())->get_dphi();
     // The velocity shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& u_phi =
       context.get_element_fe(this->_flow_vars.u_var())->get_phi();
     const std::vector<std::vector<libMesh::RealGradient> >& u_dphi =
       context.get_element_fe(this->_flow_vars.u_var())->get_dphi();
     const std::vector<std::vector<libMesh::RealTensor> >& u_d2phi =
       context.get_element_fe(this->_flow_vars.u_var())->get_d2phi();
     libMesh::DenseSubVector<libMesh::Number> &Fp = context.get_elem_residual(this->_flow_vars.p_var()); // R_{p}
     libMesh::DenseSubMatrix<libMesh::Number> &Kpp =
       context.get_elem_jacobian(this->_flow_vars.p_var(), this->_flow_vars.p_var()); // J_{pp}
     libMesh::DenseSubMatrix<libMesh::Number> &Kpu =
       context.get_elem_jacobian(this->_flow_vars.p_var(), this->_flow_vars.u_var()); // J_{pu}
     libMesh::DenseSubMatrix<libMesh::Number> &Kpv =
       context.get_elem_jacobian(this->_flow_vars.p_var(), this->_flow_vars.v_var()); // J_{pv}
     libMesh::DenseSubMatrix<libMesh::Number> *Kpw = NULL;
     if(this->_dim == 3)
       {
         Kpw = &context.get_elem_jacobian
           (this->_flow_vars.p_var(), this->_flow_vars.w_var()); // J_{pw}
       }
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     libMesh::FEBase* fe = context.get_element_fe(this->_flow_vars.u_var());
     for (unsigned int qp=0; qp != n_qpoints; qp++)
       {
         libMesh::RealGradient g = this->_stab_helper.compute_g( fe, context, qp );
         libMesh::RealTensor G = this->_stab_helper.compute_G( fe, context, qp );
         libMesh::RealGradient U( context.interior_value( this->_flow_vars.u_var(), qp ),
                                  context.interior_value( this->_flow_vars.v_var(), qp ) );
         if( this->_dim == 3 )
           {
             U(2) = context.interior_value( this->_flow_vars.w_var(), qp );
           }
         libMesh::Real tau_M;
         libMesh::Real d_tau_M_d_rho;
         libMesh::Gradient d_tau_M_dU;
         libMesh::Gradient RM_s, d_RM_s_uvw_dgraduvw;
         libMesh::Tensor d_RM_s_dgradp, d_RM_s_dU, d_RM_s_uvw_dhessuvw;
         // Compute the viscosity at this qp
         libMesh::Real _mu_qp = this->_mu(context, qp);
         if (compute_jacobian)
           {
             this->_stab_helper.compute_tau_momentum_and_derivs
               ( context, qp, g, G, this->_rho, U, _mu_qp,
                 tau_M, d_tau_M_d_rho, d_tau_M_dU,
                 this->_is_steady );
             this->_stab_helper.compute_res_momentum_steady_and_derivs
               ( context, qp, this->_rho, _mu_qp,
                 RM_s, d_RM_s_dgradp, d_RM_s_dU, d_RM_s_uvw_dgraduvw,
                 d_RM_s_uvw_dhessuvw);
           }
         else
           {
             tau_M = this->_stab_helper.compute_tau_momentum( context, qp, g, G, this->_rho, U, _mu_qp, this->_is_steady );
             RM_s = this->_stab_helper.compute_res_momentum_steady( context, qp, this->_rho, _mu_qp );
           }
         // Now a loop over the pressure degrees of freedom.  This
         // computes the contributions of the continuity equation.
         for (unsigned int i=0; i != n_p_dofs; i++)
           {
             Fp(i) += tau_M*(RM_s*p_dphi[i][qp])*JxW[qp];
             if (compute_jacobian)
               {
                 const libMesh::Real fixed_deriv =
                   context.get_fixed_solution_derivative();
                 const libMesh::TypeVector<libMesh::Number>
                   p_dphiiT_d_RM_s_dgradp =
                   d_RM_s_dgradp.transpose() * p_dphi[i][qp];
                 for (unsigned int j=0; j != n_p_dofs; j++)
                   {
                     Kpp(i,j) += tau_M*(p_dphiiT_d_RM_s_dgradp*p_dphi[j][qp])*JxW[qp];
                   }
                 for (unsigned int j=0; j != n_u_dofs; j++)
                   {
                     Kpu(i,j) += (
                                   d_tau_M_dU(0)*u_phi[j][qp]*(RM_s*p_dphi[i][qp])
                                   + tau_M*
                                   (
                                     d_RM_s_dU(0,0)*u_phi[j][qp]*p_dphi[i][qp](0) +
                                     d_RM_s_dU(1,0)*u_phi[j][qp]*p_dphi[i][qp](1) +
                                     d_RM_s_dU(2,0)*u_phi[j][qp]*p_dphi[i][qp](2) +
                                     d_RM_s_uvw_dgraduvw*u_dphi[j][qp]*p_dphi[i][qp](0) +
                                     d_RM_s_uvw_dhessuvw.contract(u_d2phi[j][qp])*p_dphi[i][qp](0)
                                   )*fixed_deriv
                                 )*JxW[qp];
                     Kpv(i,j) += (
                                   d_tau_M_dU(1)*u_phi[j][qp]*(RM_s*p_dphi[i][qp])
                                   + tau_M*
                                   (
                                     d_RM_s_dU(0,1)*u_phi[j][qp]*p_dphi[i][qp](0) +
                                     d_RM_s_dU(1,1)*u_phi[j][qp]*p_dphi[i][qp](1) +
                                     d_RM_s_dU(2,1)*u_phi[j][qp]*p_dphi[i][qp](2) +
                                     d_RM_s_uvw_dgraduvw*u_dphi[j][qp]*p_dphi[i][qp](1) +
                                     d_RM_s_uvw_dhessuvw.contract(u_d2phi[j][qp])*p_dphi[i][qp](0)
                                   )*fixed_deriv
                                 )*JxW[qp];
                   }
                 if(this->_dim == 3)
                   {
                     for (unsigned int j=0; j != n_u_dofs; j++)
                       {
                         (*Kpw)(i,j) += (
                                          d_tau_M_dU(2)*u_phi[j][qp]*(RM_s*p_dphi[i][qp])
                                          + tau_M*
                                          (
                                            d_RM_s_dU(0,2)*u_phi[j][qp]*p_dphi[i][qp](0) +
                                            d_RM_s_dU(1,2)*u_phi[j][qp]*p_dphi[i][qp](1) +
                                            d_RM_s_dU(2,2)*u_phi[j][qp]*p_dphi[i][qp](2) +
                                            d_RM_s_uvw_dgraduvw*u_dphi[j][qp]*p_dphi[i][qp](2) +
                                            d_RM_s_uvw_dhessuvw.contract(u_d2phi[j][qp])*p_dphi[i][qp](0)
                                          )*fixed_deriv
                                        )*JxW[qp];
                       }
                   }
               }
           }
       }
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->EndTimer("IncompressibleNavierStokesAdjointStabilization::element_constraint");
 #endif
     return;
   }
template<class Mu > void GRINS::IncompressibleNavierStokesAdjointStabilization< Mu >::element_time_derivative (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Time dependent part(s) of physics for element interiors.
Reimplemented from GRINS::Physics.
Definition at line 56 of file inc_navier_stokes_adjoint_stab.C.
   {
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->BeginTimer("IncompressibleNavierStokesAdjointStabilization::element_time_derivative");
 #endif
     // The number of local degrees of freedom in each variable.
     const unsigned int n_p_dofs = context.get_dof_indices(this->_flow_vars.p_var()).size();
     const unsigned int n_u_dofs = context.get_dof_indices(this->_flow_vars.u_var()).size();
     // Element Jacobian * quadrature weights for interior integration.
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(this->_flow_vars.u_var())->get_JxW();
     const std::vector<std::vector<libMesh::RealGradient> >& p_gradphi =
       context.get_element_fe(this->_flow_vars.p_var())->get_dphi();
     const std::vector<std::vector<libMesh::Real> >& u_phi =
       context.get_element_fe(this->_flow_vars.u_var())->get_phi();
     const std::vector<std::vector<libMesh::RealGradient> >& u_gradphi =
       context.get_element_fe(this->_flow_vars.u_var())->get_dphi();
     const std::vector<std::vector<libMesh::RealTensor> >& u_hessphi =
       context.get_element_fe(this->_flow_vars.u_var())->get_d2phi();
     libMesh::DenseSubVector<libMesh::Number> &Fu = context.get_elem_residual(this->_flow_vars.u_var()); // R_{p}
     libMesh::DenseSubVector<libMesh::Number> &Fv = context.get_elem_residual(this->_flow_vars.v_var()); // R_{p}
     libMesh::DenseSubMatrix<libMesh::Number> &Kup =
       context.get_elem_jacobian(this->_flow_vars.u_var(), this->_flow_vars.p_var()); // J_{up}
     libMesh::DenseSubMatrix<libMesh::Number> &Kuu =
       context.get_elem_jacobian(this->_flow_vars.u_var(), this->_flow_vars.u_var()); // J_{uu}
     libMesh::DenseSubMatrix<libMesh::Number> &Kuv =
       context.get_elem_jacobian(this->_flow_vars.u_var(), this->_flow_vars.v_var()); // J_{uv}
     libMesh::DenseSubMatrix<libMesh::Number> &Kvp =
       context.get_elem_jacobian(this->_flow_vars.v_var(), this->_flow_vars.p_var()); // J_{vp}
     libMesh::DenseSubMatrix<libMesh::Number> &Kvu =
       context.get_elem_jacobian(this->_flow_vars.v_var(), this->_flow_vars.u_var()); // J_{vu}
     libMesh::DenseSubMatrix<libMesh::Number> &Kvv =
       context.get_elem_jacobian(this->_flow_vars.v_var(), this->_flow_vars.v_var()); // J_{vv}
     libMesh::DenseSubVector<libMesh::Number> *Fw = NULL;
     libMesh::DenseSubMatrix<libMesh::Number> *Kuw = NULL;
     libMesh::DenseSubMatrix<libMesh::Number> *Kvw = NULL;
     libMesh::DenseSubMatrix<libMesh::Number> *Kwp = NULL;
     libMesh::DenseSubMatrix<libMesh::Number> *Kwu = NULL;
     libMesh::DenseSubMatrix<libMesh::Number> *Kwv = NULL;
     libMesh::DenseSubMatrix<libMesh::Number> *Kww = NULL;
     if(this->_dim == 3)
       {
         Fw = &context.get_elem_residual(this->_flow_vars.w_var()); // R_{w}
         Kuw = &context.get_elem_jacobian
           (this->_flow_vars.u_var(), this->_flow_vars.w_var()); // J_{uw}
         Kvw = &context.get_elem_jacobian
           (this->_flow_vars.v_var(), this->_flow_vars.w_var()); // J_{vw}
         Kwp = &context.get_elem_jacobian
           (this->_flow_vars.w_var(), this->_flow_vars.p_var()); // J_{wp}
         Kwu = &context.get_elem_jacobian
           (this->_flow_vars.w_var(), this->_flow_vars.u_var()); // J_{wu}
         Kwv = &context.get_elem_jacobian
           (this->_flow_vars.w_var(), this->_flow_vars.v_var()); // J_{wv}
         Kww = &context.get_elem_jacobian
           (this->_flow_vars.w_var(), this->_flow_vars.w_var()); // J_{ww}
       }
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     libMesh::FEBase* fe = context.get_element_fe(this->_flow_vars.u_var());
     for (unsigned int qp=0; qp != n_qpoints; qp++)
       {
         libMesh::RealGradient g = this->_stab_helper.compute_g( fe, context, qp );
         libMesh::RealTensor G = this->_stab_helper.compute_G( fe, context, qp );
         libMesh::RealGradient U( context.interior_value( this->_flow_vars.u_var(), qp ),
                                  context.interior_value( this->_flow_vars.v_var(), qp ) );
         if( this->_dim == 3 )
           {
             U(2) = context.interior_value( this->_flow_vars.w_var(), qp );
           }
         /*
           libMesh::Gradient grad_u, grad_v, grad_w;
           grad_u = context.interior_gradient(this->_flow_vars.u_var(), qp);
           grad_v = context.interior_gradient(this->_flow_vars.v_var(), qp);
           if (_dim == 3)
           grad_w = context.interior_gradient(this->_flow_vars.w_var(), qp);
         */
         libMesh::Real tau_M, tau_C;
         libMesh::Real d_tau_M_d_rho, d_tau_C_d_rho;
         libMesh::Gradient d_tau_M_dU, d_tau_C_dU;
         libMesh::Gradient RM_s, d_RM_s_uvw_dgraduvw;
         libMesh::Real RC;
         libMesh::Tensor d_RC_dgradU,
           d_RM_s_dgradp, d_RM_s_dU, d_RM_s_uvw_dhessuvw;
         // Compute the viscosity at this qp
         libMesh::Real _mu_qp = this->_mu(context, qp);
         if (compute_jacobian)
           {
             this->_stab_helper.compute_tau_momentum_and_derivs
               ( context, qp, g, G, this->_rho, U, _mu_qp,
                 tau_M, d_tau_M_d_rho, d_tau_M_dU,
                 this->_is_steady );
             this->_stab_helper.compute_tau_continuity_and_derivs
               ( tau_M, d_tau_M_d_rho, d_tau_M_dU,
                 g,
                 tau_C, d_tau_C_d_rho, d_tau_C_dU );
             this->_stab_helper.compute_res_momentum_steady_and_derivs
               ( context, qp, this->_rho, _mu_qp,
                 RM_s, d_RM_s_dgradp, d_RM_s_dU, d_RM_s_uvw_dgraduvw,
                 d_RM_s_uvw_dhessuvw);
             this->_stab_helper.compute_res_continuity_and_derivs
               ( context, qp, RC, d_RC_dgradU );
           }
         else
           {
             tau_M = this->_stab_helper.compute_tau_momentum( context, qp, g, G, this->_rho, U, _mu_qp, this->_is_steady );
             tau_C = this->_stab_helper.compute_tau_continuity( tau_M, g );
             RM_s = this->_stab_helper.compute_res_momentum_steady( context, qp, this->_rho, _mu_qp );
             RC = this->_stab_helper.compute_res_continuity( context, qp );
           }
         for (unsigned int i=0; i != n_u_dofs; i++)
           {
             libMesh::Real test_func = this->_rho*U*u_gradphi[i][qp] +
               _mu_qp*( u_hessphi[i][qp](0,0) + u_hessphi[i][qp](1,1) + u_hessphi[i][qp](2,2) );
             libMesh::Gradient d_test_func_dU = this->_rho*u_gradphi[i][qp];
             //libMesh::RealGradient zeroth_order_term = - this->_rho*u_phi[i][qp]*(grad_u + grad_v + grad_w);
             Fu(i) += ( -tau_M*RM_s(0)*test_func - tau_C*RC*u_gradphi[i][qp](0) )*JxW[qp];
             Fv(i) += ( -tau_M*RM_s(1)*test_func - tau_C*RC*u_gradphi[i][qp](1) )*JxW[qp];
             if(this->_dim == 3)
               {
                 (*Fw)(i) += ( -tau_M*RM_s(2)*test_func - tau_C*RC*u_gradphi[i][qp](2) )*JxW[qp];
               }
             if (compute_jacobian)
               {
                 const libMesh::Real fixed_deriv =
                   context.get_fixed_solution_derivative();
                 for (unsigned int j=0; j != n_p_dofs; j++)
                   {
                     Kup(i,j) += ( -tau_M*
                                   ( d_RM_s_dgradp(0,0) *
                                     p_gradphi[j][qp](0) +
                                     d_RM_s_dgradp(0,1) *
                                     p_gradphi[j][qp](1) +
                                     d_RM_s_dgradp(0,2) *
                                     p_gradphi[j][qp](2)
                                   )*test_func)*fixed_deriv*JxW[qp];
                     Kvp(i,j) += ( -tau_M*
                                   ( d_RM_s_dgradp(1,0) *
                                     p_gradphi[j][qp](0) +
                                     d_RM_s_dgradp(1,1) *
                                     p_gradphi[j][qp](1) +
                                     d_RM_s_dgradp(1,2) *
                                     p_gradphi[j][qp](2)
                                   )*test_func)*fixed_deriv*JxW[qp];
                   }
                 for (unsigned int j=0; j != n_u_dofs; j++)
                   {
                     Kuu(i,j) += ( -d_tau_M_dU(0)*RM_s(0)*test_func
                                   -tau_M*d_RM_s_dU(0,0)*test_func
                                   - d_tau_C_dU(0)*RC*u_gradphi[i][qp](0)
                                 )*fixed_deriv*u_phi[j][qp]*JxW[qp];
                     Kuu(i,j) += ( -tau_M*RM_s(0)*d_test_func_dU(0)
                                 )*u_phi[j][qp]*JxW[qp];
                     Kuu(i,j) += ( - tau_C*
                                   (
                                     d_RC_dgradU(0,0)*u_gradphi[j][qp](0) +
                                     d_RC_dgradU(0,1)*u_gradphi[j][qp](1) +
                                     d_RC_dgradU(0,2)*u_gradphi[j][qp](2)
                                   )
                                     *fixed_deriv*u_gradphi[i][qp](0)
                                 )*JxW[qp];
                     Kuu(i,j) += ( -tau_M*test_func*(d_RM_s_uvw_dgraduvw*u_gradphi[j][qp])
                                 )*fixed_deriv*JxW[qp];
                     Kuu(i,j) += ( -tau_M*test_func*(d_RM_s_uvw_dhessuvw.contract(u_hessphi[j][qp]))
                                 )*fixed_deriv*JxW[qp];
                     Kuv(i,j) += ( -d_tau_M_dU(1)*RM_s(0)*test_func
                                   -tau_M*d_RM_s_dU(0,1)*test_func
                                 )*fixed_deriv*u_phi[j][qp]*JxW[qp];
                     Kuv(i,j) += ( -tau_M*RM_s(0)*d_test_func_dU(1)
                                 )*u_phi[j][qp]*JxW[qp];
                     Kuv(i,j) += ( - tau_C*
                                   (
                                     d_RC_dgradU(1,0)*u_gradphi[j][qp](0) +
                                     d_RC_dgradU(1,1)*u_gradphi[j][qp](1) +
                                     d_RC_dgradU(1,2)*u_gradphi[j][qp](2)
                                   )
                                     *fixed_deriv*u_gradphi[i][qp](0)
                                 )*JxW[qp];
                     Kvu(i,j) += ( -d_tau_M_dU(0)*RM_s(1)*test_func
                                   -tau_M*d_RM_s_dU(1,0)*test_func
                                 )*fixed_deriv*u_phi[j][qp]*JxW[qp];
                     Kvu(i,j) += ( -tau_M*RM_s(1)*d_test_func_dU(0)
                                 )*u_phi[j][qp]*JxW[qp];
                     Kvu(i,j) += ( - tau_C*
                                   (
                                     d_RC_dgradU(0,0)*u_gradphi[j][qp](0) +
                                     d_RC_dgradU(0,1)*u_gradphi[j][qp](1) +
                                     d_RC_dgradU(0,2)*u_gradphi[j][qp](2)
                                   )
                                     *fixed_deriv*u_gradphi[i][qp](1)
                                 )*JxW[qp];
                     Kvv(i,j) += ( -d_tau_M_dU(1)*RM_s(1)*test_func
                                   -tau_M*d_RM_s_dU(1,1)*test_func
                                 )*fixed_deriv*u_phi[j][qp]*JxW[qp];
                     Kvv(i,j) += ( -tau_M*RM_s(1)*d_test_func_dU(1)
                                 )*u_phi[j][qp]*JxW[qp];
                     Kvv(i,j) += ( - tau_C*
                                   (
                                     d_RC_dgradU(1,0)*u_gradphi[j][qp](0) +
                                     d_RC_dgradU(1,1)*u_gradphi[j][qp](1) +
                                     d_RC_dgradU(1,2)*u_gradphi[j][qp](2)
                                   )
                                     *fixed_deriv*u_gradphi[i][qp](1)
                                 )*JxW[qp];
                     Kvv(i,j) += ( -tau_M*test_func*(d_RM_s_uvw_dgraduvw*u_gradphi[j][qp])
                                 )*fixed_deriv*JxW[qp];
                     Kvv(i,j) += ( -tau_M*test_func*(d_RM_s_uvw_dhessuvw.contract(u_hessphi[j][qp]))
                                 )*fixed_deriv*JxW[qp];
                   }
                 if(this->_dim == 3)
                   {
                     for (unsigned int j=0; j != n_p_dofs; j++)
                       {
                         (*Kwp)(i,j) += ( -tau_M*
                                          ( d_RM_s_dgradp(2,0) *
                                            p_gradphi[j][qp](0) +
                                            d_RM_s_dgradp(2,1) *
                                            p_gradphi[j][qp](1) +
                                            d_RM_s_dgradp(2,2) *
                                            p_gradphi[j][qp](2)
                                          )*test_func)*fixed_deriv*JxW[qp];
                       }
                     for (unsigned int j=0; j != n_u_dofs; j++)
                       {
                         (*Kuw)(i,j) += ( -d_tau_M_dU(2)*RM_s(0)*test_func
                                          -tau_M*d_RM_s_dU(0,2)*test_func
                                        )*fixed_deriv*u_phi[j][qp]*JxW[qp];
                         (*Kuw)(i,j) += ( -tau_M*RM_s(0)*d_test_func_dU(2)
                                        )*u_phi[j][qp]*JxW[qp];
                         (*Kuw)(i,j) += ( - tau_C*
                                          (
                                            d_RC_dgradU(2,0)*u_gradphi[j][qp](0) +
                                            d_RC_dgradU(2,1)*u_gradphi[j][qp](1) +
                                            d_RC_dgradU(2,2)*u_gradphi[j][qp](2)
                                          )
                                          *fixed_deriv* u_gradphi[i][qp](0)
                                        )*JxW[qp];
                         (*Kvw)(i,j) += ( -d_tau_M_dU(2)*RM_s(1)*test_func
                                          -tau_M*d_RM_s_dU(1,2)*test_func
                                        )*fixed_deriv*u_phi[j][qp]*JxW[qp];
                         (*Kvw)(i,j) += ( -tau_M*RM_s(1)*d_test_func_dU(2)
                                        )*u_phi[j][qp]*JxW[qp];
                         (*Kvw)(i,j) += ( - tau_C*
                                          (
                                            d_RC_dgradU(2,0)*u_gradphi[j][qp](0) +
                                            d_RC_dgradU(2,1)*u_gradphi[j][qp](1) +
                                            d_RC_dgradU(2,2)*u_gradphi[j][qp](2)
                                          )
                                          *fixed_deriv* u_gradphi[i][qp](1)
                                        )*JxW[qp];
                         (*Kwu)(i,j) += ( -d_tau_M_dU(0)*RM_s(2)*test_func
                                          -tau_M*d_RM_s_dU(2,0)*test_func
                                        )*fixed_deriv*u_phi[j][qp]*JxW[qp];
                         (*Kwu)(i,j) += ( -tau_M*RM_s(2)*d_test_func_dU(0)
                                        )*u_phi[j][qp]*JxW[qp];
                         (*Kwu)(i,j) += ( - tau_C*
                                          (
                                            d_RC_dgradU(0,0)*u_gradphi[j][qp](0) +
                                            d_RC_dgradU(0,1)*u_gradphi[j][qp](1) +
                                            d_RC_dgradU(0,2)*u_gradphi[j][qp](2)
                                          )
                                          *fixed_deriv* u_gradphi[i][qp](2)
                                        )*JxW[qp];
                         (*Kwv)(i,j) += ( -d_tau_M_dU(1)*RM_s(2)*test_func
                                          -tau_M*d_RM_s_dU(2,1)*test_func
                                        )*fixed_deriv*u_phi[j][qp]*JxW[qp];
                         (*Kwv)(i,j) += ( -tau_M*RM_s(2)*d_test_func_dU(1)
                                        )*u_phi[j][qp]*JxW[qp];
                         (*Kwv)(i,j) += ( - tau_C*
                                          (
                                            d_RC_dgradU(1,0)*u_gradphi[j][qp](0) +
                                            d_RC_dgradU(1,1)*u_gradphi[j][qp](1) +
                                            d_RC_dgradU(1,2)*u_gradphi[j][qp](2)
                                          )
                                          *fixed_deriv* u_gradphi[i][qp](2)
                                        )*JxW[qp];
                         (*Kww)(i,j) += ( -d_tau_M_dU(2)*RM_s(2)*test_func
                                          -tau_M*d_RM_s_dU(2,2)*test_func
                                        )*fixed_deriv*u_phi[j][qp]*JxW[qp];
                         (*Kww)(i,j) += ( -tau_M*RM_s(2)*d_test_func_dU(2)
                                        )*u_phi[j][qp]*JxW[qp];
                         (*Kww)(i,j) += ( - tau_C*
                                          (
                                            d_RC_dgradU(2,0)*u_gradphi[j][qp](0) +
                                            d_RC_dgradU(2,1)*u_gradphi[j][qp](1) +
                                            d_RC_dgradU(2,2)*u_gradphi[j][qp](2)
                                          )
                                          *fixed_deriv* u_gradphi[i][qp](2)
                                        )*JxW[qp];
                         (*Kww)(i,j) += ( -tau_M*test_func*(d_RM_s_uvw_dgraduvw*u_gradphi[j][qp])
                                        )*fixed_deriv*JxW[qp];
                         (*Kww)(i,j) += ( -tau_M*test_func*(d_RM_s_uvw_dhessuvw.contract(u_hessphi[j][qp]))
                                        )*fixed_deriv*JxW[qp];
                       }
                   }
               }
           }
       }
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->EndTimer("IncompressibleNavierStokesAdjointStabilization::element_time_derivative");
 #endif
     return;
   }
bool GRINS::Physics::enabled_on_elem (const libMesh::Elem * elem) virtual inherited
Find if current physics is active on supplied element.
Definition at line 83 of file physics.C.
References GRINS::Physics::_enabled_subdomains.
   {
     // Check if enabled_subdomains flag has been set and if we're
     // looking at a real element (rather than a nonlocal evaluation)
     if( !elem || _enabled_subdomains.empty() )
       return true;
     // Check if current physics is enabled on elem
     if( _enabled_subdomains.find( elem->subdomain_id() ) == _enabled_subdomains.end() )
       return false;
     return true;
   }
BCHandlingBase * GRINS::Physics::get_bc_handler () inline inherited
Definition at line 282 of file physics.h.
References GRINS::Physics::_bc_handler.
   {
     return _bc_handler;
   }
ICHandlingBase * GRINS::Physics::get_ic_handler () inline inherited
Definition at line 288 of file physics.h.
References GRINS::Physics::_ic_handler.
   {
     return _ic_handler;
   }
void GRINS::Physics::init_bcs (libMesh::FEMSystem * system) inherited
Definition at line 118 of file physics.C.
References GRINS::Physics::_bc_handler, GRINS::BCHandlingBase::init_bc_data(), GRINS::BCHandlingBase::init_dirichlet_bc_func_objs(), GRINS::BCHandlingBase::init_dirichlet_bcs(), and GRINS::BCHandlingBase::init_periodic_bcs().
   {
     // Only need to init BC's if the physics actually created a handler
     if( _bc_handler )
       {
         _bc_handler->init_bc_data( *system );
         _bc_handler->init_dirichlet_bcs( system );
         _bc_handler->init_dirichlet_bc_func_objs( system );
         _bc_handler->init_periodic_bcs( system );
       }
     return;
   }
template<class Mu > void GRINS::IncompressibleNavierStokesStabilizationBase< Mu >::init_context (AssemblyContext & context) virtual inherited
Initialize context for added physics variables.
Reimplemented from GRINS::IncompressibleNavierStokesBase< Viscosity >.
Definition at line 54 of file inc_navier_stokes_stab_base.C.
References GRINS::IncompressibleNavierStokesBase< Viscosity >::init_context().
   {
     // First call base class
     IncompressibleNavierStokesBase<Mu>::init_context(context);
     // We need pressure derivatives
     context.get_element_fe(this->_flow_vars.p_var())->get_dphi();
     // We also need second derivatives, so initialize those.
     context.get_element_fe(this->_flow_vars.u_var())->get_d2phi();
     return;
   }
void GRINS::Physics::init_ics (libMesh::FEMSystem * system, libMesh::CompositeFunction< libMesh::Number > & all_ics) inherited
Definition at line 133 of file physics.C.
References GRINS::Physics::_ic_handler, and GRINS::ICHandlingBase::init_ic_data().
   {
     if( _ic_handler )
       {
         _ic_handler->init_ic_data( *system, all_ics );
       }
     return;
   }
template<class Mu > void GRINS::IncompressibleNavierStokesStabilizationBase< Mu >::init_variables (libMesh::FEMSystem * system) virtual inherited
Initialization of Navier-Stokes variables.
Add velocity and pressure variables to system.
Reimplemented from GRINS::IncompressibleNavierStokesBase< Viscosity >.
Definition at line 69 of file inc_navier_stokes_stab_base.C.
References GRINS::IncompressibleNavierStokesBase< Viscosity >::init_variables().
   {
     // First call base class
     IncompressibleNavierStokesBase<Mu>::init_variables(system);
     _stab_helper.init(*system);
     return;
   }
bool GRINS::Physics::is_steady () const inherited
Returns whether or not this physics is being solved with a steady solver.
Definition at line 103 of file physics.C.
References GRINS::Physics::_is_steady.
Referenced by GRINS::Physics::set_is_steady().
   {
     return _is_steady;
   }
template<class Mu > void GRINS::IncompressibleNavierStokesAdjointStabilization< Mu >::mass_residual (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
Reimplemented from GRINS::Physics.
Definition at line 549 of file inc_navier_stokes_adjoint_stab.C.
   {
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->BeginTimer("IncompressibleNavierStokesAdjointStabilization::mass_residual");
 #endif
     // The number of local degrees of freedom in each variable.
     const unsigned int n_p_dofs = context.get_dof_indices(this->_flow_vars.p_var()).size();
     const unsigned int n_u_dofs = context.get_dof_indices(this->_flow_vars.u_var()).size();
     // Element Jacobian * quadrature weights for interior integration.
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(this->_flow_vars.u_var())->get_JxW();
     // The pressure shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::RealGradient> >& p_dphi =
       context.get_element_fe(this->_flow_vars.p_var())->get_dphi();
     const std::vector<std::vector<libMesh::Real> >& u_phi =
       context.get_element_fe(this->_flow_vars.u_var())->get_phi();
     const std::vector<std::vector<libMesh::RealGradient> >& u_gradphi =
       context.get_element_fe(this->_flow_vars.u_var())->get_dphi();
     const std::vector<std::vector<libMesh::RealTensor> >& u_hessphi =
       context.get_element_fe(this->_flow_vars.u_var())->get_d2phi();
     libMesh::DenseSubVector<libMesh::Number> &Fu = context.get_elem_residual(this->_flow_vars.u_var()); // R_{p}
     libMesh::DenseSubVector<libMesh::Number> &Fv = context.get_elem_residual(this->_flow_vars.v_var()); // R_{p}
     libMesh::DenseSubVector<libMesh::Number> *Fw = NULL;
     libMesh::DenseSubVector<libMesh::Number> &Fp = context.get_elem_residual(this->_flow_vars.p_var()); // R_{p}
     libMesh::DenseSubMatrix<libMesh::Number> &Kuu =
       context.get_elem_jacobian(this->_flow_vars.u_var(), this->_flow_vars.u_var()); // J_{uu}
     libMesh::DenseSubMatrix<libMesh::Number> &Kuv =
       context.get_elem_jacobian(this->_flow_vars.u_var(), this->_flow_vars.v_var()); // J_{uv}
     libMesh::DenseSubMatrix<libMesh::Number> &Kvu =
       context.get_elem_jacobian(this->_flow_vars.v_var(), this->_flow_vars.u_var()); // J_{vu}
     libMesh::DenseSubMatrix<libMesh::Number> &Kvv =
       context.get_elem_jacobian(this->_flow_vars.v_var(), this->_flow_vars.v_var()); // J_{vv}
     libMesh::DenseSubMatrix<libMesh::Number> *Kuw = NULL;
     libMesh::DenseSubMatrix<libMesh::Number> *Kvw = NULL;
     libMesh::DenseSubMatrix<libMesh::Number> *Kwu = NULL;
     libMesh::DenseSubMatrix<libMesh::Number> *Kwv = NULL;
     libMesh::DenseSubMatrix<libMesh::Number> *Kww = NULL;
     libMesh::DenseSubMatrix<libMesh::Number> &Kpu =
       context.get_elem_jacobian(this->_flow_vars.p_var(), this->_flow_vars.u_var()); // J_{pu}
     libMesh::DenseSubMatrix<libMesh::Number> &Kpv =
       context.get_elem_jacobian(this->_flow_vars.p_var(), this->_flow_vars.v_var()); // J_{pv}
     libMesh::DenseSubMatrix<libMesh::Number> *Kpw = NULL;
     if(this->_dim == 3)
       {
         Fw = &context.get_elem_residual(this->_flow_vars.w_var()); // R_{w}
         Kuw = &context.get_elem_jacobian
           (this->_flow_vars.u_var(), this->_flow_vars.w_var()); // J_{uw}
         Kvw = &context.get_elem_jacobian
           (this->_flow_vars.v_var(), this->_flow_vars.w_var()); // J_{vw}
         Kwu = &context.get_elem_jacobian
           (this->_flow_vars.w_var(), this->_flow_vars.u_var()); // J_{wu}
         Kwv = &context.get_elem_jacobian
           (this->_flow_vars.w_var(), this->_flow_vars.v_var()); // J_{wv}
         Kww = &context.get_elem_jacobian
           (this->_flow_vars.w_var(), this->_flow_vars.w_var()); // J_{ww}
         Kpw = &context.get_elem_jacobian
           (this->_flow_vars.p_var(), this->_flow_vars.w_var()); // J_{pw}
       }
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     for (unsigned int qp=0; qp != n_qpoints; qp++)
       {
         libMesh::FEBase* fe = context.get_element_fe(this->_flow_vars.u_var());
         libMesh::RealGradient g = this->_stab_helper.compute_g( fe, context, qp );
         libMesh::RealTensor G = this->_stab_helper.compute_G( fe, context, qp );
         libMesh::RealGradient U( context.fixed_interior_value( this->_flow_vars.u_var(), qp ),
                                  context.fixed_interior_value( this->_flow_vars.v_var(), qp ) );
         if( this->_dim == 3 )
           {
             U(2) = context.fixed_interior_value( this->_flow_vars.w_var(), qp );
           }
         /*
           libMesh::Gradient grad_u, grad_v, grad_w;
           grad_u = context.interior_gradient(this->_flow_vars.u_var(), qp);
           grad_v = context.interior_gradient(this->_flow_vars.v_var(), qp);
           if (_dim == 3)
           grad_w = context.interior_gradient(this->_flow_vars.w_var(), qp);
         */
         libMesh::Real tau_M;
         libMesh::Real d_tau_M_d_rho;
         libMesh::Gradient d_tau_M_dU;
         libMesh::RealGradient RM_t;
         libMesh::Real d_RM_t_uvw_duvw;
         // Compute the viscosity at this qp
         libMesh::Real _mu_qp = this->_mu(context, qp);
         if (compute_jacobian)
           {
             this->_stab_helper.compute_tau_momentum_and_derivs
               ( context, qp, g, G, this->_rho, U, _mu_qp,
                 tau_M, d_tau_M_d_rho, d_tau_M_dU,
                 false );
             this->_stab_helper.compute_res_momentum_transient_and_derivs
               ( context, qp, this->_rho,
                 RM_t, d_RM_t_uvw_duvw );
           }
         else
           {
             tau_M = this->_stab_helper.compute_tau_momentum( context, qp, g, G, this->_rho, U, _mu_qp, false );
             RM_t = this->_stab_helper.compute_res_momentum_transient( context, qp, this->_rho );
           }
         // Now a loop over the pressure degrees of freedom.  This
         // computes the contributions of the continuity equation.
         for (unsigned int i=0; i != n_p_dofs; i++)
           {
             Fp(i) -= tau_M*RM_t*p_dphi[i][qp]*JxW[qp];
             if (compute_jacobian)
               {
                 const libMesh::Real fixed_deriv =
                   context.get_fixed_solution_derivative();
                 for (unsigned int j=0; j != n_u_dofs; j++)
                   {
                     Kpu(i,j) -= d_tau_M_dU(0)*u_phi[j][qp]*RM_t*p_dphi[i][qp]*fixed_deriv*JxW[qp];
                     Kpu(i,j) -= tau_M*d_RM_t_uvw_duvw*u_phi[j][qp]*p_dphi[i][qp](0)*fixed_deriv*JxW[qp];
                     Kpv(i,j) -= d_tau_M_dU(1)*u_phi[j][qp]*RM_t*p_dphi[i][qp]*fixed_deriv*JxW[qp];
                     Kpv(i,j) -= tau_M*d_RM_t_uvw_duvw*u_phi[j][qp]*p_dphi[i][qp](1)*fixed_deriv*JxW[qp];
                   }
                 if(this->_dim == 3)
                   {
                     for (unsigned int j=0; j != n_u_dofs; j++)
                       {
                         (*Kpw)(i,j) -= d_tau_M_dU(2)*u_phi[j][qp]*RM_t*p_dphi[i][qp]*fixed_deriv*JxW[qp];
                         (*Kpw)(i,j) -= tau_M*d_RM_t_uvw_duvw*u_phi[j][qp]*p_dphi[i][qp](2)*fixed_deriv*JxW[qp];
                       }
                   }
               }
           }
         for (unsigned int i=0; i != n_u_dofs; i++)
           {
             libMesh::Real test_func = this->_rho*U*u_gradphi[i][qp] +
               _mu_qp*( u_hessphi[i][qp](0,0) + u_hessphi[i][qp](1,1) + u_hessphi[i][qp](2,2) );
             libMesh::Gradient d_test_func_dU = this->_rho*u_gradphi[i][qp];
             //libMesh::RealGradient zeroth_order_term = - this->_rho*u_phi[i][qp]*(grad_u + grad_v + grad_w);
             Fu(i) -= tau_M*RM_t(0)*test_func*JxW[qp];
             Fv(i) -= tau_M*RM_t(1)*test_func*JxW[qp];
             if(this->_dim == 3)
               {
                 (*Fw)(i) -= tau_M*RM_t(2)*test_func*JxW[qp];
               }
             if (compute_jacobian)
               {
                 const libMesh::Real fixed_deriv =
                   context.get_fixed_solution_derivative();
                 for (unsigned int j=0; j != n_u_dofs; j++)
                   {
                     Kuu(i,j) -= d_tau_M_dU(0)*u_phi[j][qp]*RM_t(0)*test_func*fixed_deriv*JxW[qp];
                     Kuu(i,j) -= tau_M*d_RM_t_uvw_duvw*u_phi[j][qp]*test_func*fixed_deriv*JxW[qp];
                     Kuu(i,j) -= tau_M*RM_t(0)*d_test_func_dU(0)*u_phi[j][qp]*fixed_deriv*JxW[qp];
                     Kuv(i,j) -= d_tau_M_dU(1)*u_phi[j][qp]*RM_t(0)*test_func*fixed_deriv*JxW[qp];
                     Kuv(i,j) -= tau_M*RM_t(0)*d_test_func_dU(1)*u_phi[j][qp]*fixed_deriv*JxW[qp];
                     Kvu(i,j) -= d_tau_M_dU(0)*u_phi[j][qp]*RM_t(1)*test_func*fixed_deriv*JxW[qp];
                     Kvu(i,j) -= tau_M*RM_t(1)*d_test_func_dU(0)*u_phi[j][qp]*fixed_deriv*JxW[qp];
                     Kvv(i,j) -= d_tau_M_dU(1)*u_phi[j][qp]*RM_t(1)*test_func*fixed_deriv*JxW[qp];
                     Kvv(i,j) -= tau_M*d_RM_t_uvw_duvw*u_phi[j][qp]*test_func*fixed_deriv*JxW[qp];
                     Kvv(i,j) -= tau_M*RM_t(1)*d_test_func_dU(1)*u_phi[j][qp]*fixed_deriv*JxW[qp];
                   }
                 if(this->_dim == 3)
                   {
                     for (unsigned int j=0; j != n_u_dofs; j++)
                       {
                         (*Kuw)(i,j) -= d_tau_M_dU(2)*u_phi[j][qp]*RM_t(0)*test_func*fixed_deriv*JxW[qp];
                         (*Kuw)(i,j) -= tau_M*RM_t(0)*d_test_func_dU(2)*u_phi[j][qp]*fixed_deriv*JxW[qp];
                         (*Kvw)(i,j) -= d_tau_M_dU(2)*u_phi[j][qp]*RM_t(1)*test_func*fixed_deriv*JxW[qp];
                         (*Kvw)(i,j) -= tau_M*RM_t(1)*d_test_func_dU(2)*u_phi[j][qp]*fixed_deriv*JxW[qp];
                         (*Kwu)(i,j) -= d_tau_M_dU(0)*u_phi[j][qp]*RM_t(2)*test_func*fixed_deriv*JxW[qp];
                         (*Kwu)(i,j) -= tau_M*RM_t(2)*d_test_func_dU(0)*u_phi[j][qp]*fixed_deriv*JxW[qp];
                         (*Kwv)(i,j) -= d_tau_M_dU(1)*u_phi[j][qp]*RM_t(2)*test_func*fixed_deriv*JxW[qp];
                         (*Kwv)(i,j) -= tau_M*RM_t(2)*d_test_func_dU(1)*u_phi[j][qp]*fixed_deriv*JxW[qp];
                         (*Kww)(i,j) -= d_tau_M_dU(2)*u_phi[j][qp]*RM_t(2)*test_func*fixed_deriv*JxW[qp];
                         (*Kww)(i,j) -= tau_M*d_RM_t_uvw_duvw*u_phi[j][qp]*test_func*fixed_deriv*JxW[qp];
                         (*Kww)(i,j) -= tau_M*RM_t(2)*d_test_func_dU(2)*u_phi[j][qp]*fixed_deriv*JxW[qp];
                       }
                   }
               }
           }
       }
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->EndTimer("IncompressibleNavierStokesAdjointStabilization::mass_residual");
 #endif
     return;
   }
void GRINS::Physics::nonlocal_constraint (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Constraint part(s) of physics for scalar variables.
Reimplemented in GRINS::ScalarODE.
Definition at line 250 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_constraint().
   {
     return;
   }
void GRINS::Physics::nonlocal_mass_residual (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Mass matrix part(s) for scalar variables.
Reimplemented in GRINS::ScalarODE, and GRINS::AveragedTurbine< Viscosity >.
Definition at line 264 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_mass_residual().
   {
     return;
   }
void GRINS::Physics::nonlocal_time_derivative (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Time dependent part(s) of physics for scalar variables.
Reimplemented in GRINS::AveragedTurbine< Viscosity >, and GRINS::ScalarODE.
Definition at line 229 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_time_derivative().
   {
     return;
   }
void GRINS::Physics::read_input_options (const GetPot & input) virtual inherited
Read options from GetPot input file. By default, nothing is read.
Reimplemented in GRINS::ScalarODE, GRINS::AveragedTurbineBase< Viscosity >, GRINS::AxisymmetricBoussinesqBuoyancy, GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::AxisymmetricHeatTransfer< Conductivity >, GRINS::AveragedFanBase< Viscosity >, GRINS::ParsedVelocitySourceBase< Viscosity >, GRINS::VelocityDragBase< Viscosity >, GRINS::VelocityPenaltyBase< Viscosity >, GRINS::IncompressibleNavierStokes< Viscosity >, GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::HeatTransfer< Conductivity >, GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >, and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >.
Definition at line 70 of file physics.C.
References GRINS::Physics::_enabled_subdomains, and GRINS::Physics::_physics_name.
Referenced by GRINS::HeatTransferBase< Conductivity >::HeatTransferBase(), GRINS::HeatTransferStabilizationBase< Conductivity >::HeatTransferStabilizationBase(), GRINS::IncompressibleNavierStokesAdjointStabilization< Viscosity >::IncompressibleNavierStokesAdjointStabilization(), GRINS::IncompressibleNavierStokesSPGSMStabilization< Viscosity >::IncompressibleNavierStokesSPGSMStabilization(), GRINS::Physics::Physics(), and GRINS::SpalartAllmarasSPGSMStabilization< Viscosity >::SpalartAllmarasSPGSMStabilization().
   {
     int num_ids = input.vector_variable_size( "Physics/"+this->_physics_name+"/enabled_subdomains" );
     for( int i = 0; i < num_ids; i++ )
       {
         libMesh::subdomain_id_type dumvar = input( "Physics/"+this->_physics_name+"/enabled_subdomains", -1, i );
         _enabled_subdomains.insert( dumvar );
       }
     return;
   }
template<class Mu > void GRINS::IncompressibleNavierStokesBase< Mu >::register_parameter (const std::string & param_name, libMesh::ParameterMultiPointer< libMesh::Number > & param_pointer) const virtual inherited
Each subclass will register its copy of an independent.
Reimplemented from GRINS::ParameterUser.
Definition at line 114 of file inc_navier_stokes_base.C.
References GRINS::ParameterUser::register_parameter().
   {
     ParameterUser::register_parameter(param_name, param_pointer);
     _mu.register_parameter(param_name, param_pointer);
   }
void GRINS::Physics::register_postprocessing_vars (const GetPot & input, PostProcessedQuantities< libMesh::Real > & postprocessing) virtual inherited
Register name of postprocessed quantity with PostProcessedQuantities.
Each Physics class will need to cache an unsigned int corresponding to each postprocessed quantity. This will be used in computing the values and putting them in the CachedVariables object.
Reimplemented in GRINS::ParsedVelocitySource< Viscosity >, GRINS::VelocityPenalty< Viscosity >, GRINS::IncompressibleNavierStokes< Viscosity >, GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::HeatTransfer< Conductivity >, GRINS::ElasticCable< StressStrainLaw >, GRINS::ElasticMembrane< StressStrainLaw >, and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >.
Definition at line 161 of file physics.C.
   {
     return;
   }
void GRINS::Physics::set_is_steady (bool is_steady) inherited
Sets whether this physics is to be solved with a steady solver or not.
Since the member variable is static, only needs to be called on a single physics.
Definition at line 97 of file physics.C.
References GRINS::Physics::_is_steady, and GRINS::Physics::is_steady().
   {
     _is_steady = is_steady;
     return;
   }
void GRINS::ParameterUser::set_parameter (libMesh::Number & param_variable, const GetPot & input, const std::string & param_name, libMesh::Number param_default) virtual inherited
Each subclass can simultaneously read a parameter value from.
Definition at line 35 of file parameter_user.C.
References GRINS::ParameterUser::_my_name, and GRINS::ParameterUser::_my_parameters.
Referenced by GRINS::AveragedFanAdjointStabilization< Viscosity >::AveragedFanAdjointStabilization(), GRINS::AveragedTurbineAdjointStabilization< Viscosity >::AveragedTurbineAdjointStabilization(), GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::BoussinesqBuoyancyAdjointStabilization(), GRINS::BoussinesqBuoyancyBase::BoussinesqBuoyancyBase(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::BoussinesqBuoyancySPGSMStabilization(), GRINS::ConstantConductivity::ConstantConductivity(), GRINS::ConstantPrandtlConductivity::ConstantPrandtlConductivity(), GRINS::ConstantSourceFunction::ConstantSourceFunction(), GRINS::ConstantSourceTerm::ConstantSourceTerm(), GRINS::ConstantSpecificHeat::ConstantSpecificHeat(), GRINS::ConstantViscosity::ConstantViscosity(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticCableConstantGravity::ElasticCableConstantGravity(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransferBase< Conductivity >::HeatTransferBase(), GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase(), GRINS::AverageNusseltNumber::init(), GRINS::MooneyRivlin::MooneyRivlin(), GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase(), GRINS::HookesLaw1D::read_input_options(), GRINS::HookesLaw::read_input_options(), GRINS::AxisymmetricBoussinesqBuoyancy::read_input_options(), and GRINS::VelocityDragAdjointStabilization< Viscosity >::VelocityDragAdjointStabilization().
   {
     param_variable = input(param_name, param_default);
     libmesh_assert_msg(!_my_parameters.count(param_name),
       "ERROR: " << _my_name << " double-registered parameter " <<
       param_name);
     _my_parameters[param_name] = &param_variable;
   }
template<class Mu > void GRINS::IncompressibleNavierStokesBase< Mu >::set_time_evolving_vars (libMesh::FEMSystem * system) virtual inherited
Sets velocity variables to be time-evolving.
Reimplemented from GRINS::Physics.
Reimplemented in GRINS::AveragedTurbineBase< Viscosity >, and GRINS::ParsedVelocitySourceBase< Viscosity >.
Definition at line 75 of file inc_navier_stokes_base.C.
Referenced by GRINS::AveragedTurbineBase< Viscosity >::set_time_evolving_vars().
   {
     const unsigned int dim = system->get_mesh().mesh_dimension();
     // Tell the system to march velocity forward in time, but
     // leave p as a constraint only
     system->time_evolving(_flow_vars.u_var());
     system->time_evolving(_flow_vars.v_var());
     if (dim == 3)
       system->time_evolving(_flow_vars.w_var());
     return;
   }
void GRINS::Physics::side_constraint (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Constraint part(s) of physics for boundaries of elements on the domain boundary.
Reimplemented in GRINS::IncompressibleNavierStokes< Viscosity >, GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >.
Definition at line 243 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::side_constraint().
   {
     return;
   }
void GRINS::Physics::side_time_derivative (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
Reimplemented in GRINS::AxisymmetricHeatTransfer< Conductivity >, GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::HeatTransfer< Conductivity >, GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >, GRINS::ElasticCable< StressStrainLaw >, and GRINS::ElasticMembrane< StressStrainLaw >.
Definition at line 222 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::side_time_derivative().
   {
     return;
   }
Member Data Documentation
GRINS::BCHandlingBase* GRINS::Physics::_bc_handler protected inherited
Definition at line 256 of file physics.h.
Referenced by GRINS::Physics::attach_dirichlet_bound_func(), GRINS::Physics::attach_neumann_bound_func(), GRINS::AxisymmetricHeatTransfer< Conductivity >::AxisymmetricHeatTransfer(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::Physics::get_bc_handler(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransfer< Conductivity >::HeatTransfer(), GRINS::IncompressibleNavierStokes< Viscosity >::IncompressibleNavierStokes(), GRINS::Physics::init_bcs(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokes(), GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::ReactingLowMachNavierStokes(), GRINS::SpalartAllmaras< Viscosity >::SpalartAllmaras(), GRINS::Stokes< Viscosity >::Stokes(), and GRINS::Physics::~Physics().
template<class Viscosity > unsigned int GRINS::IncompressibleNavierStokesBase< Viscosity >::_dim protected inherited
Physical dimension of problem.
Todo:
Do we really need to cache this?
Definition at line 79 of file inc_navier_stokes_base.h.
std::set<libMesh::subdomain_id_type> GRINS::Physics::_enabled_subdomains protected inherited
Subdomains on which the current Physics class is enabled.
Definition at line 261 of file physics.h.
Referenced by GRINS::Physics::enabled_on_elem(), and GRINS::Physics::read_input_options().
template<class Viscosity > PrimitiveFlowFEVariables GRINS::IncompressibleNavierStokesBase< Viscosity >::_flow_vars protected inherited
Definition at line 81 of file inc_navier_stokes_base.h.
GRINS::ICHandlingBase* GRINS::Physics::_ic_handler protected inherited
Definition at line 258 of file physics.h.
Referenced by GRINS::AveragedTurbine< Viscosity >::AveragedTurbine(), GRINS::AxisymmetricHeatTransfer< Conductivity >::AxisymmetricHeatTransfer(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::Physics::get_ic_handler(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransfer< Conductivity >::HeatTransfer(), GRINS::IncompressibleNavierStokes< Viscosity >::IncompressibleNavierStokes(), GRINS::Physics::init_ics(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokes(), GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::ReactingLowMachNavierStokes(), GRINS::ScalarODE::ScalarODE(), GRINS::SpalartAllmaras< Viscosity >::SpalartAllmaras(), GRINS::Stokes< Viscosity >::Stokes(), and GRINS::Physics::~Physics().
bool GRINS::Physics::_is_axisymmetric protected inherited
Definition at line 268 of file physics.h.
Referenced by GRINS::HeatTransfer< Conductivity >::HeatTransfer(), GRINS::IncompressibleNavierStokes< Viscosity >::IncompressibleNavierStokes(), GRINS::Physics::Physics(), and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::ReactingLowMachNavierStokes().
bool GRINS::Physics::_is_steady = false static protected inherited
Caches whether or not the solver that's being used is steady or not.
This is need, for example, in flow stabilization as the tau terms change depending on whether the solver is steady or unsteady.
Definition at line 266 of file physics.h.
Referenced by GRINS::Physics::is_steady(), and GRINS::Physics::set_is_steady().
template<class Viscosity > Viscosity GRINS::IncompressibleNavierStokesBase< Viscosity >::_mu protected inherited
Viscosity object.
Definition at line 88 of file inc_navier_stokes_base.h.
const PhysicsName GRINS::Physics::_physics_name protected inherited
Name of the physics object. Used for reading physics specific inputs.
We use a reference because the physics names are const global objects in GRINS namespace
No, we use a copy, because otherwise as soon as the memory in std::set<std::string> requested_physics gets overwritten we get in trouble.
Definition at line 254 of file physics.h.
Referenced by GRINS::SourceTermBase::parse_var_info(), and GRINS::Physics::read_input_options().
template<class Viscosity > libMesh::Number GRINS::IncompressibleNavierStokesBase< Viscosity >::_rho protected inherited
Material parameters, read from input.
Todo:
Create objects to allow for function specification
Definition at line 85 of file inc_navier_stokes_base.h.
Referenced by GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase().
template<class Viscosity > IncompressibleNavierStokesStabilizationHelper GRINS::IncompressibleNavierStokesStabilizationBase< Viscosity >::_stab_helper protected inherited
Definition at line 52 of file inc_navier_stokes_stab_base.h.
The documentation for this class was generated from the following files:
src/physics/include/grins/inc_navier_stokes_adjoint_stab.h
src/physics/src/inc_navier_stokes_adjoint_stab.C