GRINS-0.6.0: GRINS::AverageNusseltNumber Class Reference
GRINS::AverageNusseltNumber Class Reference
#include <average_nusselt_number.h>
Public Member Functions
AverageNusseltNumber (const std::string &qoi_name)
virtual ~AverageNusseltNumber ()
virtual QoIBase * clone () const
Clone this QoI.
virtual bool assemble_on_interior () const
Does the QoI need an element interior assembly loop?
virtual bool assemble_on_sides () const
Does the QoI need a domain boundary assembly loop?
virtual void side_qoi (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi value on the domain boundary.
virtual void side_qoi_derivative (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi derivative with respect to the solution on the domain boundary.
virtual void init (const GetPot &input, const MultiphysicsSystem &system)
Method to allow QoI to cache any system information needed for QoI calculation, for example, solution variable indices.
virtual void init_context (AssemblyContext &context)
virtual void element_qoi (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi value for element interiors.
virtual void element_qoi_derivative (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi derivative with respect to the solution on element interiors.
virtual void parallel_op (const libMesh::Parallel::Communicator &communicator, libMesh::Number &sys_qoi, libMesh::Number &local_qoi)
Call the parallel operation for this QoI and cache the value.
virtual void thread_join (libMesh::Number &qoi, const libMesh::Number &other_qoi)
Call the operation to accumulate this QoI from multiple threads.
virtual void output_qoi (std::ostream &out) const
Basic output for computed QoI's.
libMesh::Number value () const
Returns the current QoI value.
const std::string & name () const
Returns the name of this QoI.
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiPointer< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Attributes
libMesh::Real _k
Thermal conductivity.
VariableIndex _T_var
Temperature variable index.
std::set< libMesh::boundary_id_type > _bc_ids
List of boundary ids for which we want to compute this QoI.
libMesh::Real _scaling
Scaling constant.
std::string _qoi_name
libMesh::Number _qoi_value
Private Member Functions
AverageNusseltNumber ()
Detailed Description
Definition at line 35 of file average_nusselt_number.h.
Constructor & Destructor Documentation
GRINS::AverageNusseltNumber::AverageNusseltNumber (const std::string & qoi_name)
Definition at line 40 of file average_nusselt_number.C.
     : QoIBase(qoi_name)
   {
     return;
   }
GRINS::AverageNusseltNumber::~AverageNusseltNumber () virtual
Definition at line 46 of file average_nusselt_number.C.
   {
     return;
   }
GRINS::AverageNusseltNumber::AverageNusseltNumber () private
Referenced by clone().
Member Function Documentation
bool GRINS::AverageNusseltNumber::assemble_on_interior () const inline virtual
Does the QoI need an element interior assembly loop?
This is pure virtual to force to user to specify.
Implements GRINS::QoIBase.
Definition at line 80 of file average_nusselt_number.h.
   {
     return false;
   }
bool GRINS::AverageNusseltNumber::assemble_on_sides () const inline virtual
Does the QoI need a domain boundary assembly loop?
This is pure virtual to force to user to specify.
Implements GRINS::QoIBase.
Definition at line 86 of file average_nusselt_number.h.
   {
     return true;
   }
QoIBase * GRINS::AverageNusseltNumber::clone () const virtual
Clone this QoI.
We return a raw pointer, but it is expected for the user to take ownership and delete the object when done.
Implements GRINS::QoIBase.
Definition at line 51 of file average_nusselt_number.C.
References AverageNusseltNumber().
   {
     return new AverageNusseltNumber( *this );
   }
void GRINS::QoIBase::element_qoi (AssemblyContext & context, const unsigned int qoi_index) virtual inherited
Compute the qoi value for element interiors.
Override this method if your QoI is defined on element interiors
Reimplemented in GRINS::Vorticity, and GRINS::ParsedInteriorQoI.
Definition at line 63 of file qoi_base.C.
   {
     return;
   }
void GRINS::QoIBase::element_qoi_derivative (AssemblyContext & context, const unsigned int qoi_index) virtual inherited
Compute the qoi derivative with respect to the solution on element interiors.
Override this method if your QoI is defined on element interiors
Reimplemented in GRINS::Vorticity, and GRINS::ParsedInteriorQoI.
Definition at line 69 of file qoi_base.C.
   {
     return;
   }
void GRINS::AverageNusseltNumber::init (const GetPot & input, const MultiphysicsSystem & system) virtual
Method to allow QoI to cache any system information needed for QoI calculation, for example, solution variable indices.
Reimplemented from GRINS::QoIBase.
Definition at line 56 of file average_nusselt_number.C.
References _bc_ids, _k, _scaling, _T_var, GRINS::ParameterUser::set_parameter(), and GRINS::T_var_name_default.
   {
     this->set_parameter
       ( _k, input, "QoI/NusseltNumber/thermal_conductivity", -1.0 );
     this->set_parameter
       ( _scaling, input, "QoI/NusseltNumber/scaling", 1.0 );
     if( this->_k < 0.0 )
       {
         std::cerr << "Error: thermal conductivity for AverageNusseltNumber must be positive." << std::endl
                   << "Found k = " << _k << std::endl;
         libmesh_error();
       }
     // Read boundary ids for which we want to compute
     int num_bcs =  input.vector_variable_size("QoI/NusseltNumber/bc_ids");
     if( num_bcs <= 0 )
       {
         std::cerr << "Error: Must specify at least one boundary id to compute"
                   << " average Nusselt number." << std::endl
                   << "Found: " << num_bcs << std::endl;
         libmesh_error();
       }
     for( int i = 0; i < num_bcs; i++ )
       {
         _bc_ids.insert( input("QoI/NusseltNumber/bc_ids", -1, i ) );
       }
     // Grab temperature variable index
     std::string T_var_name = input( "Physics/VariableNames/Temperature",
                                     T_var_name_default );
     this->_T_var = system.variable_number(T_var_name);
     return;
   }
void GRINS::AverageNusseltNumber::init_context (AssemblyContext & context) virtual
Reimplemented from GRINS::QoIBase.
Definition at line 96 of file average_nusselt_number.C.
References _T_var.
   {
     libMesh::FEBase* T_fe;
     context.get_side_fe<libMesh::Real>(this->_T_var, T_fe);
     T_fe->get_dphi();
     T_fe->get_JxW();
     return;
   }
const std::string & GRINS::QoIBase::name () const inline inherited
Returns the name of this QoI.
Definition at line 143 of file qoi_base.h.
References GRINS::QoIBase::_qoi_name.
Referenced by GRINS::SteadyVisualization::output_adjoint(), and GRINS::UnsteadyVisualization::output_adjoint().
   {
     return _qoi_name;
   }
void GRINS::QoIBase::output_qoi (std::ostream & out) const virtual inherited
Basic output for computed QoI's.
If fancier output is desired, override this method.
Definition at line 107 of file qoi_base.C.
References GRINS::QoIBase::_qoi_name, and GRINS::QoIBase::_qoi_value.
   {
     out << "==========================================================" << std::endl;
     out << _qoi_name+" = "
         << std::setprecision(16)
         << std::scientific
         << _qoi_value << std::endl;
     out << "==========================================================" << std::endl;
     return;
   }
void GRINS::QoIBase::parallel_op (const libMesh::Parallel::Communicator & communicator, libMesh::Number & sys_qoi, libMesh::Number & local_qoi) virtual inherited
Call the parallel operation for this QoI and cache the value.
By default, this is just a sum. Override if QoI is more complex.
Definition at line 87 of file qoi_base.C.
References GRINS::QoIBase::_qoi_value.
   {
     communicator.sum(local_qoi);
     sys_qoi = local_qoi;
     _qoi_value = sys_qoi;
     return;
   }
void GRINS::ParameterUser::register_parameter (const std::string & param_name, libMesh::ParameterMultiPointer< libMesh::Number > & param_pointer) const virtual inherited
Each subclass will register its copy of an independent.
Reimplemented in GRINS::AxisymmetricHeatTransfer< Conductivity >, GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::IncompressibleNavierStokesBase< Viscosity >, GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >, GRINS::HeatConduction< Conductivity >, GRINS::HeatTransferBase< Conductivity >, and GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >.
Definition at line 50 of file parameter_user.C.
Referenced by GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::register_parameter(), GRINS::HeatTransferBase< Conductivity >::register_parameter(), GRINS::HeatConduction< Conductivity >::register_parameter(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::register_parameter(), GRINS::IncompressibleNavierStokesBase< Viscosity >::register_parameter(), GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::register_parameter(), and GRINS::AxisymmetricHeatTransfer< Conductivity >::register_parameter().
   {
     std::map<std::string, libMesh::Number*>::const_iterator it =
       _my_parameters.find(param_name);
     if (it != _my_parameters.end())
       {
         std::cout << _my_name << " uses parameter " << param_name
                   << std::endl;
         param_pointer.push_back(it->second);
       }
   }
void GRINS::ParameterUser::set_parameter (libMesh::Number & param_variable, const GetPot & input, const std::string & param_name, libMesh::Number param_default) virtual inherited
Each subclass can simultaneously read a parameter value from.
Definition at line 35 of file parameter_user.C.
References GRINS::ParameterUser::_my_name, and GRINS::ParameterUser::_my_parameters.
Referenced by GRINS::AveragedFanAdjointStabilization< Viscosity >::AveragedFanAdjointStabilization(), GRINS::AveragedTurbineAdjointStabilization< Viscosity >::AveragedTurbineAdjointStabilization(), GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::BoussinesqBuoyancyAdjointStabilization(), GRINS::BoussinesqBuoyancyBase::BoussinesqBuoyancyBase(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::BoussinesqBuoyancySPGSMStabilization(), GRINS::ConstantConductivity::ConstantConductivity(), GRINS::ConstantPrandtlConductivity::ConstantPrandtlConductivity(), GRINS::ConstantSourceFunction::ConstantSourceFunction(), GRINS::ConstantSourceTerm::ConstantSourceTerm(), GRINS::ConstantSpecificHeat::ConstantSpecificHeat(), GRINS::ConstantViscosity::ConstantViscosity(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticCableConstantGravity::ElasticCableConstantGravity(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransferBase< Conductivity >::HeatTransferBase(), GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase(), init(), GRINS::MooneyRivlin::MooneyRivlin(), GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase(), GRINS::HookesLaw1D::read_input_options(), GRINS::HookesLaw::read_input_options(), GRINS::AxisymmetricBoussinesqBuoyancy::read_input_options(), and GRINS::VelocityDragAdjointStabilization< Viscosity >::VelocityDragAdjointStabilization().
   {
     param_variable = input(param_name, param_default);
     libmesh_assert_msg(!_my_parameters.count(param_name),
       "ERROR: " << _my_name << " double-registered parameter " <<
       param_name);
     _my_parameters[param_name] = &param_variable;
   }
void GRINS::AverageNusseltNumber::side_qoi (AssemblyContext & context, const unsigned int qoi_index) virtual
Compute the qoi value on the domain boundary.
Override this method if your QoI is defined on the domain boundary
Reimplemented from GRINS::QoIBase.
Definition at line 108 of file average_nusselt_number.C.
References _bc_ids, _k, _scaling, and _T_var.
   {
     bool on_correct_side = false;
     for (std::set<libMesh::boundary_id_type>::const_iterator id =
          _bc_ids.begin(); id != _bc_ids.end(); id++ )
       if( context.has_side_boundary_id( (*id) ) )
         {
           on_correct_side = true;
           break;
         }
     if (!on_correct_side)
       return;
     libMesh::FEBase* side_fe;
     context.get_side_fe<libMesh::Real>(this->_T_var, side_fe);
     const std::vector<libMesh::Real> &JxW = side_fe->get_JxW();
     const std::vector<libMesh::Point>& normals = side_fe->get_normals();
     unsigned int n_qpoints = context.get_side_qrule().n_points();
     libMesh::Number& qoi = context.get_qois()[qoi_index];
     // Loop over quadrature points
     for (unsigned int qp = 0; qp != n_qpoints; qp++)
       {
         // Get the solution value at the quadrature point
         libMesh::Gradient grad_T = 0.0;
         context.side_gradient(this->_T_var, qp, grad_T);
         // Update the elemental increment dR for each qp
         qoi += (this->_scaling)*(this->_k)*(grad_T*normals[qp])*JxW[qp];
       } // quadrature loop
   }
void GRINS::AverageNusseltNumber::side_qoi_derivative (AssemblyContext & context, const unsigned int qoi_index) virtual
Compute the qoi derivative with respect to the solution on the domain boundary.
Override this method if your QoI is defined on the domain boundary
Reimplemented from GRINS::QoIBase.
Definition at line 149 of file average_nusselt_number.C.
References _bc_ids, _k, _scaling, and _T_var.
   {
     for( std::set<libMesh::boundary_id_type>::const_iterator id = _bc_ids.begin();
          id != _bc_ids.end(); id++ )
       {
         if( context.has_side_boundary_id( (*id) ) )
           {
             libMesh::FEBase* T_side_fe;
             context.get_side_fe<libMesh::Real>(this->_T_var, T_side_fe);
             const std::vector<libMesh::Real> &JxW = T_side_fe->get_JxW();
             const std::vector<libMesh::Point>& normals = T_side_fe->get_normals();
             unsigned int n_qpoints = context.get_side_qrule().n_points();
             const unsigned int n_T_dofs = context.get_dof_indices(_T_var).size();
             const std::vector<std::vector<libMesh::Gradient> >& T_gradphi = T_side_fe->get_dphi();
             libMesh::DenseSubVector<libMesh::Number>& dQ_dT =
               context.get_qoi_derivatives(qoi_index, _T_var);
             // Loop over quadrature points
             for (unsigned int qp = 0; qp != n_qpoints; qp++)
               {
                 // Get the solution value at the quadrature point
                 libMesh::Gradient grad_T = 0.0;
                 context.side_gradient(this->_T_var, qp, grad_T);
                 // Update the elemental increment dR for each qp
                 //qoi += (this->_scaling)*(this->_k)*(grad_T*normals[qp])*JxW[qp];
                 for( unsigned int i = 0; i != n_T_dofs; i++ )
                   {
                     dQ_dT(i) += _scaling*_k*T_gradphi[i][qp]*normals[qp]*JxW[qp];
                   }
               } // quadrature loop
           } // end check on boundary id
       }
     return;
   }
void GRINS::QoIBase::thread_join (libMesh::Number & qoi, const libMesh::Number & other_qoi) virtual inherited
Call the operation to accumulate this QoI from multiple threads.
By default, this is just a sum. Override if QoI is more complex.
Definition at line 100 of file qoi_base.C.
   {
     qoi += other_qoi;
     return;
   }
libMesh::Number GRINS::QoIBase::value () const inline inherited
Returns the current QoI value.
Definition at line 137 of file qoi_base.h.
References GRINS::QoIBase::_qoi_value.
   {
     return _qoi_value;
   }
Member Data Documentation
std::set<libMesh::boundary_id_type> GRINS::AverageNusseltNumber::_bc_ids protected
List of boundary ids for which we want to compute this QoI.
Definition at line 68 of file average_nusselt_number.h.
Referenced by init(), side_qoi(), and side_qoi_derivative().
libMesh::Real GRINS::AverageNusseltNumber::_k protected
Thermal conductivity.
Definition at line 62 of file average_nusselt_number.h.
Referenced by init(), side_qoi(), and side_qoi_derivative().
std::string GRINS::QoIBase::_qoi_name protected inherited
Definition at line 131 of file qoi_base.h.
Referenced by GRINS::QoIBase::name(), and GRINS::QoIBase::output_qoi().
libMesh::Number GRINS::QoIBase::_qoi_value protected inherited
Definition at line 133 of file qoi_base.h.
Referenced by GRINS::QoIBase::output_qoi(), GRINS::QoIBase::parallel_op(), and GRINS::QoIBase::value().
libMesh::Real GRINS::AverageNusseltNumber::_scaling protected
Scaling constant.
Definition at line 71 of file average_nusselt_number.h.
Referenced by init(), side_qoi(), and side_qoi_derivative().
VariableIndex GRINS::AverageNusseltNumber::_T_var protected
Temperature variable index.
Definition at line 65 of file average_nusselt_number.h.
Referenced by init(), init_context(), side_qoi(), and side_qoi_derivative().
The documentation for this class was generated from the following files:
src/qoi/include/grins/average_nusselt_number.h
src/qoi/src/average_nusselt_number.C