GRINS-0.6.0: GRINS::DBCContainer Class Reference
GRINS::DBCContainer Class Reference
Simple helper class to setup general Dirichlet boundary conditions.
#include <dbc_container.h>
Public Member Functions
DBCContainer ()
~DBCContainer ()
void add_var_name (const GRINS::VariableName &var)
Add variables that are constrained by the Dirichlet bc.
void add_bc_id (const GRINS::BoundaryID bc_id)
Add boundary id's for which this Dirichlet bc is to be applied.
void set_func (std::tr1::shared_ptr< libMesh::FunctionBase< libMesh::Number > > func)
Add the Dirichlet bc functor.
void set_fem_func_string (const std::string &s)
std::vector< GRINS::VariableName > get_var_names () const
std::set< GRINS::BoundaryID > get_bc_ids () const
std::tr1::shared_ptr< libMesh::FunctionBase< libMesh::Number > > get_func () const
const std::string & get_fem_func_string () const
Private Attributes
std::vector< GRINS::VariableName > _var_names
std::set< GRINS::BoundaryID > _bc_ids
std::tr1::shared_ptr< libMesh::FunctionBase< libMesh::Number > > _func
std::string _parsed_fem_func_string
Detailed Description
Simple helper class to setup general Dirichlet boundary conditions.
This class is to temporarily stash data necessary for setting up libMesh::DirichletBoundary objects. Actual instantiation of libMesh::DirichletBoundary object is handled internally by GRINS::Physics::init_user_dirichlet_bcs. For each Dirichlet bc function, there is a unique DBCContainer object.
Definition at line 49 of file dbc_container.h.
Constructor & Destructor Documentation
GRINS::DBCContainer::DBCContainer ()
Definition at line 32 of file dbc_container.C.
     : _var_names( std::vector<VariableName>() ),
       _bc_ids( std::set<BoundaryID>() ),
       _func( std::tr1::shared_ptr<libMesh::FunctionBase<libMesh::Number> >() ),
       _parsed_fem_func_string()
   {
     return;
   }
GRINS::DBCContainer::~DBCContainer ()
Definition at line 41 of file dbc_container.C.
   {
     return;
   }
Member Function Documentation
void GRINS::DBCContainer::add_bc_id (const GRINS::BoundaryID bc_id)
Add boundary id's for which this Dirichlet bc is to be applied.
Definition at line 52 of file dbc_container.C.
References _bc_ids.
Referenced by AxiParabolicBCFactory::build_dirichlet(), ParabolicBCFactory::build_dirichlet(), AxiConCylBCFactory::build_dirichlet(), TurbulentBCFactory::build_dirichlet(), GRINS::LowMachNavierStokesBCHandling::init_bc_types(), GRINS::IncompressibleNavierStokesBCHandling::init_bc_types(), and GRINS::BCHandlingBase::init_bc_types().
   {
     _bc_ids.insert( bc_id );
     return;
   }
void GRINS::DBCContainer::add_var_name (const GRINS::VariableName & var)
Add variables that are constrained by the Dirichlet bc.
Definition at line 46 of file dbc_container.C.
References _var_names.
Referenced by AxiParabolicBCFactory::build_dirichlet(), ParabolicBCFactory::build_dirichlet(), AxiConCylBCFactory::build_dirichlet(), TurbulentBCFactory::build_dirichlet(), GRINS::LowMachNavierStokesBCHandling::init_bc_types(), GRINS::IncompressibleNavierStokesBCHandling::init_bc_types(), and GRINS::BCHandlingBase::init_bc_types().
   {
     _var_names.push_back( var );
     return;
   }
std::set< BoundaryID > GRINS::DBCContainer::get_bc_ids () const
Definition at line 75 of file dbc_container.C.
References _bc_ids.
   {
     return _bc_ids;
   }
const std::string & GRINS::DBCContainer::get_fem_func_string () const
Definition at line 81 of file dbc_container.C.
References _parsed_fem_func_string.
   {
     return _parsed_fem_func_string;
   }
std::tr1::shared_ptr< libMesh::FunctionBase< libMesh::Number > > GRINS::DBCContainer::get_func () const
Definition at line 86 of file dbc_container.C.
References _func.
   {
     return _func;
   }
std::vector< VariableName > GRINS::DBCContainer::get_var_names () const
Definition at line 70 of file dbc_container.C.
References _var_names.
   {
     return _var_names;
   }
void GRINS::DBCContainer::set_fem_func_string (const std::string & s)
Definition at line 64 of file dbc_container.C.
References _parsed_fem_func_string.
Referenced by GRINS::BCHandlingBase::init_bc_types().
   {
     _parsed_fem_func_string = s;
     return;
   }
void GRINS::DBCContainer::set_func (std::tr1::shared_ptr< libMesh::FunctionBase< libMesh::Number > > func)
Add the Dirichlet bc functor.
There is only one Dirichlet bc functor for each container object
Definition at line 58 of file dbc_container.C.
References _func.
Referenced by AxiParabolicBCFactory::build_dirichlet(), ParabolicBCFactory::build_dirichlet(), AxiConCylBCFactory::build_dirichlet(), TurbulentBCFactory::build_dirichlet(), GRINS::LowMachNavierStokesBCHandling::init_bc_types(), GRINS::IncompressibleNavierStokesBCHandling::init_bc_types(), and GRINS::BCHandlingBase::init_bc_types().
   {
     _func = func;
     return;
   }
Member Data Documentation
std::set<GRINS::BoundaryID> GRINS::DBCContainer::_bc_ids private
Definition at line 80 of file dbc_container.h.
Referenced by add_bc_id(), and get_bc_ids().
std::tr1::shared_ptr<libMesh::FunctionBase<libMesh::Number> > GRINS::DBCContainer::_func private
Definition at line 81 of file dbc_container.h.
Referenced by get_func(), and set_func().
std::string GRINS::DBCContainer::_parsed_fem_func_string private
Definition at line 82 of file dbc_container.h.
Referenced by get_fem_func_string(), and set_fem_func_string().
std::vector<GRINS::VariableName> GRINS::DBCContainer::_var_names private
Definition at line 79 of file dbc_container.h.
Referenced by add_var_name(), and get_var_names().
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/dbc_container.h
src/boundary_conditions/src/dbc_container.C