GRINS-0.6.0: GRINS::StabilizationHelper Class Reference
GRINS::StabilizationHelper Class Reference
#include <stab_helper.h>
Public Member Functions
StabilizationHelper (const std::string &helper_name)
~StabilizationHelper ()
libMesh::RealGradient compute_g (libMesh::FEBase *fe, AssemblyContext &c, unsigned int qp) const
libMesh::RealTensor compute_G (libMesh::FEBase *fe, AssemblyContext &c, unsigned int qp) const
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiPointer< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Detailed Description
Definition at line 42 of file stab_helper.h.
Constructor & Destructor Documentation
GRINS::StabilizationHelper::StabilizationHelper (const std::string & helper_name)
Definition at line 36 of file stab_helper.C.
                                       :
     ParameterUser(helper_name)
   {
     return;
   }
GRINS::StabilizationHelper::~StabilizationHelper ()
Definition at line 42 of file stab_helper.C.
   {
     return;
   }
Member Function Documentation
libMesh::RealGradient GRINS::StabilizationHelper::compute_g (libMesh::FEBase * fe, AssemblyContext & c, unsigned int qp) const
Todo:
Should we inline this?
Definition at line 47 of file stab_helper.C.
   {
     libMesh::RealGradient g( fe->get_dxidx()[qp] + fe->get_detadx()[qp],
                              fe->get_dxidy()[qp] + fe->get_detady()[qp] );
     if( c.get_dim() == 3 )
       {
         g(0) += fe->get_dzetadx()[qp];
         g(1) += fe->get_dzetady()[qp];
         g(2) = fe->get_dxidz()[qp] + fe->get_detadz()[qp] + fe->get_dzetadz()[qp];
       }
     return g;
   }
libMesh::RealTensor GRINS::StabilizationHelper::compute_G (libMesh::FEBase * fe, AssemblyContext & c, unsigned int qp) const
Todo:
Should we inline this?
Definition at line 64 of file stab_helper.C.
   {
     libMesh::Real dxidx = fe->get_dxidx()[qp];
     libMesh::Real dxidy = fe->get_dxidy()[qp];
     libMesh::Real detadx = fe->get_detadx()[qp];
     libMesh::Real detady = fe->get_detady()[qp];
     libMesh::RealTensor G( dxidx*dxidx + detadx*detadx,
                            dxidx*dxidy + detadx*detady,
                            0.0,
                            dxidy*dxidx + detady*detadx,
                            dxidy*dxidy + detady*detady,
                            0.0 );
     if( c.get_dim() == 3 )
       {
         libMesh::Real dxidz = fe->get_dxidz()[qp];
         libMesh::Real detadz = fe->get_detadz()[qp];
         libMesh::Real dzetadx = fe->get_dzetadx()[qp];
         libMesh::Real dzetady = fe->get_dzetady()[qp];
         libMesh::Real dzetadz = fe->get_dzetadz()[qp];
         G(0,0) += dzetadx*dzetadx;
         G(0,1) += dzetadx*dzetady;
         G(0,2) = dxidx*dxidz + detadx*detadz + dzetadx*dzetadz;
         G(1,0) += dzetady*dzetadx;
         G(1,1) += dzetady*dzetady;
         G(1,2) = dxidy*dxidz + detady*detadz + dzetady*dzetadz;
         G(2,0) = dxidz*dxidx + detadz*detadx + dzetadz*dzetadx;
         G(2,1) = dxidz*dxidy + detadz*detady + dzetadz*dzetady;
         G(2,2) = dxidz*dxidz + detadz*detadz + dzetadz*dzetadz;
       }
     return G;
   }
void GRINS::ParameterUser::register_parameter (const std::string & param_name, libMesh::ParameterMultiPointer< libMesh::Number > & param_pointer) const virtual inherited
Each subclass will register its copy of an independent.
Reimplemented in GRINS::AxisymmetricHeatTransfer< Conductivity >, GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::IncompressibleNavierStokesBase< Viscosity >, GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >, GRINS::HeatConduction< Conductivity >, GRINS::HeatTransferBase< Conductivity >, and GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >.
Definition at line 50 of file parameter_user.C.
Referenced by GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::register_parameter(), GRINS::HeatTransferBase< Conductivity >::register_parameter(), GRINS::HeatConduction< Conductivity >::register_parameter(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::register_parameter(), GRINS::IncompressibleNavierStokesBase< Viscosity >::register_parameter(), GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::register_parameter(), and GRINS::AxisymmetricHeatTransfer< Conductivity >::register_parameter().
   {
     std::map<std::string, libMesh::Number*>::const_iterator it =
       _my_parameters.find(param_name);
     if (it != _my_parameters.end())
       {
         std::cout << _my_name << " uses parameter " << param_name
                   << std::endl;
         param_pointer.push_back(it->second);
       }
   }
void GRINS::ParameterUser::set_parameter (libMesh::Number & param_variable, const GetPot & input, const std::string & param_name, libMesh::Number param_default) virtual inherited
Each subclass can simultaneously read a parameter value from.
Definition at line 35 of file parameter_user.C.
References GRINS::ParameterUser::_my_name, and GRINS::ParameterUser::_my_parameters.
Referenced by GRINS::AveragedFanAdjointStabilization< Viscosity >::AveragedFanAdjointStabilization(), GRINS::AveragedTurbineAdjointStabilization< Viscosity >::AveragedTurbineAdjointStabilization(), GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::BoussinesqBuoyancyAdjointStabilization(), GRINS::BoussinesqBuoyancyBase::BoussinesqBuoyancyBase(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::BoussinesqBuoyancySPGSMStabilization(), GRINS::ConstantConductivity::ConstantConductivity(), GRINS::ConstantPrandtlConductivity::ConstantPrandtlConductivity(), GRINS::ConstantSourceFunction::ConstantSourceFunction(), GRINS::ConstantSourceTerm::ConstantSourceTerm(), GRINS::ConstantSpecificHeat::ConstantSpecificHeat(), GRINS::ConstantViscosity::ConstantViscosity(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticCableConstantGravity::ElasticCableConstantGravity(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransferBase< Conductivity >::HeatTransferBase(), GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase(), GRINS::AverageNusseltNumber::init(), GRINS::MooneyRivlin::MooneyRivlin(), GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase(), GRINS::HookesLaw1D::read_input_options(), GRINS::HookesLaw::read_input_options(), GRINS::AxisymmetricBoussinesqBuoyancy::read_input_options(), and GRINS::VelocityDragAdjointStabilization< Viscosity >::VelocityDragAdjointStabilization().
   {
     param_variable = input(param_name, param_default);
     libmesh_assert_msg(!_my_parameters.count(param_name),
       "ERROR: " << _my_name << " double-registered parameter " <<
       param_name);
     _my_parameters[param_name] = &param_variable;
   }
The documentation for this class was generated from the following files:
src/physics/include/grins/stab_helper.h
src/physics/src/stab_helper.C