GRINS-0.6.0: GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity > Class Template Reference
GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity > Class Template Reference
Wrapper class for storing state for computing Wilke transport properties using Antioch.
#include <antioch_wilke_transport_mixture.h>
Public Types
typedef AntiochChemistry ChemistryParent
Public Member Functions
AntiochWilkeTransportMixture (const GetPot &input)
virtual ~AntiochWilkeTransportMixture ()
const Antioch::WilkeMixture< libMesh::Real > & wilke_mixture () const
const Viscosity & viscosity () const
const Conductivity & conductivity () const
const Diffusivity & diffusivity () const
const Antioch::ReactionSet< libMesh::Real > & reaction_set () const
const Antioch::CEAThermoMixture< libMesh::Real > & cea_mixture () const
libMesh::Real h_stat_mech_ref_correction (unsigned int species) const
libMesh::Real M (unsigned int species) const
Species molar mass (molecular weight), [kg/mol].
libMesh::Real M_mix (const std::vector< libMesh::Real > &mass_fractions) const
Mixture molar mass (molecular weight), [kg/mol].
libMesh::Real R (unsigned int species) const
Species gas constant, [J/kg-K].
libMesh::Real R_mix (const std::vector< libMesh::Real > &mass_fractions) const
Mixture gas constant, [J/kg-K].
libMesh::Real X (unsigned int species, libMesh::Real M, libMesh::Real mass_fraction) const
Species mole fraction, unitless.
void X (libMesh::Real M, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &mole_fractions) const
Mole fraction for all species, unitless.
libMesh::Real molar_density (const unsigned int species, const libMesh::Real rho, const libMesh::Real mass_fraction) const
Species molar density, [mol/m^3].
void molar_densities (const libMesh::Real rho, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &molar_densities) const
Molar density for all species, [mol/m^3].
unsigned int n_species () const
unsigned int species_index (const std::string &species_name) const
std::string species_name (unsigned int species_index) const
const Antioch::ChemicalMixture< libMesh::Real > & chemical_mixture () const
Accessor to underlying Antioch object.
const AntiochChemistry & chemistry () const
Accessor for this class.
Protected Member Functions
void build_thermo (const GetPot &input)
void build_viscosity (const GetPot &input)
void build_conductivity (const GetPot &input)
void build_diffusivity (const GetPot &input)
void build_stat_mech_ref_correction ()
Protected Attributes
Antioch::WilkeMixture< libMesh::Real > _wilke_mixture
boost::scoped_ptr< Thermo > _thermo
boost::scoped_ptr< Viscosity > _viscosity
boost::scoped_ptr< Conductivity > _conductivity
boost::scoped_ptr< Diffusivity > _diffusivity
boost::scoped_ptr< Antioch::ReactionSet< libMesh::Real > > _reaction_set
boost::scoped_ptr< Antioch::CEAThermoMixture< libMesh::Real > > _cea_mixture
std::vector< libMesh::Real > _h_stat_mech_ref_correction
boost::scoped_ptr< Antioch::ChemicalMixture< libMesh::Real > > _antioch_gas
Private Member Functions
AntiochWilkeTransportMixture ()
void specialized_build_thermo (const GetPot &, boost::scoped_ptr< Antioch::StatMechThermodynamics< libMesh::Real > > &thermo, thermo_type< Antioch::StatMechThermodynamics< libMesh::Real > >)
void specialized_build_thermo (const GetPot &, boost::scoped_ptr< Antioch::CEAEvaluator< libMesh::Real > > &thermo, thermo_type< Antioch::CEAEvaluator< libMesh::Real > >)
void specialized_build_viscosity (const GetPot &, boost::scoped_ptr< Antioch::MixtureViscosity< Antioch::SutherlandViscosity< libMesh::Real > > > &viscosity, viscosity_type< Antioch::MixtureViscosity< Antioch::SutherlandViscosity< libMesh::Real > > >)
void specialized_build_viscosity (const GetPot &, boost::scoped_ptr< Antioch::MixtureViscosity< Antioch::BlottnerViscosity< libMesh::Real > > > &viscosity, viscosity_type< Antioch::MixtureViscosity< Antioch::BlottnerViscosity< libMesh::Real > > >)
void specialized_build_conductivity (const GetPot &, boost::scoped_ptr< Antioch::EuckenThermalConductivity< Thermo > > &conductivity, conductivity_type< Antioch::EuckenThermalConductivity< Thermo > >)
void specialized_build_diffusivity (const GetPot &input, boost::scoped_ptr< Antioch::ConstantLewisDiffusivity< libMesh::Real > > &diffusivity, diffusivity_type< Antioch::ConstantLewisDiffusivity< libMesh::Real > >)
Detailed Description
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity>
class GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >
Wrapper class for storing state for computing Wilke transport properties using Antioch.
This class is expected to be constructed before threads have been forked and will live during the whole program. By default, Antioch is working in SI units. Note that this documentation will always be built regardless if Antioch is included in the GRINS build or not. Check configure output to confirm that Antioch was included in the build.
Definition at line 72 of file antioch_wilke_transport_mixture.h.
Member Typedef Documentation
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> typedef AntiochChemistry GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::ChemistryParent
Definition at line 88 of file antioch_wilke_transport_mixture.h.
Constructor & Destructor Documentation
template<typename T , typename V , typename C , typename D > GRINS::AntiochWilkeTransportMixture< T, V, C, D >::AntiochWilkeTransportMixture (const GetPot & input)
Definition at line 39 of file antioch_wilke_transport_mixture.C.
References GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::build_conductivity(), GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::build_diffusivity(), GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::build_thermo(), and GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::build_viscosity().
     : AntiochMixture(input),
       _wilke_mixture(*(this->_antioch_gas.get())),
       _thermo(NULL),
       _viscosity(NULL),
       _conductivity(NULL),
       _diffusivity(NULL)
   {
     this->build_thermo( input );
     this->build_viscosity( input );
     this->build_conductivity( input );
     this->build_diffusivity( input );
     return;
   }
template<typename T , typename V , typename C , typename D > GRINS::AntiochWilkeTransportMixture< T, V, C, D >::~AntiochWilkeTransportMixture () virtual
Definition at line 59 of file antioch_wilke_transport_mixture.C.
   {
     return;
   }
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::AntiochWilkeTransportMixture () private
Member Function Documentation
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::build_conductivity (const GetPot & input) inline protected
Definition at line 112 of file antioch_wilke_transport_mixture.h.
References GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_conductivity().
Referenced by GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::AntiochWilkeTransportMixture().
     { specialized_build_conductivity( input, _conductivity, conductivity_type<Conductivity>() ); }
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::build_diffusivity (const GetPot & input) inline protected
Definition at line 115 of file antioch_wilke_transport_mixture.h.
References GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_diffusivity().
Referenced by GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::AntiochWilkeTransportMixture().
     { specialized_build_diffusivity( input, _diffusivity, diffusivity_type<Diffusivity>() ); }
void GRINS::AntiochMixture::build_stat_mech_ref_correction () protected inherited
Definition at line 71 of file antioch_mixture.C.
References GRINS::AntiochChemistry::_antioch_gas, GRINS::AntiochMixture::_h_stat_mech_ref_correction, and GRINS::AntiochChemistry::n_species().
Referenced by GRINS::AntiochMixture::AntiochMixture().
   {
     Antioch::StatMechThermodynamics<libMesh::Real> thermo( *(this->_antioch_gas.get()) );
     _h_stat_mech_ref_correction.resize(this->n_species());
     for( unsigned int s = 0; s < this->n_species(); s++ )
       {
         _h_stat_mech_ref_correction[s] = -thermo.h_tot( s, 298.15 ) + thermo.e_0(s);
       }
     return;
   }
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::build_thermo (const GetPot & input) inline protected
Definition at line 106 of file antioch_wilke_transport_mixture.h.
References GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_thermo().
Referenced by GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::AntiochWilkeTransportMixture().
     { specialized_build_thermo( input, _thermo, thermo_type<Thermo>() ); }
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::build_viscosity (const GetPot & input) inline protected
Definition at line 109 of file antioch_wilke_transport_mixture.h.
References GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_viscosity().
Referenced by GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::AntiochWilkeTransportMixture().
     { specialized_build_viscosity( input, _viscosity, viscosity_type<Viscosity>() ); }
const Antioch::CEAThermoMixture< libMesh::Real > & GRINS::AntiochMixture::cea_mixture () const inline inherited
Definition at line 101 of file antioch_mixture.h.
References GRINS::AntiochMixture::_cea_mixture.
Referenced by GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_thermo(), and GRINS::AntiochEvaluator< Thermo >::specialized_build_thermo().
   {
     return *_cea_mixture.get();
   }
const Antioch::ChemicalMixture< libMesh::Real > & GRINS::AntiochChemistry::chemical_mixture () const inline inherited
Accessor to underlying Antioch object.
Definition at line 178 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
Referenced by GRINS::AntiochEvaluator< Thermo >::specialized_build_thermo().
   {
     return *_antioch_gas.get();
   }
const AntiochChemistry & GRINS::AntiochChemistry::chemistry () const inline inherited
Accessor for this class.
Definition at line 201 of file antioch_chemistry.h.
   {
     return *this;
   }
template<typename T , typename V , typename Conductivity , typename D > const Conductivity & GRINS::AntiochWilkeTransportMixture< T, V, Conductivity, D >::conductivity () const inline
Definition at line 204 of file antioch_wilke_transport_mixture.h.
   {
     return *_conductivity.get();
   }
template<typename T , typename V , typename C , typename Diffusivity > const Diffusivity & GRINS::AntiochWilkeTransportMixture< T, V, C, Diffusivity >::diffusivity () const inline
Definition at line 211 of file antioch_wilke_transport_mixture.h.
   {
     return *_diffusivity.get();
   }
libMesh::Real GRINS::AntiochMixture::h_stat_mech_ref_correction (unsigned int species) const inline inherited
Definition at line 107 of file antioch_mixture.h.
References GRINS::AntiochMixture::_h_stat_mech_ref_correction.
   {
     return _h_stat_mech_ref_correction[species];
   }
libMesh::Real GRINS::AntiochChemistry::M (unsigned int species) const inline inherited
Species molar mass (molecular weight), [kg/mol].
Definition at line 122 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
   {
     return _antioch_gas->M(species);
   }
libMesh::Real GRINS::AntiochChemistry::M_mix (const std::vector< libMesh::Real > & mass_fractions) const inline inherited
Mixture molar mass (molecular weight), [kg/mol].
Definition at line 128 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
Referenced by main().
   {
     return _antioch_gas->M(mass_fractions);
   }
void GRINS::AntiochChemistry::molar_densities (const libMesh::Real rho, const std::vector< libMesh::Real > & mass_fractions, std::vector< libMesh::Real > & molar_densities) const inline inherited
Molar density for all species, [mol/m^3].
Definition at line 192 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
Referenced by GRINS::AntiochKinetics::omega_dot().
   {
     _antioch_gas->molar_densities( rho, mass_fractions, molar_densities );
     return;
   }
libMesh::Real GRINS::AntiochChemistry::molar_density (const unsigned int species, const libMesh::Real rho, const libMesh::Real mass_fraction) const inline inherited
Species molar density, [mol/m^3].
Definition at line 184 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
   {
     return _antioch_gas->molar_density( species, rho, mass_fraction );
   }
unsigned int GRINS::AntiochChemistry::n_species () const inline inherited
Definition at line 162 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
Referenced by GRINS::AntiochChemistry::AntiochChemistry(), GRINS::AntiochMixture::build_stat_mech_ref_correction(), do_transport_eval(), main(), and GRINS::AntiochKinetics::omega_dot().
   {
     return _antioch_gas->n_species();
   }
libMesh::Real GRINS::AntiochChemistry::R (unsigned int species) const inline inherited
Species gas constant, [J/kg-K].
R_universal/M(species)
Definition at line 134 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
   {
     return _antioch_gas->R(species);
   }
libMesh::Real GRINS::AntiochChemistry::R_mix (const std::vector< libMesh::Real > & mass_fractions) const inline inherited
Mixture gas constant, [J/kg-K].
Definition at line 140 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
Referenced by main(), and test_evaluator().
   {
     return _antioch_gas->R(mass_fractions);
   }
const Antioch::ReactionSet< libMesh::Real > & GRINS::AntiochMixture::reaction_set () const inline inherited
Definition at line 95 of file antioch_mixture.h.
References GRINS::AntiochMixture::_reaction_set.
   {
     return *_reaction_set.get();
   }
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_conductivity (const GetPot & , boost::scoped_ptr< Antioch::EuckenThermalConductivity< Thermo > > & conductivity, conductivity_type< Antioch::EuckenThermalConductivity< Thermo > >) inline private
Definition at line 158 of file antioch_wilke_transport_mixture.h.
Referenced by GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::build_conductivity().
     {
       conductivity.reset( new Antioch::EuckenThermalConductivity<Thermo>( *_thermo.get() ) );
       return;
     }
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_diffusivity (const GetPot & input, boost::scoped_ptr< Antioch::ConstantLewisDiffusivity< libMesh::Real > > & diffusivity, diffusivity_type< Antioch::ConstantLewisDiffusivity< libMesh::Real > >) inline private
Definition at line 166 of file antioch_wilke_transport_mixture.h.
Referenced by GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::build_diffusivity().
     {
       if( !input.have_variable( "Physics/Antioch/Le" ) )
         {
           std::cerr << "Error: Must provide Lewis number for constant_lewis diffusivity model."
                     << std::endl;
           libmesh_error();
         }
       const libMesh::Real Le = input( "Physics/Antioch/Le", 0.0 );
       diffusivity.reset( new Antioch::ConstantLewisDiffusivity<libMesh::Real>( Le ) );
       return;
     }
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_thermo (const GetPot & , boost::scoped_ptr< Antioch::StatMechThermodynamics< libMesh::Real > > & thermo, thermo_type< Antioch::StatMechThermodynamics< libMesh::Real > >) inline private
Definition at line 122 of file antioch_wilke_transport_mixture.h.
References GRINS::AntiochChemistry::_antioch_gas.
Referenced by GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::build_thermo().
     {
       thermo.reset( new Antioch::StatMechThermodynamics<libMesh::Real>( *(this->_antioch_gas.get()) ) );
       return;
     }
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_thermo (const GetPot & , boost::scoped_ptr< Antioch::CEAEvaluator< libMesh::Real > > & thermo, thermo_type< Antioch::CEAEvaluator< libMesh::Real > >) inline private
Definition at line 130 of file antioch_wilke_transport_mixture.h.
References GRINS::AntiochMixture::cea_mixture().
     {
       thermo.reset( new Antioch::CEAEvaluator<libMesh::Real>( this->cea_mixture() ) );
       return;
     }
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_viscosity (const GetPot & , boost::scoped_ptr< Antioch::MixtureViscosity< Antioch::SutherlandViscosity< libMesh::Real > > > & viscosity, viscosity_type< Antioch::MixtureViscosity< Antioch::SutherlandViscosity< libMesh::Real > > >) inline private
Definition at line 138 of file antioch_wilke_transport_mixture.h.
References GRINS::AntiochChemistry::_antioch_gas.
Referenced by GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::build_viscosity().
     {
       viscosity.reset( new Antioch::MixtureViscosity<Antioch::SutherlandViscosity<libMesh::Real> >( *(this->_antioch_gas.get()) ) );
       Antioch::read_sutherland_data_ascii_default( *(viscosity.get()) );
       return;
     }
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_viscosity (const GetPot & , boost::scoped_ptr< Antioch::MixtureViscosity< Antioch::BlottnerViscosity< libMesh::Real > > > & viscosity, viscosity_type< Antioch::MixtureViscosity< Antioch::BlottnerViscosity< libMesh::Real > > >) inline private
Definition at line 148 of file antioch_wilke_transport_mixture.h.
References GRINS::AntiochChemistry::_antioch_gas.
     {
       viscosity.reset( new Antioch::MixtureViscosity<Antioch::BlottnerViscosity<libMesh::Real> >( *(this->_antioch_gas.get()) ) );
       Antioch::read_blottner_data_ascii_default( *(viscosity.get()) );
       return;
     }
unsigned int GRINS::AntiochChemistry::species_index (const std::string & species_name) const inline inherited
Definition at line 168 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
   {
 #if ANTIOCH_MAJOR_VERSION < 1 && ANTIOCH_MINOR_VERSION < 3
     return _antioch_gas->active_species_name_map().find(species_name)->second;
 #else
     return _antioch_gas->species_name_map().find(species_name)->second;
 #endif
   }
std::string GRINS::AntiochChemistry::species_name (unsigned int species_index) const inherited
Definition at line 65 of file antioch_chemistry.C.
References GRINS::AntiochChemistry::_antioch_gas.
Referenced by do_transport_eval(), main(), and test_evaluator().
   {
     libmesh_assert_less(species_index, _antioch_gas->n_species());
 #if ANTIOCH_MAJOR_VERSION < 1 && ANTIOCH_MINOR_VERSION < 3
     std::string name = "dummy";
     for( std::map<std::string,unsigned int>::const_iterator it = _antioch_gas->active_species_name_map().begin();
          it != _antioch_gas->active_species_name_map().end(); it++ )
       {
         if( it->second == species_index )
           {
             name = it->first;
           }
       }
     if( name == std::string("dummy") )
       {
         std::cerr << "Error: Could not find a species name for the given index!"
                   << std::endl;
         libmesh_error();
       }
     return name;
 #else
     return _antioch_gas->species_inverse_name_map().find(species_index)->second;
 #endif
   }
template<typename T , typename Viscosity , typename C , typename D > const Viscosity & GRINS::AntiochWilkeTransportMixture< T, Viscosity, C, D >::viscosity () const inline
Definition at line 197 of file antioch_wilke_transport_mixture.h.
   {
     return *_viscosity.get();
   }
template<typename T , typename V , typename C , typename D > const Antioch::WilkeMixture< libMesh::Real > & GRINS::AntiochWilkeTransportMixture< T, V, C, D >::wilke_mixture () const inline
Definition at line 190 of file antioch_wilke_transport_mixture.h.
   {
     return _wilke_mixture;
   }
libMesh::Real GRINS::AntiochChemistry::X (unsigned int species, libMesh::Real M, libMesh::Real mass_fraction) const inline inherited
Species mole fraction, unitless.
Definition at line 146 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
Referenced by main().
   {
     return _antioch_gas->X(species,M,mass_fraction);
   }
void GRINS::AntiochChemistry::X (libMesh::Real M, const std::vector< libMesh::Real > & mass_fractions, std::vector< libMesh::Real > & mole_fractions) const inline inherited
Mole fraction for all species, unitless.
Definition at line 153 of file antioch_chemistry.h.
References GRINS::AntiochChemistry::_antioch_gas.
   {
     _antioch_gas->X(M,mass_fractions,mole_fractions);
     return;
   }
Member Data Documentation
boost::scoped_ptr<Antioch::ChemicalMixture<libMesh::Real> > GRINS::AntiochChemistry::_antioch_gas protected inherited
Definition at line 112 of file antioch_chemistry.h.
Referenced by GRINS::AntiochChemistry::AntiochChemistry(), GRINS::AntiochMixture::build_stat_mech_ref_correction(), GRINS::AntiochChemistry::chemical_mixture(), GRINS::AntiochChemistry::M(), GRINS::AntiochChemistry::M_mix(), GRINS::AntiochChemistry::molar_densities(), GRINS::AntiochChemistry::molar_density(), GRINS::AntiochChemistry::n_species(), GRINS::AntiochChemistry::R(), GRINS::AntiochChemistry::R_mix(), GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_thermo(), GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_viscosity(), GRINS::AntiochChemistry::species_index(), GRINS::AntiochChemistry::species_name(), and GRINS::AntiochChemistry::X().
boost::scoped_ptr<Antioch::CEAThermoMixture<libMesh::Real> > GRINS::AntiochMixture::_cea_mixture protected inherited
Definition at line 81 of file antioch_mixture.h.
Referenced by GRINS::AntiochMixture::AntiochMixture(), and GRINS::AntiochMixture::cea_mixture().
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> boost::scoped_ptr<Conductivity> GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::_conductivity protected
Definition at line 98 of file antioch_wilke_transport_mixture.h.
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> boost::scoped_ptr<Diffusivity> GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::_diffusivity protected
Definition at line 100 of file antioch_wilke_transport_mixture.h.
std::vector<libMesh::Real> GRINS::AntiochMixture::_h_stat_mech_ref_correction protected inherited
Definition at line 83 of file antioch_mixture.h.
Referenced by GRINS::AntiochMixture::build_stat_mech_ref_correction(), and GRINS::AntiochMixture::h_stat_mech_ref_correction().
boost::scoped_ptr<Antioch::ReactionSet<libMesh::Real> > GRINS::AntiochMixture::_reaction_set protected inherited
Definition at line 79 of file antioch_mixture.h.
Referenced by GRINS::AntiochMixture::AntiochMixture(), and GRINS::AntiochMixture::reaction_set().
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> boost::scoped_ptr<Thermo> GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::_thermo protected
Definition at line 94 of file antioch_wilke_transport_mixture.h.
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> boost::scoped_ptr<Viscosity> GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::_viscosity protected
Definition at line 96 of file antioch_wilke_transport_mixture.h.
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> Antioch::WilkeMixture<libMesh::Real> GRINS::AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity >::_wilke_mixture protected
Definition at line 92 of file antioch_wilke_transport_mixture.h.
The documentation for this class was generated from the following files:
src/properties/include/grins/antioch_wilke_transport_mixture.h
src/properties/src/antioch_wilke_transport_mixture.C