GRINS-0.6.0: GRINS::QoIBase Class Reference
GRINS::QoIBase Class Reference abstract
#include <qoi_base.h>
Public Member Functions
QoIBase (const std::string &qoi_name)
virtual ~QoIBase ()
virtual QoIBase * clone () const =0
Clone this QoI.
virtual bool assemble_on_interior () const =0
Does the QoI need an element interior assembly loop?
virtual bool assemble_on_sides () const =0
Does the QoI need a domain boundary assembly loop?
virtual void init (const GetPot &input, const MultiphysicsSystem &system)
Method to allow QoI to cache any system information needed for QoI calculation, for example, solution variable indices.
virtual void init_context (AssemblyContext &context)
virtual void element_qoi (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi value for element interiors.
virtual void element_qoi_derivative (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi derivative with respect to the solution on element interiors.
virtual void side_qoi (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi value on the domain boundary.
virtual void side_qoi_derivative (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi derivative with respect to the solution on the domain boundary.
virtual void parallel_op (const libMesh::Parallel::Communicator &communicator, libMesh::Number &sys_qoi, libMesh::Number &local_qoi)
Call the parallel operation for this QoI and cache the value.
virtual void thread_join (libMesh::Number &qoi, const libMesh::Number &other_qoi)
Call the operation to accumulate this QoI from multiple threads.
virtual void output_qoi (std::ostream &out) const
Basic output for computed QoI's.
libMesh::Number value () const
Returns the current QoI value.
const std::string & name () const
Returns the name of this QoI.
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiPointer< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Attributes
std::string _qoi_name
libMesh::Number _qoi_value
Detailed Description
Definition at line 54 of file qoi_base.h.
Constructor & Destructor Documentation
GRINS::QoIBase::QoIBase (const std::string & qoi_name)
Definition at line 39 of file qoi_base.C.
     : ParameterUser(qoi_name),
       _qoi_name(qoi_name),
       _qoi_value(0.0)
   {
     return;
   }
GRINS::QoIBase::~QoIBase () virtual
Definition at line 47 of file qoi_base.C.
   {
     return;
   }
Member Function Documentation
virtual bool GRINS::QoIBase::assemble_on_interior () const pure virtual
Does the QoI need an element interior assembly loop?
This is pure virtual to force to user to specify.
Implemented in GRINS::ParsedInteriorQoI, GRINS::Vorticity, and GRINS::AverageNusseltNumber.
Referenced by GRINS::CompositeQoI::add_qoi().
virtual bool GRINS::QoIBase::assemble_on_sides () const pure virtual
Does the QoI need a domain boundary assembly loop?
This is pure virtual to force to user to specify.
Implemented in GRINS::ParsedInteriorQoI, GRINS::Vorticity, and GRINS::AverageNusseltNumber.
Referenced by GRINS::CompositeQoI::add_qoi().
virtual QoIBase* GRINS::QoIBase::clone () const pure virtual
Clone this QoI.
We return a raw pointer, but it is expected for the user to take ownership and delete the object when done.
Implemented in GRINS::ParsedInteriorQoI, GRINS::Vorticity, and GRINS::AverageNusseltNumber.
Referenced by GRINS::CompositeQoI::add_qoi().
void GRINS::QoIBase::element_qoi (AssemblyContext & context, const unsigned int qoi_index) virtual
Compute the qoi value for element interiors.
Override this method if your QoI is defined on element interiors
Reimplemented in GRINS::Vorticity, and GRINS::ParsedInteriorQoI.
Definition at line 63 of file qoi_base.C.
   {
     return;
   }
void GRINS::QoIBase::element_qoi_derivative (AssemblyContext & context, const unsigned int qoi_index) virtual
Compute the qoi derivative with respect to the solution on element interiors.
Override this method if your QoI is defined on element interiors
Reimplemented in GRINS::Vorticity, and GRINS::ParsedInteriorQoI.
Definition at line 69 of file qoi_base.C.
   {
     return;
   }
void GRINS::QoIBase::init (const GetPot & input, const MultiphysicsSystem & system) virtual
Method to allow QoI to cache any system information needed for QoI calculation, for example, solution variable indices.
Reimplemented in GRINS::Vorticity, GRINS::ParsedInteriorQoI, and GRINS::AverageNusseltNumber.
Definition at line 52 of file qoi_base.C.
   {
     return;
   }
void GRINS::QoIBase::init_context (AssemblyContext & context) virtual
Reimplemented in GRINS::Vorticity, GRINS::ParsedInteriorQoI, and GRINS::AverageNusseltNumber.
Definition at line 58 of file qoi_base.C.
   {
     return;
   }
const std::string & GRINS::QoIBase::name () const inline
Returns the name of this QoI.
Definition at line 143 of file qoi_base.h.
References _qoi_name.
Referenced by GRINS::SteadyVisualization::output_adjoint(), and GRINS::UnsteadyVisualization::output_adjoint().
   {
     return _qoi_name;
   }
void GRINS::QoIBase::output_qoi (std::ostream & out) const virtual
Basic output for computed QoI's.
If fancier output is desired, override this method.
Definition at line 107 of file qoi_base.C.
References _qoi_name, and _qoi_value.
   {
     out << "==========================================================" << std::endl;
     out << _qoi_name+" = "
         << std::setprecision(16)
         << std::scientific
         << _qoi_value << std::endl;
     out << "==========================================================" << std::endl;
     return;
   }
void GRINS::QoIBase::parallel_op (const libMesh::Parallel::Communicator & communicator, libMesh::Number & sys_qoi, libMesh::Number & local_qoi) virtual
Call the parallel operation for this QoI and cache the value.
By default, this is just a sum. Override if QoI is more complex.
Definition at line 87 of file qoi_base.C.
References _qoi_value.
   {
     communicator.sum(local_qoi);
     sys_qoi = local_qoi;
     _qoi_value = sys_qoi;
     return;
   }
void GRINS::ParameterUser::register_parameter (const std::string & param_name, libMesh::ParameterMultiPointer< libMesh::Number > & param_pointer) const virtual inherited
Each subclass will register its copy of an independent.
Reimplemented in GRINS::AxisymmetricHeatTransfer< Conductivity >, GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::IncompressibleNavierStokesBase< Viscosity >, GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >, GRINS::HeatConduction< Conductivity >, GRINS::HeatTransferBase< Conductivity >, and GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >.
Definition at line 50 of file parameter_user.C.
Referenced by GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::register_parameter(), GRINS::HeatTransferBase< Conductivity >::register_parameter(), GRINS::HeatConduction< Conductivity >::register_parameter(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::register_parameter(), GRINS::IncompressibleNavierStokesBase< Viscosity >::register_parameter(), GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::register_parameter(), and GRINS::AxisymmetricHeatTransfer< Conductivity >::register_parameter().
   {
     std::map<std::string, libMesh::Number*>::const_iterator it =
       _my_parameters.find(param_name);
     if (it != _my_parameters.end())
       {
         std::cout << _my_name << " uses parameter " << param_name
                   << std::endl;
         param_pointer.push_back(it->second);
       }
   }
void GRINS::ParameterUser::set_parameter (libMesh::Number & param_variable, const GetPot & input, const std::string & param_name, libMesh::Number param_default) virtual inherited
Each subclass can simultaneously read a parameter value from.
Definition at line 35 of file parameter_user.C.
References GRINS::ParameterUser::_my_name, and GRINS::ParameterUser::_my_parameters.
Referenced by GRINS::AveragedFanAdjointStabilization< Viscosity >::AveragedFanAdjointStabilization(), GRINS::AveragedTurbineAdjointStabilization< Viscosity >::AveragedTurbineAdjointStabilization(), GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::BoussinesqBuoyancyAdjointStabilization(), GRINS::BoussinesqBuoyancyBase::BoussinesqBuoyancyBase(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::BoussinesqBuoyancySPGSMStabilization(), GRINS::ConstantConductivity::ConstantConductivity(), GRINS::ConstantPrandtlConductivity::ConstantPrandtlConductivity(), GRINS::ConstantSourceFunction::ConstantSourceFunction(), GRINS::ConstantSourceTerm::ConstantSourceTerm(), GRINS::ConstantSpecificHeat::ConstantSpecificHeat(), GRINS::ConstantViscosity::ConstantViscosity(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticCableConstantGravity::ElasticCableConstantGravity(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransferBase< Conductivity >::HeatTransferBase(), GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase(), GRINS::AverageNusseltNumber::init(), GRINS::MooneyRivlin::MooneyRivlin(), GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase(), GRINS::HookesLaw1D::read_input_options(), GRINS::HookesLaw::read_input_options(), GRINS::AxisymmetricBoussinesqBuoyancy::read_input_options(), and GRINS::VelocityDragAdjointStabilization< Viscosity >::VelocityDragAdjointStabilization().
   {
     param_variable = input(param_name, param_default);
     libmesh_assert_msg(!_my_parameters.count(param_name),
       "ERROR: " << _my_name << " double-registered parameter " <<
       param_name);
     _my_parameters[param_name] = &param_variable;
   }
void GRINS::QoIBase::side_qoi (AssemblyContext & context, const unsigned int qoi_index) virtual
Compute the qoi value on the domain boundary.
Override this method if your QoI is defined on the domain boundary
Reimplemented in GRINS::AverageNusseltNumber.
Definition at line 75 of file qoi_base.C.
   {
     return;
   }
void GRINS::QoIBase::side_qoi_derivative (AssemblyContext & context, const unsigned int qoi_index) virtual
Compute the qoi derivative with respect to the solution on the domain boundary.
Override this method if your QoI is defined on the domain boundary
Reimplemented in GRINS::AverageNusseltNumber.
Definition at line 81 of file qoi_base.C.
   {
     return;
   }
void GRINS::QoIBase::thread_join (libMesh::Number & qoi, const libMesh::Number & other_qoi) virtual
Call the operation to accumulate this QoI from multiple threads.
By default, this is just a sum. Override if QoI is more complex.
Definition at line 100 of file qoi_base.C.
   {
     qoi += other_qoi;
     return;
   }
libMesh::Number GRINS::QoIBase::value () const inline
Returns the current QoI value.
Definition at line 137 of file qoi_base.h.
References _qoi_value.
   {
     return _qoi_value;
   }
Member Data Documentation
std::string GRINS::QoIBase::_qoi_name protected
Definition at line 131 of file qoi_base.h.
Referenced by name(), and output_qoi().
libMesh::Number GRINS::QoIBase::_qoi_value protected
Definition at line 133 of file qoi_base.h.
Referenced by output_qoi(), parallel_op(), and value().
The documentation for this class was generated from the following files:
src/qoi/include/grins/qoi_base.h
src/qoi/src/qoi_base.C