GRINS-0.6.0: ParabolicBCFactory Class Reference
ParabolicBCFactory Class Reference
Public Member Functions
ParabolicBCFactory ()
~ParabolicBCFactory ()
std::multimap< GRINS::PhysicsName, GRINS::DBCContainer > build_dirichlet ()
Builds all required libMesh::DirichletBoundary objects and adds them to DofMap.
ParabolicBCFactory ()
~ParabolicBCFactory ()
std::multimap< GRINS::PhysicsName, GRINS::DBCContainer > build_dirichlet ()
Builds all required libMesh::DirichletBoundary objects and adds them to DofMap.
ParabolicBCFactory ()
~ParabolicBCFactory ()
std::multimap< GRINS::PhysicsName, GRINS::DBCContainer > build_dirichlet ()
Builds all required libMesh::DirichletBoundary objects and adds them to DofMap.
ParabolicBCFactory ()
~ParabolicBCFactory ()
std::multimap< GRINS::PhysicsName, GRINS::DBCContainer > build_dirichlet ()
Builds all required libMesh::DirichletBoundary objects and adds them to DofMap.
virtual std::map< GRINS::PhysicsName, GRINS::NBCContainer > build_neumann (libMesh::EquationSystems &equation_system)
Builds all Neumann boundary condition function objects needed.
Detailed Description
Definition at line 57 of file test_ns_poiseuille_flow.C.
Constructor & Destructor Documentation
ParabolicBCFactory::ParabolicBCFactory () inline
Definition at line 61 of file test_ns_poiseuille_flow.C.
     : GRINS::BoundaryConditionsFactory()
   { return; };
ParabolicBCFactory::~ParabolicBCFactory () inline
Definition at line 65 of file test_ns_poiseuille_flow.C.
 {return;};
ParabolicBCFactory::ParabolicBCFactory () inline
Definition at line 60 of file test_stokes_poiseuille_flow.C.
     : GRINS::BoundaryConditionsFactory()
   { return; };
ParabolicBCFactory::~ParabolicBCFactory () inline
Definition at line 64 of file test_stokes_poiseuille_flow.C.
 {return;};
ParabolicBCFactory::ParabolicBCFactory () inline
Definition at line 60 of file test_stokes_poiseuille_flow_parsed_viscosity.C.
     : GRINS::BoundaryConditionsFactory()
   { return; };
ParabolicBCFactory::~ParabolicBCFactory () inline
Definition at line 64 of file test_stokes_poiseuille_flow_parsed_viscosity.C.
 {return;};
ParabolicBCFactory::ParabolicBCFactory () inline
Definition at line 60 of file test_stokes_poiseuille_flow_parsed_viscosity_parsed_conductivity.C.
     : GRINS::BoundaryConditionsFactory()
   { return; };
ParabolicBCFactory::~ParabolicBCFactory () inline
Definition at line 64 of file test_stokes_poiseuille_flow_parsed_viscosity_parsed_conductivity.C.
 {return;};
Member Function Documentation
std::multimap< GRINS::PhysicsName, GRINS::DBCContainer > ParabolicBCFactory::build_dirichlet () virtual
Builds all required libMesh::DirichletBoundary objects and adds them to DofMap.
This needs to be done for all the physics in the simulation, for all "special" dirichlet boundary conditions.
Reimplemented from GRINS::BoundaryConditionsFactory.
std::multimap< GRINS::PhysicsName, GRINS::DBCContainer > ParabolicBCFactory::build_dirichlet () virtual
Builds all required libMesh::DirichletBoundary objects and adds them to DofMap.
This needs to be done for all the physics in the simulation, for all "special" dirichlet boundary conditions.
Reimplemented from GRINS::BoundaryConditionsFactory.
std::multimap< GRINS::PhysicsName, GRINS::DBCContainer > ParabolicBCFactory::build_dirichlet () virtual
Builds all required libMesh::DirichletBoundary objects and adds them to DofMap.
This needs to be done for all the physics in the simulation, for all "special" dirichlet boundary conditions.
Reimplemented from GRINS::BoundaryConditionsFactory.
std::multimap< GRINS::PhysicsName, GRINS::DBCContainer > ParabolicBCFactory::build_dirichlet () virtual
Builds all required libMesh::DirichletBoundary objects and adds them to DofMap.
This needs to be done for all the physics in the simulation, for all "special" dirichlet boundary conditions.
Reimplemented from GRINS::BoundaryConditionsFactory.
Definition at line 163 of file test_ns_poiseuille_flow.C.
References GRINS::DBCContainer::add_bc_id(), GRINS::DBCContainer::add_var_name(), GRINS::incompressible_navier_stokes, and GRINS::DBCContainer::set_func().
 {
   GRINS::DBCContainer cont;
   cont.add_var_name( "u" );
   cont.add_bc_id( 1 );
   cont.add_bc_id( 3 );
   std::tr1::shared_ptr<libMesh::FunctionBase<libMesh::Number> > u_func( new GRINS::ParabolicProfile );
   cont.set_func( u_func );
   std::multimap< GRINS::PhysicsName, GRINS::DBCContainer > mymap;
   mymap.insert( std::pair<GRINS::PhysicsName, GRINS::DBCContainer >(GRINS::incompressible_navier_stokes,  cont) );
   return mymap;
 }
std::map< PhysicsName, NBCContainer > GRINS::BoundaryConditionsFactory::build_neumann (libMesh::EquationSystems & equation_system) virtual inherited
Builds all Neumann boundary condition function objects needed.
This is done for each physics. Thus, the container returned maps between each physics and set of Neumann boundary conditions for that physics.
Reimplemented in GRINS::ThermallyDrivenFlowTestBCFactory.
Definition at line 47 of file bc_factory.C.
   {
     return std::map< PhysicsName, NBCContainer >();
   }
The documentation for this class was generated from the following files:
test/test_ns_poiseuille_flow.C
test/test_stokes_poiseuille_flow.C
test/test_stokes_poiseuille_flow_parsed_viscosity.C
test/test_stokes_poiseuille_flow_parsed_viscosity_parsed_conductivity.C