GRINS-0.6.0: test/test_axi_ns_con_cyl_flow.C File Reference
test_axi_ns_con_cyl_flow.C File Reference
#include "grins_config.h"
#include <iostream>
#include "grins/mesh_builder.h"
#include "grins/simulation.h"
#include "grins/simulation_builder.h"
#include "grins/multiphysics_sys.h"
#include "grins/concentric_cylinder_profile.h"
#include "libmesh/exact_solution.h"
#include "libmesh/zero_function.h"
Classes
class AxiConCylBCFactory
Functions
libMesh::Number exact_solution (const libMesh::Point &p, const libMesh::Parameters &, const std::string &, const std::string &)
libMesh::Gradient exact_derivative (const libMesh::Point &p, const libMesh::Parameters &, const std::string &, const std::string &)
int main (int argc, char *argv[])
Function Documentation
libMesh::Gradient exact_derivative (const libMesh::Point & p, const libMesh::Parameters & , const std::string & sys, const std::string & var)
Definition at line 222 of file test_axi_ns_con_cyl_flow.C.
Referenced by main().
 {
   const double r = p(0);
   const double r0 = 1.0;
   const double r1 = 2.0;
   const double u0 = 2.0;
   libMesh::Gradient g;
   // Hardcoded to velocity in input file.
   if( var == "z_vel" )
     {
       g(0) = -u0/std::log(r1/r0)*r/r1*r1/(r*r);
       g(1) = 0.0;
     }
   return g;
 }
libMesh::Number exact_solution (const libMesh::Point & p, const libMesh::Parameters & , const std::string & sys, const std::string & var)
Definition at line 202 of file test_axi_ns_con_cyl_flow.C.
Referenced by main().
 {
   const double r = p(0);
   const double r0 = 1.0;
   const double r1 = 2.0;
   const double u0 = 2.0;
   libMesh::Number f = 0;
   // Hardcoded to velocity in input file.
   if( var == "z_vel" ) f = u0*std::log( r1/r )/std::log( r1/r0 );
   else libmesh_assert(false);
   return f;
 }
int main (int argc, char * argv[])
Definition at line 71 of file test_axi_ns_con_cyl_flow.C.
References GRINS::SimulationBuilder::attach_bc_factory(), exact_derivative(), exact_solution(), and GRINS::Simulation::run().
 {
 #ifdef GRINS_USE_GRVY_TIMERS
   GRVY::GRVY_Timer_Class grvy_timer;
   grvy_timer.Init("GRINS Timer");
 #endif
   // Check command line count.
   if( argc < 2 )
     {
       // TODO: Need more consistent error handling.
       std::cerr << "Error: Must specify libMesh input file." << std::endl;
       exit(1); // TODO: something more sophisticated for parallel runs?
     }
   // libMesh input file should be first argument
   std::string libMesh_input_filename = argv[1];
   // Create our GetPot object.
   GetPot libMesh_inputfile( libMesh_input_filename );
 #ifdef GRINS_USE_GRVY_TIMERS
   grvy_timer.BeginTimer("Initialize Solver");
 #endif
   // Initialize libMesh library.
   libMesh::LibMeshInit libmesh_init(argc, argv);
   // This is a tough problem to get to converge without PETSc
   libmesh_example_requires
     (libMesh::default_solver_package() != libMesh::LASPACK_SOLVERS,
      "--enable-petsc");
   GRINS::SimulationBuilder sim_builder;
   std::tr1::shared_ptr<AxiConCylBCFactory> bc_factory( new AxiConCylBCFactory );
   sim_builder.attach_bc_factory(bc_factory);
   GRINS::Simulation grins( libMesh_inputfile,
                            sim_builder,
                            libmesh_init.comm() );
 #ifdef GRINS_USE_GRVY_TIMERS
   grvy_timer.EndTimer("Initialize Solver");
   // Attach GRVY timer to solver
   grins.attach_grvy_timer( &grvy_timer );
 #endif
   // Do solve here
   grins.run();
   // Get equation systems to create ExactSolution object
   std::tr1::shared_ptr<libMesh::EquationSystems> es = grins.get_equation_system();
   // Create Exact solution object and attach exact solution quantities
   libMesh::ExactSolution exact_sol(*es);
   exact_sol.attach_exact_value(&exact_solution);
   exact_sol.attach_exact_deriv(&exact_derivative);
   // Compute error and get it in various norms
   exact_sol.compute_error("GRINS", "z_vel");
   double l2error = exact_sol.l2_error("GRINS", "z_vel");
   double h1error = exact_sol.h1_error("GRINS", "z_vel");
   int return_flag = 0;
   if( l2error > 2.0e-9 || h1error > 4.0e-7 )
     {
       return_flag = 1;
       std::cout << "Tolerance exceeded for velocity in Poiseuille test." << std::endl
                 << "l2 error = " << l2error << std::endl
                 << "h1 error = " << h1error << std::endl;
     }
   /*
   // Compute error and get it in various norms
   exact_sol.compute_error("GRINS", "p");
   l2error = exact_sol.l2_error("GRINS", "p");
   h1error = exact_sol.h1_error("GRINS", "p");
   if( l2error > 1.0e-11 || h1error > 1.0e-11 )
     {
       return_flag = 1;
       std::cout << "Tolerance exceeded for pressure in Poiseuille test." << std::endl
                 << "l2 error = " << l2error << std::endl
                 << "h1 error = " << h1error << std::endl;
     }
   */
   return return_flag;
 }