GRINS-0.7.0: GRINS::PhysicsNaming Class Reference
GRINS::PhysicsNaming Class Reference
#include <physics_naming.h>
Static Public Member Functions
static void set_suffix (const std::string &suff)
static void clear_suffix ()
static void extract_physics_and_suffix (const std::string &full_name, std::string &physics_name, std::string &suffix)
Extract the physics name and the suffix from the full_name.
static std::string extract_physics (const std::string &full_name)
Extract the physics name from the full_name.
static std::string extract_suffix (const std::string &full_name)
Extract the suffix from the full_name.
static PhysicsName stokes ()
static PhysicsName incompressible_navier_stokes ()
static PhysicsName incompressible_navier_stokes_adjoint_stab ()
static PhysicsName incompressible_navier_stokes_spgsm_stab ()
static PhysicsName velocity_drag ()
static PhysicsName velocity_drag_adjoint_stab ()
static PhysicsName velocity_penalty ()
static PhysicsName velocity_penalty2 ()
static PhysicsName velocity_penalty3 ()
static PhysicsName velocity_penalty_adjoint_stab ()
static PhysicsName velocity_penalty2_adjoint_stab ()
static PhysicsName velocity_penalty3_adjoint_stab ()
static PhysicsName parsed_velocity_source ()
static PhysicsName parsed_velocity_source_adjoint_stab ()
static PhysicsName averaged_fan ()
static PhysicsName averaged_fan_adjoint_stab ()
static PhysicsName averaged_turbine ()
static PhysicsName spalart_allmaras ()
static PhysicsName spalart_allmaras_spgsm_stab ()
static PhysicsName scalar_ode ()
static PhysicsName heat_conduction ()
static PhysicsName heat_transfer ()
static PhysicsName heat_transfer_adjoint_stab ()
static PhysicsName heat_transfer_spgsm_stab ()
static PhysicsName axisymmetric_heat_transfer ()
static PhysicsName boussinesq_buoyancy ()
static PhysicsName boussinesq_buoyancy_adjoint_stab ()
static PhysicsName boussinesq_buoyancy_spgsm_stab ()
static PhysicsName axisymmetric_boussinesq_buoyancy ()
static PhysicsName low_mach_navier_stokes ()
static PhysicsName low_mach_navier_stokes_braack_stab ()
static PhysicsName low_mach_navier_stokes_spgsm_stab ()
static PhysicsName low_mach_navier_stokes_vms_stab ()
static PhysicsName reacting_low_mach_navier_stokes ()
static PhysicsName elastic_membrane ()
static PhysicsName elastic_cable ()
static PhysicsName elastic_cable_rayleigh_damping ()
static PhysicsName elastic_membrane_rayleigh_damping ()
static PhysicsName elastic_membrane_constant_pressure ()
static PhysicsName elastic_cable_constant_gravity ()
static PhysicsName constant_source_term ()
static PhysicsName parsed_source_term ()
static PhysicsName convection_diffusion ()
Static Private Member Functions
static std::string physics_name_delimiter ()
static std::string & suffix ()
Detailed Description
Definition at line 35 of file physics_naming.h.
Member Function Documentation
static PhysicsName GRINS::PhysicsNaming::averaged_fan () inline static
Definition at line 104 of file physics_naming.h.
References suffix().
Referenced by GRINS::AveragedFanBase< Viscosity >::read_input_options().
     { return "AveragedFan"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::averaged_fan_adjoint_stab () inline static
Definition at line 107 of file physics_naming.h.
References suffix().
     { return "AveragedFanAdjointStabilization"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::averaged_turbine () inline static
Definition at line 110 of file physics_naming.h.
References suffix().
Referenced by GRINS::AveragedTurbineBase< Viscosity >::read_input_options().
     { return "AveragedTurbine"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::axisymmetric_boussinesq_buoyancy () inline static
Definition at line 146 of file physics_naming.h.
References suffix().
Referenced by GRINS::AxisymmetricBoussinesqBuoyancy::read_input_options().
     { return "AxisymmetricBoussinesqBuoyancy"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::axisymmetric_heat_transfer () inline static
Definition at line 134 of file physics_naming.h.
References suffix().
Referenced by GRINS::OldStyleBCBuilder::build_basic_physics(), GRINS::OldStyleBCBuilder::determine_variable_group(), and GRINS::AxisymmetricHeatTransfer< Conductivity >::read_input_options().
     { return "AxisymmetricHeatTransfer"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::boussinesq_buoyancy () inline static
Definition at line 137 of file physics_naming.h.
References suffix().
Referenced by GRINS::BoussinesqBuoyancyBase::BoussinesqBuoyancyBase(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::BoussinesqBuoyancySPGSMStabilization(), GRINS::BoussinesqBuoyancyBase::no_input_warning(), and GRINS::BoussinesqBuoyancyBase::read_property().
     { return "BoussinesqBuoyancy"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::boussinesq_buoyancy_adjoint_stab () inline static
Definition at line 140 of file physics_naming.h.
References suffix().
     { return "BoussinesqBuoyancyAdjointStabilization"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::boussinesq_buoyancy_spgsm_stab () inline static
Definition at line 143 of file physics_naming.h.
References suffix().
     { return "BoussinesqBuoyancySPGSMStabilization"+suffix(); }
static void GRINS::PhysicsNaming::clear_suffix () inline static
Definition at line 42 of file physics_naming.h.
References suffix().
Referenced by GRINS::PhysicsBuilder::build_physics_map().
     { PhysicsNaming::suffix().clear(); }
static PhysicsName GRINS::PhysicsNaming::constant_source_term () inline static
Definition at line 182 of file physics_naming.h.
References suffix().
     { return "ConstantSourceTerm"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::convection_diffusion () inline static
Definition at line 188 of file physics_naming.h.
References suffix().
Referenced by GRINS::OldStyleBCBuilder::build_basic_physics(), and GRINS::OldStyleBCBuilder::determine_variable_group().
     { return "ConvectionDiffusion"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::elastic_cable () inline static
Definition at line 167 of file physics_naming.h.
References suffix().
Referenced by GRINS::OldStyleBCBuilder::build_basic_physics(), GRINS::OldStyleBCBuilder::determine_variable_group(), GRINS::ElasticCableAbstract::ElasticCableAbstract(), GRINS::ElasticCableRayleighDamping< StressStrainLaw >::ElasticCableRayleighDamping(), and GRINS::ElasticCable< StressStrainLaw >::register_postprocessing_vars().
     { return "ElasticCable"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::elastic_cable_constant_gravity () inline static
Definition at line 179 of file physics_naming.h.
References suffix().
     { return "ElasticCableConstantGravity"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::elastic_cable_rayleigh_damping () inline static
Definition at line 170 of file physics_naming.h.
References suffix().
Referenced by GRINS::ElasticCableRayleighDamping< StressStrainLaw >::ElasticCableRayleighDamping().
     { return "ElasticCableRayleighDamping"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::elastic_membrane () inline static
Definition at line 164 of file physics_naming.h.
References suffix().
Referenced by GRINS::OldStyleBCBuilder::build_basic_physics(), GRINS::OldStyleBCBuilder::determine_variable_group(), GRINS::ElasticMembraneBase< StressStrainLaw >::ElasticMembraneBase(), GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure(), GRINS::ElasticMembraneRayleighDamping< StressStrainLaw >::ElasticMembraneRayleighDamping(), and GRINS::ElasticMembrane< StressStrainLaw >::register_postprocessing_vars().
     { return "ElasticMembrane"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::elastic_membrane_constant_pressure () inline static
Definition at line 176 of file physics_naming.h.
References suffix().
Referenced by GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure().
     { return "ElasticMembraneConstantPressure"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::elastic_membrane_rayleigh_damping () inline static
Definition at line 173 of file physics_naming.h.
References suffix().
Referenced by GRINS::ElasticMembraneRayleighDamping< StressStrainLaw >::ElasticMembraneRayleighDamping().
     { return "ElasticMembraneRayleighDamping"+suffix(); }
std::string GRINS::PhysicsNaming::extract_physics (const std::string & full_name) static
Extract the physics name from the full_name.
If the delimiter is not present in the full_name, then the physics_name is the full_name.
Definition at line 39 of file physics_naming.C.
References physics_name_delimiter().
Referenced by GRINS::OldStyleBCBuilder::build_bcs(), GRINS::PhysicsBuilder::build_physics_map(), extract_physics_and_suffix(), and GRINS::PhysicsFactoryWithCore::find_core_physics_name().
   {
     // We look for this delimiter to separate the physics name from
     // the user-supplied suffix
     std::string delimiter = PhysicsNaming::physics_name_delimiter();
     std::size_t idx = full_name.find_first_of( delimiter );
     std::string physics_name;
     // If this delimiter is not found, then the full_name is the physics_name
     if( idx == full_name.npos )
         physics_name = full_name;
     // If it is found, the first part is the physics_name
     // and the second part is the suffix
     else
         physics_name = full_name.substr(0,idx);
     return physics_name;
   }
void GRINS::PhysicsNaming::extract_physics_and_suffix (const std::string & full_name, std::string & physics_name, std::string & suffix) static
Extract the physics name and the suffix from the full_name.
Note returned suffix includes the delimiter
Definition at line 31 of file physics_naming.C.
References extract_physics(), and extract_suffix().
   {
     physics_name = PhysicsNaming::extract_physics(full_name);
     suffix = PhysicsNaming::extract_suffix(full_name);
   }
std::string GRINS::PhysicsNaming::extract_suffix (const std::string & full_name) static
Extract the suffix from the full_name.
Note returned suffix includes the delimiter. If there is no delimiter present, then the returned suffix is an empty string.
Definition at line 61 of file physics_naming.C.
References physics_name_delimiter(), and suffix().
Referenced by GRINS::PhysicsBuilder::build_physics_map(), extract_physics_and_suffix(), and GRINS::PhysicsFactoryWithCore::find_core_physics_name().
   {
     // We look for this delimiter to separate the physics name from
     // the user-supplied suffix
     std::string delimiter = PhysicsNaming::physics_name_delimiter();
     std::size_t idx = full_name.find_first_of( delimiter );
     std::string suffix;
     // If this delimiter is not found, then there's no suffix
     // So no need to do anything in that case.
     // If it is found, the first part is the physics_name
     // and the second part is the suffix.
     // Note the suffix extraction *includes* the delimiter
     if( idx != full_name.npos )
         suffix = full_name.substr(idx,full_name.npos);
     return suffix;
   }
static PhysicsName GRINS::PhysicsNaming::heat_conduction () inline static
Definition at line 122 of file physics_naming.h.
References suffix().
Referenced by GRINS::OldStyleBCBuilder::build_basic_physics(), GRINS::OldStyleBCBuilder::determine_variable_group(), and GRINS::HeatConduction< Conductivity >::HeatConduction().
     { return "HeatConduction"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::heat_transfer () inline static
Definition at line 125 of file physics_naming.h.
References suffix().
Referenced by GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::BoussinesqBuoyancySPGSMStabilization(), GRINS::OldStyleBCBuilder::build_basic_physics(), GRINS::QoIFactory::check_qoi_physics_consistency(), GRINS::OldStyleBCBuilder::determine_variable_group(), GRINS::PhysicsFactoryHelper::parse_conductivity_model(), GRINS::MaterialsParsing::read_specific_heat(), and GRINS::HeatTransfer< Conductivity >::register_postprocessing_vars().
     { return "HeatTransfer"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::heat_transfer_adjoint_stab () inline static
Definition at line 128 of file physics_naming.h.
References suffix().
     { return "HeatTransferAdjointStabilization"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::heat_transfer_spgsm_stab () inline static
Definition at line 131 of file physics_naming.h.
References suffix().
     { return "HeatTransferSPGSMStabilization"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::incompressible_navier_stokes () inline static
Definition at line 65 of file physics_naming.h.
References suffix().
Referenced by GRINS::OldStyleBCBuilder::build_basic_physics(), GRINS::ConstantConductivity::ConstantConductivity(), GRINS::ConstantViscosity::ConstantViscosity(), GRINS::PhysicsFactoryHelper::deprecated_visc_model_parsing(), GRINS::OldStyleBCBuilder::determine_variable_group(), GRINS::IncompressibleNavierStokes< Viscosity >::IncompressibleNavierStokes(), GRINS::PhysicsFactoryHelper::parse_turb_viscosity_model(), GRINS::PhysicsFactoryHelper::parse_viscosity_model(), GRINS::MaterialsParsing::read_density(), GRINS::IncompressibleNavierStokes< Viscosity >::register_postprocessing_vars(), and GRINS::TurbulenceModelsBase< Viscosity >::TurbulenceModelsBase().
     { return "IncompressibleNavierStokes"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::incompressible_navier_stokes_adjoint_stab () inline static
Definition at line 68 of file physics_naming.h.
References suffix().
     { return  "IncompressibleNavierStokesAdjointStabilization"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::incompressible_navier_stokes_spgsm_stab () inline static
Definition at line 71 of file physics_naming.h.
References suffix().
     { return "IncompressibleNavierStokesSPGSMStabilization"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::low_mach_navier_stokes () inline static
Definition at line 149 of file physics_naming.h.
References suffix().
Referenced by GRINS::OldStyleBCBuilder::build_vel_and_temp_physics(), GRINS::QoIFactory::check_qoi_physics_consistency(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokes(), GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokesBase(), GRINS::PhysicsFactoryHelper::parse_specific_heat_model(), GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::read_input_options(), and GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::register_postprocessing_vars().
     { return "LowMachNavierStokes"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::low_mach_navier_stokes_braack_stab () inline static
Definition at line 152 of file physics_naming.h.
References suffix().
     { return "LowMachNavierStokesBraackStabilization"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::low_mach_navier_stokes_spgsm_stab () inline static
Definition at line 155 of file physics_naming.h.
References suffix().
     { return "LowMachNavierStokesSPGSMStabilization"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::low_mach_navier_stokes_vms_stab () inline static
Definition at line 158 of file physics_naming.h.
References suffix().
     { return "LowMachNavierStokesVMSStabilization"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::parsed_source_term () inline static
Definition at line 185 of file physics_naming.h.
References suffix().
     { return "ParsedSourceTerm"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::parsed_velocity_source () inline static
Definition at line 98 of file physics_naming.h.
References suffix().
     { return "ParsedVelocitySource"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::parsed_velocity_source_adjoint_stab () inline static
Definition at line 101 of file physics_naming.h.
References suffix().
     { return "ParsedVelocitySourceAdjointStabilization"+suffix(); }
static std::string GRINS::PhysicsNaming::physics_name_delimiter () inline static private
Definition at line 193 of file physics_naming.h.
Referenced by extract_physics(), and extract_suffix().
     { return ":"; }
static PhysicsName GRINS::PhysicsNaming::reacting_low_mach_navier_stokes () inline static
Definition at line 161 of file physics_naming.h.
References suffix().
Referenced by GRINS::PrescribedMoleFractionsDirichletOldStyleBCFactory::add_funcs(), GRINS::OldStyleBCBuilder::build_reacting_physics(), do_transport_eval(), main(), GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType >::parse_thermo_pressure(), GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType >::parse_thermochem_model(), GRINS::PhysicsFactoryHelper::parse_thermochemistry_model(), GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::ReactingLowMachNavierStokes(), GRINS::ReactingLowMachNavierStokesAbstract::ReactingLowMachNavierStokesAbstract(), GRINS::ReactingLowMachNavierStokesAbstract::read_input_options(), and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::register_postprocessing_vars().
     { return "ReactingLowMachNavierStokes"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::scalar_ode () inline static
Definition at line 119 of file physics_naming.h.
References suffix().
Referenced by GRINS::ScalarODE::read_input_options(), and GRINS::ScalarODE::set_time_evolving_vars().
     { return "ScalarODE"+suffix(); }
static void GRINS::PhysicsNaming::set_suffix (const std::string & suff) inline static
Definition at line 39 of file physics_naming.h.
References suffix().
Referenced by GRINS::PhysicsBuilder::build_physics_map().
     { PhysicsNaming::suffix() = suff; }
static PhysicsName GRINS::PhysicsNaming::spalart_allmaras () inline static
Definition at line 113 of file physics_naming.h.
References suffix().
Referenced by GRINS::OldStyleBCBuilder::build_basic_physics(), GRINS::OldStyleBCBuilder::determine_variable_group(), GRINS::SpalartAllmaras< Viscosity >::SpalartAllmaras(), and GRINS::SpalartAllmarasParameters::SpalartAllmarasParameters().
     { return "SpalartAllmaras"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::spalart_allmaras_spgsm_stab () inline static
Definition at line 116 of file physics_naming.h.
References suffix().
     { return "SpalartAllmarasSPGSMStabilization"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::stokes () inline static
Definition at line 62 of file physics_naming.h.
References suffix().
Referenced by GRINS::OldStyleBCBuilder::build_basic_physics(), and GRINS::OldStyleBCBuilder::determine_variable_group().
     { return "Stokes"+suffix(); }
static std::string& GRINS::PhysicsNaming::suffix () inline static private
Definition at line 196 of file physics_naming.h.
Referenced by averaged_fan(), averaged_fan_adjoint_stab(), averaged_turbine(), axisymmetric_boussinesq_buoyancy(), axisymmetric_heat_transfer(), boussinesq_buoyancy(), boussinesq_buoyancy_adjoint_stab(), boussinesq_buoyancy_spgsm_stab(), clear_suffix(), constant_source_term(), convection_diffusion(), elastic_cable(), elastic_cable_constant_gravity(), elastic_cable_rayleigh_damping(), elastic_membrane(), elastic_membrane_constant_pressure(), elastic_membrane_rayleigh_damping(), extract_suffix(), heat_conduction(), heat_transfer(), heat_transfer_adjoint_stab(), heat_transfer_spgsm_stab(), incompressible_navier_stokes(), incompressible_navier_stokes_adjoint_stab(), incompressible_navier_stokes_spgsm_stab(), low_mach_navier_stokes(), low_mach_navier_stokes_braack_stab(), low_mach_navier_stokes_spgsm_stab(), low_mach_navier_stokes_vms_stab(), parsed_source_term(), parsed_velocity_source(), parsed_velocity_source_adjoint_stab(), reacting_low_mach_navier_stokes(), scalar_ode(), set_suffix(), spalart_allmaras(), spalart_allmaras_spgsm_stab(), stokes(), velocity_drag(), velocity_drag_adjoint_stab(), velocity_penalty(), velocity_penalty2(), velocity_penalty2_adjoint_stab(), velocity_penalty3(), velocity_penalty3_adjoint_stab(), and velocity_penalty_adjoint_stab().
     {
       static std::string _suffix;
       return _suffix;
     };
static PhysicsName GRINS::PhysicsNaming::velocity_drag () inline static
Definition at line 74 of file physics_naming.h.
References suffix().
Referenced by GRINS::VelocityDragBase< Viscosity >::read_input_options().
     { return "VelocityDrag"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::velocity_drag_adjoint_stab () inline static
Definition at line 77 of file physics_naming.h.
References suffix().
     { return "VelocityDragAdjointStabilization"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::velocity_penalty () inline static
Definition at line 80 of file physics_naming.h.
References suffix().
     { return "VelocityPenalty"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::velocity_penalty2 () inline static
Definition at line 83 of file physics_naming.h.
References suffix().
Referenced by GRINS::VelocityPenaltyBase< Viscosity >::VelocityPenaltyBase().
     { return "VelocityPenalty2"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::velocity_penalty2_adjoint_stab () inline static
Definition at line 92 of file physics_naming.h.
References suffix().
Referenced by GRINS::VelocityPenaltyBase< Viscosity >::VelocityPenaltyBase().
     { return "VelocityPenalty2AdjointStabilization"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::velocity_penalty3 () inline static
Definition at line 86 of file physics_naming.h.
References suffix().
Referenced by GRINS::VelocityPenaltyBase< Viscosity >::VelocityPenaltyBase().
     { return "VelocityPenalty3"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::velocity_penalty3_adjoint_stab () inline static
Definition at line 95 of file physics_naming.h.
References suffix().
Referenced by GRINS::VelocityPenaltyBase< Viscosity >::VelocityPenaltyBase().
     { return "VelocityPenalty3AdjointStabilization"+suffix(); }
static PhysicsName GRINS::PhysicsNaming::velocity_penalty_adjoint_stab () inline static
Definition at line 89 of file physics_naming.h.
References suffix().
     { return "VelocityPenaltyAdjointStabilization"+suffix(); }
The documentation for this class was generated from the following files:
src/physics/include/grins/physics_naming.h
src/physics/src/physics_naming.C