GRINS-0.7.0: GRINS::TurbulenceModelsBase< Viscosity > Class Template Reference
GRINS::TurbulenceModelsBase< Viscosity > Class Template Reference
Physics class for Turbulence Models.
#include <turbulence_models_base.h>
Public Member Functions
TurbulenceModelsBase (const std::string &physics_name, const GetPot &input)
virtual void init_variables (libMesh::FEMSystem *system)
Initialize variables for this physics.
~TurbulenceModelsBase ()
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Public Member Functions inherited from GRINS::Physics
Physics (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~Physics ()
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Set which variables are time evolving.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for element interiors.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void damping_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Damping matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_damping_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
ICHandlingBase * get_ic_handler ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
Protected Attributes
unsigned int _dim
Physical dimension of problem.
libMesh::Number _rho
Material parameters, read from input.
Viscosity _mu
Viscosity object.
Protected Attributes inherited from GRINS::Physics
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
Private Member Functions
TurbulenceModelsBase ()
Additional Inherited Members
Static Public Member Functions inherited from GRINS::Physics
static void set_is_axisymmetric (bool is_axisymmetric)
Set whether we should treat the problem as axisymmetric.
static bool is_axisymmetric ()
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Member Functions inherited from GRINS::Physics
libMesh::UniquePtr< libMesh::FEGenericBase< libMesh::Real > > build_new_fe (const libMesh::Elem *elem, const libMesh::FEGenericBase< libMesh::Real > *fe, const libMesh::Point p)
void parse_enabled_subdomains (const GetPot &input, const std::string &physics_name)
Static Protected Attributes inherited from GRINS::Physics
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
static bool _is_axisymmetric = false
Caches whether we are solving an axisymmetric problem or not.
Detailed Description
template<class Viscosity>
class GRINS::TurbulenceModelsBase< Viscosity >
Physics class for Turbulence Models.
This physics class implements the various turbulence models that can be used alongside NS to model turbulent flows. This is a templated class, the class Viscosity can be instantiated as a specific type (right now:ConstantViscosity or SpatiallyVaryingViscosity) to allow the user to specify a constant or spatially varying viscosity in the input file
Definition at line 48 of file turbulence_models_base.h.
Constructor & Destructor Documentation
template<class Mu > GRINS::TurbulenceModelsBase< Mu >::TurbulenceModelsBase (const std::string & physics_name, const GetPot & input)
Definition at line 47 of file turbulence_models_base.C.
References GRINS::TurbulenceModelsBase< Viscosity >::_rho, GRINS::PhysicsNaming::incompressible_navier_stokes(), and GRINS::ParameterUser::set_parameter().
     : Physics(physics_name, input),
       _rho(input("Physics/"+PhysicsNaming::incompressible_navier_stokes()+"/rho", 1.0)),
       _mu(input,MaterialsParsing::material_name(input,PhysicsNaming::incompressible_navier_stokes()))
   {
     this->set_parameter(this->_rho, input, "Physics/"+PhysicsNaming::incompressible_navier_stokes()+"/rho", this->_rho);
   }
template<class Mu > GRINS::TurbulenceModelsBase< Mu >::~TurbulenceModelsBase ()
Definition at line 66 of file turbulence_models_base.C.
   {
     return;
   }
template<class Viscosity > GRINS::TurbulenceModelsBase< Viscosity >::TurbulenceModelsBase () private
Member Function Documentation
template<class Mu > void GRINS::TurbulenceModelsBase< Mu >::init_variables (libMesh::FEMSystem * system) virtual
Initialize variables for this physics.
Implements GRINS::Physics.
Reimplemented in GRINS::SpalartAllmaras< Viscosity >, GRINS::SpalartAllmarasStabilizationBase< Viscosity >, and GRINS::SpalartAllmarasSPGSMStabilization< Viscosity >.
Definition at line 56 of file turbulence_models_base.C.
Referenced by GRINS::SpalartAllmaras< Viscosity >::init_variables().
   {
     this->_dim = system->get_mesh().mesh_dimension();
     this->_mu.init(system);
     return;
   }
template<class Mu > void GRINS::TurbulenceModelsBase< Mu >::register_parameter (const std::string & param_name, libMesh::ParameterMultiAccessor< libMesh::Number > & param_pointer) const virtual
Each subclass will register its copy of an independent.
Reimplemented from GRINS::ParameterUser.
Reimplemented in GRINS::SpalartAllmaras< Viscosity >, GRINS::SpalartAllmarasSPGSMStabilization< Viscosity >, and GRINS::SpalartAllmarasStabilizationBase< Viscosity >.
Definition at line 73 of file turbulence_models_base.C.
References GRINS::ParameterUser::register_parameter().
   {
     ParameterUser::register_parameter(param_name, param_pointer);
     _mu.register_parameter(param_name, param_pointer);
   }
Member Data Documentation
template<class Viscosity > unsigned int GRINS::TurbulenceModelsBase< Viscosity >::_dim protected
Physical dimension of problem.
Todo:
Do we really need to cache this?
Definition at line 69 of file turbulence_models_base.h.
template<class Viscosity > Viscosity GRINS::TurbulenceModelsBase< Viscosity >::_mu protected
Viscosity object.
Definition at line 76 of file turbulence_models_base.h.
template<class Viscosity > libMesh::Number GRINS::TurbulenceModelsBase< Viscosity >::_rho protected
Material parameters, read from input.
Todo:
Create objects to allow for function specification
Definition at line 73 of file turbulence_models_base.h.
Referenced by GRINS::TurbulenceModelsBase< Viscosity >::TurbulenceModelsBase().
The documentation for this class was generated from the following files:
src/physics/include/grins/turbulence_models_base.h
src/physics/src/turbulence_models_base.C