GRINS-0.7.0: GRINS::SpeciesMassFractionsFEVariables Class Reference
GRINS::SpeciesMassFractionsFEVariables Class Reference
#include <species_mass_fracs_fe_variables.h>
Public Member Functions
SpeciesMassFractionsFEVariables (const GetPot &input, const std::string &physics_name, bool _is_constraint_var=false)
~SpeciesMassFractionsFEVariables ()
unsigned int n_species () const
VariableIndex species (unsigned int species) const
const std::string & material () const
const std::string & prefix () const
Public Member Functions inherited from GRINS::SingleFETypeVariable
SingleFETypeVariable (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &subsection, const std::string &default_family, const std::string &default_order, bool is_constraint_var)
Deprecated, old style constructor.
SingleFETypeVariable (const GetPot &input, const std::string &subsection, bool is_constraint_var)
Primary constructor.
~SingleFETypeVariable ()
virtual void init (libMesh::FEMSystem *system)
Add variables to the system.
Public Member Functions inherited from GRINS::FEVariablesBase
FEVariablesBase (bool is_constraint_var)
~FEVariablesBase ()
bool is_constraint_var () const
void set_neumann_bc_is_positive (bool is_positive)
Reset whetever Neumann bc is postive or not.
libMesh::Real neumann_bc_sign () const
const std::vector< std::string > & active_var_names () const
Return the var names that are active from this class.
const std::vector< VariableIndex > & var_indices () const
Private Member Functions
SpeciesMassFractionsFEVariables ()
std::string subsection () const
Private Attributes
std::string _prefix
std::string _material
Additional Inherited Members
Protected Member Functions inherited from GRINS::SingleFETypeVariable
void parse_family_and_order (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &subsection, std::vector< GRINSEnums::FEFamily > &family, std::vector< GRINSEnums::Order > &order, const std::string &default_family, const std::string &default_order)
Helper function to parse FEFamily and Order.
void dup_family_order_check (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix) const
Check (and error if true) for old and new style FEFamily/Order input.
bool have_family_or_order (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &subsection) const
Check for no presence of FEFamily/Order input.
void parse_old_style_with_warning (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &default_family, const std::string &default_order, const std::string &subsection, GRINSEnums::FEFamily &family, GRINSEnums::Order &order)
void parse_new_style (const GetPot &input, const std::string &subsection, GRINSEnums::FEFamily &family, GRINSEnums::Order &order)
Protected Member Functions inherited from GRINS::FEVariablesBase
void parse_names_from_input (const GetPot &input, const std::string &subsection, std::vector< std::string > &var_names, const std::vector< std::string > &default_names)
Method to parse variable names from input.
void duplicate_name_section_check (const GetPot &input) const
Check for old name style and new name style. If both present, error.
bool check_dep_name_input (const GetPot &input, const std::string &new_subsection) const
Check for deprecated variable name input style.
Protected Attributes inherited from GRINS::FEVariablesBase
std::vector< VariableIndex > _vars
std::vector< std::string > _var_names
std::vector< GRINSEnums::FEFamily > _family
std::vector< GRINSEnums::Order > _order
bool _is_constraint_var
Tracks whether this is a constraint variable.
libMesh::Real _neumann_bc_sign
Track the sign of the Neumann BC term. Defaults to 1.0.
Detailed Description
Definition at line 36 of file species_mass_fracs_fe_variables.h.
Constructor & Destructor Documentation
GRINS::SpeciesMassFractionsFEVariables::SpeciesMassFractionsFEVariables (const GetPot & input, const std::string & physics_name, bool _is_constraint_var = false)
Definition at line 36 of file species_mass_fracs_fe_variables.C.
References _material, _prefix, GRINS::FEVariablesBase::_var_names, and GRINS::MaterialsParsing::parse_species_varnames().
       :  SingleFETypeVariable(input,physics_name,"species_",this->subsection(),
                               "LAGRANGE","SECOND",is_constraint_var),
          _prefix(input("Variables/"+this->subsection()+"/names", "w_" )),
          _material(MaterialsParsing::material_name(input,physics_name))
     {
       MaterialsParsing::parse_species_varnames(input, _material, _prefix, _var_names);
     }
GRINS::SpeciesMassFractionsFEVariables::~SpeciesMassFractionsFEVariables () inline
Definition at line 43 of file species_mass_fracs_fe_variables.h.
 {};
GRINS::SpeciesMassFractionsFEVariables::SpeciesMassFractionsFEVariables () private
Member Function Documentation
const std::string& GRINS::SpeciesMassFractionsFEVariables::material () const inline
Definition at line 49 of file species_mass_fracs_fe_variables.h.
References _material.
Referenced by GRINS::MoleFractionsDirichletBCFactory::add_found_vars(), GRINS::PrescribedMoleFractionsDirichletOldStyleBCFactory::convert_mole_fracs_and_add_to_func(), and GRINS::CatalyticWallNeumannBCFactoryCommon< ImplType >::extract_material().
     { return _material; }
unsigned int GRINS::SpeciesMassFractionsFEVariables::n_species () const inline
Definition at line 68 of file species_mass_fracs_fe_variables.h.
References GRINS::FEVariablesBase::_var_names.
   {
     // We *must* use the size of _var_names here since that gets populated
     // at construction time.
     return _var_names.size();
   }
const std::string& GRINS::SpeciesMassFractionsFEVariables::prefix () const inline
Definition at line 52 of file species_mass_fracs_fe_variables.h.
References _prefix.
Referenced by GRINS::MoleFractionsDirichletBCFactory::add_mole_frac_to_mass_frac(), and GRINS::MoleFractionsDirichletBCFactory::set_vars_to_search_for().
     { return _prefix; }
VariableIndex GRINS::SpeciesMassFractionsFEVariables::species (unsigned int species) const inline
Definition at line 76 of file species_mass_fracs_fe_variables.h.
References GRINS::FEVariablesBase::_vars.
Referenced by GRINS::MoleFractionsDirichletBCFactory::add_mole_frac_to_mass_frac(), GRINS::PrescribedMoleFractionsDirichletOldStyleBCFactory::convert_mole_fracs_and_add_to_func(), GRINS::ReactingLowMachNavierStokesAbstract::init_context(), GRINS::ReactingLowMachNavierStokesAbstract::mass_fractions(), and GRINS::ReactingLowMachNavierStokesAbstract::set_time_evolving_vars().
   {
     return _vars[species];
   }
std::string GRINS::SpeciesMassFractionsFEVariables::subsection () const inline private
Definition at line 59 of file species_mass_fracs_fe_variables.h.
References GRINS::VariablesParsing::species_mass_fractions_section().
     { return VariablesParsing::species_mass_fractions_section(); }
Member Data Documentation
std::string GRINS::SpeciesMassFractionsFEVariables::_material private
Definition at line 64 of file species_mass_fracs_fe_variables.h.
Referenced by material(), and SpeciesMassFractionsFEVariables().
std::string GRINS::SpeciesMassFractionsFEVariables::_prefix private
Definition at line 62 of file species_mass_fracs_fe_variables.h.
Referenced by prefix(), and SpeciesMassFractionsFEVariables().
The documentation for this class was generated from the following files:
src/variables/include/grins/species_mass_fracs_fe_variables.h
src/variables/src/species_mass_fracs_fe_variables.C