GRINS-0.7.0: GRINS::ElasticCableAbstract Class Reference
GRINS::ElasticCableAbstract Class Reference
#include <elastic_cable_abstract.h>
Public Member Functions
ElasticCableAbstract (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~ElasticCableAbstract ()
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
Public Member Functions inherited from GRINS::SolidMechanicsAbstract
SolidMechanicsAbstract (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~SolidMechanicsAbstract ()
virtual void init_variables (libMesh::FEMSystem *system)
Initialize variables for this physics.
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Set which variables are time evolving.
Public Member Functions inherited from GRINS::Physics
Physics (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~Physics ()
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for element interiors.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void damping_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Damping matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_damping_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
ICHandlingBase * get_ic_handler ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Member Functions
const libMesh::FEGenericBase< libMesh::Real > * get_fe (const AssemblyContext &context)
Protected Member Functions inherited from GRINS::Physics
libMesh::UniquePtr< libMesh::FEGenericBase< libMesh::Real > > build_new_fe (const libMesh::Elem *elem, const libMesh::FEGenericBase< libMesh::Real > *fe, const libMesh::Point p)
void parse_enabled_subdomains (const GetPot &input, const std::string &physics_name)
Protected Attributes
libMesh::Real _A
Cross-sectional area of the cable.
libMesh::Real _rho
Cable density.
Protected Attributes inherited from GRINS::SolidMechanicsAbstract
DisplacementFEVariables _disp_vars
Protected Attributes inherited from GRINS::Physics
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
Private Member Functions
ElasticCableAbstract ()
Additional Inherited Members
Static Public Member Functions inherited from GRINS::Physics
static void set_is_axisymmetric (bool is_axisymmetric)
Set whether we should treat the problem as axisymmetric.
static bool is_axisymmetric ()
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Types inherited from GRINS::SolidMechanicsAbstract
typedef const libMesh::DenseSubVector< libMesh::Number > &(libMesh::DiffContext::* VarFuncType) (unsigned int) const
typedef void(libMesh::FEMContext::* InteriorFuncType) (unsigned int, unsigned int, libMesh::Real &) const
typedef libMesh::Real(libMesh::DiffContext::* VarDerivType) () const
Static Protected Attributes inherited from GRINS::Physics
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
static bool _is_axisymmetric = false
Caches whether we are solving an axisymmetric problem or not.
Detailed Description
Definition at line 37 of file elastic_cable_abstract.h.
Constructor & Destructor Documentation
GRINS::ElasticCableAbstract::ElasticCableAbstract (const GRINS::PhysicsName & physics_name, const GetPot & input)
Definition at line 39 of file elastic_cable_abstract.C.
References _A, _rho, GRINS::PhysicsNaming::elastic_cable(), and GRINS::MaterialsParsing::read_property().
     : SolidMechanicsAbstract(physics_name,input),
       _A( 0.0 ),
       _rho(0.0)
   {
     MaterialsParsing::read_property( input,
                                      "Physics/"+physics_name+"/A",
                                      "CrossSectionalArea",
                                      PhysicsNaming::elastic_cable(),
                                      (*this),
                                      _A );
     MaterialsParsing::read_property( input,
                                      "Physics/"+physics_name+"/rho",
                                      "Density",
                                      PhysicsNaming::elastic_cable(),
                                      (*this),
                                      _rho );
   }
virtual GRINS::ElasticCableAbstract::~ElasticCableAbstract () inline virtual
Definition at line 43 of file elastic_cable_abstract.h.
 {};
GRINS::ElasticCableAbstract::ElasticCableAbstract () private
Member Function Documentation
const libMesh::FEGenericBase< libMesh::Real > * GRINS::ElasticCableAbstract::get_fe (const AssemblyContext & context) inline protected
Definition at line 65 of file elastic_cable_abstract.h.
References GRINS::SolidMechanicsAbstract::_disp_vars, and GRINS::DisplacementFEVariables::u().
Referenced by GRINS::ElasticCableConstantGravity::element_time_derivative(), and init_context().
   {
     // For this Physics, we need to make sure that we grab only the 1D elements
     return context.get_element_fe(_disp_vars.u(),1);
   }
void GRINS::ElasticCableAbstract::init_context (AssemblyContext & context) virtual
Initialize context for added physics variables.
Reimplemented from GRINS::Physics.
Definition at line 61 of file elastic_cable_abstract.C.
References get_fe().
   {
     this->get_fe(context)->get_JxW();
     this->get_fe(context)->get_phi();
     this->get_fe(context)->get_dphidxi();
     // Need for constructing metric tensors
     this->get_fe(context)->get_dxyzdxi();
     this->get_fe(context)->get_dxidx();
     this->get_fe(context)->get_dxidy();
     this->get_fe(context)->get_dxidz();
   }
Member Data Documentation
libMesh::Real GRINS::ElasticCableAbstract::_A protected
Cross-sectional area of the cable.
Definition at line 51 of file elastic_cable_abstract.h.
Referenced by ElasticCableAbstract(), and GRINS::ElasticCableConstantGravity::element_time_derivative().
libMesh::Real GRINS::ElasticCableAbstract::_rho protected
Cable density.
Definition at line 54 of file elastic_cable_abstract.h.
Referenced by ElasticCableAbstract(), and GRINS::ElasticCableConstantGravity::element_time_derivative().
The documentation for this class was generated from the following files:
src/physics/include/grins/elastic_cable_abstract.h
src/physics/src/elastic_cable_abstract.C