GRINS-0.7.0: GRINS::AntiochKinetics Class Reference
GRINS::AntiochKinetics Class Reference
Wrapper class for evaluating chemical kinetics using Antioch.
#include <antioch_kinetics.h>
Public Member Functions
AntiochKinetics (const AntiochMixture &mixture)
~AntiochKinetics ()
void omega_dot (const libMesh::Real &T, const libMesh::Real rho, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &omega_dot)
void omega_dot (const Antioch::TempCache< libMesh::Real > &temp_cache, const libMesh::Real rho, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &omega_dot)
Protected Attributes
const AntiochMixture & _antioch_mixture
Antioch::KineticsEvaluator< libMesh::Real > _antioch_kinetics
Antioch::CEAEvaluator< libMesh::Real > _antioch_cea_thermo
Private Member Functions
AntiochKinetics ()
Detailed Description
Wrapper class for evaluating chemical kinetics using Antioch.
This class is expected to be constructed after threads have been forked and will only live during the lifetime of the thread. By default, Antioch is working in SI units. Note that this documentation will always be built regardless if Antioch is included in the GRINS build or not. Check configure output to confirm that Antioch was included in the build.
Definition at line 57 of file antioch_kinetics.h.
Constructor & Destructor Documentation
GRINS::AntiochKinetics::AntiochKinetics (const AntiochMixture & mixture)
Definition at line 42 of file antioch_kinetics.C.
     : _antioch_mixture( mixture ),
       _antioch_kinetics( mixture.reaction_set(), 0 ),
       _antioch_cea_thermo( mixture.cea_mixture() )
   {}
GRINS::AntiochKinetics::~AntiochKinetics () inline
Definition at line 63 of file antioch_kinetics.h.
 {};
GRINS::AntiochKinetics::AntiochKinetics () private
Member Function Documentation
void GRINS::AntiochKinetics::omega_dot (const libMesh::Real & T, const libMesh::Real rho, const std::vector< libMesh::Real > & mass_fractions, std::vector< libMesh::Real > & omega_dot)
Definition at line 48 of file antioch_kinetics.C.
Referenced by main().
   {
     Antioch::TempCache<libMesh::Real> temp_cache(T);
     this->omega_dot(temp_cache,rho,mass_fractions,omega_dot);
   }
void GRINS::AntiochKinetics::omega_dot (const Antioch::TempCache< libMesh::Real > & temp_cache, const libMesh::Real rho, const std::vector< libMesh::Real > & mass_fractions, std::vector< libMesh::Real > & omega_dot)
Definition at line 57 of file antioch_kinetics.C.
References _antioch_cea_thermo, _antioch_kinetics, _antioch_mixture, GRINS::AntiochChemistry::molar_densities(), and GRINS::AntiochChemistry::n_species().
   {
     const unsigned int n_species = _antioch_mixture.n_species();
     libmesh_assert_equal_to( mass_fractions.size(), n_species );
     libmesh_assert_equal_to( omega_dot.size(), n_species );
     std::vector<libMesh::Real> h_RT_minus_s_R(n_species, 0.0);
     std::vector<libMesh::Real> molar_densities(n_species, 0.0);
     _antioch_cea_thermo.h_RT_minus_s_R( temp_cache, h_RT_minus_s_R );
     _antioch_mixture.molar_densities( rho, mass_fractions, molar_densities );
     _antioch_kinetics.compute_mass_sources( temp_cache.T,
                                             molar_densities,
                                             h_RT_minus_s_R,
                                             omega_dot );
   }
Member Data Documentation
Antioch::CEAEvaluator<libMesh::Real> GRINS::AntiochKinetics::_antioch_cea_thermo protected
Definition at line 81 of file antioch_kinetics.h.
Referenced by omega_dot().
Antioch::KineticsEvaluator<libMesh::Real> GRINS::AntiochKinetics::_antioch_kinetics protected
Definition at line 79 of file antioch_kinetics.h.
Referenced by omega_dot().
const AntiochMixture& GRINS::AntiochKinetics::_antioch_mixture protected
Definition at line 77 of file antioch_kinetics.h.
Referenced by omega_dot().
The documentation for this class was generated from the following files:
src/properties/include/grins/antioch_kinetics.h
src/properties/src/antioch_kinetics.C