GRINS-0.7.0: GRINSTesting::ThermochemTestCommon Class Reference
GRINSTesting::ThermochemTestCommon Class Reference
#include <thermochem_test_common.h>
Static Public Member Functions
static libMesh::Real compute_mass_frac_mixture_prop (const std::vector< libMesh::Real > &properties, const std::vector< libMesh::Real > &mass_fracs)
static libMesh::Real arrhenius_rate (libMesh::Real A, libMesh::Real b, libMesh::Real Ea, libMesh::Real T)
static libMesh::Real compute_third_body_molar_density (const std::vector< libMesh::Real > &molar_densities, const std::vector< libMesh::Real > &three_body_efficiencies)
static libMesh::Real nasa7_cp_R_exact (libMesh::Real T, libMesh::Real a0, libMesh::Real a1, libMesh::Real a2, libMesh::Real a3, libMesh::Real a4)
static libMesh::Real nasa7_h_RT_exact (libMesh::Real T, libMesh::Real a0, libMesh::Real a1, libMesh::Real a2, libMesh::Real a3, libMesh::Real a4, libMesh::Real a5)
static libMesh::Real nasa7_s_R_exact (libMesh::Real T, libMesh::Real a0, libMesh::Real a1, libMesh::Real a2, libMesh::Real a3, libMesh::Real a4, libMesh::Real a6)
static libMesh::Real nasa9_cp_R_exact (libMesh::Real T, libMesh::Real a0, libMesh::Real a1, libMesh::Real a2, libMesh::Real a3, libMesh::Real a4, libMesh::Real a5, libMesh::Real a6)
static libMesh::Real nasa9_h_RT_exact (libMesh::Real T, libMesh::Real a0, libMesh::Real a1, libMesh::Real a2, libMesh::Real a3, libMesh::Real a4, libMesh::Real a5, libMesh::Real a6, libMesh::Real a7)
static libMesh::Real nasa9_s_R_exact (libMesh::Real T, libMesh::Real a0, libMesh::Real a1, libMesh::Real a2, libMesh::Real a3, libMesh::Real a4, libMesh::Real a5, libMesh::Real a6, libMesh::Real a8)
Detailed Description
Definition at line 40 of file thermochem_test_common.h.
Member Function Documentation
static libMesh::Real GRINSTesting::ThermochemTestCommon::arrhenius_rate (libMesh::Real A, libMesh::Real b, libMesh::Real Ea, libMesh::Real T) inline static
Definition at line 58 of file thermochem_test_common.h.
References GRINS::Constants::R_universal.
Referenced by GRINSTesting::KineticsTestBase::compute_reaction_rates().
     {
       libMesh::Real RT = GRINS::Constants::R_universal*T;
       return A*std::pow(T,b)*std::exp(-Ea/RT);
     }
static libMesh::Real GRINSTesting::ThermochemTestCommon::compute_mass_frac_mixture_prop (const std::vector< libMesh::Real > & properties, const std::vector< libMesh::Real > & mass_fracs) inline static
Definition at line 44 of file thermochem_test_common.h.
Referenced by GRINSTesting::NASAThermoTestBase::test_cp_common().
     {
       CPPUNIT_ASSERT_EQUAL( properties.size(), mass_fracs.size() );
       unsigned int size = properties.size();
       libMesh::Real mixed_value = 0.0;
       for( unsigned int s = 0; s < size; s++ )
         mixed_value += mass_fracs[s]*properties[s];
       return mixed_value;
     }
static libMesh::Real GRINSTesting::ThermochemTestCommon::compute_third_body_molar_density (const std::vector< libMesh::Real > & molar_densities, const std::vector< libMesh::Real > & three_body_efficiencies) inline static
Definition at line 68 of file thermochem_test_common.h.
Referenced by GRINSTesting::KineticsTestBase::compute_reaction_rates().
     {
       CPPUNIT_ASSERT_EQUAL( molar_densities.size(), three_body_efficiencies.size() );
       libMesh::Real M = 0.0;
       for(unsigned int s = 0; s < molar_densities.size(); s++ )
         M += molar_densities[s]*three_body_efficiencies[s];
       return M;
     }
static libMesh::Real GRINSTesting::ThermochemTestCommon::nasa7_cp_R_exact (libMesh::Real T, libMesh::Real a0, libMesh::Real a1, libMesh::Real a2, libMesh::Real a3, libMesh::Real a4) inline static
Definition at line 81 of file thermochem_test_common.h.
Referenced by GRINSTesting::NASA7ThermoTestBase::cp_exact().
     {
       return a0 + a1*T + a2*T*T + a3*T*T*T + a4*(T*T*T*T);
     }
static libMesh::Real GRINSTesting::ThermochemTestCommon::nasa7_h_RT_exact (libMesh::Real T, libMesh::Real a0, libMesh::Real a1, libMesh::Real a2, libMesh::Real a3, libMesh::Real a4, libMesh::Real a5) inline static
Definition at line 88 of file thermochem_test_common.h.
Referenced by GRINSTesting::NASA7ThermoTestBase::h_exact(), and GRINSTesting::NASA7ThermoTestBase::h_RT_exact().
     {
       return a0 + a1/2.0*T + a2/3.0*T*T + a3/4.0*T*T*T + a4/5.0*(T*T*T*T) + a5/T;
     }
static libMesh::Real GRINSTesting::ThermochemTestCommon::nasa7_s_R_exact (libMesh::Real T, libMesh::Real a0, libMesh::Real a1, libMesh::Real a2, libMesh::Real a3, libMesh::Real a4, libMesh::Real a6) inline static
Definition at line 95 of file thermochem_test_common.h.
Referenced by GRINSTesting::NASA7ThermoTestBase::s_R_exact().
     {
       return a0*std::log(T) + a1*T + a2/2.0*T*T + a3/3.0*T*T*T + a4/4.0*(T*T*T*T) + a6;
     }
static libMesh::Real GRINSTesting::ThermochemTestCommon::nasa9_cp_R_exact (libMesh::Real T, libMesh::Real a0, libMesh::Real a1, libMesh::Real a2, libMesh::Real a3, libMesh::Real a4, libMesh::Real a5, libMesh::Real a6) inline static
Definition at line 102 of file thermochem_test_common.h.
Referenced by GRINSTesting::NASA9ThermoTestBase::cp_exact().
     {
       return a0/(T*T) + a1/T + a2 + a3*T + a4*(T*T) + a5*(T*T*T) + a6*(T*T*T*T);
     }
static libMesh::Real GRINSTesting::ThermochemTestCommon::nasa9_h_RT_exact (libMesh::Real T, libMesh::Real a0, libMesh::Real a1, libMesh::Real a2, libMesh::Real a3, libMesh::Real a4, libMesh::Real a5, libMesh::Real a6, libMesh::Real a7) inline static
Definition at line 109 of file thermochem_test_common.h.
Referenced by GRINSTesting::NASA9ThermoTestBase::h_exact(), and GRINSTesting::NASA9ThermoTestBase::h_RT_exact().
     {
       return -a0/(T*T) + a1*std::log(T)/T + a2 + a3*T/2.0 + a4*(T*T)/3.0
         + a5*(T*T*T)/4.0 + a6*(T*T*T*T)/5.0 + a7/T;
     }
static libMesh::Real GRINSTesting::ThermochemTestCommon::nasa9_s_R_exact (libMesh::Real T, libMesh::Real a0, libMesh::Real a1, libMesh::Real a2, libMesh::Real a3, libMesh::Real a4, libMesh::Real a5, libMesh::Real a6, libMesh::Real a8) inline static
Definition at line 117 of file thermochem_test_common.h.
Referenced by GRINSTesting::NASA9ThermoTestBase::s_R_exact().
     {
       return -a0/(2.*T*T) - a1/T + a2*std::log(T) + a3*T + a4*(T*T)/2.0
         + a5*(T*T*T)/3.0 + a6*(T*T*T*T)/4.0 + a8;
     }
The documentation for this class was generated from the following file:
test/interface/thermochem_test_common.h