GRINS-0.7.0: GRINS::HeatTransferBase< Conductivity > Class Template Reference
GRINS::HeatTransferBase< Conductivity > Class Template Reference
Physics class for Heat Transfer.
#include <heat_transfer_base.h>
Public Member Functions
HeatTransferBase (const std::string &physics_name, const std::string &core_physics_name, const GetPot &input)
~HeatTransferBase ()
virtual void init_variables (libMesh::FEMSystem *system)
Initialization Heat Transfer variables.
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Sets velocity variables to be time-evolving.
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Public Member Functions inherited from GRINS::Physics
Physics (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~Physics ()
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for element interiors.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void damping_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Damping matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_damping_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
ICHandlingBase * get_ic_handler ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
Protected Attributes
unsigned int _dim
Physical dimension of problem.
VelocityFEVariables _flow_vars
PressureFEVariable _press_var
PrimitiveTempFEVariables _temp_vars
libMesh::Number _rho
Material parameters, read from input.
libMesh::Number _Cp
Conductivity _k
Conductivity.
Protected Attributes inherited from GRINS::Physics
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
Private Member Functions
HeatTransferBase ()
void register_variables ()
Additional Inherited Members
Static Public Member Functions inherited from GRINS::Physics
static void set_is_axisymmetric (bool is_axisymmetric)
Set whether we should treat the problem as axisymmetric.
static bool is_axisymmetric ()
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Member Functions inherited from GRINS::Physics
libMesh::UniquePtr< libMesh::FEGenericBase< libMesh::Real > > build_new_fe (const libMesh::Elem *elem, const libMesh::FEGenericBase< libMesh::Real > *fe, const libMesh::Point p)
void parse_enabled_subdomains (const GetPot &input, const std::string &physics_name)
Static Protected Attributes inherited from GRINS::Physics
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
static bool _is_axisymmetric = false
Caches whether we are solving an axisymmetric problem or not.
Detailed Description
template<class Conductivity>
class GRINS::HeatTransferBase< Conductivity >
Physics class for Heat Transfer.
Definition at line 43 of file heat_transfer_base.h.
Constructor & Destructor Documentation
template<class K > GRINS::HeatTransferBase< K >::HeatTransferBase (const std::string & physics_name, const std::string & core_physics_name, const GetPot & input)
Definition at line 47 of file heat_transfer_base.C.
References GRINS::HeatTransferBase< Conductivity >::_Cp, GRINS::HeatTransferBase< Conductivity >::_rho, GRINS::MaterialsParsing::read_density(), GRINS::MaterialsParsing::read_specific_heat(), and GRINS::HeatTransferBase< Conductivity >::register_variables().
     : Physics(physics_name, input),
       _flow_vars(input,PhysicsNaming::incompressible_navier_stokes()),
       _press_var(input,PhysicsNaming::incompressible_navier_stokes(), true /*is_constraint_var*/),
       _temp_vars(input,PhysicsNaming::heat_transfer()),
       _rho(0.0),
       _Cp(0.0),
       _k(input,MaterialsParsing::material_name(input,core_physics_name))
   {
     MaterialsParsing::read_density( core_physics_name, input, (*this), this->_rho );
     MaterialsParsing::read_specific_heat( core_physics_name, input, (*this), this->_Cp );
     this->register_variables();
   }
template<class Conductivity > GRINS::HeatTransferBase< Conductivity >::~HeatTransferBase () inline
Definition at line 51 of file heat_transfer_base.h.
 {};
template<class Conductivity > GRINS::HeatTransferBase< Conductivity >::HeatTransferBase () private
Member Function Documentation
template<class K > void GRINS::HeatTransferBase< K >::init_context (AssemblyContext & context) virtual
Initialize context for added physics variables.
Reimplemented from GRINS::Physics.
Reimplemented in GRINS::HeatTransferStabilizationBase< Conductivity >.
Definition at line 99 of file heat_transfer_base.C.
Referenced by GRINS::HeatTransferStabilizationBase< Conductivity >::init_context().
   {
     // We should prerequest all the data
     // we will need to build the linear system
     // or evaluate a quantity of interest.
     context.get_element_fe(_temp_vars.T())->get_JxW();
     context.get_element_fe(_temp_vars.T())->get_phi();
     context.get_element_fe(_temp_vars.T())->get_dphi();
     context.get_element_fe(_temp_vars.T())->get_xyz();
     context.get_side_fe(_temp_vars.T())->get_JxW();
     context.get_side_fe(_temp_vars.T())->get_phi();
     context.get_side_fe(_temp_vars.T())->get_dphi();
     context.get_side_fe(_temp_vars.T())->get_xyz();
     return;
   }
template<class K > void GRINS::HeatTransferBase< K >::init_variables (libMesh::FEMSystem * system) virtual
Initialization Heat Transfer variables.
Add velocity and pressure variables to system.
Implements GRINS::Physics.
Definition at line 77 of file heat_transfer_base.C.
   {
     // Get libMesh to assign an index for each variable
     this->_dim = system->get_mesh().mesh_dimension();
     _flow_vars.init(system);
     this->_press_var.init(system);
     _temp_vars.init(system);
     return;
   }
template<class K > void GRINS::HeatTransferBase< K >::register_parameter (const std::string & param_name, libMesh::ParameterMultiAccessor< libMesh::Number > & param_pointer) const virtual
Each subclass will register its copy of an independent.
Reimplemented from GRINS::ParameterUser.
Definition at line 119 of file heat_transfer_base.C.
References GRINS::ParameterUser::register_parameter().
   {
     ParameterUser::register_parameter(param_name, param_pointer);
     _k.register_parameter(param_name, param_pointer);
   }
template<class K > void GRINS::HeatTransferBase< K >::register_variables () private
Definition at line 66 of file heat_transfer_base.C.
References GRINS::GRINSPrivate::VariableWarehouse::check_and_register_variable(), GRINS::VariablesParsing::pressure_section(), GRINS::VariablesParsing::temperature_section(), and GRINS::VariablesParsing::velocity_section().
Referenced by GRINS::HeatTransferBase< Conductivity >::HeatTransferBase().
   {
     GRINSPrivate::VariableWarehouse::check_and_register_variable(VariablesParsing::pressure_section(),
                                                                  this->_press_var);
     GRINSPrivate::VariableWarehouse::check_and_register_variable(VariablesParsing::velocity_section(),
                                                                  this->_flow_vars);
     GRINSPrivate::VariableWarehouse::check_and_register_variable(VariablesParsing::temperature_section(),
                                                                  this->_temp_vars);
   }
template<class K > void GRINS::HeatTransferBase< K >::set_time_evolving_vars (libMesh::FEMSystem * system) virtual
Sets velocity variables to be time-evolving.
Reimplemented from GRINS::Physics.
Definition at line 90 of file heat_transfer_base.C.
   {
     // Tell the system to march temperature forward in time
     system->time_evolving(_temp_vars.T());
     return;
   }
Member Data Documentation
template<class Conductivity > libMesh::Number GRINS::HeatTransferBase< Conductivity >::_Cp protected
Definition at line 87 of file heat_transfer_base.h.
Referenced by GRINS::HeatTransferBase< Conductivity >::HeatTransferBase().
template<class Conductivity > unsigned int GRINS::HeatTransferBase< Conductivity >::_dim protected
Physical dimension of problem.
Todo:
Make this static member of base class?
Definition at line 76 of file heat_transfer_base.h.
template<class Conductivity > VelocityFEVariables GRINS::HeatTransferBase< Conductivity >::_flow_vars protected
Definition at line 78 of file heat_transfer_base.h.
template<class Conductivity > Conductivity GRINS::HeatTransferBase< Conductivity >::_k protected
Conductivity.
Definition at line 90 of file heat_transfer_base.h.
template<class Conductivity > PressureFEVariable GRINS::HeatTransferBase< Conductivity >::_press_var protected
Definition at line 79 of file heat_transfer_base.h.
template<class Conductivity > libMesh::Number GRINS::HeatTransferBase< Conductivity >::_rho protected
Material parameters, read from input.
Todo:
Need to generalize material parameters. Right now they are assumed constant
Todo:
Shouldn't this rho be the same as the one in the flow? Need to figure out how to have those shared
Definition at line 87 of file heat_transfer_base.h.
Referenced by GRINS::HeatTransferBase< Conductivity >::HeatTransferBase().
template<class Conductivity > PrimitiveTempFEVariables GRINS::HeatTransferBase< Conductivity >::_temp_vars protected
Definition at line 80 of file heat_transfer_base.h.
The documentation for this class was generated from the following files:
src/physics/include/grins/heat_transfer_base.h
src/physics/src/heat_transfer_base.C