GRINS-0.7.0: GRINS::BoussinesqBuoyancy Class Reference
GRINS::BoussinesqBuoyancy Class Reference
Adds Boussinesq bouyancy source term.
#include <boussinesq_buoyancy.h>
Public Member Functions
BoussinesqBuoyancy (const std::string &physics_name, const GetPot &input)
~BoussinesqBuoyancy ()
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Source term contribution for BoussinesqBuoyancy.
Public Member Functions inherited from GRINS::BoussinesqBuoyancyBase
BoussinesqBuoyancyBase (const std::string &physics_name, const GetPot &input)
~BoussinesqBuoyancyBase ()
virtual void init_variables (libMesh::FEMSystem *system)
Initialization of BoussinesqBuoyancy variables.
Public Member Functions inherited from GRINS::Physics
Physics (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~Physics ()
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Set which variables are time evolving.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void damping_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Damping matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_damping_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
ICHandlingBase * get_ic_handler ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Private Member Functions
BoussinesqBuoyancy ()
Additional Inherited Members
Static Public Member Functions inherited from GRINS::Physics
static void set_is_axisymmetric (bool is_axisymmetric)
Set whether we should treat the problem as axisymmetric.
static bool is_axisymmetric ()
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Member Functions inherited from GRINS::BoussinesqBuoyancyBase
void read_property (const GetPot &input, const std::string &old_option, const std::string &property, libMesh::Real &value)
Helper function for parsing/maintaing backward compatibility.
void no_input_warning (const GetPot &input, const std::string &old_option, const std::string &material, const std::string &property)
Helper function for parsing/maintaing backward compatibility.
Protected Member Functions inherited from GRINS::Physics
libMesh::UniquePtr< libMesh::FEGenericBase< libMesh::Real > > build_new_fe (const libMesh::Elem *elem, const libMesh::FEGenericBase< libMesh::Real > *fe, const libMesh::Point p)
void parse_enabled_subdomains (const GetPot &input, const std::string &physics_name)
Protected Attributes inherited from GRINS::BoussinesqBuoyancyBase
VelocityFEVariables _flow_vars
PressureFEVariable _press_var
PrimitiveTempFEVariables _temp_vars
libMesh::Number _rho
density
libMesh::Number _T_ref
reference temperature
libMesh::Number _beta_T
coefficient of thermal expansion
libMesh::Point _g
Gravitational vector.
unsigned int _dim
Physical dimension of problem.
Protected Attributes inherited from GRINS::Physics
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
Static Protected Attributes inherited from GRINS::Physics
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
static bool _is_axisymmetric = false
Caches whether we are solving an axisymmetric problem or not.
Detailed Description
Adds Boussinesq bouyancy source term.
This class implements the Boussinesq approximation for thermal buoyancy. Namely: where reference density, reference temperature, coefficient of thermal expansion, and the gravitional vector. This source term to the governing flow equations through the element_time_derivative routine. This class requires a flow physics enabled and the ConvectiveHeatTransfer physics class enabled.
Definition at line 48 of file boussinesq_buoyancy.h.
Constructor & Destructor Documentation
GRINS::BoussinesqBuoyancy::BoussinesqBuoyancy (const std::string & physics_name, const GetPot & input)
Definition at line 41 of file boussinesq_buoyancy.C.
     : BoussinesqBuoyancyBase(physics_name,input)
   {
     return;
   }
GRINS::BoussinesqBuoyancy::~BoussinesqBuoyancy ()
Definition at line 47 of file boussinesq_buoyancy.C.
   {
     return;
   }
GRINS::BoussinesqBuoyancy::BoussinesqBuoyancy () private
Member Function Documentation
void GRINS::BoussinesqBuoyancy::element_time_derivative (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Source term contribution for BoussinesqBuoyancy.
This is the main part of the class. This will add the source term to the IncompressibleNavierStokes class.
Reimplemented from GRINS::Physics.
Definition at line 52 of file boussinesq_buoyancy.C.
References GRINS::BoussinesqBuoyancyBase::_beta_T, GRINS::BoussinesqBuoyancyBase::_dim, GRINS::BoussinesqBuoyancyBase::_flow_vars, GRINS::BoussinesqBuoyancyBase::_g, GRINS::BoussinesqBuoyancyBase::_rho, GRINS::BoussinesqBuoyancyBase::_T_ref, GRINS::BoussinesqBuoyancyBase::_temp_vars, GRINS::PrimitiveTempFEVariables::T(), GRINS::VelocityFEVariables::u(), GRINS::VelocityFEVariables::v(), and GRINS::VelocityFEVariables::w().
   {
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->BeginTimer("BoussinesqBuoyancy::element_time_derivative");
 #endif
     // The number of local degrees of freedom in each variable.
     const unsigned int n_u_dofs = context.get_dof_indices(_flow_vars.u()).size();
     const unsigned int n_T_dofs = context.get_dof_indices(_temp_vars.T()).size();
     // Element Jacobian * quadrature weights for interior integration.
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(_flow_vars.u())->get_JxW();
     // The velocity shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& vel_phi =
       context.get_element_fe(_flow_vars.u())->get_phi();
     // The temperature shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& T_phi =
       context.get_element_fe(_temp_vars.T())->get_phi();
     // Get residuals
     libMesh::DenseSubVector<libMesh::Number> &Fu = context.get_elem_residual(_flow_vars.u()); // R_{u}
     libMesh::DenseSubVector<libMesh::Number> &Fv = context.get_elem_residual(_flow_vars.v()); // R_{v}
     libMesh::DenseSubVector<libMesh::Number>* Fw = NULL;
     // Get Jacobians
     libMesh::DenseSubMatrix<libMesh::Number> &KuT = context.get_elem_jacobian(_flow_vars.u(), _temp_vars.T()); // R_{u},{T}
     libMesh::DenseSubMatrix<libMesh::Number> &KvT = context.get_elem_jacobian(_flow_vars.v(), _temp_vars.T()); // R_{v},{T}
     libMesh::DenseSubMatrix<libMesh::Number>* KwT = NULL;
     if( _dim == 3 )
       {
         Fw  = &context.get_elem_residual(_flow_vars.w()); // R_{w}
         KwT = &context.get_elem_jacobian(_flow_vars.w(), _temp_vars.T()); // R_{w},{T}
       }
     // Now we will build the element Jacobian and residual.
     // Constructing the residual requires the solution and its
     // gradient from the previous timestep.  This must be
     // calculated at each quadrature point by summing the
     // solution degree-of-freedom values by the appropriate
     // weight functions.
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     for (unsigned int qp=0; qp != n_qpoints; qp++)
       {
         // Compute the solution & its gradient at the old Newton iterate.
         libMesh::Number T;
         T = context.interior_value(_temp_vars.T(), qp);
         // First, an i-loop over the velocity degrees of freedom.
         // We know that n_u_dofs == n_v_dofs so we can compute contributions
         // for both at the same time.
         for (unsigned int i=0; i != n_u_dofs; i++)
           {
             Fu(i) += -_rho*_beta_T*(T - _T_ref)*_g(0)*vel_phi[i][qp]*JxW[qp];
             Fv(i) += -_rho*_beta_T*(T - _T_ref)*_g(1)*vel_phi[i][qp]*JxW[qp];
             if (_dim == 3)
               (*Fw)(i) += -_rho*_beta_T*(T - _T_ref)*_g(2)*vel_phi[i][qp]*JxW[qp];
             if (compute_jacobian)
               {
                 for (unsigned int j=0; j != n_T_dofs; j++)
                   {
                     KuT(i,j) += context.get_elem_solution_derivative() *
                       -_rho*_beta_T*_g(0)*vel_phi[i][qp]*T_phi[j][qp]*JxW[qp];
                     KvT(i,j) += context.get_elem_solution_derivative() *
                       -_rho*_beta_T*_g(1)*vel_phi[i][qp]*T_phi[j][qp]*JxW[qp];
                     if (_dim == 3)
                       (*KwT)(i,j) += context.get_elem_solution_derivative() *
                         -_rho*_beta_T*_g(2)*vel_phi[i][qp]*T_phi[j][qp]*JxW[qp];
                   } // End j dof loop
               } // End compute_jacobian check
           } // End i dof loop
       } // End quadrature loop
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->EndTimer("BoussinesqBuoyancy::element_time_derivative");
 #endif
     return;
   }
The documentation for this class was generated from the following files:
src/physics/include/grins/boussinesq_buoyancy.h
src/physics/src/boussinesq_buoyancy.C