GRINS-0.7.0: GRINS::ElasticMembraneRayleighDamping< StressStrainLaw > Class Template Reference
GRINS::ElasticMembraneRayleighDamping< StressStrainLaw > Class Template Reference
#include <elastic_membrane_rayleigh_damping.h>
Public Member Functions
ElasticMembraneRayleighDamping (const PhysicsName &physics_name, const GetPot &input, bool is_compressible)
virtual ~ElasticMembraneRayleighDamping ()
virtual void damping_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for element interiors.
Public Member Functions inherited from GRINS::ElasticMembraneBase< StressStrainLaw >
ElasticMembraneBase (const GRINS::PhysicsName &physics_name, const GetPot &input, bool is_compressible)
virtual ~ElasticMembraneBase ()
virtual void init_variables (libMesh::FEMSystem *system)
Initialize variables for this physics.
Public Member Functions inherited from GRINS::ElasticMembraneAbstract
ElasticMembraneAbstract (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~ElasticMembraneAbstract ()
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
Public Member Functions inherited from GRINS::SolidMechanicsAbstract
SolidMechanicsAbstract (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~SolidMechanicsAbstract ()
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Set which variables are time evolving.
Public Member Functions inherited from GRINS::Physics
Physics (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~Physics ()
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for element interiors.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_damping_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
ICHandlingBase * get_ic_handler ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Attributes
libMesh::Real _lambda_factor
libMesh::Real _mu_factor
Protected Attributes inherited from GRINS::ElasticMembraneBase< StressStrainLaw >
StressStrainLaw _stress_strain_law
bool _is_compressible
libMesh::Real _h0
Membrane thickness.
libMesh::Real _rho
Membrane density.
VariableIndex _lambda_sq_var
Variable index for lambda_sq variable.
Protected Attributes inherited from GRINS::SolidMechanicsAbstract
DisplacementFEVariables _disp_vars
Protected Attributes inherited from GRINS::Physics
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
Private Member Functions
ElasticMembraneRayleighDamping ()
Additional Inherited Members
Static Public Member Functions inherited from GRINS::Physics
static void set_is_axisymmetric (bool is_axisymmetric)
Set whether we should treat the problem as axisymmetric.
static bool is_axisymmetric ()
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Types inherited from GRINS::SolidMechanicsAbstract
typedef const libMesh::DenseSubVector< libMesh::Number > &(libMesh::DiffContext::* VarFuncType) (unsigned int) const
typedef void(libMesh::FEMContext::* InteriorFuncType) (unsigned int, unsigned int, libMesh::Real &) const
typedef libMesh::Real(libMesh::DiffContext::* VarDerivType) () const
Protected Member Functions inherited from GRINS::ElasticMembraneBase< StressStrainLaw >
void mass_residual_impl (bool compute_jacobian, AssemblyContext &context, InteriorFuncType interior_solution, VarDerivType get_solution_deriv, libMesh::Real mu=1.0)
Implementation of mass_residual.
void compute_metric_tensors (unsigned int qp, const libMesh::FEBase &elem, const AssemblyContext &context, const libMesh::Gradient &grad_u, const libMesh::Gradient &grad_v, const libMesh::Gradient &grad_w, libMesh::TensorValue< libMesh::Real > &a_cov, libMesh::TensorValue< libMesh::Real > &a_contra, libMesh::TensorValue< libMesh::Real > &A_cov, libMesh::TensorValue< libMesh::Real > &A_contra, libMesh::Real &lambda_sq)
Protected Member Functions inherited from GRINS::ElasticMembraneAbstract
const libMesh::FEGenericBase< libMesh::Real > * get_fe (const AssemblyContext &context)
Protected Member Functions inherited from GRINS::Physics
libMesh::UniquePtr< libMesh::FEGenericBase< libMesh::Real > > build_new_fe (const libMesh::Elem *elem, const libMesh::FEGenericBase< libMesh::Real > *fe, const libMesh::Point p)
void parse_enabled_subdomains (const GetPot &input, const std::string &physics_name)
Static Protected Attributes inherited from GRINS::Physics
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
static bool _is_axisymmetric = false
Caches whether we are solving an axisymmetric problem or not.
Detailed Description
template<typename StressStrainLaw>
class GRINS::ElasticMembraneRayleighDamping< StressStrainLaw >
Definition at line 33 of file elastic_membrane_rayleigh_damping.h.
Constructor & Destructor Documentation
template<typename StressStrainLaw > GRINS::ElasticMembraneRayleighDamping< StressStrainLaw >::ElasticMembraneRayleighDamping (const PhysicsName & physics_name, const GetPot & input, bool is_compressible)
Definition at line 40 of file elastic_membrane_rayleigh_damping.C.
References GRINS::PhysicsNaming::elastic_membrane(), GRINS::PhysicsNaming::elastic_membrane_rayleigh_damping(), and GRINS::Physics::parse_enabled_subdomains().
     : ElasticMembraneBase<StressStrainLaw>(physics_name,input,is_compressible),
     _lambda_factor(input("Physics/"+PhysicsNaming::elastic_membrane_rayleigh_damping()+"/lambda_factor",0.0)),
     _mu_factor(input("Physics/"+PhysicsNaming::elastic_membrane_rayleigh_damping()+"/mu_factor",0.0))
   {
     if( !input.have_variable("Physics/"+PhysicsNaming::elastic_membrane_rayleigh_damping()+"/lambda_factor") )
       libmesh_error_msg("ERROR: Couldn't find Physics/"+PhysicsNaming::elastic_membrane_rayleigh_damping()+"/lambda_factor in input!");
     if( !input.have_variable("Physics/"+PhysicsNaming::elastic_membrane_rayleigh_damping()+"/mu_factor") )
       libmesh_error_msg("ERROR: Couldn't find Physics/"+PhysicsNaming::elastic_membrane_rayleigh_damping()+"/mu_factor in input!");
     // If the user specified enabled subdomains in this Physics section,
     // that's an error; we're slave to ElasticMembrane.
     if( input.have_variable("Physics/"+PhysicsNaming::elastic_membrane_rayleigh_damping()+"/enabled_subdomains" ) )
       libmesh_error_msg("ERROR: Cannot specify subdomains for "
                         +PhysicsNaming::elastic_membrane_rayleigh_damping()
                         +"! Must specify subdomains through "
                         +PhysicsNaming::elastic_membrane()+".");
     this->parse_enabled_subdomains(input,PhysicsNaming::elastic_membrane());
   }
template<typename StressStrainLaw > virtual GRINS::ElasticMembraneRayleighDamping< StressStrainLaw >::~ElasticMembraneRayleighDamping () inline virtual
Definition at line 41 of file elastic_membrane_rayleigh_damping.h.
 {};
template<typename StressStrainLaw > GRINS::ElasticMembraneRayleighDamping< StressStrainLaw >::ElasticMembraneRayleighDamping () private
Member Function Documentation
template<typename StressStrainLaw > void GRINS::ElasticMembraneRayleighDamping< StressStrainLaw >::damping_residual (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Time dependent part(s) of physics for element interiors.
Reimplemented from GRINS::Physics.
Definition at line 65 of file elastic_membrane_rayleigh_damping.C.
   {
     // First do the mass part
     this->mass_residual_impl(compute_jacobian,
                                context,
                                &libMesh::FEMContext::interior_rate,
                                &libMesh::DiffContext::get_elem_solution_rate_derivative,
                                _mu_factor);
     // Now do the stiffness part
     const unsigned int n_u_dofs = context.get_dof_indices(this->_disp_vars.u()).size();
     const std::vector<libMesh::Real> &JxW =
       this->get_fe(context)->get_JxW();
     // Residuals that we're populating
     libMesh::DenseSubVector<libMesh::Number> &Fu = context.get_elem_residual(this->_disp_vars.u());
     libMesh::DenseSubVector<libMesh::Number> &Fv = context.get_elem_residual(this->_disp_vars.v());
     libMesh::DenseSubVector<libMesh::Number> &Fw = context.get_elem_residual(this->_disp_vars.w());
     libMesh::DenseSubMatrix<libMesh::Number>& Kuu = context.get_elem_jacobian(this->_disp_vars.u(),this->_disp_vars.u());
     libMesh::DenseSubMatrix<libMesh::Number>& Kuv = context.get_elem_jacobian(this->_disp_vars.u(),this->_disp_vars.v());
     libMesh::DenseSubMatrix<libMesh::Number>& Kuw = context.get_elem_jacobian(this->_disp_vars.u(),this->_disp_vars.w());
     libMesh::DenseSubMatrix<libMesh::Number>& Kvu = context.get_elem_jacobian(this->_disp_vars.v(),this->_disp_vars.u());
     libMesh::DenseSubMatrix<libMesh::Number>& Kvv = context.get_elem_jacobian(this->_disp_vars.v(),this->_disp_vars.v());
     libMesh::DenseSubMatrix<libMesh::Number>& Kvw = context.get_elem_jacobian(this->_disp_vars.v(),this->_disp_vars.w());
     libMesh::DenseSubMatrix<libMesh::Number>& Kwu = context.get_elem_jacobian(this->_disp_vars.w(),this->_disp_vars.u());
     libMesh::DenseSubMatrix<libMesh::Number>& Kwv = context.get_elem_jacobian(this->_disp_vars.w(),this->_disp_vars.v());
     libMesh::DenseSubMatrix<libMesh::Number>& Kww = context.get_elem_jacobian(this->_disp_vars.w(),this->_disp_vars.w());
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     // All shape function gradients are w.r.t. master element coordinates
     const std::vector<std::vector<libMesh::Real> >& dphi_dxi =
       this->get_fe(context)->get_dphidxi();
     const std::vector<std::vector<libMesh::Real> >& dphi_deta =
       this->get_fe(context)->get_dphideta();
     const libMesh::DenseSubVector<libMesh::Number>& u_coeffs = context.get_elem_solution( this->_disp_vars.u() );
     const libMesh::DenseSubVector<libMesh::Number>& v_coeffs = context.get_elem_solution( this->_disp_vars.v() );
     const libMesh::DenseSubVector<libMesh::Number>& w_coeffs = context.get_elem_solution( this->_disp_vars.w() );
     const libMesh::DenseSubVector<libMesh::Number>& dudt_coeffs = context.get_elem_solution_rate( this->_disp_vars.u() );
     const libMesh::DenseSubVector<libMesh::Number>& dvdt_coeffs = context.get_elem_solution_rate( this->_disp_vars.v() );
     const libMesh::DenseSubVector<libMesh::Number>& dwdt_coeffs = context.get_elem_solution_rate( this->_disp_vars.w() );
     // Need these to build up the covariant and contravariant metric tensors
     const std::vector<libMesh::RealGradient>& dxdxi  = this->get_fe(context)->get_dxyzdxi();
     const std::vector<libMesh::RealGradient>& dxdeta = this->get_fe(context)->get_dxyzdeta();
     const unsigned int dim = 2; // The manifold dimension is always 2 for this physics
     for (unsigned int qp=0; qp != n_qpoints; qp++)
       {
         // Gradients are w.r.t. master element coordinates
         libMesh::Gradient grad_u, grad_v, grad_w;
         libMesh::Gradient dgradu_dt, dgradv_dt, dgradw_dt;
         for( unsigned int d = 0; d < n_u_dofs; d++ )
           {
             libMesh::RealGradient u_gradphi( dphi_dxi[d][qp], dphi_deta[d][qp] );
             grad_u += u_coeffs(d)*u_gradphi;
             grad_v += v_coeffs(d)*u_gradphi;
             grad_w += w_coeffs(d)*u_gradphi;
             dgradu_dt += dudt_coeffs(d)*u_gradphi;
             dgradv_dt += dvdt_coeffs(d)*u_gradphi;
             dgradw_dt += dwdt_coeffs(d)*u_gradphi;
           }
         libMesh::RealGradient grad_x( dxdxi[qp](0), dxdeta[qp](0) );
         libMesh::RealGradient grad_y( dxdxi[qp](1), dxdeta[qp](1) );
         libMesh::RealGradient grad_z( dxdxi[qp](2), dxdeta[qp](2) );
         libMesh::TensorValue<libMesh::Real> a_cov, a_contra, A_cov, A_contra;
         libMesh::Real lambda_sq = 0;
         this->compute_metric_tensors( qp, *(this->get_fe(context)), context,
                                       grad_u, grad_v, grad_w,
                                       a_cov, a_contra, A_cov, A_contra,
                                       lambda_sq );
         // Compute stress and elasticity tensors
         libMesh::TensorValue<libMesh::Real> tau;
         ElasticityTensor C;
         this->_stress_strain_law.compute_stress_and_elasticity(dim,a_contra,a_cov,A_contra,A_cov,tau,C);
         libMesh::Real jac = JxW[qp];
         for (unsigned int i=0; i != n_u_dofs; i++)
           {
             libMesh::RealGradient u_gradphi( dphi_dxi[i][qp], dphi_deta[i][qp] );
             for( unsigned int alpha = 0; alpha < dim; alpha++ )
               {
                 for( unsigned int beta = 0; beta < dim; beta++ )
                   {
                     const libMesh::Real common_factor = _lambda_factor*0.5*this->_h0*jac;
                     const libMesh::Real factor = common_factor*tau(alpha,beta);
                     libMesh::Real u_diagterm = dgradu_dt(beta)*u_gradphi(alpha) + dgradu_dt(alpha)*u_gradphi(beta);
                     libMesh::Real v_diagterm = dgradv_dt(beta)*u_gradphi(alpha) + dgradv_dt(alpha)*u_gradphi(beta);
                     libMesh::Real w_diagterm = dgradw_dt(beta)*u_gradphi(alpha) + dgradw_dt(alpha)*u_gradphi(beta);
                     Fu(i) += factor*u_diagterm;
                     Fv(i) += factor*v_diagterm;
                     Fw(i) += factor*w_diagterm;
                     for( unsigned int lambda = 0; lambda < dim; lambda++ )
                       {
                         for( unsigned int mu = 0; mu < dim; mu++ )
{
                             const libMesh::Real C1 = common_factor*C(alpha,beta,lambda,mu);
                             const libMesh::Real gamma_u = 0.5*( dgradu_dt(lambda)*(grad_x(mu)+grad_u(mu)) +
                                                                 (grad_x(lambda)+grad_u(lambda))*dgradu_dt(mu) );
                             const libMesh::Real gamma_v = 0.5*( dgradv_dt(lambda)*(grad_y(mu)+grad_v(mu)) +
                                                                 (grad_y(lambda)+grad_v(lambda))*dgradv_dt(mu) );
                             const libMesh::Real gamma_w = 0.5*( dgradw_dt(lambda)*(grad_z(mu)+grad_w(mu)) +
                                                                 (grad_z(lambda)+grad_w(lambda))*dgradw_dt(mu) );
                             const libMesh::Real x_term = C1*( (grad_x(beta)+grad_u(beta))*u_gradphi(alpha) +
                                                               (grad_x(alpha)+grad_u(alpha))*u_gradphi(beta) );
                             const libMesh::Real y_term = C1*( (grad_y(beta)+grad_v(beta))*u_gradphi(alpha) +
                                                               (grad_y(alpha)+grad_v(alpha))*u_gradphi(beta) );
                             const libMesh::Real z_term = C1*( (grad_z(beta)+grad_w(beta))*u_gradphi(alpha) +
                                                               (grad_z(alpha)+grad_w(alpha))*u_gradphi(beta) );
                             const libMesh::Real gamma_sum = gamma_u + gamma_v + gamma_w;
                             Fu(i) += x_term*gamma_sum;
                             Fv(i) += y_term*gamma_sum;
                             Fw(i) += z_term*gamma_sum;
                           }
                       }
                   }
               }
           }
         if( compute_jacobian )
           {
             for (unsigned int i=0; i != n_u_dofs; i++)
               {
                 libMesh::RealGradient u_gradphi_i( dphi_dxi[i][qp], dphi_deta[i][qp] );
                 for (unsigned int j=0; j != n_u_dofs; j++)
                   {
                     libMesh::RealGradient u_gradphi_j( dphi_dxi[j][qp], dphi_deta[j][qp] );
                     for( unsigned int alpha = 0; alpha < dim; alpha++ )
                       {
                         for( unsigned int beta = 0; beta < dim; beta++ )
{
                             const libMesh::Real common_factor = _lambda_factor*0.5*this->_h0*jac;
                             libMesh::Real u_diagterm = dgradu_dt(beta)*u_gradphi_i(alpha) + dgradu_dt(alpha)*u_gradphi_i(beta);
                             libMesh::Real v_diagterm = dgradv_dt(beta)*u_gradphi_i(alpha) + dgradv_dt(alpha)*u_gradphi_i(beta);
                             libMesh::Real w_diagterm = dgradw_dt(beta)*u_gradphi_i(alpha) + dgradw_dt(alpha)*u_gradphi_i(beta);
                             const libMesh::Real factor = common_factor*tau(alpha,beta);
                             const libMesh::Real ddiagterm = u_gradphi_j(beta)*u_gradphi_i(alpha) + u_gradphi_j(alpha)*u_gradphi_i(beta);
                             Kuu(i,j) += factor*ddiagterm*context.get_elem_solution_rate_derivative();
                             Kvv(i,j) += factor*ddiagterm*context.get_elem_solution_rate_derivative();
                             Kww(i,j) += factor*ddiagterm*context.get_elem_solution_rate_derivative();
                             for( unsigned int lambda = 0; lambda < dim; lambda++ )
{
                                 for( unsigned int mu = 0; mu < dim; mu++ )
{
                                     const libMesh::Real dgamma_du = 0.5*( u_gradphi_j(lambda)*(grad_x(mu)+grad_u(mu)) +
                                                                           (grad_x(lambda)+grad_u(lambda))*u_gradphi_j(mu) );
                                     const libMesh::Real dgamma_dv = 0.5*( u_gradphi_j(lambda)*(grad_y(mu)+grad_v(mu)) +
                                                                           (grad_y(lambda)+grad_v(lambda))*u_gradphi_j(mu) );
                                     const libMesh::Real dgamma_dw = 0.5*( u_gradphi_j(lambda)*(grad_z(mu)+grad_w(mu)) +
                                                                           (grad_z(lambda)+grad_w(lambda))*u_gradphi_j(mu) );
                                     const libMesh::Real C1 = common_factor*C(alpha,beta,lambda,mu);
                                     const libMesh::Real dfactor_du = C1*dgamma_du*context.get_elem_solution_derivative();
                                     const libMesh::Real dfactor_dv = C1*dgamma_dv*context.get_elem_solution_derivative();
                                     const libMesh::Real dfactor_dw = C1*dgamma_dw*context.get_elem_solution_derivative();
                                     Kuu(i,j) += u_diagterm*dfactor_du;
                                     Kuv(i,j) += u_diagterm*dfactor_dv;
                                     Kuw(i,j) += u_diagterm*dfactor_dw;
                                     Kvu(i,j) += v_diagterm*dfactor_du;
                                     Kvv(i,j) += v_diagterm*dfactor_dv;
                                     Kvw(i,j) += v_diagterm*dfactor_dw;
                                     Kwu(i,j) += w_diagterm*dfactor_du;
                                     Kwv(i,j) += w_diagterm*dfactor_dv;
                                     Kww(i,j) += w_diagterm*dfactor_dw;
                                     const libMesh::Real gamma_u = 0.5*( dgradu_dt(lambda)*(grad_x(mu)+grad_u(mu)) +
                                                                         (grad_x(lambda)+grad_u(lambda))*dgradu_dt(mu) );
                                     const libMesh::Real gamma_v = 0.5*( dgradv_dt(lambda)*(grad_y(mu)+grad_v(mu)) +
                                                                         (grad_y(lambda)+grad_v(lambda))*dgradv_dt(mu) );
                                     const libMesh::Real gamma_w = 0.5*( dgradw_dt(lambda)*(grad_z(mu)+grad_w(mu)) +
                                                                         (grad_z(lambda)+grad_w(lambda))*dgradw_dt(mu) );
                                     const libMesh::Real x_term = C1*( (grad_x(beta)+grad_u(beta))*u_gradphi_i(alpha) +
                                                                       (grad_x(alpha)+grad_u(alpha))*u_gradphi_i(beta) );
                                     const libMesh::Real y_term = C1*( (grad_y(beta)+grad_v(beta))*u_gradphi_i(alpha) +
                                                                       (grad_y(alpha)+grad_v(alpha))*u_gradphi_i(beta) );
                                     const libMesh::Real z_term = C1*( (grad_z(beta)+grad_w(beta))*u_gradphi_i(alpha) +
                                                                       (grad_z(alpha)+grad_w(alpha))*u_gradphi_i(beta) );
                                     const libMesh::Real gamma_sum = gamma_u + gamma_v + gamma_w;
                                     // Here, we're missing derivatives of C(alpha,beta,lambda,mu) w.r.t. strain
                                     // Nonzero for hyperelasticity models
                                     const libMesh::Real dxterm_du = C1*(  u_gradphi_j(beta)*u_gradphi_i(alpha)
                                                                         + u_gradphi_j(alpha)*u_gradphi_i(beta) )*context.get_elem_solution_derivative();
                                     const libMesh::Real dyterm_dv = dxterm_du;
                                     const libMesh::Real dzterm_dw = dxterm_du;
                                     Kuu(i,j) += gamma_sum*dxterm_du;
                                     Kvv(i,j) += gamma_sum*dyterm_dv;
                                     Kww(i,j) += gamma_sum*dzterm_dw;
                                     const libMesh::Real dgamma_sum_du = 0.5*(   u_gradphi_j(lambda)*(grad_x(mu)+grad_u(mu))*context.get_elem_solution_rate_derivative()
                                                                               + dgradu_dt(lambda)*u_gradphi_j(mu)*context.get_elem_solution_derivative()
                                                                               + u_gradphi_j(mu)*(grad_x(lambda)+grad_u(lambda))*context.get_elem_solution_rate_derivative()
                                                                               + dgradu_dt(mu)*u_gradphi_j(lambda)*context.get_elem_solution_derivative() );
                                     const libMesh::Real dgamma_sum_dv = 0.5*(   u_gradphi_j(lambda)*(grad_y(mu)+grad_v(mu))*context.get_elem_solution_rate_derivative()
                                                                               + dgradv_dt(lambda)*u_gradphi_j(mu)*context.get_elem_solution_derivative()
                                                                               + u_gradphi_j(mu)*(grad_y(lambda)+grad_v(lambda))*context.get_elem_solution_rate_derivative()
                                                                               + dgradv_dt(mu)*u_gradphi_j(lambda)*context.get_elem_solution_derivative() );
                                     const libMesh::Real dgamma_sum_dw = 0.5*(   u_gradphi_j(lambda)*(grad_z(mu)+grad_w(mu))*context.get_elem_solution_rate_derivative()
                                                                               + dgradw_dt(lambda)*u_gradphi_j(mu)*context.get_elem_solution_derivative()
                                                                               + u_gradphi_j(mu)*(grad_z(lambda)+grad_w(lambda))*context.get_elem_solution_rate_derivative()
                                                                               + dgradw_dt(mu)*u_gradphi_j(lambda)*context.get_elem_solution_derivative() );
                                     Kuu(i,j) += x_term*dgamma_sum_du;
                                     Kuv(i,j) += x_term*dgamma_sum_dv;
                                     Kuw(i,j) += x_term*dgamma_sum_dw;
                                     Kvu(i,j) += y_term*dgamma_sum_du;
                                     Kvv(i,j) += y_term*dgamma_sum_dv;
                                     Kvw(i,j) += y_term*dgamma_sum_dw;
                                     Kwu(i,j) += z_term*dgamma_sum_du;
                                     Kwv(i,j) += z_term*dgamma_sum_dv;
                                     Kww(i,j) += z_term*dgamma_sum_dw;
                                   }
                               }
                           }
                       }
                   }
               }
           }
       }
   }
Member Data Documentation
template<typename StressStrainLaw > libMesh::Real GRINS::ElasticMembraneRayleighDamping< StressStrainLaw >::_lambda_factor protected
Definition at line 50 of file elastic_membrane_rayleigh_damping.h.
template<typename StressStrainLaw > libMesh::Real GRINS::ElasticMembraneRayleighDamping< StressStrainLaw >::_mu_factor protected
Definition at line 51 of file elastic_membrane_rayleigh_damping.h.
The documentation for this class was generated from the following files:
src/physics/include/grins/elastic_membrane_rayleigh_damping.h
src/physics/src/elastic_membrane_rayleigh_damping.C