GRINS-0.7.0: GRINS::IncompressibleNavierStokesBase< Viscosity > Class Template Reference
GRINS::IncompressibleNavierStokesBase< Viscosity > Class Template Reference
Physics class for Incompressible Navier-Stokes.
#include <inc_navier_stokes_base.h>
Public Member Functions
IncompressibleNavierStokesBase (const std::string &my_physics_name, const std::string &core_physics_name, const GetPot &input)
~IncompressibleNavierStokesBase ()
virtual void init_variables (libMesh::FEMSystem *system)
Initialization of Navier-Stokes variables.
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Sets velocity variables to be time-evolving.
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
libMesh::Real get_viscosity_value (AssemblyContext &context, unsigned int qp) const
Public Member Functions inherited from GRINS::Physics
Physics (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~Physics ()
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for element interiors.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void damping_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Damping matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_damping_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
ICHandlingBase * get_ic_handler ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
Protected Attributes
unsigned int _dim
Physical dimension of problem.
VelocityFEVariables _flow_vars
PressureFEVariable _press_var
libMesh::Number _rho
Material parameters, read from input.
Viscosity _mu
Viscosity object.
Protected Attributes inherited from GRINS::Physics
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
Private Member Functions
IncompressibleNavierStokesBase ()
void register_variables ()
Additional Inherited Members
Static Public Member Functions inherited from GRINS::Physics
static void set_is_axisymmetric (bool is_axisymmetric)
Set whether we should treat the problem as axisymmetric.
static bool is_axisymmetric ()
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Member Functions inherited from GRINS::Physics
libMesh::UniquePtr< libMesh::FEGenericBase< libMesh::Real > > build_new_fe (const libMesh::Elem *elem, const libMesh::FEGenericBase< libMesh::Real > *fe, const libMesh::Point p)
void parse_enabled_subdomains (const GetPot &input, const std::string &physics_name)
Static Protected Attributes inherited from GRINS::Physics
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
static bool _is_axisymmetric = false
Caches whether we are solving an axisymmetric problem or not.
Detailed Description
template<class Viscosity>
class GRINS::IncompressibleNavierStokesBase< Viscosity >
Physics class for Incompressible Navier-Stokes.
This physics class implements the classical Incompressible Navier-Stokes equations. This is a templated class, the class Viscosity can be instantiated as a specific type (right now:ConstantViscosity or SpatiallyVaryingViscosity) to allow the user to specify a constant or spatially varying viscosity in the input file
Definition at line 45 of file inc_navier_stokes_base.h.
Constructor & Destructor Documentation
template<class Mu > GRINS::IncompressibleNavierStokesBase< Mu >::IncompressibleNavierStokesBase (const std::string & my_physics_name, const std::string & core_physics_name, const GetPot & input)
Definition at line 47 of file inc_navier_stokes_base.C.
References GRINS::IncompressibleNavierStokesBase< Viscosity >::_rho, GRINS::MaterialsParsing::read_density(), and GRINS::IncompressibleNavierStokesBase< Viscosity >::register_variables().
     : Physics(my_physics_name, input),
       _flow_vars(input, core_physics_name),
       _press_var(input, core_physics_name, true /*is_constraint_var*/),
       _rho(0.0),
       _mu(input,MaterialsParsing::material_name(input,core_physics_name))
   {
     MaterialsParsing::read_density( core_physics_name, input, (*this), this->_rho );
     this->register_variables();
   }
template<class Viscosity > GRINS::IncompressibleNavierStokesBase< Viscosity >::~IncompressibleNavierStokesBase () inline
Definition at line 53 of file inc_navier_stokes_base.h.
 {};
template<class Viscosity > GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase () private
Member Function Documentation
template<class Mu > libMesh::Real GRINS::IncompressibleNavierStokesBase< Mu >::get_viscosity_value (AssemblyContext & context, unsigned int qp) const
Definition at line 83 of file inc_navier_stokes_base.C.
   {
     return this->_mu(context, qp);
   }
template<class Mu > void GRINS::IncompressibleNavierStokesBase< Mu >::init_context (AssemblyContext & context) virtual
Initialize context for added physics variables.
Reimplemented from GRINS::Physics.
Reimplemented in GRINS::AveragedFan< Viscosity >, GRINS::AveragedTurbine< Viscosity >, GRINS::VelocityDrag< Viscosity >, GRINS::ParsedVelocitySource< Viscosity >, GRINS::VelocityPenalty< Viscosity >, GRINS::AveragedTurbineAdjointStabilization< Viscosity >, GRINS::VelocityDragAdjointStabilization< Viscosity >, GRINS::AveragedFanAdjointStabilization< Viscosity >, GRINS::ParsedVelocitySourceAdjointStabilization< Viscosity >, GRINS::VelocityPenaltyAdjointStabilization< Viscosity >, and GRINS::IncompressibleNavierStokesStabilizationBase< Viscosity >.
Definition at line 105 of file inc_navier_stokes_base.C.
Referenced by GRINS::IncompressibleNavierStokesStabilizationBase< Viscosity >::init_context().
   {
     // We should prerequest all the data
     // we will need to build the linear system
     // or evaluate a quantity of interest.
     context.get_element_fe(_flow_vars.u())->get_JxW();
     context.get_element_fe(_flow_vars.u())->get_phi();
     context.get_element_fe(_flow_vars.u())->get_dphi();
     context.get_element_fe(_flow_vars.u())->get_xyz();
     context.get_element_fe(_press_var.p())->get_phi();
     context.get_element_fe(_press_var.p())->get_xyz();
     context.get_side_fe(_flow_vars.u())->get_JxW();
     context.get_side_fe(_flow_vars.u())->get_phi();
     context.get_side_fe(_flow_vars.u())->get_dphi();
     context.get_side_fe(_flow_vars.u())->get_xyz();
     return;
   }
template<class Mu > void GRINS::IncompressibleNavierStokesBase< Mu >::init_variables (libMesh::FEMSystem * system) virtual
Initialization of Navier-Stokes variables.
Add velocity and pressure variables to system.
Implements GRINS::Physics.
Reimplemented in GRINS::AveragedTurbineBase< Viscosity >.
Definition at line 70 of file inc_navier_stokes_base.C.
Referenced by GRINS::AveragedTurbineBase< Viscosity >::init_variables().
   {
     this->_dim = system->get_mesh().mesh_dimension();
     this->_flow_vars.init(system);
     this->_press_var.init(system);
     this->_mu.init(system);
     return;
   }
template<class Mu > void GRINS::IncompressibleNavierStokesBase< Mu >::register_parameter (const std::string & param_name, libMesh::ParameterMultiAccessor< libMesh::Number > & param_pointer) const virtual
Each subclass will register its copy of an independent.
Reimplemented from GRINS::ParameterUser.
Definition at line 128 of file inc_navier_stokes_base.C.
References GRINS::ParameterUser::register_parameter().
   {
     ParameterUser::register_parameter(param_name, param_pointer);
     _mu.register_parameter(param_name, param_pointer);
   }
template<class Mu > void GRINS::IncompressibleNavierStokesBase< Mu >::register_variables () private
Definition at line 61 of file inc_navier_stokes_base.C.
References GRINS::GRINSPrivate::VariableWarehouse::check_and_register_variable(), GRINS::VariablesParsing::pressure_section(), and GRINS::VariablesParsing::velocity_section().
Referenced by GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase().
   {
     GRINSPrivate::VariableWarehouse::check_and_register_variable(VariablesParsing::pressure_section(),
                                                                  this->_press_var);
     GRINSPrivate::VariableWarehouse::check_and_register_variable(VariablesParsing::velocity_section(),
                                                                  this->_flow_vars);
   }
template<class Mu > void GRINS::IncompressibleNavierStokesBase< Mu >::set_time_evolving_vars (libMesh::FEMSystem * system) virtual
Sets velocity variables to be time-evolving.
Reimplemented from GRINS::Physics.
Reimplemented in GRINS::AveragedTurbineBase< Viscosity >, GRINS::VelocityPenaltyBase< Viscosity >, and GRINS::ParsedVelocitySourceBase< Viscosity >.
Definition at line 89 of file inc_navier_stokes_base.C.
Referenced by GRINS::AveragedTurbineBase< Viscosity >::set_time_evolving_vars().
   {
     const unsigned int dim = system->get_mesh().mesh_dimension();
     // Tell the system to march velocity forward in time, but
     // leave p as a constraint only
     system->time_evolving(_flow_vars.u());
     system->time_evolving(_flow_vars.v());
     if (dim == 3)
       system->time_evolving(_flow_vars.w());
     return;
   }
Member Data Documentation
template<class Viscosity > unsigned int GRINS::IncompressibleNavierStokesBase< Viscosity >::_dim protected
Physical dimension of problem.
Todo:
Do we really need to cache this?
Definition at line 81 of file inc_navier_stokes_base.h.
template<class Viscosity > VelocityFEVariables GRINS::IncompressibleNavierStokesBase< Viscosity >::_flow_vars protected
Definition at line 83 of file inc_navier_stokes_base.h.
template<class Viscosity > Viscosity GRINS::IncompressibleNavierStokesBase< Viscosity >::_mu protected
Viscosity object.
Definition at line 90 of file inc_navier_stokes_base.h.
template<class Viscosity > PressureFEVariable GRINS::IncompressibleNavierStokesBase< Viscosity >::_press_var protected
Definition at line 84 of file inc_navier_stokes_base.h.
template<class Viscosity > libMesh::Number GRINS::IncompressibleNavierStokesBase< Viscosity >::_rho protected
Material parameters, read from input.
Todo:
Create objects to allow for function specification
Definition at line 87 of file inc_navier_stokes_base.h.
Referenced by GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase().
The documentation for this class was generated from the following files:
src/physics/include/grins/inc_navier_stokes_base.h
src/physics/src/inc_navier_stokes_base.C