GRINS-0.7.0: GRINS::CatalyticWallBase< Chemistry > Class Template Reference
GRINS::CatalyticWallBase< Chemistry > Class Template Reference abstract
#include <catalytic_wall_base.h>
Public Member Functions
CatalyticWallBase (SharedPtr< Chemistry > &chem, SharedPtr< CatalycityBase > &gamma, const std::vector< VariableIndex > &species_vars, VariableIndex T_var, libMesh::Real p0, unsigned int reactant_species_idx)
CatalyticWallBase (const Chemistry &chem_mixture, CatalycityBase &gamma, const unsigned int reactant_species_idx)
Deprecated.
virtual ~CatalyticWallBase ()
virtual void apply_fluxes (AssemblyContext &context, const CachedValues &cache, const bool request_jacobian)=0
Deprecated.
virtual void init (const libMesh::FEMSystem &)
libMesh::Real rho (libMesh::Real T, libMesh::Real p0, libMesh::Real R_mix) const
libMesh::Real omega_dot (const libMesh::Real rho_s, const libMesh::Real T) const
libMesh::Real domega_dot_dws (const libMesh::Real rho_s, const libMesh::Real w_s, const libMesh::Real T, const libMesh::Real R) const
libMesh::Real domega_dot_dT (const libMesh::Real rho_s, const libMesh::Real T) const
void set_catalycity_params (const std::vector< libMesh::Real > &params)
Public Member Functions inherited from GRINS::NeumannBCAbstract
NeumannBCAbstract ()
virtual ~NeumannBCAbstract ()
virtual bool eval_flux (bool compute_jacobian, AssemblyContext &context, libMesh::Real sign, bool is_axisymmetric)=0
Protected Member Functions
libMesh::Real eval_gamma (libMesh::Real T) const
Temporary helper to deal with intermediate refactoring.
libMesh::Real eval_gamma_dT (libMesh::Real T) const
Temporary helper to deal with intermediate refactoring.
Protected Attributes
SharedPtr< Chemistry > _chem_ptr
const Chemistry & _chemistry
Deprecated.
SharedPtr< CatalycityBase > _gamma_ptr
libMesh::UniquePtr< CatalycityBase > _gamma_s
Deprecated.
const libMesh::Real _C
std::vector< VariableIndex > _species_vars
VariableIndex _T_var
libMesh::Real _p0
Thermodynamic pressure.
Detailed Description
template<typename Chemistry>
class GRINS::CatalyticWallBase< Chemistry >
Definition at line 50 of file catalytic_wall_base.h.
Constructor & Destructor Documentation
template<typename Chemistry > GRINS::CatalyticWallBase< Chemistry >::CatalyticWallBase (SharedPtr< Chemistry > & chem, SharedPtr< CatalycityBase > & gamma, const std::vector< VariableIndex > & species_vars, VariableIndex T_var, libMesh::Real p0, unsigned int reactant_species_idx)
Definition at line 39 of file catalytic_wall_base.C.
   : _chem_ptr(chem),
     _chemistry(*(chem.get())),// This will be removed after NeumannBC refactoring
     _gamma_ptr(gamma),
     _C( std::sqrt( chem->R(reactant_species_idx)/(GRINS::Constants::two_pi) ) ),
     _species_vars(species_vars),
     _T_var(T_var),
     _p0(p0)
   {}
template<typename Chemistry > GRINS::CatalyticWallBase< Chemistry >::CatalyticWallBase (const Chemistry & chem_mixture, CatalycityBase & gamma, const unsigned int reactant_species_idx)
Deprecated.
Definition at line 55 of file catalytic_wall_base.C.
     : _chemistry(chemistry),
       _gamma_s( gamma.clone() ),
       _C( std::sqrt( chemistry.R(reactant_species_idx)/(GRINS::Constants::two_pi) ) )
   {}
template<typename Chemistry > virtual GRINS::CatalyticWallBase< Chemistry >::~CatalyticWallBase () inline virtual
Definition at line 66 of file catalytic_wall_base.h.
 {};
Member Function Documentation
template<typename Chemistry > virtual void GRINS::CatalyticWallBase< Chemistry >::apply_fluxes (AssemblyContext & context, const CachedValues & cache, const bool request_jacobian) pure virtual
Deprecated.
Implemented in GRINS::GasSolidCatalyticWall< Chemistry >, and GRINS::GasRecombinationCatalyticWall< Chemistry >.
template<typename Chemistry > libMesh::Real GRINS::CatalyticWallBase< Chemistry >::domega_dot_dT (const libMesh::Real rho_s, const libMesh::Real T) const inline
Definition at line 179 of file catalytic_wall_base.h.
Referenced by test().
   {
     libMesh::Real sqrtT = std::sqrt(T);
     return rho_s*_C*( 0.5/sqrtT*this->eval_gamma(T) + sqrtT*this->eval_gamma_dT(T) );
   }
template<typename Chemistry > libMesh::Real GRINS::CatalyticWallBase< Chemistry >::domega_dot_dws (const libMesh::Real rho_s, const libMesh::Real w_s, const libMesh::Real T, const libMesh::Real R) const inline
Definition at line 171 of file catalytic_wall_base.h.
Referenced by test().
   {
     return (1.0/w_s - rho_s/R)*(this->omega_dot( rho_s, T ));
   }
template<typename Chemistry > libMesh::Real GRINS::CatalyticWallBase< Chemistry >::eval_gamma (libMesh::Real T) const inline protected
Temporary helper to deal with intermediate refactoring.
Definition at line 132 of file catalytic_wall_base.h.
   {
     libMesh::Real value;
     if(_gamma_s)
       value = (*_gamma_s)(T);
     else if(_gamma_ptr)
       value = (*_gamma_ptr)(T);
     else
       libmesh_error();
     return value;
   }
template<typename Chemistry > libMesh::Real GRINS::CatalyticWallBase< Chemistry >::eval_gamma_dT (libMesh::Real T) const inline protected
Temporary helper to deal with intermediate refactoring.
Definition at line 148 of file catalytic_wall_base.h.
   {
     libMesh::Real value;
     if(_gamma_s)
       value = (*_gamma_s).dT(T);
     else if(_gamma_ptr)
       value = (*_gamma_ptr).dT(T);
     else
       libmesh_error();
     return value;
   }
template<typename Chemistry > virtual void GRINS::CatalyticWallBase< Chemistry >::init (const libMesh::FEMSystem &) inline virtual
Reimplemented in GRINS::GasSolidCatalyticWall< Chemistry >, and GRINS::GasRecombinationCatalyticWall< Chemistry >.
Definition at line 73 of file catalytic_wall_base.h.
 {};
template<typename Chemistry > libMesh::Real GRINS::CatalyticWallBase< Chemistry >::omega_dot (const libMesh::Real rho_s, const libMesh::Real T) const inline
Definition at line 164 of file catalytic_wall_base.h.
Referenced by test().
   {
     return rho_s*this->eval_gamma(T)*_C*std::sqrt(T);
   }
template<typename Chemistry > libMesh::Real GRINS::CatalyticWallBase< Chemistry >::rho (libMesh::Real T, libMesh::Real p0, libMesh::Real R_mix) const inline
Definition at line 125 of file catalytic_wall_base.h.
   {
     return p0/(R_mix*T);
   }
template<typename Chemistry > void GRINS::CatalyticWallBase< Chemistry >::set_catalycity_params (const std::vector< libMesh::Real > & params)
Definition at line 64 of file catalytic_wall_base.C.
   {
     if(_gamma_s)
       {
         libmesh_deprecated();
         _gamma_s->set_params( params );
       }
     else if( _gamma_ptr)
       _gamma_ptr->set_params( params );
     else
       libmesh_error();
   }
Member Data Documentation
template<typename Chemistry > const libMesh::Real GRINS::CatalyticWallBase< Chemistry >::_C protected
Definition at line 106 of file catalytic_wall_base.h.
template<typename Chemistry > SharedPtr<Chemistry> GRINS::CatalyticWallBase< Chemistry >::_chem_ptr protected
Definition at line 95 of file catalytic_wall_base.h.
template<typename Chemistry > const Chemistry& GRINS::CatalyticWallBase< Chemistry >::_chemistry protected
Deprecated.
Definition at line 98 of file catalytic_wall_base.h.
template<typename Chemistry > SharedPtr<CatalycityBase> GRINS::CatalyticWallBase< Chemistry >::_gamma_ptr protected
Definition at line 100 of file catalytic_wall_base.h.
template<typename Chemistry > libMesh::UniquePtr<CatalycityBase> GRINS::CatalyticWallBase< Chemistry >::_gamma_s protected
Deprecated.
Definition at line 103 of file catalytic_wall_base.h.
template<typename Chemistry > libMesh::Real GRINS::CatalyticWallBase< Chemistry >::_p0 protected
Thermodynamic pressure.
Currently, we assume that the thermodynamic pressure is constant. This is not true in cavity type systems.
Todo:
make const
Definition at line 119 of file catalytic_wall_base.h.
template<typename Chemistry > std::vector<VariableIndex> GRINS::CatalyticWallBase< Chemistry >::_species_vars protected
Todo:
make const
Definition at line 109 of file catalytic_wall_base.h.
template<typename Chemistry > VariableIndex GRINS::CatalyticWallBase< Chemistry >::_T_var protected
Todo:
make const
Definition at line 112 of file catalytic_wall_base.h.
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/catalytic_wall_base.h
src/boundary_conditions/src/catalytic_wall_base.C