GRINS-0.8.0: test/regression/3d_low_mach_jacobians.C File Reference
3d_low_mach_jacobians.C File Reference
#include "grins_config.h"
#include <iostream>
#include "grins/runner.h"
#include "libmesh/parallel.h"
Functions
libMesh::Real initial_values (const libMesh::Point &p, const libMesh::Parameters &params, const std::string &system_name, const std::string &unknown_name)
int main (int argc, char *argv[])
Function Documentation
libMesh::Real initial_values (const libMesh::Point & p, const libMesh::Parameters & params, const std::string & system_name, const std::string & unknown_name)
Definition at line 77 of file 3d_low_mach_jacobians.C.
Referenced by main().
 {
   libMesh::Real value = 0.0;
   if( unknown_name == "T" )
     value = params.get<libMesh::Real>("T_init");
   else if( unknown_name == "p0" )
     value = params.get<libMesh::Real>("p0_init");
   else
     value = 0.0;
   return value;
 }
int main (int argc, char * argv[])
Definition at line 40 of file 3d_low_mach_jacobians.C.
References GRINS::Simulation::get_equation_system(), GRINS::Runner::get_input_file(), GRINS::Runner::get_simulation(), GRINS::Runner::init(), initial_values(), and GRINS::Runner::run().
 {
   GRINS::Runner grins(argc,argv);
   grins.init();
   const GetPot & inputfile = grins.get_input_file();
   //FIXME: We need to move this to within the Simulation object somehow...
   std::string restart_file = inputfile( "restart-options/restart_file", "none" );
   if( restart_file == "none" )
     {
       GRINS::Simulation & sim = grins.get_simulation();
       // Asssign initial temperature value
       std::string system_name = inputfile( "screen-options/system_name", "GRINS" );
       GRINS::SharedPtr<libMesh::EquationSystems> es = sim.get_equation_system();
       const libMesh::System& system = es->get_system(system_name);
       libMesh::Parameters &params = es->parameters;
       libMesh::Real T_init = inputfile("Materials/TestMaterial/ReferenceTemperature/value", 0.0);
       libMesh::Real p0_init = inputfile("Materials/TestMaterial/ThermodynamicPressure/value", 0.0);
       libMesh::Real& dummy_T  = params.set<libMesh::Real>("T_init");
       dummy_T = T_init;
       libMesh::Real& dummy_p0 = params.set<libMesh::Real>("p0_init");
       dummy_p0 = p0_init;
       system.project_solution( initial_values, NULL, params );
     }
   grins.run();
   return 0;
 }