GRINS-0.8.0: src/apps/cantera_kinetic_rates.C File Reference
cantera_kinetic_rates.C File Reference
#include "grins_config.h"
#include <fstream>
#include <iomanip>
#include "grins/cantera_mixture.h"
#include "grins/cantera_kinetics.h"
#include "grins/materials_parsing.h"
#include "grins/physics_naming.h"
#include "libmesh/getpot.h"
#include "libmesh/libmesh_common.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 45 of file cantera_kinetic_rates.C.
References GRINS::MaterialsParsing::material_name(), GRINS::CanteraMixture::n_species(), GRINS::CanteraKinetics::omega_dot(), GRINS::PhysicsNaming::reacting_low_mach_navier_stokes(), and GRINS::CanteraMixture::species_name().
 {
   // Check command line count.
   if( argc < 2 )
     {
       // TODO: Need more consistent error handling.
       std::cerr << "Error: Must specify input file." << std::endl;
       exit(1);
     }
   GetPot input( argv[1] );
   GRINS::CanteraMixture mixture( input, GRINS::MaterialsParsing::material_name(input,GRINS::PhysicsNaming::reacting_low_mach_navier_stokes()) );
   GRINS::CanteraKinetics kinetics( mixture );
   libMesh::Real T0 = input( "Conditions/T0", 300.0 );
   libMesh::Real T1 = input( "Conditions/T1", 300.0 );
   libMesh::Real T_inc = input( "Conditions/T_increment", 100.0 );
   libMesh::Real rho = input( "Conditions/density", 1.0e-3 );
   const unsigned int n_species = mixture.n_species();
   std::vector<double> Y(n_species,0.0);
   for( unsigned int s = 0; s < n_species; s++ )
     {
       Y[s] = input( "Conditions/mass_fractions", 0.0, s );
     }
   std::vector<double> omega_dot(n_species,0.0);
   libMesh::Real T = T0;
   std::ofstream output;
   output.open( "omega_dot.dat", std::ios::trunc );
   output << "# Species names" << std::endl;
   for( unsigned int s = 0; s < n_species; s++ )
     {
       output << mixture.species_name( s ) << " ";
     }
   output << std::endl;
   output << "# T [K]                  omega_dot [kg/m^3-s]" << std::endl;
   output.close();
   while( T < T1 )
     {
       kinetics.omega_dot( T, rho, Y, omega_dot );
       output.open( "omega_dot.dat", std::ios::app );
       output << T << " ";
       for( unsigned int i = 0; i < n_species; i++ )
         {
           output << std::scientific << std::setprecision(16)
                  << omega_dot[i] << " ";
         }
       output << std::endl;
       output.close();
       T += T_inc;
     }
   return 0;
 }