GRINS-0.6.0: GRINS::ParsedInteriorQoI Class Reference
GRINS::ParsedInteriorQoI Class Reference
Parsed Interior QoI.
#include <parsed_interior_qoi.h>
Public Member Functions
ParsedInteriorQoI (const std::string &qoi_name)
Constructor.
virtual ~ParsedInteriorQoI ()
virtual QoIBase * clone () const
Required to provide clone (deep-copy) for adding QoI object to libMesh objects.
virtual bool assemble_on_interior () const
Does the QoI need an element interior assembly loop?
virtual bool assemble_on_sides () const
Does the QoI need a domain boundary assembly loop?
virtual void init (const GetPot &input, const MultiphysicsSystem &system)
Initialize local variables.
virtual void init_context (AssemblyContext &context)
virtual void element_qoi (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi value.
virtual void element_qoi_derivative (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi derivative with respect to the solution.
virtual void side_qoi (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi value on the domain boundary.
virtual void side_qoi_derivative (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi derivative with respect to the solution on the domain boundary.
virtual void parallel_op (const libMesh::Parallel::Communicator &communicator, libMesh::Number &sys_qoi, libMesh::Number &local_qoi)
Call the parallel operation for this QoI and cache the value.
virtual void thread_join (libMesh::Number &qoi, const libMesh::Number &other_qoi)
Call the operation to accumulate this QoI from multiple threads.
virtual void output_qoi (std::ostream &out) const
Basic output for computed QoI's.
libMesh::Number value () const
Returns the current QoI value.
const std::string & name () const
Returns the name of this QoI.
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiPointer< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Member Functions
ParsedInteriorQoI (const ParsedInteriorQoI &original)
Manual copy constructor due to the AutoPtr.
Protected Attributes
libMesh::AutoPtr< libMesh::FEMFunctionBase< libMesh::Number > > qoi_functional
std::string _qoi_name
libMesh::Number _qoi_value
Private Member Functions
ParsedInteriorQoI ()
User never call default constructor.
Detailed Description
Parsed Interior QoI.
This class implements a QoI that is an arbitrary integral of a parsed function on the interior of the domain.
Definition at line 43 of file parsed_interior_qoi.h.
Constructor & Destructor Documentation
GRINS::ParsedInteriorQoI::ParsedInteriorQoI (const std::string & qoi_name)
Constructor.
Constructor takes GetPot object to read any input options associated with this QoI
Definition at line 42 of file parsed_interior_qoi.C.
     : QoIBase(qoi_name) {}
GRINS::ParsedInteriorQoI::~ParsedInteriorQoI () virtual
Definition at line 52 of file parsed_interior_qoi.C.
 {}
GRINS::ParsedInteriorQoI::ParsedInteriorQoI (const ParsedInteriorQoI & original) protected
Manual copy constructor due to the AutoPtr.
Definition at line 45 of file parsed_interior_qoi.C.
References qoi_functional.
     : QoIBase(original.name())
   {
     if (original.qoi_functional.get())
       this->qoi_functional = original.qoi_functional->clone();
   }
GRINS::ParsedInteriorQoI::ParsedInteriorQoI () private
User never call default constructor.
Referenced by clone().
Member Function Documentation
bool GRINS::ParsedInteriorQoI::assemble_on_interior () const inline virtual
Does the QoI need an element interior assembly loop?
This is pure virtual to force to user to specify.
Implements GRINS::QoIBase.
Definition at line 89 of file parsed_interior_qoi.h.
   {
     return true;
   }
bool GRINS::ParsedInteriorQoI::assemble_on_sides () const inline virtual
Does the QoI need a domain boundary assembly loop?
This is pure virtual to force to user to specify.
Implements GRINS::QoIBase.
Definition at line 95 of file parsed_interior_qoi.h.
   {
     return false;
   }
QoIBase * GRINS::ParsedInteriorQoI::clone () const virtual
Required to provide clone (deep-copy) for adding QoI object to libMesh objects.
Implements GRINS::QoIBase.
Definition at line 54 of file parsed_interior_qoi.C.
References ParsedInteriorQoI().
   {
     return new ParsedInteriorQoI( *this );
   }
void GRINS::ParsedInteriorQoI::element_qoi (AssemblyContext & context, const unsigned int qoi_index) virtual
Compute the qoi value.
Todo:
Need to generalize this to the multiple QoI case
Reimplemented from GRINS::QoIBase.
Definition at line 83 of file parsed_interior_qoi.C.
   {
     libMesh::FEBase* element_fe;
     context.get_element_fe<libMesh::Real>(0, element_fe);
     const std::vector<libMesh::Real> &JxW = element_fe->get_JxW();
     const std::vector<libMesh::Point>& x_qp = element_fe->get_xyz();
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     libMesh::Number& qoi = context.get_qois()[qoi_index];
     for( unsigned int qp = 0; qp != n_qpoints; qp++ )
       {
         const libMesh::Number func_val =
           (*qoi_functional)(context, x_qp[qp], context.get_time());
         qoi += func_val * JxW[qp];
       }
   }
void GRINS::ParsedInteriorQoI::element_qoi_derivative (AssemblyContext & context, const unsigned int qoi_index) virtual
Compute the qoi derivative with respect to the solution.
Todo:
Need to generalize this to the multiple QoI case
Reimplemented from GRINS::QoIBase.
Definition at line 106 of file parsed_interior_qoi.C.
   {
     libMesh::FEBase* element_fe;
     context.get_element_fe<libMesh::Real>(0, element_fe);
     const std::vector<libMesh::Real> &JxW = element_fe->get_JxW();
     const std::vector<libMesh::Point>& x_qp = element_fe->get_xyz();
     // Local DOF count and quadrature point count
     const unsigned int n_u_dofs = context.get_dof_indices().size();
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     // Local solution vector - non-const version for finite
     // differenting purposes
     libMesh::DenseVector<libMesh::Number>& elem_solution =
       const_cast<libMesh::DenseVector<libMesh::Number>&>
         (context.get_elem_solution());
     libMesh::DenseVector<libMesh::Number> &Qu =
       context.get_qoi_derivatives()[qoi_index];
     for( unsigned int qp = 0; qp != n_qpoints; qp++ )
       {
         // Central finite differencing to approximate derivatives.
         // FIXME - we should hook the FParserAD stuff into
         // ParsedFEMFunction
         for( unsigned int i = 0; i != n_u_dofs; ++i )
           {
             libMesh::Number &current_solution = elem_solution(i);
             const libMesh::Number original_solution = current_solution;
             current_solution = original_solution + libMesh::TOLERANCE;
             const libMesh::Number plus_val =
               (*qoi_functional)(context, x_qp[qp], context.get_time());
             current_solution = original_solution - libMesh::TOLERANCE;
             const libMesh::Number minus_val =
               (*qoi_functional)(context, x_qp[qp], context.get_time());
             Qu(i) += (plus_val - minus_val) *
                      (0.5 / libMesh::TOLERANCE) * JxW[qp];
             // Don't forget to restore the correct solution...
             current_solution = original_solution;
           }
       }
   }
void GRINS::ParsedInteriorQoI::init (const GetPot & input, const MultiphysicsSystem & system) virtual
Initialize local variables.
Reimplemented from GRINS::QoIBase.
Definition at line 59 of file parsed_interior_qoi.C.
References qoi_functional.
   {
     std::string qoi_functional_string =
       input("QoI/ParsedInterior/qoi_functional", std::string("0"));
     if (qoi_functional_string == "0")
       libmesh_error_msg("Error! Zero ParsedInteriorQoI specified!" <<
                         std::endl);
     this->qoi_functional.reset
       (new libMesh::ParsedFEMFunction<libMesh::Number>
        (system, qoi_functional_string));
   }
void GRINS::ParsedInteriorQoI::init_context (AssemblyContext & context) virtual
Reimplemented from GRINS::QoIBase.
Definition at line 73 of file parsed_interior_qoi.C.
References qoi_functional.
   {
     libMesh::FEBase* element_fe;
     context.get_element_fe<libMesh::Real>(0, element_fe);
     element_fe->get_JxW();
     element_fe->get_xyz();
     qoi_functional->init_context(context);
   }
const std::string & GRINS::QoIBase::name () const inline inherited
Returns the name of this QoI.
Definition at line 143 of file qoi_base.h.
References GRINS::QoIBase::_qoi_name.
Referenced by GRINS::SteadyVisualization::output_adjoint(), and GRINS::UnsteadyVisualization::output_adjoint().
   {
     return _qoi_name;
   }
void GRINS::QoIBase::output_qoi (std::ostream & out) const virtual inherited
Basic output for computed QoI's.
If fancier output is desired, override this method.
Definition at line 107 of file qoi_base.C.
References GRINS::QoIBase::_qoi_name, and GRINS::QoIBase::_qoi_value.
   {
     out << "==========================================================" << std::endl;
     out << _qoi_name+" = "
         << std::setprecision(16)
         << std::scientific
         << _qoi_value << std::endl;
     out << "==========================================================" << std::endl;
     return;
   }
void GRINS::QoIBase::parallel_op (const libMesh::Parallel::Communicator & communicator, libMesh::Number & sys_qoi, libMesh::Number & local_qoi) virtual inherited
Call the parallel operation for this QoI and cache the value.
By default, this is just a sum. Override if QoI is more complex.
Definition at line 87 of file qoi_base.C.
References GRINS::QoIBase::_qoi_value.
   {
     communicator.sum(local_qoi);
     sys_qoi = local_qoi;
     _qoi_value = sys_qoi;
     return;
   }
void GRINS::ParameterUser::register_parameter (const std::string & param_name, libMesh::ParameterMultiPointer< libMesh::Number > & param_pointer) const virtual inherited
Each subclass will register its copy of an independent.
Reimplemented in GRINS::AxisymmetricHeatTransfer< Conductivity >, GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::IncompressibleNavierStokesBase< Viscosity >, GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >, GRINS::HeatConduction< Conductivity >, GRINS::HeatTransferBase< Conductivity >, and GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >.
Definition at line 50 of file parameter_user.C.
Referenced by GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::register_parameter(), GRINS::HeatTransferBase< Conductivity >::register_parameter(), GRINS::HeatConduction< Conductivity >::register_parameter(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::register_parameter(), GRINS::IncompressibleNavierStokesBase< Viscosity >::register_parameter(), GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::register_parameter(), and GRINS::AxisymmetricHeatTransfer< Conductivity >::register_parameter().
   {
     std::map<std::string, libMesh::Number*>::const_iterator it =
       _my_parameters.find(param_name);
     if (it != _my_parameters.end())
       {
         std::cout << _my_name << " uses parameter " << param_name
                   << std::endl;
         param_pointer.push_back(it->second);
       }
   }
void GRINS::ParameterUser::set_parameter (libMesh::Number & param_variable, const GetPot & input, const std::string & param_name, libMesh::Number param_default) virtual inherited
Each subclass can simultaneously read a parameter value from.
Definition at line 35 of file parameter_user.C.
References GRINS::ParameterUser::_my_name, and GRINS::ParameterUser::_my_parameters.
Referenced by GRINS::AveragedFanAdjointStabilization< Viscosity >::AveragedFanAdjointStabilization(), GRINS::AveragedTurbineAdjointStabilization< Viscosity >::AveragedTurbineAdjointStabilization(), GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::BoussinesqBuoyancyAdjointStabilization(), GRINS::BoussinesqBuoyancyBase::BoussinesqBuoyancyBase(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::BoussinesqBuoyancySPGSMStabilization(), GRINS::ConstantConductivity::ConstantConductivity(), GRINS::ConstantPrandtlConductivity::ConstantPrandtlConductivity(), GRINS::ConstantSourceFunction::ConstantSourceFunction(), GRINS::ConstantSourceTerm::ConstantSourceTerm(), GRINS::ConstantSpecificHeat::ConstantSpecificHeat(), GRINS::ConstantViscosity::ConstantViscosity(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticCableConstantGravity::ElasticCableConstantGravity(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransferBase< Conductivity >::HeatTransferBase(), GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase(), GRINS::AverageNusseltNumber::init(), GRINS::MooneyRivlin::MooneyRivlin(), GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase(), GRINS::HookesLaw1D::read_input_options(), GRINS::HookesLaw::read_input_options(), GRINS::AxisymmetricBoussinesqBuoyancy::read_input_options(), and GRINS::VelocityDragAdjointStabilization< Viscosity >::VelocityDragAdjointStabilization().
   {
     param_variable = input(param_name, param_default);
     libmesh_assert_msg(!_my_parameters.count(param_name),
       "ERROR: " << _my_name << " double-registered parameter " <<
       param_name);
     _my_parameters[param_name] = &param_variable;
   }
void GRINS::QoIBase::side_qoi (AssemblyContext & context, const unsigned int qoi_index) virtual inherited
Compute the qoi value on the domain boundary.
Override this method if your QoI is defined on the domain boundary
Reimplemented in GRINS::AverageNusseltNumber.
Definition at line 75 of file qoi_base.C.
   {
     return;
   }
void GRINS::QoIBase::side_qoi_derivative (AssemblyContext & context, const unsigned int qoi_index) virtual inherited
Compute the qoi derivative with respect to the solution on the domain boundary.
Override this method if your QoI is defined on the domain boundary
Reimplemented in GRINS::AverageNusseltNumber.
Definition at line 81 of file qoi_base.C.
   {
     return;
   }
void GRINS::QoIBase::thread_join (libMesh::Number & qoi, const libMesh::Number & other_qoi) virtual inherited
Call the operation to accumulate this QoI from multiple threads.
By default, this is just a sum. Override if QoI is more complex.
Definition at line 100 of file qoi_base.C.
   {
     qoi += other_qoi;
     return;
   }
libMesh::Number GRINS::QoIBase::value () const inline inherited
Returns the current QoI value.
Definition at line 137 of file qoi_base.h.
References GRINS::QoIBase::_qoi_value.
   {
     return _qoi_value;
   }
Member Data Documentation
std::string GRINS::QoIBase::_qoi_name protected inherited
Definition at line 131 of file qoi_base.h.
Referenced by GRINS::QoIBase::name(), and GRINS::QoIBase::output_qoi().
libMesh::Number GRINS::QoIBase::_qoi_value protected inherited
Definition at line 133 of file qoi_base.h.
Referenced by GRINS::QoIBase::output_qoi(), GRINS::QoIBase::parallel_op(), and GRINS::QoIBase::value().
libMesh::AutoPtr<libMesh::FEMFunctionBase<libMesh::Number> > GRINS::ParsedInteriorQoI::qoi_functional protected
Definition at line 77 of file parsed_interior_qoi.h.
Referenced by init(), init_context(), and ParsedInteriorQoI().
The documentation for this class was generated from the following files:
src/qoi/include/grins/parsed_interior_qoi.h
src/qoi/src/parsed_interior_qoi.C