GRINS-0.8.0: GRINS::BCBuilder Class Reference
GRINS::BCBuilder Class Reference abstract
Manages runtime construction of Dirichlet boundary conditions.
#include <bc_builder.h>
Public Member Functions
BCBuilder ()
virtual ~BCBuilder ()
Static Public Member Functions
static void build_boundary_conditions (const GetPot &input, MultiphysicsSystem &system, std::vector< SharedPtr< NeumannBCContainer > > &neumann_bcs)
Protected Member Functions
virtual void build_bcs (const GetPot &input, MultiphysicsSystem &system, std::vector< SharedPtr< NeumannBCContainer > > &neumann_bcs)=0
void construct_dbc_core (const GetPot &input, MultiphysicsSystem &system, const std::set< BoundaryID > &bc_ids, const FEVariablesBase &fe_var, const std::string &section, const std::string &bc_type, libMesh::DofMap &dof_map)
void construct_nbc_core (const GetPot &input, MultiphysicsSystem &system, const std::set< BoundaryID > &bc_ids, const FEVariablesBase &fe_var, const std::string &section, const std::string &bc_type, std::vector< SharedPtr< NeumannBCContainer > > &neumann_bcs)
bool is_dirichlet_bc_type (const std::string &bc_type)
bool is_neumann_bc_type (const std::string &bc_type)
void add_periodic_bc_to_dofmap (libMesh::boundary_id_type master_id, libMesh::boundary_id_type slave_id, const libMesh::RealVectorValue &offset_vector, libMesh::DofMap &dof_map)
Static Protected Member Functions
static bool is_new_bc_input_style (const GetPot &input)
static libMesh::UniquePtr< BCBuilder > build_builder (const GetPot &input)
Detailed Description
Manages runtime construction of Dirichlet boundary conditions.
This will parse the input for the request Dirichlet boundary conditions and manage their construction. Actual construction of the DirichletBoundary objects is delegated to factory classes. This builder classes merely manages tasks around the factories as needed. To add new Dirichlet boundary conditions, the user should instantiate an appropriate factory sub class.
Definition at line 60 of file bc_builder.h.
Constructor & Destructor Documentation
GRINS::BCBuilder::BCBuilder () inline
Definition at line 64 of file bc_builder.h.
 {};
virtual GRINS::BCBuilder::~BCBuilder () inline virtual
Definition at line 66 of file bc_builder.h.
 {};
Member Function Documentation
void GRINS::BCBuilder::add_periodic_bc_to_dofmap (libMesh::boundary_id_type master_id, libMesh::boundary_id_type slave_id, const libMesh::RealVectorValue & offset_vector, libMesh::DofMap & dof_map) protected
Definition at line 151 of file bc_builder.C.
Referenced by GRINS::OldStyleBCBuilder::build_periodic_bc(), and GRINS::DefaultBCBuilder::build_periodic_bc().
   {
     libMesh::PeriodicBoundary bc( offset_vector );
     bc.myboundary = master_id;
     bc.pairedboundary = slave_id;
     dof_map.add_periodic_boundary( bc );
   }
virtual void GRINS::BCBuilder::build_bcs (const GetPot & input, MultiphysicsSystem & system, std::vector< SharedPtr< NeumannBCContainer > > & neumann_bcs) protected pure virtual
Implemented in GRINS::DefaultBCBuilder, and GRINS::OldStyleBCBuilder.
void GRINS::BCBuilder::build_boundary_conditions (const GetPot & input, MultiphysicsSystem & system, std::vector< SharedPtr< NeumannBCContainer > > & neumann_bcs) static
Definition at line 41 of file bc_builder.C.
References build_builder().
Referenced by GRINS::MultiphysicsSystem::init_data().
   {
     libMesh::UniquePtr<BCBuilder>
       bc_builder = BCBuilder::build_builder(input);
     bc_builder->build_bcs(input,system,neumann_bcs);
   }
libMesh::UniquePtr< BCBuilder > GRINS::BCBuilder::build_builder (const GetPot & input) static protected
Definition at line 51 of file bc_builder.C.
References is_new_bc_input_style().
Referenced by build_boundary_conditions().
   {
     bool is_new_style = BCBuilder::is_new_bc_input_style( input );
     libMesh::UniquePtr<BCBuilder> bc_builder;
     if( is_new_style )
       bc_builder.reset( new DefaultBCBuilder );
     else
       bc_builder.reset( new OldStyleBCBuilder );
     return bc_builder;
   }
void GRINS::BCBuilder::construct_dbc_core (const GetPot & input, MultiphysicsSystem & system, const std::set< BoundaryID > & bc_ids, const FEVariablesBase & fe_var, const std::string & section, const std::string & bc_type, libMesh::DofMap & dof_map) protected
Definition at line 76 of file bc_builder.C.
References GRINS::FactoryAbstract< libMesh::DirichletBoundary >::build(), GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >::set_bc_ids(), GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >::set_fe_var(), GRINS::FactoryWithGetPot< libMesh::DirichletBoundary >::set_getpot(), GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >::set_section(), and GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >::set_system().
Referenced by GRINS::DefaultBCBuilder::build_axisymmetric_bcs(), GRINS::DefaultBCBuilder::build_bcs_by_var_section(), and GRINS::OldStyleBCBuilder::construct_bcs_old_style().
   {
     // Give the BC factory access to the System
     DirichletBCFactoryAbstract::set_system( system );
     // Give the BC factory access to the GetPot object
     DirichletBCFactoryAbstract::set_getpot(input);
     // Set the boundary id. This gets reset each time inside the factory.
     DirichletBCFactoryAbstract::set_bc_ids( bc_ids );
     // Set the FEVariable. This gets reset each time inside the factory.
     DirichletBCFactoryAbstract::set_fe_var( fe_var );
     // Tell the DirichletBCFactory where to parse the value of the BC,
     // if it needs to
     DirichletBCFactoryAbstract::set_section( section );
     libMesh::UniquePtr<libMesh::DirichletBoundary>
       dbc = DirichletBCFactoryAbstract::build( bc_type );
     dof_map.add_dirichlet_boundary( *dbc );
   }
void GRINS::BCBuilder::construct_nbc_core (const GetPot & input, MultiphysicsSystem & system, const std::set< BoundaryID > & bc_ids, const FEVariablesBase & fe_var, const std::string & section, const std::string & bc_type, std::vector< SharedPtr< NeumannBCContainer > > & neumann_bcs) protected
Definition at line 106 of file bc_builder.C.
References GRINS::FactoryAbstract< NeumannBCContainer >::build(), GRINS::BCFactoryAbstract< NeumannBCContainer >::set_bc_ids(), GRINS::BCFactoryAbstract< NeumannBCContainer >::set_fe_var(), GRINS::FactoryWithGetPot< NeumannBCContainer >::set_getpot(), GRINS::BCFactoryAbstract< NeumannBCContainer >::set_section(), and GRINS::BCFactoryAbstract< NeumannBCContainer >::set_system().
Referenced by GRINS::DefaultBCBuilder::build_axisymmetric_bcs(), GRINS::DefaultBCBuilder::build_bcs_by_var_section(), and GRINS::OldStyleBCBuilder::construct_bcs_old_style().
   {
     // Give the BC factory access to the System
     NeumannBCFactoryAbstract::set_system( system );
     // Give the BC factory access to the GetPot object
     NeumannBCFactoryAbstract::set_getpot(input);
     // Set the boundary id. This gets reset each time inside the factory.
     NeumannBCFactoryAbstract::set_bc_ids( bc_ids );
     // Set the FEVariable. This gets reset each time inside the factory.
     NeumannBCFactoryAbstract::set_fe_var( fe_var );
     // Tell the NeumannBCFactory where to parse the value of the BC,
     // if it needs to
     NeumannBCFactoryAbstract::set_section( section );
     libMesh::UniquePtr<NeumannBCContainer>
       nbc = NeumannBCFactoryAbstract::build(bc_type);
     // Get nothing if it's a homogeneous Neumann BC
     // so only try to add it if something was built.
     if(nbc)
       neumann_bcs.push_back(nbc.release());
   }
bool GRINS::BCBuilder::is_dirichlet_bc_type (const std::string & bc_type) protected
Definition at line 139 of file bc_builder.C.
References GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >::have_bc_type().
Referenced by GRINS::DefaultBCBuilder::build_axisymmetric_bcs(), GRINS::DefaultBCBuilder::build_bcs_by_var_section(), and GRINS::OldStyleBCBuilder::construct_bcs_old_style().
   {
     // We query the factory to see if it's registered there or not.
     return DirichletBCFactoryAbstract::have_bc_type( bc_type );
   }
bool GRINS::BCBuilder::is_neumann_bc_type (const std::string & bc_type) protected
Definition at line 145 of file bc_builder.C.
References GRINS::BCFactoryAbstract< NeumannBCContainer >::have_bc_type().
Referenced by GRINS::DefaultBCBuilder::build_axisymmetric_bcs(), GRINS::DefaultBCBuilder::build_bcs_by_var_section(), and GRINS::OldStyleBCBuilder::construct_bcs_old_style().
   {
     // We query the factory to see if it's registered there or not.
     return NeumannBCFactoryAbstract::have_bc_type( bc_type );
   }
bool GRINS::BCBuilder::is_new_bc_input_style (const GetPot & input) static protected
Definition at line 66 of file bc_builder.C.
References GRINS::BoundaryConditionNames::bc_section().
Referenced by build_builder().
   {
     bool new_style = false;
     if( input.have_section(BoundaryConditionNames::bc_section()) )
       new_style = true;
     return new_style;
   }
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/bc_builder.h
src/boundary_conditions/src/bc_builder.C