GRINS-0.7.0: GRINS::BoussinesqBuoyancyBase Class Reference
GRINS::BoussinesqBuoyancyBase Class Reference
#include <boussinesq_buoyancy_base.h>
Public Member Functions
BoussinesqBuoyancyBase (const std::string &physics_name, const GetPot &input)
~BoussinesqBuoyancyBase ()
virtual void init_variables (libMesh::FEMSystem *system)
Initialization of BoussinesqBuoyancy variables.
Public Member Functions inherited from GRINS::Physics
Physics (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~Physics ()
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Set which variables are time evolving.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for element interiors.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void damping_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Damping matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_damping_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
ICHandlingBase * get_ic_handler ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Member Functions
void read_property (const GetPot &input, const std::string &old_option, const std::string &property, libMesh::Real &value)
Helper function for parsing/maintaing backward compatibility.
void no_input_warning (const GetPot &input, const std::string &old_option, const std::string &material, const std::string &property)
Helper function for parsing/maintaing backward compatibility.
Protected Member Functions inherited from GRINS::Physics
libMesh::UniquePtr< libMesh::FEGenericBase< libMesh::Real > > build_new_fe (const libMesh::Elem *elem, const libMesh::FEGenericBase< libMesh::Real > *fe, const libMesh::Point p)
void parse_enabled_subdomains (const GetPot &input, const std::string &physics_name)
Protected Attributes
VelocityFEVariables _flow_vars
PressureFEVariable _press_var
PrimitiveTempFEVariables _temp_vars
libMesh::Number _rho
density
libMesh::Number _T_ref
reference temperature
libMesh::Number _beta_T
coefficient of thermal expansion
libMesh::Point _g
Gravitational vector.
unsigned int _dim
Physical dimension of problem.
Protected Attributes inherited from GRINS::Physics
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
Private Member Functions
BoussinesqBuoyancyBase ()
void register_variables ()
Additional Inherited Members
Static Public Member Functions inherited from GRINS::Physics
static void set_is_axisymmetric (bool is_axisymmetric)
Set whether we should treat the problem as axisymmetric.
static bool is_axisymmetric ()
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Static Protected Attributes inherited from GRINS::Physics
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
static bool _is_axisymmetric = false
Caches whether we are solving an axisymmetric problem or not.
Detailed Description
Definition at line 40 of file boussinesq_buoyancy_base.h.
Constructor & Destructor Documentation
GRINS::BoussinesqBuoyancyBase::BoussinesqBuoyancyBase (const std::string & physics_name, const GetPot & input)
Definition at line 44 of file boussinesq_buoyancy_base.C.
References _beta_T, _g, _rho, _T_ref, GRINS::PhysicsNaming::boussinesq_buoyancy(), read_property(), and register_variables().
     : Physics(physics_name,input),
       _flow_vars(input,PhysicsNaming::incompressible_navier_stokes()),
       _press_var(input,PhysicsNaming::incompressible_navier_stokes(), true /*is_constraint_var*/),
       _temp_vars(input,PhysicsNaming::heat_transfer()),
       _rho(0.0),
       _T_ref(1.0),
       _beta_T(1.0)
   {
     this->read_property(input,
                         "Physics/"+PhysicsNaming::boussinesq_buoyancy()+"/rho_ref",
                         "Density",
                         _rho);
     this->read_property(input,
                         "Physics/"+PhysicsNaming::boussinesq_buoyancy()+"/T_ref",
                         "ReferenceTemperature",
                         _T_ref);
     this->read_property(input,
                         "Physics/"+PhysicsNaming::boussinesq_buoyancy()+"/beta_T",
                         "ThermalExpansionCoeff",
                         _beta_T);
     unsigned int g_dim = input.vector_variable_size("Physics/"+PhysicsNaming::boussinesq_buoyancy()+"/g");
     _g(0) = input("Physics/"+PhysicsNaming::boussinesq_buoyancy()+"/g", 0.0, 0 );
     _g(1) = input("Physics/"+PhysicsNaming::boussinesq_buoyancy()+"/g", 0.0, 1 );
     if( g_dim == 3)
       _g(2) = input("Physics/"+PhysicsNaming::boussinesq_buoyancy()+"/g", 0.0, 2 );
     this->register_variables();
   }
GRINS::BoussinesqBuoyancyBase::~BoussinesqBuoyancyBase ()
Definition at line 80 of file boussinesq_buoyancy_base.C.
   {
     return;
   }
GRINS::BoussinesqBuoyancyBase::BoussinesqBuoyancyBase () private
Member Function Documentation
void GRINS::BoussinesqBuoyancyBase::init_variables (libMesh::FEMSystem * system) virtual
Initialization of BoussinesqBuoyancy variables.
Implements GRINS::Physics.
Definition at line 95 of file boussinesq_buoyancy_base.C.
References _dim, _flow_vars, _press_var, _temp_vars, GRINS::VelocityFEVariables::init(), and GRINS::SingleFETypeVariable::init().
   {
     // Get libMesh to assign an index for each variable
     this->_dim = system->get_mesh().mesh_dimension();
     _temp_vars.init(system);
     _flow_vars.init(system);
     this->_press_var.init(system);
     return;
   }
void GRINS::BoussinesqBuoyancyBase::no_input_warning (const GetPot & input, const std::string & old_option, const std::string & material, const std::string & property) protected
Helper function for parsing/maintaing backward compatibility.
Definition at line 153 of file boussinesq_buoyancy_base.C.
References GRINS::PhysicsNaming::boussinesq_buoyancy(), grins_warning, and GRINS::MaterialsParsing::have_material().
Referenced by read_property().
   {
     std::string warning;
     if( !MaterialsParsing::have_material(input,PhysicsNaming::boussinesq_buoyancy()) )
       {
         warning = "WARNING: Neither "+old_option+"\n";
         warning += "         nor a material_name was detected in input\n";
         warning +  "         "+property+" is defaulting to 1.0. This behavior is DEPRECATED!\n";
         warning += "         Please update to use Material/MATERIAL_NAME/"+property+"/value\n";
       }
     else
       {
         warning = "WARNING: Neither "+old_option+"\n";
         warning += "         nor Material/"+material+"/"+property+"/value\n";
         warning +  "         "+property+" is defaulting to 1.0. This behavior is DEPRECATED!\n";
         warning += "         Please update to use Material/MATERIAL_NAME/"+property+"/value\n";
       }
     grins_warning(warning);
   }
void GRINS::BoussinesqBuoyancyBase::read_property (const GetPot & input, const std::string & old_option, const std::string & property, libMesh::Real & value) protected
Helper function for parsing/maintaing backward compatibility.
Definition at line 107 of file boussinesq_buoyancy_base.C.
References GRINS::PhysicsNaming::boussinesq_buoyancy(), GRINS::MaterialsParsing::dep_input_warning(), GRINS::MaterialsParsing::duplicate_input_test(), GRINS::MaterialsParsing::material_name(), no_input_warning(), and GRINS::ParameterUser::set_parameter().
Referenced by BoussinesqBuoyancyBase().
   {
     std::string material = MaterialsParsing::material_name(input,PhysicsNaming::boussinesq_buoyancy());
     // Can't specify both material and rho_ref
     MaterialsParsing::duplicate_input_test(input,
                                            old_option,
                                            "Materials/"+material+"/"+property+"/value" );
     // Deprecated
     if( input.have_variable(old_option) )
       {
         MaterialsParsing::dep_input_warning( old_option,property+"/value" );
         this->set_parameter
           (value, input,
            old_option, 1.0 /*Old default*/);
       }
     // Preferred
     else if( input.have_variable("Materials/"+material+"/"+property+"/value" ) )
       {
         this->set_parameter
           (value, input,
            "Materials/"+material+"/"+property+"/value", 0.0 /*default*/);
       }
     // If nothing was set, we default to 1.0. Deprecated, what was I thinking
     else
       {
         this->no_input_warning( input,
                                 old_option,
                                 material,
                                 property );
         this->set_parameter
           (value, input, old_option, 1.0 /*default*/);
       }
     // Make sure density is positive
     if( value <= 0.0 )
       {
         libmesh_error_msg("ERROR: Detected non-positive "+property+"!");
       }
   }
void GRINS::BoussinesqBuoyancyBase::register_variables () private
Definition at line 85 of file boussinesq_buoyancy_base.C.
References _flow_vars, _press_var, _temp_vars, GRINS::GRINSPrivate::VariableWarehouse::check_and_register_variable(), GRINS::VariablesParsing::pressure_section(), GRINS::VariablesParsing::temperature_section(), and GRINS::VariablesParsing::velocity_section().
Referenced by BoussinesqBuoyancyBase().
   {
     GRINSPrivate::VariableWarehouse::check_and_register_variable(VariablesParsing::pressure_section(),
                                                                  this->_press_var);
     GRINSPrivate::VariableWarehouse::check_and_register_variable(VariablesParsing::velocity_section(),
                                                                  this->_flow_vars);
     GRINSPrivate::VariableWarehouse::check_and_register_variable(VariablesParsing::temperature_section(),
                                                                  this->_temp_vars);
   }
Member Data Documentation
libMesh::Number GRINS::BoussinesqBuoyancyBase::_beta_T protected
coefficient of thermal expansion
Definition at line 76 of file boussinesq_buoyancy_base.h.
Referenced by BoussinesqBuoyancyBase(), and GRINS::BoussinesqBuoyancy::element_time_derivative().
unsigned int GRINS::BoussinesqBuoyancyBase::_dim protected
Physical dimension of problem.
Definition at line 82 of file boussinesq_buoyancy_base.h.
Referenced by GRINS::BoussinesqBuoyancy::element_time_derivative(), and init_variables().
VelocityFEVariables GRINS::BoussinesqBuoyancyBase::_flow_vars protected
Definition at line 65 of file boussinesq_buoyancy_base.h.
Referenced by GRINS::BoussinesqBuoyancy::element_time_derivative(), init_variables(), and register_variables().
libMesh::Point GRINS::BoussinesqBuoyancyBase::_g protected
Gravitational vector.
Definition at line 79 of file boussinesq_buoyancy_base.h.
Referenced by BoussinesqBuoyancyBase(), and GRINS::BoussinesqBuoyancy::element_time_derivative().
PressureFEVariable GRINS::BoussinesqBuoyancyBase::_press_var protected
Definition at line 66 of file boussinesq_buoyancy_base.h.
Referenced by init_variables(), and register_variables().
libMesh::Number GRINS::BoussinesqBuoyancyBase::_rho protected
density
Definition at line 70 of file boussinesq_buoyancy_base.h.
Referenced by BoussinesqBuoyancyBase(), and GRINS::BoussinesqBuoyancy::element_time_derivative().
libMesh::Number GRINS::BoussinesqBuoyancyBase::_T_ref protected
reference temperature
Definition at line 73 of file boussinesq_buoyancy_base.h.
Referenced by BoussinesqBuoyancyBase(), and GRINS::BoussinesqBuoyancy::element_time_derivative().
PrimitiveTempFEVariables GRINS::BoussinesqBuoyancyBase::_temp_vars protected
Definition at line 67 of file boussinesq_buoyancy_base.h.
Referenced by GRINS::BoussinesqBuoyancy::element_time_derivative(), init_variables(), and register_variables().
The documentation for this class was generated from the following files:
src/physics/include/grins/boussinesq_buoyancy_base.h
src/physics/src/boussinesq_buoyancy_base.C