GRINS-0.8.0: GRINS::AntiochMixtureBuilderBase Class Reference
GRINS::AntiochMixtureBuilderBase Class Reference
Base class building Antioch mixture wrappers.
#include <antioch_mixture_builder_base.h>
Public Member Functions
AntiochMixtureBuilderBase ()
~AntiochMixtureBuilderBase ()
libMesh::UniquePtr< Antioch::ChemicalMixture< libMesh::Real > > build_chem_mix (const GetPot &input, const std::string &material)
libMesh::UniquePtr< Antioch::ReactionSet< libMesh::Real > > build_reaction_set (const GetPot &input, const std::string &material, const Antioch::ChemicalMixture< libMesh::Real > &chem_mix)
template<typename KineticsThermoCurveFit >
libMesh::UniquePtr< Antioch::NASAThermoMixture< libMesh::Real, KineticsThermoCurveFit > > build_nasa_thermo_mix (const GetPot &input, const std::string &material, const Antioch::ChemicalMixture< libMesh::Real > &chem_mix)
template<typename KineticsThermoCurveFit >
libMesh::UniquePtr< AntiochMixture< KineticsThermoCurveFit > > build_antioch_mixture (const GetPot &input, const std::string &material)
libMesh::Real parse_min_T (const GetPot &input, const std::string &material)
bool parse_clip_negative_rho (const GetPot &input, const std::string &material)
Protected Member Functions
void parse_nasa_data (Antioch::NASAThermoMixture< libMesh::Real, Antioch::CEACurveFit< libMesh::Real > > &nasa_mixture, const GetPot &input, const std::string &material)
Detailed Description
Base class building Antioch mixture wrappers.
This class only worries about building the kinetics and the thermo associated with kinetics. Subclasses will handle thermo and transport.
Definition at line 62 of file antioch_mixture_builder_base.h.
Constructor & Destructor Documentation
GRINS::AntiochMixtureBuilderBase::AntiochMixtureBuilderBase () inline
Definition at line 65 of file antioch_mixture_builder_base.h.
 {}
GRINS::AntiochMixtureBuilderBase::~AntiochMixtureBuilderBase () inline
Definition at line 66 of file antioch_mixture_builder_base.h.
 {}
Member Function Documentation
template<typename KineticsThermoCurveFit > libMesh::UniquePtr< AntiochMixture< KineticsThermoCurveFit > > GRINS::AntiochMixtureBuilderBase::build_antioch_mixture (const GetPot & input, const std::string & material) inline
Definition at line 129 of file antioch_mixture_builder_base.h.
References build_chem_mix(), build_reaction_set(), parse_clip_negative_rho(), and parse_min_T().
Referenced by GRINSTesting::AntiochTestBase::init_antioch(), and main().
   {
     libMesh::UniquePtr<Antioch::ChemicalMixture<libMesh::Real> > chem_mixture =
       this->build_chem_mix(input,material);
     libMesh::UniquePtr<Antioch::ReactionSet<libMesh::Real> > reaction_set =
       this->build_reaction_set(input,material,*chem_mixture);
     libMesh::UniquePtr<Antioch::NASAThermoMixture<libMesh::Real,KineticsThermoCurveFit> > nasa_mixture =
       this->build_nasa_thermo_mix<KineticsThermoCurveFit>(input,material,*chem_mixture);
     libMesh::Real min_T = this->parse_min_T(input,material);
     bool clip_negative_rho = this->parse_clip_negative_rho(input,material);
     return libMesh::UniquePtr<AntiochMixture<KineticsThermoCurveFit> >
       ( new AntiochMixture<KineticsThermoCurveFit>
         (chem_mixture,reaction_set,nasa_mixture,min_T,clip_negative_rho) );
   }
libMesh::UniquePtr< Antioch::ChemicalMixture< libMesh::Real > > GRINS::AntiochMixtureBuilderBase::build_chem_mix (const GetPot & input, const std::string & material)
Definition at line 42 of file antioch_mixture_builder_base.C.
References GRINS::MaterialsParsing::parse_chemical_species().
Referenced by build_antioch_mixture(), GRINS::ChemistryBuilder::build_chemistry(), GRINS::AntiochConstantTransportMixtureBuilder::build_mixture(), GRINS::AntiochMixtureAveragedTransportMixtureBuilder::build_mixture(), GRINSTesting::AntiochMixtureBuilderBaseTest::test_build_chem_mix(), GRINSTesting::AntiochMixtureBuilderBaseTest::test_build_nasa_thermo_mix_cea(), and GRINSTesting::AntiochMixtureBuilderBaseTest::test_build_reaction_set().
   {
     std::vector<std::string> species_list;
     MaterialsParsing::parse_chemical_species(input,material,species_list);
     bool verbose_antioch_read = input("Materials/"+material+"/GasMixture/Antioch/verbose_read",false);
     std::string species_data_filename = input("Materials/"+material+"/GasMixture/Antioch/species_data", "default" );
     if( species_data_filename == std::string("default") )
       species_data_filename = Antioch::DefaultInstallFilename::chemical_mixture();
     std::string vibration_data_filename = input("Materials/"+material+"/GasMixture/Antioch/vibration_data", "default" );
     if( vibration_data_filename == std::string("default") )
       vibration_data_filename = Antioch::DefaultInstallFilename::vibrational_data();
     std::string electronic_data_filename = input("Materials/"+material+"/GasMixture/Antioch/electronic_data", "default" );
     if( electronic_data_filename == std::string("default") )
       electronic_data_filename = Antioch::DefaultInstallFilename::electronic_data();
     // By default, Antioch is using its ASCII parser. We haven't added more options yet.
     return libMesh::UniquePtr<Antioch::ChemicalMixture<libMesh::Real> >
       ( new Antioch::ChemicalMixture<libMesh::Real>( species_list,
                                                      verbose_antioch_read,
                                                      species_data_filename,
                                                      vibration_data_filename,
                                                      electronic_data_filename ) );
   }
template<typename KineticsThermoCurveFit > libMesh::UniquePtr< Antioch::NASAThermoMixture< libMesh::Real, KineticsThermoCurveFit > > GRINS::AntiochMixtureBuilderBase::build_nasa_thermo_mix (const GetPot & input, const std::string & material, const Antioch::ChemicalMixture< libMesh::Real > & chem_mix) inline
Definition at line 115 of file antioch_mixture_builder_base.h.
References parse_nasa_data().
Referenced by GRINSTesting::AntiochMixtureBuilderBaseTest::test_build_nasa_thermo_mix_cea().
   {
     libMesh::UniquePtr<Antioch::NASAThermoMixture<libMesh::Real,KineticsThermoCurveFit> >
       nasa_mixture( new Antioch::NASAThermoMixture<libMesh::Real,KineticsThermoCurveFit>(chem_mix) );
     this->parse_nasa_data( *nasa_mixture, input, material);
     return nasa_mixture;
   }
libMesh::UniquePtr< Antioch::ReactionSet< libMesh::Real > > GRINS::AntiochMixtureBuilderBase::build_reaction_set (const GetPot & input, const std::string & material, const Antioch::ChemicalMixture< libMesh::Real > & chem_mix)
Definition at line 71 of file antioch_mixture_builder_base.C.
References GRINS::MaterialsParsing::parse_chemical_kinetics_datafile_name().
Referenced by build_antioch_mixture(), GRINS::AntiochConstantTransportMixtureBuilder::build_mixture(), GRINS::AntiochMixtureAveragedTransportMixtureBuilder::build_mixture(), and GRINSTesting::AntiochMixtureBuilderBaseTest::test_build_reaction_set().
   {
     libMesh::UniquePtr<Antioch::ReactionSet<libMesh::Real> >
       reaction_set( new Antioch::ReactionSet<libMesh::Real>(chem_mix) );
     std::string kinetics_data_filename = MaterialsParsing::parse_chemical_kinetics_datafile_name( input, material );
     bool verbose_read = input("screen-options/verbose_kinetics_read", false );
     Antioch::read_reaction_set_data_xml<libMesh::Real>( kinetics_data_filename, verbose_read, *reaction_set );
     return reaction_set;
   }
bool GRINS::AntiochMixtureBuilderBase::parse_clip_negative_rho (const GetPot & input, const std::string & material) inline
Definition at line 91 of file antioch_mixture_builder_base.h.
Referenced by build_antioch_mixture(), GRINS::AntiochConstantTransportMixtureBuilder::build_mixture(), GRINS::AntiochMixtureAveragedTransportMixtureBuilder::build_mixture(), and GRINSTesting::AntiochMixtureBuilderBaseTest::test_parse_clip_negative_rho().
     {
       return input( "Materials/"+material+"/GasMixture/Antioch/clip_negative_rho", false);
     }
libMesh::Real GRINS::AntiochMixtureBuilderBase::parse_min_T (const GetPot & input, const std::string & material) inline
Definition at line 85 of file antioch_mixture_builder_base.h.
Referenced by build_antioch_mixture(), GRINS::AntiochConstantTransportMixtureBuilder::build_mixture(), GRINS::AntiochMixtureAveragedTransportMixtureBuilder::build_mixture(), and GRINSTesting::AntiochMixtureBuilderBaseTest::test_parse_min_T().
     {
       return input( "Materials/"+material+"/GasMixture/Antioch/minimum_T",
                     -std::numeric_limits<libMesh::Real>::max() );
     }
void GRINS::AntiochMixtureBuilderBase::parse_nasa_data (Antioch::NASAThermoMixture< libMesh::Real, Antioch::CEACurveFit< libMesh::Real > > & nasa_mixture, const GetPot & input, const std::string & material) inline protected
Definition at line 99 of file antioch_mixture_builder_base.h.
Referenced by build_nasa_thermo_mix().
     {
       std::string cea_data_filename = input( "Materials/"+material+"/GasMixture/Antioch/cea_data", "default" );
       if( cea_data_filename == std::string("default") )
         cea_data_filename = Antioch::DefaultInstallFilename::thermo_data();
       Antioch::read_nasa_mixture_data( nasa_mixture, cea_data_filename, Antioch::ASCII, true );
     }
The documentation for this class was generated from the following files:
src/properties/include/grins/antioch_mixture_builder_base.h
src/properties/src/antioch_mixture_builder_base.C