GRINS-0.8.0: GRINS::ICHandlingBase Class Reference
GRINS::ICHandlingBase Class Reference
Base class for reading and handling initial conditions for physics classes.
#include <ic_handling_base.h>
Public Member Functions
ICHandlingBase (const std::string &physics_name)
virtual ~ICHandlingBase ()
void attach_initial_func (const libMesh::FunctionBase< libMesh::Number > &initial_val)
virtual void read_ic_data (const GetPot &input, const std::string &id_str, const std::string &ic_str, const std::string &var_str, const std::string &value_str)
virtual void init_ic_data (const libMesh::FEMSystem &system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
Override this method to initialize any system-dependent data.
virtual int string_to_int (const std::string &bc_type_in) const
virtual void init_ic_types (const libMesh::subdomain_id_type ic_id, const std::string &ic_id_string, const int ic_type, const std::string &ic_vars_string, const std::string &ic_value_string, const GetPot &input)
libMesh::FunctionBase< libMesh::Number > * get_ic_func () const
Protected Types
enum IC_BASE { PARSED = -2, CONSTANT }
Protected Attributes
libMesh::UniquePtr< libMesh::FunctionBase< libMesh::Number > > _ic_func
std::string _physics_name
std::vector< std::string > _subfunction_variables
Detailed Description
Base class for reading and handling initial conditions for physics classes.
Definition at line 51 of file ic_handling_base.h.
Member Enumeration Documentation
enum GRINS::ICHandlingBase::IC_BASE protected
Enumerator
PARSED
CONSTANT
Definition at line 90 of file ic_handling_base.h.
                 { PARSED = -2,
                   CONSTANT };
Constructor & Destructor Documentation
GRINS::ICHandlingBase::ICHandlingBase (const std::string & physics_name)
Definition at line 52 of file ic_handling_base.C.
     : _physics_name( physics_name )
   {
     return;
   }
GRINS::ICHandlingBase::~ICHandlingBase () virtual
Definition at line 58 of file ic_handling_base.C.
   {
     return;
   }
Member Function Documentation
void GRINS::ICHandlingBase::attach_initial_func (const libMesh::FunctionBase< libMesh::Number > & initial_val)
Definition at line 64 of file ic_handling_base.C.
   {
     _ic_func = initial_val.clone();
   }
libMesh::FunctionBase< libMesh::Number > * GRINS::ICHandlingBase::get_ic_func () const inline
Definition at line 99 of file ic_handling_base.h.
References _ic_func.
Referenced by init_ic_data().
   {
     return _ic_func.get();
   }
void GRINS::ICHandlingBase::init_ic_data (const libMesh::FEMSystem & system, libMesh::CompositeFunction< libMesh::Number > & all_ics) virtual
Override this method to initialize any system-dependent data.
Override this method to, for example, cache a System variable number.
Definition at line 128 of file ic_handling_base.C.
References _subfunction_variables, and get_ic_func().
Referenced by GRINS::Physics::init_ics().
   {
     if (this->get_ic_func())
       {
         std::vector<unsigned int> index_map;
         libmesh_assert(_subfunction_variables.size());
         for (unsigned int i=0; i != _subfunction_variables.size();
              ++i)
           index_map.push_back
             (system.variable_number(_subfunction_variables[i]));
         all_ics.attach_subfunction(*this->get_ic_func(), index_map);
       }
   }
void GRINS::ICHandlingBase::init_ic_types (const libMesh::subdomain_id_type ic_id, const std::string & ic_id_string, const int ic_type, const std::string & ic_vars_string, const std::string & ic_value_string, const GetPot & input) virtual
Definition at line 168 of file ic_handling_base.C.
References _ic_func, _physics_name, _subfunction_variables, CONSTANT, PARSED, and GRINS::StringUtilities::split_string().
Referenced by read_ic_data().
   {
     StringUtilities::split_string(ic_vars_string, ":", _subfunction_variables);
     libmesh_assert(_subfunction_variables.size());
     switch(ic_type)
       {
       case(PARSED):
         {
           _ic_func = libMesh::UniquePtr<libMesh::FunctionBase<libMesh::Number> >
             (new libMesh::ParsedFunction<libMesh::Number>(ic_value_string));
         }
         break;
       case(CONSTANT):
         {
           _ic_func = libMesh::UniquePtr<libMesh::FunctionBase<libMesh::Number> >
             (new libMesh::ConstFunction<libMesh::Number>
              (StringUtilities::string_to_T<libMesh::Number>(ic_value_string)));
         }
         break;
       default:
         {
           std::cerr << "=========================================================="
                     << "Error: Invalid IC type for " << _physics_name << std::endl
                     << "       Detected IC type was " << ic_type << std::endl
                     << "==========================================================" << std::endl;
           libmesh_error();
         }
       }
     return;
   }
void GRINS::ICHandlingBase::read_ic_data (const GetPot & input, const std::string & id_str, const std::string & ic_str, const std::string & var_str, const std::string & value_str) virtual
Definition at line 69 of file ic_handling_base.C.
References init_ic_types(), and string_to_int().
Referenced by GRINS::GenericICHandler::GenericICHandler().
   {
     int num_ids = input.vector_variable_size(id_str);
     int num_ics = input.vector_variable_size(ic_str);
     int num_vars = input.vector_variable_size(var_str);
     int num_values = input.vector_variable_size(value_str);
     if( num_ids != num_ics )
       {
         std::cerr << "Error: number of subdomain ids " << num_ids
                   << "must equal number of initial condition types " << num_ics
                   << std::endl;
         libmesh_error();
       }
     if( num_ids != num_vars )
       {
         std::cerr << "Error: number of subdomain ids " << num_ids
                   << "must equal number of variable name lists " << num_vars
                   << std::endl;
         libmesh_error();
       }
     if( num_ids != num_values )
       {
         std::cerr << "Error: number of subdomain ids " << num_ids
                   << "must equal number of initial condition values " << num_values
                   << std::endl;
         libmesh_error();
       }
     if( num_ids > 1 )
       {
         std::cerr << "Error: GRINS does not yet support per-subdomain initial conditions" << std::endl;
         libmesh_not_implemented();
       }
     for( int i = 0; i < num_ids; i++ )
       {
         int ic_id = input(id_str, -1, i );
         std::string ic_type_in = input(ic_str, "NULL", i );
         std::string ic_value_in = input(value_str, "NULL", i );
         std::string ic_vars_in = input(var_str, "NULL", i );
         int ic_type = this->string_to_int( ic_type_in );
         std::stringstream ss;
         ss << ic_id;
         std::string ic_id_string = ss.str();
         this->init_ic_types( ic_id, ic_id_string, ic_type, ic_vars_in, ic_value_in, input );
       }
     return;
   }
int GRINS::ICHandlingBase::string_to_int (const std::string & bc_type_in) const virtual
Definition at line 146 of file ic_handling_base.C.
References _physics_name, CONSTANT, and PARSED.
Referenced by read_ic_data().
   {
     int ic_type_out;
     if( ic_type_in == "parsed" )
       {
         ic_type_out = PARSED;
       }
     else if( ic_type_in == "constant" )
       {
         ic_type_out = CONSTANT;
       }
     else
       {
         std::cerr << "=========================================================="  << std::endl
                   << "Error: Invalid ic_type " << ic_type_in                       << std::endl
                   << "       Physics class is " << _physics_name                   << std::endl
                   << "=========================================================="  << std::endl;
         libmesh_error();
       }
     return ic_type_out;
   }
Member Data Documentation
libMesh::UniquePtr<libMesh::FunctionBase<libMesh::Number> > GRINS::ICHandlingBase::_ic_func protected
Definition at line 86 of file ic_handling_base.h.
Referenced by get_ic_func(), and init_ic_types().
std::string GRINS::ICHandlingBase::_physics_name protected
Definition at line 88 of file ic_handling_base.h.
Referenced by GRINS::GenericICHandler::GenericICHandler(), init_ic_types(), and string_to_int().
std::vector<std::string> GRINS::ICHandlingBase::_subfunction_variables protected
Definition at line 93 of file ic_handling_base.h.
Referenced by init_ic_data(), and init_ic_types().
The documentation for this class was generated from the following files:
src/ic_handling/include/grins/ic_handling_base.h
src/ic_handling/src/ic_handling_base.C