GRINS-0.8.0: GRINS::GasSolidCatalyticWall< Chemistry > Class Template Reference
GRINS::GasSolidCatalyticWall< Chemistry > Class Template Reference
#include <gas_solid_catalytic_wall.h>
Public Member Functions
GasSolidCatalyticWall (SharedPtr< Chemistry > &chem, SharedPtr< CatalycityBase > &gamma, const std::vector< VariableIndex > &species_vars, VariableIndex T_var, libMesh::Real p0, unsigned int reactant_gas_species_idx, unsigned int reactant_solid_species_idx, unsigned int product_species_idx)
GasSolidCatalyticWall (const Chemistry &chem_mixture, CatalycityBase &gamma, const unsigned int reactant_gas_species_idx, const unsigned int reactant_solid_species_idx, const unsigned int product_species_idx)
Deprecated.
virtual ~GasSolidCatalyticWall ()
virtual void init (const libMesh::FEMSystem &system)
Deprecated.
virtual bool eval_flux (bool compute_jacobian, AssemblyContext &context, libMesh::Real sign, bool is_axisymmetric)
virtual void apply_fluxes (AssemblyContext &context, const CachedValues &cache, const bool request_jacobian)
Deprecated.
libMesh::Real compute_reactant_gas_mass_flux (const libMesh::Real rho, const libMesh::Real Y_r, const libMesh::Real T)
libMesh::Real compute_reactant_solid_mass_consumption (const libMesh::Real rho, const libMesh::Real Y_r, const libMesh::Real T)
libMesh::Real compute_product_mass_flux (const libMesh::Real rho, const libMesh::Real Y_r, const libMesh::Real T)
libMesh::Real compute_reactant_solid_mass_consumption_dT (const libMesh::Real rho, const libMesh::Real Y_r, const libMesh::Real T)
libMesh::Real compute_reactant_solid_mass_consumption_dYs (const libMesh::Real rho, const std::vector< libMesh::Real > Y, const libMesh::Real T)
Public Member Functions inherited from GRINS::CatalyticWallBase< Chemistry >
CatalyticWallBase (SharedPtr< Chemistry > &chem, SharedPtr< CatalycityBase > &gamma, const std::vector< VariableIndex > &species_vars, VariableIndex T_var, libMesh::Real p0, unsigned int reactant_species_idx)
CatalyticWallBase (const Chemistry &chem_mixture, CatalycityBase &gamma, const unsigned int reactant_species_idx)
Deprecated.
virtual ~CatalyticWallBase ()
libMesh::Real rho (libMesh::Real T, libMesh::Real p0, libMesh::Real R_mix) const
libMesh::Real omega_dot (const libMesh::Real rho_s, const libMesh::Real T) const
libMesh::Real domega_dot_dws (const libMesh::Real rho_s, const libMesh::Real w_s, const libMesh::Real T, const libMesh::Real R) const
libMesh::Real domega_dot_dT (const libMesh::Real rho_s, const libMesh::Real T) const
void set_catalycity_params (const std::vector< libMesh::Real > &params)
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Public Member Functions inherited from GRINS::NeumannBCAbstract
NeumannBCAbstract ()
virtual ~NeumannBCAbstract ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
Protected Attributes
const unsigned int _reactant_gas_species_idx
VariableIndex _reactant_gas_var_idx
const unsigned int _reactant_solid_species_idx
const unsigned int _product_species_idx
VariableIndex _product_var_idx
Protected Attributes inherited from GRINS::CatalyticWallBase< Chemistry >
SharedPtr< Chemistry > _chem_ptr
const Chemistry & _chemistry
Deprecated.
SharedPtr< CatalycityBase > _gamma_ptr
libMesh::UniquePtr< CatalycityBase > _gamma_s
Deprecated.
const libMesh::Real _C
std::vector< VariableIndex > _species_vars
VariableIndex _T_var
libMesh::Real _p0
Thermodynamic pressure.
Additional Inherited Members
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Member Functions inherited from GRINS::CatalyticWallBase< Chemistry >
libMesh::Real eval_gamma (libMesh::Real T) const
Temporary helper to deal with intermediate refactoring.
libMesh::Real eval_gamma_dT (libMesh::Real T) const
Temporary helper to deal with intermediate refactoring.
Detailed Description
template<typename Chemistry>
class GRINS::GasSolidCatalyticWall< Chemistry >
Definition at line 36 of file gas_solid_catalytic_wall.h.
Constructor & Destructor Documentation
template<typename Chemistry > GRINS::GasSolidCatalyticWall< Chemistry >::GasSolidCatalyticWall (SharedPtr< Chemistry > & chem, SharedPtr< CatalycityBase > & gamma, const std::vector< VariableIndex > & species_vars, VariableIndex T_var, libMesh::Real p0, unsigned int reactant_gas_species_idx, unsigned int reactant_solid_species_idx, unsigned int product_species_idx)
Definition at line 37 of file gas_solid_catalytic_wall.C.
   : CatalyticWallBase<Chemistry>(chem,gamma,species_vars,T_var,p0,reactant_gas_species_idx),
     _reactant_gas_species_idx(reactant_gas_species_idx),
     _reactant_gas_var_idx(species_vars[reactant_gas_species_idx]),
     _reactant_solid_species_idx(reactant_solid_species_idx),
     _product_species_idx(product_species_idx),
     _product_var_idx(species_vars[product_species_idx])
   {}
template<typename Chemistry > GRINS::GasSolidCatalyticWall< Chemistry >::GasSolidCatalyticWall (const Chemistry & chem_mixture, CatalycityBase & gamma, const unsigned int reactant_gas_species_idx, const unsigned int reactant_solid_species_idx, const unsigned int product_species_idx)
Deprecated.
Definition at line 54 of file gas_solid_catalytic_wall.C.
     : CatalyticWallBase<Chemistry>(chem_mixture,gamma,reactant_gas_species_idx),
     _reactant_gas_species_idx(reactant_gas_species_idx),
     _reactant_solid_species_idx(reactant_solid_species_idx),
     _product_species_idx(product_species_idx)
   {
     libmesh_deprecated();
   }
template<typename Chemistry> virtual GRINS::GasSolidCatalyticWall< Chemistry >::~GasSolidCatalyticWall () inline virtual
Definition at line 56 of file gas_solid_catalytic_wall.h.
 {};
Member Function Documentation
template<typename Chemistry > void GRINS::GasSolidCatalyticWall< Chemistry >::apply_fluxes (AssemblyContext & context, const CachedValues & cache, const bool request_jacobian) virtual
Deprecated.
Implements GRINS::CatalyticWallBase< Chemistry >.
Definition at line 159 of file gas_solid_catalytic_wall.C.
References GRINS::CachedValues::get_cached_values(), GRINS::CachedValues::get_cached_vector_values(), GRINS::Physics::is_axisymmetric(), GRINS::Cache::MASS_FRACTIONS, GRINS::Cache::MIXTURE_DENSITY, and GRINS::Cache::TEMPERATURE.
   {
     libmesh_do_once(libmesh_deprecated());
     libMesh::FEGenericBase<libMesh::Real>* side_fe = NULL;
     context.get_side_fe( _reactant_gas_var_idx, side_fe );
     // The number of local degrees of freedom in each variable.
     const unsigned int n_var_dofs = context.get_dof_indices(_reactant_gas_var_idx).size();
     libmesh_assert_equal_to( n_var_dofs, context.get_dof_indices(_product_var_idx).size() );
     // Element Jacobian * quadrature weight for side integration.
     const std::vector<libMesh::Real> &JxW_side = side_fe->get_JxW();
     // The var shape functions at side quadrature points.
     const std::vector<std::vector<libMesh::Real> >& var_phi_side = side_fe->get_phi();
     // Physical location of the quadrature points
     const std::vector<libMesh::Point>& var_qpoint = side_fe->get_xyz();
     // reactant residual
     libMesh::DenseSubVector<libMesh::Number> &F_r_var = context.get_elem_residual(_reactant_gas_var_idx);
     // product residual
     libMesh::DenseSubVector<libMesh::Number> &F_p_var = context.get_elem_residual(_product_var_idx);
     unsigned int n_qpoints = context.get_side_qrule().n_points();
     for (unsigned int qp=0; qp != n_qpoints; qp++)
       {
         libMesh::Real jac = JxW_side[qp];
         if(Physics::is_axisymmetric())
           {
             const libMesh::Number r = var_qpoint[qp](0);
             jac *= r;
           }
         const libMesh::Real rho = cache.get_cached_values(Cache::MIXTURE_DENSITY)[qp];
         const libMesh::Real Y_r = cache.get_cached_vector_values(Cache::MASS_FRACTIONS)[qp][this->_reactant_gas_species_idx];
         const libMesh::Real T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
         const libMesh::Real r_value = this->compute_reactant_gas_mass_flux(rho, Y_r, T);
         const libMesh::Real p_value = this->compute_product_mass_flux(rho, Y_r, T);
         for (unsigned int i=0; i != n_var_dofs; i++)
           {
             F_r_var(i) += r_value*var_phi_side[i][qp]*jac;
             F_p_var(i) += p_value*var_phi_side[i][qp]*jac;
             if( request_jacobian )
               {
                 libmesh_not_implemented();
               }
           }
       }
     return;
   }
template<typename Chemistry > libMesh::Real GRINS::GasSolidCatalyticWall< Chemistry >::compute_product_mass_flux (const libMesh::Real rho, const libMesh::Real Y_r, const libMesh::Real T) inline
Definition at line 136 of file gas_solid_catalytic_wall.h.
Referenced by test().
   {
     const libMesh::Real rho_r = rho*Y_r;
     const libMesh::Real M_r = this->_chemistry.M(_reactant_gas_species_idx);
     const libMesh::Real M_p = this->_chemistry.M(_product_species_idx);
     const libMesh::Real omega_dot = this->omega_dot( rho_r, T )*M_p/M_r;
     return omega_dot;
   }
template<typename Chemistry > libMesh::Real GRINS::GasSolidCatalyticWall< Chemistry >::compute_reactant_gas_mass_flux (const libMesh::Real rho, const libMesh::Real Y_r, const libMesh::Real T) inline
Definition at line 106 of file gas_solid_catalytic_wall.h.
Referenced by test().
   {
     const libMesh::Real rho_r = rho*Y_r;
     const libMesh::Real omega_dot = this->omega_dot( rho_r, T );
     return -omega_dot;
   }
template<typename Chemistry > libMesh::Real GRINS::GasSolidCatalyticWall< Chemistry >::compute_reactant_solid_mass_consumption (const libMesh::Real rho, const libMesh::Real Y_r, const libMesh::Real T) inline
Definition at line 119 of file gas_solid_catalytic_wall.h.
Referenced by test().
   {
     const libMesh::Real rho_r = rho*Y_r;
     const libMesh::Real M_r = this->_chemistry.M(_reactant_gas_species_idx);
     const libMesh::Real M_solid = this->_chemistry.M(_reactant_solid_species_idx);
     const libMesh::Real omega_dot = this->omega_dot( rho_r, T )*M_solid/M_r;
     return -omega_dot;
   }
template<typename Chemistry > libMesh::Real GRINS::GasSolidCatalyticWall< Chemistry >::compute_reactant_solid_mass_consumption_dT (const libMesh::Real rho, const libMesh::Real Y_r, const libMesh::Real T) inline
Definition at line 153 of file gas_solid_catalytic_wall.h.
   {
     const libMesh::Real rho_r = rho*Y_r;
     const libMesh::Real M_r = this->_chemistry.M(_reactant_gas_species_idx);
     const libMesh::Real M_solid = this->_chemistry.M(_reactant_solid_species_idx);
     const libMesh::Real domega_dot_dT = this->domega_dot_dT( rho_r, T )*M_solid/M_r;
     return -domega_dot_dT;
   }
template<typename Chemistry > libMesh::Real GRINS::GasSolidCatalyticWall< Chemistry >::compute_reactant_solid_mass_consumption_dYs (const libMesh::Real rho, const std::vector< libMesh::Real > Y, const libMesh::Real T) inline
Definition at line 170 of file gas_solid_catalytic_wall.h.
   {
     const libMesh::Real Y_r = Y[_reactant_gas_species_idx];
     const libMesh::Real rho_r = rho*Y_r;
     const libMesh::Real M_r = this->_chemistry.M(_reactant_gas_species_idx);
     const libMesh::Real M_solid = this->_chemistry.M(_reactant_solid_species_idx);
     const libMesh::Real R = this->_chemistry.R_mix(Y);
     const libMesh::Real domega_dot_dYs = this->domega_dot_dws( rho_r, Y_r, T, R )*M_solid/M_r;
     return -domega_dot_dYs;
   }
template<typename Chemistry > bool GRINS::GasSolidCatalyticWall< Chemistry >::eval_flux (bool compute_jacobian, AssemblyContext & context, libMesh::Real sign, bool is_axisymmetric) virtual
Implements GRINS::NeumannBCAbstract.
Definition at line 87 of file gas_solid_catalytic_wall.C.
   {
     libMesh::FEGenericBase<libMesh::Real>* side_fe = NULL;
     context.get_side_fe( _reactant_gas_var_idx, side_fe );
     // The number of local degrees of freedom in each variable.
     const unsigned int n_var_dofs = context.get_dof_indices(_reactant_gas_var_idx).size();
     libmesh_assert_equal_to( n_var_dofs, context.get_dof_indices(_product_var_idx).size() );
     // Element Jacobian * quadrature weight for side integration.
     const std::vector<libMesh::Real> &JxW_side = side_fe->get_JxW();
     // The var shape functions at side quadrature points.
     const std::vector<std::vector<libMesh::Real> >& var_phi_side = side_fe->get_phi();
     // Physical location of the quadrature points
     const std::vector<libMesh::Point>& var_qpoint = side_fe->get_xyz();
     // reactant residual
     libMesh::DenseSubVector<libMesh::Number> &F_r_var = context.get_elem_residual(_reactant_gas_var_idx);
     // product residual
     libMesh::DenseSubVector<libMesh::Number> &F_p_var = context.get_elem_residual(_product_var_idx);
     unsigned int n_qpoints = context.get_side_qrule().n_points();
     for (unsigned int qp=0; qp != n_qpoints; qp++)
       {
         libMesh::Real jac = JxW_side[qp];
         if(is_axisymmetric)
           {
             const libMesh::Number r = var_qpoint[qp](0);
             jac *= r;
           }
         std::vector<libMesh::Real> mass_fractions(this->_chem_ptr->n_species());
         for( unsigned int s = 0; s < this->_chem_ptr->n_species(); s++ )
           mass_fractions[s] = context.side_value(this->_species_vars[s], qp);
         libMesh::Real T =  context.side_value(this->_T_var, qp);
         libMesh::Real R_mix = this->_chem_ptr->R_mix(mass_fractions);
         libMesh::Real rho = this->rho( T, this->_p0, R_mix );
         libMesh::Real Y_r = mass_fractions[this->_reactant_gas_species_idx];
         const libMesh::Real r_value = this->compute_reactant_gas_mass_flux(rho, Y_r, T);
         const libMesh::Real p_value = this->compute_product_mass_flux(rho, Y_r, T);
         for (unsigned int i=0; i != n_var_dofs; i++)
           {
             F_r_var(i) += sign*r_value*var_phi_side[i][qp]*jac;
             F_p_var(i) += sign*p_value*var_phi_side[i][qp]*jac;
             if( compute_jacobian )
               {
                 libmesh_not_implemented();
               }
           }
       }
     // We're not computing the Jacobian yet
     return false;
   }
template<typename Chemistry > void GRINS::GasSolidCatalyticWall< Chemistry >::init (const libMesh::FEMSystem & system) virtual
Deprecated.
Reimplemented from GRINS::CatalyticWallBase< Chemistry >.
Definition at line 68 of file gas_solid_catalytic_wall.C.
   {
     libmesh_do_once(libmesh_deprecated());
     const std::string r_var_name = std::string("w_"+this->_chemistry.species_name( this->_reactant_gas_species_idx ) );
     const std::string p_var_name = std::string("w_"+this->_chemistry.species_name( this->_product_species_idx ) );
     libmesh_assert( system.has_variable( r_var_name ) );
     libmesh_assert( system.has_variable( p_var_name ) );
     this->_reactant_gas_var_idx = system.variable_number( r_var_name );
     this->_product_var_idx = system.variable_number( p_var_name );
     return;
   }
Member Data Documentation
template<typename Chemistry> const unsigned int GRINS::GasSolidCatalyticWall< Chemistry >::_product_species_idx protected
Definition at line 99 of file gas_solid_catalytic_wall.h.
template<typename Chemistry> VariableIndex GRINS::GasSolidCatalyticWall< Chemistry >::_product_var_idx protected
Definition at line 100 of file gas_solid_catalytic_wall.h.
template<typename Chemistry> const unsigned int GRINS::GasSolidCatalyticWall< Chemistry >::_reactant_gas_species_idx protected
Definition at line 94 of file gas_solid_catalytic_wall.h.
template<typename Chemistry> VariableIndex GRINS::GasSolidCatalyticWall< Chemistry >::_reactant_gas_var_idx protected
Definition at line 95 of file gas_solid_catalytic_wall.h.
template<typename Chemistry> const unsigned int GRINS::GasSolidCatalyticWall< Chemistry >::_reactant_solid_species_idx protected
Definition at line 97 of file gas_solid_catalytic_wall.h.
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/gas_solid_catalytic_wall.h
src/boundary_conditions/src/gas_solid_catalytic_wall.C