GRINS-0.8.0: GRINS::VariableBuilder Class Reference
GRINS::VariableBuilder Class Reference abstract
Manages runtime construction of the FEVariableBase objects.
#include <variable_builder.h>
Public Member Functions
VariableBuilder ()
~VariableBuilder ()
virtual void build_variables_impl (const GetPot &input, MultiphysicsSystem &system)=0
Implementation of Variable construction done in subclasses.
Static Public Member Functions
static void build_variables (const GetPot &input, MultiphysicsSystem &system)
Protected Member Functions
void add_variable_to_warehouse (SharedPtr< FEVariablesBase > &fe_var, const std::string &var_name)
Adds/registers the fe_var to VariableWarehouse.
void add_vars_to_system (MultiphysicsSystem &system, const std::vector< std::string > &var_names, const std::string &fe_family, const std::string &order, std::vector< VariableIndex > &var_indices, const std::set< libMesh::subdomain_id_type > &subdomain_ids)
Given the names, family, and order, this adds the variables to the system and populates var_indices.
SharedPtr< FEVariablesBase > build_fe_var (const std::string &var_type, const std::vector< std::string > &var_names, const std::vector< VariableIndex > &var_indices, const std::set< libMesh::subdomain_id_type > &subdomain_ids)
Sets appropriate data in the VariableFactoryAbstract and calls VariableFactoryAbstract::build()
Detailed Description
Manages runtime construction of the FEVariableBase objects.
build_variables() is intended to be called before building the Physics and boundary conditions so that the VariableWarhouse is populated and can be referenced by the Physics and boundary conditions.
Definition at line 47 of file variable_builder.h.
Constructor & Destructor Documentation
GRINS::VariableBuilder::VariableBuilder () inline
Definition at line 51 of file variable_builder.h.
 {}
GRINS::VariableBuilder::~VariableBuilder () inline
Definition at line 52 of file variable_builder.h.
 {}
Member Function Documentation
void GRINS::VariableBuilder::add_variable_to_warehouse (SharedPtr< FEVariablesBase > & fe_var, const std::string & var_name) protected
Adds/registers the fe_var to VariableWarehouse.
Definition at line 49 of file variable_builder.C.
References GRINS::GRINSPrivate::VariableWarehouse::register_variable().
Referenced by GRINS::DefaultVariableBuilder::build_variables_impl().
   {
     GRINSPrivate::VariableWarehouse::register_variable(var_name,fe_var);
   }
void GRINS::VariableBuilder::add_vars_to_system (MultiphysicsSystem & system, const std::vector< std::string > & var_names, const std::string & fe_family, const std::string & order, std::vector< VariableIndex > & var_indices, const std::set< libMesh::subdomain_id_type > & subdomain_ids) protected
Given the names, family, and order, this adds the variables to the system and populates var_indices.
The var_indices are the respective indices returned by the System from the add_variable call.
Definition at line 55 of file variable_builder.C.
Referenced by GRINS::DefaultVariableBuilder::build_variables_impl().
   {
     const unsigned int n_vars = var_names.size();
     // Setup var_indices
     libmesh_assert( var_indices.empty() );
     var_indices.resize(n_vars);
     if( subdomain_ids.empty() )
       for( unsigned int v = 0; v < n_vars; v++ )
         var_indices[v] = system.add_variable( var_names[v],
                                               libMesh::Utility::string_to_enum<GRINSEnums::Order>(order),
                                               libMesh::Utility::string_to_enum<GRINSEnums::FEFamily>(fe_family) );
     else
       for( unsigned int v = 0; v < n_vars; v++ )
         var_indices[v] = system.add_variable( var_names[v],
                                               libMesh::Utility::string_to_enum<GRINSEnums::Order>(order),
                                               libMesh::Utility::string_to_enum<GRINSEnums::FEFamily>(fe_family),
                                               &subdomain_ids );
   }
SharedPtr< FEVariablesBase > GRINS::VariableBuilder::build_fe_var (const std::string & var_type, const std::vector< std::string > & var_names, const std::vector< VariableIndex > & var_indices, const std::set< libMesh::subdomain_id_type > & subdomain_ids) protected
Sets appropriate data in the VariableFactoryAbstract and calls VariableFactoryAbstract::build()
Definition at line 82 of file variable_builder.C.
References GRINS::FactoryAbstract< FEVariablesBase >::build(), GRINS::VariableFactoryAbstract::set_subdomain_ids(), GRINS::VariableFactoryAbstract::set_var_indices(), and GRINS::VariableFactoryAbstract::set_var_names().
Referenced by GRINS::DefaultVariableBuilder::build_variables_impl().
   {
     // Setup VariableFactory
     VariableFactoryAbstract::set_var_names(var_names);
     VariableFactoryAbstract::set_var_indices(var_indices);
     VariableFactoryAbstract::set_subdomain_ids(subdomain_ids);
     libMesh::UniquePtr<FEVariablesBase> var = VariableFactoryAbstract::build(var_type);
     // Need to return a SharedPtr, so release from the UniquePtr we got back
     return SharedPtr<FEVariablesBase>( var.release() );
   }
void GRINS::VariableBuilder::build_variables (const GetPot & input, MultiphysicsSystem & system) static
Definition at line 40 of file variable_builder.C.
References GRINS::DefaultVariableBuilder::build_variables_impl().
Referenced by GRINS::Simulation::init_multiphysics_system(), GRINSTesting::VariablesTest::test_var_constraint(), GRINSTesting::VariablesTest::test_variable_arbitrary_names(), and GRINSTesting::VariablesTest::test_variable_builder().
   {
     DefaultVariableBuilder var_builder;
     // Defer the construction to the builder subclass implementation
     var_builder.build_variables_impl(input,system);
   }
virtual void GRINS::VariableBuilder::build_variables_impl (const GetPot & input, MultiphysicsSystem & system) pure virtual
Implementation of Variable construction done in subclasses.
Implemented in GRINS::DefaultVariableBuilder.
The documentation for this class was generated from the following files:
src/variables/include/grins/variable_builder.h
src/variables/src/variable_builder.C