GRINS-0.8.0: GRINSTesting::BuilderHelperTest Class Reference
GRINSTesting::BuilderHelperTest Class Reference
Public Member Functions
CPPUNIT_TEST_SUITE (BuilderHelperTest)
CPPUNIT_TEST (test_parse_var_sections)
CPPUNIT_TEST_SUITE_END ()
void tearDown ()
void test_parse_var_sections ()
Public Member Functions inherited from GRINS::BuilderHelper
BuilderHelper ()
~BuilderHelper ()
Additional Inherited Members
Static Public Member Functions inherited from GRINS::BuilderHelper
static void parse_var_sections (const GetPot &input, std::set< std::string > &sections)
Parses the input file for [Variables] first-level subsections.
static void parse_var_sections_vector (const GetPot &input, std::vector< std::string > &sections)
The same as parse_var_sections, except the result is returned in an std::vector.
Protected Member Functions inherited from GRINSTesting::SystemHelper
void setup_multiphysics_system (const std::string &filename)
void reset_all ()
Protected Attributes inherited from GRINSTesting::SystemHelper
libMesh::UniquePtr< GetPot > _input
GRINS::SharedPtr< libMesh::UnstructuredMesh > _mesh
libMesh::UniquePtr< libMesh::EquationSystems > _es
GRINS::MultiphysicsSystem * _system
Detailed Description
Definition at line 47 of file builder_helper.C.
Member Function Documentation
GRINSTesting::BuilderHelperTest::CPPUNIT_TEST (test_parse_var_sections)
GRINSTesting::BuilderHelperTest::CPPUNIT_TEST_SUITE (BuilderHelperTest)
GRINSTesting::BuilderHelperTest::CPPUNIT_TEST_SUITE_END ()
void GRINSTesting::BuilderHelperTest::tearDown () inline
Definition at line 60 of file builder_helper.C.
References GRINSTesting::SystemHelper::reset_all().
     {
       this->reset_all();
     }
void GRINSTesting::BuilderHelperTest::test_parse_var_sections () inline
Definition at line 65 of file builder_helper.C.
References GRINSTesting::SystemHelper::_input, GRINS::BuilderHelper::parse_var_sections(), and GRINSTesting::SystemHelper::setup_multiphysics_system().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/default_bc_builder.in";
       this->setup_multiphysics_system(filename);
       // Now we can parse the variable sections and names
       std::set<std::string> sections;
       this->parse_var_sections(*_input,sections);
       // Make sure we have the right sections
       CPPUNIT_ASSERT_EQUAL(4,(int)sections.size());
       CPPUNIT_ASSERT( sections.find("Velocity") != sections.end() );
       CPPUNIT_ASSERT( sections.find("Pressure") != sections.end() );
       CPPUNIT_ASSERT( sections.find("Temperature") != sections.end() );
       CPPUNIT_ASSERT( sections.find("SpeciesMassFractions") != sections.end() );
     }
The documentation for this class was generated from the following file:
test/unit/builder_helper.C