GRINS-0.8.0: GRINSTesting::RayfireTestAMR Class Reference
GRINSTesting::RayfireTestAMR Class Reference
Public Member Functions
CPPUNIT_TEST_SUITE (RayfireTestAMR)
CPPUNIT_TEST (single_elems)
CPPUNIT_TEST (through_vertex_postrefinment)
CPPUNIT_TEST (near_vertex_postrefinement)
CPPUNIT_TEST (large_2D_mesh)
CPPUNIT_TEST (refine_elem_not_on_rayfire)
CPPUNIT_TEST (multiple_refinements)
CPPUNIT_TEST (coarsen_elements)
CPPUNIT_TEST (refine_and_coarsen)
CPPUNIT_TEST (mixed_type_mesh)
CPPUNIT_TEST (start_with_refined_mesh)
CPPUNIT_TEST (refined_above_unrefined)
CPPUNIT_TEST (refine_deformed_elem)
CPPUNIT_TEST (refine_deformed_elem_near_tolerance)
CPPUNIT_TEST (init_on_refined_mesh)
CPPUNIT_TEST_SUITE_END ()
void single_elems ()
Refine a single element.
void through_vertex_postrefinment ()
After refinement, the rayfire will travel through a vertex.
void near_vertex_postrefinement ()
After refinement, the rayfire will travel very near (but not through) a vertex.
void large_2D_mesh ()
A 10x10 mesh with selectively refined elements.
void refine_elem_not_on_rayfire ()
Make sure refined elements not on the rayfire do not get added.
void multiple_refinements ()
Test for multiple successive refinements.
void coarsen_elements ()
Test of the coarsening functionality.
void refine_and_coarsen ()
Refine and coarsen before calling reinit()
void mixed_type_mesh ()
Mesh contains 2 QUAD4 and 2 TRI3.
void start_with_refined_mesh ()
Mesh given to init() is already refined.
void refined_above_unrefined ()
2 QUAD4 elems, one is refined, one if not, rayfire travels boundary between them
void refine_deformed_elem ()
QUAD4 elem is deformed, rayfire goes within libMesh::TOLERANCE central node.
void refine_deformed_elem_near_tolerance ()
void init_on_refined_mesh ()
Private Member Functions
libMesh::Real calc_theta (libMesh::Point &start, libMesh::Point end)
GRINS::SharedPtr< libMesh::UnstructuredMesh > build_mesh (const GetPot &input)
GRINS::SharedPtr< libMesh::UnstructuredMesh > build_quad4_elem ()
Build a single square QUAD4.
GRINS::SharedPtr< libMesh::UnstructuredMesh > build_quad9_elem ()
Build a single square QUAD9.
void test_single_elem (GRINS::SharedPtr< libMesh::UnstructuredMesh > mesh)
Runs the test on single square QUADs of unit length and width.
void test_through_vertex (GRINS::SharedPtr< libMesh::UnstructuredMesh > mesh)
void test_near_vertex (GRINS::SharedPtr< libMesh::UnstructuredMesh > mesh)
void test_large_mesh (GRINS::SharedPtr< libMesh::UnstructuredMesh > mesh)
Refine specific elements on a large mesh.
void test_multiple_refinements (GRINS::SharedPtr< libMesh::UnstructuredMesh > mesh)
Refine the mesh 3 times.
void test_coarsen (GRINS::SharedPtr< libMesh::UnstructuredMesh > mesh)
Test coarsening specific elements on a large mesh.
void test_deformed_elem (GRINS::SharedPtr< libMesh::UnstructuredMesh > &mesh, libMesh::Point &origin, libMesh::Real theta, std::vector< unsigned int > &children_in_rayfire, std::vector< unsigned int > &children_not_in_rayfire)
Detailed Description
Definition at line 57 of file rayfireAMR_test.C.
Member Function Documentation
GRINS::SharedPtr<libMesh::UnstructuredMesh> GRINSTesting::RayfireTestAMR::build_mesh (const GetPot & input) inline private
Definition at line 503 of file rayfireAMR_test.C.
References GRINS::MeshBuilder::build(), and TestCommWorld.
Referenced by coarsen_elements(), init_on_refined_mesh(), large_2D_mesh(), mixed_type_mesh(), and refine_elem_not_on_rayfire().
     {
       GRINS::MeshBuilder mesh_builder;
       return mesh_builder.build( input, *TestCommWorld );
     }
GRINS::SharedPtr<libMesh::UnstructuredMesh> GRINSTesting::RayfireTestAMR::build_quad4_elem () inline private
Build a single square QUAD4.
Definition at line 510 of file rayfireAMR_test.C.
References TestCommWorld.
Referenced by multiple_refinements(), near_vertex_postrefinement(), refine_and_coarsen(), single_elems(), start_with_refined_mesh(), and through_vertex_postrefinment().
     {
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = new libMesh::SerialMesh(*TestCommWorld);
       mesh->set_mesh_dimension(2);
       mesh->add_point( libMesh::Point(0.0,0.0),0 );
       mesh->add_point( libMesh::Point(1.0,0.0),1 );
       mesh->add_point( libMesh::Point(1.0,1.0),2 );
       mesh->add_point( libMesh::Point(0.0,1.0),3 );
       libMesh::Elem* elem = mesh->add_elem( new libMesh::Quad4 );
       for (unsigned int n=0; n<4; n++)
         elem->set_node(n) = mesh->node_ptr(n);
       mesh->prepare_for_use();
       return mesh;
     }
GRINS::SharedPtr<libMesh::UnstructuredMesh> GRINSTesting::RayfireTestAMR::build_quad9_elem () inline private
Build a single square QUAD9.
Definition at line 531 of file rayfireAMR_test.C.
References TestCommWorld.
Referenced by multiple_refinements(), near_vertex_postrefinement(), single_elems(), and through_vertex_postrefinment().
     {
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = new libMesh::SerialMesh(*TestCommWorld);
       mesh->set_mesh_dimension(2);
       mesh->add_point( libMesh::Point(0.0,0.0),0 );
       mesh->add_point( libMesh::Point(1.0,0.0),1 );
       mesh->add_point( libMesh::Point(1.0,1.0),2 );
       mesh->add_point( libMesh::Point(0.0,1.0),3 );
       mesh->add_point( libMesh::Point(0.5,0.0),4 );
       mesh->add_point( libMesh::Point(1.0,0.5),5 );
       mesh->add_point( libMesh::Point(0.5,1.0),6 );
       mesh->add_point( libMesh::Point(0.0,0.5),7 );
       mesh->add_point( libMesh::Point(0.5,0.5),8 );
       libMesh::Elem* elem = mesh->add_elem( new libMesh::Quad9 );
       for (unsigned int n=0; n<9; n++)
         elem->set_node(n) = mesh->node_ptr(n);
       mesh->prepare_for_use();
       return mesh;
     }
libMesh::Real GRINSTesting::RayfireTestAMR::calc_theta (libMesh::Point & start, libMesh::Point end) inline private
Definition at line 498 of file rayfireAMR_test.C.
Referenced by mixed_type_mesh(), refine_and_coarsen(), refine_elem_not_on_rayfire(), start_with_refined_mesh(), test_coarsen(), test_large_mesh(), test_multiple_refinements(), test_near_vertex(), test_single_elem(), and test_through_vertex().
     {
       return std::atan2( (end(1)-start(1)), (end(0)-start(0)) );
     }
void GRINSTesting::RayfireTestAMR::coarsen_elements () inline
Test of the coarsening functionality.
Definition at line 166 of file rayfireAMR_test.C.
References build_mesh(), and test_coarsen().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/mesh_quad4_100elem_2D.in";
       GetPot input_quad4(filename);
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = this->build_mesh(input_quad4);
       test_coarsen(mesh);
       filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/mesh_quad9_100elem_2D.in";
       GetPot input_quad9(filename);
       mesh = this->build_mesh(input_quad9);
       test_coarsen(mesh);
     }
GRINSTesting::RayfireTestAMR::CPPUNIT_TEST (single_elems)
GRINSTesting::RayfireTestAMR::CPPUNIT_TEST (through_vertex_postrefinment)
GRINSTesting::RayfireTestAMR::CPPUNIT_TEST (near_vertex_postrefinement)
GRINSTesting::RayfireTestAMR::CPPUNIT_TEST (large_2D_mesh)
GRINSTesting::RayfireTestAMR::CPPUNIT_TEST (refine_elem_not_on_rayfire)
GRINSTesting::RayfireTestAMR::CPPUNIT_TEST (multiple_refinements)
GRINSTesting::RayfireTestAMR::CPPUNIT_TEST (coarsen_elements)
GRINSTesting::RayfireTestAMR::CPPUNIT_TEST (refine_and_coarsen)
GRINSTesting::RayfireTestAMR::CPPUNIT_TEST (mixed_type_mesh)
GRINSTesting::RayfireTestAMR::CPPUNIT_TEST (start_with_refined_mesh)
GRINSTesting::RayfireTestAMR::CPPUNIT_TEST (refined_above_unrefined)
GRINSTesting::RayfireTestAMR::CPPUNIT_TEST (refine_deformed_elem)
GRINSTesting::RayfireTestAMR::CPPUNIT_TEST (refine_deformed_elem_near_tolerance)
GRINSTesting::RayfireTestAMR::CPPUNIT_TEST (init_on_refined_mesh)
GRINSTesting::RayfireTestAMR::CPPUNIT_TEST_SUITE (RayfireTestAMR)
GRINSTesting::RayfireTestAMR::CPPUNIT_TEST_SUITE_END ()
void GRINSTesting::RayfireTestAMR::init_on_refined_mesh () inline
Call init() on an already refined mesh
Mimics a run from restart
Definition at line 463 of file rayfireAMR_test.C.
References build_mesh().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/mesh_quad4_9elem_2D.in";
       GetPot input_quad4(filename);
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = this->build_mesh(input_quad4);
       // refine elem 1 before rayfire init
       libMesh::MeshRefinement mr(*mesh);
       mesh->elem_ptr(1)->set_refinement_flag(libMesh::Elem::RefinementState::REFINE);
       mr.refine_elements();
       CPPUNIT_ASSERT( !(mesh->elem_ptr(1)->active()) );
       CPPUNIT_ASSERT( mesh->elem_ptr(1)->has_children() );
       libMesh::Point origin(0.0,0.1);
       libMesh::Real theta = 0.0;
       // initialize the rayfire
       GRINS::SharedPtr<GRINS::RayfireMesh> rayfire = new GRINS::RayfireMesh(origin,theta);
       rayfire->init(*mesh);
       // make sure we pick up the 2 unrefined elements
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(0) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(2) );
       // rayfire should not include elem 1 since it's INACTIVE
       CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem(1)) );
       // rayfire should contain children 0,1 of elem 1
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ref(1).child_ptr(0)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ref(1).child_ptr(1)->id()) );
     }
void GRINSTesting::RayfireTestAMR::large_2D_mesh () inline
A 10x10 mesh with selectively refined elements.
Definition at line 112 of file rayfireAMR_test.C.
References build_mesh(), and test_large_mesh().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/mesh_quad4_100elem_2D.in";
       GetPot input_quad4(filename);
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = this->build_mesh(input_quad4);
       test_large_mesh(mesh);
       filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/mesh_quad9_100elem_2D.in";
       GetPot input_quad9(filename);
       mesh = this->build_mesh(input_quad9);
       test_large_mesh(mesh);
     }
void GRINSTesting::RayfireTestAMR::mixed_type_mesh () inline
Mesh contains 2 QUAD4 and 2 TRI3.
Definition at line 217 of file rayfireAMR_test.C.
References build_mesh(), and calc_theta().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/mixed_quad_tri.in";
       GetPot input(filename);
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = this->build_mesh(input);
       libMesh::Point origin(0.0,0.25);
       libMesh::Point end_point(1.0,0.25);
       libMesh::Real theta = calc_theta(origin,end_point);
       GRINS::SharedPtr<GRINS::RayfireMesh> rayfire = new GRINS::RayfireMesh(origin,theta);
       rayfire->init(*mesh);
       // check that the rayfire is through the right elems
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(0) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(6) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(9) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(8) );
       // and not through others
       CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem(2)) );
       CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem(3)) );
       CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem(4)) );
       CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem(5)) );
       CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem(1)) );
       CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem(7)) );
       // now do a uniform refinement
       libMesh::MeshRefinement mr(*mesh);
       mr.uniformly_refine();
       rayfire->reinit(*mesh);
       // check post-refinement
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(0)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(1)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(6)->child_ptr(0)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(9)->child_ptr(1)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(8)->child_ptr(2)->id()) );
       // coarsen two of the TRIs
       for (unsigned int c=0; c<mesh->elem_ptr(6)->n_children(); c++)
         {
           mesh->elem_ptr(6)->child_ptr(c)->set_refinement_flag(libMesh::Elem::RefinementState::COARSEN);
           mesh->elem_ptr(9)->child_ptr(c)->set_refinement_flag(libMesh::Elem::RefinementState::COARSEN);
         }
       mr.coarsen_elements();
       rayfire->reinit(*mesh);
       CPPUNIT_ASSERT( mesh->elem_ptr(6)->active() );
       CPPUNIT_ASSERT( mesh->elem_ptr(9)->active() );
       // check post-coarsen
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(0)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(1)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(8)->child_ptr(2)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(6) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(9) );
       for (unsigned int c=0; c<mesh->elem_ptr(6)->n_children(); c++)
         {
           CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem(mesh->elem_ptr(6)->child_ptr(c)->id())) );
           CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem(mesh->elem_ptr(9)->child_ptr(c)->id())) );
         }
     }
void GRINSTesting::RayfireTestAMR::multiple_refinements () inline
Test for multiple successive refinements.
Definition at line 156 of file rayfireAMR_test.C.
References build_quad4_elem(), build_quad9_elem(), and test_multiple_refinements().
     {
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = build_quad4_elem();
       test_multiple_refinements(mesh);
       mesh = build_quad9_elem();
       test_multiple_refinements(mesh);
     }
void GRINSTesting::RayfireTestAMR::near_vertex_postrefinement () inline
After refinement, the rayfire will travel very near (but not through) a vertex.
Definition at line 102 of file rayfireAMR_test.C.
References build_quad4_elem(), build_quad9_elem(), and test_near_vertex().
     {
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = build_quad4_elem();
       test_near_vertex(mesh);
       mesh = build_quad9_elem();
       test_near_vertex(mesh);
     }
void GRINSTesting::RayfireTestAMR::refine_and_coarsen () inline
Refine and coarsen before calling reinit()
Definition at line 180 of file rayfireAMR_test.C.
References build_quad4_elem(), and calc_theta().
     {
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = build_quad4_elem();
       libMesh::Point origin(0.0,0.1);
       libMesh::Point end_point(1.0,0.1);
       libMesh::Real theta = calc_theta(origin,end_point);
       GRINS::SharedPtr<GRINS::RayfireMesh> rayfire = new GRINS::RayfireMesh(origin,theta);
       rayfire->init(*mesh);
       libMesh::MeshRefinement mr(*mesh);
       mr.uniformly_refine();
       rayfire->reinit(*mesh);
       mr.uniformly_refine();
       rayfire->reinit(*mesh);
       // refine elem(0)->child_ptr(1)->child_ptr(1)
       mesh->elem_ptr(0)->child_ptr(1)->child_ptr(1)->set_refinement_flag(libMesh::Elem::RefinementState::REFINE);
       // coarsen elem(0)->child_ptr(0)
       for (unsigned int c=0; c<mesh->elem_ptr(0)->child_ptr(0)->n_children(); c++)
         mesh->elem_ptr(0)->child_ptr(0)->child_ptr(c)->set_refinement_flag(libMesh::Elem::RefinementState::COARSEN);
       mr.refine_and_coarsen_elements();
       rayfire->reinit(*mesh);
       CPPUNIT_ASSERT( mesh->elem_ptr(0)->child_ptr(0)->active() );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(0)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(1)->child_ptr(0)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(1)->child_ptr(1)->child_ptr(0)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(1)->child_ptr(1)->child_ptr(1)->id()) );
     }
void GRINSTesting::RayfireTestAMR::refine_deformed_elem () inline
QUAD4 elem is deformed, rayfire goes within libMesh::TOLERANCE central node.
Definition at line 385 of file rayfireAMR_test.C.
References test_deformed_elem(), and TestCommWorld.
     {
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = new libMesh::SerialMesh(*TestCommWorld);
       mesh->set_mesh_dimension(2);
       mesh->add_point( libMesh::Point(0.0,0.0),0 );
       mesh->add_point( libMesh::Point(1.0,0.0),1 );
       mesh->add_point( libMesh::Point(1.1,1.1),2 );
       mesh->add_point( libMesh::Point(0.2,1.0),3 );
       libMesh::Elem* e = mesh->add_elem( new libMesh::Quad4 );
       for (unsigned int n=0; n<4; n++)
         e->set_node(n) = mesh->node_ptr(n);
       mesh->prepare_for_use();
       CPPUNIT_ASSERT_EQUAL( mesh->n_elem(), (libMesh::dof_id_type)1 );
       libMesh::Real y = 0.5250005;
       libMesh::Real x = y/5.0;
       libMesh::Point origin(x,y); // within libMesh::TOLERANCE of node 8
       libMesh::Real theta = 0.0;
       std::vector<unsigned int> children_in_rayfire;
       children_in_rayfire.push_back(1);
       children_in_rayfire.push_back(2);
       children_in_rayfire.push_back(3);
       std::vector<unsigned int> children_not_in_rayfire;
       children_not_in_rayfire.push_back(0);
       this->test_deformed_elem(mesh,origin,theta,children_in_rayfire,children_not_in_rayfire);
     }
void GRINSTesting::RayfireTestAMR::refine_deformed_elem_near_tolerance () inline
QUAD4 elem is slightly deformed, rayfire starts and ends very neay boundary of refined children.
Based on an element from a larger mesh, hence the seemingly arbitrary coordinates
Definition at line 424 of file rayfireAMR_test.C.
References test_deformed_elem(), and TestCommWorld.
     {
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = new libMesh::SerialMesh(*TestCommWorld);
       mesh->set_mesh_dimension(2);
       mesh->add_point( libMesh::Point(0.26591876082146976,0.016285303166482301),2 );
       mesh->add_point( libMesh::Point(0.26539426622418877,0.016285726631637167),3 );
       mesh->add_point( libMesh::Point(0.26538091506882988,0.015714299294800886),0 );
       mesh->add_point( libMesh::Point(0.26590538328042834,0.015713833483130532),1 );
       libMesh::Elem* e = mesh->add_elem( new libMesh::Quad4 );
       for (unsigned int n=0; n<4; n++)
         e->set_node(n) = mesh->node_ptr(n);
       mesh->prepare_for_use();
       CPPUNIT_ASSERT_EQUAL( mesh->n_elem(), (libMesh::dof_id_type)1 );
       libMesh::Real x = 0.26538759034362924;
       libMesh::Real y = 0.01600000000000000;
       libMesh::Point origin(x,y);
       libMesh::Real theta = 0.0;
       std::vector<unsigned int> children_in_rayfire;
       children_in_rayfire.push_back(0);
       children_in_rayfire.push_back(2);
       children_in_rayfire.push_back(3);
       std::vector<unsigned int> children_not_in_rayfire;
       children_not_in_rayfire.push_back(1);
       this->test_deformed_elem(mesh,origin,theta,children_in_rayfire,children_not_in_rayfire);
     }
void GRINSTesting::RayfireTestAMR::refine_elem_not_on_rayfire () inline
Make sure refined elements not on the rayfire do not get added.
Definition at line 126 of file rayfireAMR_test.C.
References build_mesh(), and calc_theta().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/mesh_quad4_100elem_2D.in";
       GetPot input(filename);
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = this->build_mesh(input);
       libMesh::Point origin(0.0,6.5);
       libMesh::Point end_point(10.0,0.25);
       libMesh::Real theta = calc_theta(origin,end_point);
       GRINS::SharedPtr<GRINS::RayfireMesh> rayfire = new GRINS::RayfireMesh(origin,theta);
       rayfire->init(*mesh);
       // elem 0 is not along the rayfire
       mesh->elem_ptr(0)->set_refinement_flag(libMesh::Elem::RefinementState::REFINE);
       libMesh::MeshRefinement mr(*mesh);
       mr.refine_elements();
       rayfire->reinit(*mesh);
       // elem 0 should not be in the rayfire
       CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->id()) ) );
       // no children of elem 0 should be in the rayfire
       for (unsigned int i=0; i<4; i++)
         CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem( mesh->elem_ptr(0)->child_ptr(i)->id() ) ) );
     }
void GRINSTesting::RayfireTestAMR::refined_above_unrefined () inline
2 QUAD4 elems, one is refined, one if not, rayfire travels boundary between them
Definition at line 334 of file rayfireAMR_test.C.
References TestCommWorld.
{
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = new libMesh::SerialMesh(*TestCommWorld);
       mesh->set_mesh_dimension(2);
       mesh->add_point( libMesh::Point(0.0,0.0),0 );
       mesh->add_point( libMesh::Point(1.0,0.0),1 );
       mesh->add_point( libMesh::Point(1.0,1.0),2 );
       mesh->add_point( libMesh::Point(0.0,1.0),3 );
       mesh->add_point( libMesh::Point(1.0,2.0),4 );
       mesh->add_point( libMesh::Point(0.0,2.0),5 );
       libMesh::Elem* elem0 = mesh->add_elem( new libMesh::Quad4 );
       elem0->set_node(0) = mesh->node_ptr(0);
       elem0->set_node(1) = mesh->node_ptr(1);
       elem0->set_node(2) = mesh->node_ptr(2);
       elem0->set_node(3) = mesh->node_ptr(3);
       libMesh::Elem* elem1 = mesh->add_elem( new libMesh::Quad4 );
       elem1->set_node(0) = mesh->node_ptr(3);
       elem1->set_node(1) = mesh->node_ptr(2);
       elem1->set_node(2) = mesh->node_ptr(4);
       elem1->set_node(3) = mesh->node_ptr(5);
       mesh->prepare_for_use();
       libMesh::Point origin(0.0,1.0);
       libMesh::Real theta = 0.0;
       GRINS::SharedPtr<GRINS::RayfireMesh> rayfire = new GRINS::RayfireMesh(origin,theta);
       rayfire->init(*mesh);
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(elem0->id()) );
       CPPUNIT_ASSERT( !rayfire->map_to_rayfire_elem(elem1->id()) );
       elem0->set_refinement_flag(libMesh::Elem::RefinementState::REFINE);
       libMesh::MeshRefinement mr(*mesh);
       mr.refine_elements();
       rayfire->reinit(*mesh);
       CPPUNIT_ASSERT( !rayfire->map_to_rayfire_elem(elem1->id()) );
       CPPUNIT_ASSERT( !rayfire->map_to_rayfire_elem(elem0->child_ptr(0)->id()) );
       CPPUNIT_ASSERT( !rayfire->map_to_rayfire_elem(elem0->child_ptr(1)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(elem0->child_ptr(2)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(elem0->child_ptr(3)->id()) );
     }
void GRINSTesting::RayfireTestAMR::single_elems () inline
Refine a single element.
Definition at line 82 of file rayfireAMR_test.C.
References build_quad4_elem(), build_quad9_elem(), and test_single_elem().
     {
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = build_quad4_elem();
       test_single_elem(mesh);
       mesh = build_quad9_elem();
       test_single_elem(mesh);
     }
void GRINSTesting::RayfireTestAMR::start_with_refined_mesh () inline
Mesh given to init() is already refined.
Definition at line 285 of file rayfireAMR_test.C.
References build_quad4_elem(), and calc_theta().
     {
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = build_quad4_elem();
       // uniform refinement
       libMesh::MeshRefinement mr(*mesh);
       mr.uniformly_refine();
       // now init the rayfire
       libMesh::Point origin(0.0,0.1);
       libMesh::Point end_point(1.0,0.1);
       libMesh::Real theta = calc_theta(origin,end_point);
       GRINS::SharedPtr<GRINS::RayfireMesh> rayfire = new GRINS::RayfireMesh(origin,theta);
       rayfire->init(*mesh);
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(0)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(1)->id()) );
       CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(2)->id())) );
       CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(3)->id())) );
       // refine again
       mr.uniformly_refine();
       rayfire->reinit(*mesh);
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(0)->child_ptr(0)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(0)->child_ptr(1)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(1)->child_ptr(0)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(1)->child_ptr(1)->id()) );
       // uniformly coarsen twice to get back to a single elem
       mr.uniformly_coarsen();
       rayfire->reinit(*mesh);
       mr.uniformly_coarsen();
       rayfire->reinit(*mesh);
       // ensure the original elem is active
       CPPUNIT_ASSERT( mesh->elem_ptr(0)->active() );
       // the original elem should be in the rayfire
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(0) );
       // and no other elem
       for (unsigned int e=1; e<mesh->n_elem(); e++)
         CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem(e)) );
     }
void GRINSTesting::RayfireTestAMR::test_coarsen (GRINS::SharedPtr< libMesh::UnstructuredMesh > mesh) inline private
Test coarsening specific elements on a large mesh.
Definition at line 778 of file rayfireAMR_test.C.
References calc_theta().
Referenced by coarsen_elements().
     {
       libMesh::Point origin(0.0,6.5);
       libMesh::Point end_point(10.0,0.25);
       libMesh::Real theta = calc_theta(origin,end_point);
       GRINS::SharedPtr<GRINS::RayfireMesh> rayfire = new GRINS::RayfireMesh(origin,theta);
       rayfire->init(*mesh);
       // unifromly refine the elements
       libMesh::MeshRefinement mr(*mesh);
       mr.uniformly_refine();
       rayfire->reinit(*mesh);
       // coarsen specific elements along the rayfire
       for(unsigned int c=0; c<4; c++)
         {
           mesh->elem_ptr(60)->child_ptr(c)->set_refinement_flag(libMesh::Elem::RefinementState::COARSEN);
           mesh->elem_ptr(25)->child_ptr(c)->set_refinement_flag(libMesh::Elem::RefinementState::COARSEN);
           mesh->elem_ptr(26)->child_ptr(c)->set_refinement_flag(libMesh::Elem::RefinementState::COARSEN);
           mesh->elem_ptr(9)->child_ptr(c)->set_refinement_flag(libMesh::Elem::RefinementState::COARSEN);
         }
       mr.coarsen_elements();
       rayfire->reinit(*mesh);
       // check that the coarsened elems are in the rayfire
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(60) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(25) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(26) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(9) );
       // and that their children are not
       for(unsigned int c=0; c<4; c++)
         {
           CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem(mesh->elem_ptr(60)->child_ptr(c)->id())) );
           CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem(mesh->elem_ptr(25)->child_ptr(c)->id())) );
           CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem(mesh->elem_ptr(26)->child_ptr(c)->id())) );
           CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem(mesh->elem_ptr(9)->child_ptr(c)->id())) );
         }
     }
void GRINSTesting::RayfireTestAMR::test_deformed_elem (GRINS::SharedPtr< libMesh::UnstructuredMesh > & mesh, libMesh::Point & origin, libMesh::Real theta, std::vector< unsigned int > & children_in_rayfire, std::vector< unsigned int > & children_not_in_rayfire) inline private
Definition at line 820 of file rayfireAMR_test.C.
Referenced by refine_deformed_elem(), and refine_deformed_elem_near_tolerance().
     {
       GRINS::SharedPtr<GRINS::RayfireMesh> rayfire = new GRINS::RayfireMesh(origin,theta);
       rayfire->init(*mesh);
       libMesh::Elem* elem = mesh->elem_ptr(0);
       CPPUNIT_ASSERT(elem);
       elem->set_refinement_flag(libMesh::Elem::RefinementState::REFINE);
       libMesh::MeshRefinement mr(*mesh);
       mr.refine_elements();
       rayfire->reinit(*mesh);
       for (unsigned int c=0; c<children_in_rayfire.size(); c++)
         CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(children_in_rayfire[c])->id()) );
       for (unsigned int c=0; c<children_not_in_rayfire.size(); c++)
         CPPUNIT_ASSERT( !rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(children_not_in_rayfire[c])->id()) );
     }
void GRINSTesting::RayfireTestAMR::test_large_mesh (GRINS::SharedPtr< libMesh::UnstructuredMesh > mesh) inline private
Refine specific elements on a large mesh.
Definition at line 655 of file rayfireAMR_test.C.
References calc_theta().
Referenced by large_2D_mesh().
     {
       libMesh::Point origin(0.0,6.5);
       libMesh::Point end_point(10.0,0.25);
       libMesh::Real theta = calc_theta(origin,end_point);
       GRINS::SharedPtr<GRINS::RayfireMesh> rayfire = new GRINS::RayfireMesh(origin,theta);
       rayfire->init(*mesh);
       // manually refine specific elements
       // map index 0: main_elem id to refine
       // map index 1: children that should be in the rayfire post-refinement
       std::map<unsigned int,std::vector<unsigned int> > refine_elems;
       refine_elems[60] = std::vector<unsigned int>();
       refine_elems[60].push_back(0);
       refine_elems[60].push_back(1);
       refine_elems[52] = std::vector<unsigned int>();
       refine_elems[52].push_back(0);
       refine_elems[34] = std::vector<unsigned int>();
       refine_elems[34].push_back(1);
       refine_elems[34].push_back(2);
       refine_elems[34].push_back(3);
       refine_elems[25] = std::vector<unsigned int>();
       refine_elems[25].push_back(3);
       refine_elems[26] = std::vector<unsigned int>();
       refine_elems[26].push_back(0);
       refine_elems[26].push_back(1);
       refine_elems[26].push_back(2);
       refine_elems[17] = std::vector<unsigned int>();
       refine_elems[17].push_back(2);
       refine_elems[17].push_back(3);
       refine_elems[9] = std::vector<unsigned int>();
       refine_elems[9].push_back(1);
       refine_elems[9].push_back(2);
       refine_elems[9].push_back(3);
       // check to make sure those elements are along the rayfire
       // and then set their refinement flags
       std::map<unsigned int,std::vector<unsigned int> >::iterator it = refine_elems.begin();
       for(; it != refine_elems.end(); it++)
         {
           libMesh::Elem* elem = mesh->elem_ptr( it->first );
           CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(elem->id()) );
           elem->set_refinement_flag(libMesh::Elem::RefinementState::REFINE);
         }
       // refine the elements
       libMesh::MeshRefinement mr(*mesh);
       mr.refine_elements();
       // reinitialize the rayfire
       rayfire->reinit(*mesh);
       // check the refined elements and their children
       it = refine_elems.begin();
       for(; it != refine_elems.end(); it++)
         {
           libMesh::Elem* elem = mesh->elem_ptr( it->first );
           // make sure it was refined
           CPPUNIT_ASSERT_EQUAL( elem->refinement_flag(), libMesh::Elem::RefinementState::INACTIVE );
           // make sure it was deleted from the rayfire
           CPPUNIT_ASSERT( !( rayfire->map_to_rayfire_elem(elem->id()) ) );
           // check that the computed children are in the rayfire
           // and that the rest are not
           std::vector<unsigned int> children = it->second;
           unsigned int index = 0;
           for(unsigned int c=0; c<elem->n_children(); c++)
             {
               if (index<children.size())
                 {
                   if (c==children[index])
                     {
                       index++;
                       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem( elem->child_ptr(c)->id() ) );
                     }
                 }
               else
                 CPPUNIT_ASSERT( !(rayfire->map_to_rayfire_elem( elem->child_ptr(c)->id() )) );
             }
         }
     }
void GRINSTesting::RayfireTestAMR::test_multiple_refinements (GRINS::SharedPtr< libMesh::UnstructuredMesh > mesh) inline private
Refine the mesh 3 times.
Definition at line 747 of file rayfireAMR_test.C.
References calc_theta().
Referenced by multiple_refinements().
     {
       libMesh::Point origin(0.0,0.0);
       libMesh::Point end_point(1.0,0.25);
       libMesh::Real theta = calc_theta(origin,end_point);
       GRINS::SharedPtr<GRINS::RayfireMesh> rayfire = new GRINS::RayfireMesh(origin,theta);
       rayfire->init(*mesh);
       libMesh::MeshRefinement mr(*mesh);
       // do 3 successive uniform refinements
       for (unsigned int i=0; i<3; i++)
         {
           mr.uniformly_refine();
           rayfire->reinit(*mesh);
         }
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(0)->child_ptr(0)->child_ptr(0)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(0)->child_ptr(0)->child_ptr(1)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(0)->child_ptr(1)->child_ptr(0)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(0)->child_ptr(1)->child_ptr(1)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(1)->child_ptr(0)->child_ptr(2)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(1)->child_ptr(0)->child_ptr(3)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(1)->child_ptr(1)->child_ptr(2)->id()) );
       CPPUNIT_ASSERT( rayfire->map_to_rayfire_elem(mesh->elem_ptr(0)->child_ptr(1)->child_ptr(1)->child_ptr(3)->id()) );
     }
void GRINSTesting::RayfireTestAMR::test_near_vertex (GRINS::SharedPtr< libMesh::UnstructuredMesh > mesh) inline private
Definition at line 621 of file rayfireAMR_test.C.
References calc_theta().
Referenced by near_vertex_postrefinement().
     {
       libMesh::Point origin(0.4999,0.0);
       libMesh::Point end_point(1.0,1.0);
       libMesh::Real theta = calc_theta(origin,end_point);
       GRINS::SharedPtr<GRINS::RayfireMesh> rayfire = new GRINS::RayfireMesh(origin,theta);
       rayfire->init(*mesh);
       libMesh::Elem* elem = mesh->elem_ptr(0);
       CPPUNIT_ASSERT(elem);
       elem->set_refinement_flag(libMesh::Elem::RefinementState::REFINE);
       libMesh::MeshRefinement mr(*mesh);
       mr.refine_elements();
       rayfire->reinit(*mesh);
       const libMesh::Elem* rayfire_elem0 = rayfire->map_to_rayfire_elem( elem->child_ptr(0)->id() );
       CPPUNIT_ASSERT(rayfire_elem0);
       const libMesh::Elem* rayfire_elem1 = rayfire->map_to_rayfire_elem( elem->child_ptr(1)->id() );
       CPPUNIT_ASSERT(rayfire_elem1);
       const libMesh::Elem* rayfire_elem2 = rayfire->map_to_rayfire_elem( elem->child_ptr(3)->id() );
       CPPUNIT_ASSERT(rayfire_elem2);
       // not in rayfire
       const libMesh::Elem* non_rayfire_elem = rayfire->map_to_rayfire_elem( elem->child_ptr(2)->id() );
       CPPUNIT_ASSERT(!non_rayfire_elem);
     }
void GRINSTesting::RayfireTestAMR::test_single_elem (GRINS::SharedPtr< libMesh::UnstructuredMesh > mesh) inline private
Runs the test on single square QUADs of unit length and width.
Definition at line 557 of file rayfireAMR_test.C.
References calc_theta().
Referenced by single_elems().
     {
       CPPUNIT_ASSERT_EQUAL( mesh->n_elem(), (libMesh::dof_id_type)1 );
       libMesh::Point origin(0.0,0.1);
       libMesh::Point end_point(1.0,0.2);
       libMesh::Real theta = calc_theta(origin,end_point);
       GRINS::SharedPtr<GRINS::RayfireMesh> rayfire = new GRINS::RayfireMesh(origin,theta);
       rayfire->init(*mesh);
       libMesh::Elem* elem = mesh->elem_ptr(0);
       CPPUNIT_ASSERT(elem);
       elem->set_refinement_flag(libMesh::Elem::RefinementState::REFINE);
       libMesh::MeshRefinement mr(*mesh);
       mr.refine_elements();
       rayfire->reinit(*mesh);
       const libMesh::Elem* rayfire_elem0 = rayfire->map_to_rayfire_elem( elem->child_ptr(0)->id() );
       CPPUNIT_ASSERT(rayfire_elem0);
       const libMesh::Elem* rayfire_elem1 = rayfire->map_to_rayfire_elem( elem->child_ptr(1)->id() );
       CPPUNIT_ASSERT(rayfire_elem1);
       CPPUNIT_ASSERT( (rayfire_elem0->node_ptr(0))->absolute_fuzzy_equals(origin) );
       CPPUNIT_ASSERT( (rayfire_elem0->node_ptr(1))->absolute_fuzzy_equals(libMesh::Point(0.5,0.15)) );
       CPPUNIT_ASSERT( (rayfire_elem1->node_ptr(0))->absolute_fuzzy_equals(libMesh::Point(0.5,0.15)) );
       CPPUNIT_ASSERT( (rayfire_elem1->node_ptr(1))->absolute_fuzzy_equals(end_point) );
     }
void GRINSTesting::RayfireTestAMR::test_through_vertex (GRINS::SharedPtr< libMesh::UnstructuredMesh > mesh) inline private
Definition at line 590 of file rayfireAMR_test.C.
References calc_theta().
Referenced by through_vertex_postrefinment().
     {
       libMesh::Point origin(0.0,0.0);
       libMesh::Point end_point(1.0,1.0);
       libMesh::Real theta = calc_theta(origin,end_point);
       GRINS::SharedPtr<GRINS::RayfireMesh> rayfire = new GRINS::RayfireMesh(origin,theta);
       rayfire->init(*mesh);
       libMesh::Elem* elem = mesh->elem_ptr(0);
       CPPUNIT_ASSERT(elem);
       elem->set_refinement_flag(libMesh::Elem::RefinementState::REFINE);
       libMesh::MeshRefinement mr(*mesh);
       mr.refine_elements();
       rayfire->reinit(*mesh);
       const libMesh::Elem* rayfire_elem0 = rayfire->map_to_rayfire_elem( elem->child_ptr(0)->id() );
       CPPUNIT_ASSERT(rayfire_elem0);
       const libMesh::Elem* rayfire_elem1 = rayfire->map_to_rayfire_elem( elem->child_ptr(3)->id() );
       CPPUNIT_ASSERT(rayfire_elem1);
       CPPUNIT_ASSERT( (rayfire_elem0->node_ptr(0))->absolute_fuzzy_equals(origin) );
       CPPUNIT_ASSERT( (rayfire_elem0->node_ptr(1))->absolute_fuzzy_equals(libMesh::Point(0.5,0.5)) );
       CPPUNIT_ASSERT( (rayfire_elem1->node_ptr(0))->absolute_fuzzy_equals(libMesh::Point(0.5,0.5)) );
       CPPUNIT_ASSERT( (rayfire_elem1->node_ptr(1))->absolute_fuzzy_equals(end_point) );
     }
void GRINSTesting::RayfireTestAMR::through_vertex_postrefinment () inline
After refinement, the rayfire will travel through a vertex.
Definition at line 92 of file rayfireAMR_test.C.
References build_quad4_elem(), build_quad9_elem(), and test_through_vertex().
     {
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = build_quad4_elem();
       test_through_vertex(mesh);
       mesh = build_quad9_elem();
       test_through_vertex(mesh);
     }
The documentation for this class was generated from the following file:
test/unit/rayfireAMR_test.C