GRINS-0.8.0: GRINS::GasRecombinationCatalyticWallNeumannBCFactoryImpl Class Reference
GRINS::GasRecombinationCatalyticWallNeumannBCFactoryImpl Class Reference
#include <gas_recombination_catalytic_wall_neumann_bc_factory_impl.h>
Public Member Functions
GasRecombinationCatalyticWallNeumannBCFactoryImpl ()
~GasRecombinationCatalyticWallNeumannBCFactoryImpl ()
SharedPtr< NeumannBCAbstract > build_catalytic_wall (const GetPot &input, const std::string &reaction, SharedPtr< CatalycityBase > &gamma_ptr, const std::vector< VariableIndex > &species_vars, const std::string &material, VariableIndex T_var, libMesh::Real p0, const std::string &thermochem_lib)
void parse_reactant_and_product (const std::string &reaction, std::string &reactant, std::string &product) const
Protected Member Functions
template<typename ChemistryType >
void build_wall_ptr (SharedPtr< ChemistryType > &chem_ptr, SharedPtr< CatalycityBase > &catalycity, const std::string &reactant, const std::string &product, const std::vector< VariableIndex > &species_vars, VariableIndex T_var, libMesh::Real p0, SharedPtr< NeumannBCAbstract > &catalytic_wall)
Detailed Description
Definition at line 37 of file gas_recombination_catalytic_wall_neumann_bc_factory_impl.h.
Constructor & Destructor Documentation
GRINS::GasRecombinationCatalyticWallNeumannBCFactoryImpl::GasRecombinationCatalyticWallNeumannBCFactoryImpl () inline
Definition at line 41 of file gas_recombination_catalytic_wall_neumann_bc_factory_impl.h.
 {}
GRINS::GasRecombinationCatalyticWallNeumannBCFactoryImpl::~GasRecombinationCatalyticWallNeumannBCFactoryImpl () inline
Definition at line 43 of file gas_recombination_catalytic_wall_neumann_bc_factory_impl.h.
 {}
Member Function Documentation
SharedPtr< NeumannBCAbstract > GRINS::GasRecombinationCatalyticWallNeumannBCFactoryImpl::build_catalytic_wall (const GetPot & input, const std::string & reaction, SharedPtr< CatalycityBase > & gamma_ptr, const std::vector< VariableIndex > & species_vars, const std::string & material, VariableIndex T_var, libMesh::Real p0, const std::string & thermochem_lib)
Todo:
Update the API for the catalytic walls to take a unique_ptr to avoid this garbage.
Todo:
Update the API for the catalytic walls to take a unique_ptr to avoid this garbage.
Definition at line 46 of file gas_recombination_catalytic_wall_neumann_bc_factory_impl.C.
References GRINS::ChemistryBuilder::build_chemistry().
   {
     std::string reactant;
     std::string product;
     this->parse_reactant_and_product(reaction,reactant,product);
     // Now construct the Neumann BC
     SharedPtr<NeumannBCAbstract> catalytic_wall;
     ChemistryBuilder chem_builder;
     if( thermochem_lib == "cantera" )
       {
 #ifdef GRINS_HAVE_CANTERA
         libMesh::UniquePtr<CanteraMixture> chem_uptr;
         chem_builder.build_chemistry(input,material,chem_uptr);
         SharedPtr<CanteraMixture> chem_ptr(chem_uptr.release());
         this->build_wall_ptr<CanteraMixture>(chem_ptr,gamma_ptr,reactant,product,
                                              species_vars,T_var,p0,catalytic_wall);
 #else
         libmesh_error_msg("Error: Cantera not enabled in this configuration. Reconfigure using --with-cantera option.");
 #endif
       }
     else if( thermochem_lib == "antioch" )
       {
 #ifdef GRINS_HAVE_ANTIOCH
         libMesh::UniquePtr<AntiochChemistry> chem_uptr;
         chem_builder.build_chemistry(input,material,chem_uptr);
         SharedPtr<AntiochChemistry> chem_ptr(chem_uptr.release());
         this->build_wall_ptr<AntiochChemistry>(chem_ptr,gamma_ptr,reactant,product,
                                                species_vars,T_var,p0,catalytic_wall);
 #else
         libmesh_error_msg("Error: Antioch not enabled in this configuration. Reconfigure using --with-antioch option.");
 #endif
       }
     else
       libmesh_error_msg("ERROR: Invalid thermochemistry library "+thermochem_lib+"!");
     return catalytic_wall;
   }
template<typename ChemistryType > void GRINS::GasRecombinationCatalyticWallNeumannBCFactoryImpl::build_wall_ptr (SharedPtr< ChemistryType > & chem_ptr, SharedPtr< CatalycityBase > & catalycity, const std::string & reactant, const std::string & product, const std::vector< VariableIndex > & species_vars, VariableIndex T_var, libMesh::Real p0, SharedPtr< NeumannBCAbstract > & catalytic_wall) inline protected
Definition at line 62 of file gas_recombination_catalytic_wall_neumann_bc_factory_impl.h.
     {
       catalytic_wall.reset( new GasRecombinationCatalyticWall<ChemistryType>
                             ( chem_ptr,
                               catalycity,
                               species_vars,
                               T_var,
                               p0,
                               chem_ptr->species_index(reactant),
                               chem_ptr->species_index(product) ) );
     }
void GRINS::GasRecombinationCatalyticWallNeumannBCFactoryImpl::parse_reactant_and_product (const std::string & reaction, std::string & reactant, std::string & product) const
Todo:
We currently can only handle reactions of the type R -> P e.g. not R1+R2 -> P, etc.
Definition at line 102 of file gas_recombination_catalytic_wall_neumann_bc_factory_impl.C.
References GRINS::StringUtilities::split_string().
Referenced by GRINS::GasRecombinationCatalyticWallNeumannBCOldStyleFactory::reactant_for_catalycity().
   {
     // Split each reaction into reactants and products
     std::vector<std::string> partners;
     StringUtilities::split_string(reaction, "->", partners);
     if( partners.size() != 2 )
       libmesh_error_msg("ERROR: Must have only one reactant and one product for GasRecombinationCatalyticWall!");
     reactant = partners[0];
     product = partners[1];
   }
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/gas_recombination_catalytic_wall_neumann_bc_factory_impl.h
src/boundary_conditions/src/gas_recombination_catalytic_wall_neumann_bc_factory_impl.C