GRINS-0.6.0: GRINS::ConstantSpecificHeat Class Reference
GRINS::ConstantSpecificHeat Class Reference
#include <constant_specific_heat.h>
Public Member Functions
ConstantSpecificHeat (const GetPot &input)
~ConstantSpecificHeat ()
libMesh::Real operator() () const
libMesh::Real operator() (const libMesh::Real T) const
libMesh::Real deriv (const libMesh::Real T) const
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiPointer< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Private Member Functions
ConstantSpecificHeat ()
Private Attributes
libMesh::Real _cp
Detailed Description
Definition at line 39 of file constant_specific_heat.h.
Constructor & Destructor Documentation
GRINS::ConstantSpecificHeat::ConstantSpecificHeat (const GetPot & input)
Definition at line 35 of file constant_specific_heat.C.
References _cp, and GRINS::ParameterUser::set_parameter().
     : ParameterUser("ConstantSpecificHeat"),
       _cp(0.0)
   {
     if( !input.have_variable("Materials/SpecificHeat/cp") )
       {
         std::cerr << "Error: Must specify cp value for constant specific heat model!" << std::endl;
         libmesh_error();
       }
     this->set_parameter
       (_cp, input, "Materials/SpecificHeat/cp", _cp);
   }
GRINS::ConstantSpecificHeat::~ConstantSpecificHeat ()
Definition at line 49 of file constant_specific_heat.C.
   {
     return;
   }
GRINS::ConstantSpecificHeat::ConstantSpecificHeat () private
Member Function Documentation
libMesh::Real GRINS::ConstantSpecificHeat::deriv (const libMesh::Real T) const inline
Definition at line 74 of file constant_specific_heat.h.
   {
     return 0.0;
   }
libMesh::Real GRINS::ConstantSpecificHeat::operator() () const inline
Definition at line 62 of file constant_specific_heat.h.
References _cp.
   {
     return _cp;
   }
libMesh::Real GRINS::ConstantSpecificHeat::operator() (const libMesh::Real T) const inline
Definition at line 68 of file constant_specific_heat.h.
   {
     return (*this)();
   }
void GRINS::ParameterUser::register_parameter (const std::string & param_name, libMesh::ParameterMultiPointer< libMesh::Number > & param_pointer) const virtual inherited
Each subclass will register its copy of an independent.
Reimplemented in GRINS::AxisymmetricHeatTransfer< Conductivity >, GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::IncompressibleNavierStokesBase< Viscosity >, GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >, GRINS::HeatConduction< Conductivity >, GRINS::HeatTransferBase< Conductivity >, and GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >.
Definition at line 50 of file parameter_user.C.
Referenced by GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::register_parameter(), GRINS::HeatTransferBase< Conductivity >::register_parameter(), GRINS::HeatConduction< Conductivity >::register_parameter(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::register_parameter(), GRINS::IncompressibleNavierStokesBase< Viscosity >::register_parameter(), GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::register_parameter(), and GRINS::AxisymmetricHeatTransfer< Conductivity >::register_parameter().
   {
     std::map<std::string, libMesh::Number*>::const_iterator it =
       _my_parameters.find(param_name);
     if (it != _my_parameters.end())
       {
         std::cout << _my_name << " uses parameter " << param_name
                   << std::endl;
         param_pointer.push_back(it->second);
       }
   }
void GRINS::ParameterUser::set_parameter (libMesh::Number & param_variable, const GetPot & input, const std::string & param_name, libMesh::Number param_default) virtual inherited
Each subclass can simultaneously read a parameter value from.
Definition at line 35 of file parameter_user.C.
References GRINS::ParameterUser::_my_name, and GRINS::ParameterUser::_my_parameters.
Referenced by GRINS::AveragedFanAdjointStabilization< Viscosity >::AveragedFanAdjointStabilization(), GRINS::AveragedTurbineAdjointStabilization< Viscosity >::AveragedTurbineAdjointStabilization(), GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::BoussinesqBuoyancyAdjointStabilization(), GRINS::BoussinesqBuoyancyBase::BoussinesqBuoyancyBase(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::BoussinesqBuoyancySPGSMStabilization(), GRINS::ConstantConductivity::ConstantConductivity(), GRINS::ConstantPrandtlConductivity::ConstantPrandtlConductivity(), GRINS::ConstantSourceFunction::ConstantSourceFunction(), GRINS::ConstantSourceTerm::ConstantSourceTerm(), ConstantSpecificHeat(), GRINS::ConstantViscosity::ConstantViscosity(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticCableConstantGravity::ElasticCableConstantGravity(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransferBase< Conductivity >::HeatTransferBase(), GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase(), GRINS::AverageNusseltNumber::init(), GRINS::MooneyRivlin::MooneyRivlin(), GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase(), GRINS::HookesLaw1D::read_input_options(), GRINS::HookesLaw::read_input_options(), GRINS::AxisymmetricBoussinesqBuoyancy::read_input_options(), and GRINS::VelocityDragAdjointStabilization< Viscosity >::VelocityDragAdjointStabilization().
   {
     param_variable = input(param_name, param_default);
     libmesh_assert_msg(!_my_parameters.count(param_name),
       "ERROR: " << _my_name << " double-registered parameter " <<
       param_name);
     _my_parameters[param_name] = &param_variable;
   }
Member Data Documentation
libMesh::Real GRINS::ConstantSpecificHeat::_cp private
Definition at line 56 of file constant_specific_heat.h.
Referenced by ConstantSpecificHeat(), and operator()().
The documentation for this class was generated from the following files:
src/properties/include/grins/constant_specific_heat.h
src/properties/src/constant_specific_heat.C