GRINS-0.8.0: GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType > Class Template Reference
GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType > Class Template Reference abstract
#include <catalytic_wall_neumann_bc_old_style_factory_base.h>
Public Member Functions
CatalyticWallNeumannBCOldStyleFactoryBase (const std::string &bc_type_name)
~CatalyticWallNeumannBCOldStyleFactoryBase ()
Public Member Functions inherited from GRINS::NeumannBCOldStyleFactoryAbstract
NeumannBCOldStyleFactoryAbstract (const std::string &bc_type_name)
~NeumannBCOldStyleFactoryAbstract ()
Public Member Functions inherited from GRINS::NeumannBCFactoryAbstract
NeumannBCFactoryAbstract (const std::string &bc_type_name)
~NeumannBCFactoryAbstract ()
virtual libMesh::UniquePtr< NeumannBCContainer > create ()
Creates NeumannBCContainer for this Factory object.
Public Member Functions inherited from GRINS::BCFactoryAbstract< NeumannBCContainer >
BCFactoryAbstract (const std::string &bc_type_name)
~BCFactoryAbstract ()
Public Member Functions inherited from GRINS::FactoryWithGetPot< NeumannBCContainer >
FactoryWithGetPot (const std::string &name)
~FactoryWithGetPot ()
Public Member Functions inherited from GRINS::FactoryAbstract< NeumannBCContainer >
virtual ~FactoryAbstract ()
Public Member Functions inherited from GRINS::CatalyticWallNeumannBCFactoryCommon< ImplType >
CatalyticWallNeumannBCFactoryCommon ()
~CatalyticWallNeumannBCFactoryCommon ()
Protected Member Functions
virtual SharedPtr< NeumannBCAbstract > build_neumann_func (const GetPot &input, MultiphysicsSystem &system, const FEVariablesBase &fe_var, const std::string &section)
Builds the NeumannBCAbstract object for Neumann boundary conditions.
std::string parse_reaction (const GetPot &input, const std::string &section) const
Parse the reaction.
std::string parse_thermochem_model (const GetPot &input) const
libMesh::Real parse_thermo_pressure (const GetPot &input, const std::string &material) const
SharedPtr< CatalycityBase > build_catalycity (const GetPot &input, const std::string &section, const std::string &reactant) const
virtual std::string reactant_for_catalycity (const std::string &reaction) const =0
virtual std::string catalytic_wall_prefix_str () const =0
Protected Member Functions inherited from GRINS::NeumannBCOldStyleFactoryAbstract
virtual void check_state () const
Helper function to reduce code duplication.
virtual void reset_state ()
Helper function to reduce code duplication.
Protected Member Functions inherited from GRINS::NeumannBCFactoryAbstract
void check_for_flux (const GetPot &input, const std::string &section, const std::vector< std::string > &var_names)
Checks that the flux variable has been set.
Protected Member Functions inherited from GRINS::BCFactoryAbstract< NeumannBCContainer >
void check_for_multiple_expressions (const GetPot &input, const std::string &section, const std::string &var_name) const
Ensure that there is only one expression for the [Section/var_name] variable.
void build_var_indices (const MultiphysicsSystem &system, const std::vector< std::string > &var_names, std::vector< VariableIndex > &var_indices) const
Protected Member Functions inherited from GRINS::FactoryAbstract< NeumannBCContainer >
FactoryAbstract (const std::string &name)
Constructor is protected. Use the build() method to construct Base objects.
Protected Member Functions inherited from GRINS::CatalyticWallNeumannBCFactoryCommon< ImplType >
SharedPtr< NeumannBCAbstract > build_catalytic_wall_common (const GetPot &input, const FEVariablesBase &fe_var, const std::string &material, const std::string &reaction, SharedPtr< CatalycityBase > &gamma_ptr, libMesh::Real p0, std::string &thermochem_lib)
void extract_species_vars (const FEVariablesBase &fe_var, std::vector< VariableIndex > &species_vars) const
void extract_material (const FEVariablesBase &fe_var, std::string &material) const
VariableIndex extract_temp_var () const
Additional Inherited Members
Static Public Member Functions inherited from GRINS::NeumannBCOldStyleFactoryAbstract
static void set_value_var_old_style (const std::string &value_var)
Input variable for parsing old style.
static void set_value_index_old_style (unsigned int idx)
Input variable index for parsing old style.
Static Public Member Functions inherited from GRINS::BCFactoryAbstract< NeumannBCContainer >
static void set_system (MultiphysicsSystem &system)
static void set_bc_ids (const std::set< BoundaryID > &bc_ids)
Boundary id for the current boundary condition section.
static void set_fe_var (const FEVariablesBase &fe_var)
Active variable for the current boundary condition.
static void set_section (const std::string &section)
Sets the current section of the input file.
static bool have_bc_type (const std::string &bc_type)
Static Public Member Functions inherited from GRINS::FactoryWithGetPot< NeumannBCContainer >
static void set_getpot (const GetPot &input)
Static Public Member Functions inherited from GRINS::FactoryAbstract< NeumannBCContainer >
static libMesh::UniquePtr< NeumannBCContainer > build (const std::string &name)
Use this method to build objects of type Base.
Static Protected Member Functions inherited from GRINS::FactoryAbstract< NeumannBCContainer >
static FactoryAbstract< NeumannBCContainer > & get_factory (const std::string &name)
Helper method that looks up the factory and returns it if present, or error if it's not.
static DerivedType & get_factory_subclass (const std::string &name)
Like get_factory, but will downcast to DerivedType.
static std::map< std::string, FactoryAbstract< NeumannBCContainer > * > & factory_map ()
Protected Attributes inherited from GRINS::NeumannBCFactoryAbstract
bool _is_homogeneous
Track if this is a homogeneous Neumann boundary condition.
Protected Attributes inherited from GRINS::CatalyticWallNeumannBCFactoryCommon< ImplType >
ImplType _wall_impl
Static Protected Attributes inherited from GRINS::NeumannBCOldStyleFactoryAbstract
static std::string _value_var_old_style = std::string("DIE!")
static unsigned int _value_idx_old_style = libMesh::invalid_uint
Static Protected Attributes inherited from GRINS::BCFactoryAbstract< NeumannBCContainer >
static MultiphysicsSystem * _system
We store only a raw pointer here because we can't make a copy.
static const std::set< BoundaryID > * _bc_ids
BoundaryID for constructing a particular boundary condition.
static const FEVariablesBase * _fe_var
The FEVariablesBase class associated with the boundary condition being built.
static std::string _section
Static Protected Attributes inherited from GRINS::FactoryWithGetPot< NeumannBCContainer >
static const GetPot * _input
We store only a raw pointer here because we can't make a copy.
Detailed Description
template<typename ImplType>
class GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType >
Definition at line 36 of file catalytic_wall_neumann_bc_old_style_factory_base.h.
Constructor & Destructor Documentation
template<typename ImplType> GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType >::CatalyticWallNeumannBCOldStyleFactoryBase (const std::string & bc_type_name) inline
Definition at line 41 of file catalytic_wall_neumann_bc_old_style_factory_base.h.
       : NeumannBCOldStyleFactoryAbstract(bc_type_name),
         CatalyticWallNeumannBCFactoryCommon<ImplType>()
     {}
template<typename ImplType> GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType >::~CatalyticWallNeumannBCOldStyleFactoryBase () inline
Definition at line 46 of file catalytic_wall_neumann_bc_old_style_factory_base.h.
 {};
Member Function Documentation
template<typename ImplType > SharedPtr< CatalycityBase > GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType >::build_catalycity (const GetPot & input, const std::string & section, const std::string & reactant) const protected
Definition at line 126 of file catalytic_wall_neumann_bc_old_style_factory_base.C.
References GRINS::BCFactoryAbstract< NeumannBCContainer >::_bc_ids, GRINS::FactoryAbstract< CatalycityBase >::build(), GRINS::CatalycityFactoryOldStyleBase::set_bc_id(), GRINS::FactoryWithGetPot< CatalycityBase >::set_getpot(), GRINS::CatalycityFactoryOldStyleBase::set_reactant(), and GRINS::CatalycityFactoryAbstract::set_section().
   {
     libmesh_assert_equal_to(NeumannBCFactoryAbstract::_bc_ids->size(), 1 );
     std::string bc_id_str = StringUtilities::T_to_string<BoundaryID>( *(_bc_ids->begin()) );
     CatalycityFactoryOldStyleBase::set_getpot(input);
     CatalycityFactoryOldStyleBase::set_section(section);
     CatalycityFactoryOldStyleBase::set_reactant(reactant);
     CatalycityFactoryOldStyleBase::set_bc_id(bc_id_str);
     std::string catalycity_input_str = section+"/gamma_"+reactant+"_"+bc_id_str+"_type";
     if( !input.have_variable(catalycity_input_str) )
       libmesh_error_msg("ERROR: Could not find input variable "+catalycity_input_str+" !\n");
     std::string catalycity_type = input(catalycity_input_str, "none");
     catalycity_type += "_old_style";
     libMesh::UniquePtr<CatalycityBase> catalycity_ptr = CatalycityFactoryOldStyleBase::build(catalycity_type);
     // We need to return a SharedPtr
     return SharedPtr<CatalycityBase>( catalycity_ptr.release() );
   }
template<typename ImplType > SharedPtr< NeumannBCAbstract > GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType >::build_neumann_func (const GetPot & input, MultiphysicsSystem & system, const FEVariablesBase & fe_var, const std::string & section) protected virtual
Builds the NeumannBCAbstract object for Neumann boundary conditions.
Subclasses should override this function to build the NeumannBCAbstract object that corresponds to the variables passed in var_names. The FEVariableBase object corresponds to the variable associated with this boundary condition, e.g. Velocity. The section arguments corresponds to the section to parse for the flux in the input file, e.g. input(section+"/"+flux). Note that for Variables with more than one component, the flux input should be a vector the size of the var_names object, even if one of the components is zero.
Todo:
We're assuming constant thermodynamic pressure
Implements GRINS::NeumannBCFactoryAbstract.
Definition at line 39 of file catalytic_wall_neumann_bc_old_style_factory_base.C.
   {
     std::string reaction = this->parse_reaction(input,section);
     // Parse and construct the corresponding catalycity
     SharedPtr<CatalycityBase> gamma_ptr = this->build_catalycity( input, section,
                                                                   this->reactant_for_catalycity(reaction) );
     std::string material;
     this->extract_material( fe_var, material );
     // Parse thermodynamic pressure
     libMesh::Real p0 = this->parse_thermo_pressure(input,material);
     std::string thermochem_lib = this->parse_thermochem_model(input);
     return this->build_catalytic_wall_common(input,fe_var,material,reaction,gamma_ptr,p0,thermochem_lib);
   }
template<typename ImplType> virtual std::string GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType >::catalytic_wall_prefix_str () const protected pure virtual
Implemented in GRINS::GasSolidCatalyticWallNeumannBCOldStyleFactory, and GRINS::GasRecombinationCatalyticWallNeumannBCOldStyleFactory.
template<typename ImplType > std::string GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType >::parse_reaction (const GetPot & input, const std::string & section) const protected
Parse the reaction.
Definition at line 63 of file catalytic_wall_neumann_bc_old_style_factory_base.C.
References GRINS::BCFactoryAbstract< NeumannBCContainer >::_bc_ids.
   {
     libmesh_assert_equal_to(NeumannBCFactoryAbstract::_bc_ids->size(), 1 );
     std::string bc_id_string = StringUtilities::T_to_string<BoundaryID>( *(_bc_ids->begin()) );
     std::string prefix_str = this->catalytic_wall_prefix_str();
     std::string reaction_input_str = section+"/"+prefix_str+"_"+bc_id_string;
     // First make sure the input reaction is there
     if(!input.have_variable(reaction_input_str))
       libmesh_error_msg("ERROR: Could not find input for "+reaction_input_str+" !\n");
     // Make sure there's only one
     if( input.vector_variable_size(reaction_input_str) != 1 )
       libmesh_error_msg("ERROR: Can only specify one catalytic_reaction!\n");
     return input( reaction_input_str, std::string("DIE!") );
   }
template<typename ImplType > libMesh::Real GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType >::parse_thermo_pressure (const GetPot & input, const std::string & material) const protected
Definition at line 86 of file catalytic_wall_neumann_bc_old_style_factory_base.C.
References GRINS::PhysicsNaming::reacting_low_mach_navier_stokes().
   {
     std::string thermo_press_input_str =
       "Materials/"+material+"/ThermodynamicPressure/value";
     std::string thermo_press_input_str_old_style =
       "Physics/"+PhysicsNaming::reacting_low_mach_navier_stokes()+"/p0";
     if( input.have_variable(thermo_press_input_str) && input.have_variable(thermo_press_input_str_old_style) )
       libmesh_error_msg("ERROR: Cannot specify both "+thermo_press_input_str+" and "+thermo_press_input_str_old_style);
     libMesh::Real invalid_real =  std::numeric_limits<libMesh::Real>::max();
     libMesh::Real p0 = invalid_real;
     if( input.have_variable(thermo_press_input_str) )
       p0 = input(thermo_press_input_str,invalid_real);
     else if( input.have_variable(thermo_press_input_str_old_style) )
       p0 = input(thermo_press_input_str_old_style,invalid_real);
     else
       libmesh_error_msg("ERROR: Could not valid input for thermodynamic pressure!");
     return p0;
   }
template<typename ImplType > std::string GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType >::parse_thermochem_model (const GetPot & input) const protected
Definition at line 114 of file catalytic_wall_neumann_bc_old_style_factory_base.C.
References GRINS::PhysicsFactoryHelper::parse_thermochemistry_model(), and GRINS::PhysicsNaming::reacting_low_mach_navier_stokes().
   {
     std::string thermochem_lib;
     PhysicsFactoryHelper::parse_thermochemistry_model( input,
                                                        PhysicsNaming::reacting_low_mach_navier_stokes(),
                                                        thermochem_lib );
     return thermochem_lib;
   }
template<typename ImplType> virtual std::string GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType >::reactant_for_catalycity (const std::string & reaction) const protected pure virtual
Implemented in GRINS::GasSolidCatalyticWallNeumannBCOldStyleFactory, and GRINS::GasRecombinationCatalyticWallNeumannBCOldStyleFactory.
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/catalytic_wall_neumann_bc_old_style_factory_base.h
src/boundary_conditions/src/catalytic_wall_neumann_bc_old_style_factory_base.C