GRINS-0.8.0: GRINS::PhysicsFactoryInitializer Class Reference
GRINS::PhysicsFactoryInitializer Class Reference
Initialize all PhysicsFactory objects.
#include <physics_factory_initializer.h>
Public Member Functions
PhysicsFactoryInitializer ()
~PhysicsFactoryInitializer ()
Detailed Description
Initialize all PhysicsFactory objects.
To avoid symbol stripping from static linking, we use this class to initialize/register the Physics factory objects.
Relevant discussion: http://stackoverflow.com/questions/5202142/static-variable-initialization-over-a-library
Definition at line 35 of file physics_factory_initializer.h.
Constructor & Destructor Documentation
GRINS::PhysicsFactoryInitializer::PhysicsFactoryInitializer ()
Definition at line 86 of file physics_factory_initializer.C.
References GRINS::PhysicsNaming::averaged_fan(), GRINS::PhysicsNaming::averaged_fan_adjoint_stab(), GRINS::PhysicsNaming::averaged_turbine(), GRINS::PhysicsNaming::axisymmetric_boussinesq_buoyancy(), GRINS::PhysicsNaming::axisymmetric_heat_transfer(), GRINS::PhysicsNaming::boussinesq_buoyancy(), GRINS::PhysicsNaming::boussinesq_buoyancy_adjoint_stab(), GRINS::PhysicsNaming::boussinesq_buoyancy_spgsm_stab(), GRINS::PhysicsNaming::constant_source_term(), GRINS::PhysicsNaming::convection_diffusion(), GRINS::PhysicsNaming::elastic_cable(), GRINS::PhysicsNaming::elastic_cable_rayleigh_damping(), GRINS::PhysicsNaming::elastic_membrane(), GRINS::PhysicsNaming::elastic_membrane_constant_pressure(), GRINS::PhysicsNaming::elastic_membrane_rayleigh_damping(), GRINS::PhysicsNaming::heat_conduction(), GRINS::PhysicsNaming::heat_transfer(), GRINS::PhysicsNaming::heat_transfer_adjoint_stab(), GRINS::PhysicsNaming::heat_transfer_spgsm_stab(), GRINS::PhysicsNaming::incompressible_navier_stokes(), GRINS::PhysicsNaming::incompressible_navier_stokes_adjoint_stab(), GRINS::PhysicsNaming::incompressible_navier_stokes_spgsm_stab(), GRINS::PhysicsNaming::low_mach_navier_stokes(), GRINS::PhysicsNaming::low_mach_navier_stokes_braack_stab(), GRINS::PhysicsNaming::low_mach_navier_stokes_spgsm_stab(), GRINS::PhysicsNaming::low_mach_navier_stokes_vms_stab(), GRINS::PhysicsNaming::parsed_source_term(), GRINS::PhysicsNaming::parsed_velocity_source(), GRINS::PhysicsNaming::parsed_velocity_source_adjoint_stab(), GRINS::PhysicsNaming::scalar_ode(), GRINS::PhysicsNaming::spalart_allmaras(), GRINS::PhysicsNaming::spalart_allmaras_spgsm_stab(), GRINS::PhysicsNaming::stokes(), GRINS::PhysicsNaming::variable_pinning(), GRINS::PhysicsNaming::velocity_drag(), GRINS::PhysicsNaming::velocity_drag_adjoint_stab(), GRINS::PhysicsNaming::velocity_penalty(), GRINS::PhysicsNaming::velocity_penalty2(), GRINS::PhysicsNaming::velocity_penalty2_adjoint_stab(), GRINS::PhysicsNaming::velocity_penalty3(), GRINS::PhysicsNaming::velocity_penalty3_adjoint_stab(), and GRINS::PhysicsNaming::velocity_penalty_adjoint_stab().
   {
     static PhysicsFactoryBasic<ScalarODE> grins_factory_scalar_ode(PhysicsNaming::scalar_ode());
     static PhysicsFactoryBasic<BoussinesqBuoyancy> grins_factory_boussinesq(PhysicsNaming::boussinesq_buoyancy());
     // This one needs to die. Regular Boussinesq should handle the axisymmetry
     static PhysicsFactoryBasic<AxisymmetricBoussinesqBuoyancy>
       grins_factory_axi_boussinesq(PhysicsNaming::axisymmetric_boussinesq_buoyancy());
     static PhysicsFactoryBasic<ElasticMembraneConstantPressure>
       grins_factory_elastic_membrane_pressure(PhysicsNaming::elastic_membrane_constant_pressure());
     // This one needs to die and just have the parsed version
     static PhysicsFactoryBasic<ConstantSourceTerm>
       grins_factory_constant_source_term(PhysicsNaming::constant_source_term());
     static PhysicsFactoryBasic<ParsedSourceTerm>
       grins_factory_parsed_source_term(PhysicsNaming::parsed_source_term());
     static PhysicsFactoryBasic<ConvectionDiffusion>
       grins_factory_convection_difffusion(PhysicsNaming::convection_diffusion());
     static PhysicsFactoryBasic<VariablePinning>
       grins_factory_variable_pinning(PhysicsNaming::variable_pinning());
     static PhysicsFactoryHeatTransfer<HeatConduction> grins_factory_heat_conduction
       (PhysicsNaming::heat_conduction(),PhysicsNaming::heat_conduction());
     static PhysicsFactoryHeatTransfer<HeatTransfer> grins_factory_heat_transfer
       (PhysicsNaming::heat_transfer(),PhysicsNaming::heat_transfer());
     static PhysicsFactoryHeatTransfer<HeatTransferAdjointStabilization> grins_factory_heat_transfer_adjoint_stab
       (PhysicsNaming::heat_transfer_adjoint_stab(),PhysicsNaming::heat_transfer());
     static PhysicsFactoryHeatTransfer<HeatTransferAdjointStabilization> grins_factory_heat_transfer_spgsm_stab
       (PhysicsNaming::heat_transfer_spgsm_stab(),PhysicsNaming::heat_transfer());
     // This needs to die. Axisymmetry should be handled within heat_transfer
     static PhysicsFactoryHeatTransfer<AxisymmetricHeatTransfer> grins_factory_axi_heat_transfer
       (PhysicsNaming::axisymmetric_heat_transfer(),PhysicsNaming::axisymmetric_heat_transfer());
     static PhysicsFactoryIncompressibleFlow<IncompressibleNavierStokes> grins_factory_incompressible_navier_stokes
       (PhysicsNaming::incompressible_navier_stokes(),PhysicsNaming::incompressible_navier_stokes());
     static PhysicsFactoryIncompressibleFlow<Stokes> grins_factory_stokes
       (PhysicsNaming::stokes(),PhysicsNaming::stokes());
     static PhysicsFactoryIncompressibleFlow<IncompressibleNavierStokesAdjointStabilization>
       grins_factory_ins_adjoint_stab
       (PhysicsNaming::incompressible_navier_stokes_adjoint_stab(),PhysicsNaming::incompressible_navier_stokes());
     static PhysicsFactoryIncompressibleFlow<IncompressibleNavierStokesSPGSMStabilization>
       grins_factory_spsgm_adjoint_stab
       (PhysicsNaming::incompressible_navier_stokes_spgsm_stab(),PhysicsNaming::incompressible_navier_stokes());
     static PhysicsFactoryIncompressibleFlow<VelocityDrag> grins_factory_velocity_drag
       (PhysicsNaming::velocity_drag(),PhysicsNaming::incompressible_navier_stokes());
     static PhysicsFactoryIncompressibleFlow<VelocityDragAdjointStabilization>
       grins_factory_velocity_drag_adjoint_stab
       (PhysicsNaming::velocity_drag_adjoint_stab(),PhysicsNaming::incompressible_navier_stokes());
     static PhysicsFactoryIncompressibleFlow<VelocityPenalty> grins_factory_vel_penalty
       (PhysicsNaming::velocity_penalty(),PhysicsNaming::incompressible_navier_stokes());
     static PhysicsFactoryIncompressibleFlow<VelocityPenalty> grins_factory_vel_penalty2
       (PhysicsNaming::velocity_penalty2(),PhysicsNaming::incompressible_navier_stokes());
     static PhysicsFactoryIncompressibleFlow<VelocityPenalty> grins_factory_vel_penalty3
       (PhysicsNaming::velocity_penalty3(),PhysicsNaming::incompressible_navier_stokes());
     static PhysicsFactoryIncompressibleFlow<VelocityPenaltyAdjointStabilization>
       grins_factory_vel_penalty_adjoint_stab
       (PhysicsNaming::velocity_penalty_adjoint_stab(),PhysicsNaming::incompressible_navier_stokes());
     static PhysicsFactoryIncompressibleFlow<VelocityPenaltyAdjointStabilization>
       grins_factory_vel_penalty2_adjoint_stab
       (PhysicsNaming::velocity_penalty2_adjoint_stab(),PhysicsNaming::incompressible_navier_stokes());
     static PhysicsFactoryIncompressibleFlow<VelocityPenaltyAdjointStabilization>
       grins_factory_vel_penalty3_adjoint_stab
       (PhysicsNaming::velocity_penalty3_adjoint_stab(),PhysicsNaming::incompressible_navier_stokes());
     static PhysicsFactoryIncompressibleFlow<ParsedVelocitySource> grins_factory_parsed_vel_source
       (PhysicsNaming::parsed_velocity_source(),PhysicsNaming::incompressible_navier_stokes());
     static PhysicsFactoryIncompressibleFlow<ParsedVelocitySourceAdjointStabilization>
       grins_factory_parsed_vel_source_adjoint_stab
       (PhysicsNaming::parsed_velocity_source_adjoint_stab(),PhysicsNaming::incompressible_navier_stokes());
     static PhysicsFactoryIncompressibleFlow<AveragedFan> grins_factory_averaged_fan
       (PhysicsNaming::averaged_fan(),PhysicsNaming::incompressible_navier_stokes());
     static PhysicsFactoryIncompressibleFlow<AveragedFanAdjointStabilization>
       grins_factory_averaged_fan_adjoint_stab
       (PhysicsNaming::averaged_fan_adjoint_stab(),PhysicsNaming::incompressible_navier_stokes());
     static PhysicsFactoryIncompressibleFlow<AveragedTurbine> grins_factory_averaged_turbine
       (PhysicsNaming::averaged_turbine(),PhysicsNaming::incompressible_navier_stokes());
     static PhysicsFactoryIncompressibleFlow<BoussinesqBuoyancyAdjointStabilization>
       grins_factory_boussinesq_adjoint_stab
       (PhysicsNaming::boussinesq_buoyancy_adjoint_stab(),PhysicsNaming::boussinesq_buoyancy());
     static PhysicsFactoryIncompressibleFlow<BoussinesqBuoyancySPGSMStabilization>
       grins_factory_boussinesq_spgsm_stab
       (PhysicsNaming::boussinesq_buoyancy_spgsm_stab(),PhysicsNaming::boussinesq_buoyancy());
     static PhysicsFactoryIncompressibleTurbFlow<SpalartAllmaras> grins_factory_spalart_allmaras
       (PhysicsNaming::spalart_allmaras(),PhysicsNaming::spalart_allmaras());
     static PhysicsFactoryIncompressibleTurbFlow<SpalartAllmarasSPGSMStabilization>
       grins_factory_spalart_allmaras_spgsm_stab
       (PhysicsNaming::spalart_allmaras_spgsm_stab(),PhysicsNaming::spalart_allmaras());
     static PhysicsFactoryOneDStressSolids<ElasticCable> grins_factory_elastic_cable
       (PhysicsNaming::elastic_cable(),PhysicsNaming::elastic_cable());
     static PhysicsFactoryOneDStressSolids<ElasticCableRayleighDamping> grins_factory_elastic_cable_rayleigh_damping
       (PhysicsNaming::elastic_cable_rayleigh_damping(),PhysicsNaming::elastic_cable());
     static PhysicsFactoryPlaneStressSolids<ElasticMembrane> grins_factory_elastic_membrane
       (PhysicsNaming::elastic_membrane(),PhysicsNaming::elastic_membrane());
     static PhysicsFactoryPlaneStressSolids<ElasticMembraneRayleighDamping>
       grins_factory_elastic_membrane_rayleigh_damping
       (PhysicsNaming::elastic_membrane_rayleigh_damping(),PhysicsNaming::elastic_membrane());
     static PhysicsFactoryVariableDensityFlow<LowMachNavierStokes> grins_factory_low_mach_navier_stokes
       (PhysicsNaming::low_mach_navier_stokes(),PhysicsNaming::low_mach_navier_stokes());
     static PhysicsFactoryVariableDensityFlow<LowMachNavierStokesSPGSMStabilization> grins_factory_lmns_spgsm_stab
       (PhysicsNaming::low_mach_navier_stokes_spgsm_stab(),PhysicsNaming::low_mach_navier_stokes());
     static PhysicsFactoryVariableDensityFlow<LowMachNavierStokesVMSStabilization> grins_factory_lmns_vms_stab
       (PhysicsNaming::low_mach_navier_stokes_vms_stab(),PhysicsNaming::low_mach_navier_stokes());
     static PhysicsFactoryVariableDensityFlow<LowMachNavierStokesBraackStabilization> grins_factory_lmns_braack_stab
       (PhysicsNaming::low_mach_navier_stokes_braack_stab(),PhysicsNaming::low_mach_navier_stokes());
     ReactingFlowsPhysicsFactoryInitializer grins_factory_reacting_flows_init;
   }
GRINS::PhysicsFactoryInitializer::~PhysicsFactoryInitializer () inline
Definition at line 39 of file physics_factory_initializer.h.
 {}
The documentation for this class was generated from the following files:
src/physics/include/grins/physics_factory_initializer.h
src/physics/src/physics_factory_initializer.C