GRINS-0.8.0: GRINSTesting::DefaultBCBuilderTest Class Reference
GRINSTesting::DefaultBCBuilderTest Class Reference
Public Member Functions
CPPUNIT_TEST_SUITE (DefaultBCBuilderTest)
CPPUNIT_TEST (test_parse_and_build_bc_id_map)
CPPUNIT_TEST (test_verify_bc_ids_with_mesh)
CPPUNIT_TEST (test_parse_periodic_master_slave_ids)
CPPUNIT_TEST (test_parse_periodic_offset)
CPPUNIT_TEST_SUITE_END ()
void tearDown ()
void test_parse_and_build_bc_id_map ()
void test_verify_bc_ids_with_mesh ()
void test_parse_periodic_master_slave_ids ()
void test_parse_periodic_offset ()
Public Member Functions inherited from GRINS::DefaultBCBuilder
DefaultBCBuilder ()
~DefaultBCBuilder ()
Public Member Functions inherited from GRINS::BCBuilder
BCBuilder ()
virtual ~BCBuilder ()
Public Member Functions inherited from GRINS::BuilderHelper
BuilderHelper ()
~BuilderHelper ()
Private Member Functions
void test_for_var_name (const std::vector< std::string > &var_names, const std::string &var_to_find)
Additional Inherited Members
Static Public Member Functions inherited from GRINS::BCBuilder
static void build_boundary_conditions (const GetPot &input, MultiphysicsSystem &system, std::vector< SharedPtr< NeumannBCContainer > > &neumann_bcs)
Static Public Member Functions inherited from GRINS::BuilderHelper
static void parse_var_sections (const GetPot &input, std::set< std::string > &sections)
Parses the input file for [Variables] first-level subsections.
static void parse_var_sections_vector (const GetPot &input, std::vector< std::string > &sections)
The same as parse_var_sections, except the result is returned in an std::vector.
Protected Member Functions inherited from GRINSTesting::SystemHelper
void setup_multiphysics_system (const std::string &filename)
void reset_all ()
Protected Member Functions inherited from GRINS::DefaultBCBuilder
virtual void build_bcs (const GetPot &input, MultiphysicsSystem &system, std::vector< SharedPtr< NeumannBCContainer > > &neumann_bcs)
void build_type_based_bcs (const GetPot &input, MultiphysicsSystem &system, const std::set< BoundaryID > &bc_ids, libMesh::DofMap &dof_map, const std::string &type_input_section, std::set< std::string > &var_sections, std::vector< SharedPtr< NeumannBCContainer > > &neumann_bcs)
Helper function to build boundary conditions specified by a single type.
void build_axisymmetric_bcs (const GetPot &input, MultiphysicsSystem &system, const std::set< BoundaryID > &bc_ids, libMesh::DofMap &dof_map, const std::string &bc_type, std::set< std::string > &var_sections, std::vector< SharedPtr< NeumannBCContainer > > &neumann_bcs)
void build_bcs_by_var_section (const GetPot &input, MultiphysicsSystem &system, const std::string &bc_name, const std::set< BoundaryID > &bc_ids, libMesh::DofMap &dof_map, std::set< std::string > &var_sections, const std::map< BoundaryID, std::vector< libMesh::subdomain_id_type > > &bc_id_to_subdomain_id_map, std::vector< SharedPtr< NeumannBCContainer > > &neumann_bcs)
Helper function to build boundary conditions using Variable sections.
void parse_and_build_bc_id_map (const GetPot &input, std::map< std::string, std::set< BoundaryID > > &bc_id_map)
void verify_bc_ids_with_mesh (const MultiphysicsSystem &system, const std::map< std::string, std::set< BoundaryID > > &bc_id_map) const
void build_periodic_bc (const GetPot &input, libMesh::System &system, const std::set< BoundaryID > &bc_ids, const std::string &section)
void parse_periodic_master_slave_ids (const GetPot &input, const std::string &section, libMesh::boundary_id_type &master_id, libMesh::boundary_id_type &slave_id) const
libMesh::RealVectorValue parse_periodic_offset (const GetPot &input, const std::string &section) const
void build_bc_to_subdomain_map_check_with_mesh (const MultiphysicsSystem &system, std::map< BoundaryID, std::vector< libMesh::subdomain_id_type > > &bc_id_to_subdomain_id_map) const
Build up bc_id to subdomain_id map.
bool is_var_active (const FEVariablesBase &var, const std::vector< libMesh::subdomain_id_type > &subdomain_ids) const
Check if the Variable var is active on the given subdomain_id.
Protected Member Functions inherited from GRINS::BCBuilder
void construct_dbc_core (const GetPot &input, MultiphysicsSystem &system, const std::set< BoundaryID > &bc_ids, const FEVariablesBase &fe_var, const std::string &section, const std::string &bc_type, libMesh::DofMap &dof_map)
void construct_nbc_core (const GetPot &input, MultiphysicsSystem &system, const std::set< BoundaryID > &bc_ids, const FEVariablesBase &fe_var, const std::string &section, const std::string &bc_type, std::vector< SharedPtr< NeumannBCContainer > > &neumann_bcs)
bool is_dirichlet_bc_type (const std::string &bc_type)
bool is_neumann_bc_type (const std::string &bc_type)
void add_periodic_bc_to_dofmap (libMesh::boundary_id_type master_id, libMesh::boundary_id_type slave_id, const libMesh::RealVectorValue &offset_vector, libMesh::DofMap &dof_map)
Static Protected Member Functions inherited from GRINS::BCBuilder
static bool is_new_bc_input_style (const GetPot &input)
static libMesh::UniquePtr< BCBuilder > build_builder (const GetPot &input)
Protected Attributes inherited from GRINSTesting::SystemHelper
libMesh::UniquePtr< GetPot > _input
GRINS::SharedPtr< libMesh::UnstructuredMesh > _mesh
libMesh::UniquePtr< libMesh::EquationSystems > _es
GRINS::MultiphysicsSystem * _system
Detailed Description
Definition at line 48 of file default_bc_builder.C.
Member Function Documentation
GRINSTesting::DefaultBCBuilderTest::CPPUNIT_TEST (test_parse_and_build_bc_id_map)
GRINSTesting::DefaultBCBuilderTest::CPPUNIT_TEST (test_verify_bc_ids_with_mesh)
GRINSTesting::DefaultBCBuilderTest::CPPUNIT_TEST (test_parse_periodic_master_slave_ids)
GRINSTesting::DefaultBCBuilderTest::CPPUNIT_TEST (test_parse_periodic_offset)
GRINSTesting::DefaultBCBuilderTest::CPPUNIT_TEST_SUITE (DefaultBCBuilderTest)
GRINSTesting::DefaultBCBuilderTest::CPPUNIT_TEST_SUITE_END ()
void GRINSTesting::DefaultBCBuilderTest::tearDown () inline
Definition at line 64 of file default_bc_builder.C.
References GRINSTesting::SystemHelper::reset_all().
     {
       this->reset_all();
     }
void GRINSTesting::DefaultBCBuilderTest::test_for_var_name (const std::vector< std::string > & var_names, const std::string & var_to_find) inline private
Definition at line 156 of file default_bc_builder.C.
     {
       CPPUNIT_ASSERT( std::find( var_names.begin(), var_names.end(), var_to_find ) != var_names.end() );
     }
void GRINSTesting::DefaultBCBuilderTest::test_parse_and_build_bc_id_map () inline
Definition at line 69 of file default_bc_builder.C.
References GRINS::DefaultBCBuilder::parse_and_build_bc_id_map().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/default_bc_builder.in";
       GetPot input(filename);
       std::map<std::string,std::set<GRINS::BoundaryID> > bc_id_map;
       this->parse_and_build_bc_id_map(input,bc_id_map);
       // Make sure we have the right sections
       CPPUNIT_ASSERT_EQUAL(3,(int)bc_id_map.size());
       CPPUNIT_ASSERT( bc_id_map.find("Hot") != bc_id_map.end() );
       CPPUNIT_ASSERT( bc_id_map.find("Together") != bc_id_map.end() );
       CPPUNIT_ASSERT( bc_id_map.find("Cold") != bc_id_map.end() );
       // Make sure we have the right number and values of the bc ids
       {
         std::set<GRINS::BoundaryID> bc_ids = bc_id_map["Hot"];
         CPPUNIT_ASSERT_EQUAL(1,(int)bc_ids.size());
         CPPUNIT_ASSERT(bc_ids.find(0) != bc_ids.end());
       }
       // Make sure we have the right number and values of the bc ids
       {
         std::set<GRINS::BoundaryID> bc_ids = bc_id_map["Together"];
         CPPUNIT_ASSERT_EQUAL(2,(int)bc_ids.size());
         CPPUNIT_ASSERT(bc_ids.find(1) != bc_ids.end());
         CPPUNIT_ASSERT(bc_ids.find(2) != bc_ids.end());
       }
       // Make sure we have the right number and values of the bc ids
       {
         std::set<GRINS::BoundaryID> bc_ids = bc_id_map["Cold"];
         CPPUNIT_ASSERT_EQUAL(1,(int)bc_ids.size());
         CPPUNIT_ASSERT(bc_ids.find(3) != bc_ids.end());
       }
     }
void GRINSTesting::DefaultBCBuilderTest::test_parse_periodic_master_slave_ids () inline
Definition at line 120 of file default_bc_builder.C.
References GRINSTesting::SystemHelper::_input, GRINS::BoundaryConditionNames::bc_section(), GRINS::DefaultBCBuilder::parse_periodic_master_slave_ids(), and GRINSTesting::SystemHelper::setup_multiphysics_system().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/default_bc_builder.in";
       this->setup_multiphysics_system(filename);
       libMesh::boundary_id_type invalid_bid =
         std::numeric_limits<libMesh::boundary_id_type>::max();
       libMesh::boundary_id_type master_id = invalid_bid;
       libMesh::boundary_id_type slave_id = invalid_bid;
       std::string section = GRINS::BoundaryConditionNames::bc_section()+"/Together";
       this->parse_periodic_master_slave_ids(*_input,section,master_id,slave_id);
       CPPUNIT_ASSERT_EQUAL(1,(int)master_id);
       CPPUNIT_ASSERT_EQUAL(2,(int)slave_id);
     }
void GRINSTesting::DefaultBCBuilderTest::test_parse_periodic_offset () inline
Definition at line 139 of file default_bc_builder.C.
References GRINSTesting::SystemHelper::_input, GRINS::BoundaryConditionNames::bc_section(), GRINS::DefaultBCBuilder::parse_periodic_offset(), and GRINSTesting::SystemHelper::setup_multiphysics_system().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/default_bc_builder.in";
       this->setup_multiphysics_system(filename);
       std::string section = GRINS::BoundaryConditionNames::bc_section()+"/Together";
       libMesh::RealVectorValue offset =
         this->parse_periodic_offset(*_input,section);
       libMesh::Real tol = std::numeric_limits<libMesh::Real>::epsilon()*10;
       CPPUNIT_ASSERT_DOUBLES_EQUAL(1.21,offset(0),tol);
       CPPUNIT_ASSERT_DOUBLES_EQUAL(0.0,offset(1),tol);
     }
void GRINSTesting::DefaultBCBuilderTest::test_verify_bc_ids_with_mesh () inline
Definition at line 106 of file default_bc_builder.C.
References GRINSTesting::SystemHelper::_input, GRINSTesting::SystemHelper::_system, GRINS::DefaultBCBuilder::parse_and_build_bc_id_map(), GRINSTesting::SystemHelper::setup_multiphysics_system(), and GRINS::DefaultBCBuilder::verify_bc_ids_with_mesh().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/default_bc_builder.in";
       this->setup_multiphysics_system(filename);
       std::map<std::string,std::set<GRINS::BoundaryID> > bc_id_map;
       this->parse_and_build_bc_id_map(*_input,bc_id_map);
       // This shouldn't error
       this->verify_bc_ids_with_mesh( *_system, bc_id_map );
     }
The documentation for this class was generated from the following file:
test/unit/default_bc_builder.C