GRINS-0.7.0: GRINS::PrescribedMoleFractionsDirichletOldStyleBCFactory Class Reference
GRINS::PrescribedMoleFractionsDirichletOldStyleBCFactory Class Reference
#include <prescribed_vector_value_dirichlet_old_style_bc_factory.h>
Public Member Functions
PrescribedMoleFractionsDirichletOldStyleBCFactory (const std::string &bc_type_name)
Public Member Functions inherited from GRINS::PrescribedSpeciesDirichletOldStyleBCFactory
PrescribedSpeciesDirichletOldStyleBCFactory (const std::string &bc_type_name)
Public Member Functions inherited from GRINS::PrescribedVectorValueDirichletOldStyleBCFactory
PrescribedVectorValueDirichletOldStyleBCFactory (const std::string &bc_type_name)
~PrescribedVectorValueDirichletOldStyleBCFactory ()
Public Member Functions inherited from GRINS::DirichletBCFactoryFunctionOldStyleBase< libMesh::FunctionBase< libMesh::Number > >
DirichletBCFactoryFunctionOldStyleBase (const std::string &bc_type_name)
~DirichletBCFactoryFunctionOldStyleBase ()
Public Member Functions inherited from GRINS::DirichletBCFactoryFunctionBase< libMesh::FunctionBase< libMesh::Number > >
DirichletBCFactoryFunctionBase (const std::string &bc_type_name)
~DirichletBCFactoryFunctionBase ()
Public Member Functions inherited from GRINS::DirichletBCFactoryAbstract
DirichletBCFactoryAbstract (const std::string &bc_type_name)
~DirichletBCFactoryAbstract ()
Public Member Functions inherited from GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >
BCFactoryAbstract (const std::string &bc_type_name)
~BCFactoryAbstract ()
Public Member Functions inherited from GRINS::FactoryWithGetPot< libMesh::DirichletBoundary >
FactoryWithGetPot (const std::string &name)
~FactoryWithGetPot ()
Protected Member Functions
virtual void add_funcs (const GetPot &input, MultiphysicsSystem &system, const std::string &input_string, const std::vector< std::string > &var_names, libMesh::CompositeFunction< libMesh::Number > &composite_func) const
template<typename ChemistryType >
void convert_mole_fracs_and_add_to_func (const GetPot &input, const std::vector< libMesh::Number > &species_mole_fracs, const SpeciesMassFractionsFEVariables &species_fe_var, libMesh::CompositeFunction< libMesh::Number > &composite_func) const
Protected Member Functions inherited from GRINS::PrescribedSpeciesDirichletOldStyleBCFactory
virtual std::string var_input_string ()
Protected Member Functions inherited from GRINS::PrescribedVectorValueDirichletOldStyleBCFactory
virtual libMesh::UniquePtr< libMesh::FunctionBase< libMesh::Number > > build_func (const GetPot &input, MultiphysicsSystem &system, std::vector< std::string > &var_names, const std::string &section)
Builds the FunctionBase object for boundary condition.
Protected Member Functions inherited from GRINS::DirichletBCFactoryFunctionOldStyleBase< libMesh::FunctionBase< libMesh::Number > >
virtual void check_state () const
Helper function.
virtual void reset_state ()
Helper function.
virtual const std::vector< std::string > & get_var_names () const
Helper function that can be overridded in subclasses.
Protected Member Functions inherited from GRINS::DirichletBCFactoryFunctionBase< libMesh::FunctionBase< libMesh::Number > >
libMesh::UniquePtr< libMesh::DirichletBoundary > make_dirichlet_boundary (const std::set< BoundaryID > &bc_ids, const libMesh::System &system, libMesh::UniquePtr< libMesh::FunctionBase< libMesh::Number > > &func, const std::vector< VariableIndex > &var_indices)
Dispatch, based on FunctionType, to the correct DirchletBoundary construction.
Protected Member Functions inherited from GRINS::DirichletBCFactoryAbstract
void check_for_vars (const GetPot &input, const std::string &section, const std::vector< std::string > &var_names, std::set< std::string > *vars_found=NULL)
Helper function.
Protected Member Functions inherited from GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >
void check_for_multiple_expressions (const GetPot &input, const std::string &section, const std::string &var_name) const
Ensure that there is only one expression for the [Section/var_name] variable.
void build_var_indices (const MultiphysicsSystem &system, const std::vector< std::string > &var_names, std::vector< VariableIndex > &var_indices) const
Additional Inherited Members
Static Public Member Functions inherited from GRINS::DirichletBCFactoryFunctionOldStyleBase< libMesh::FunctionBase< libMesh::Number > >
static void set_value_var_old_style (const std::string &value_var)
Input variable for parsing old style.
static void set_value_index_old_style (unsigned int idx)
Input variable index for parsing old style.
static void set_var_names_old_style (const std::vector< std::string > &var_names)
Static Public Member Functions inherited from GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >
static void set_system (MultiphysicsSystem &system)
static void set_bc_ids (const std::set< BoundaryID > &bc_ids)
Boundary id for the current boundary condition section.
static void set_fe_var (const FEVariablesBase &fe_var)
Active variable for the current boundary condition.
static void set_section (const std::string &section)
Sets the current section of the input file.
static bool have_bc_type (const std::string &bc_type)
Static Public Member Functions inherited from GRINS::FactoryWithGetPot< libMesh::DirichletBoundary >
static void set_getpot (const GetPot &input)
Static Protected Attributes inherited from GRINS::DirichletBCFactoryFunctionOldStyleBase< libMesh::FunctionBase< libMesh::Number > >
static std::string _value_var_old_style
static unsigned int _value_idx_old_style
static const std::vector< std::string > * _var_names_old_style
Static Protected Attributes inherited from GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >
static MultiphysicsSystem * _system
We store only a raw pointer here because we can't make a copy.
static const std::set< BoundaryID > * _bc_ids
BoundaryID for constructing a particular boundary condition.
static const FEVariablesBase * _fe_var
The FEVariablesBase class associated with the boundary condition being built.
static std::string _section
Static Protected Attributes inherited from GRINS::FactoryWithGetPot< libMesh::DirichletBoundary >
static const GetPot * _input
We store only a raw pointer here because we can't make a copy.
Detailed Description
Definition at line 109 of file prescribed_vector_value_dirichlet_old_style_bc_factory.h.
Constructor & Destructor Documentation
GRINS::PrescribedMoleFractionsDirichletOldStyleBCFactory::PrescribedMoleFractionsDirichletOldStyleBCFactory (const std::string & bc_type_name) inline
Definition at line 113 of file prescribed_vector_value_dirichlet_old_style_bc_factory.h.
       : PrescribedSpeciesDirichletOldStyleBCFactory(bc_type_name)
     {}
Member Function Documentation
void GRINS::PrescribedMoleFractionsDirichletOldStyleBCFactory::add_funcs (const GetPot & input, MultiphysicsSystem & system, const std::string & input_string, const std::vector< std::string > & var_names, libMesh::CompositeFunction< libMesh::Number > & composite_func) const protected virtual
Reimplemented from GRINS::PrescribedVectorValueDirichletOldStyleBCFactory.
Definition at line 93 of file prescribed_vector_value_dirichlet_old_style_bc_factory.C.
References GRINS::PhysicsFactoryHelper::parse_thermochemistry_model(), GRINS::PhysicsNaming::reacting_low_mach_navier_stokes(), and GRINS::VariablesParsing::species_mass_fractions_section().
   {
     const unsigned int n_vars = var_names.size();
     // Parse in all the species mole fracs that are in the input
     std::vector<libMesh::Number> species_mole_fracs(n_vars);
     libMesh::Number invalid_num = std::numeric_limits<libMesh::Number>::max();
     if( input.vector_variable_size(input_string) != n_vars )
       libmesh_error_msg("ERROR: Expected "+StringUtilities::T_to_string<unsigned int>(n_vars)+" components in "+input_string);
     for(unsigned int v = 0; v < n_vars; v++ )
       species_mole_fracs[v] = input(input_string,invalid_num,v);
     // Make sure mole fracs sum to 1
     libMesh::Number sum = 0.0;
     for(unsigned int v = 0; v < n_vars; v++ )
       sum += species_mole_fracs[v];
     libMesh::Number tol = std::numeric_limits<libMesh::Number>::epsilon()*10;
     if( std::abs(sum-1.0) > tol )
       libmesh_error_msg("ERROR: Mole fractions do not sum to 1! Found sum = "+StringUtilities::T_to_string<libMesh::Number>(sum));
     // To avoid compiler warnings without GRINS or Cantera
 #if defined(GRINS_HAVE_ANTIOCH) || defined(GRINS_HAVE_CANTERA)
     // This only makes sense for SpeciesMassFractionsFEVariables in the
     // VariableWarehouse. This call will error out if it's not there.
     const SpeciesMassFractionsFEVariables& species_fe_var =
       GRINSPrivate::VariableWarehouse::get_variable_subclass<SpeciesMassFractionsFEVariables>
       (VariablesParsing::species_mass_fractions_section());
 #endif
     std::string thermochem_lib;
     PhysicsFactoryHelper::parse_thermochemistry_model( input,
                                                        PhysicsNaming::reacting_low_mach_navier_stokes(),
                                                        thermochem_lib );
     if( thermochem_lib == "cantera" )
       {
 #ifdef GRINS_HAVE_CANTERA
         this->convert_mole_fracs_and_add_to_func<CanteraMixture>(input,
                                                                  species_mole_fracs,
                                                                  species_fe_var,
                                                                  composite_func);
 #else
         libmesh_error_msg("Error: Cantera not enabled in this configuration. Reconfigure using --with-cantera option.");
 #endif
       }
     else if( thermochem_lib == "antioch" )
       {
 #ifdef GRINS_HAVE_ANTIOCH
         this->convert_mole_fracs_and_add_to_func<AntiochChemistry>(input,
                                                                    species_mole_fracs,
                                                                    species_fe_var,
                                                                    composite_func);
 #else
         libmesh_error_msg("Error: Antioch not enabled in this configuration. Reconfigure using --with-antioch option.");
 #endif
       }
     else
       libmesh_error_msg("ERROR: Invalid thermochemistry library "+thermochem_lib+"!");
   }
template<typename ChemistryType > template void GRINS::PrescribedMoleFractionsDirichletOldStyleBCFactory::convert_mole_fracs_and_add_to_func< AntiochChemistry > (const GetPot & input, const std::vector< libMesh::Number > & species_mole_fracs, const SpeciesMassFractionsFEVariables & species_fe_var, libMesh::CompositeFunction< libMesh::Number > & composite_func) const protected
Todo:
We should have a ChemsitryWarehouse or something to just grab this from one place instead of rebuilding.
Definition at line 171 of file prescribed_vector_value_dirichlet_old_style_bc_factory.C.
References GRINS::SpeciesMassFractionsFEVariables::material(), and GRINS::SpeciesMassFractionsFEVariables::species().
   {
     const std::string& material = species_fe_var.material();
     ChemistryType chem(input,material);
     const unsigned int n_vars = species_mole_fracs.size();
     // Compute M
     libMesh::Real M = 0.0;
     for( unsigned int s = 0; s < n_vars; s++ )
       M += species_mole_fracs[s]*chem.M(s);
     // Convert mole fractions to mass fractions and add to function
     for( unsigned int s = 0; s < n_vars; s++ )
       {
         libMesh::Number species_mass_fracs =species_mole_fracs[s]*chem.M(s)/M;
         std::vector<VariableIndex> var_idx(1,species_fe_var.species(s));
         libMesh::ConstFunction<libMesh::Number> const_func(species_mass_fracs);
         composite_func.attach_subfunction(const_func,var_idx);
       }
   }
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/prescribed_vector_value_dirichlet_old_style_bc_factory.h
src/boundary_conditions/src/prescribed_vector_value_dirichlet_old_style_bc_factory.C