GRINS-0.7.0: GRINS::PrimitiveTempFEVariables Class Reference
GRINS::PrimitiveTempFEVariables Class Reference
#include <primitive_temp_fe_variables.h>
Public Member Functions
PrimitiveTempFEVariables (const GetPot &input, const std::string &physics_name, bool _is_constraint_var=false)
~PrimitiveTempFEVariables ()
VariableIndex T () const
Public Member Functions inherited from GRINS::SingleVarSingleFETypeVariable
SingleVarSingleFETypeVariable (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &old_var_name, const std::string &default_name, const std::string &subsection, const std::string &default_family, const std::string &default_order, bool is_constraint_var)
Deprecated, old style constructor.
SingleVarSingleFETypeVariable (const GetPot &input, const std::string &subsection, const std::string &default_name, bool is_constraint_var)
Primary constructor.
~SingleVarSingleFETypeVariable ()
Public Member Functions inherited from GRINS::SingleFETypeVariable
SingleFETypeVariable (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &subsection, const std::string &default_family, const std::string &default_order, bool is_constraint_var)
Deprecated, old style constructor.
SingleFETypeVariable (const GetPot &input, const std::string &subsection, bool is_constraint_var)
Primary constructor.
~SingleFETypeVariable ()
virtual void init (libMesh::FEMSystem *system)
Add variables to the system.
Public Member Functions inherited from GRINS::FEVariablesBase
FEVariablesBase (bool is_constraint_var)
~FEVariablesBase ()
bool is_constraint_var () const
void set_neumann_bc_is_positive (bool is_positive)
Reset whetever Neumann bc is postive or not.
libMesh::Real neumann_bc_sign () const
const std::vector< std::string > & active_var_names () const
Return the var names that are active from this class.
const std::vector< VariableIndex > & var_indices () const
Protected Member Functions
std::string old_var_name () const
std::string subsection () const
std::string default_name () const
Protected Member Functions inherited from GRINS::SingleFETypeVariable
void parse_family_and_order (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &subsection, std::vector< GRINSEnums::FEFamily > &family, std::vector< GRINSEnums::Order > &order, const std::string &default_family, const std::string &default_order)
Helper function to parse FEFamily and Order.
void dup_family_order_check (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix) const
Check (and error if true) for old and new style FEFamily/Order input.
bool have_family_or_order (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &subsection) const
Check for no presence of FEFamily/Order input.
void parse_old_style_with_warning (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &default_family, const std::string &default_order, const std::string &subsection, GRINSEnums::FEFamily &family, GRINSEnums::Order &order)
void parse_new_style (const GetPot &input, const std::string &subsection, GRINSEnums::FEFamily &family, GRINSEnums::Order &order)
Protected Member Functions inherited from GRINS::FEVariablesBase
void parse_names_from_input (const GetPot &input, const std::string &subsection, std::vector< std::string > &var_names, const std::vector< std::string > &default_names)
Method to parse variable names from input.
void duplicate_name_section_check (const GetPot &input) const
Check for old name style and new name style. If both present, error.
bool check_dep_name_input (const GetPot &input, const std::string &new_subsection) const
Check for deprecated variable name input style.
Private Member Functions
PrimitiveTempFEVariables ()
Additional Inherited Members
Protected Attributes inherited from GRINS::FEVariablesBase
std::vector< VariableIndex > _vars
std::vector< std::string > _var_names
std::vector< GRINSEnums::FEFamily > _family
std::vector< GRINSEnums::Order > _order
bool _is_constraint_var
Tracks whether this is a constraint variable.
libMesh::Real _neumann_bc_sign
Track the sign of the Neumann BC term. Defaults to 1.0.
Detailed Description
Definition at line 41 of file primitive_temp_fe_variables.h.
Constructor & Destructor Documentation
GRINS::PrimitiveTempFEVariables::PrimitiveTempFEVariables (const GetPot & input, const std::string & physics_name, bool _is_constraint_var = false) inline
Definition at line 45 of file primitive_temp_fe_variables.h.
       :  SingleVarSingleFETypeVariable(input,physics_name,"T_",this->old_var_name(),this->default_name(),
                                        this->subsection(),"LAGRANGE","SECOND",_is_constraint_var)
     {}
GRINS::PrimitiveTempFEVariables::~PrimitiveTempFEVariables () inline
Definition at line 51 of file primitive_temp_fe_variables.h.
 {};
GRINS::PrimitiveTempFEVariables::PrimitiveTempFEVariables () private
Member Function Documentation
std::string GRINS::PrimitiveTempFEVariables::default_name () const inline protected
Definition at line 63 of file primitive_temp_fe_variables.h.
     { return "T"; }
std::string GRINS::PrimitiveTempFEVariables::old_var_name () const inline protected
Definition at line 57 of file primitive_temp_fe_variables.h.
References GRINS::VariablesParsing::temperature_section().
     { return VariablesParsing::temperature_section(); }
std::string GRINS::PrimitiveTempFEVariables::subsection () const inline protected
Definition at line 60 of file primitive_temp_fe_variables.h.
References GRINS::VariablesParsing::temperature_section().
     { return VariablesParsing::temperature_section(); }
VariableIndex GRINS::PrimitiveTempFEVariables::T () const inline
Definition at line 73 of file primitive_temp_fe_variables.h.
References GRINS::FEVariablesBase::_vars.
Referenced by GRINS::HeatTransferStabilizationHelper::compute_res_energy_steady(), GRINS::HeatTransferStabilizationHelper::compute_res_energy_transient(), GRINS::BoussinesqBuoyancy::element_time_derivative(), GRINS::AxisymmetricBoussinesqBuoyancy::element_time_derivative(), GRINS::ReactingLowMachNavierStokesAbstract::init_context(), GRINS::AxisymmetricBoussinesqBuoyancy::init_context(), GRINS::ReactingLowMachNavierStokesAbstract::set_time_evolving_vars(), and GRINS::ReactingLowMachNavierStokesAbstract::T().
   {
     return _vars[0];
   }
The documentation for this class was generated from the following file:
src/variables/include/grins/primitive_temp_fe_variables.h