GRINS-0.7.0: GRINSTesting::VariablesTest Class Reference
GRINSTesting::VariablesTest Class Reference
Public Member Functions
CPPUNIT_TEST_SUITE (VariablesTest)
CPPUNIT_TEST (test_velocity_2d)
CPPUNIT_TEST (test_velocity_3d)
CPPUNIT_TEST (test_temp)
CPPUNIT_TEST (test_species_mass_fracs)
CPPUNIT_TEST (test_pressure)
CPPUNIT_TEST (test_var_constraint_and_warehouse)
CPPUNIT_TEST_SUITE_END ()
void tearDown ()
void test_velocity_2d ()
void test_velocity_3d ()
void test_temp ()
void test_species_mass_fracs ()
void test_var_constraint_and_warehouse ()
void test_pressure ()
Private Member Functions
void test_vel_var_names_2d (const std::vector< std::string > &var_names)
void test_vel_var_names_3d (const std::vector< std::string > &var_names)
void test_temp_var_names (const std::vector< std::string > &var_names)
void test_species_var_names (const std::vector< std::string > &var_names)
void test_press_var_names (const std::vector< std::string > &var_names)
void test_species_var_names_no_order (const std::vector< std::string > &var_names)
void test_vel_fe_2d (const libMesh::System &system)
void test_vel_fe_3d (const libMesh::System &system)
void test_temp_fe (const libMesh::System &system)
void test_press_fe (const libMesh::System &system)
void test_species_fe (const libMesh::System &system)
Additional Inherited Members
Protected Member Functions inherited from GRINSTesting::SystemHelper
void setup_multiphysics_system (const std::string &filename)
void reset_all ()
Protected Attributes inherited from GRINSTesting::SystemHelper
libMesh::UniquePtr< GetPot > _input
GRINS::SharedPtr< libMesh::UnstructuredMesh > _mesh
libMesh::UniquePtr< libMesh::EquationSystems > _es
GRINS::MultiphysicsSystem * _system
Detailed Description
Definition at line 47 of file variables.C.
Member Function Documentation
GRINSTesting::VariablesTest::CPPUNIT_TEST (test_velocity_2d)
GRINSTesting::VariablesTest::CPPUNIT_TEST (test_velocity_3d)
GRINSTesting::VariablesTest::CPPUNIT_TEST (test_temp)
GRINSTesting::VariablesTest::CPPUNIT_TEST (test_species_mass_fracs)
GRINSTesting::VariablesTest::CPPUNIT_TEST (test_pressure)
GRINSTesting::VariablesTest::CPPUNIT_TEST (test_var_constraint_and_warehouse)
GRINSTesting::VariablesTest::CPPUNIT_TEST_SUITE (VariablesTest)
GRINSTesting::VariablesTest::CPPUNIT_TEST_SUITE_END ()
void GRINSTesting::VariablesTest::tearDown () inline
Definition at line 64 of file variables.C.
References GRINSTesting::SystemHelper::reset_all().
     {
       this->reset_all();
     }
void GRINSTesting::VariablesTest::test_press_fe (const libMesh::System & system) inline private
Definition at line 261 of file variables.C.
Referenced by test_pressure().
     {
       libMesh::Order order = system.variable_type("p").order;
       CPPUNIT_ASSERT_EQUAL(GRINSEnums::LAGRANGE,system.variable_type("p").family);
       CPPUNIT_ASSERT_EQUAL(GRINSEnums::FIRST,order);
     }
void GRINSTesting::VariablesTest::test_press_var_names (const std::vector< std::string > & var_names) inline private
Definition at line 218 of file variables.C.
Referenced by test_pressure().
     {
       CPPUNIT_ASSERT_EQUAL(1,(int)var_names.size());
       CPPUNIT_ASSERT_EQUAL(std::string("p"),var_names[0]);
     }
void GRINSTesting::VariablesTest::test_pressure () inline
Definition at line 169 of file variables.C.
References GRINSTesting::SystemHelper::_input, GRINSTesting::SystemHelper::_system, GRINS::FEVariablesBase::active_var_names(), GRINS::SingleFETypeVariable::init(), GRINSTesting::SystemHelper::setup_multiphysics_system(), test_press_fe(), and test_press_var_names().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/variables_2d.in";
       this->setup_multiphysics_system(filename);
       // This will add the variables to the system
       GRINS::PressureFEVariable press_vars(*_input,"PhysicsNameIsDUMMYForThisTest");
       press_vars.init(_system);
       CPPUNIT_ASSERT_EQUAL((unsigned int)1,_system->n_vars());
       const std::vector<std::string>& var_names = press_vars.active_var_names();
       this->test_press_var_names(var_names);
       // Verify the FE part
       this->test_press_fe(*_system);
     }
void GRINSTesting::VariablesTest::test_species_fe (const libMesh::System & system) inline private
Definition at line 269 of file variables.C.
Referenced by test_species_mass_fracs().
     {
       libMesh::Order order = system.variable_type("Y_N2").order;
       CPPUNIT_ASSERT_EQUAL(GRINSEnums::LAGRANGE,system.variable_type("Y_N2").family);
       CPPUNIT_ASSERT_EQUAL(GRINSEnums::SECOND,order);
       order = system.variable_type("Y_N").order;
       CPPUNIT_ASSERT_EQUAL(GRINSEnums::LAGRANGE,system.variable_type("Y_N").family);
       CPPUNIT_ASSERT_EQUAL(GRINSEnums::SECOND,order);
     }
void GRINSTesting::VariablesTest::test_species_mass_fracs () inline
Definition at line 120 of file variables.C.
References GRINSTesting::SystemHelper::_input, GRINSTesting::SystemHelper::_system, GRINS::FEVariablesBase::active_var_names(), GRINS::SingleFETypeVariable::init(), GRINSTesting::SystemHelper::setup_multiphysics_system(), test_species_fe(), and test_species_var_names().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/variables_2d.in";
       this->setup_multiphysics_system(filename);
       // This will add the variables to the system
       GRINS::SpeciesMassFractionsFEVariables species_vars(*_input,"TestSpeciesMassFractionsVariables");
       species_vars.init(_system);
       CPPUNIT_ASSERT_EQUAL((unsigned int)2,_system->n_vars());
       const std::vector<std::string>& var_names = species_vars.active_var_names();
       this->test_species_var_names(var_names);
       // Verify the FE part
       this->test_species_fe(*_system);
     }
void GRINSTesting::VariablesTest::test_species_var_names (const std::vector< std::string > & var_names) inline private
Definition at line 211 of file variables.C.
Referenced by test_species_mass_fracs().
     {
       CPPUNIT_ASSERT_EQUAL(2,(int)var_names.size());
       CPPUNIT_ASSERT_EQUAL(std::string("Y_N2"),var_names[0]);
       CPPUNIT_ASSERT_EQUAL(std::string("Y_N"),var_names[1]);
     }
void GRINSTesting::VariablesTest::test_species_var_names_no_order (const std::vector< std::string > & var_names) inline private
Definition at line 224 of file variables.C.
     {
       // For this one, we can't guarantee the order, so we check to
       // make sure both the species are there.
       CPPUNIT_ASSERT_EQUAL(2,(int)var_names.size());
       CPPUNIT_ASSERT( std::find( var_names.begin(), var_names.end(),"Y_N2")
                         != var_names.end() );
       CPPUNIT_ASSERT( std::find( var_names.begin(), var_names.end(),"Y_N")
                         != var_names.end() );
     }
void GRINSTesting::VariablesTest::test_temp () inline
Definition at line 103 of file variables.C.
References GRINSTesting::SystemHelper::_input, GRINSTesting::SystemHelper::_system, GRINS::FEVariablesBase::active_var_names(), GRINS::SingleFETypeVariable::init(), GRINSTesting::SystemHelper::setup_multiphysics_system(), test_temp_fe(), and test_temp_var_names().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/variables_2d.in";
       this->setup_multiphysics_system(filename);
       // This will add the variables to the system
       GRINS::PrimitiveTempFEVariables temp_vars(*_input,"PhysicsNameIsDUMMYForThisTest");
       temp_vars.init(_system);
       CPPUNIT_ASSERT_EQUAL((unsigned int)1,_system->n_vars());
       const std::vector<std::string>& var_names = temp_vars.active_var_names();
       this->test_temp_var_names(var_names);
       // Verify the FE part
       this->test_temp_fe(*_system);
     }
void GRINSTesting::VariablesTest::test_temp_fe (const libMesh::System & system) inline private
Definition at line 254 of file variables.C.
Referenced by test_temp().
     {
       libMesh::Order order = system.variable_type("T").order;
       CPPUNIT_ASSERT_EQUAL(GRINSEnums::LAGRANGE,system.variable_type("T").family);
       CPPUNIT_ASSERT_EQUAL(GRINSEnums::FIRST,order);
     }
void GRINSTesting::VariablesTest::test_temp_var_names (const std::vector< std::string > & var_names) inline private
Definition at line 205 of file variables.C.
Referenced by test_temp().
     {
       CPPUNIT_ASSERT_EQUAL(1,(int)var_names.size());
       CPPUNIT_ASSERT_EQUAL(std::string("T"),var_names[0]);
     }
void GRINSTesting::VariablesTest::test_var_constraint_and_warehouse () inline
Definition at line 137 of file variables.C.
References GRINSTesting::SystemHelper::_input, GRINSTesting::SystemHelper::_system, GRINS::GRINSPrivate::VariableWarehouse::check_and_register_variable(), GRINS::GRINSPrivate::VariableWarehouse::clear(), GRINS::GRINSPrivate::VariableWarehouse::get_variable(), GRINS::VelocityFEVariables::init(), GRINS::SingleFETypeVariable::init(), GRINS::FEVariablesBase::is_constraint_var(), GRINS::GRINSPrivate::VariableWarehouse::register_variable(), and GRINSTesting::SystemHelper::setup_multiphysics_system().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/variables_3d.in";
       this->setup_multiphysics_system(filename);
       GRINS::VelocityFEVariables vel_vars(*_input,"PhysicsNameIsDUMMYForThisTest");
       GRINS::PressureFEVariable press_vars(*_input,"PhysicsNameIsDUMMYForThisTest",true /*is_constraint_variable*/ );
       GRINS::GRINSPrivate::VariableWarehouse::register_variable("Velocity", vel_vars);
       GRINS::GRINSPrivate::VariableWarehouse::register_variable("Pressure", press_vars);
       // This should not throw an error
       GRINS::GRINSPrivate::VariableWarehouse::check_and_register_variable("Velocity", vel_vars);
       GRINS::GRINSPrivate::VariableWarehouse::check_and_register_variable("Pressure", press_vars);
       vel_vars.init(_system);
       press_vars.init(_system);
       {
         const GRINS::FEVariablesBase& vel_base =
           GRINS::GRINSPrivate::VariableWarehouse::get_variable("Velocity");
         CPPUNIT_ASSERT(!vel_base.is_constraint_var());
         const GRINS::FEVariablesBase& press_base =
           GRINS::GRINSPrivate::VariableWarehouse::get_variable("Pressure");
         CPPUNIT_ASSERT(press_base.is_constraint_var());
       }
       // Clear out the VariableWarehouse so it doesn't interfere with other tests.
       GRINS::GRINSPrivate::VariableWarehouse::clear();
     }
void GRINSTesting::VariablesTest::test_vel_fe_2d (const libMesh::System & system) inline private
Definition at line 235 of file variables.C.
Referenced by test_vel_fe_3d(), and test_velocity_2d().
     {
       libMesh::Order order = system.variable_type("Ux").order;
       CPPUNIT_ASSERT_EQUAL(GRINSEnums::LAGRANGE,system.variable_type("Ux").family);
       CPPUNIT_ASSERT_EQUAL(GRINSEnums::FIRST,order);
       order = system.variable_type("Uy").order;
       CPPUNIT_ASSERT_EQUAL(GRINSEnums::LAGRANGE,system.variable_type("Uy").family);
       CPPUNIT_ASSERT_EQUAL(GRINSEnums::FIRST,order);
     }
void GRINSTesting::VariablesTest::test_vel_fe_3d (const libMesh::System & system) inline private
Definition at line 246 of file variables.C.
References test_vel_fe_2d().
Referenced by test_velocity_3d().
     {
       this->test_vel_fe_2d(system);
       libMesh::Order order = system.variable_type("Uz").order;
       CPPUNIT_ASSERT_EQUAL(GRINSEnums::LAGRANGE,system.variable_type("Uz").family);
       CPPUNIT_ASSERT_EQUAL(GRINSEnums::FIRST,order);
     }
void GRINSTesting::VariablesTest::test_vel_var_names_2d (const std::vector< std::string > & var_names) inline private
Definition at line 188 of file variables.C.
Referenced by test_velocity_2d().
     {
       // For 2-D, we should only have 2 components
       CPPUNIT_ASSERT_EQUAL(2,(int)var_names.size());
       CPPUNIT_ASSERT_EQUAL(std::string("Ux"),var_names[0]);
       CPPUNIT_ASSERT_EQUAL(std::string("Uy"),var_names[1]);
     }
void GRINSTesting::VariablesTest::test_vel_var_names_3d (const std::vector< std::string > & var_names) inline private
Definition at line 196 of file variables.C.
Referenced by test_velocity_3d().
     {
       // For 3-D, we should have 3 components
       CPPUNIT_ASSERT_EQUAL(3,(int)var_names.size());
       CPPUNIT_ASSERT_EQUAL(std::string("Ux"),var_names[0]);
       CPPUNIT_ASSERT_EQUAL(std::string("Uy"),var_names[1]);
       CPPUNIT_ASSERT_EQUAL(std::string("Uz"),var_names[2]);
     }
void GRINSTesting::VariablesTest::test_velocity_2d () inline
Definition at line 69 of file variables.C.
References GRINSTesting::SystemHelper::_input, GRINSTesting::SystemHelper::_system, GRINS::FEVariablesBase::active_var_names(), GRINS::VelocityFEVariables::init(), GRINSTesting::SystemHelper::setup_multiphysics_system(), test_vel_fe_2d(), and test_vel_var_names_2d().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/variables_2d.in";
       this->setup_multiphysics_system(filename);
       // This will add the variables to the system
       GRINS::VelocityFEVariables vel_vars(*_input,"PhysicsNameIsDUMMYForThisTest");
       vel_vars.init(_system);
       CPPUNIT_ASSERT_EQUAL((unsigned int)2,_system->n_vars());
       const std::vector<std::string>& var_names = vel_vars.active_var_names();
       this->test_vel_var_names_2d(var_names);
       // Verify the FE part
       this->test_vel_fe_2d(*_system);
     }
void GRINSTesting::VariablesTest::test_velocity_3d () inline
Definition at line 86 of file variables.C.
References GRINSTesting::SystemHelper::_input, GRINSTesting::SystemHelper::_system, GRINS::FEVariablesBase::active_var_names(), GRINS::VelocityFEVariables::init(), GRINSTesting::SystemHelper::setup_multiphysics_system(), test_vel_fe_3d(), and test_vel_var_names_3d().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/variables_3d.in";
       this->setup_multiphysics_system(filename);
       // This will add the variables to the system
       GRINS::VelocityFEVariables vel_vars(*_input,"PhysicsNameIsDUMMYForThisTest");
       vel_vars.init(_system);
       CPPUNIT_ASSERT_EQUAL((unsigned int)3,_system->n_vars());
       const std::vector<std::string>& var_names = vel_vars.active_var_names();
       this->test_vel_var_names_3d(var_names);
       // Verify the FE part
       this->test_vel_fe_3d(*_system);
     }
The documentation for this class was generated from the following file:
test/unit/variables.C