GRINS-0.7.0: GRINS::SimulationParsing Class Reference
GRINS::SimulationParsing Class Reference
#include <simulation_parsing.h>
Public Member Functions
SimulationParsing ()
~SimulationParsing ()
Static Public Member Functions
static bool have_restart (const GetPot &input)
static std::string restart_file (const GetPot &input)
Static Private Member Functions
static std::string restart_input_option ()
Detailed Description
Definition at line 36 of file simulation_parsing.h.
Constructor & Destructor Documentation
GRINS::SimulationParsing::SimulationParsing () inline
Definition at line 40 of file simulation_parsing.h.
 {};
GRINS::SimulationParsing::~SimulationParsing () inline
Definition at line 42 of file simulation_parsing.h.
 {};
Member Function Documentation
static bool GRINS::SimulationParsing::have_restart (const GetPot & input) inline static
Definition at line 44 of file simulation_parsing.h.
References restart_input_option().
     { return input.have_variable( SimulationParsing::restart_input_option() ); }
static std::string GRINS::SimulationParsing::restart_file (const GetPot & input) inline static
Definition at line 47 of file simulation_parsing.h.
References restart_input_option().
Referenced by GRINS::Simulation::read_restart().
     { return input( SimulationParsing::restart_input_option(), "none" ); }
static std::string GRINS::SimulationParsing::restart_input_option () inline static private
Definition at line 52 of file simulation_parsing.h.
Referenced by have_restart(), and restart_file().
     { return "restart-options/restart_file"; }
The documentation for this class was generated from the following file:
src/solver/include/grins/simulation_parsing.h