GRINS-0.6.0: GRINS::ParsedConductivity Class Reference
GRINS::ParsedConductivity Class Reference
#include <parsed_conductivity.h>
Public Member Functions
ParsedConductivity (const GetPot &input)
~ParsedConductivity ()
libMesh::Real operator() (AssemblyContext &context, unsigned int qp) const
libMesh::Real operator() (const libMesh::Point &p, const libMesh::Real time)
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiPointer< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Private Member Functions
ParsedConductivity ()
Private Attributes
libMesh::AutoPtr< libMesh::FunctionBase< libMesh::Number > > k
Detailed Description
Definition at line 44 of file parsed_conductivity.h.
Constructor & Destructor Documentation
GRINS::ParsedConductivity::ParsedConductivity (const GetPot & input)
Definition at line 29 of file parsed_conductivity.C.
References k.
                                                                :
      ParameterUser("ParsedConductivity")
     {
       if( !input.have_variable("Materials/Conductivity/k") )
        {
          std::cerr<<"No conductivity has been specified."<<std::endl;
          libmesh_error();
        }
       else
        {
          std::string conductivity_function = input("Materials/Conductivity/k",std::string("0"));
          k.reset(new libMesh::ParsedFunction<libMesh::Number>(conductivity_function));
          if (conductivity_function == "0")
             {
               std::cerr << "Warning! Zero Conductivity specified!" << std::endl;
               libmesh_error();
             }
        }
       return;
       }
GRINS::ParsedConductivity::~ParsedConductivity ()
Definition at line 55 of file parsed_conductivity.C.
   {
     return;
   }
GRINS::ParsedConductivity::ParsedConductivity () private
Member Function Documentation
libMesh::Real GRINS::ParsedConductivity::operator() (AssemblyContext & context, unsigned int qp) const inline
Definition at line 66 of file parsed_conductivity.h.
   {
     // FIXME: We should be getting the variable index to get the qps from the context
     // not hardcode it to be 0
     const std::vector<libMesh::Point>& x = context.get_element_fe(0)->get_xyz();
     const libMesh::Point& x_qp = x[qp];
     libMesh::Number _k_value = (*k)(x_qp,context.time);
     return _k_value;
   }
libMesh::Real GRINS::ParsedConductivity::operator() (const libMesh::Point & p, const libMesh::Real time) inline
Definition at line 80 of file parsed_conductivity.h.
References k.
   {
     return (*k)(p,time);
   }
void GRINS::ParameterUser::register_parameter (const std::string & param_name, libMesh::ParameterMultiPointer< libMesh::Number > & param_pointer) const virtual inherited
Each subclass will register its copy of an independent.
Reimplemented in GRINS::AxisymmetricHeatTransfer< Conductivity >, GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::IncompressibleNavierStokesBase< Viscosity >, GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >, GRINS::HeatConduction< Conductivity >, GRINS::HeatTransferBase< Conductivity >, and GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >.
Definition at line 50 of file parameter_user.C.
Referenced by GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::register_parameter(), GRINS::HeatTransferBase< Conductivity >::register_parameter(), GRINS::HeatConduction< Conductivity >::register_parameter(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::register_parameter(), GRINS::IncompressibleNavierStokesBase< Viscosity >::register_parameter(), GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::register_parameter(), and GRINS::AxisymmetricHeatTransfer< Conductivity >::register_parameter().
   {
     std::map<std::string, libMesh::Number*>::const_iterator it =
       _my_parameters.find(param_name);
     if (it != _my_parameters.end())
       {
         std::cout << _my_name << " uses parameter " << param_name
                   << std::endl;
         param_pointer.push_back(it->second);
       }
   }
void GRINS::ParameterUser::set_parameter (libMesh::Number & param_variable, const GetPot & input, const std::string & param_name, libMesh::Number param_default) virtual inherited
Each subclass can simultaneously read a parameter value from.
Definition at line 35 of file parameter_user.C.
References GRINS::ParameterUser::_my_name, and GRINS::ParameterUser::_my_parameters.
Referenced by GRINS::AveragedFanAdjointStabilization< Viscosity >::AveragedFanAdjointStabilization(), GRINS::AveragedTurbineAdjointStabilization< Viscosity >::AveragedTurbineAdjointStabilization(), GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::BoussinesqBuoyancyAdjointStabilization(), GRINS::BoussinesqBuoyancyBase::BoussinesqBuoyancyBase(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::BoussinesqBuoyancySPGSMStabilization(), GRINS::ConstantConductivity::ConstantConductivity(), GRINS::ConstantPrandtlConductivity::ConstantPrandtlConductivity(), GRINS::ConstantSourceFunction::ConstantSourceFunction(), GRINS::ConstantSourceTerm::ConstantSourceTerm(), GRINS::ConstantSpecificHeat::ConstantSpecificHeat(), GRINS::ConstantViscosity::ConstantViscosity(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticCableConstantGravity::ElasticCableConstantGravity(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransferBase< Conductivity >::HeatTransferBase(), GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase(), GRINS::AverageNusseltNumber::init(), GRINS::MooneyRivlin::MooneyRivlin(), GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase(), GRINS::HookesLaw1D::read_input_options(), GRINS::HookesLaw::read_input_options(), GRINS::AxisymmetricBoussinesqBuoyancy::read_input_options(), and GRINS::VelocityDragAdjointStabilization< Viscosity >::VelocityDragAdjointStabilization().
   {
     param_variable = input(param_name, param_default);
     libmesh_assert_msg(!_my_parameters.count(param_name),
       "ERROR: " << _my_name << " double-registered parameter " <<
       param_name);
     _my_parameters[param_name] = &param_variable;
   }
Member Data Documentation
libMesh::AutoPtr<libMesh::FunctionBase<libMesh::Number> > GRINS::ParsedConductivity::k private
Definition at line 60 of file parsed_conductivity.h.
Referenced by operator()(), and ParsedConductivity().
The documentation for this class was generated from the following files:
src/properties/include/grins/parsed_conductivity.h
src/properties/src/parsed_conductivity.C