GRINS-0.6.0: GRINS::AxisymmetricHeatTransfer< Conductivity > Class Template Reference
GRINS::AxisymmetricHeatTransfer< Conductivity > Class Template Reference
Physics class for Axisymmetric Heat Transfer.
#include <axisym_heat_transfer.h>
Public Member Functions
AxisymmetricHeatTransfer (const std::string &physics_name, const GetPot &input)
~AxisymmetricHeatTransfer ()
virtual void read_input_options (const GetPot &input)
Read options from GetPot input file.
virtual void init_variables (libMesh::FEMSystem *system)
Initialization AxisymmetricHeatTransfer variables.
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Sets velocity variables to be time-evolving.
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for element interiors.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiPointer< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_bcs (libMesh::FEMSystem *system)
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
void attach_neumann_bound_func (GRINS::NBCContainer &neumann_bcs)
void attach_dirichlet_bound_func (const GRINS::DBCContainer &dirichlet_bc)
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
BCHandlingBase * get_bc_handler ()
ICHandlingBase * get_ic_handler ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
Protected Attributes
unsigned int _dim
Physical dimension of problem.
VariableIndex _T_var
Index for temperature field.
VariableIndex _u_r_var
Index for r-velocity field.
VariableIndex _u_z_var
Index for z-velocity field.
std::string _T_var_name
Name for temperature variable.
std::string _u_r_var_name
Name of r-velocity.
std::string _u_z_var_name
Name of z-velocity.
GRINSEnums::FEFamily _T_FE_family
Element type, read from input.
GRINSEnums::FEFamily _V_FE_family
GRINSEnums::Order _T_order
Temperature element order, read from input.
GRINSEnums::Order _V_order
libMesh::Number _rho
Material parameters, read from input.
libMesh::Number _Cp
Conductivity _k
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::BCHandlingBase * _bc_handler
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
bool _is_axisymmetric
Static Protected Attributes
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
Private Member Functions
AxisymmetricHeatTransfer ()
Detailed Description
template<class Conductivity>
class GRINS::AxisymmetricHeatTransfer< Conductivity >
Physics class for Axisymmetric Heat Transfer.
Definition at line 46 of file axisym_heat_transfer.h.
Constructor & Destructor Documentation
template<class Conductivity > GRINS::AxisymmetricHeatTransfer< Conductivity >::AxisymmetricHeatTransfer (const std::string & physics_name, const GetPot & input)
Definition at line 47 of file axisym_heat_transfer.C.
References GRINS::Physics::_bc_handler, GRINS::Physics::_ic_handler, and GRINS::AxisymmetricHeatTransfer< Conductivity >::read_input_options().
     : Physics(physics_name, input),
       _k(input)
   {
     this->read_input_options(input);
     // This is deleted in the base class
     this->_bc_handler = new AxisymmetricHeatTransferBCHandling( physics_name, input );
     this->_ic_handler = new GenericICHandler( physics_name, input );
     return;
   }
template<class Conductivity > GRINS::AxisymmetricHeatTransfer< Conductivity >::~AxisymmetricHeatTransfer ()
Definition at line 62 of file axisym_heat_transfer.C.
   {
     return;
   }
template<class Conductivity > GRINS::AxisymmetricHeatTransfer< Conductivity >::AxisymmetricHeatTransfer () private
Member Function Documentation
void GRINS::Physics::attach_dirichlet_bound_func (const GRINS::DBCContainer & dirichlet_bc) inherited
Definition at line 150 of file physics.C.
References GRINS::Physics::_bc_handler, and GRINS::BCHandlingBase::attach_dirichlet_bound_func().
   {
     _bc_handler->attach_dirichlet_bound_func( dirichlet_bc );
     return;
   }
void GRINS::Physics::attach_neumann_bound_func (GRINS::NBCContainer & neumann_bcs) inherited
Definition at line 144 of file physics.C.
References GRINS::Physics::_bc_handler, and GRINS::BCHandlingBase::attach_neumann_bound_func().
   {
     _bc_handler->attach_neumann_bound_func( neumann_bcs );
     return;
   }
void GRINS::Physics::auxiliary_init (MultiphysicsSystem & system) virtual inherited
Any auxillary initialization a Physics class may need.
This is called after all variables are added, so this method can safely query the MultiphysicsSystem about variable information.
Definition at line 113 of file physics.C.
   {
     return;
   }
void GRINS::Physics::compute_element_constraint_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 185 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::element_constraint().
   {
     return;
   }
void GRINS::Physics::compute_element_time_derivative_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Reimplemented in GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >.
Definition at line 167 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::element_time_derivative().
   {
     return;
   }
void GRINS::Physics::compute_mass_residual_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 203 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::mass_residual().
   {
     return;
   }
void GRINS::Physics::compute_nonlocal_constraint_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 197 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_constraint().
   {
     return;
   }
void GRINS::Physics::compute_nonlocal_mass_residual_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 209 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_mass_residual().
   {
     return;
   }
void GRINS::Physics::compute_nonlocal_time_derivative_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 179 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_time_derivative().
   {
     return;
   }
void GRINS::Physics::compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext & context, const libMesh::Point & point, libMesh::Real & value) virtual inherited
Reimplemented in GRINS::IncompressibleNavierStokes< Viscosity >, GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >, GRINS::HeatTransfer< Conductivity >, GRINS::ParsedVelocitySource< Viscosity >, GRINS::VelocityPenalty< Viscosity >, GRINS::ElasticMembrane< StressStrainLaw >, and GRINS::ElasticCable< StressStrainLaw >.
Definition at line 271 of file physics.C.
   {
     return;
   }
void GRINS::Physics::compute_side_constraint_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Definition at line 191 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::side_constraint().
   {
     return;
   }
void GRINS::Physics::compute_side_time_derivative_cache (const AssemblyContext & context, CachedValues & cache) virtual inherited
Reimplemented in GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >.
Definition at line 173 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::side_time_derivative().
   {
     return;
   }
void GRINS::Physics::element_constraint (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Constraint part(s) of physics for element interiors.
Reimplemented in GRINS::IncompressibleNavierStokes< Viscosity >, GRINS::AveragedTurbineAdjointStabilization< Viscosity >, GRINS::VelocityDragAdjointStabilization< Viscosity >, GRINS::AveragedFanAdjointStabilization< Viscosity >, GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >, GRINS::ElasticMembrane< StressStrainLaw >, GRINS::Stokes< Viscosity >, GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >, GRINS::ParsedVelocitySourceAdjointStabilization< Viscosity >, GRINS::VelocityPenaltyAdjointStabilization< Viscosity >, GRINS::IncompressibleNavierStokesAdjointStabilization< Viscosity >, and GRINS::IncompressibleNavierStokesSPGSMStabilization< Viscosity >.
Definition at line 236 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::element_constraint().
   {
     return;
   }
template<class Conductivity > void GRINS::AxisymmetricHeatTransfer< Conductivity >::element_time_derivative (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Time dependent part(s) of physics for element interiors.
Reimplemented from GRINS::Physics.
Definition at line 146 of file axisym_heat_transfer.C.
   {
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->BeginTimer("AxisymmetricHeatTransfer::element_time_derivative");
 #endif
     // The number of local degrees of freedom in each variable.
     const unsigned int n_T_dofs = context.get_dof_indices(_T_var).size();
     const unsigned int n_u_dofs = context.get_dof_indices(_u_r_var).size();
     //TODO: check n_T_dofs is same as n_u_dofs, n_v_dofs, n_w_dofs
     // We get some references to cell-specific data that
     // will be used to assemble the linear system.
     // Element Jacobian * quadrature weights for interior integration.
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(_T_var)->get_JxW();
     // The temperature shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& T_phi =
       context.get_element_fe(_T_var)->get_phi();
     // The velocity shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& vel_phi =
       context.get_element_fe(_u_r_var)->get_phi();
     // The temperature shape function gradients (in global coords.)
     // at interior quadrature points.
     const std::vector<std::vector<libMesh::RealGradient> >& T_gradphi =
       context.get_element_fe(_T_var)->get_dphi();
     // Physical location of the quadrature points
     const std::vector<libMesh::Point>& u_qpoint =
       context.get_element_fe(_u_r_var)->get_xyz();
     // The subvectors and submatrices we need to fill:
     libMesh::DenseSubVector<libMesh::Number> &FT = context.get_elem_residual(_T_var); // R_{T}
     libMesh::DenseSubMatrix<libMesh::Number> &KTT = context.get_elem_jacobian(_T_var, _T_var); // R_{T},{T}
     libMesh::DenseSubMatrix<libMesh::Number> &KTr = context.get_elem_jacobian(_T_var, _u_r_var); // R_{T},{r}
     libMesh::DenseSubMatrix<libMesh::Number> &KTz = context.get_elem_jacobian(_T_var, _u_z_var); // R_{T},{z}
     // Now we will build the element Jacobian and residual.
     // Constructing the residual requires the solution and its
     // gradient from the previous timestep.  This must be
     // calculated at each quadrature point by summing the
     // solution degree-of-freedom values by the appropriate
     // weight functions.
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     for (unsigned int qp=0; qp != n_qpoints; qp++)
       {
         const libMesh::Number r = u_qpoint[qp](0);
         // Compute the solution & its gradient at the old Newton iterate.
         libMesh::Number u_r, u_z;
         u_r = context.interior_value(_u_r_var, qp);
         u_z = context.interior_value(_u_z_var, qp);
         libMesh::Gradient grad_T;
         grad_T = context.interior_gradient(_T_var, qp);
         libMesh::NumberVectorValue U (u_r,u_z);
         libMesh::Number k = this->_k( context, qp );
         // FIXME - once we have T-dependent k, we'll need its
         // derivatives in Jacobians
         // libMesh::Number dk_dT = this->_k.deriv( T );
         // First, an i-loop over the  degrees of freedom.
         for (unsigned int i=0; i != n_T_dofs; i++)
           {
             FT(i) += JxW[qp]*r*
               (-_rho*_Cp*T_phi[i][qp]*(U*grad_T)    // convection term
                -k*(T_gradphi[i][qp]*grad_T) );  // diffusion term
             if (compute_jacobian)
               {
                 libmesh_assert (context.get_elem_solution_derivative() == 1.0);
                 for (unsigned int j=0; j != n_T_dofs; j++)
                   {
                     // TODO: precompute some terms like:
                     //   _rho*_Cp*T_phi[i][qp]*(vel_phi[j][qp]*T_grad_phi[j][qp])
                     KTT(i,j) += JxW[qp] * context.get_elem_solution_derivative() *r*
                       (-_rho*_Cp*T_phi[i][qp]*(U*T_gradphi[j][qp])  // convection term
                        -k*(T_gradphi[i][qp]*T_gradphi[j][qp])); // diffusion term
                   } // end of the inner dof (j) loop
 #if 0
                 if( dk_dT != 0.0 )
                 {
                   for (unsigned int j=0; j != n_T_dofs; j++)
                     {
                       // TODO: precompute some terms like:
                       KTT(i,j) -= JxW[qp] * context.get_elem_solution_derivative() *r*( dk_dT*T_phi[j][qp]*T_gradphi[i][qp]*grad_T );
                     }
                 }
 #endif
                 // Matrix contributions for the Tu, Tv and Tw couplings (n_T_dofs same as n_u_dofs, n_v_dofs and n_w_dofs)
                 for (unsigned int j=0; j != n_u_dofs; j++)
                   {
                     KTr(i,j) += JxW[qp] * context.get_elem_solution_derivative() *r*(-_rho*_Cp*T_phi[i][qp]*(vel_phi[j][qp]*grad_T(0)));
                     KTz(i,j) += JxW[qp] * context.get_elem_solution_derivative() *r*(-_rho*_Cp*T_phi[i][qp]*(vel_phi[j][qp]*grad_T(1)));
                   } // end of the inner dof (j) loop
               } // end - if (compute_jacobian && context.get_elem_solution_derivative())
           } // end of the outer dof (i) loop
       } // end of the quadrature point (qp) loop
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->EndTimer("AxisymmetricHeatTransfer::element_time_derivative");
 #endif
     return;
   }
bool GRINS::Physics::enabled_on_elem (const libMesh::Elem * elem) virtual inherited
Find if current physics is active on supplied element.
Definition at line 83 of file physics.C.
References GRINS::Physics::_enabled_subdomains.
   {
     // Check if enabled_subdomains flag has been set and if we're
     // looking at a real element (rather than a nonlocal evaluation)
     if( !elem || _enabled_subdomains.empty() )
       return true;
     // Check if current physics is enabled on elem
     if( _enabled_subdomains.find( elem->subdomain_id() ) == _enabled_subdomains.end() )
       return false;
     return true;
   }
BCHandlingBase * GRINS::Physics::get_bc_handler () inline inherited
Definition at line 282 of file physics.h.
References GRINS::Physics::_bc_handler.
   {
     return _bc_handler;
   }
ICHandlingBase * GRINS::Physics::get_ic_handler () inline inherited
Definition at line 288 of file physics.h.
References GRINS::Physics::_ic_handler.
   {
     return _ic_handler;
   }
void GRINS::Physics::init_bcs (libMesh::FEMSystem * system) inherited
Definition at line 118 of file physics.C.
References GRINS::Physics::_bc_handler, GRINS::BCHandlingBase::init_bc_data(), GRINS::BCHandlingBase::init_dirichlet_bc_func_objs(), GRINS::BCHandlingBase::init_dirichlet_bcs(), and GRINS::BCHandlingBase::init_periodic_bcs().
   {
     // Only need to init BC's if the physics actually created a handler
     if( _bc_handler )
       {
         _bc_handler->init_bc_data( *system );
         _bc_handler->init_dirichlet_bcs( system );
         _bc_handler->init_dirichlet_bc_func_objs( system );
         _bc_handler->init_periodic_bcs( system );
       }
     return;
   }
template<class Conductivity > void GRINS::AxisymmetricHeatTransfer< Conductivity >::init_context (AssemblyContext & context) virtual
Initialize context for added physics variables.
Reimplemented from GRINS::Physics.
Definition at line 124 of file axisym_heat_transfer.C.
   {
     // We should prerequest all the data
     // we will need to build the linear system
     // or evaluate a quantity of interest.
     context.get_element_fe(_T_var)->get_JxW();
     context.get_element_fe(_T_var)->get_phi();
     context.get_element_fe(_T_var)->get_dphi();
     context.get_element_fe(_T_var)->get_xyz();
     context.get_side_fe(_T_var)->get_JxW();
     context.get_side_fe(_T_var)->get_phi();
     context.get_side_fe(_T_var)->get_dphi();
     context.get_side_fe(_T_var)->get_xyz();
     // _u_var is registered so can we assume things related to _u_var
     // are available in FEMContext
     return;
   }
void GRINS::Physics::init_ics (libMesh::FEMSystem * system, libMesh::CompositeFunction< libMesh::Number > & all_ics) inherited
Definition at line 133 of file physics.C.
References GRINS::Physics::_ic_handler, and GRINS::ICHandlingBase::init_ic_data().
   {
     if( _ic_handler )
       {
         _ic_handler->init_ic_data( *system, all_ics );
       }
     return;
   }
template<class Conductivity > void GRINS::AxisymmetricHeatTransfer< Conductivity >::init_variables (libMesh::FEMSystem * system) virtual
Initialization AxisymmetricHeatTransfer variables.
Add velocity and pressure variables to system.
Implements GRINS::Physics.
Definition at line 101 of file axisym_heat_transfer.C.
   {
     // Get libMesh to assign an index for each variable
     this->_dim = system->get_mesh().mesh_dimension();
     _T_var = system->add_variable( _T_var_name, _T_order, _T_FE_family);
     // If these are already added, then we just get the index.
     _u_r_var = system->add_variable(_u_r_var_name, _V_order, _V_FE_family);
     _u_z_var = system->add_variable(_u_z_var_name, _V_order, _V_FE_family);
     return;
   }
bool GRINS::Physics::is_steady () const inherited
Returns whether or not this physics is being solved with a steady solver.
Definition at line 103 of file physics.C.
References GRINS::Physics::_is_steady.
Referenced by GRINS::Physics::set_is_steady().
   {
     return _is_steady;
   }
template<class Conductivity > void GRINS::AxisymmetricHeatTransfer< Conductivity >::mass_residual (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
Reimplemented from GRINS::Physics.
Definition at line 299 of file axisym_heat_transfer.C.
   {
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->BeginTimer("AxisymmetricHeatTransfer::mass_residual");
 #endif
     // First we get some references to cell-specific data that
     // will be used to assemble the linear system.
     // Element Jacobian * quadrature weights for interior integration
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(_T_var)->get_JxW();
     // The shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& phi =
       context.get_element_fe(_T_var)->get_phi();
     // The number of local degrees of freedom in each variable
     const unsigned int n_T_dofs = context.get_dof_indices(_T_var).size();
     // Physical location of the quadrature points
     const std::vector<libMesh::Point>& u_qpoint =
       context.get_element_fe(_u_r_var)->get_xyz();
     // The subvectors and submatrices we need to fill:
     libMesh::DenseSubVector<libMesh::Real> &F =
       context.get_elem_residual(_T_var);
     libMesh::DenseSubMatrix<libMesh::Real> &M =
       context.get_elem_jacobian(_T_var, _T_var);
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     for (unsigned int qp = 0; qp != n_qpoints; ++qp)
       {
         const libMesh::Number r = u_qpoint[qp](0);
         // For the mass residual, we need to be a little careful.
         // The time integrator is handling the time-discretization
         // for us so we need to supply M(u_fixed)*u' for the residual.
         // u_fixed will be given by the fixed_interior_value function
         // while u' will be given by the interior_rate function.
         libMesh::Real T_dot;
         context.interior_rate(_T_var, qp, T_dot);
         for (unsigned int i = 0; i != n_T_dofs; ++i)
           {
             F(i) -= JxW[qp]*r*(_rho*_Cp*T_dot*phi[i][qp] );
             if( compute_jacobian )
               {
                 for (unsigned int j=0; j != n_T_dofs; j++)
                   {
                     // We're assuming rho, cp are constant w.r.t. T here.
                     M(i,j) -= JxW[qp] * context.get_elem_solution_rate_derivative() *r*_rho*_Cp*phi[j][qp]*phi[i][qp] ;
                   }
               }// End of check on Jacobian
           } // End of element dof loop
       } // End of the quadrature point loop
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->EndTimer("AxisymmetricHeatTransfer::mass_residual");
 #endif
     return;
   }
void GRINS::Physics::nonlocal_constraint (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Constraint part(s) of physics for scalar variables.
Reimplemented in GRINS::ScalarODE.
Definition at line 250 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_constraint().
   {
     return;
   }
void GRINS::Physics::nonlocal_mass_residual (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Mass matrix part(s) for scalar variables.
Reimplemented in GRINS::ScalarODE, and GRINS::AveragedTurbine< Viscosity >.
Definition at line 264 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_mass_residual().
   {
     return;
   }
void GRINS::Physics::nonlocal_time_derivative (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Time dependent part(s) of physics for scalar variables.
Reimplemented in GRINS::AveragedTurbine< Viscosity >, and GRINS::ScalarODE.
Definition at line 229 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::nonlocal_time_derivative().
   {
     return;
   }
template<class Conductivity > void GRINS::AxisymmetricHeatTransfer< Conductivity >::read_input_options (const GetPot & input) virtual
Read options from GetPot input file.
Reimplemented from GRINS::Physics.
Definition at line 68 of file axisym_heat_transfer.C.
References GRINS::axisymmetric_heat_transfer, GRINS::incompressible_navier_stokes, GRINS::T_var_name_default, GRINS::u_r_var_name_default, and GRINS::u_z_var_name_default.
Referenced by GRINS::AxisymmetricHeatTransfer< Conductivity >::AxisymmetricHeatTransfer().
   {
     this->_T_FE_family =
       libMesh::Utility::string_to_enum<GRINSEnums::FEFamily>( input("Physics/"+axisymmetric_heat_transfer+"/FE_family", "LAGRANGE") );
     this->_T_order =
       libMesh::Utility::string_to_enum<GRINSEnums::Order>( input("Physics/"+axisymmetric_heat_transfer+"/T_order", "SECOND") );
     this->_V_FE_family =
       libMesh::Utility::string_to_enum<GRINSEnums::FEFamily>( input("Physics/"+incompressible_navier_stokes+"/FE_family", "LAGRANGE") );
     this->_V_order =
       libMesh::Utility::string_to_enum<GRINSEnums::Order>( input("Physics/"+incompressible_navier_stokes+"/V_order", "SECOND") );
     //TODO: same as Incompressible NS
     this->set_parameter
       (this->_rho, input,
        "Physics/"+axisymmetric_heat_transfer+"/rho", 1.0);
     this->set_parameter
       (this->_Cp, input,
        "Physics/"+axisymmetric_heat_transfer+"/Cp", 1.0);
     this->_T_var_name = input("Physics/VariableNames/Temperature", T_var_name_default );
     // registered/non-owned variable names
     this->_u_r_var_name = input("Physics/VariableNames/r_velocity", u_r_var_name_default );
     this->_u_z_var_name = input("Physics/VariableNames/z_velocity", u_z_var_name_default );
     return;
   }
template<class Conductivity > void GRINS::AxisymmetricHeatTransfer< Conductivity >::register_parameter (const std::string & param_name, libMesh::ParameterMultiPointer< libMesh::Number > & param_pointer) const virtual
Each subclass will register its copy of an independent.
Reimplemented from GRINS::ParameterUser.
Definition at line 372 of file axisym_heat_transfer.C.
References GRINS::ParameterUser::register_parameter().
   {
     ParameterUser::register_parameter(param_name, param_pointer);
     _k.register_parameter(param_name, param_pointer);
   }
void GRINS::Physics::register_postprocessing_vars (const GetPot & input, PostProcessedQuantities< libMesh::Real > & postprocessing) virtual inherited
Register name of postprocessed quantity with PostProcessedQuantities.
Each Physics class will need to cache an unsigned int corresponding to each postprocessed quantity. This will be used in computing the values and putting them in the CachedVariables object.
Reimplemented in GRINS::ParsedVelocitySource< Viscosity >, GRINS::VelocityPenalty< Viscosity >, GRINS::IncompressibleNavierStokes< Viscosity >, GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::HeatTransfer< Conductivity >, GRINS::ElasticCable< StressStrainLaw >, GRINS::ElasticMembrane< StressStrainLaw >, and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >.
Definition at line 161 of file physics.C.
   {
     return;
   }
void GRINS::Physics::set_is_steady (bool is_steady) inherited
Sets whether this physics is to be solved with a steady solver or not.
Since the member variable is static, only needs to be called on a single physics.
Definition at line 97 of file physics.C.
References GRINS::Physics::_is_steady, and GRINS::Physics::is_steady().
   {
     _is_steady = is_steady;
     return;
   }
void GRINS::ParameterUser::set_parameter (libMesh::Number & param_variable, const GetPot & input, const std::string & param_name, libMesh::Number param_default) virtual inherited
Each subclass can simultaneously read a parameter value from.
Definition at line 35 of file parameter_user.C.
References GRINS::ParameterUser::_my_name, and GRINS::ParameterUser::_my_parameters.
Referenced by GRINS::AveragedFanAdjointStabilization< Viscosity >::AveragedFanAdjointStabilization(), GRINS::AveragedTurbineAdjointStabilization< Viscosity >::AveragedTurbineAdjointStabilization(), GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::BoussinesqBuoyancyAdjointStabilization(), GRINS::BoussinesqBuoyancyBase::BoussinesqBuoyancyBase(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::BoussinesqBuoyancySPGSMStabilization(), GRINS::ConstantConductivity::ConstantConductivity(), GRINS::ConstantPrandtlConductivity::ConstantPrandtlConductivity(), GRINS::ConstantSourceFunction::ConstantSourceFunction(), GRINS::ConstantSourceTerm::ConstantSourceTerm(), GRINS::ConstantSpecificHeat::ConstantSpecificHeat(), GRINS::ConstantViscosity::ConstantViscosity(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticCableConstantGravity::ElasticCableConstantGravity(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransferBase< Conductivity >::HeatTransferBase(), GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase(), GRINS::AverageNusseltNumber::init(), GRINS::MooneyRivlin::MooneyRivlin(), GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase(), GRINS::HookesLaw1D::read_input_options(), GRINS::HookesLaw::read_input_options(), GRINS::AxisymmetricBoussinesqBuoyancy::read_input_options(), and GRINS::VelocityDragAdjointStabilization< Viscosity >::VelocityDragAdjointStabilization().
   {
     param_variable = input(param_name, param_default);
     libmesh_assert_msg(!_my_parameters.count(param_name),
       "ERROR: " << _my_name << " double-registered parameter " <<
       param_name);
     _my_parameters[param_name] = &param_variable;
   }
template<class Conductivity > void GRINS::AxisymmetricHeatTransfer< Conductivity >::set_time_evolving_vars (libMesh::FEMSystem * system) virtual
Sets velocity variables to be time-evolving.
Reimplemented from GRINS::Physics.
Definition at line 116 of file axisym_heat_transfer.C.
   {
     // Tell the system to march temperature forward in time
     system->time_evolving(_T_var);
     return;
   }
void GRINS::Physics::side_constraint (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual inherited
Constraint part(s) of physics for boundaries of elements on the domain boundary.
Reimplemented in GRINS::IncompressibleNavierStokes< Viscosity >, GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >, and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >.
Definition at line 243 of file physics.C.
Referenced by GRINS::MultiphysicsSystem::side_constraint().
   {
     return;
   }
template<class Conductivity > void GRINS::AxisymmetricHeatTransfer< Conductivity >::side_time_derivative (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
Reimplemented from GRINS::Physics.
Definition at line 273 of file axisym_heat_transfer.C.
   {
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->BeginTimer("AxisymmetricHeatTransfer::side_time_derivative");
 #endif
     std::vector<BoundaryID> ids = context.side_boundary_ids();
     for( std::vector<BoundaryID>::const_iterator it = ids.begin();
          it != ids.end(); it++ )
       {
         libmesh_assert (*it != libMesh::BoundaryInfo::invalid_id);
         _bc_handler->apply_neumann_bcs( context, cache, compute_jacobian, *it );
       }
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->EndTimer("AxisymmetricHeatTransfer::side_time_derivative");
 #endif
     return;
   }
Member Data Documentation
GRINS::BCHandlingBase* GRINS::Physics::_bc_handler protected inherited
Definition at line 256 of file physics.h.
Referenced by GRINS::Physics::attach_dirichlet_bound_func(), GRINS::Physics::attach_neumann_bound_func(), GRINS::AxisymmetricHeatTransfer< Conductivity >::AxisymmetricHeatTransfer(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::Physics::get_bc_handler(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransfer< Conductivity >::HeatTransfer(), GRINS::IncompressibleNavierStokes< Viscosity >::IncompressibleNavierStokes(), GRINS::Physics::init_bcs(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokes(), GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::ReactingLowMachNavierStokes(), GRINS::SpalartAllmaras< Viscosity >::SpalartAllmaras(), GRINS::Stokes< Viscosity >::Stokes(), and GRINS::Physics::~Physics().
template<class Conductivity > libMesh::Number GRINS::AxisymmetricHeatTransfer< Conductivity >::_Cp protected
Definition at line 130 of file axisym_heat_transfer.h.
template<class Conductivity > unsigned int GRINS::AxisymmetricHeatTransfer< Conductivity >::_dim protected
Physical dimension of problem.
Todo:
Make this static member of base class?
Definition at line 97 of file axisym_heat_transfer.h.
std::set<libMesh::subdomain_id_type> GRINS::Physics::_enabled_subdomains protected inherited
Subdomains on which the current Physics class is enabled.
Definition at line 261 of file physics.h.
Referenced by GRINS::Physics::enabled_on_elem(), and GRINS::Physics::read_input_options().
GRINS::ICHandlingBase* GRINS::Physics::_ic_handler protected inherited
Definition at line 258 of file physics.h.
Referenced by GRINS::AveragedTurbine< Viscosity >::AveragedTurbine(), GRINS::AxisymmetricHeatTransfer< Conductivity >::AxisymmetricHeatTransfer(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::Physics::get_ic_handler(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransfer< Conductivity >::HeatTransfer(), GRINS::IncompressibleNavierStokes< Viscosity >::IncompressibleNavierStokes(), GRINS::Physics::init_ics(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokes(), GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::ReactingLowMachNavierStokes(), GRINS::ScalarODE::ScalarODE(), GRINS::SpalartAllmaras< Viscosity >::SpalartAllmaras(), GRINS::Stokes< Viscosity >::Stokes(), and GRINS::Physics::~Physics().
bool GRINS::Physics::_is_axisymmetric protected inherited
Definition at line 268 of file physics.h.
Referenced by GRINS::HeatTransfer< Conductivity >::HeatTransfer(), GRINS::IncompressibleNavierStokes< Viscosity >::IncompressibleNavierStokes(), GRINS::Physics::Physics(), and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::ReactingLowMachNavierStokes().
bool GRINS::Physics::_is_steady = false static protected inherited
Caches whether or not the solver that's being used is steady or not.
This is need, for example, in flow stabilization as the tau terms change depending on whether the solver is steady or unsteady.
Definition at line 266 of file physics.h.
Referenced by GRINS::Physics::is_steady(), and GRINS::Physics::set_is_steady().
template<class Conductivity > Conductivity GRINS::AxisymmetricHeatTransfer< Conductivity >::_k protected
Definition at line 132 of file axisym_heat_transfer.h.
const PhysicsName GRINS::Physics::_physics_name protected inherited
Name of the physics object. Used for reading physics specific inputs.
We use a reference because the physics names are const global objects in GRINS namespace
No, we use a copy, because otherwise as soon as the memory in std::set<std::string> requested_physics gets overwritten we get in trouble.
Definition at line 254 of file physics.h.
Referenced by GRINS::SourceTermBase::parse_var_info(), and GRINS::Physics::read_input_options().
template<class Conductivity > libMesh::Number GRINS::AxisymmetricHeatTransfer< Conductivity >::_rho protected
Material parameters, read from input.
Todo:
Need to generalize material parameters. Right now they are assumed constant
Todo:
Shouldn't this rho be the same as the one in the flow? Need to figure out how to have those shared
Definition at line 130 of file axisym_heat_transfer.h.
template<class Conductivity > GRINSEnums::FEFamily GRINS::AxisymmetricHeatTransfer< Conductivity >::_T_FE_family protected
Element type, read from input.
Definition at line 120 of file axisym_heat_transfer.h.
template<class Conductivity > GRINSEnums::Order GRINS::AxisymmetricHeatTransfer< Conductivity >::_T_order protected
Temperature element order, read from input.
Definition at line 123 of file axisym_heat_transfer.h.
template<class Conductivity > VariableIndex GRINS::AxisymmetricHeatTransfer< Conductivity >::_T_var protected
Index for temperature field.
Definition at line 101 of file axisym_heat_transfer.h.
template<class Conductivity > std::string GRINS::AxisymmetricHeatTransfer< Conductivity >::_T_var_name protected
Name for temperature variable.
Definition at line 111 of file axisym_heat_transfer.h.
template<class Conductivity > VariableIndex GRINS::AxisymmetricHeatTransfer< Conductivity >::_u_r_var protected
Index for r-velocity field.
Definition at line 104 of file axisym_heat_transfer.h.
template<class Conductivity > std::string GRINS::AxisymmetricHeatTransfer< Conductivity >::_u_r_var_name protected
Name of r-velocity.
Definition at line 114 of file axisym_heat_transfer.h.
template<class Conductivity > VariableIndex GRINS::AxisymmetricHeatTransfer< Conductivity >::_u_z_var protected
Index for z-velocity field.
Definition at line 107 of file axisym_heat_transfer.h.
template<class Conductivity > std::string GRINS::AxisymmetricHeatTransfer< Conductivity >::_u_z_var_name protected
Name of z-velocity.
Definition at line 117 of file axisym_heat_transfer.h.
template<class Conductivity > GRINSEnums::FEFamily GRINS::AxisymmetricHeatTransfer< Conductivity >::_V_FE_family protected
Definition at line 120 of file axisym_heat_transfer.h.
template<class Conductivity > GRINSEnums::Order GRINS::AxisymmetricHeatTransfer< Conductivity >::_V_order protected
Definition at line 123 of file axisym_heat_transfer.h.
The documentation for this class was generated from the following files:
src/physics/include/grins/axisym_heat_transfer.h
src/physics/src/axisym_heat_transfer.C