GRINS-0.7.0: GRINSTesting::NASA9ThermoTestBase Class Reference
GRINSTesting::NASA9ThermoTestBase Class Reference
#include <nasa_thermo_test_base.h>
Public Member Functions
NASA9ThermoTestBase ()
virtual libMesh::Real cp_exact (unsigned int species_idx, libMesh::Real T)
virtual libMesh::Real h_exact (unsigned int species_idx, libMesh::Real T)
virtual libMesh::Real s_R_exact (unsigned int species_idx, libMesh::Real T)
virtual libMesh::Real h_RT_exact (unsigned int species_idx, libMesh::Real T)
Public Member Functions inherited from GRINSTesting::NASAThermoTestBase
template<typename ThermoMixture , typename ThermoEvaluator >
void test_cp_common (ThermoMixture &mixture, const std::vector< libMesh::Real > &Y, libMesh::Real rel_tol)
template<typename ThermoMixture , typename ThermoEvaluator >
void test_h_common (ThermoMixture &mixture, libMesh::Real rel_tol)
Public Member Functions inherited from GRINSTesting::SpeciesTestBase
SpeciesTestBase ()
libMesh::Real molar_mass (unsigned int idx)
libMesh::Real R_species (unsigned int idx)
Private Member Functions
void init_N2_coeffs ()
void init_O2_coeffs ()
void init_O_coeffs ()
void init_NO_coeffs ()
void init_N_coeffs ()
Additional Inherited Members
Protected Member Functions inherited from GRINSTesting::NASAThermoTestBase
const std::vector< libMesh::Real > & nasa_coeffs (unsigned int idx)
Protected Attributes inherited from GRINSTesting::NASAThermoTestBase
std::vector< libMesh::Real > _N2_200_1000_coeffs
std::vector< libMesh::Real > _O2_200_1000_coeffs
std::vector< libMesh::Real > _O_200_1000_coeffs
std::vector< libMesh::Real > _NO_200_1000_coeffs
std::vector< libMesh::Real > _N_200_1000_coeffs
Protected Attributes inherited from GRINSTesting::SpeciesTestBase
unsigned int _N2_idx
unsigned int _O2_idx
unsigned int _O_idx
unsigned int _N_idx
unsigned int _NO_idx
std::vector< unsigned int > _active_species
Detailed Description
Definition at line 282 of file nasa_thermo_test_base.h.
Constructor & Destructor Documentation
GRINSTesting::NASA9ThermoTestBase::NASA9ThermoTestBase () inline
Definition at line 286 of file nasa_thermo_test_base.h.
References init_N2_coeffs(), init_N_coeffs(), init_NO_coeffs(), init_O2_coeffs(), and init_O_coeffs().
     {
       this->init_N2_coeffs();
       this->init_O2_coeffs();
       this->init_O_coeffs();
       this->init_NO_coeffs();
       this->init_N_coeffs();
     }
Member Function Documentation
virtual libMesh::Real GRINSTesting::NASA9ThermoTestBase::cp_exact (unsigned int species_idx, libMesh::Real T) inline virtual
Implements GRINSTesting::NASAThermoTestBase.
Definition at line 295 of file nasa_thermo_test_base.h.
References GRINSTesting::ThermochemTestCommon::nasa9_cp_R_exact(), GRINSTesting::NASAThermoTestBase::nasa_coeffs(), and GRINSTesting::SpeciesTestBase::R_species().
     {
       const std::vector<libMesh::Real> coeffs = this->nasa_coeffs(species_idx);
       return ThermochemTestCommon::nasa9_cp_R_exact(T,
                                                     coeffs[0],
                                                     coeffs[1],
                                                     coeffs[2],
                                                     coeffs[3],
                                                     coeffs[4],
                                                     coeffs[5],
                                                     coeffs[6])*this->R_species(species_idx);
     }
virtual libMesh::Real GRINSTesting::NASA9ThermoTestBase::h_exact (unsigned int species_idx, libMesh::Real T) inline virtual
Implements GRINSTesting::NASAThermoTestBase.
Definition at line 308 of file nasa_thermo_test_base.h.
References GRINSTesting::ThermochemTestCommon::nasa9_h_RT_exact(), GRINSTesting::NASAThermoTestBase::nasa_coeffs(), and GRINSTesting::SpeciesTestBase::R_species().
     {
       const std::vector<libMesh::Real> coeffs = this->nasa_coeffs(species_idx);
       return ThermochemTestCommon::nasa9_h_RT_exact(T,
                                                     coeffs[0],
                                                     coeffs[1],
                                                     coeffs[2],
                                                     coeffs[3],
                                                     coeffs[4],
                                                     coeffs[5],
                                                     coeffs[6],
                                                     coeffs[7])*this->R_species(species_idx)*T;
     }
virtual libMesh::Real GRINSTesting::NASA9ThermoTestBase::h_RT_exact (unsigned int species_idx, libMesh::Real T) inline virtual
Implements GRINSTesting::NASAThermoTestBase.
Definition at line 336 of file nasa_thermo_test_base.h.
References GRINSTesting::ThermochemTestCommon::nasa9_h_RT_exact(), and GRINSTesting::NASAThermoTestBase::nasa_coeffs().
     {
       const std::vector<libMesh::Real> coeffs = this->nasa_coeffs(species_idx);
       return ThermochemTestCommon::nasa9_h_RT_exact(T,
                                                     coeffs[0],
                                                     coeffs[1],
                                                     coeffs[2],
                                                     coeffs[3],
                                                     coeffs[4],
                                                     coeffs[5],
                                                     coeffs[6],
                                                     coeffs[7]);
     }
void GRINSTesting::NASA9ThermoTestBase::init_N2_coeffs () inline private
Definition at line 352 of file nasa_thermo_test_base.h.
References GRINSTesting::NASAThermoTestBase::_N2_200_1000_coeffs.
Referenced by NASA9ThermoTestBase().
     {
       _N2_200_1000_coeffs.resize(9);
       _N2_200_1000_coeffs[0] =  2.21037122e+04;
       _N2_200_1000_coeffs[1] = -3.81846145e+02;
       _N2_200_1000_coeffs[2] =  6.08273815e+00;
       _N2_200_1000_coeffs[3] = -8.53091381e-03;
       _N2_200_1000_coeffs[4] =  1.38464610e-05;
       _N2_200_1000_coeffs[5] = -9.62579293e-09;
       _N2_200_1000_coeffs[6] =  2.51970560e-12;
       _N2_200_1000_coeffs[7] =  7.10845911e+02;
       _N2_200_1000_coeffs[8] = -1.07600320e+01;
     }
void GRINSTesting::NASA9ThermoTestBase::init_N_coeffs () inline private
Definition at line 412 of file nasa_thermo_test_base.h.
References GRINSTesting::NASAThermoTestBase::_N_200_1000_coeffs.
Referenced by NASA9ThermoTestBase().
     {
       _N_200_1000_coeffs.resize(9);
       _N_200_1000_coeffs[0] =  0.0;
       _N_200_1000_coeffs[1] =  0.0;
       _N_200_1000_coeffs[2] =  2.5;
       _N_200_1000_coeffs[3] =  0.0;
       _N_200_1000_coeffs[4] =  0.0;
       _N_200_1000_coeffs[5] =  0.0;
       _N_200_1000_coeffs[6] =  0.0;
       _N_200_1000_coeffs[7] =  5.61046378e+04;
       _N_200_1000_coeffs[8] =  4.19390932e+00;
     }
void GRINSTesting::NASA9ThermoTestBase::init_NO_coeffs () inline private
Definition at line 397 of file nasa_thermo_test_base.h.
References GRINSTesting::NASAThermoTestBase::_NO_200_1000_coeffs.
Referenced by NASA9ThermoTestBase().
     {
       _NO_200_1000_coeffs.resize(9);
       _NO_200_1000_coeffs[0] = -1.14391658e+04;
       _NO_200_1000_coeffs[1] =  1.53646774e+02;
       _NO_200_1000_coeffs[2] =  3.43146865e+00;
       _NO_200_1000_coeffs[3] = -2.66859213e-03;
       _NO_200_1000_coeffs[4] =  8.48139877e-06;
       _NO_200_1000_coeffs[5] = -7.68511079e-09;
       _NO_200_1000_coeffs[6] =  2.38679758e-12;
       _NO_200_1000_coeffs[7] =  9.09794974e+03;
       _NO_200_1000_coeffs[8] =  6.72872795e+00;
     }
void GRINSTesting::NASA9ThermoTestBase::init_O2_coeffs () inline private
Definition at line 367 of file nasa_thermo_test_base.h.
References GRINSTesting::NASAThermoTestBase::_O2_200_1000_coeffs.
Referenced by NASA9ThermoTestBase().
     {
       _O2_200_1000_coeffs.resize(9);
       _O2_200_1000_coeffs[0] = -3.42556269e+04;
       _O2_200_1000_coeffs[1] =  4.84699986e+02;
       _O2_200_1000_coeffs[2] =  1.11901159e+00;
       _O2_200_1000_coeffs[3] =  4.29388743e-03;
       _O2_200_1000_coeffs[4] = -6.83627313e-07;
       _O2_200_1000_coeffs[5] = -2.02337478e-09;
       _O2_200_1000_coeffs[6] =  1.03904064e-12;
       _O2_200_1000_coeffs[7] = -3.39145434e+03;
       _O2_200_1000_coeffs[8] =  1.84969912e+01;
     }
void GRINSTesting::NASA9ThermoTestBase::init_O_coeffs () inline private
Definition at line 382 of file nasa_thermo_test_base.h.
References GRINSTesting::NASAThermoTestBase::_O_200_1000_coeffs.
Referenced by NASA9ThermoTestBase().
     {
       _O_200_1000_coeffs.resize(9);
       _O_200_1000_coeffs[0] = -7.95361130e+03;
       _O_200_1000_coeffs[1] =  1.60717779e+02;
       _O_200_1000_coeffs[2] =  1.96622644e+00;
       _O_200_1000_coeffs[3] =  1.01367031e-03;
       _O_200_1000_coeffs[4] = -1.11041542e-06;
       _O_200_1000_coeffs[5] =  6.51750750e-10;
       _O_200_1000_coeffs[6] = -1.58477925e-13;
       _O_200_1000_coeffs[7] =  2.84036244e+04;
       _O_200_1000_coeffs[8] =  8.40424182e+00;
     }
virtual libMesh::Real GRINSTesting::NASA9ThermoTestBase::s_R_exact (unsigned int species_idx, libMesh::Real T) inline virtual
Implements GRINSTesting::NASAThermoTestBase.
Definition at line 322 of file nasa_thermo_test_base.h.
References GRINSTesting::ThermochemTestCommon::nasa9_s_R_exact(), and GRINSTesting::NASAThermoTestBase::nasa_coeffs().
     {
       const std::vector<libMesh::Real> coeffs = this->nasa_coeffs(species_idx);
       return ThermochemTestCommon::nasa9_s_R_exact(T,
                                                    coeffs[0],
                                                    coeffs[1],
                                                    coeffs[2],
                                                    coeffs[3],
                                                    coeffs[4],
                                                    coeffs[5],
                                                    coeffs[6],
                                                    coeffs[8]);
     }
The documentation for this class was generated from the following file:
test/interface/nasa_thermo_test_base.h