GRINS-0.6.0: GRINS::Vorticity Class Reference
GRINS::Vorticity Class Reference
Vorticity QoI.
#include <vorticity.h>
Public Member Functions
Vorticity (const std::string &qoi_name)
Constructor.
virtual ~Vorticity ()
virtual QoIBase * clone () const
Required to provide clone (deep-copy) for adding QoI object to libMesh objects.
virtual bool assemble_on_interior () const
Does the QoI need an element interior assembly loop?
virtual bool assemble_on_sides () const
Does the QoI need a domain boundary assembly loop?
virtual void init (const GetPot &input, const MultiphysicsSystem &system)
Initialize local variables.
virtual void init_context (AssemblyContext &context)
virtual void element_qoi (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi value.
virtual void element_qoi_derivative (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi derivative with respect to the solution.
virtual void side_qoi (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi value on the domain boundary.
virtual void side_qoi_derivative (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi derivative with respect to the solution on the domain boundary.
virtual void parallel_op (const libMesh::Parallel::Communicator &communicator, libMesh::Number &sys_qoi, libMesh::Number &local_qoi)
Call the parallel operation for this QoI and cache the value.
virtual void thread_join (libMesh::Number &qoi, const libMesh::Number &other_qoi)
Call the operation to accumulate this QoI from multiple threads.
virtual void output_qoi (std::ostream &out) const
Basic output for computed QoI's.
libMesh::Number value () const
Returns the current QoI value.
const std::string & name () const
Returns the name of this QoI.
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiPointer< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Attributes
VariableIndex _u_var
u-velocity component variable index
VariableIndex _v_var
v-velocity component variable index
std::set< libMesh::subdomain_id_type > _subdomain_ids
List of sumdomain ids for which we want to compute this QoI.
std::string _qoi_name
libMesh::Number _qoi_value
Private Member Functions
Vorticity ()
User never call default constructor.
Detailed Description
Vorticity QoI.
This class implement a vorticity QoI that can be used to both compute QoI values and drive QoI-based adaptive refinement. Currently, this QoI is only implemented in 2D and will error if it detects a three-dimensional problem.
Definition at line 42 of file vorticity.h.
Constructor & Destructor Documentation
GRINS::Vorticity::Vorticity (const std::string & qoi_name)
Constructor.
Constructor takes GetPot object to read any input options associated with this QoI
Definition at line 41 of file vorticity.C.
     : QoIBase(qoi_name)
   {
     return;
   }
GRINS::Vorticity::~Vorticity () virtual
Definition at line 47 of file vorticity.C.
   {
     return;
   }
GRINS::Vorticity::Vorticity () private
User never call default constructor.
Referenced by clone().
Member Function Documentation
bool GRINS::Vorticity::assemble_on_interior () const inline virtual
Does the QoI need an element interior assembly loop?
This is pure virtual to force to user to specify.
Implements GRINS::QoIBase.
Definition at line 98 of file vorticity.h.
   {
     return true;
   }
bool GRINS::Vorticity::assemble_on_sides () const inline virtual
Does the QoI need a domain boundary assembly loop?
This is pure virtual to force to user to specify.
Implements GRINS::QoIBase.
Definition at line 104 of file vorticity.h.
   {
     return false;
   }
QoIBase * GRINS::Vorticity::clone () const virtual
Required to provide clone (deep-copy) for adding QoI object to libMesh objects.
Implements GRINS::QoIBase.
Definition at line 52 of file vorticity.C.
References Vorticity().
   {
     return new Vorticity( *this );
   }
void GRINS::Vorticity::element_qoi (AssemblyContext & context, const unsigned int qoi_index) virtual
Compute the qoi value.
Currently, only implemented for 2D. Assumes that the vorticity will be computed over area of input subdomain id. Vorticity computed as
Todo:
Need to generalize this to the multiple QoI case
Reimplemented from GRINS::QoIBase.
Definition at line 99 of file vorticity.C.
References _subdomain_ids, _u_var, and _v_var.
   {
     if( _subdomain_ids.find( (&context.get_elem())->subdomain_id() ) != _subdomain_ids.end() )
       {
         libMesh::FEBase* element_fe;
         context.get_element_fe<libMesh::Real>(this->_u_var, element_fe);
         const std::vector<libMesh::Real> &JxW = element_fe->get_JxW();
         unsigned int n_qpoints = context.get_element_qrule().n_points();
         libMesh::Number& qoi = context.get_qois()[qoi_index];
         for( unsigned int qp = 0; qp != n_qpoints; qp++ )
           {
             libMesh::Gradient grad_u = 0.;
             libMesh::Gradient grad_v = 0.;
             context.interior_gradient( this->_u_var, qp, grad_u );
             context.interior_gradient( this->_v_var, qp, grad_v );
             qoi += (grad_v(0) - grad_u(1)) * JxW[qp];
           }
       }
     return;
   }
void GRINS::Vorticity::element_qoi_derivative (AssemblyContext & context, const unsigned int qoi_index) virtual
Compute the qoi derivative with respect to the solution.
Currently, only implemented for 2D. Assumes that the vorticity will be computed over area of input subdomain id.
Todo:
Need to generalize this to the multiple QoI case
Reimplemented from GRINS::QoIBase.
Definition at line 127 of file vorticity.C.
References _subdomain_ids, _u_var, and _v_var.
   {
     if( _subdomain_ids.find( (&context.get_elem())->subdomain_id() ) != _subdomain_ids.end() )
       {
         // Element
         libMesh::FEBase* element_fe;
         context.get_element_fe<libMesh::Real>(this->_u_var, element_fe);
         // Jacobian times integration weights
         const std::vector<libMesh::Real> &JxW = element_fe->get_JxW();
         // Grad of basis functions
         const std::vector<std::vector<libMesh::RealGradient> >& du_phi =
           context.get_element_fe(_u_var)->get_dphi();
         const std::vector<std::vector<libMesh::RealGradient> >& dv_phi =
           context.get_element_fe(_v_var)->get_dphi();
         // Local DOF count and quadrature point count
         const unsigned int n_T_dofs = context.get_dof_indices(0).size();
         unsigned int n_qpoints = context.get_element_qrule().n_points();
         // Warning: we assume here that vorticity is the only QoI!
         // This should be consistent with the assertion in grins_mesh_adaptive_solver.C
         libMesh::DenseSubVector<libMesh::Number> &Qu = context.get_qoi_derivatives(qoi_index, _u_var);
         libMesh::DenseSubVector<libMesh::Number> &Qv = context.get_qoi_derivatives(qoi_index, _v_var);
         // Integration loop
         for( unsigned int qp = 0; qp != n_qpoints; qp++ )
           {
             for( unsigned int i = 0; i != n_T_dofs; i++ )
               {
                 Qu(i) += - dv_phi[i][qp](1) * JxW[qp];
                 Qv(i) += du_phi[i][qp](0) * JxW[qp];
               }
           }
       }
     return;
   }
void GRINS::Vorticity::init (const GetPot & input, const MultiphysicsSystem & system) virtual
Initialize local variables.
Any local variables that need information from libMesh get initialized here. For example, variable indices.
Reimplemented from GRINS::QoIBase.
Definition at line 57 of file vorticity.C.
References _subdomain_ids, _u_var, _v_var, GRINS::u_var_name_default, and GRINS::v_var_name_default.
   {
     // Extract subdomain on which to compute to qoi
     int num_ids = input.vector_variable_size( "QoI/Vorticity/enabled_subdomains" );
     if( num_ids == 0 )
       {
         std::cerr << "Error: Must specify at least one subdomain id on which to compute vorticity." << std::endl;
         libmesh_error();
       }
     for( int i = 0; i < num_ids; i++ )
       {
         libMesh::subdomain_id_type s_id = input( "QoI/Vorticity/enabled_subdomains", -1, i );
         _subdomain_ids.insert( s_id );
       }
     // Grab velocity variable indices
     std::string u_var_name = input("Physics/VariableNames/u_velocity", u_var_name_default);
     std::string v_var_name = input("Physics/VariableNames/v_velocity", v_var_name_default);
     this->_u_var = system.variable_number(u_var_name);
     this->_v_var = system.variable_number(v_var_name);
     return;
   }
void GRINS::Vorticity::init_context (AssemblyContext & context) virtual
Reimplemented from GRINS::QoIBase.
Definition at line 83 of file vorticity.C.
References _u_var, and _v_var.
   {
     libMesh::FEBase* u_fe = NULL;
     libMesh::FEBase* v_fe = NULL;
     context.get_element_fe<libMesh::Real>(this->_u_var, u_fe);
     context.get_element_fe<libMesh::Real>(this->_v_var, v_fe);
     u_fe->get_dphi();
     u_fe->get_JxW();
     v_fe->get_dphi();
     return;
   }
const std::string & GRINS::QoIBase::name () const inline inherited
Returns the name of this QoI.
Definition at line 143 of file qoi_base.h.
References GRINS::QoIBase::_qoi_name.
Referenced by GRINS::SteadyVisualization::output_adjoint(), and GRINS::UnsteadyVisualization::output_adjoint().
   {
     return _qoi_name;
   }
void GRINS::QoIBase::output_qoi (std::ostream & out) const virtual inherited
Basic output for computed QoI's.
If fancier output is desired, override this method.
Definition at line 107 of file qoi_base.C.
References GRINS::QoIBase::_qoi_name, and GRINS::QoIBase::_qoi_value.
   {
     out << "==========================================================" << std::endl;
     out << _qoi_name+" = "
         << std::setprecision(16)
         << std::scientific
         << _qoi_value << std::endl;
     out << "==========================================================" << std::endl;
     return;
   }
void GRINS::QoIBase::parallel_op (const libMesh::Parallel::Communicator & communicator, libMesh::Number & sys_qoi, libMesh::Number & local_qoi) virtual inherited
Call the parallel operation for this QoI and cache the value.
By default, this is just a sum. Override if QoI is more complex.
Definition at line 87 of file qoi_base.C.
References GRINS::QoIBase::_qoi_value.
   {
     communicator.sum(local_qoi);
     sys_qoi = local_qoi;
     _qoi_value = sys_qoi;
     return;
   }
void GRINS::ParameterUser::register_parameter (const std::string & param_name, libMesh::ParameterMultiPointer< libMesh::Number > & param_pointer) const virtual inherited
Each subclass will register its copy of an independent.
Reimplemented in GRINS::AxisymmetricHeatTransfer< Conductivity >, GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::IncompressibleNavierStokesBase< Viscosity >, GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >, GRINS::HeatConduction< Conductivity >, GRINS::HeatTransferBase< Conductivity >, and GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >.
Definition at line 50 of file parameter_user.C.
Referenced by GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::register_parameter(), GRINS::HeatTransferBase< Conductivity >::register_parameter(), GRINS::HeatConduction< Conductivity >::register_parameter(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::register_parameter(), GRINS::IncompressibleNavierStokesBase< Viscosity >::register_parameter(), GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::register_parameter(), and GRINS::AxisymmetricHeatTransfer< Conductivity >::register_parameter().
   {
     std::map<std::string, libMesh::Number*>::const_iterator it =
       _my_parameters.find(param_name);
     if (it != _my_parameters.end())
       {
         std::cout << _my_name << " uses parameter " << param_name
                   << std::endl;
         param_pointer.push_back(it->second);
       }
   }
void GRINS::ParameterUser::set_parameter (libMesh::Number & param_variable, const GetPot & input, const std::string & param_name, libMesh::Number param_default) virtual inherited
Each subclass can simultaneously read a parameter value from.
Definition at line 35 of file parameter_user.C.
References GRINS::ParameterUser::_my_name, and GRINS::ParameterUser::_my_parameters.
Referenced by GRINS::AveragedFanAdjointStabilization< Viscosity >::AveragedFanAdjointStabilization(), GRINS::AveragedTurbineAdjointStabilization< Viscosity >::AveragedTurbineAdjointStabilization(), GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::BoussinesqBuoyancyAdjointStabilization(), GRINS::BoussinesqBuoyancyBase::BoussinesqBuoyancyBase(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::BoussinesqBuoyancySPGSMStabilization(), GRINS::ConstantConductivity::ConstantConductivity(), GRINS::ConstantPrandtlConductivity::ConstantPrandtlConductivity(), GRINS::ConstantSourceFunction::ConstantSourceFunction(), GRINS::ConstantSourceTerm::ConstantSourceTerm(), GRINS::ConstantSpecificHeat::ConstantSpecificHeat(), GRINS::ConstantViscosity::ConstantViscosity(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticCableConstantGravity::ElasticCableConstantGravity(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransferBase< Conductivity >::HeatTransferBase(), GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase(), GRINS::AverageNusseltNumber::init(), GRINS::MooneyRivlin::MooneyRivlin(), GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase(), GRINS::HookesLaw1D::read_input_options(), GRINS::HookesLaw::read_input_options(), GRINS::AxisymmetricBoussinesqBuoyancy::read_input_options(), and GRINS::VelocityDragAdjointStabilization< Viscosity >::VelocityDragAdjointStabilization().
   {
     param_variable = input(param_name, param_default);
     libmesh_assert_msg(!_my_parameters.count(param_name),
       "ERROR: " << _my_name << " double-registered parameter " <<
       param_name);
     _my_parameters[param_name] = &param_variable;
   }
void GRINS::QoIBase::side_qoi (AssemblyContext & context, const unsigned int qoi_index) virtual inherited
Compute the qoi value on the domain boundary.
Override this method if your QoI is defined on the domain boundary
Reimplemented in GRINS::AverageNusseltNumber.
Definition at line 75 of file qoi_base.C.
   {
     return;
   }
void GRINS::QoIBase::side_qoi_derivative (AssemblyContext & context, const unsigned int qoi_index) virtual inherited
Compute the qoi derivative with respect to the solution on the domain boundary.
Override this method if your QoI is defined on the domain boundary
Reimplemented in GRINS::AverageNusseltNumber.
Definition at line 81 of file qoi_base.C.
   {
     return;
   }
void GRINS::QoIBase::thread_join (libMesh::Number & qoi, const libMesh::Number & other_qoi) virtual inherited
Call the operation to accumulate this QoI from multiple threads.
By default, this is just a sum. Override if QoI is more complex.
Definition at line 100 of file qoi_base.C.
   {
     qoi += other_qoi;
     return;
   }
libMesh::Number GRINS::QoIBase::value () const inline inherited
Returns the current QoI value.
Definition at line 137 of file qoi_base.h.
References GRINS::QoIBase::_qoi_value.
   {
     return _qoi_value;
   }
Member Data Documentation
std::string GRINS::QoIBase::_qoi_name protected inherited
Definition at line 131 of file qoi_base.h.
Referenced by GRINS::QoIBase::name(), and GRINS::QoIBase::output_qoi().
libMesh::Number GRINS::QoIBase::_qoi_value protected inherited
Definition at line 133 of file qoi_base.h.
Referenced by GRINS::QoIBase::output_qoi(), GRINS::QoIBase::parallel_op(), and GRINS::QoIBase::value().
std::set<libMesh::subdomain_id_type> GRINS::Vorticity::_subdomain_ids protected
List of sumdomain ids for which we want to compute this QoI.
Definition at line 89 of file vorticity.h.
Referenced by element_qoi(), element_qoi_derivative(), and init().
VariableIndex GRINS::Vorticity::_u_var protected
u-velocity component variable index
Definition at line 83 of file vorticity.h.
Referenced by element_qoi(), element_qoi_derivative(), init(), and init_context().
VariableIndex GRINS::Vorticity::_v_var protected
v-velocity component variable index
Definition at line 86 of file vorticity.h.
Referenced by element_qoi(), element_qoi_derivative(), init(), and init_context().
The documentation for this class was generated from the following files:
src/qoi/include/grins/vorticity.h
src/qoi/src/vorticity.C