GRINS-0.8.0: GRINSTesting::SpectroscopicAbsorptionTest Class Reference
GRINSTesting::SpectroscopicAbsorptionTest Class Reference
Public Member Functions
CPPUNIT_TEST_SUITE (SpectroscopicAbsorptionTest)
CPPUNIT_TEST (single_elem_mesh)
CPPUNIT_TEST (multi_elem_mesh)
CPPUNIT_TEST (param_derivs)
CPPUNIT_TEST (elem_qoi_derivatives)
CPPUNIT_TEST_SUITE_END ()
void tearDown ()
void single_elem_mesh ()
Single QUAD4 elem, uniform T,P,Y.
void multi_elem_mesh ()
10x10 mesh, uniform T,P,Y
void param_derivs ()
void elem_qoi_derivatives ()
Private Member Functions
void run_test (const std::string filename, libMesh::Real calc_answer)
Run the test on a given input file and calculated answer.
void init_sim (const std::string &filename)
Initialize the GetPot and Simulation class objects.
void T_param_derivatives (GRINS::SharedPtr< AbsorptionCoeffTesting< GRINS::AntiochChemistry > >absorb, libMesh::Real T, libMesh::Real P, std::vector< libMesh::Real > &Y, unsigned int i)
void P_param_derivatives (GRINS::SharedPtr< AbsorptionCoeffTesting< GRINS::AntiochChemistry > >absorb, libMesh::Real T, libMesh::Real P, std::vector< libMesh::Real > &Y, unsigned int i)
void Y_param_derivatives (GRINS::SharedPtr< AbsorptionCoeffTesting< GRINS::AntiochChemistry > >absorb, libMesh::Real T, libMesh::Real P, std::vector< libMesh::Real > &Y, unsigned int i)
void check_param_derivatives (std::vector< libMesh::Real > &analytic, std::vector< libMesh::Real > &fd_plus, std::vector< libMesh::Real > &fd_minus, libMesh::Real delta)
void T_elem_derivative (GRINS::MultiphysicsSystem *system, GRINS::AssemblyContext *context)
void P_elem_derivative (GRINS::MultiphysicsSystem *system, GRINS::AssemblyContext *context)
void Y_elem_derivative (GRINS::MultiphysicsSystem *system, GRINS::AssemblyContext *context)
void test_var_elem_derivs (GRINS::MultiphysicsSystem *system, GRINS::AssemblyContext *context, unsigned int var_index, libMesh::Real delta)
Private Attributes
GRINS::SharedPtr< GRINS::Simulation > _sim
GRINS::SharedPtr< GetPot > _input
Detailed Description
Definition at line 60 of file spectroscopic_absorption_test.C.
Member Function Documentation
void GRINSTesting::SpectroscopicAbsorptionTest::check_param_derivatives (std::vector< libMesh::Real > & analytic, std::vector< libMesh::Real > & fd_plus, std::vector< libMesh::Real > & fd_minus, libMesh::Real delta) inline private
Definition at line 287 of file spectroscopic_absorption_test.C.
Referenced by P_param_derivatives(), T_param_derivatives(), and Y_param_derivatives().
     {
       for (unsigned int d=0; d<analytic.size(); ++d)
         {
           libMesh::Real f_analytic = analytic[d];
           libMesh::Real fd_approx = (fd_plus[d] - fd_minus[d])/(2.0*delta);
           CPPUNIT_ASSERT_DOUBLES_EQUAL(fd_approx,f_analytic,libMesh::TOLERANCE);
         }
     }
GRINSTesting::SpectroscopicAbsorptionTest::CPPUNIT_TEST (single_elem_mesh)
GRINSTesting::SpectroscopicAbsorptionTest::CPPUNIT_TEST (multi_elem_mesh)
GRINSTesting::SpectroscopicAbsorptionTest::CPPUNIT_TEST (param_derivs)
GRINSTesting::SpectroscopicAbsorptionTest::CPPUNIT_TEST (elem_qoi_derivatives)
GRINSTesting::SpectroscopicAbsorptionTest::CPPUNIT_TEST_SUITE (SpectroscopicAbsorptionTest)
GRINSTesting::SpectroscopicAbsorptionTest::CPPUNIT_TEST_SUITE_END ()
void GRINSTesting::SpectroscopicAbsorptionTest::elem_qoi_derivatives () inline
Definition at line 133 of file spectroscopic_absorption_test.C.
References _sim, GRINS::MultiphysicsSystem::build_context(), GRINS::MultiphysicsSystem::init_context(), init_sim(), P_elem_derivative(), T_elem_derivative(), and Y_elem_derivative().
     {
       const std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/spectroscopic_absorption_qoi.in";
       // run the Simulation once to ensure everything is initialized and populated
       this->init_sim(filename);
       _sim->run();
       GRINS::MultiphysicsSystem * system = _sim->get_multiphysics_system();
       GRINS::AssemblyContext * context = libMesh::cast_ptr<GRINS::AssemblyContext*>(system->build_context().release());
       system->init_context(*context);
       context->pre_fe_reinit(*system,system->get_mesh().elem_ptr(0));
       libMesh::QoISet qs;
       qs.add_index(0);
       libMesh::DifferentiableQoI * qoi = system->get_qoi();
       qoi->element_qoi_derivative(*context,qs);
       this->T_elem_derivative(system,context);
       this->P_elem_derivative(system,context);
       this->Y_elem_derivative(system,context);
     }
void GRINSTesting::SpectroscopicAbsorptionTest::init_sim (const std::string & filename) inline private
Initialize the GetPot and Simulation class objects.
Definition at line 172 of file spectroscopic_absorption_test.C.
References TestCommWorld.
Referenced by elem_qoi_derivatives(), param_derivs(), and run_test().
     {
       _input.reset(new GetPot(filename));
       const char * const argv = "unit_driver";
       GetPot empty_command_line( (const int)1,&argv );
       GRINS::SimulationBuilder sim_builder;
       _sim = new GRINS::Simulation(*_input,
                                    empty_command_line,
                                    sim_builder,
                                    *TestCommWorld );
     }
void GRINSTesting::SpectroscopicAbsorptionTest::multi_elem_mesh () inline
10x10 mesh, uniform T,P,Y
Definition at line 88 of file spectroscopic_absorption_test.C.
References run_test().
     {
       const std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/spectroscopic_absorption_qoi_fine.in";
       libMesh::Real calc_answer = 0.520403290868787; // same physical conditions as single_elem_mesh, so answer should not change
       this->run_test(filename,calc_answer);
     }
void GRINSTesting::SpectroscopicAbsorptionTest::P_elem_derivative (GRINS::MultiphysicsSystem * system, GRINS::AssemblyContext * context) inline private
Definition at line 305 of file spectroscopic_absorption_test.C.
References GRINS::PressureFEVariable::p(), and test_var_elem_derivs().
Referenced by elem_qoi_derivatives().
     {
       GRINS::PressureFEVariable P_var( GRINS::GRINSPrivate::VariableWarehouse::get_variable_subclass<GRINS::PressureFEVariable>("Pressure") );
       libMesh::Real delta = 1e-3;
       test_var_elem_derivs(system,context,P_var.p(),delta);
     }
void GRINSTesting::SpectroscopicAbsorptionTest::P_param_derivatives (GRINS::SharedPtr< AbsorptionCoeffTesting< GRINS::AntiochChemistry > > absorb, libMesh::Real T, libMesh::Real P, std::vector< libMesh::Real > & Y, unsigned int i) inline private
Definition at line 220 of file spectroscopic_absorption_test.C.
References check_param_derivatives().
Referenced by param_derivs().
     {
       libMesh::Real delta = 1.0e-3;
       std::vector<libMesh::Real> P_analytic;
       P_analytic.push_back(absorb->dS_dP(T,P,i));
       P_analytic.push_back(absorb->d_nuC_dP(T,Y,i));
       P_analytic.push_back(absorb->d_nuD_dP(T,i));
       P_analytic.push_back(absorb->d_voigt_a_dP(T,P,Y,i));
       P_analytic.push_back(absorb->d_voigt_w_dP(T,P,i));
       P_analytic.push_back(absorb->d_voigt_dP(T,P,Y,i));
       P_analytic.push_back(absorb->d_kv_dP(T,P,Y,i));
       std::vector<libMesh::Real> fd_plus;
       fd_plus.push_back(absorb->Sw(T,P+delta,i));
       fd_plus.push_back(absorb->nu_C(T,P+delta,Y,i));
       fd_plus.push_back(absorb->nu_D(T,P+delta,i));
       fd_plus.push_back(absorb->voigt_a(T,P+delta,Y,i));
       fd_plus.push_back(absorb->voigt_w(T,P+delta,i));
       fd_plus.push_back(absorb->voigt(T,P+delta,Y,i));
       fd_plus.push_back(absorb->kv(T,P+delta,Y,i));
       std::vector<libMesh::Real> fd_minus;
       fd_minus.push_back(absorb->Sw(T,P-delta,i));
       fd_minus.push_back(absorb->nu_C(T,P-delta,Y,i));
       fd_minus.push_back(absorb->nu_D(T,P-delta,i));
       fd_minus.push_back(absorb->voigt_a(T,P-delta,Y,i));
       fd_minus.push_back(absorb->voigt_w(T,P-delta,i));
       fd_minus.push_back(absorb->voigt(T,P-delta,Y,i));
       fd_minus.push_back(absorb->kv(T,P-delta,Y,i));
       check_param_derivatives(P_analytic,fd_plus,fd_minus,delta);
     }
void GRINSTesting::SpectroscopicAbsorptionTest::param_derivs () inline
Definition at line 96 of file spectroscopic_absorption_test.C.
References _input, GRINS::ChemistryBuilder::build_chemistry(), init_sim(), P_param_derivatives(), T_param_derivatives(), and Y_param_derivatives().
     {
       const std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/spectroscopic_absorption_qoi.in";
       this->init_sim(filename);
       std::string material = "TestMaterial";
       std::string hitran_data = "./test_data/CO2_data.dat";
       std::string hitran_partition = "./test_data/CO2_partition_function.dat";
       libMesh::Real T_min = 290.0,
         T_max = 310.0,
         T_step = 0.01;
       GRINS::SharedPtr<GRINS::HITRAN> hitran( new GRINS::HITRAN(hitran_data,hitran_partition,T_min,T_max,T_step) );
       std::string species = "CO2";
       libMesh::Real thermo_pressure = 5066.25;
       libMesh::Real nu_desired = 3682.7649;
       libMesh::Real nu_min = 3682.69;
       libMesh::Real nu_max = 3682.8;
       GRINS::ChemistryBuilder chem_builder;
       libMesh::UniquePtr<GRINS::AntiochChemistry> chem_ptr;
       chem_builder.build_chemistry(*(_input.get()),material,chem_ptr);
       GRINS::SharedPtr<GRINS::AntiochChemistry> chem(chem_ptr.release());
       GRINS::SharedPtr<AbsorptionCoeffTesting<GRINS::AntiochChemistry> > absorb = new AbsorptionCoeffTesting<GRINS::AntiochChemistry>(chem,hitran,nu_min,nu_max,nu_desired,species,thermo_pressure);
       libMesh::Real T = 300.0;
       libMesh::Real P = 5066.25;
       std::vector<libMesh::Real> Y = {0.0763662233, 0.9236337767};
       for (unsigned int i=0; i<33; ++i)
         {
           this->T_param_derivatives(absorb,T,P,Y,i);
           this->P_param_derivatives(absorb,T,P,Y,i);
           this->Y_param_derivatives(absorb,T,P,Y,i);
         }
     }
void GRINSTesting::SpectroscopicAbsorptionTest::run_test (const std::string filename, libMesh::Real calc_answer) inline private
Run the test on a given input file and calculated answer.
Definition at line 162 of file spectroscopic_absorption_test.C.
References init_sim().
Referenced by multi_elem_mesh(), and single_elem_mesh().
     {
       this->init_sim(filename);
       _sim->run();
       CPPUNIT_ASSERT_DOUBLES_EQUAL( calc_answer, _sim->get_qoi_value(0),libMesh::TOLERANCE  );
     }
void GRINSTesting::SpectroscopicAbsorptionTest::single_elem_mesh () inline
Single QUAD4 elem, uniform T,P,Y.
Definition at line 79 of file spectroscopic_absorption_test.C.
References run_test().
     {
       const std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/spectroscopic_absorption_qoi.in";
       libMesh::Real calc_answer = 0.520403290868787;
       this->run_test(filename,calc_answer);
     }
void GRINSTesting::SpectroscopicAbsorptionTest::T_elem_derivative (GRINS::MultiphysicsSystem * system, GRINS::AssemblyContext * context) inline private
Definition at line 298 of file spectroscopic_absorption_test.C.
References GRINS::PrimitiveTempFEVariables::T(), and test_var_elem_derivs().
Referenced by elem_qoi_derivatives().
     {
       GRINS::PrimitiveTempFEVariables T_var( GRINS::GRINSPrivate::VariableWarehouse::get_variable_subclass<GRINS::PrimitiveTempFEVariables>("Temperature") );
       libMesh::Real delta = 1e-6;
       test_var_elem_derivs(system,context,T_var.T(),delta);
     }
void GRINSTesting::SpectroscopicAbsorptionTest::T_param_derivatives (GRINS::SharedPtr< AbsorptionCoeffTesting< GRINS::AntiochChemistry > > absorb, libMesh::Real T, libMesh::Real P, std::vector< libMesh::Real > & Y, unsigned int i) inline private
Definition at line 186 of file spectroscopic_absorption_test.C.
References check_param_derivatives().
Referenced by param_derivs().
     {
       libMesh::Real delta = 1.0e-6;
       std::vector<libMesh::Real> T_analytic;
       T_analytic.push_back(absorb->dS_dT(T,P,i));
       T_analytic.push_back(absorb->d_nuC_dT(T,P,Y,i));
       T_analytic.push_back(absorb->d_nuD_dT(T,P,i));
       T_analytic.push_back(absorb->d_voigt_a_dT(T,P,Y,i));
       T_analytic.push_back(absorb->d_voigt_w_dT(T,P,i));
       T_analytic.push_back(absorb->d_voigt_dT(T,P,Y,i));
       T_analytic.push_back(absorb->d_kv_dT(T,P,Y,i));
       std::vector<libMesh::Real> fd_plus;
       fd_plus.push_back(absorb->Sw(T+delta,P,i));
       fd_plus.push_back(absorb->nu_C(T+delta,P,Y,i));
       fd_plus.push_back(absorb->nu_D(T+delta,P,i));
       fd_plus.push_back(absorb->voigt_a(T+delta,P,Y,i));
       fd_plus.push_back(absorb->voigt_w(T+delta,P,i));
       fd_plus.push_back(absorb->voigt(T+delta,P,Y,i));
       fd_plus.push_back(absorb->kv(T+delta,P,Y,i));
       std::vector<libMesh::Real> fd_minus;
       fd_minus.push_back(absorb->Sw(T-delta,P,i));
       fd_minus.push_back(absorb->nu_C(T-delta,P,Y,i));
       fd_minus.push_back(absorb->nu_D(T-delta,P,i));
       fd_minus.push_back(absorb->voigt_a(T-delta,P,Y,i));
       fd_minus.push_back(absorb->voigt_w(T-delta,P,i));
       fd_minus.push_back(absorb->voigt(T-delta,P,Y,i));
       fd_minus.push_back(absorb->kv(T-delta,P,Y,i));
       check_param_derivatives(T_analytic,fd_plus,fd_minus,delta);
     }
void GRINSTesting::SpectroscopicAbsorptionTest::tearDown () inline
Definition at line 72 of file spectroscopic_absorption_test.C.
References GRINS::GRINSPrivate::VariableWarehouse::clear().
     {
       // Clear out the VariableWarehouse so it doesn't interfere with other tests.
       GRINS::GRINSPrivate::VariableWarehouse::clear();
     }
void GRINSTesting::SpectroscopicAbsorptionTest::test_var_elem_derivs (GRINS::MultiphysicsSystem * system, GRINS::AssemblyContext * context, unsigned int var_index, libMesh::Real delta) inline private
Definition at line 319 of file spectroscopic_absorption_test.C.
Referenced by P_elem_derivative(), T_elem_derivative(), and Y_elem_derivative().
     {
       libMesh::DifferentiableQoI * qoi = system->get_qoi();
       libMesh::Number & qoi_value = context->get_qois()[0];
       qoi_value = 0.0;
       libMesh::QoISet qs;
       qs.add_index(0);
       libMesh::DenseSubVector<libMesh::Number> deriv = context->get_qoi_derivatives(0,var_index);
       libMesh::DenseSubVector<libMesh::Number> & solution  = context->get_elem_solution(var_index);
       for (unsigned int d=0; d<solution.size(); ++d)
         {
           libMesh::Number soln = solution.el(d);
           solution(d) = soln+delta;
           qoi->element_qoi(*context,qs);
           libMesh::Number qoi_p1 = qoi_value;
           qoi_value = 0.0;
           solution(d) = soln-delta;
           qoi->element_qoi(*context,qs);
           libMesh::Number qoi_m1= qoi_value;
           qoi_value = 0.0;
           solution(d) = soln;
           libMesh::Real fd_approx = (qoi_p1 - qoi_m1)/(2.0*delta);
           CPPUNIT_ASSERT_DOUBLES_EQUAL(fd_approx,deriv(d),libMesh::TOLERANCE);
         }
     }
void GRINSTesting::SpectroscopicAbsorptionTest::Y_elem_derivative (GRINS::MultiphysicsSystem * system, GRINS::AssemblyContext * context) inline private
Definition at line 312 of file spectroscopic_absorption_test.C.
References GRINS::SpeciesMassFractionsVariable::species(), and test_var_elem_derivs().
Referenced by elem_qoi_derivatives().
     {
       GRINS::SpeciesMassFractionsVariable Y_var( GRINS::GRINSPrivate::VariableWarehouse::get_variable_subclass<GRINS::SpeciesMassFractionsVariable>("SpeciesMassFractions") );
       libMesh::Real delta = 1e-8;
       test_var_elem_derivs(system,context,Y_var.species(0),delta);
     }
void GRINSTesting::SpectroscopicAbsorptionTest::Y_param_derivatives (GRINS::SharedPtr< AbsorptionCoeffTesting< GRINS::AntiochChemistry > > absorb, libMesh::Real T, libMesh::Real P, std::vector< libMesh::Real > & Y, unsigned int i) inline private
Definition at line 254 of file spectroscopic_absorption_test.C.
References check_param_derivatives().
Referenced by param_derivs().
     {
       libMesh::Real delta = 1.0e-8;
       libMesh::Real y_base = Y[0];
       std::vector<libMesh::Real> Y_analytic;
       Y_analytic.push_back(absorb->dX_dY(Y));
       Y_analytic.push_back(absorb->d_nuC_dY(T,P,Y,i));
       Y_analytic.push_back(absorb->d_voigt_a_dY(T,P,Y,i));
       Y_analytic.push_back(absorb->d_voigt_dY(T,P,Y,i));
       Y_analytic.push_back(absorb->d_kv_dY(T,P,Y,i));
       std::vector<libMesh::Real> fd_plus;
       Y[0] = y_base + delta;
       fd_plus.push_back(absorb->_chemistry->X(absorb->_species_idx,absorb->_chemistry->M_mix(Y),Y[absorb->_species_idx]));
       fd_plus.push_back(absorb->nu_C(T,P,Y,i));
       fd_plus.push_back(absorb->voigt_a(T,P,Y,i));
       fd_plus.push_back(absorb->voigt(T,P,Y,i));
       fd_plus.push_back(absorb->kv(T,P,Y,i));
       std::vector<libMesh::Real> fd_minus;
       Y[0] = y_base - delta;
       fd_minus.push_back(absorb->_chemistry->X(absorb->_species_idx,absorb->_chemistry->M_mix(Y),Y[absorb->_species_idx]));
       fd_minus.push_back(absorb->nu_C(T,P,Y,i));
       fd_minus.push_back(absorb->voigt_a(T,P,Y,i));
       fd_minus.push_back(absorb->voigt(T,P,Y,i));
       fd_minus.push_back(absorb->kv(T,P,Y,i));
       Y[0] = y_base;
       check_param_derivatives(Y_analytic,fd_plus,fd_minus,delta);
     }
Member Data Documentation
GRINS::SharedPtr<GetPot> GRINSTesting::SpectroscopicAbsorptionTest::_input private
Definition at line 159 of file spectroscopic_absorption_test.C.
Referenced by param_derivs().
GRINS::SharedPtr<GRINS::Simulation> GRINSTesting::SpectroscopicAbsorptionTest::_sim private
Definition at line 158 of file spectroscopic_absorption_test.C.
Referenced by elem_qoi_derivatives().
The documentation for this class was generated from the following file:
test/unit/spectroscopic_absorption_test.C