GRINS-0.8.0: GRINS::AntiochMixtureAveragedTransportEvaluator< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity > Class Template Reference
GRINS::AntiochMixtureAveragedTransportEvaluator< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity > Class Template Reference
Wrapper class for evaluating Wilke transport properties using Antioch.
#include <antioch_mixture_averaged_transport_evaluator.h>
Public Member Functions
AntiochMixtureAveragedTransportEvaluator (const AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity > &mixture)
virtual ~AntiochMixtureAveragedTransportEvaluator ()
libMesh::Real mu (const libMesh::Real T, const libMesh::Real P, const std::vector< libMesh::Real > &Y)
libMesh::Real k (const libMesh::Real T, const libMesh::Real P, const std::vector< libMesh::Real > &Y)
void mu_and_k_and_D (const libMesh::Real T, const libMesh::Real rho, const libMesh::Real cp, const std::vector< libMesh::Real > &Y, libMesh::Real &mu, libMesh::Real &k, std::vector< libMesh::Real > &D)
Public Member Functions inherited from GRINS::AntiochEvaluator< Antioch::CEACurveFit< libMesh::Real >, Thermo >
AntiochEvaluator (const AntiochMixture< Antioch::CEACurveFit< libMesh::Real > > &mixture)
virtual ~AntiochEvaluator ()
libMesh::Real M (unsigned int species) const
libMesh::Real M_mix (const std::vector< libMesh::Real > &mass_fractions) const
libMesh::Real R (unsigned int species) const
libMesh::Real R_mix (const std::vector< libMesh::Real > &mass_fractions) const
libMesh::Real X (unsigned int species, libMesh::Real M, libMesh::Real mass_fraction) const
void X (libMesh::Real M, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &mole_fractions) const
unsigned int species_index (const std::string &species_name) const
std::string species_name (unsigned int species_index) const
libMesh::Real cp (const libMesh::Real &T, const libMesh::Real P, const std::vector< libMesh::Real > &Y)
libMesh::Real cv (const libMesh::Real &T, const libMesh::Real P, const std::vector< libMesh::Real > &Y)
libMesh::Real h_s (const libMesh::Real &T, unsigned int species)
void omega_dot (const libMesh::Real &T, libMesh::Real rho, const std::vector< libMesh::Real > mass_fractions, std::vector< libMesh::Real > &omega_dot)
Protected Attributes
libMesh::UniquePtr< Antioch::MixtureAveragedTransportEvaluator< Diffusivity, Viscosity, Conductivity, libMesh::Real > > _wilke_evaluator
const Antioch::MixtureDiffusion< Diffusivity, libMesh::Real > & _diffusivity
Protected Attributes inherited from GRINS::AntiochEvaluator< Antioch::CEACurveFit< libMesh::Real >, Thermo >
const AntiochMixture< Antioch::CEACurveFit< libMesh::Real > > & _chem
libMesh::UniquePtr< Thermo > _thermo
Primary thermo object.
libMesh::UniquePtr< Antioch::NASAEvaluator< libMesh::Real, Antioch::CEACurveFit< libMesh::Real > > > _nasa_evaluator
For some Thermo types, we also need to cache a NASAEvaluator.
libMesh::UniquePtr< AntiochKinetics< Antioch::CEACurveFit< libMesh::Real > > > _kinetics
libMesh::Real _clipped_T
const libMesh::Real _minimum_T
libMesh::UniquePtr< Antioch::TempCache< libMesh::Real > > _temp_cache
Private Member Functions
AntiochMixtureAveragedTransportEvaluator ()
Additional Inherited Members
Protected Member Functions inherited from GRINS::AntiochEvaluator< Antioch::CEACurveFit< libMesh::Real >, Thermo >
void check_and_reset_temp_cache (const libMesh::Real &T)
Helper method for managing _temp_cache.
void build_thermo (const AntiochMixture< Antioch::CEACurveFit< libMesh::Real > > &mixture)
Detailed Description
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity>
class GRINS::AntiochMixtureAveragedTransportEvaluator< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >
Wrapper class for evaluating Wilke transport properties using Antioch.
This class is expected to be constructed after threads have been forked and will only live during the lifetime of the thread. By default, Antioch is working in SI units. Note that this documentation will always be built regardless if Antioch is included in the GRINS build or not. Check configure output to confirm that Antioch was included in the build.
Definition at line 54 of file antioch_mixture_averaged_transport_evaluator.h.
Constructor & Destructor Documentation
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> GRINS::AntiochMixtureAveragedTransportEvaluator< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::AntiochMixtureAveragedTransportEvaluator (const AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity > & mixture)
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> virtual GRINS::AntiochMixtureAveragedTransportEvaluator< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::~AntiochMixtureAveragedTransportEvaluator () inline virtual
Definition at line 60 of file antioch_mixture_averaged_transport_evaluator.h.
 {};
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> GRINS::AntiochMixtureAveragedTransportEvaluator< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::AntiochMixtureAveragedTransportEvaluator () private
Member Function Documentation
template<typename KT , typename Th , typename V , typename C , typename D > libMesh::Real GRINS::AntiochMixtureAveragedTransportEvaluator< KT, Th, V, C, D >::k (const libMesh::Real T, const libMesh::Real P, const std::vector< libMesh::Real > & Y)
Definition at line 58 of file antioch_mixture_averaged_transport_evaluator.C.
   {
     libmesh_error();
     return 0.0;//_wilke_evaluator->k( T, Y );
   }
template<typename KT , typename Th , typename V , typename C , typename D > libMesh::Real GRINS::AntiochMixtureAveragedTransportEvaluator< KT, Th, V, C, D >::mu (const libMesh::Real T, const libMesh::Real P, const std::vector< libMesh::Real > & Y)
Definition at line 50 of file antioch_mixture_averaged_transport_evaluator.C.
References GRINS::AntiochMixtureAveragedTransportEvaluator< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::mu().
Referenced by GRINS::AntiochMixtureAveragedTransportEvaluator< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::mu().
   {
     return _wilke_evaluator->mu( T, Y );
   }
template<typename KT , typename Th , typename V , typename C , typename Diff > void GRINS::AntiochMixtureAveragedTransportEvaluator< KT, Th, V, C, Diff >::mu_and_k_and_D (const libMesh::Real T, const libMesh::Real rho, const libMesh::Real cp, const std::vector< libMesh::Real > & Y, libMesh::Real & mu, libMesh::Real & k, std::vector< libMesh::Real > & D)
Definition at line 67 of file antioch_mixture_averaged_transport_evaluator.C.
References GRINS::AntiochMixtureAveragedTransportEvaluator< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::mu_and_k_and_D().
Referenced by do_transport_eval(), GRINS::AntiochMixtureAveragedTransportEvaluator< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::mu_and_k_and_D(), and test_evaluator().
   {
     typename Antioch::MixtureAveragedTransportEvaluator<Diff,V,C,libMesh::Real>::DiffusivityType diff_type =
       Antioch::MixtureAveragedTransportEvaluator<Diff,V,C,libMesh::Real>::DiffusivityType::MASS_FLUX_MASS_FRACTION;
     _wilke_evaluator->mu_and_k_and_D( T, rho, cp, Y, mu, k, D, diff_type );
   }
Member Data Documentation
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> const Antioch::MixtureDiffusion<Diffusivity,libMesh::Real>& GRINS::AntiochMixtureAveragedTransportEvaluator< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::_diffusivity protected
Definition at line 82 of file antioch_mixture_averaged_transport_evaluator.h.
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> libMesh::UniquePtr<Antioch::MixtureAveragedTransportEvaluator<Diffusivity,Viscosity,Conductivity,libMesh::Real> > GRINS::AntiochMixtureAveragedTransportEvaluator< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::_wilke_evaluator protected
Definition at line 80 of file antioch_mixture_averaged_transport_evaluator.h.
The documentation for this class was generated from the following files:
src/properties/include/grins/antioch_mixture_averaged_transport_evaluator.h
src/properties/src/antioch_mixture_averaged_transport_evaluator.C