GRINS-0.8.0: GRINS::VariableFactoryInitializer Class Reference
GRINS::VariableFactoryInitializer Class Reference
Initialize all VariableFactory objects.
#include <variable_factory_initializer.h>
Public Member Functions
VariableFactoryInitializer ()
~VariableFactoryInitializer ()
Detailed Description
Initialize all VariableFactory objects.
To avoid symbol stripping from static linking, we use this class to initialize/register the Variable factory objects.
Relevant discussion: http://stackoverflow.com/questions/5202142/static-variable-initialization-over-a-library
Definition at line 35 of file variable_factory_initializer.h.
Constructor & Destructor Documentation
GRINS::VariableFactoryInitializer::VariableFactoryInitializer ()
Definition at line 36 of file variable_factory_initializer.C.
References GRINS::VariablesParsing::displacement_section(), GRINS::VariablesParsing::pressure_section(), GRINS::VariablesParsing::scalar_var_section(), GRINS::VariablesParsing::single_var_section(), GRINS::VariablesParsing::species_mass_fractions_section(), GRINS::VariablesParsing::temperature_section(), GRINS::VariablesParsing::thermo_pressure_section(), GRINS::VariablesParsing::turbulence_section(), and GRINS::VariablesParsing::velocity_section().
   {
     static VariableFactoryBasic<DisplacementVariable>
       grins_factory_disp_fe_var(VariablesParsing::displacement_section());
     static VariableFactoryBasic<SingleVariable>
       grins_factory_single_var(VariablesParsing::single_var_section());
     static VariableFactoryBasic<PressureFEVariable>
       grins_factory_press_fe_var(VariablesParsing::pressure_section());
     static VariableFactoryBasic<PrimitiveTempFEVariables>
       grins_factory_temp_fe_var(VariablesParsing::temperature_section());
     static SpeciesVariableFactory<SpeciesMassFractionsVariable>
       grins_factory_species_mass_frac_fe_var(VariablesParsing::species_mass_fractions_section());
     static ScalarVariableFactory<ThermoPressureVariable>
       grins_factory_thermo_press_fe_var(VariablesParsing::thermo_pressure_section());
     static VariableFactoryBasic<TurbulenceFEVariables>
       grins_factory_turb_fe_var(VariablesParsing::turbulence_section());
     static VariableFactoryBasic<VelocityVariable>
       grins_factory_velocity_fe_var(VariablesParsing::velocity_section());
     static ScalarVariableFactory<ScalarVariable>
       grins_factory_scalar_var(VariablesParsing::scalar_var_section());
   }
GRINS::VariableFactoryInitializer::~VariableFactoryInitializer () inline
Definition at line 39 of file variable_factory_initializer.h.
 {}
The documentation for this class was generated from the following files:
src/variables/include/grins/variable_factory_initializer.h
src/variables/src/variable_factory_initializer.C