GRINS-0.8.0: GRINSTesting::AntiochConstantTransportMixtureBuilderTest Class Reference
GRINSTesting::AntiochConstantTransportMixtureBuilderTest Class Reference
Public Member Functions
CPPUNIT_TEST_SUITE (AntiochConstantTransportMixtureBuilderTest)
CPPUNIT_TEST (test_build_constant_viscosity)
CPPUNIT_TEST (test_build_constant_conductivity)
CPPUNIT_TEST (test_build_constant_prandtl_conductivity)
CPPUNIT_TEST (test_build_constant_lewis_diff)
CPPUNIT_TEST (test_build_cea_constcond_mix)
CPPUNIT_TEST (test_build_cea_constpr_mix)
CPPUNIT_TEST_SUITE_END ()
void setUp ()
void test_build_constant_viscosity ()
void test_build_constant_conductivity ()
void test_build_constant_prandtl_conductivity ()
void test_build_constant_lewis_diff ()
void test_build_cea_constcond_mix ()
void test_build_cea_constpr_mix ()
Private Attributes
libMesh::UniquePtr< GetPot > _input
Detailed Description
Definition at line 133 of file antioch_mixture_builder_test.C.
Member Function Documentation
GRINSTesting::AntiochConstantTransportMixtureBuilderTest::CPPUNIT_TEST (test_build_constant_viscosity)
GRINSTesting::AntiochConstantTransportMixtureBuilderTest::CPPUNIT_TEST (test_build_constant_conductivity)
GRINSTesting::AntiochConstantTransportMixtureBuilderTest::CPPUNIT_TEST (test_build_constant_prandtl_conductivity)
GRINSTesting::AntiochConstantTransportMixtureBuilderTest::CPPUNIT_TEST (test_build_constant_lewis_diff)
GRINSTesting::AntiochConstantTransportMixtureBuilderTest::CPPUNIT_TEST (test_build_cea_constcond_mix)
GRINSTesting::AntiochConstantTransportMixtureBuilderTest::CPPUNIT_TEST (test_build_cea_constpr_mix)
GRINSTesting::AntiochConstantTransportMixtureBuilderTest::CPPUNIT_TEST_SUITE (AntiochConstantTransportMixtureBuilderTest)
GRINSTesting::AntiochConstantTransportMixtureBuilderTest::CPPUNIT_TEST_SUITE_END ()
void GRINSTesting::AntiochConstantTransportMixtureBuilderTest::setUp () inline
Definition at line 149 of file antioch_mixture_builder_test.C.
References _input.
     {
       std::string input_file = std::string(GRINS_TEST_SRCDIR)+"/input_files/antioch.in";
       _input.reset( new GetPot(input_file) );
     }
void GRINSTesting::AntiochConstantTransportMixtureBuilderTest::test_build_cea_constcond_mix () inline
Definition at line 214 of file antioch_mixture_builder_test.C.
References _input, and GRINS::AntiochConstantTransportMixtureBuilder::build_mixture().
     {
       GRINS::AntiochConstantTransportMixtureBuilder builder;
       libMesh::UniquePtr<GRINS::AntiochConstantTransportMixture<Antioch::CEACurveFit<libMesh::Real>,
                                                                 GRINS::ConstantConductivity> >
         mixture = builder.build_mixture<Antioch::CEACurveFit<libMesh::Real>,GRINS::ConstantConductivity>
         (*_input, "TestMaterial");
       libMesh::Real mu = mixture->mu();
       libMesh::Real k = (mixture->conductivity())();
       libMesh::Real rho = 1.2;
       libMesh::Real cp = 2.3;
       libMesh::Real Le = 1.4;
       libMesh::Real D = mixture->diffusivity().D(rho,cp,k);
       libMesh::Real D_exact = k/rho/cp/Le;
       CPPUNIT_ASSERT_DOUBLES_EQUAL( 3.14, mu, std::numeric_limits<libMesh::Real>::epsilon() );
       CPPUNIT_ASSERT_DOUBLES_EQUAL( 2.71, k, std::numeric_limits<libMesh::Real>::epsilon() );
       CPPUNIT_ASSERT_DOUBLES_EQUAL( D_exact, D, std::numeric_limits<libMesh::Real>::epsilon() );
     }
void GRINSTesting::AntiochConstantTransportMixtureBuilderTest::test_build_cea_constpr_mix () inline
Definition at line 240 of file antioch_mixture_builder_test.C.
References _input, and GRINS::AntiochConstantTransportMixtureBuilder::build_mixture().
     {
       GRINS::AntiochConstantTransportMixtureBuilder builder;
       libMesh::UniquePtr<GRINS::AntiochConstantTransportMixture<Antioch::CEACurveFit<libMesh::Real>,
                                                                 GRINS::ConstantPrandtlConductivity> >
         mixture = builder.build_mixture<Antioch::CEACurveFit<libMesh::Real>,GRINS::ConstantPrandtlConductivity>
         (*_input, "TestMaterial");
       libMesh::Real mu = mixture->mu();
       libMesh::Real cp = 2.3;
       libMesh::Real Pr = 0.7;
       libMesh::Real k = (mixture->conductivity())(mu, cp);
       libMesh::Real k_exact = mu*cp/Pr;
       libMesh::Real rho = 1.2;
       libMesh::Real Le = 1.4;
       libMesh::Real D = mixture->diffusivity().D(rho,cp,k);
       libMesh::Real D_exact = k/rho/cp/Le;
       CPPUNIT_ASSERT_DOUBLES_EQUAL( 3.14, mu, std::numeric_limits<libMesh::Real>::epsilon() );
       CPPUNIT_ASSERT_DOUBLES_EQUAL( k_exact, k, std::numeric_limits<libMesh::Real>::epsilon() );
       CPPUNIT_ASSERT_DOUBLES_EQUAL( D_exact, D, std::numeric_limits<libMesh::Real>::epsilon() );
     }
void GRINSTesting::AntiochConstantTransportMixtureBuilderTest::test_build_constant_conductivity () inline
Definition at line 167 of file antioch_mixture_builder_test.C.
References _input, and GRINS::AntiochConstantTransportMixtureBuilder::build_constant_conductivity().
     {
       GRINS::AntiochConstantTransportMixtureBuilder builder;
       libMesh::UniquePtr<GRINS::ConstantConductivity> conductivity =
         builder.build_constant_conductivity<GRINS::ConstantConductivity>( *_input, "TestMaterial" );
       libMesh::Real k = (*conductivity)();
       CPPUNIT_ASSERT_DOUBLES_EQUAL( 2.71, k, std::numeric_limits<libMesh::Real>::epsilon() );
     }
void GRINSTesting::AntiochConstantTransportMixtureBuilderTest::test_build_constant_lewis_diff () inline
Definition at line 195 of file antioch_mixture_builder_test.C.
References _input, and GRINS::AntiochConstantTransportMixtureBuilder::build_constant_lewis_diff().
     {
       GRINS::AntiochConstantTransportMixtureBuilder builder;
       libMesh::UniquePtr<Antioch::ConstantLewisDiffusivity<libMesh::Real> > diff =
         builder.build_constant_lewis_diff( *_input, "TestMaterial" );
       libMesh::Real rho = 1.2;
       libMesh::Real cp = 2.3;
       libMesh::Real k = 3.4;
       libMesh::Real Le = 1.4;
       libMesh::Real D = diff->D(rho,cp,k);
       libMesh::Real D_exact = k/rho/cp/Le;
       CPPUNIT_ASSERT_DOUBLES_EQUAL( D_exact, D, std::numeric_limits<libMesh::Real>::epsilon() );
     }
void GRINSTesting::AntiochConstantTransportMixtureBuilderTest::test_build_constant_prandtl_conductivity () inline
Definition at line 179 of file antioch_mixture_builder_test.C.
References _input, and GRINS::AntiochConstantTransportMixtureBuilder::build_constant_conductivity().
     {
       GRINS::AntiochConstantTransportMixtureBuilder builder;
       libMesh::UniquePtr<GRINS::ConstantPrandtlConductivity> conductivity =
         builder.build_constant_conductivity<GRINS::ConstantPrandtlConductivity>( *_input, "TestMaterial" );
       libMesh::Real mu = 1.2;
       libMesh::Real cp = 2.3;
       libMesh::Real Pr = 0.7;
       libMesh::Real k = (*conductivity)( mu, cp );
       libMesh::Real k_exact = mu*cp/Pr;
       CPPUNIT_ASSERT_DOUBLES_EQUAL( k_exact, k, std::numeric_limits<libMesh::Real>::epsilon() );
     }
void GRINSTesting::AntiochConstantTransportMixtureBuilderTest::test_build_constant_viscosity () inline
Definition at line 155 of file antioch_mixture_builder_test.C.
References _input, and GRINS::AntiochConstantTransportMixtureBuilder::build_constant_viscosity().
     {
       GRINS::AntiochConstantTransportMixtureBuilder builder;
       libMesh::UniquePtr<GRINS::ConstantViscosity> visc =
         builder.build_constant_viscosity( *_input, "TestMaterial" );
       libMesh::Real mu = (*visc)();
       CPPUNIT_ASSERT_DOUBLES_EQUAL( 3.14, mu, std::numeric_limits<libMesh::Real>::epsilon() );
     }
Member Data Documentation
libMesh::UniquePtr<GetPot> GRINSTesting::AntiochConstantTransportMixtureBuilderTest::_input private
Definition at line 270 of file antioch_mixture_builder_test.C.
Referenced by setUp(), test_build_cea_constcond_mix(), test_build_cea_constpr_mix(), test_build_constant_conductivity(), test_build_constant_lewis_diff(), test_build_constant_prandtl_conductivity(), and test_build_constant_viscosity().
The documentation for this class was generated from the following file:
test/interface/antioch_mixture_builder_test.C