GRINS-0.6.0: GRINS::CanteraEvaluator Class Reference
GRINS::CanteraEvaluator Class Reference
Wrapper class for evaluating thermochemistry and transport properties using Cantera.
#include <cantera_evaluator.h>
Public Member Functions
CanteraEvaluator (CanteraMixture &mixture)
~CanteraEvaluator ()
libMesh::Real M (unsigned int species) const
libMesh::Real M_mix (const std::vector< libMesh::Real > &mass_fractions) const
libMesh::Real R (unsigned int species) const
libMesh::Real R_mix (const std::vector< libMesh::Real > &mass_fractions) const
libMesh::Real X (unsigned int species, libMesh::Real M, libMesh::Real mass_fraction) const
void X (libMesh::Real M, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &mole_fractions) const
unsigned int species_index (const std::string &species_name) const
std::string species_name (unsigned int species_index) const
libMesh::Real cp (const CachedValues &cache, unsigned int qp) const
libMesh::Real cv (const CachedValues &cache, unsigned int qp) const
libMesh::Real h_s (const CachedValues &cache, unsigned int qp, unsigned int species) const
void h_s (const CachedValues &cache, unsigned int qp, std::vector< libMesh::Real > &h) const
libMesh::Real h_s (const libMesh::Real &T, unsigned int species)
libMesh::Real mu (const CachedValues &cache, unsigned int qp) const
libMesh::Real k (const CachedValues &cache, unsigned int qp) const
void mu_and_k (const CachedValues &cache, unsigned int qp, libMesh::Real &mu, libMesh::Real &k)
void D (const CachedValues &cache, unsigned int qp, std::vector< libMesh::Real > &D) const
void omega_dot (const CachedValues &cache, unsigned int qp, std::vector< libMesh::Real > &omega_dot) const
void omega_dot (const libMesh::Real &T, libMesh::Real rho, const std::vector< libMesh::Real > mass_fractions, std::vector< libMesh::Real > &omega_dot)
libMesh::Real cp (const libMesh::Real &, const std::vector< libMesh::Real > &)
libMesh::Real mu (const libMesh::Real &, const std::vector< libMesh::Real > &)
libMesh::Real k (const libMesh::Real &, const std::vector< libMesh::Real > &)
void D (const libMesh::Real, const libMesh::Real, const libMesh::Real, std::vector< libMesh::Real > &)
Protected Attributes
CanteraMixture & _chem
CanteraThermodynamics _thermo
CanteraTransport _transport
CanteraKinetics _kinetics
Private Member Functions
CanteraEvaluator ()
Detailed Description
Wrapper class for evaluating thermochemistry and transport properties using Cantera.
This class is expected to be constructed after threads have been forked and will only live during the lifetime of the thread. Note that this documentation will always be built regardless if Cantera is included in the GRINS build or not. Check configure output to confirm that Cantera was included in the build if you wish to use it.
Definition at line 48 of file cantera_evaluator.h.
Constructor & Destructor Documentation
GRINS::CanteraEvaluator::CanteraEvaluator (CanteraMixture & mixture)
Definition at line 39 of file cantera_evaluator.C.
     : _chem( mixture ),
       _thermo( CanteraThermodynamics(mixture) ),
       _transport( CanteraTransport(mixture) ),
       _kinetics( CanteraKinetics(mixture) )
   {
     return;
   }
GRINS::CanteraEvaluator::~CanteraEvaluator ()
Definition at line 48 of file cantera_evaluator.C.
   {
     return;
   }
GRINS::CanteraEvaluator::CanteraEvaluator () private
Member Function Documentation
libMesh::Real GRINS::CanteraEvaluator::cp (const CachedValues & cache, unsigned int qp) const inline
Definition at line 201 of file cantera_evaluator.h.
References _thermo, and GRINS::CanteraThermodynamics::cp().
Referenced by main().
   {
     return _thermo.cp(cache,qp);
   }
libMesh::Real GRINS::CanteraEvaluator::cp (const libMesh::Real & , const std::vector< libMesh::Real > &) inline
Definition at line 103 of file cantera_evaluator.h.
     {
       libmesh_not_implemented();
       return 0.0;
     }
libMesh::Real GRINS::CanteraEvaluator::cv (const CachedValues & cache, unsigned int qp) const inline
Definition at line 207 of file cantera_evaluator.h.
References _thermo, and GRINS::CanteraThermodynamics::cv().
Referenced by main().
   {
     return _thermo.cv(cache,qp);
   }
void GRINS::CanteraEvaluator::D (const CachedValues & cache, unsigned int qp, std::vector< libMesh::Real > & D) const inline
Definition at line 253 of file cantera_evaluator.h.
References _transport, and GRINS::CanteraTransport::D().
Referenced by main().
   {
     return _transport.D(cache,qp,D);
   }
void GRINS::CanteraEvaluator::D (const libMesh::Real , const libMesh::Real , const libMesh::Real , std::vector< libMesh::Real > &) inline
Definition at line 124 of file cantera_evaluator.h.
     {
       libmesh_not_implemented();
       return;
     }
libMesh::Real GRINS::CanteraEvaluator::h_s (const CachedValues & cache, unsigned int qp, unsigned int species) const inline
Definition at line 213 of file cantera_evaluator.h.
References _thermo, and GRINS::CanteraThermodynamics::h().
Referenced by main().
   {
     return _thermo.h(cache,qp,species);
   }
void GRINS::CanteraEvaluator::h_s (const CachedValues & cache, unsigned int qp, std::vector< libMesh::Real > & h) const inline
Definition at line 219 of file cantera_evaluator.h.
References _thermo, and GRINS::CanteraThermodynamics::h().
   {
     _thermo.h(cache,qp,h);
     return;
   }
libMesh::Real GRINS::CanteraEvaluator::h_s (const libMesh::Real & T, unsigned int species) inline
Definition at line 226 of file cantera_evaluator.h.
References _thermo, and GRINS::CanteraThermodynamics::h().
   {
     return _thermo.h(T,species);
   }
libMesh::Real GRINS::CanteraEvaluator::k (const CachedValues & cache, unsigned int qp) const inline
Definition at line 238 of file cantera_evaluator.h.
References _transport, and GRINS::CanteraTransport::k().
Referenced by main().
   {
     return _transport.k(cache,qp);
   }
libMesh::Real GRINS::CanteraEvaluator::k (const libMesh::Real & , const std::vector< libMesh::Real > &) inline
Definition at line 117 of file cantera_evaluator.h.
     {
       libmesh_not_implemented();
       return 0.0;
     }
libMesh::Real GRINS::CanteraEvaluator::M (unsigned int species) const inline
Definition at line 151 of file cantera_evaluator.h.
References _chem, and GRINS::CanteraMixture::M().
   {
     return _chem.M(species);
   }
libMesh::Real GRINS::CanteraEvaluator::M_mix (const std::vector< libMesh::Real > & mass_fractions) const inline
Definition at line 157 of file cantera_evaluator.h.
References _chem, and GRINS::CanteraMixture::M_mix().
   {
     return _chem.M_mix(mass_fractions);
   }
libMesh::Real GRINS::CanteraEvaluator::mu (const CachedValues & cache, unsigned int qp) const inline
Definition at line 232 of file cantera_evaluator.h.
References _transport, and GRINS::CanteraTransport::mu().
Referenced by main().
   {
     return _transport.mu(cache,qp);
   }
libMesh::Real GRINS::CanteraEvaluator::mu (const libMesh::Real & , const std::vector< libMesh::Real > &) inline
Definition at line 110 of file cantera_evaluator.h.
     {
       libmesh_not_implemented();
       return 0.0;
     }
void GRINS::CanteraEvaluator::mu_and_k (const CachedValues & cache, unsigned int qp, libMesh::Real & mu, libMesh::Real & k) inline
Definition at line 244 of file cantera_evaluator.h.
References _transport, GRINS::CanteraTransport::k(), and GRINS::CanteraTransport::mu().
   {
     mu = _transport.mu(cache,qp);
     k = _transport.k(cache,qp);
     return;
   }
void GRINS::CanteraEvaluator::omega_dot (const CachedValues & cache, unsigned int qp, std::vector< libMesh::Real > & omega_dot) const inline
Definition at line 260 of file cantera_evaluator.h.
References _kinetics, and GRINS::CanteraKinetics::omega_dot().
Referenced by main().
   {
     return _kinetics.omega_dot(cache,qp,omega_dot);
   }
void GRINS::CanteraEvaluator::omega_dot (const libMesh::Real & T, libMesh::Real rho, const std::vector< libMesh::Real > mass_fractions, std::vector< libMesh::Real > & omega_dot) inline
Definition at line 267 of file cantera_evaluator.h.
References _kinetics, and GRINS::CanteraKinetics::omega_dot_TRY().
   {
     return _kinetics.omega_dot_TRY(T,rho,mass_fractions,omega_dot);
   }
libMesh::Real GRINS::CanteraEvaluator::R (unsigned int species) const inline
Definition at line 163 of file cantera_evaluator.h.
References _chem, and GRINS::CanteraMixture::R().
   {
     return _chem.R(species);
   }
libMesh::Real GRINS::CanteraEvaluator::R_mix (const std::vector< libMesh::Real > & mass_fractions) const inline
Definition at line 169 of file cantera_evaluator.h.
References _chem, and GRINS::CanteraMixture::R_mix().
   {
     return _chem.R_mix(mass_fractions);
   }
unsigned int GRINS::CanteraEvaluator::species_index (const std::string & species_name) const inline
Definition at line 189 of file cantera_evaluator.h.
References _chem, and GRINS::CanteraMixture::species_index().
   {
     return _chem.species_index(species_name);
   }
std::string GRINS::CanteraEvaluator::species_name (unsigned int species_index) const inline
Definition at line 195 of file cantera_evaluator.h.
References _chem, and GRINS::CanteraMixture::species_name().
   {
     return _chem.species_name(species_index);
   }
libMesh::Real GRINS::CanteraEvaluator::X (unsigned int species, libMesh::Real M, libMesh::Real mass_fraction) const inline
Definition at line 175 of file cantera_evaluator.h.
References _chem, and GRINS::CanteraMixture::X().
   {
     return _chem.X(species,M,mass_fraction);
   }
void GRINS::CanteraEvaluator::X (libMesh::Real M, const std::vector< libMesh::Real > & mass_fractions, std::vector< libMesh::Real > & mole_fractions) const inline
Definition at line 181 of file cantera_evaluator.h.
References _chem, and GRINS::CanteraMixture::X().
   {
     _chem.X(M,mass_fractions,mole_fractions);
     return;
   }
Member Data Documentation
CanteraMixture& GRINS::CanteraEvaluator::_chem protected
Definition at line 135 of file cantera_evaluator.h.
Referenced by M(), M_mix(), R(), R_mix(), species_index(), species_name(), and X().
CanteraKinetics GRINS::CanteraEvaluator::_kinetics protected
Definition at line 141 of file cantera_evaluator.h.
Referenced by omega_dot().
CanteraThermodynamics GRINS::CanteraEvaluator::_thermo protected
Definition at line 137 of file cantera_evaluator.h.
Referenced by cp(), cv(), and h_s().
CanteraTransport GRINS::CanteraEvaluator::_transport protected
Definition at line 139 of file cantera_evaluator.h.
Referenced by D(), k(), mu(), and mu_and_k().
The documentation for this class was generated from the following files:
src/properties/include/grins/cantera_evaluator.h
src/properties/src/cantera_evaluator.C