GRINS-0.8.0: GRINS::AntiochMixture< KineticsThermoCurveFit > Class Template Reference
GRINS::AntiochMixture< KineticsThermoCurveFit > Class Template Reference
Wrapper class for storing state for Antioch thermo and kinetics.
#include <antioch_kinetics.h>
Public Member Functions
AntiochMixture (const GetPot &input, const std::string &material)
Deprecated Constructor.
AntiochMixture (libMesh::UniquePtr< Antioch::ChemicalMixture< libMesh::Real > > &chem_mixture, libMesh::UniquePtr< Antioch::ReactionSet< libMesh::Real > > &reaction_set, libMesh::UniquePtr< Antioch::NASAThermoMixture< libMesh::Real, KineticsThermoCurveFit > > &nasa_mixture, libMesh::Real min_T=-std::numeric_limits< libMesh::Real >::max(), bool clip_negative_rho=false)
Constructor with user-built objects.
virtual ~AntiochMixture ()
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
const Antioch::ReactionSet< libMesh::Real > & reaction_set () const
const Antioch::NASAThermoMixture< libMesh::Real, KineticsThermoCurveFit > & nasa_mixture () const
libMesh::Real h_stat_mech_ref_correction (unsigned int species) const
libMesh::Real minimum_T () const
bool clip_negative_rho () const
Public Member Functions inherited from GRINS::AntiochChemistry
AntiochChemistry (const GetPot &input, const std::string &material)
Deprecated Constructor.
AntiochChemistry (libMesh::UniquePtr< Antioch::ChemicalMixture< libMesh::Real > > &chem_mixture)
User passes in built ChemicalMixture and this class takes ownership.
virtual ~AntiochChemistry ()
libMesh::Real M (unsigned int species) const
Species molar mass (molecular weight), [kg/mol].
libMesh::Real M_mix (const std::vector< libMesh::Real > &mass_fractions) const
Mixture molar mass (molecular weight), [kg/mol].
libMesh::Real R (unsigned int species) const
Species gas constant, [J/kg-K].
libMesh::Real R_mix (const std::vector< libMesh::Real > &mass_fractions) const
Mixture gas constant, [J/kg-K].
libMesh::Real X (unsigned int species, libMesh::Real M, libMesh::Real mass_fraction) const
Species mole fraction, unitless.
void X (libMesh::Real M, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &mole_fractions) const
Mole fraction for all species, unitless.
libMesh::Real molar_density (const unsigned int species, const libMesh::Real rho, const libMesh::Real mass_fraction) const
Species molar density, [mol/m^3].
void molar_densities (const libMesh::Real rho, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &molar_densities) const
Molar density for all species, [mol/m^3].
unsigned int n_species () const
unsigned int species_index (const std::string &species_name) const
std::string species_name (unsigned int species_index) const
const Antioch::ChemicalMixture< libMesh::Real > & chemical_mixture () const
Accessor to underlying Antioch object.
const AntiochChemistry & chemistry () const
Accessor for this class.
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
Protected Member Functions
void build_stat_mech_ref_correction ()
Protected Attributes
libMesh::UniquePtr< Antioch::ReactionSet< libMesh::Real > > _reaction_set
libMesh::UniquePtr< Antioch::NASAThermoMixture< libMesh::Real, KineticsThermoCurveFit > > _nasa_mixture
std::vector< libMesh::Real > _h_stat_mech_ref_correction
libMesh::Real _minimum_T
bool _clip_negative_rho
Protected Attributes inherited from GRINS::AntiochChemistry
libMesh::UniquePtr< Antioch::ChemicalMixture< libMesh::Real > > _antioch_gas
Private Member Functions
AntiochMixture ()
Additional Inherited Members
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Detailed Description
template<typename KineticsThermoCurveFit>
class GRINS::AntiochMixture< KineticsThermoCurveFit >
Wrapper class for storing state for Antioch thermo and kinetics.
This class handles caching needed state for Antioch kinetics, and the thermodynamics required for the kinetics evaluation. Currently, we only support NASA type curve fits for required thermodynamic evaluations, but we template on the curve fit type.
This class is expected to be constructed before threads have been forked and will live during the whole program. By default, Antioch is working in SI units. Note that this documentation will always be built regardless if Antioch is included in the GRINS build or not. Check configure output to confirm that Antioch was included in the build.
Definition at line 48 of file antioch_kinetics.h.
Constructor & Destructor Documentation
template<typename KineticsThermoCurveFit > GRINS::AntiochMixture< KineticsThermoCurveFit >::AntiochMixture (const GetPot & input, const std::string & material)
Deprecated Constructor.
Definition at line 49 of file antioch_mixture.C.
References GRINS::AntiochMixture< KineticsThermoCurveFit >::_nasa_mixture, GRINS::AntiochMixture< KineticsThermoCurveFit >::_reaction_set, GRINS::AntiochMixture< KineticsThermoCurveFit >::build_stat_mech_ref_correction(), and GRINS::MaterialsParsing::parse_chemical_kinetics_datafile_name().
     : AntiochChemistry(input,material),
       _reaction_set( new Antioch::ReactionSet<libMesh::Real>( (*_antioch_gas.get()) ) ),
       _nasa_mixture( new Antioch::NASAThermoMixture<libMesh::Real,KineticsThermoCurveFit>( (*_antioch_gas.get()) ) ),
       _minimum_T( input( "Materials/"+material+"/GasMixture/Antioch/minimum_T", -std::numeric_limits<libMesh::Real>::max() ) ),
       _clip_negative_rho( input( "Materials/"+material+"/GasMixture/Antioch/clip_negative_rho", false) )
   {
     {
       std::string warning = "==============================================\n";
       warning += "WARNING: This AntiochMixture constructor is DEPREACTED!\n";
       warning += "         Prefer alternate constructor where parsing\n";
       warning += "         is done outside this class.\n";
       warning += "==============================================\n";
       libmesh_warning(warning);
     }
     std::string kinetics_data_filename = MaterialsParsing::parse_chemical_kinetics_datafile_name( input, material );
     bool verbose_read = input("screen-options/verbose_kinetics_read", false );
     Antioch::read_reaction_set_data_xml<libMesh::Real>( kinetics_data_filename, verbose_read, *_reaction_set.get() );
     std::string cea_data_filename = input( "Materials/"+material+"/GasMixture/Antioch/cea_data", "default" );
     if( cea_data_filename == std::string("default") )
       cea_data_filename = Antioch::DefaultInstallFilename::thermo_data();
     Antioch::read_nasa_mixture_data( *_nasa_mixture.get(), cea_data_filename, Antioch::ASCII, true );
     this->build_stat_mech_ref_correction();
   }
template<typename KineticsThermoCurveFit> GRINS::AntiochMixture< KineticsThermoCurveFit >::AntiochMixture (libMesh::UniquePtr< Antioch::ChemicalMixture< libMesh::Real > > & chem_mixture, libMesh::UniquePtr< Antioch::ReactionSet< libMesh::Real > > & reaction_set, libMesh::UniquePtr< Antioch::NASAThermoMixture< libMesh::Real, KineticsThermoCurveFit > > & nasa_mixture, libMesh::Real min_T = -std::numeric_limits<libMesh::Real>::max(), bool clip_negative_rho = false)
Constructor with user-built objects.
This constructor expects the user to pass in a ChemicalMixture, ReactionSet, and NASAThermoMixture object already built; this class will take ownership of the pointer.
Todo:
Use std::move when we have C++11
Definition at line 84 of file antioch_mixture.C.
     : AntiochChemistry(chem_mixture),
       _minimum_T(min_T),
       _clip_negative_rho(clip_negative_rho)
   {
     _reaction_set.reset( reaction_set.release() );
     _nasa_mixture.reset( nasa_mixture.release() );
     this->build_stat_mech_ref_correction();
   }
template<typename KineticsThermoCurveFit> virtual GRINS::AntiochMixture< KineticsThermoCurveFit >::~AntiochMixture () inline virtual
Definition at line 83 of file antioch_mixture.h.
 {};
template<typename KineticsThermoCurveFit> GRINS::AntiochMixture< KineticsThermoCurveFit >::AntiochMixture () private
Member Function Documentation
template<typename KineticsThermoCurveFit > void GRINS::AntiochMixture< KineticsThermoCurveFit >::build_stat_mech_ref_correction () protected
Definition at line 116 of file antioch_mixture.C.
Referenced by GRINS::AntiochMixture< KineticsThermoCurveFit >::AntiochMixture().
   {
     Antioch::StatMechThermodynamics<libMesh::Real> thermo( *(this->_antioch_gas.get()) );
     _h_stat_mech_ref_correction.resize(this->n_species());
     for( unsigned int s = 0; s < this->n_species(); s++ )
       {
         _h_stat_mech_ref_correction[s] = -thermo.h_tot( s, 298.15 ) + thermo.e_0(s);
       }
   }
template<typename KineticsThermoCurveFit > bool GRINS::AntiochMixture< KineticsThermoCurveFit >::clip_negative_rho () const inline
Definition at line 174 of file antioch_mixture.h.
   {
     return _clip_negative_rho;
   }
template<typename KineticsThermoCurveFit > libMesh::Real GRINS::AntiochMixture< KineticsThermoCurveFit >::h_stat_mech_ref_correction (unsigned int species) const inline
Definition at line 160 of file antioch_mixture.h.
   {
     return _h_stat_mech_ref_correction[species];
   }
template<typename KineticsThermoCurveFit > libMesh::Real GRINS::AntiochMixture< KineticsThermoCurveFit >::minimum_T () const inline
Definition at line 167 of file antioch_mixture.h.
   {
     return _minimum_T;
   }
template<typename KineticsThermoCurveFit > const Antioch::NASAThermoMixture< libMesh::Real, KineticsThermoCurveFit > & GRINS::AntiochMixture< KineticsThermoCurveFit >::nasa_mixture () const inline
Definition at line 152 of file antioch_mixture.h.
Referenced by GRINS::AntiochEvaluator< Antioch::CEACurveFit< libMesh::Real >, Thermo >::specialized_build_thermo(), and GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_thermo().
   {
     return *_nasa_mixture.get();
   }
template<typename KineticsThermoCurveFit > const Antioch::ReactionSet< libMesh::Real > & GRINS::AntiochMixture< KineticsThermoCurveFit >::reaction_set () const inline
Definition at line 144 of file antioch_mixture.h.
   {
     return *_reaction_set.get();
   }
template<typename KineticsThermoCurveFit > void GRINS::AntiochMixture< KineticsThermoCurveFit >::register_parameter (const std::string & param_name, libMesh::ParameterMultiAccessor< libMesh::Number > & param_pointer) const virtual
Each subclass will register its copy of an independent.
Reimplemented from GRINS::ParameterUser.
Definition at line 102 of file antioch_mixture.C.
References GRINS::ParameterUser::register_parameter().
   {
     // Use common code for any GRINS parameters
     AntiochChemistry::register_parameter(param_name, param_pointer);
     // Create a special setter/getter for any Antioch-only parameters
     if (param_name.find("Antioch") == 0) // name starts with Antioch
       param_pointer.push_back
         (ParameterAntiochReset
          (*this->_reaction_set.get(), param_name));
   }
Member Data Documentation
template<typename KineticsThermoCurveFit> bool GRINS::AntiochMixture< KineticsThermoCurveFit >::_clip_negative_rho protected
Definition at line 132 of file antioch_mixture.h.
template<typename KineticsThermoCurveFit> std::vector<libMesh::Real> GRINS::AntiochMixture< KineticsThermoCurveFit >::_h_stat_mech_ref_correction protected
Definition at line 112 of file antioch_mixture.h.
template<typename KineticsThermoCurveFit> libMesh::Real GRINS::AntiochMixture< KineticsThermoCurveFit >::_minimum_T protected
Definition at line 123 of file antioch_mixture.h.
template<typename KineticsThermoCurveFit> libMesh::UniquePtr<Antioch::NASAThermoMixture<libMesh::Real,KineticsThermoCurveFit> > GRINS::AntiochMixture< KineticsThermoCurveFit >::_nasa_mixture protected
Definition at line 110 of file antioch_mixture.h.
Referenced by GRINS::AntiochMixture< KineticsThermoCurveFit >::AntiochMixture().
template<typename KineticsThermoCurveFit> libMesh::UniquePtr<Antioch::ReactionSet<libMesh::Real> > GRINS::AntiochMixture< KineticsThermoCurveFit >::_reaction_set protected
Definition at line 108 of file antioch_mixture.h.
Referenced by GRINS::AntiochMixture< KineticsThermoCurveFit >::AntiochMixture().
The documentation for this class was generated from the following files:
src/properties/include/grins/antioch_kinetics.h
src/properties/include/grins/antioch_mixture.h
src/properties/src/antioch_mixture.C