GRINS-0.8.0: GRINS::AssemblyContext Class Reference
GRINS::AssemblyContext Class Reference
#include <assembly_context.h>
Public Member Functions
AssemblyContext (const libMesh::System &system)
~AssemblyContext ()
CachedValues & get_cached_values ()
const CachedValues & get_cached_values () const
Protected Attributes
CachedValues _cached_values
Detailed Description
Definition at line 37 of file assembly_context.h.
Constructor & Destructor Documentation
GRINS::AssemblyContext::AssemblyContext (const libMesh::System & system)
Definition at line 30 of file assembly_context.C.
     : libMesh::FEMContext(system)
   {
     return;
   }
GRINS::AssemblyContext::~AssemblyContext ()
Definition at line 36 of file assembly_context.C.
   {
     return;
   }
Member Function Documentation
CachedValues& GRINS::AssemblyContext::get_cached_values () inline
Definition at line 44 of file assembly_context.h.
References _cached_values.
Referenced by GRINS::MultiphysicsSystem::_general_residual(), GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::compute_element_time_derivative_cache(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::compute_element_time_derivative_cache(), GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::element_time_derivative(), and GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::element_time_derivative().
     { return _cached_values; }
const CachedValues& GRINS::AssemblyContext::get_cached_values () const inline
Definition at line 47 of file assembly_context.h.
References _cached_values.
     { return _cached_values; }
Member Data Documentation
CachedValues GRINS::AssemblyContext::_cached_values protected
Definition at line 52 of file assembly_context.h.
Referenced by get_cached_values().
The documentation for this class was generated from the following files:
src/physics/include/grins/assembly_context.h
src/physics/src/assembly_context.C