GRINS-0.8.0: GRINS::BuilderHelper Class Reference
GRINS::BuilderHelper Class Reference
This class contains common functions used by various Builders throughout GRINS.
#include <builder_helper.h>
Public Member Functions
BuilderHelper ()
~BuilderHelper ()
Static Public Member Functions
static void parse_var_sections (const GetPot &input, std::set< std::string > &sections)
Parses the input file for [Variables] first-level subsections.
static void parse_var_sections_vector (const GetPot &input, std::vector< std::string > &sections)
The same as parse_var_sections, except the result is returned in an std::vector.
Detailed Description
This class contains common functions used by various Builders throughout GRINS.
Definition at line 39 of file builder_helper.h.
Constructor & Destructor Documentation
GRINS::BuilderHelper::BuilderHelper () inline
Definition at line 42 of file builder_helper.h.
 {}
GRINS::BuilderHelper::~BuilderHelper () inline
Definition at line 43 of file builder_helper.h.
 {}
Member Function Documentation
void GRINS::BuilderHelper::parse_var_sections (const GetPot & input, std::set< std::string > & sections) static
Parses the input file for [Variables] first-level subsections.
The expected format for the Variables is
 [Variables]
 [./Displacement]
 fe_family = '...'
 order = '...'
 names = '...'
 [../]
 [./Velocity]
 ...
 [../]
 [../]
For the example above, this function will fill 'sections' with "Displacement" and "Velocity".
The result is return in an std::set so the actual ordering from the input file is lost.
Definition at line 40 of file builder_helper.C.
References parse_var_sections_vector().
Referenced by GRINS::DefaultBCBuilder::build_bcs(), and GRINSTesting::BuilderHelperTest::test_parse_var_sections().
   {
     std::vector<std::string> sec_vec;
     parse_var_sections_vector(input,sec_vec);
     // Now convert populated vector to a set
     for(std::vector<std::string>::const_iterator it = sec_vec.begin();
         it != sec_vec.end(); ++it )
       sections.insert(*it);
   }
void GRINS::BuilderHelper::parse_var_sections_vector (const GetPot & input, std::vector< std::string > & sections) static
The same as parse_var_sections, except the result is returned in an std::vector.
This allows the maintaining of the order of the Variable subsection in the input file. This is important for things like setting up the Variables in the System so that the user can control the order the variables are added to the system.
Definition at line 52 of file builder_helper.C.
References GRINS::VariablesParsing::variables_section().
Referenced by GRINS::DefaultVariableBuilder::build_variables_impl(), GRINS::ConstrainedPoints::ConstrainedPoints(), and parse_var_sections().
   {
     if( !input.have_section(VariablesParsing::variables_section()) )
       libmesh_error_msg("ERROR: Could not find "+VariablesParsing::variables_section()+" section!");
     // We need to extract all the Variable subsections from the input file
     sections = input.get_subsection_names(VariablesParsing::variables_section());
     // Make sure we found some variable subsections
     if( sections.empty() )
       libmesh_error_msg("ERROR: Did not find any Variable subsections!");
   }
The documentation for this class was generated from the following files:
src/common/include/grins/builder_helper.h
src/common/src/builder_helper.C