GRINS-0.8.0: GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity > Class Template Reference
GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity > Class Template Reference
Wrapper class for storing state for computing Wilke transport properties using Antioch.
#include <antioch_mixture_averaged_transport_mixture.h>
Public Types
typedef AntiochChemistry ChemistryParent
Public Member Functions
AntiochMixtureAveragedTransportMixture (const GetPot &input, const std::string &material)
Deprecated Constructor.
AntiochMixtureAveragedTransportMixture (libMesh::UniquePtr< Antioch::ChemicalMixture< libMesh::Real > > &chem_mixture, libMesh::UniquePtr< Antioch::ReactionSet< libMesh::Real > > &reaction_set, libMesh::UniquePtr< Antioch::NASAThermoMixture< libMesh::Real, KineticsThermoCurveFit > > &kinetics_thermo_mix, libMesh::UniquePtr< Antioch::TransportMixture< libMesh::Real > > &trans_mix, libMesh::UniquePtr< Antioch::MixtureAveragedTransportMixture< libMesh::Real > > &wilke_mix, libMesh::UniquePtr< Antioch::MixtureViscosity< Viscosity, libMesh::Real > > &visc, libMesh::UniquePtr< Antioch::MixtureDiffusion< Diffusivity, libMesh::Real > > &diff, libMesh::Real min_T=-std::numeric_limits< libMesh::Real >::max(), bool clip_negative_rho=false)
Constructor with user-built objects.
virtual ~AntiochMixtureAveragedTransportMixture ()
const Antioch::MixtureAveragedTransportMixture< libMesh::Real > & wilke_mixture () const
const Antioch::MixtureViscosity< Viscosity, libMesh::Real > & viscosity () const
const Antioch::MixtureConductivity< Conductivity, libMesh::Real > & conductivity () const
const Antioch::MixtureDiffusion< Diffusivity, libMesh::Real > & diffusivity () const
Public Member Functions inherited from GRINS::AntiochMixture< KineticsThermoCurveFit >
AntiochMixture (const GetPot &input, const std::string &material)
Deprecated Constructor.
AntiochMixture (libMesh::UniquePtr< Antioch::ChemicalMixture< libMesh::Real > > &chem_mixture, libMesh::UniquePtr< Antioch::ReactionSet< libMesh::Real > > &reaction_set, libMesh::UniquePtr< Antioch::NASAThermoMixture< libMesh::Real, KineticsThermoCurveFit > > &nasa_mixture, libMesh::Real min_T=-std::numeric_limits< libMesh::Real >::max(), bool clip_negative_rho=false)
Constructor with user-built objects.
virtual ~AntiochMixture ()
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
const Antioch::ReactionSet< libMesh::Real > & reaction_set () const
const Antioch::NASAThermoMixture< libMesh::Real, KineticsThermoCurveFit > & nasa_mixture () const
libMesh::Real h_stat_mech_ref_correction (unsigned int species) const
libMesh::Real minimum_T () const
bool clip_negative_rho () const
Public Member Functions inherited from GRINS::AntiochChemistry
AntiochChemistry (const GetPot &input, const std::string &material)
Deprecated Constructor.
AntiochChemistry (libMesh::UniquePtr< Antioch::ChemicalMixture< libMesh::Real > > &chem_mixture)
User passes in built ChemicalMixture and this class takes ownership.
virtual ~AntiochChemistry ()
libMesh::Real M (unsigned int species) const
Species molar mass (molecular weight), [kg/mol].
libMesh::Real M_mix (const std::vector< libMesh::Real > &mass_fractions) const
Mixture molar mass (molecular weight), [kg/mol].
libMesh::Real R (unsigned int species) const
Species gas constant, [J/kg-K].
libMesh::Real R_mix (const std::vector< libMesh::Real > &mass_fractions) const
Mixture gas constant, [J/kg-K].
libMesh::Real X (unsigned int species, libMesh::Real M, libMesh::Real mass_fraction) const
Species mole fraction, unitless.
void X (libMesh::Real M, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &mole_fractions) const
Mole fraction for all species, unitless.
libMesh::Real molar_density (const unsigned int species, const libMesh::Real rho, const libMesh::Real mass_fraction) const
Species molar density, [mol/m^3].
void molar_densities (const libMesh::Real rho, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &molar_densities) const
Molar density for all species, [mol/m^3].
unsigned int n_species () const
unsigned int species_index (const std::string &species_name) const
std::string species_name (unsigned int species_index) const
const Antioch::ChemicalMixture< libMesh::Real > & chemical_mixture () const
Accessor to underlying Antioch object.
const AntiochChemistry & chemistry () const
Accessor for this class.
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
Protected Member Functions
void build_thermo ()
void build_viscosity (const GetPot &input, const std::string &material)
void build_conductivity ()
void build_diffusivity (const GetPot &input, const std::string &material)
Protected Member Functions inherited from GRINS::AntiochMixture< KineticsThermoCurveFit >
void build_stat_mech_ref_correction ()
Protected Attributes
libMesh::UniquePtr< Antioch::TransportMixture< libMesh::Real > > _trans_mixture
libMesh::UniquePtr< Antioch::MixtureAveragedTransportMixture< libMesh::Real > > _wilke_mixture
libMesh::UniquePtr< Thermo > _thermo
libMesh::UniquePtr< Antioch::NASAEvaluator< libMesh::Real, KineticsThermoCurveFit > > _nasa_evaluator
For some Thermo types, we also need to cache a NASAEvaluator.
libMesh::UniquePtr< Antioch::MixtureViscosity< Viscosity, libMesh::Real > > _viscosity
libMesh::UniquePtr< Antioch::MixtureConductivity< Conductivity, libMesh::Real > > _conductivity
libMesh::UniquePtr< Antioch::MixtureDiffusion< Diffusivity, libMesh::Real > > _diffusivity
Protected Attributes inherited from GRINS::AntiochMixture< KineticsThermoCurveFit >
libMesh::UniquePtr< Antioch::ReactionSet< libMesh::Real > > _reaction_set
libMesh::UniquePtr< Antioch::NASAThermoMixture< libMesh::Real, KineticsThermoCurveFit > > _nasa_mixture
std::vector< libMesh::Real > _h_stat_mech_ref_correction
libMesh::Real _minimum_T
bool _clip_negative_rho
Protected Attributes inherited from GRINS::AntiochChemistry
libMesh::UniquePtr< Antioch::ChemicalMixture< libMesh::Real > > _antioch_gas
Private Member Functions
AntiochMixtureAveragedTransportMixture ()
void specialized_build_thermo (libMesh::UniquePtr< Antioch::StatMechThermodynamics< libMesh::Real > > &thermo, thermo_type< Antioch::StatMechThermodynamics< libMesh::Real > >)
void specialized_build_thermo (libMesh::UniquePtr< Antioch::IdealGasMicroThermo< Antioch::NASAEvaluator< libMesh::Real, KineticsThermoCurveFit >, libMesh::Real > > &thermo, thermo_type< Antioch::IdealGasMicroThermo< Antioch::NASAEvaluator< libMesh::Real, KineticsThermoCurveFit >, libMesh::Real > >)
void specialized_build_viscosity (const GetPot &input, const std::string &material, libMesh::UniquePtr< Antioch::MixtureViscosity< Antioch::SutherlandViscosity< libMesh::Real >, libMesh::Real > > &viscosity, viscosity_type< Antioch::SutherlandViscosity< libMesh::Real > >)
void specialized_build_viscosity (const GetPot &input, const std::string &material, libMesh::UniquePtr< Antioch::MixtureViscosity< Antioch::BlottnerViscosity< libMesh::Real >, libMesh::Real > > &viscosity, viscosity_type< Antioch::BlottnerViscosity< libMesh::Real > >)
void specialized_build_conductivity (libMesh::UniquePtr< Antioch::MixtureConductivity< Antioch::EuckenThermalConductivity< Thermo >, libMesh::Real > > &conductivity, conductivity_type< Antioch::EuckenThermalConductivity< Thermo > >)
void specialized_build_diffusivity (const GetPot &input, const std::string &material, libMesh::UniquePtr< Antioch::MixtureDiffusion< Antioch::ConstantLewisDiffusivity< libMesh::Real >, libMesh::Real > > &diffusivity, diffusivity_type< Antioch::ConstantLewisDiffusivity< libMesh::Real > >)
Additional Inherited Members
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Detailed Description
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity>
class GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >
Wrapper class for storing state for computing Wilke transport properties using Antioch.
This class is expected to be constructed before threads have been forked and will live during the whole program. By default, Antioch is working in SI units. Note that this documentation will always be built regardless if Antioch is included in the GRINS build or not. Check configure output to confirm that Antioch was included in the build.
Definition at line 85 of file antioch_mixture_averaged_transport_mixture.h.
Member Typedef Documentation
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> typedef AntiochChemistry GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::ChemistryParent
Definition at line 113 of file antioch_mixture_averaged_transport_mixture.h.
Constructor & Destructor Documentation
template<typename KT , typename T , typename V , typename C , typename D > GRINS::AntiochMixtureAveragedTransportMixture< KT, T, V, C, D >::AntiochMixtureAveragedTransportMixture (const GetPot & input, const std::string & material)
Deprecated Constructor.
Definition at line 43 of file antioch_mixture_averaged_transport_mixture.C.
     : AntiochMixture<KT>(input,material)
   {
     {
       std::string warning = "==============================================\n";
       warning += "WARNING: This AntiochMixtureAveragedTransportMixture constructor is DEPREACTED!\n";
       warning += "         Prefer alternate constructor where parsing\n";
       warning += "         is done outside this class.\n";
       warning += "==============================================\n";
       libmesh_warning(warning);
     }
     std::string transport_data_filename =
       input( "Materials/"+material+"/GasMixture/Antioch/transport_data", "default" );
     if( transport_data_filename == std::string("default") )
       transport_data_filename = Antioch::DefaultInstallFilename::transport_mixture();
     bool verbose_transport_read =
       input( "Materials/"+material+"/GasMixture/Antioch/verbose_transport_read", false );
     _trans_mixture.reset( new Antioch::TransportMixture<libMesh::Real>( *(this->_antioch_gas.get()),
                                                                         transport_data_filename,
                                                                         verbose_transport_read,
                                                                         Antioch::ParsingType::ASCII ) );
     _wilke_mixture.reset( new Antioch::MixtureAveragedTransportMixture<libMesh::Real>(*(_trans_mixture.get()) ) );
     this->build_thermo();
     this->build_viscosity( input, material );
     this->build_conductivity( );
     this->build_diffusivity( input, material );
   }
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::AntiochMixtureAveragedTransportMixture (libMesh::UniquePtr< Antioch::ChemicalMixture< libMesh::Real > > & chem_mixture, libMesh::UniquePtr< Antioch::ReactionSet< libMesh::Real > > & reaction_set, libMesh::UniquePtr< Antioch::NASAThermoMixture< libMesh::Real, KineticsThermoCurveFit > > & kinetics_thermo_mix, libMesh::UniquePtr< Antioch::TransportMixture< libMesh::Real > > & trans_mix, libMesh::UniquePtr< Antioch::MixtureAveragedTransportMixture< libMesh::Real > > & wilke_mix, libMesh::UniquePtr< Antioch::MixtureViscosity< Viscosity, libMesh::Real > > & visc, libMesh::UniquePtr< Antioch::MixtureDiffusion< Diffusivity, libMesh::Real > > & diff, libMesh::Real min_T = -std::numeric_limits< libMesh::Real >::max(), bool clip_negative_rho = false)
Constructor with user-built objects.
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> virtual GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::~AntiochMixtureAveragedTransportMixture () inline virtual
Definition at line 103 of file antioch_mixture_averaged_transport_mixture.h.
 {}
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::AntiochMixtureAveragedTransportMixture () private
Member Function Documentation
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::build_conductivity () inline protected
Definition at line 142 of file antioch_mixture_averaged_transport_mixture.h.
References GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_conductivity().
     { specialized_build_conductivity( _conductivity, conductivity_type<Conductivity>() ); }
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::build_diffusivity (const GetPot & input, const std::string & material) inline protected
Definition at line 145 of file antioch_mixture_averaged_transport_mixture.h.
References GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_diffusivity().
     { specialized_build_diffusivity( input, material, _diffusivity, diffusivity_type<Diffusivity>() ); }
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::build_thermo () inline protected
Definition at line 136 of file antioch_mixture_averaged_transport_mixture.h.
References GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_thermo().
     { specialized_build_thermo( _thermo, thermo_type<Thermo>() ); }
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::build_viscosity (const GetPot & input, const std::string & material) inline protected
Definition at line 139 of file antioch_mixture_averaged_transport_mixture.h.
References GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_viscosity().
     { specialized_build_viscosity( input, material, _viscosity, viscosity_type<Viscosity>() ); }
template<typename KT , typename T , typename V , typename C , typename D > const Antioch::MixtureConductivity< C, libMesh::Real > & GRINS::AntiochMixtureAveragedTransportMixture< KT, T, V, C, D >::conductivity () const inline
Definition at line 268 of file antioch_mixture_averaged_transport_mixture.h.
Referenced by GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_conductivity().
   {
     return *_conductivity.get();
   }
template<typename KT , typename T , typename V , typename C , typename D > const Antioch::MixtureDiffusion< D, libMesh::Real > & GRINS::AntiochMixtureAveragedTransportMixture< KT, T, V, C, D >::diffusivity () const inline
Definition at line 276 of file antioch_mixture_averaged_transport_mixture.h.
Referenced by GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_diffusivity().
   {
     return *_diffusivity.get();
   }
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_conductivity (libMesh::UniquePtr< Antioch::MixtureConductivity< Antioch::EuckenThermalConductivity< Thermo >, libMesh::Real > > & conductivity, conductivity_type< Antioch::EuckenThermalConductivity< Thermo > >) inline private
Definition at line 205 of file antioch_mixture_averaged_transport_mixture.h.
References GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::conductivity().
Referenced by GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::build_conductivity().
     {
       conductivity.reset( new Antioch::MixtureConductivity<Antioch::EuckenThermalConductivity<Thermo>,libMesh::Real>(*(_trans_mixture.get())) );
       Antioch::build_eucken_thermal_conductivity<Thermo,libMesh::Real>(*(conductivity.get()),*(_thermo.get()));
       return;
     }
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_diffusivity (const GetPot & input, const std::string & material, libMesh::UniquePtr< Antioch::MixtureDiffusion< Antioch::ConstantLewisDiffusivity< libMesh::Real >, libMesh::Real > > & diffusivity, diffusivity_type< Antioch::ConstantLewisDiffusivity< libMesh::Real > >) inline private
Definition at line 223 of file antioch_mixture_averaged_transport_mixture.h.
References GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::diffusivity(), and GRINS::MaterialsParsing::parse_lewis_number().
Referenced by GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::build_diffusivity().
     {
       libMesh::Real Le = MaterialsParsing::parse_lewis_number(input,material);
       diffusivity.reset( new Antioch::MixtureDiffusion<Antioch::ConstantLewisDiffusivity<libMesh::Real>,libMesh::Real>(*(_trans_mixture.get())) );
       Antioch::build_constant_lewis_diffusivity<libMesh::Real>( *(diffusivity.get()), Le);
       return;
     }
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_thermo (libMesh::UniquePtr< Antioch::StatMechThermodynamics< libMesh::Real > > & thermo, thermo_type< Antioch::StatMechThermodynamics< libMesh::Real > >) inline private
Definition at line 152 of file antioch_mixture_averaged_transport_mixture.h.
References GRINS::AntiochChemistry::_antioch_gas.
Referenced by GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::build_thermo().
     {
       thermo.reset( new Antioch::StatMechThermodynamics<libMesh::Real>( *(this->_antioch_gas.get()) ) );
     }
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_thermo (libMesh::UniquePtr< Antioch::IdealGasMicroThermo< Antioch::NASAEvaluator< libMesh::Real, KineticsThermoCurveFit >, libMesh::Real > > & thermo, thermo_type< Antioch::IdealGasMicroThermo< Antioch::NASAEvaluator< libMesh::Real, KineticsThermoCurveFit >, libMesh::Real > >) inline private
Definition at line 158 of file antioch_mixture_averaged_transport_mixture.h.
References GRINS::AntiochChemistry::_antioch_gas, and GRINS::AntiochMixture< KineticsThermoCurveFit >::nasa_mixture().
     {
       _nasa_evaluator.reset( new Antioch::NASAEvaluator<libMesh::Real,KineticsThermoCurveFit>(this->nasa_mixture()) );
       thermo.reset( new Antioch::IdealGasMicroThermo<Antioch::NASAEvaluator<libMesh::Real,KineticsThermoCurveFit>, libMesh::Real>( *_nasa_evaluator, *(this->_antioch_gas.get()) ) );
     }
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_viscosity (const GetPot & input, const std::string & material, libMesh::UniquePtr< Antioch::MixtureViscosity< Antioch::SutherlandViscosity< libMesh::Real >, libMesh::Real > > & viscosity, viscosity_type< Antioch::SutherlandViscosity< libMesh::Real > >) inline private
Definition at line 165 of file antioch_mixture_averaged_transport_mixture.h.
References GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::viscosity().
Referenced by GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::build_viscosity().
     {
       viscosity.reset( new Antioch::MixtureViscosity<Antioch::SutherlandViscosity<libMesh::Real>,libMesh::Real>(*(_trans_mixture.get())) );
       std::string sutherland_data = input("Materials/"+material+"/GasMixture/Antioch/sutherland_data", "default");
       if( sutherland_data == "default" )
         sutherland_data = Antioch::DefaultInstallFilename::sutherland_data();
       Antioch::read_sutherland_data_ascii( *(viscosity.get()), sutherland_data );
     }
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> void GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_viscosity (const GetPot & input, const std::string & material, libMesh::UniquePtr< Antioch::MixtureViscosity< Antioch::BlottnerViscosity< libMesh::Real >, libMesh::Real > > & viscosity, viscosity_type< Antioch::BlottnerViscosity< libMesh::Real > >) inline private
Definition at line 179 of file antioch_mixture_averaged_transport_mixture.h.
References GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::viscosity().
     {
       viscosity.reset( new Antioch::MixtureViscosity<Antioch::BlottnerViscosity<libMesh::Real>,libMesh::Real>(*(_trans_mixture.get())) );
       std::string blottner_data = input("Materials/"+material+"/GasMixture/Antioch/blottner_data", "default");
       if( blottner_data == "default" )
         blottner_data = Antioch::DefaultInstallFilename::blottner_data();
       Antioch::read_blottner_data_ascii( *(viscosity.get()), blottner_data );
     }
template<typename KT , typename T , typename V , typename C , typename D > const Antioch::MixtureViscosity< V, libMesh::Real > & GRINS::AntiochMixtureAveragedTransportMixture< KT, T, V, C, D >::viscosity () const inline
Definition at line 260 of file antioch_mixture_averaged_transport_mixture.h.
Referenced by GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_viscosity().
   {
     return *_viscosity.get();
   }
template<typename KT , typename T , typename V , typename C , typename D > const Antioch::MixtureAveragedTransportMixture< libMesh::Real > & GRINS::AntiochMixtureAveragedTransportMixture< KT, T, V, C, D >::wilke_mixture () const inline
Definition at line 252 of file antioch_mixture_averaged_transport_mixture.h.
   {
     return *(_wilke_mixture.get());
   }
Member Data Documentation
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> libMesh::UniquePtr<Antioch::MixtureConductivity<Conductivity,libMesh::Real> > GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::_conductivity protected
Definition at line 128 of file antioch_mixture_averaged_transport_mixture.h.
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> libMesh::UniquePtr<Antioch::MixtureDiffusion<Diffusivity,libMesh::Real> > GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::_diffusivity protected
Definition at line 130 of file antioch_mixture_averaged_transport_mixture.h.
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> libMesh::UniquePtr<Antioch::NASAEvaluator<libMesh::Real,KineticsThermoCurveFit> > GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::_nasa_evaluator protected
For some Thermo types, we also need to cache a NASAEvaluator.
Definition at line 124 of file antioch_mixture_averaged_transport_mixture.h.
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> libMesh::UniquePtr<Thermo> GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::_thermo protected
Definition at line 121 of file antioch_mixture_averaged_transport_mixture.h.
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> libMesh::UniquePtr<Antioch::TransportMixture<libMesh::Real> > GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::_trans_mixture protected
Definition at line 117 of file antioch_mixture_averaged_transport_mixture.h.
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> libMesh::UniquePtr<Antioch::MixtureViscosity<Viscosity,libMesh::Real> > GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::_viscosity protected
Definition at line 126 of file antioch_mixture_averaged_transport_mixture.h.
template<typename KineticsThermoCurveFit, typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> libMesh::UniquePtr<Antioch::MixtureAveragedTransportMixture<libMesh::Real> > GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::_wilke_mixture protected
Definition at line 119 of file antioch_mixture_averaged_transport_mixture.h.
The documentation for this class was generated from the following files:
src/properties/include/grins/antioch_mixture_averaged_transport_mixture.h
src/properties/src/antioch_mixture_averaged_transport_mixture.C