GRINS-0.8.0: GRINSTesting::AntiochTestBase Class Reference
GRINSTesting::AntiochTestBase Class Reference
#include <antioch_test_base.h>
Public Member Functions
void init_antioch (const std::string &input_file, const std::string &material_name)
Protected Attributes
libMesh::UniquePtr< GRINS::AntiochMixture< Antioch::CEACurveFit< libMesh::Real > > > _antioch_mixture
Detailed Description
Definition at line 42 of file antioch_test_base.h.
Member Function Documentation
void GRINSTesting::AntiochTestBase::init_antioch (const std::string & input_file, const std::string & material_name) inline
Definition at line 46 of file antioch_test_base.h.
References _antioch_mixture, and GRINS::AntiochMixtureBuilderBase::build_antioch_mixture().
Referenced by GRINSTesting::AntiochAirNASA9ThermoTest::setUp(), and GRINSTesting::AntiochAirNASA9KineticsTest::setUp().
     {
       GetPot input(input_file);
       GRINS::AntiochMixtureBuilderBase builder;
       this->_antioch_mixture =
         builder.build_antioch_mixture<Antioch::CEACurveFit<libMesh::Real> >(input,material_name);
     }
Member Data Documentation
libMesh::UniquePtr<GRINS::AntiochMixture<Antioch::CEACurveFit<libMesh::Real> > > GRINSTesting::AntiochTestBase::_antioch_mixture protected
Definition at line 58 of file antioch_test_base.h.
Referenced by init_antioch(), GRINSTesting::AntiochAirNASA9ThermoTest::test_cp(), GRINSTesting::AntiochAirNASA9ThermoTest::test_hs(), and GRINSTesting::AntiochAirNASA9KineticsTest::test_omega_dot().
The documentation for this class was generated from the following file:
test/interface/antioch_test_base.h