GRINS-0.7.0: GRINS::PhysicsBuilder Class Reference
GRINS::PhysicsBuilder Class Reference
Manages runtime construction of Physics objects.
#include <physics_builder.h>
Public Member Functions
PhysicsBuilder ()
~PhysicsBuilder ()
Static Public Member Functions
static PhysicsList build_physics_map (const GetPot &input)
Returns container of constructed Physics objects.
Static Private Member Functions
static void parse_requested_physics (const GetPot &input, std::set< std::string > &requested_physics)
Parses the requested Physics from input and populates the set passed to this function.
Detailed Description
Manages runtime construction of Physics objects.
This will parse the input file for the requested Physics and manage their construction. Actual construction of the Physics object is delegated to PhysicsFactoryBase subclasses. The PhysicsBuilder merely manages tasks around them as needed. To add a new Physics, the user should instantiate an appropriate PhysicsFactoryBase subclass.
Definition at line 49 of file physics_builder.h.
Constructor & Destructor Documentation
GRINS::PhysicsBuilder::PhysicsBuilder () inline
Definition at line 53 of file physics_builder.h.
 {};
GRINS::PhysicsBuilder::~PhysicsBuilder () inline
Definition at line 55 of file physics_builder.h.
 {};
Member Function Documentation
PhysicsList GRINS::PhysicsBuilder::build_physics_map (const GetPot & input) static
Returns container of constructed Physics objects.
Definition at line 38 of file physics_builder.C.
References GRINS::PhysicsNaming::clear_suffix(), GRINS::PhysicsNaming::extract_physics(), GRINS::PhysicsNaming::extract_suffix(), parse_requested_physics(), GRINS::FactoryWithGetPot< Physics >::set_getpot(), GRINS::FactoryWithGetPotPhysicsName< Physics >::set_physics_name(), and GRINS::PhysicsNaming::set_suffix().
Referenced by GRINS::Simulation::init_multiphysics_system().
   {
     // First parse what Physics the user requested
     std::set<std::string> requested_physics;
     PhysicsBuilder::parse_requested_physics(input,requested_physics);
     // Give the PhysicsFactories access to the GetPot object
     PhysicsFactoryBase::set_getpot(input);
     PhysicsList physics_map;
     // Now populate the PhysicsList with with of the corresponding Physics objects
     for( std::set<std::string>::const_iterator physics_name_it = requested_physics.begin();
          physics_name_it != requested_physics.end();
          physics_name_it++ )
       {
         // Convenience
         std::string physics_name = *physics_name_it;
         // Set the physics_name in the PhysicsFactory as it will be used internally
         // to feed to the Physics constructors
         PhysicsFactoryBase::set_physics_name(physics_name);
         // Set the suffix in PhysicsNaming so it propagates to the Physics classes
         std::string physics_suffix = PhysicsNaming::extract_suffix(physics_name);
         PhysicsNaming::set_suffix(physics_suffix);
         // Strip any suffix out when querying the PhysicsFactories
         std::string physics_name_prefix = PhysicsNaming::extract_physics(physics_name);
         // Now build the actual Physics object
         libMesh::UniquePtr<Physics> physics_ptr = PhysicsFactoryBase::build(physics_name_prefix);
         // Clear out the suffix now that we're done
         PhysicsNaming::clear_suffix();
         // Now give it to the PhysicsList
         physics_map[physics_name] = SharedPtr<Physics>( physics_ptr.release() );
       }
     // Echo Physics to display, if requested
     if( input( "screen-options/echo_physics", true ) )
       {
         libMesh::out << "==========================================================" << std::endl
                      << "List of Enabled Physics:" << std::endl;
         for( PhysicsListIter it = physics_map.begin();
              it != physics_map.end();
              it++ )
           {
             libMesh::out << it->first << std::endl;
           }
         libMesh::out <<  "==========================================================" << std::endl;
       }
     return physics_map;
   }
void GRINS::PhysicsBuilder::parse_requested_physics (const GetPot & input, std::set< std::string > & requested_physics) static private
Parses the requested Physics from input and populates the set passed to this function.
Definition at line 96 of file physics_builder.C.
Referenced by build_physics_map().
   {
     int num_physics =  input.vector_variable_size("Physics/enabled_physics");
     if( num_physics < 1 )
       libmesh_error_msg("Error: Must enable at least one physics model!");
     for( int i = 0; i < num_physics; i++ )
       requested_physics.insert( input("Physics/enabled_physics", "NULL", i ) );
   }
The documentation for this class was generated from the following files:
src/physics/include/grins/physics_builder.h
src/physics/src/physics_builder.C