GRINS-0.6.0: GRINS::ConstantConductivity Class Reference
GRINS::ConstantConductivity Class Reference
#include <constant_conductivity.h>
Public Member Functions
ConstantConductivity (const GetPot &input)
~ConstantConductivity ()
libMesh::Real operator() () const
libMesh::Real operator() (AssemblyContext &context, unsigned int qp) const
libMesh::Real operator() (const libMesh::Point &p, const libMesh::Real time)
libMesh::Real operator() (const libMesh::Real T) const
libMesh::Real operator() (const libMesh::Real mu, const libMesh::Real cp) const
libMesh::Real deriv (const libMesh::Real T) const
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiPointer< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Private Member Functions
ConstantConductivity ()
Private Attributes
libMesh::Real _k
Detailed Description
Definition at line 40 of file constant_conductivity.h.
Constructor & Destructor Documentation
GRINS::ConstantConductivity::ConstantConductivity (const GetPot & input)
Definition at line 38 of file constant_conductivity.C.
References _k, GRINS::incompressible_navier_stokes, and GRINS::ParameterUser::set_parameter().
     : ParameterUser("ConstantConductivity"),
       _k(0.0)
   {
     if( !input.have_variable("Materials/Conductivity/k") )
       {
         libmesh_warning("No Materials/Conductivity/k specified!\n");
         // Try and get the conductivity from other specifications
         this->set_parameter
           (_k, input, "Physics/"+incompressible_navier_stokes+"/k", _k);
       }
     else
       this->set_parameter
         (_k, input, "Materials/Conductivity/k", _k);
     return;
   }
GRINS::ConstantConductivity::~ConstantConductivity ()
Definition at line 56 of file constant_conductivity.C.
   {
     return;
   }
GRINS::ConstantConductivity::ConstantConductivity () private
Member Function Documentation
libMesh::Real GRINS::ConstantConductivity::deriv (const libMesh::Real T) const inline
Definition at line 100 of file constant_conductivity.h.
   {
     return 0.0;
   }
libMesh::Real GRINS::ConstantConductivity::operator() () const inline
Definition at line 69 of file constant_conductivity.h.
References _k.
   {
     return _k;
   }
libMesh::Real GRINS::ConstantConductivity::operator() (AssemblyContext & context, unsigned int qp) const inline
Definition at line 75 of file constant_conductivity.h.
References _k.
   {
     return _k;
   }
libMesh::Real GRINS::ConstantConductivity::operator() (const libMesh::Point & p, const libMesh::Real time) inline
Definition at line 81 of file constant_conductivity.h.
References _k.
   {
     return _k;
   }
libMesh::Real GRINS::ConstantConductivity::operator() (const libMesh::Real T) const inline
Definition at line 88 of file constant_conductivity.h.
   {
     return (*this)();
   }
libMesh::Real GRINS::ConstantConductivity::operator() (const libMesh::Real mu, const libMesh::Real cp) const inline
Definition at line 94 of file constant_conductivity.h.
   {
     return (*this)();
   }
void GRINS::ParameterUser::register_parameter (const std::string & param_name, libMesh::ParameterMultiPointer< libMesh::Number > & param_pointer) const virtual inherited
Each subclass will register its copy of an independent.
Reimplemented in GRINS::AxisymmetricHeatTransfer< Conductivity >, GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::IncompressibleNavierStokesBase< Viscosity >, GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >, GRINS::HeatConduction< Conductivity >, GRINS::HeatTransferBase< Conductivity >, and GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >.
Definition at line 50 of file parameter_user.C.
Referenced by GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::register_parameter(), GRINS::HeatTransferBase< Conductivity >::register_parameter(), GRINS::HeatConduction< Conductivity >::register_parameter(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::register_parameter(), GRINS::IncompressibleNavierStokesBase< Viscosity >::register_parameter(), GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::register_parameter(), and GRINS::AxisymmetricHeatTransfer< Conductivity >::register_parameter().
   {
     std::map<std::string, libMesh::Number*>::const_iterator it =
       _my_parameters.find(param_name);
     if (it != _my_parameters.end())
       {
         std::cout << _my_name << " uses parameter " << param_name
                   << std::endl;
         param_pointer.push_back(it->second);
       }
   }
void GRINS::ParameterUser::set_parameter (libMesh::Number & param_variable, const GetPot & input, const std::string & param_name, libMesh::Number param_default) virtual inherited
Each subclass can simultaneously read a parameter value from.
Definition at line 35 of file parameter_user.C.
References GRINS::ParameterUser::_my_name, and GRINS::ParameterUser::_my_parameters.
Referenced by GRINS::AveragedFanAdjointStabilization< Viscosity >::AveragedFanAdjointStabilization(), GRINS::AveragedTurbineAdjointStabilization< Viscosity >::AveragedTurbineAdjointStabilization(), GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::BoussinesqBuoyancyAdjointStabilization(), GRINS::BoussinesqBuoyancyBase::BoussinesqBuoyancyBase(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::BoussinesqBuoyancySPGSMStabilization(), ConstantConductivity(), GRINS::ConstantPrandtlConductivity::ConstantPrandtlConductivity(), GRINS::ConstantSourceFunction::ConstantSourceFunction(), GRINS::ConstantSourceTerm::ConstantSourceTerm(), GRINS::ConstantSpecificHeat::ConstantSpecificHeat(), GRINS::ConstantViscosity::ConstantViscosity(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticCableConstantGravity::ElasticCableConstantGravity(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransferBase< Conductivity >::HeatTransferBase(), GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase(), GRINS::AverageNusseltNumber::init(), GRINS::MooneyRivlin::MooneyRivlin(), GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase(), GRINS::HookesLaw1D::read_input_options(), GRINS::HookesLaw::read_input_options(), GRINS::AxisymmetricBoussinesqBuoyancy::read_input_options(), and GRINS::VelocityDragAdjointStabilization< Viscosity >::VelocityDragAdjointStabilization().
   {
     param_variable = input(param_name, param_default);
     libmesh_assert_msg(!_my_parameters.count(param_name),
       "ERROR: " << _my_name << " double-registered parameter " <<
       param_name);
     _my_parameters[param_name] = &param_variable;
   }
Member Data Documentation
libMesh::Real GRINS::ConstantConductivity::_k private
Definition at line 63 of file constant_conductivity.h.
Referenced by ConstantConductivity(), and operator()().
The documentation for this class was generated from the following files:
src/properties/include/grins/constant_conductivity.h
src/properties/src/constant_conductivity.C