GRINS-0.8.0: GRINS::ElasticCableRayleighDamping< StressStrainLaw > Class Template Reference
GRINS::ElasticCableRayleighDamping< StressStrainLaw > Class Template Reference
#include <elastic_cable_rayleigh_damping.h>
Public Member Functions
ElasticCableRayleighDamping (const PhysicsName &physics_name, const GetPot &input, bool is_compressible)
virtual ~ElasticCableRayleighDamping ()
virtual void damping_residual (bool compute_jacobian, AssemblyContext &context)
Time dependent part(s) of physics for element interiors.
Public Member Functions inherited from GRINS::ElasticCableBase< StressStrainLaw >
ElasticCableBase (const GRINS::PhysicsName &physics_name, const GetPot &input, bool is_compressible)
virtual ~ElasticCableBase ()
Public Member Functions inherited from GRINS::ElasticCableAbstract
ElasticCableAbstract (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~ElasticCableAbstract ()
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
Public Member Functions inherited from GRINS::SolidMechanicsAbstract
SolidMechanicsAbstract (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~SolidMechanicsAbstract ()
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Set which variables are time evolving.
Public Member Functions inherited from GRINS::Physics
Physics (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~Physics ()
virtual void init_variables (libMesh::FEMSystem *)
Initialize variables for this physics.
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void preassembly (MultiphysicsSystem &)
Perform any necessary setup before element assembly begins.
virtual void reinit (MultiphysicsSystem &)
Any reinitialization that needs to be done.
virtual void element_time_derivative (bool, AssemblyContext &)
Time dependent part(s) of physics for element interiors.
virtual void side_time_derivative (bool, AssemblyContext &)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool, AssemblyContext &)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool, AssemblyContext &)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool, AssemblyContext &)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool, AssemblyContext &)
Constraint part(s) of physics for scalar variables.
virtual void mass_residual (bool, AssemblyContext &)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool, AssemblyContext &)
Mass matrix part(s) for scalar variables.
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
virtual void compute_element_time_derivative_cache (AssemblyContext &)
virtual void compute_side_time_derivative_cache (AssemblyContext &)
virtual void compute_nonlocal_time_derivative_cache (AssemblyContext &)
virtual void compute_element_constraint_cache (AssemblyContext &)
virtual void compute_side_constraint_cache (AssemblyContext &)
virtual void compute_nonlocal_constraint_cache (AssemblyContext &)
virtual void compute_damping_residual_cache (AssemblyContext &)
virtual void compute_mass_residual_cache (AssemblyContext &)
virtual void compute_nonlocal_mass_residual_cache (AssemblyContext &)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
ICHandlingBase * get_ic_handler ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Attributes
libMesh::Real _lambda_factor
libMesh::Real _mu_factor
Protected Attributes inherited from GRINS::ElasticCableBase< StressStrainLaw >
StressStrainLaw _stress_strain_law
bool _is_compressible
Protected Attributes inherited from GRINS::ElasticCableAbstract
libMesh::Real _A
Cross-sectional area of the cable.
libMesh::Real _rho
Cable density.
Protected Attributes inherited from GRINS::SolidMechanicsAbstract
DisplacementVariable & _disp_vars
Protected Attributes inherited from GRINS::Physics
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
Private Member Functions
ElasticCableRayleighDamping ()
Additional Inherited Members
Static Public Member Functions inherited from GRINS::Physics
static void set_is_axisymmetric (bool is_axisymmetric)
Set whether we should treat the problem as axisymmetric.
static bool is_axisymmetric ()
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Types inherited from GRINS::SolidMechanicsAbstract
typedef const libMesh::DenseSubVector< libMesh::Number > &(libMesh::DiffContext::* VarFuncType) (unsigned int) const
typedef void(libMesh::FEMContext::* InteriorFuncType) (unsigned int, unsigned int, libMesh::Real &) const
typedef libMesh::Real(libMesh::DiffContext::* VarDerivType) () const
Protected Member Functions inherited from GRINS::ElasticCableBase< StressStrainLaw >
void mass_residual_impl (bool compute_jacobian, AssemblyContext &context, InteriorFuncType interior_solution, VarDerivType get_solution_deriv, libMesh::Real mu=1.0)
Implementation of mass_residual.
void compute_metric_tensors (unsigned int qp, const libMesh::FEBase &elem, const AssemblyContext &context, const libMesh::Gradient &grad_u, const libMesh::Gradient &grad_v, const libMesh::Gradient &grad_w, libMesh::TensorValue< libMesh::Real > &a_cov, libMesh::TensorValue< libMesh::Real > &a_contra, libMesh::TensorValue< libMesh::Real > &A_cov, libMesh::TensorValue< libMesh::Real > &A_contra, libMesh::Real &lambda_sq)
Protected Member Functions inherited from GRINS::ElasticCableAbstract
const libMesh::FEGenericBase< libMesh::Real > * get_fe (const AssemblyContext &context)
Protected Member Functions inherited from GRINS::Physics
libMesh::UniquePtr< libMesh::FEGenericBase< libMesh::Real > > build_new_fe (const libMesh::Elem *elem, const libMesh::FEGenericBase< libMesh::Real > *fe, const libMesh::Point p)
void parse_enabled_subdomains (const GetPot &input, const std::string &physics_name)
void check_var_subdomain_consistency (const FEVariablesBase &var) const
Check that var is enabled on at least the subdomains this Physics is.
Static Protected Attributes inherited from GRINS::Physics
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
static bool _is_axisymmetric = false
Caches whether we are solving an axisymmetric problem or not.
Detailed Description
template<typename StressStrainLaw>
class GRINS::ElasticCableRayleighDamping< StressStrainLaw >
Definition at line 33 of file elastic_cable_rayleigh_damping.h.
Constructor & Destructor Documentation
template<typename StressStrainLaw > GRINS::ElasticCableRayleighDamping< StressStrainLaw >::ElasticCableRayleighDamping (const PhysicsName & physics_name, const GetPot & input, bool is_compressible)
Definition at line 39 of file elastic_cable_rayleigh_damping.C.
References GRINS::PhysicsNaming::elastic_cable(), GRINS::PhysicsNaming::elastic_cable_rayleigh_damping(), and GRINS::Physics::parse_enabled_subdomains().
     : ElasticCableBase<StressStrainLaw>(physics_name,input,is_compressible),
     _lambda_factor(input("Physics/"+PhysicsNaming::elastic_cable_rayleigh_damping()+"/lambda_factor",0.0)),
     _mu_factor(input("Physics/"+PhysicsNaming::elastic_cable_rayleigh_damping()+"/mu_factor",0.0))
   {
     if( !input.have_variable("Physics/"+PhysicsNaming::elastic_cable_rayleigh_damping()+"/lambda_factor") )
       libmesh_error_msg("ERROR: Couldn't find Physics/"+PhysicsNaming::elastic_cable_rayleigh_damping()+"/lambda_factor in input!");
     if( !input.have_variable("Physics/"+PhysicsNaming::elastic_cable_rayleigh_damping()+"/mu_factor") )
       libmesh_error_msg("ERROR: Couldn't find Physics/"+PhysicsNaming::elastic_cable_rayleigh_damping()+"/mu_factor in input!");
     // If the user specified enabled subdomains in this Physics section,
     // that's an error; we're slave to ElasticCable.
     if( input.have_variable("Physics/"+PhysicsNaming::elastic_cable_rayleigh_damping()+"/enabled_subdomains" ) )
       libmesh_error_msg("ERROR: Cannot specify subdomains for "
                         +PhysicsNaming::elastic_cable_rayleigh_damping()
                         +"! Must specify subdomains through "
                         +PhysicsNaming::elastic_cable()+".");
     this->parse_enabled_subdomains(input,PhysicsNaming::elastic_cable());
   }
template<typename StressStrainLaw > virtual GRINS::ElasticCableRayleighDamping< StressStrainLaw >::~ElasticCableRayleighDamping () inline virtual
Definition at line 41 of file elastic_cable_rayleigh_damping.h.
 {};
template<typename StressStrainLaw > GRINS::ElasticCableRayleighDamping< StressStrainLaw >::ElasticCableRayleighDamping () private
Member Function Documentation
template<typename StressStrainLaw > void GRINS::ElasticCableRayleighDamping< StressStrainLaw >::damping_residual (bool compute_jacobian, AssemblyContext & context) virtual
Time dependent part(s) of physics for element interiors.
Reimplemented from GRINS::Physics.
Definition at line 66 of file elastic_cable_rayleigh_damping.C.
   {
     // First, do the "mass" contribution
     this->mass_residual_impl(compute_jacobian,
                              context,
                              &libMesh::FEMContext::interior_rate,
                              &libMesh::DiffContext::get_elem_solution_rate_derivative,
                              _mu_factor);
     // Now do the stiffness contribution
     const unsigned int n_u_dofs = context.get_dof_indices(this->_disp_vars.u()).size();
     const std::vector<libMesh::Real> &JxW =
       this->get_fe(context)->get_JxW();
     // Residuals, Jacobians that we're populating
     libMesh::DenseSubVector<libMesh::Number> &Fu = context.get_elem_residual(this->_disp_vars.u());
     libMesh::DenseSubVector<libMesh::Number>* Fv = NULL;
     libMesh::DenseSubVector<libMesh::Number>* Fw = NULL;
     libMesh::DenseSubMatrix<libMesh::Number>& Kuu = context.get_elem_jacobian(this->_disp_vars.u(),this->_disp_vars.u());
     libMesh::DenseSubMatrix<libMesh::Number>* Kuv = NULL;
     libMesh::DenseSubMatrix<libMesh::Number>* Kuw = NULL;
     libMesh::DenseSubMatrix<libMesh::Number>* Kvu = NULL;
     libMesh::DenseSubMatrix<libMesh::Number>* Kvv = NULL;
     libMesh::DenseSubMatrix<libMesh::Number>* Kvw = NULL;
     libMesh::DenseSubMatrix<libMesh::Number>* Kwu = NULL;
     libMesh::DenseSubMatrix<libMesh::Number>* Kwv = NULL;
     libMesh::DenseSubMatrix<libMesh::Number>* Kww = NULL;
     if( this->_disp_vars.dim() >= 2 )
       {
         Fv = &context.get_elem_residual(this->_disp_vars.v());
         Kuv = &context.get_elem_jacobian(this->_disp_vars.u(),this->_disp_vars.v());
         Kvu = &context.get_elem_jacobian(this->_disp_vars.v(),this->_disp_vars.u());
         Kvv = &context.get_elem_jacobian(this->_disp_vars.v(),this->_disp_vars.v());
       }
     if( this->_disp_vars.dim() == 3 )
       {
         Fw = &context.get_elem_residual(this->_disp_vars.w());
         Kuw = &context.get_elem_jacobian(this->_disp_vars.u(),this->_disp_vars.w());
         Kvw = &context.get_elem_jacobian(this->_disp_vars.v(),this->_disp_vars.w());
         Kwu = &context.get_elem_jacobian(this->_disp_vars.w(),this->_disp_vars.u());
         Kwv = &context.get_elem_jacobian(this->_disp_vars.w(),this->_disp_vars.v());
         Kww = &context.get_elem_jacobian(this->_disp_vars.w(),this->_disp_vars.w());
       }
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     // All shape function gradients are w.r.t. master element coordinates
     const std::vector<std::vector<libMesh::Real> >& dphi_dxi = this->get_fe(context)->get_dphidxi();
     const libMesh::DenseSubVector<libMesh::Number>& u_coeffs = context.get_elem_solution( this->_disp_vars.u() );
     const libMesh::DenseSubVector<libMesh::Number>* v_coeffs = NULL;
     const libMesh::DenseSubVector<libMesh::Number>* w_coeffs = NULL;
     if( this->_disp_vars.dim() >= 2 )
       v_coeffs = &context.get_elem_solution( this->_disp_vars.v() );
     if( this->_disp_vars.dim() == 3 )
       w_coeffs = &context.get_elem_solution( this->_disp_vars.w() );
     const libMesh::DenseSubVector<libMesh::Number>& dudt_coeffs =
       context.get_elem_solution_rate( this->_disp_vars.u() );
     const libMesh::DenseSubVector<libMesh::Number>* dvdt_coeffs = NULL;
     const libMesh::DenseSubVector<libMesh::Number>* dwdt_coeffs = NULL;
     if( this->_disp_vars.dim() >= 2 )
       dvdt_coeffs = &context.get_elem_solution_rate( this->_disp_vars.v() );
     if( this->_disp_vars.dim() == 3 )
       dwdt_coeffs = &context.get_elem_solution_rate( this->_disp_vars.w() );
     // Need these to build up the covariant and contravariant metric tensors
     const std::vector<libMesh::RealGradient>& dxdxi  = this->get_fe(context)->get_dxyzdxi();
     const unsigned int dim = 1; // The cable dimension is always 1 for this physics
     for (unsigned int qp=0; qp != n_qpoints; qp++)
       {
         // Gradients are w.r.t. master element coordinates
         libMesh::Gradient grad_u, grad_v, grad_w;
         libMesh::Gradient dgradu_dt, dgradv_dt, dgradw_dt;
         for( unsigned int d = 0; d < n_u_dofs; d++ )
           {
             libMesh::RealGradient u_gradphi( dphi_dxi[d][qp] );
             grad_u += u_coeffs(d)*u_gradphi;
             dgradu_dt += dudt_coeffs(d)*u_gradphi;
             if( this->_disp_vars.dim() >= 2 )
               {
                 grad_v += (*v_coeffs)(d)*u_gradphi;
                 dgradv_dt += (*dvdt_coeffs)(d)*u_gradphi;
               }
             if( this->_disp_vars.dim() == 3 )
               {
                 grad_w += (*w_coeffs)(d)*u_gradphi;
                 dgradw_dt += (*dwdt_coeffs)(d)*u_gradphi;
               }
           }
         libMesh::RealGradient grad_x( dxdxi[qp](0) );
         libMesh::RealGradient grad_y( dxdxi[qp](1) );
         libMesh::RealGradient grad_z( dxdxi[qp](2) );
         libMesh::TensorValue<libMesh::Real> a_cov, a_contra, A_cov, A_contra;
         libMesh::Real lambda_sq = 0;
         this->compute_metric_tensors( qp, *(this->get_fe(context)), context,
                                       grad_u, grad_v, grad_w,
                                       a_cov, a_contra, A_cov, A_contra,
                                       lambda_sq );
         // Compute stress tensor
         libMesh::TensorValue<libMesh::Real> tau;
         ElasticityTensor C;
         this->_stress_strain_law.compute_stress_and_elasticity(dim,a_contra,a_cov,A_contra,A_cov,tau,C);
         libMesh::Real jac = JxW[qp];
         for (unsigned int i=0; i != n_u_dofs; i++)
           {
             libMesh::RealGradient u_gradphi( dphi_dxi[i][qp] );
             libMesh::Real u_diag_factor = _lambda_factor*this->_A*jac*tau(0,0)*dgradu_dt(0)*u_gradphi(0);
             libMesh::Real v_diag_factor = _lambda_factor*this->_A*jac*tau(0,0)*dgradv_dt(0)*u_gradphi(0);
             libMesh::Real w_diag_factor = _lambda_factor*this->_A*jac*tau(0,0)*dgradw_dt(0)*u_gradphi(0);
             const libMesh::Real C1 = _lambda_factor*this->_A*jac*C(0,0,0,0)*u_gradphi(0);
             const libMesh::Real gamma_u = (grad_x(0)+grad_u(0));
             libMesh::Real gamma_v = 0.0;
             libMesh::Real gamma_w = 0.0;
             if( this->_disp_vars.dim() >= 2 )
               gamma_v = (grad_y(0)+grad_v(0));
             if( this->_disp_vars.dim() == 3 )
               gamma_w = (grad_z(0)+grad_w(0));
             const libMesh::Real x_term = C1*gamma_u;
             const libMesh::Real y_term = C1*gamma_v;
             const libMesh::Real z_term = C1*gamma_w;
             libMesh::Real dt_term = dgradu_dt(0)*gamma_u + dgradv_dt(0)*gamma_v + dgradw_dt(0)*gamma_w;
             Fu(i) += u_diag_factor + x_term*dt_term;
             if( this->_disp_vars.dim() >= 2 )
               (*Fv)(i) += v_diag_factor + y_term*dt_term;
             if( this->_disp_vars.dim() == 3 )
               (*Fw)(i) += w_diag_factor + z_term*dt_term;
           }
         if( compute_jacobian )
           {
             for(unsigned int i=0; i != n_u_dofs; i++)
               {
                 libMesh::RealGradient u_gradphi_I( dphi_dxi[i][qp] );
                 for(unsigned int j=0; j != n_u_dofs; j++)
                   {
                     libMesh::RealGradient u_gradphi_J( dphi_dxi[j][qp] );
                     libMesh::Real common_factor = _lambda_factor*this->_A*jac*u_gradphi_I(0);
                     const libMesh::Real diag_term_1 = common_factor*tau(0,0)*u_gradphi_J(0)*context.get_elem_solution_rate_derivative();
                     const libMesh::Real dgamma_du = ( u_gradphi_J(0)*(grad_x(0)+grad_u(0)) );
                     const libMesh::Real dgamma_dv = ( u_gradphi_J(0)*(grad_y(0)+grad_v(0)) );
                     const libMesh::Real dgamma_dw = ( u_gradphi_J(0)*(grad_z(0)+grad_w(0)) );
                     const libMesh::Real diag_term_2_factor = common_factor*C(0,0,0,0)*context.get_elem_solution_derivative();
                     Kuu(i,j) += diag_term_1 + dgradu_dt(0)*diag_term_2_factor*dgamma_du;
                     if( this->_disp_vars.dim() >= 2 )
                       {
                         (*Kuv)(i,j) += dgradu_dt(0)*diag_term_2_factor*dgamma_dv;
                         (*Kvu)(i,j) += dgradv_dt(0)*diag_term_2_factor*dgamma_du;
                         (*Kvv)(i,j) += diag_term_1 + dgradv_dt(0)*diag_term_2_factor*dgamma_dv;
                       }
                     if( this->_disp_vars.dim() == 3 )
                       {
                         (*Kuw)(i,j) += dgradu_dt(0)*diag_term_2_factor*dgamma_dw;
                         (*Kvw)(i,j) += dgradv_dt(0)*diag_term_2_factor*dgamma_dw;
                         (*Kwu)(i,j) += dgradw_dt(0)*diag_term_2_factor*dgamma_du;
                         (*Kwv)(i,j) += dgradw_dt(0)*diag_term_2_factor*dgamma_dv;
                         (*Kww)(i,j) += diag_term_1 + dgradw_dt(0)*diag_term_2_factor*dgamma_dw;
                       }
                     const libMesh::Real C1 = common_factor*C(0,0,0,0);
                     const libMesh::Real gamma_u = (grad_x(0)+grad_u(0));
                     const libMesh::Real gamma_v = (grad_y(0)+grad_v(0));
                     const libMesh::Real gamma_w = (grad_z(0)+grad_w(0));
                     const libMesh::Real x_term = C1*gamma_u;
                     const libMesh::Real y_term = C1*gamma_v;
                     const libMesh::Real z_term = C1*gamma_w;
                     const libMesh::Real ddtterm_du = u_gradphi_J(0)*(gamma_u*context.get_elem_solution_rate_derivative()
                                                                      + dgradu_dt(0)*context.get_elem_solution_derivative());
                     libMesh::Real ddtterm_dv = 0.0;
                     if( this->_disp_vars.dim() >= 2 )
                       ddtterm_dv = u_gradphi_J(0)*(gamma_v*context.get_elem_solution_rate_derivative()
                                                    + dgradv_dt(0)*context.get_elem_solution_derivative());
                     libMesh::Real ddtterm_dw = 0.0;
                     if( this->_disp_vars.dim() == 3 )
                       ddtterm_dw = u_gradphi_J(0)*(gamma_w*context.get_elem_solution_rate_derivative()
                                                    + dgradw_dt(0)*context.get_elem_solution_derivative());
                     Kuu(i,j) += x_term*ddtterm_du;
                     if( this->_disp_vars.dim() >= 2 )
                       {
                         (*Kuv)(i,j) += x_term*ddtterm_dv;
                         (*Kvu)(i,j) += y_term*ddtterm_du;
                         (*Kvv)(i,j) += y_term*ddtterm_dv;
                       }
                     if( this->_disp_vars.dim() == 3 )
                       {
                         (*Kuw)(i,j) += x_term*ddtterm_dw;
                         (*Kvw)(i,j) += y_term*ddtterm_dw;
                         (*Kwu)(i,j) += z_term*ddtterm_du;
                         (*Kwv)(i,j) += z_term*ddtterm_dv;
                         (*Kww)(i,j) += z_term*ddtterm_dw;
                       }
                     libMesh::Real dt_term = dgradu_dt(0)*gamma_u + dgradv_dt(0)*gamma_v + dgradw_dt(0)*gamma_w;
                     // Here, we're missing derivatives of C(0,0,0,0) w.r.t. strain
                     // Nonzero for hyperelasticity models
                     const libMesh::Real dxterm_du = C1*u_gradphi_J(0)*context.get_elem_solution_derivative();
                     const libMesh::Real dyterm_dv = dxterm_du;
                     const libMesh::Real dzterm_dw = dxterm_du;
                     Kuu(i,j) += dxterm_du*dt_term;
                     if( this->_disp_vars.dim() >= 2 )
                       (*Kvv)(i,j) += dyterm_dv*dt_term;
                     if( this->_disp_vars.dim() == 3 )
                       (*Kww)(i,j) += dzterm_dw*dt_term;
                   } // end j-loop
               } // end i-loop
           } // end if(compute_jacobian)
       } // end qp loop
   }
Member Data Documentation
template<typename StressStrainLaw > libMesh::Real GRINS::ElasticCableRayleighDamping< StressStrainLaw >::_lambda_factor protected
Definition at line 49 of file elastic_cable_rayleigh_damping.h.
template<typename StressStrainLaw > libMesh::Real GRINS::ElasticCableRayleighDamping< StressStrainLaw >::_mu_factor protected
Definition at line 50 of file elastic_cable_rayleigh_damping.h.
The documentation for this class was generated from the following files:
src/physics/include/grins/elastic_cable_rayleigh_damping.h
src/physics/src/elastic_cable_rayleigh_damping.C