GRINS-0.8.0: GRINSTesting::NASAThermoTestBase Class Reference
GRINSTesting::NASAThermoTestBase Class Reference abstract
#include <nasa_thermo_test_base.h>
Public Member Functions
virtual libMesh::Real cp_exact (unsigned int species_idx, libMesh::Real T)=0
virtual libMesh::Real h_exact (unsigned int species_idx, libMesh::Real T)=0
virtual libMesh::Real s_R_exact (unsigned int species_idx, libMesh::Real T)=0
virtual libMesh::Real h_RT_exact (unsigned int species_idx, libMesh::Real T)=0
template<typename ThermoMixture , typename ThermoEvaluator >
void test_cp_common (ThermoMixture &mixture, const std::vector< libMesh::Real > &Y, libMesh::Real rel_tol)
template<typename ThermoMixture , typename ThermoEvaluator >
void test_h_common (ThermoMixture &mixture, libMesh::Real rel_tol)
Public Member Functions inherited from GRINSTesting::SpeciesTestBase
SpeciesTestBase ()
libMesh::Real molar_mass (unsigned int idx)
libMesh::Real R_species (unsigned int idx)
Protected Member Functions
const std::vector< libMesh::Real > & nasa_coeffs (unsigned int idx)
Protected Attributes
std::vector< libMesh::Real > _N2_200_1000_coeffs
std::vector< libMesh::Real > _O2_200_1000_coeffs
std::vector< libMesh::Real > _O_200_1000_coeffs
std::vector< libMesh::Real > _NO_200_1000_coeffs
std::vector< libMesh::Real > _N_200_1000_coeffs
Protected Attributes inherited from GRINSTesting::SpeciesTestBase
unsigned int _N2_idx
unsigned int _O2_idx
unsigned int _O_idx
unsigned int _N_idx
unsigned int _NO_idx
std::vector< unsigned int > _active_species
Detailed Description
Definition at line 40 of file nasa_thermo_test_base.h.
Member Function Documentation
virtual libMesh::Real GRINSTesting::NASAThermoTestBase::cp_exact (unsigned int species_idx, libMesh::Real T) pure virtual
Implemented in GRINSTesting::NASA9ThermoTestBase, and GRINSTesting::NASA7ThermoTestBase.
Referenced by test_cp_common().
virtual libMesh::Real GRINSTesting::NASAThermoTestBase::h_exact (unsigned int species_idx, libMesh::Real T) pure virtual
Implemented in GRINSTesting::NASA9ThermoTestBase, and GRINSTesting::NASA7ThermoTestBase.
Referenced by test_h_common().
virtual libMesh::Real GRINSTesting::NASAThermoTestBase::h_RT_exact (unsigned int species_idx, libMesh::Real T) pure virtual
Implemented in GRINSTesting::NASA9ThermoTestBase, and GRINSTesting::NASA7ThermoTestBase.
Referenced by GRINSTesting::KineticsTestBase::eq_constant().
const std::vector<libMesh::Real>& GRINSTesting::NASAThermoTestBase::nasa_coeffs (unsigned int idx) inline protected
Definition at line 121 of file nasa_thermo_test_base.h.
References _N2_200_1000_coeffs, GRINSTesting::SpeciesTestBase::_N2_idx, _N_200_1000_coeffs, GRINSTesting::SpeciesTestBase::_N_idx, _NO_200_1000_coeffs, GRINSTesting::SpeciesTestBase::_NO_idx, _O2_200_1000_coeffs, GRINSTesting::SpeciesTestBase::_O2_idx, _O_200_1000_coeffs, and GRINSTesting::SpeciesTestBase::_O_idx.
Referenced by GRINSTesting::NASA7ThermoTestBase::cp_exact(), GRINSTesting::NASA9ThermoTestBase::cp_exact(), GRINSTesting::NASA7ThermoTestBase::h_exact(), GRINSTesting::NASA9ThermoTestBase::h_exact(), GRINSTesting::NASA7ThermoTestBase::h_RT_exact(), GRINSTesting::NASA9ThermoTestBase::h_RT_exact(), GRINSTesting::NASA7ThermoTestBase::s_R_exact(), and GRINSTesting::NASA9ThermoTestBase::s_R_exact().
     {
       if(idx == _N2_idx)
         return _N2_200_1000_coeffs;
       else if( idx == _O2_idx)
         return _O2_200_1000_coeffs;
       else if( idx == _NO_idx)
         return _NO_200_1000_coeffs;
       else if(idx == _O_idx)
         return _O_200_1000_coeffs;
       else if(idx == _N_idx)
         return _N_200_1000_coeffs;
       else
         CPPUNIT_FAIL("Invalid idx for nasa_coeffs");
       // dummy to avoid warning
       return _N2_200_1000_coeffs;
     }
virtual libMesh::Real GRINSTesting::NASAThermoTestBase::s_R_exact (unsigned int species_idx, libMesh::Real T) pure virtual
Implemented in GRINSTesting::NASA9ThermoTestBase, and GRINSTesting::NASA7ThermoTestBase.
Referenced by GRINSTesting::KineticsTestBase::eq_constant().
template<typename ThermoMixture , typename ThermoEvaluator > void GRINSTesting::NASAThermoTestBase::test_cp_common (ThermoMixture & mixture, const std::vector< libMesh::Real > & Y, libMesh::Real rel_tol) inline
Definition at line 53 of file nasa_thermo_test_base.h.
References GRINSTesting::SpeciesTestBase::_active_species, GRINSTesting::TestingUtils::abs_tol_from_rel_tol(), GRINSTesting::ThermochemTestCommon::compute_mass_frac_mixture_prop(), and cp_exact().
     {
       CPPUNIT_ASSERT_EQUAL(_active_species.size(), Y.size() );
       ThermoEvaluator evaluator( mixture );
       libMesh::Real R_mix = mixture.R_mix(Y);
       libMesh::Real rho = 1.0e-3;
       libMesh::Real T = 300;
       while( T <= 1000 )
         {
           libMesh::Real P = rho*R_mix*T;
           libMesh::Real cp_mix_computed =  evaluator.cp( T, P, Y );
           std::vector<libMesh::Real> species_cp(_active_species.size(),0.0);
           for( unsigned int s = 0; s < _active_species.size(); s++ )
             species_cp[s] = this->cp_exact(_active_species[s], T);
           libMesh::Real cp_mix_exact =
             ThermochemTestCommon::compute_mass_frac_mixture_prop( species_cp, Y );
           std::stringstream ss;
           ss << T;
           std::string message = "T = "+ss.str();
           libMesh::Real tol = TestingUtils::abs_tol_from_rel_tol( cp_mix_exact, rel_tol );
           CPPUNIT_ASSERT_DOUBLES_EQUAL_MESSAGE( message, cp_mix_exact, cp_mix_computed, tol );
           T += 100.0;
         }
     }
template<typename ThermoMixture , typename ThermoEvaluator > void GRINSTesting::NASAThermoTestBase::test_h_common (ThermoMixture & mixture, libMesh::Real rel_tol) inline
Definition at line 89 of file nasa_thermo_test_base.h.
References GRINSTesting::SpeciesTestBase::_active_species, GRINSTesting::TestingUtils::abs_tol_from_rel_tol(), and h_exact().
     {
       ThermoEvaluator evaluator( mixture );
       libMesh::Real tol;
       libMesh::Real T = 300;
       while( T <= 1000 )
         {
           std::stringstream ss;
           ss << T;
           std::string message = "T = "+ss.str();
           for( unsigned int s = 0; s < _active_species.size(); s++ )
             {
               libMesh::Real h_exact = this->h_exact(_active_species[s], T);
               libMesh::Real h_computed = evaluator.h_s( T, _active_species[s] );
               tol = TestingUtils::abs_tol_from_rel_tol( h_exact, rel_tol );
               CPPUNIT_ASSERT_DOUBLES_EQUAL_MESSAGE( message,
                                                     h_exact,
                                                     h_computed,
                                                     tol );
             }
           T += 100.0;
         }
     }
Member Data Documentation
std::vector<libMesh::Real> GRINSTesting::NASAThermoTestBase::_N2_200_1000_coeffs protected
Definition at line 145 of file nasa_thermo_test_base.h.
Referenced by GRINSTesting::NASA7ThermoTestBase::init_N2_coeffs(), GRINSTesting::NASA9ThermoTestBase::init_N2_coeffs(), and nasa_coeffs().
std::vector<libMesh::Real> GRINSTesting::NASAThermoTestBase::_N_200_1000_coeffs protected
Definition at line 149 of file nasa_thermo_test_base.h.
Referenced by GRINSTesting::NASA7ThermoTestBase::init_N_coeffs(), GRINSTesting::NASA9ThermoTestBase::init_N_coeffs(), and nasa_coeffs().
std::vector<libMesh::Real> GRINSTesting::NASAThermoTestBase::_NO_200_1000_coeffs protected
Definition at line 148 of file nasa_thermo_test_base.h.
Referenced by GRINSTesting::NASA7ThermoTestBase::init_NO_coeffs(), GRINSTesting::NASA9ThermoTestBase::init_NO_coeffs(), and nasa_coeffs().
std::vector<libMesh::Real> GRINSTesting::NASAThermoTestBase::_O2_200_1000_coeffs protected
Definition at line 146 of file nasa_thermo_test_base.h.
Referenced by GRINSTesting::NASA7ThermoTestBase::init_O2_coeffs(), GRINSTesting::NASA9ThermoTestBase::init_O2_coeffs(), and nasa_coeffs().
std::vector<libMesh::Real> GRINSTesting::NASAThermoTestBase::_O_200_1000_coeffs protected
Definition at line 147 of file nasa_thermo_test_base.h.
Referenced by GRINSTesting::NASA7ThermoTestBase::init_O_coeffs(), GRINSTesting::NASA9ThermoTestBase::init_O_coeffs(), and nasa_coeffs().
The documentation for this class was generated from the following file:
test/interface/nasa_thermo_test_base.h