GRINS-0.8.0: GRINS::ChemistryBuilder Class Reference
GRINS::ChemistryBuilder Class Reference
#include <chemistry_builder.h>
Public Member Functions
ChemistryBuilder ()
~ChemistryBuilder ()
template<typename ChemistryType >
void build_chemistry (const GetPot &input, const std::string &material, libMesh::UniquePtr< ChemistryType > &chem_ptr)
template<>
void build_chemistry (const GetPot &input, const std::string &material, libMesh::UniquePtr< CanteraMixture > &chem_ptr)
template<>
void build_chemistry (const GetPot &input, const std::string &material, libMesh::UniquePtr< AntiochChemistry > &chem_ptr)
Detailed Description
Definition at line 38 of file chemistry_builder.h.
Constructor & Destructor Documentation
GRINS::ChemistryBuilder::ChemistryBuilder () inline
Definition at line 41 of file chemistry_builder.h.
 {}
GRINS::ChemistryBuilder::~ChemistryBuilder () inline
Definition at line 42 of file chemistry_builder.h.
 {}
Member Function Documentation
template<typename ChemistryType > void GRINS::ChemistryBuilder::build_chemistry (const GetPot & input, const std::string & material, libMesh::UniquePtr< ChemistryType > & chem_ptr)
Referenced by GRINS::MoleFractionsDirichletBCFactory::add_mole_frac_to_mass_frac(), GRINS::QoIFactory::add_qoi(), GRINS::GasSolidCatalyticWallNeumannBCFactoryImpl::build_catalytic_wall(), GRINS::GasRecombinationCatalyticWallNeumannBCFactoryImpl::build_catalytic_wall(), GRINS::PrescribedMoleFractionsDirichletOldStyleBCFactory::convert_mole_fracs_and_add_to_func(), main(), and GRINSTesting::SpectroscopicAbsorptionTest::param_derivs().
template<> void GRINS::ChemistryBuilder::build_chemistry (const GetPot & input, const std::string & material, libMesh::UniquePtr< CanteraMixture > & chem_ptr)
Definition at line 45 of file chemistry_builder.C.
   {
     chem_ptr.reset( new CanteraMixture(input,material) );
   }
template<> void GRINS::ChemistryBuilder::build_chemistry (const GetPot & input, const std::string & material, libMesh::UniquePtr< AntiochChemistry > & chem_ptr)
Definition at line 54 of file chemistry_builder.C.
References GRINS::AntiochMixtureBuilderBase::build_chem_mix().
   {
     AntiochMixtureBuilderBase builder;
     libMesh::UniquePtr<Antioch::ChemicalMixture<libMesh::Real> > antioch_chem_mix
       = builder.build_chem_mix(input,material);
     chem_ptr.reset( new AntiochChemistry(antioch_chem_mix) );
   }
The documentation for this class was generated from the following files:
src/properties/include/grins/chemistry_builder.h
src/properties/src/chemistry_builder.C