GRINS-0.8.0: GRINS::ErrorEstimatorFactoryInitializer Class Reference
GRINS::ErrorEstimatorFactoryInitializer Class Reference
Initialize all ErrorEstimatorFactory objects.
#include <error_estimator_factory_initializer.h>
Public Member Functions
ErrorEstimatorFactoryInitializer ()
~ErrorEstimatorFactoryInitializer ()
Detailed Description
Initialize all ErrorEstimatorFactory objects.
To avoid symbol stripping from static linking, we use this class to initialize/register the ErrorEstimator factory objects.
Relevant discussion: http://stackoverflow.com/questions/5202142/static-variable-initialization-over-a-library
Definition at line 35 of file error_estimator_factory_initializer.h.
Constructor & Destructor Documentation
GRINS::ErrorEstimatorFactoryInitializer::ErrorEstimatorFactoryInitializer ()
Definition at line 39 of file error_estimator_factory_initializer.C.
References GRINS::StrategiesParsing::adjoint_refinement_error_estimator(), GRINS::StrategiesParsing::adjoint_residual_error_estimator(), GRINS::StrategiesParsing::kelly_error_estimator(), and GRINS::StrategiesParsing::patch_recovery_error_estimator().
   {
     static ErrorEstimatorFactoryBasic<libMesh::KellyErrorEstimator>
       grins_factory_kelly_error_est(StrategiesParsing::kelly_error_estimator());
     static ErrorEstimatorFactoryBasic<libMesh::PatchRecoveryErrorEstimator>
       grins_factory_patch_recovery_error_est(StrategiesParsing::patch_recovery_error_estimator());
     static AdjointRefinementErrorEstimatorFactory
       grins_factory_adjoint_refinement_estimator(StrategiesParsing::adjoint_refinement_error_estimator());
     static AdjointResidualErrorEstimatorFactory
       grins_factory_adjoint_residual_estimator(StrategiesParsing::adjoint_residual_error_estimator());
   }
GRINS::ErrorEstimatorFactoryInitializer::~ErrorEstimatorFactoryInitializer () inline
Definition at line 39 of file error_estimator_factory_initializer.h.
 {}
The documentation for this class was generated from the following files:
src/strategies/include/grins/error_estimator_factory_initializer.h
src/strategies/src/error_estimator_factory_initializer.C