GRINS-0.8.0: GRINS::VariablesParsing Class Reference
GRINS::VariablesParsing Class Reference
#include <variables_parsing.h>
Public Types
enum SECTION_TYPE { PHYSICS = 0, QOI }
Static Public Member Functions
static std::string displacement_section ()
static std::string pressure_section ()
static std::string temperature_section ()
static std::string thermo_pressure_section ()
static std::string turbulence_section ()
static std::string species_mass_fractions_section ()
static std::string velocity_section ()
static std::string single_var_section ()
static std::string scalar_var_section ()
static std::string variables_section ()
Helper function to encapsualte the overall [Variables] section name.
static std::string varnames_input_name (const std::string &subsection)
Helper function to encapsulate the names variable in the input file.
static std::string fe_family_input_name (const std::string &subsection)
Helper function to encaplusate fe_family input variable.
static std::string order_input_name (const std::string &subsection)
Helper function to encaplusate order input variable.
static std::string single_variable_name (const GetPot &input, const std::string &subsection_name, const SECTION_TYPE section_type)
static std::string scalar_variable_name (const GetPot &input, const std::string &subsection_name, const SECTION_TYPE section_type)
static std::string velocity_variable_name (const GetPot &input, const std::string &subsection_name, const SECTION_TYPE section_type)
static std::string temp_variable_name (const GetPot &input, const std::string &subsection_name, const SECTION_TYPE section_type)
static std::string press_variable_name (const GetPot &input, const std::string &subsection_name, const SECTION_TYPE section_type)
static std::string thermo_press_variable_name (const GetPot &input, const std::string &subsection_name, const SECTION_TYPE section_type)
static std::string turb_variable_name (const GetPot &input, const std::string &subsection_name, const SECTION_TYPE section_type)
static std::string disp_variable_name (const GetPot &input, const std::string &subsection_name, const SECTION_TYPE section_type)
static std::string species_mass_frac_variable_name (const GetPot &input, const std::string &subsection_name, const SECTION_TYPE section_type)
Static Private Member Functions
static std::string section_parse_var_name (const GetPot &input, const std::string &input_subsection_name, const std::string &input_var_name, const std::string &default_var_name, const SECTION_TYPE section_type)
Detailed Description
Definition at line 36 of file variables_parsing.h.
Member Enumeration Documentation
enum GRINS::VariablesParsing::SECTION_TYPE
Enumerator
PHYSICS
QOI
Definition at line 85 of file variables_parsing.h.
 { PHYSICS = 0, QOI };
Member Function Documentation
static std::string GRINS::VariablesParsing::disp_variable_name (const GetPot & input, const std::string & subsection_name, const SECTION_TYPE section_type) inline static
Definition at line 143 of file variables_parsing.h.
References displacement_section(), and section_parse_var_name().
     { return VariablesParsing::section_parse_var_name(input,
                                                       subsection_name,
                                                       "displacement_var_name",
                                                       VariablesParsing::displacement_section(),
                                                       section_type); }
static std::string GRINS::VariablesParsing::displacement_section () inline static
Definition at line 40 of file variables_parsing.h.
Referenced by GRINS::OldStyleBCBuilder::determine_variable_group(), disp_variable_name(), and GRINS::VariableFactoryInitializer::VariableFactoryInitializer().
     { return "Displacement"; }
static std::string GRINS::VariablesParsing::fe_family_input_name (const std::string & subsection) inline static
Helper function to encaplusate fe_family input variable.
Definition at line 78 of file variables_parsing.h.
References variables_section().
     { return VariablesParsing::variables_section()+"/"+subsection+"/fe_family"; }
static std::string GRINS::VariablesParsing::order_input_name (const std::string & subsection) inline static
Helper function to encaplusate order input variable.
Definition at line 82 of file variables_parsing.h.
References variables_section().
     { return VariablesParsing::variables_section()+"/"+subsection+"/order"; }
static std::string GRINS::VariablesParsing::press_variable_name (const GetPot & input, const std::string & subsection_name, const SECTION_TYPE section_type) inline static
Definition at line 119 of file variables_parsing.h.
References pressure_section(), and section_parse_var_name().
     { return VariablesParsing::section_parse_var_name(input,
                                                       subsection_name,
                                                       "pressure_var_name",
                                                       VariablesParsing::pressure_section(),
                                                       section_type); }
static std::string GRINS::VariablesParsing::pressure_section () inline static
Definition at line 43 of file variables_parsing.h.
Referenced by press_variable_name(), GRINSTesting::VariablesTest::test_var_constraint(), GRINSTesting::VariablesTest::test_variable_builder(), and GRINS::VariableFactoryInitializer::VariableFactoryInitializer().
     { return "Pressure"; }
static std::string GRINS::VariablesParsing::scalar_var_section () inline static
Definition at line 64 of file variables_parsing.h.
Referenced by scalar_variable_name(), and GRINS::VariableFactoryInitializer::VariableFactoryInitializer().
     { return "ScalarVariable"; }
static std::string GRINS::VariablesParsing::scalar_variable_name (const GetPot & input, const std::string & subsection_name, const SECTION_TYPE section_type) inline static
Definition at line 95 of file variables_parsing.h.
References scalar_var_section(), and section_parse_var_name().
     { return VariablesParsing::section_parse_var_name(input,
                                                       subsection_name,
                                                       "var_name",
                                                       VariablesParsing::scalar_var_section(),
                                                       section_type); }
std::string GRINS::VariablesParsing::section_parse_var_name (const GetPot & input, const std::string & input_subsection_name, const std::string & input_var_name, const std::string & default_var_name, const SECTION_TYPE section_type) static private
Definition at line 30 of file variables_parsing.C.
References PHYSICS, and QOI.
Referenced by disp_variable_name(), press_variable_name(), scalar_variable_name(), single_variable_name(), species_mass_frac_variable_name(), temp_variable_name(), thermo_press_variable_name(), turb_variable_name(), and velocity_variable_name().
   {
     std::string header;
     switch(section_type)
       {
       case(PHYSICS):
         {
           header = "Physics";
           break;
         }
       case(QOI):
         {
           header = "QoI";
           break;
         }
       default:
         libmesh_error_msg("ERROR: Invalid section value!");
       }
     return input(header+"/"+input_subsection_name+"/"+input_var_name, default_var_name );
   }
static std::string GRINS::VariablesParsing::single_var_section () inline static
Definition at line 61 of file variables_parsing.h.
Referenced by GRINS::OldStyleBCBuilder::determine_variable_group(), single_variable_name(), GRINSTesting::VariablesTest::test_variable_builder(), and GRINS::VariableFactoryInitializer::VariableFactoryInitializer().
     { return "SingleVariable"; }
static std::string GRINS::VariablesParsing::single_variable_name (const GetPot & input, const std::string & subsection_name, const SECTION_TYPE section_type) inline static
Definition at line 87 of file variables_parsing.h.
References section_parse_var_name(), and single_var_section().
     { return VariablesParsing::section_parse_var_name(input,
                                                       subsection_name,
                                                       "var_name",
                                                       VariablesParsing::single_var_section(),
                                                       section_type); }
static std::string GRINS::VariablesParsing::species_mass_frac_variable_name (const GetPot & input, const std::string & subsection_name, const SECTION_TYPE section_type) inline static
Definition at line 151 of file variables_parsing.h.
References section_parse_var_name(), and species_mass_fractions_section().
     { return VariablesParsing::section_parse_var_name(input,
                                                       subsection_name,
                                                       "species_mass_fracs_var_name",
                                                       VariablesParsing::species_mass_fractions_section(),
                                                       section_type); }
static std::string GRINS::VariablesParsing::species_mass_fractions_section () inline static
Definition at line 55 of file variables_parsing.h.
Referenced by GRINS::PrescribedMoleFractionsDirichletOldStyleBCFactory::add_funcs(), GRINS::OldStyleBCBuilder::determine_variable_group(), species_mass_frac_variable_name(), GRINSTesting::VariablesTest::test_variable_builder(), and GRINS::VariableFactoryInitializer::VariableFactoryInitializer().
     { return "SpeciesMassFractions"; }
static std::string GRINS::VariablesParsing::temp_variable_name (const GetPot & input, const std::string & subsection_name, const SECTION_TYPE section_type) inline static
Definition at line 111 of file variables_parsing.h.
References section_parse_var_name(), and temperature_section().
Referenced by GRINS::AverageNusseltNumber::init().
     { return VariablesParsing::section_parse_var_name(input,
                                                       subsection_name,
                                                       "temperature_var_name",
                                                       VariablesParsing::temperature_section(),
                                                       section_type); }
static std::string GRINS::VariablesParsing::temperature_section () inline static
Definition at line 46 of file variables_parsing.h.
Referenced by GRINS::OldStyleBCBuilder::determine_variable_group(), GRINS::CatalyticWallNeumannBCFactoryCommon< ImplType >::extract_temp_var(), temp_variable_name(), GRINSTesting::VariablesTest::test_variable_builder(), and GRINS::VariableFactoryInitializer::VariableFactoryInitializer().
     { return "Temperature"; }
static std::string GRINS::VariablesParsing::thermo_press_variable_name (const GetPot & input, const std::string & subsection_name, const SECTION_TYPE section_type) inline static
Definition at line 127 of file variables_parsing.h.
References section_parse_var_name(), and thermo_pressure_section().
Referenced by GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokesBase(), and GRINS::ReactingLowMachNavierStokesAbstract::ReactingLowMachNavierStokesAbstract().
     { return VariablesParsing::section_parse_var_name(input,
                                                       subsection_name,
                                                       "thermo_pressure_var_name",
                                                       VariablesParsing::thermo_pressure_section(),
                                                       section_type); }
static std::string GRINS::VariablesParsing::thermo_pressure_section () inline static
Definition at line 49 of file variables_parsing.h.
Referenced by thermo_press_variable_name(), and GRINS::VariableFactoryInitializer::VariableFactoryInitializer().
     { return "ThermoPressure"; }
static std::string GRINS::VariablesParsing::turb_variable_name (const GetPot & input, const std::string & subsection_name, const SECTION_TYPE section_type) inline static
Definition at line 135 of file variables_parsing.h.
References section_parse_var_name(), and turbulence_section().
     { return VariablesParsing::section_parse_var_name(input,
                                                       subsection_name,
                                                       "turbulence_var_name",
                                                       VariablesParsing::turbulence_section(),
                                                       section_type); }
static std::string GRINS::VariablesParsing::turbulence_section () inline static
Definition at line 52 of file variables_parsing.h.
Referenced by GRINS::OldStyleBCBuilder::determine_variable_group(), turb_variable_name(), and GRINS::VariableFactoryInitializer::VariableFactoryInitializer().
     { return "TurbulentViscosity"; }
static std::string GRINS::VariablesParsing::variables_section () inline static
Helper function to encapsualte the overall [Variables] section name.
Definition at line 68 of file variables_parsing.h.
Referenced by GRINS::ConstrainedPoints::ConstrainedPoints(), fe_family_input_name(), order_input_name(), GRINS::DefaultVariableBuilder::parse_fe_family(), GRINS::DefaultVariableBuilder::parse_fe_order(), GRINS::DefaultVariableBuilder::parse_subdomain_ids(), GRINS::DefaultVariableBuilder::parse_var_names(), GRINS::BuilderHelper::parse_var_sections_vector(), GRINS::DefaultVariableBuilder::parse_var_type(), and varnames_input_name().
     { return "Variables"; }
static std::string GRINS::VariablesParsing::varnames_input_name (const std::string & subsection) inline static
Helper function to encapsulate the names variable in the input file.
This is the full variable name to be passed to GetPot to read in user-supplied names for variables.
Definition at line 74 of file variables_parsing.h.
References variables_section().
     { return VariablesParsing::variables_section()+"/"+subsection+"/names"; }
static std::string GRINS::VariablesParsing::velocity_section () inline static
Definition at line 58 of file variables_parsing.h.
Referenced by GRINS::OldStyleBCBuilder::determine_variable_group(), GRINSTesting::VariablesTest::test_var_constraint(), GRINSTesting::VariablesTest::test_variable_builder(), GRINS::VariableFactoryInitializer::VariableFactoryInitializer(), and velocity_variable_name().
     { return "Velocity"; }
static std::string GRINS::VariablesParsing::velocity_variable_name (const GetPot & input, const std::string & subsection_name, const SECTION_TYPE section_type) inline static
Definition at line 103 of file variables_parsing.h.
References section_parse_var_name(), and velocity_section().
Referenced by GRINS::Vorticity::init().
     { return VariablesParsing::section_parse_var_name(input,
                                                       subsection_name,
                                                       "velocity_var_name",
                                                       VariablesParsing::velocity_section(),
                                                       section_type); }
The documentation for this class was generated from the following files:
src/variables/include/grins/variables_parsing.h
src/variables/src/variables_parsing.C