GRINS-0.8.0: GRINS::DefaultVariableBuilder Class Reference
GRINS::DefaultVariableBuilder Class Reference
#include <default_variable_builder.h>
Public Member Functions
DefaultVariableBuilder ()
~DefaultVariableBuilder ()
virtual void build_variables_impl (const GetPot &input, MultiphysicsSystem &system)
Implementation of Variable construction done in subclasses.
Public Member Functions inherited from GRINS::VariableBuilder
VariableBuilder ()
~VariableBuilder ()
Public Member Functions inherited from GRINS::BuilderHelper
BuilderHelper ()
~BuilderHelper ()
Protected Member Functions
void parse_var_names (const GetPot &input, const std::string &var_type, const std::string &var_section, std::vector< std::string > &var_names) const
Parse [Variable/<var_section>/names].
std::string parse_fe_family (const GetPot &input, const std::string &var_section, const std::string &var_type) const
Helper function to extract from input.
std::string parse_fe_order (const GetPot &input, const std::string &var_section, const std::string &var_type) const
Helper function to extract [Varaiable/<var_section>/order] from input.
std::string parse_var_type (const GetPot &input, const std::string &var_section) const
Parses the [Variable/<var_section>/var_type] option.
void parse_subdomain_ids (const std::set< libMesh::subdomain_id_type > &mesh_subdomain_ids, const GetPot &input, const std::string &var_section, std::set< libMesh::subdomain_id_type > &subdomain_ids)
Protected Member Functions inherited from GRINS::VariableBuilder
void add_variable_to_warehouse (SharedPtr< FEVariablesBase > &fe_var, const std::string &var_name)
Adds/registers the fe_var to VariableWarehouse.
void add_vars_to_system (MultiphysicsSystem &system, const std::vector< std::string > &var_names, const std::string &fe_family, const std::string &order, std::vector< VariableIndex > &var_indices, const std::set< libMesh::subdomain_id_type > &subdomain_ids)
Given the names, family, and order, this adds the variables to the system and populates var_indices.
SharedPtr< FEVariablesBase > build_fe_var (const std::string &var_type, const std::vector< std::string > &var_names, const std::vector< VariableIndex > &var_indices, const std::set< libMesh::subdomain_id_type > &subdomain_ids)
Sets appropriate data in the VariableFactoryAbstract and calls VariableFactoryAbstract::build()
Additional Inherited Members
Static Public Member Functions inherited from GRINS::VariableBuilder
static void build_variables (const GetPot &input, MultiphysicsSystem &system)
Static Public Member Functions inherited from GRINS::BuilderHelper
static void parse_var_sections (const GetPot &input, std::set< std::string > &sections)
Parses the input file for [Variables] first-level subsections.
static void parse_var_sections_vector (const GetPot &input, std::vector< std::string > &sections)
The same as parse_var_sections, except the result is returned in an std::vector.
Detailed Description
Definition at line 37 of file default_variable_builder.h.
Constructor & Destructor Documentation
GRINS::DefaultVariableBuilder::DefaultVariableBuilder () inline
Definition at line 41 of file default_variable_builder.h.
 {}
GRINS::DefaultVariableBuilder::~DefaultVariableBuilder () inline
Definition at line 42 of file default_variable_builder.h.
 {}
Member Function Documentation
void GRINS::DefaultVariableBuilder::build_variables_impl (const GetPot & input, MultiphysicsSystem & system) virtual
Implementation of Variable construction done in subclasses.
Implements GRINS::VariableBuilder.
Definition at line 38 of file default_variable_builder.C.
References GRINS::VariableBuilder::add_variable_to_warehouse(), GRINS::VariableBuilder::add_vars_to_system(), GRINS::VariableBuilder::build_fe_var(), parse_fe_family(), parse_fe_order(), parse_subdomain_ids(), parse_var_names(), GRINS::BuilderHelper::parse_var_sections_vector(), and parse_var_type().
Referenced by GRINS::VariableBuilder::build_variables().
   {
     std::set<libMesh::subdomain_id_type> mesh_subdomain_ids;
     const libMesh::MeshBase& mesh = system.get_mesh();
     // Note this does a full loop of the mesh, these are not cached
     // So we compute them once
     mesh.subdomain_ids(mesh_subdomain_ids);
     std::vector<std::string> var_sections;
     this->parse_var_sections_vector( input, var_sections );
     for( std::vector<std::string>::const_iterator var_sect = var_sections.begin();
          var_sect != var_sections.end(); ++var_sect )
       {
         // Convenience
         std::string var_section( *var_sect );
         // We construct based on the Variable type so we can name the Variables whatever we want
         // If var_type is invalid, that will be detected in the build_fe_var call, since
         // we feed the var_type to VariableFactoryAbstract::build.
         std::string var_type = this->parse_var_type( input, var_section );
         // Parse names
         std::vector<std::string> var_names;
         this->parse_var_names( input, var_type, var_section, var_names );
         // Parse FE family
         std::string fe_family = this->parse_fe_family( input, var_section, var_type );
         // Parse FE order
         std::string order = this->parse_fe_order( input, var_section, var_type );
         // Parse the subdomain_ids
         std::set<libMesh::subdomain_id_type> subdomain_ids;
         this->parse_subdomain_ids( mesh_subdomain_ids, input, var_section, subdomain_ids );
         // Add variables to system
         std::vector<VariableIndex> var_indices;
         this->add_vars_to_system( system, var_names, fe_family, order, var_indices, subdomain_ids );
         // Build FEVariablesBase object
         SharedPtr<FEVariablesBase> fe_var = this->build_fe_var( var_type, var_names, var_indices, subdomain_ids );
         // Add to VariableWarehouse
         this->add_variable_to_warehouse( fe_var, var_section );
       }
   }
std::string GRINS::DefaultVariableBuilder::parse_fe_family (const GetPot & input, const std::string & var_section, const std::string & var_type) const protected
Helper function to extract from input.
This will dispatch to the VariableFactory.
Definition at line 103 of file default_variable_builder.C.
References GRINS::VariableFactoryAbstract::parse_fe_family(), GRINS::FactoryWithGetPot< FEVariablesBase >::set_getpot(), GRINS::VariableFactoryAbstract::set_var_section(), and GRINS::VariablesParsing::variables_section().
Referenced by build_variables_impl().
   {
     VariableFactoryAbstract::set_getpot(input);
     VariableFactoryAbstract::set_var_section(VariablesParsing::variables_section()+"/"+var_section);
     return VariableFactoryAbstract::parse_fe_family(var_type);
   }
std::string GRINS::DefaultVariableBuilder::parse_fe_order (const GetPot & input, const std::string & var_section, const std::string & var_type) const protected
Helper function to extract [Varaiable/<var_section>/order] from input.
This will dispatch to the VariableFactory.
Definition at line 113 of file default_variable_builder.C.
References GRINS::VariableFactoryAbstract::parse_fe_order(), GRINS::FactoryWithGetPot< FEVariablesBase >::set_getpot(), GRINS::VariableFactoryAbstract::set_var_section(), and GRINS::VariablesParsing::variables_section().
Referenced by build_variables_impl().
   {
     VariableFactoryAbstract::set_getpot(input);
     VariableFactoryAbstract::set_var_section(VariablesParsing::variables_section()+"/"+var_section);
     return VariableFactoryAbstract::parse_fe_order(var_type);
   }
void GRINS::DefaultVariableBuilder::parse_subdomain_ids (const std::set< libMesh::subdomain_id_type > & mesh_subdomain_ids, const GetPot & input, const std::string & var_section, std::set< libMesh::subdomain_id_type > & subdomain_ids) protected
Definition at line 123 of file default_variable_builder.C.
References GRINS::VariablesParsing::variables_section().
Referenced by build_variables_impl().
   {
     std::string input_sec(VariablesParsing::variables_section()+"/"+var_section+"/enabled_subdomains");
     if( input.have_variable(input_sec) )
       {
         unsigned int invalid_id = std::numeric_limits<unsigned int>::max();
         unsigned int n_ids = input.vector_variable_size(input_sec);
         for( unsigned int i = 0; i < n_ids; i++ )
           {
             unsigned int id = input(input_sec,invalid_id,i);
             subdomain_ids.insert(id);
           }
         for( std::set<libMesh::subdomain_id_type>::const_iterator it = subdomain_ids.begin(); it != subdomain_ids.end(); ++it )
           if( mesh_subdomain_ids.find(*it) == mesh_subdomain_ids.end() )
             libmesh_error_msg("ERROR: Could not find subdomain " << *it << " in the mesh!");
       }
   }
void GRINS::DefaultVariableBuilder::parse_var_names (const GetPot & input, const std::string & var_type, const std::string & var_section, std::vector< std::string > & var_names) const protected
Parse [Variable/<var_section>/names].
Definition at line 89 of file default_variable_builder.C.
References GRINS::VariableFactoryAbstract::build_var_names(), GRINS::FactoryWithGetPot< FEVariablesBase >::set_getpot(), GRINS::VariableFactoryAbstract::set_var_section(), and GRINS::VariablesParsing::variables_section().
Referenced by build_variables_impl().
   {
     // Just in case
     var_names.clear();
     VariableFactoryAbstract::set_getpot(input);
     VariableFactoryAbstract::set_var_section(VariablesParsing::variables_section()+"/"+var_section);
     var_names = VariableFactoryAbstract::build_var_names(var_type);
   }
std::string GRINS::DefaultVariableBuilder::parse_var_type (const GetPot & input, const std::string & var_section) const inline protected
Parses the [Variable/<var_section>/var_type] option.
The var_type is how we distinguish between the Variables so that the user can name the section whatever they want. If var_type is not present, then we assume that the var_type is actually the the section name, var_section.
Definition at line 72 of file default_variable_builder.h.
References GRINS::VariablesParsing::variables_section().
Referenced by build_variables_impl().
     { std::string input_sec = VariablesParsing::variables_section()+"/"+var_section+"/type";
       return input(input_sec,var_section); }
The documentation for this class was generated from the following files:
src/variables/include/grins/default_variable_builder.h
src/variables/src/default_variable_builder.C