GRINS-0.7.0: GRINS::ConstantCatalycity Class Reference
GRINS::ConstantCatalycity Class Reference
#include <constant_catalycity.h>
Public Member Functions
ConstantCatalycity (const libMesh::Real gamma)
virtual ~ConstantCatalycity ()
virtual libMesh::Real operator() (const libMesh::Real T) const
virtual libMesh::Real dT (const libMesh::Real T) const
virtual void set_params (const std::vector< libMesh::Real > &params)
virtual CatalycityBase * clone () const
Creates a new copy of the current class.
Public Member Functions inherited from GRINS::CatalycityBase
CatalycityBase ()
virtual ~CatalycityBase ()
Protected Attributes
libMesh::Real _gamma
Private Member Functions
ConstantCatalycity ()
Detailed Description
Definition at line 33 of file constant_catalycity.h.
Constructor & Destructor Documentation
GRINS::ConstantCatalycity::ConstantCatalycity (const libMesh::Real gamma)
Definition at line 30 of file constant_catalycity.C.
     : _gamma(gamma)
   {
     return;
   }
GRINS::ConstantCatalycity::~ConstantCatalycity () virtual
Definition at line 36 of file constant_catalycity.C.
   {
     return;
   }
GRINS::ConstantCatalycity::ConstantCatalycity () private
Referenced by clone().
Member Function Documentation
CatalycityBase * GRINS::ConstantCatalycity::clone () const virtual
Creates a new copy of the current class.
A raw pointer is returned and it is assumed the user will take ownership and worry about memory management.
Implements GRINS::CatalycityBase.
Definition at line 60 of file constant_catalycity.C.
References ConstantCatalycity().
   {
     return new ConstantCatalycity( *this );
   }
libMesh::Real GRINS::ConstantCatalycity::dT (const libMesh::Real T) const virtual
Implements GRINS::CatalycityBase.
Definition at line 46 of file constant_catalycity.C.
Referenced by main().
   {
     return 0.0;
   }
libMesh::Real GRINS::ConstantCatalycity::operator() (const libMesh::Real T) const virtual
Implements GRINS::CatalycityBase.
Definition at line 41 of file constant_catalycity.C.
References _gamma.
   {
     return _gamma;
   }
void GRINS::ConstantCatalycity::set_params (const std::vector< libMesh::Real > & params) virtual
Implements GRINS::CatalycityBase.
Definition at line 51 of file constant_catalycity.C.
References _gamma.
Referenced by main().
   {
     libmesh_assert_equal_to( params.size(), 1 );
     _gamma = params[0];
     return;
   }
Member Data Documentation
libMesh::Real GRINS::ConstantCatalycity::_gamma protected
Definition at line 54 of file constant_catalycity.h.
Referenced by operator()(), and set_params().
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/constant_catalycity.h
src/boundary_conditions/src/constant_catalycity.C