GRINS-0.8.0: GRINS::CanteraMixture Class Reference
GRINS::CanteraMixture Class Reference
Wrapper class for storing state for computing thermochemistry and transport properties using Cantera.
#include <cantera_mixture.h>
Public Types
typedef CanteraMixture ChemistryParent
This is basically dummy, but is needed for template games elsewhere.
Public Member Functions
CanteraMixture (const GetPot &input, const std::string &material)
~CanteraMixture ()
Cantera::IdealGasMix & get_chemistry ()
const Cantera::IdealGasMix & get_chemistry () const
Cantera::Transport & get_transport ()
libMesh::Real M (unsigned int species) const
libMesh::Real M_mix (const std::vector< libMesh::Real > &mass_fractions) const
libMesh::Real R (unsigned int species) const
libMesh::Real R_mix (const std::vector< libMesh::Real > &mass_fractions) const
libMesh::Real X (unsigned int species, libMesh::Real M, libMesh::Real mass_fraction) const
void X (libMesh::Real M, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &mole_fractions) const
unsigned int n_species () const
unsigned int species_index (const std::string &species_name) const
std::string species_name (unsigned int species_index) const
const CanteraMixture & chemistry () const
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Member Functions
std::string parse_mixture (const GetPot &input, const std::string &material)
Protected Attributes
libMesh::UniquePtr< Cantera::IdealGasMix > _cantera_gas
libMesh::UniquePtr< Cantera::Transport > _cantera_transport
Private Member Functions
CanteraMixture ()
Additional Inherited Members
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Detailed Description
Wrapper class for storing state for computing thermochemistry and transport properties using Cantera.
This class is expected to be constructed before threads have been forked and will live during the whole program. Note that this documentation will always be built regardless if Cantera is included in the GRINS build or not. Check configure output to confirm that Cantera was included in the build if you wish to use it.
Definition at line 65 of file cantera_mixture.h.
Member Typedef Documentation
typedef CanteraMixture GRINS::CanteraMixture::ChemistryParent
This is basically dummy, but is needed for template games elsewhere.
Definition at line 99 of file cantera_mixture.h.
Constructor & Destructor Documentation
GRINS::CanteraMixture::CanteraMixture (const GetPot & input, const std::string & material)
Definition at line 41 of file cantera_mixture.C.
References _cantera_gas, _cantera_transport, GRINS::MaterialsParsing::parse_chemical_kinetics_datafile_name(), and parse_mixture().
     : ParameterUser("CanteraMixture")
   {
     const std::string cantera_chem_file = MaterialsParsing::parse_chemical_kinetics_datafile_name( input, material );
     std::string mixture = this->parse_mixture(input,material);
     try
       {
         _cantera_gas.reset( new Cantera::IdealGasMix( cantera_chem_file, mixture ) );
       }
     catch(Cantera::CanteraError)
       {
         Cantera::showErrors(std::cerr);
         libmesh_error();
       }
     try
       {
         _cantera_transport.reset( Cantera::newTransportMgr("Mix", _cantera_gas.get()) );
       }
     catch(Cantera::CanteraError)
       {
         Cantera::showErrors(std::cerr);
         libmesh_error();
       }
     return;
   }
GRINS::CanteraMixture::~CanteraMixture ()
Definition at line 71 of file cantera_mixture.C.
   {
     return;
   }
GRINS::CanteraMixture::CanteraMixture () private
Member Function Documentation
const CanteraMixture & GRINS::CanteraMixture::chemistry () const inline
Definition at line 176 of file cantera_mixture.h.
   {
     return *this;
   }
Cantera::IdealGasMix & GRINS::CanteraMixture::get_chemistry () inline
Definition at line 117 of file cantera_mixture.h.
References _cantera_gas.
   {
     return (*_cantera_gas);
   }
const Cantera::IdealGasMix & GRINS::CanteraMixture::get_chemistry () const inline
Definition at line 123 of file cantera_mixture.h.
References _cantera_gas.
   {
     return (*_cantera_gas);
   }
Cantera::Transport & GRINS::CanteraMixture::get_transport () inline
Definition at line 129 of file cantera_mixture.h.
References _cantera_transport.
   {
     return (*_cantera_transport);
   }
libMesh::Real GRINS::CanteraMixture::M (unsigned int species) const inline
Definition at line 135 of file cantera_mixture.h.
References _cantera_gas.
Referenced by GRINS::CanteraEvaluator::M(), M_mix(), and X().
   {
     // Cantera returns molar mass in kg/kmol
     return _cantera_gas->molecularWeight(species);
   }
libMesh::Real GRINS::CanteraMixture::M_mix (const std::vector< libMesh::Real > & mass_fractions) const
Definition at line 99 of file cantera_mixture.C.
References _cantera_gas, and M().
Referenced by GRINS::CanteraEvaluator::M_mix(), and main().
   {
     libmesh_assert_equal_to( mass_fractions.size(), _cantera_gas->nSpecies() );
     libMesh::Real M = 0;
     for( unsigned int s = 0; s < mass_fractions.size(); s++ )
       {
         M += mass_fractions[s]/(this->M(s));
       }
     return 1.0/M;
   }
unsigned int GRINS::CanteraMixture::n_species () const inline
Definition at line 158 of file cantera_mixture.h.
References _cantera_gas.
Referenced by main().
   {
     return _cantera_gas->nSpecies();
   }
std::string GRINS::CanteraMixture::parse_mixture (const GetPot & input, const std::string & material) protected
Definition at line 76 of file cantera_mixture.C.
References GRINS::MaterialsParsing::dep_input_warning().
Referenced by CanteraMixture().
   {
     std::string mixture;
     if( input.have_variable("Physics/Chemistry/mixture") )
       {
         MaterialsParsing::dep_input_warning("Physics/Chemistry/mixture",
                                             "GasMixture/Cantera/gas_mixture" );
         mixture = input( "Physics/Chemistry/mixture", "DIE!" );
       }
     else if( input.have_variable("Materials/"+material+"/GasMixture/Cantera/gas_mixture") )
       {
         mixture = input("Materials/"+material+"/GasMixture/Cantera/gas_mixture", "DIE!");
       }
     else
       {
         libmesh_error_msg("ERROR: Could not find valid input for Cantera gas_mixture!");
       }
     return mixture;
   }
libMesh::Real GRINS::CanteraMixture::R (unsigned int species) const inline
Definition at line 142 of file cantera_mixture.h.
References _cantera_gas.
Referenced by GRINS::CanteraThermodynamics::h(), GRINS::CanteraEvaluator::R(), and R_mix().
   {
     // Cantera::GasConstant in J/kmol-K
     // Cantera returns molar mass in kg/kmol
     return Cantera::GasConstant/_cantera_gas->molecularWeight(species);
   }
libMesh::Real GRINS::CanteraMixture::R_mix (const std::vector< libMesh::Real > & mass_fractions) const
Definition at line 112 of file cantera_mixture.C.
References _cantera_gas, and R().
Referenced by main(), and GRINS::CanteraEvaluator::R_mix().
   {
     libmesh_assert_equal_to( mass_fractions.size(), _cantera_gas->nSpecies() );
     libMesh::Real R = 0.0;
     for( unsigned int s = 0; s < mass_fractions.size(); s++ )
       {
         R += mass_fractions[s]*this->R(s);
       }
     return R;
   }
unsigned int GRINS::CanteraMixture::species_index (const std::string & species_name) const inline
Definition at line 164 of file cantera_mixture.h.
References _cantera_gas.
Referenced by GRINS::CanteraEvaluator::species_index().
   {
     return _cantera_gas->speciesIndex( species_name );
   }
std::string GRINS::CanteraMixture::species_name (unsigned int species_index) const inline
Definition at line 170 of file cantera_mixture.h.
References _cantera_gas.
Referenced by main(), and GRINS::CanteraEvaluator::species_name().
   {
     return _cantera_gas->speciesName( species_index );
   }
libMesh::Real GRINS::CanteraMixture::X (unsigned int species, libMesh::Real M, libMesh::Real mass_fraction) const inline
Definition at line 150 of file cantera_mixture.h.
References M().
Referenced by main(), GRINS::CanteraEvaluator::X(), and X().
   {
     return mass_fraction*M_mix/this->M(species);
   }
void GRINS::CanteraMixture::X (libMesh::Real M, const std::vector< libMesh::Real > & mass_fractions, std::vector< libMesh::Real > & mole_fractions) const
Definition at line 125 of file cantera_mixture.C.
References _cantera_gas, and X().
   {
     libmesh_assert_equal_to( mass_fractions.size(), _cantera_gas->nSpecies() );
     libmesh_assert_equal_to( mole_fractions.size(), mass_fractions.size() );
     for( unsigned int s = 0; s < mass_fractions.size(); s++ )
       {
         mole_fractions[s] = this->X(s, M_mix, mass_fractions[s]);
       }
     return;
   }
Member Data Documentation
libMesh::UniquePtr<Cantera::IdealGasMix> GRINS::CanteraMixture::_cantera_gas protected
Definition at line 103 of file cantera_mixture.h.
Referenced by CanteraMixture(), get_chemistry(), M(), M_mix(), n_species(), R(), R_mix(), species_index(), species_name(), and X().
libMesh::UniquePtr<Cantera::Transport> GRINS::CanteraMixture::_cantera_transport protected
Definition at line 105 of file cantera_mixture.h.
Referenced by CanteraMixture(), and get_transport().
The documentation for this class was generated from the following files:
src/properties/include/grins/cantera_mixture.h
src/properties/src/cantera_mixture.C