GRINS-0.8.0: GRINS::AntiochConstantTransportMixtureBuilder Class Reference
GRINS::AntiochConstantTransportMixtureBuilder Class Reference
#include <antioch_constant_transport_mixture_builder.h>
Public Member Functions
AntiochConstantTransportMixtureBuilder ()
~AntiochConstantTransportMixtureBuilder ()
template<typename KineticsThermoCurveFit , typename Conductivity >
libMesh::UniquePtr< AntiochConstantTransportMixture< KineticsThermoCurveFit, Conductivity > > build_mixture (const GetPot &input, const std::string &material)
libMesh::UniquePtr< ConstantViscosity > build_constant_viscosity (const GetPot &input, const std::string &material)
template<typename Conductivity >
libMesh::UniquePtr< Conductivity > build_constant_conductivity (const GetPot &input, const std::string &material)
libMesh::UniquePtr< Antioch::ConstantLewisDiffusivity< libMesh::Real > > build_constant_lewis_diff (const GetPot &input, const std::string &material)
Public Member Functions inherited from GRINS::AntiochMixtureBuilderBase
AntiochMixtureBuilderBase ()
~AntiochMixtureBuilderBase ()
libMesh::UniquePtr< Antioch::ChemicalMixture< libMesh::Real > > build_chem_mix (const GetPot &input, const std::string &material)
libMesh::UniquePtr< Antioch::ReactionSet< libMesh::Real > > build_reaction_set (const GetPot &input, const std::string &material, const Antioch::ChemicalMixture< libMesh::Real > &chem_mix)
template<typename KineticsThermoCurveFit >
libMesh::UniquePtr< Antioch::NASAThermoMixture< libMesh::Real, KineticsThermoCurveFit > > build_nasa_thermo_mix (const GetPot &input, const std::string &material, const Antioch::ChemicalMixture< libMesh::Real > &chem_mix)
template<typename KineticsThermoCurveFit >
libMesh::UniquePtr< AntiochMixture< KineticsThermoCurveFit > > build_antioch_mixture (const GetPot &input, const std::string &material)
libMesh::Real parse_min_T (const GetPot &input, const std::string &material)
bool parse_clip_negative_rho (const GetPot &input, const std::string &material)
Private Member Functions
libMesh::UniquePtr< ConstantConductivity > specialized_build_conductivity (const GetPot &input, const std::string &material, conductivity_type< ConstantConductivity >)
libMesh::UniquePtr< ConstantPrandtlConductivity > specialized_build_conductivity (const GetPot &input, const std::string &material, conductivity_type< ConstantPrandtlConductivity >)
Additional Inherited Members
Protected Member Functions inherited from GRINS::AntiochMixtureBuilderBase
void parse_nasa_data (Antioch::NASAThermoMixture< libMesh::Real, Antioch::CEACurveFit< libMesh::Real > > &nasa_mixture, const GetPot &input, const std::string &material)
Detailed Description
Definition at line 47 of file antioch_constant_transport_mixture_builder.h.
Constructor & Destructor Documentation
GRINS::AntiochConstantTransportMixtureBuilder::AntiochConstantTransportMixtureBuilder () inline
Definition at line 50 of file antioch_constant_transport_mixture_builder.h.
 {}
GRINS::AntiochConstantTransportMixtureBuilder::~AntiochConstantTransportMixtureBuilder () inline
Definition at line 51 of file antioch_constant_transport_mixture_builder.h.
 {}
Member Function Documentation
template<typename Conductivity > libMesh::UniquePtr<Conductivity> GRINS::AntiochConstantTransportMixtureBuilder::build_constant_conductivity (const GetPot & input, const std::string & material) inline
Definition at line 65 of file antioch_constant_transport_mixture_builder.h.
References specialized_build_conductivity().
Referenced by GRINSTesting::AntiochConstantTransportMixtureBuilderTest::test_build_constant_conductivity(), and GRINSTesting::AntiochConstantTransportMixtureBuilderTest::test_build_constant_prandtl_conductivity().
     {
       return specialized_build_conductivity( input, material, conductivity_type<Conductivity>() );
     }
libMesh::UniquePtr<Antioch::ConstantLewisDiffusivity<libMesh::Real> > GRINS::AntiochConstantTransportMixtureBuilder::build_constant_lewis_diff (const GetPot & input, const std::string & material) inline
Definition at line 71 of file antioch_constant_transport_mixture_builder.h.
References GRINS::MaterialsParsing::parse_lewis_number().
Referenced by build_mixture(), and GRINSTesting::AntiochConstantTransportMixtureBuilderTest::test_build_constant_lewis_diff().
     {
       libMesh::Real Le = MaterialsParsing::parse_lewis_number(input,material);
       return libMesh::UniquePtr<Antioch::ConstantLewisDiffusivity<libMesh::Real> >
         ( new Antioch::ConstantLewisDiffusivity<libMesh::Real>(Le) );
     }
libMesh::UniquePtr<ConstantViscosity> GRINS::AntiochConstantTransportMixtureBuilder::build_constant_viscosity (const GetPot & input, const std::string & material) inline
Definition at line 58 of file antioch_constant_transport_mixture_builder.h.
Referenced by build_mixture(), and GRINSTesting::AntiochConstantTransportMixtureBuilderTest::test_build_constant_viscosity().
     {
       return libMesh::UniquePtr<ConstantViscosity>( new ConstantViscosity(input,material) );
     }
template<typename KineticsThermoCurveFit , typename Conductivity > libMesh::UniquePtr< AntiochConstantTransportMixture< KineticsThermoCurveFit, Conductivity > > GRINS::AntiochConstantTransportMixtureBuilder::build_mixture (const GetPot & input, const std::string & material) inline
Definition at line 99 of file antioch_constant_transport_mixture_builder.h.
References GRINS::AntiochMixtureBuilderBase::build_chem_mix(), build_constant_lewis_diff(), build_constant_viscosity(), GRINS::AntiochMixtureBuilderBase::build_reaction_set(), GRINS::AntiochMixtureBuilderBase::parse_clip_negative_rho(), and GRINS::AntiochMixtureBuilderBase::parse_min_T().
Referenced by GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_const_physics_ptr(), GRINSTesting::AntiochConstantTransportMixtureBuilderTest::test_build_cea_constcond_mix(), and GRINSTesting::AntiochConstantTransportMixtureBuilderTest::test_build_cea_constpr_mix().
   {
     libMesh::UniquePtr<Antioch::ChemicalMixture<libMesh::Real> > chem_mix =
       this->build_chem_mix(input,material);
     libMesh::UniquePtr<Antioch::ReactionSet<libMesh::Real> > reaction_set =
       this->build_reaction_set(input,material,*chem_mix);
     libMesh::UniquePtr<Antioch::NASAThermoMixture<libMesh::Real,KineticsThermoCurveFit> > kinetics_thermo =
       this->build_nasa_thermo_mix<KineticsThermoCurveFit>(input,material,*chem_mix);
     libMesh::UniquePtr<ConstantViscosity> visc =
       this->build_constant_viscosity(input,material);
     libMesh::UniquePtr<Conductivity> cond =
       this->build_constant_conductivity<Conductivity>(input,material);
     libMesh::UniquePtr<Antioch::ConstantLewisDiffusivity<libMesh::Real> > diff =
       this->build_constant_lewis_diff(input,material);
     libMesh::Real min_T = this->parse_min_T(input,material);
     bool clip_negative_rho = this->parse_clip_negative_rho(input,material);
     return libMesh::UniquePtr<AntiochConstantTransportMixture<KineticsThermoCurveFit,Conductivity> >
       ( new AntiochConstantTransportMixture<KineticsThermoCurveFit,Conductivity>
         (chem_mix, reaction_set, kinetics_thermo, visc, cond, diff, min_T, clip_negative_rho) );
   }
libMesh::UniquePtr<ConstantConductivity> GRINS::AntiochConstantTransportMixtureBuilder::specialized_build_conductivity (const GetPot & input, const std::string & material, conductivity_type< ConstantConductivity >) inline private
Definition at line 81 of file antioch_constant_transport_mixture_builder.h.
Referenced by build_constant_conductivity().
     {
       return libMesh::UniquePtr<ConstantConductivity>( new ConstantConductivity(input,material) );
     }
libMesh::UniquePtr<ConstantPrandtlConductivity> GRINS::AntiochConstantTransportMixtureBuilder::specialized_build_conductivity (const GetPot & input, const std::string & material, conductivity_type< ConstantPrandtlConductivity >) inline private
Definition at line 88 of file antioch_constant_transport_mixture_builder.h.
     {
       return libMesh::UniquePtr<ConstantPrandtlConductivity>( new ConstantPrandtlConductivity(input,material) );
     }
The documentation for this class was generated from the following file:
src/properties/include/grins/antioch_constant_transport_mixture_builder.h