GRINS-0.7.0: GRINS::SolverFactory Class Reference
GRINS::SolverFactory Class Reference
This object handles constructing the solver to be used.
#include <solver_factory.h>
Public Member Functions
SolverFactory ()
virtual ~SolverFactory ()
virtual SharedPtr< GRINS::Solver > build (const GetPot &input)
Builds GRINS::Solver object.
Detailed Description
This object handles constructing the solver to be used.
To allow the user to easily extend the (limited) available solvers, the solver construction is handled in this object.
Definition at line 40 of file solver_factory.h.
Constructor & Destructor Documentation
GRINS::SolverFactory::SolverFactory () inline
Definition at line 44 of file solver_factory.h.
 {};
virtual GRINS::SolverFactory::~SolverFactory () inline virtual
Definition at line 45 of file solver_factory.h.
 {};
Member Function Documentation
SharedPtr< Solver > GRINS::SolverFactory::build (const GetPot & input) virtual
Builds GRINS::Solver object.
Users should override this method to construct their own solvers.
Definition at line 41 of file solver_factory.C.
References GRINS::SolverParsing::solver_type(), GRINS::SolverNames::steady_mesh_adaptive_solver(), GRINS::SolverNames::steady_solver(), GRINS::SolverNames::unsteady_mesh_adaptive_solver(), and GRINS::SolverNames::unsteady_solver().
   {
     std::string solver_type = SolverParsing::solver_type(input);
     SharedPtr<Solver> solver;  // Effectively NULL
     if(solver_type == SolverNames::unsteady_solver() )
       {
         solver.reset( new UnsteadySolver(input) );
       }
     else if( solver_type == SolverNames::steady_solver() )
       {
         solver.reset( new SteadySolver(input) );
       }
     else if( solver_type == SolverNames::steady_mesh_adaptive_solver() )
       {
         solver.reset( new SteadyMeshAdaptiveSolver(input) );
       }
     else if( solver_type == SolverNames::unsteady_mesh_adaptive_solver() )
       {
         solver.reset( new UnsteadyMeshAdaptiveSolver(input) );
       }
     else
       {
         libmesh_error_msg("Invalid solver_type: "+solver_type);
       }
     return solver;
   }
The documentation for this class was generated from the following files:
src/solver/include/grins/solver_factory.h
src/solver/src/solver_factory.C