GRINS-0.8.0: GRINS::CatalycityFactoryAbstract Class Reference
GRINS::CatalycityFactoryAbstract Class Reference abstract
#include <catalycity_factory_abstract.h>
Public Member Functions
CatalycityFactoryAbstract (const std::string &physics_name)
~CatalycityFactoryAbstract ()
Public Member Functions inherited from GRINS::FactoryWithGetPot< CatalycityBase >
FactoryWithGetPot (const std::string &name)
~FactoryWithGetPot ()
Public Member Functions inherited from GRINS::FactoryAbstract< CatalycityBase >
virtual ~FactoryAbstract ()
Static Public Member Functions
static void set_section (const std::string &section)
Static Public Member Functions inherited from GRINS::FactoryWithGetPot< CatalycityBase >
static void set_getpot (const GetPot &input)
Static Public Member Functions inherited from GRINS::FactoryAbstract< CatalycityBase >
static libMesh::UniquePtr< CatalycityBase > build (const std::string &name)
Use this method to build objects of type Base.
Protected Member Functions
virtual libMesh::UniquePtr< CatalycityBase > build_catalycity (const GetPot &input, const std::string &section)=0
virtual void check_state () const
Helper function to reduce code duplication.
virtual void reset_state ()
Helper function to reduce code duplication.
Protected Member Functions inherited from GRINS::FactoryAbstract< CatalycityBase >
FactoryAbstract (const std::string &name)
Constructor is protected. Use the build() method to construct Base objects.
Static Protected Attributes
static std::string _section = std::string("DIE!")
Static Protected Attributes inherited from GRINS::FactoryWithGetPot< CatalycityBase >
static const GetPot * _input
We store only a raw pointer here because we can't make a copy.
Private Member Functions
virtual libMesh::UniquePtr< CatalycityBase > create ()
Subclasses implement the actual construction of the Base object in create().
Additional Inherited Members
Static Protected Member Functions inherited from GRINS::FactoryAbstract< CatalycityBase >
static FactoryAbstract< CatalycityBase > & get_factory (const std::string &name)
Helper method that looks up the factory and returns it if present, or error if it's not.
static DerivedType & get_factory_subclass (const std::string &name)
Like get_factory, but will downcast to DerivedType.
static std::map< std::string, FactoryAbstract< CatalycityBase > * > & factory_map ()
Detailed Description
Definition at line 38 of file catalycity_factory_abstract.h.
Constructor & Destructor Documentation
GRINS::CatalycityFactoryAbstract::CatalycityFactoryAbstract (const std::string & physics_name) inline
Definition at line 41 of file catalycity_factory_abstract.h.
       : FactoryWithGetPot<CatalycityBase>(physics_name)
     {}
GRINS::CatalycityFactoryAbstract::~CatalycityFactoryAbstract () inline
Definition at line 45 of file catalycity_factory_abstract.h.
 {};
Member Function Documentation
virtual libMesh::UniquePtr<CatalycityBase> GRINS::CatalycityFactoryAbstract::build_catalycity (const GetPot & input, const std::string & section) protected pure virtual
Implemented in GRINS::PowerLawCatalycityFactory, GRINS::ArrheniusCatalycityFactory, GRINS::ConstantCatalycityFactory, and GRINS::CatalycityFactoryOldStyleBase.
Referenced by create().
void GRINS::CatalycityFactoryAbstract::check_state () const inline protected virtual
Helper function to reduce code duplication.
Reimplemented in GRINS::CatalycityFactoryOldStyleBase.
Definition at line 81 of file catalycity_factory_abstract.h.
References GRINS::FactoryWithGetPot< CatalycityBase >::_input, and _section.
Referenced by GRINS::CatalycityFactoryOldStyleBase::check_state(), and create().
   {
     if( !_input )
       libmesh_error_msg("ERROR: must call set_getpot() before building Catalycity!");
     if( _section == std::string("DIE!") )
       libmesh_error_msg("ERROR: must call set_section() before building Catalycity!");
   }
libMesh::UniquePtr< CatalycityBase > GRINS::CatalycityFactoryAbstract::create () inline private virtual
Subclasses implement the actual construction of the Base object in create().
Implements GRINS::FactoryAbstract< CatalycityBase >.
Definition at line 69 of file catalycity_factory_abstract.h.
References GRINS::FactoryWithGetPot< CatalycityBase >::_input, _section, build_catalycity(), check_state(), and reset_state().
   {
     this->check_state();
     libMesh::UniquePtr<CatalycityBase> new_catalycity = this->build_catalycity( *_input, _section );
     this->reset_state();
     return new_catalycity;
   }
void GRINS::CatalycityFactoryAbstract::reset_state () inline protected virtual
Helper function to reduce code duplication.
Reimplemented in GRINS::CatalycityFactoryOldStyleBase.
Definition at line 91 of file catalycity_factory_abstract.h.
References _section.
Referenced by create(), and GRINS::CatalycityFactoryOldStyleBase::reset_state().
   {
     // Reset for error checking
     _section = std::string("DIE!");
   }
static void GRINS::CatalycityFactoryAbstract::set_section (const std::string & section) inline static
Definition at line 47 of file catalycity_factory_abstract.h.
References _section.
Referenced by GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType >::build_catalycity(), and GRINS::CatalyticWallNeumannBCFactoryBase< ImplType >::build_catalycity().
     { _section = section; }
Member Data Documentation
std::string GRINS::CatalycityFactoryAbstract::_section = std::string("DIE!") static protected
Definition at line 61 of file catalycity_factory_abstract.h.
Referenced by check_state(), create(), reset_state(), and set_section().
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/catalycity_factory_abstract.h
src/boundary_conditions/src/catalycity_factory_abstract.C