GRINS-0.8.0: GRINS::FactoryAbstract< Base > Class Template Reference
GRINS::FactoryAbstract< Base > Class Template Reference abstract
Abstract factory.
#include <factory_abstract.h>
Public Member Functions
virtual ~FactoryAbstract ()
virtual libMesh::UniquePtr< Base > create ()=0
Subclasses implement the actual construction of the Base object in create().
Static Public Member Functions
static libMesh::UniquePtr< Base > build (const std::string &name)
Use this method to build objects of type Base.
Protected Member Functions
FactoryAbstract (const std::string &name)
Constructor is protected. Use the build() method to construct Base objects.
template<>
std::map< std::string, FactoryAbstract< CatalycityBase > * > & factory_map ()
template<>
std::map< std::string, FactoryAbstract< libMesh::DirichletBoundary > * > & factory_map ()
template<>
std::map< std::string, FactoryAbstract< NeumannBCContainer > * > & factory_map ()
template<>
std::map< std::string, FactoryAbstract< Physics > * > & factory_map ()
template<>
std::map< std::string, FactoryAbstract< Solver > * > & factory_map ()
template<>
std::map< std::string, FactoryAbstract< libMesh::ErrorEstimator > * > & factory_map ()
template<>
std::map< std::string, FactoryAbstract< FEVariablesBase > * > & factory_map ()
Static Protected Member Functions
static FactoryAbstract< Base > & get_factory (const std::string &name)
Helper method that looks up the factory and returns it if present, or error if it's not.
template<typename DerivedType >
static DerivedType & get_factory_subclass (const std::string &name)
Like get_factory, but will downcast to DerivedType.
static std::map< std::string, FactoryAbstract< Base > * > & factory_map ()
Detailed Description
template<typename Base>
class GRINS::FactoryAbstract< Base >
Abstract factory.
Copied from libMesh::Factory. The main difference is the helper method to fetch the factory (this was moved out of the build() function in libMesh::Factory). That is useful so subclasses can additional static methods that dispatch to virtual methods of the subclass.
Definition at line 45 of file factory_abstract.h.
Constructor & Destructor Documentation
template<typename Base> virtual GRINS::FactoryAbstract< Base >::~FactoryAbstract () inline virtual
Definition at line 49 of file factory_abstract.h.
 {}
template<class Base > GRINS::FactoryAbstract< Base >::FactoryAbstract (const std::string & name) inline protected
Constructor is protected. Use the build() method to construct Base objects.
Definition at line 75 of file factory_abstract.h.
   {
     // Make sure we haven't already added this name
     // to the map
     libmesh_assert (!factory_map().count(name));
     factory_map()[name] = this;
   }
Member Function Documentation
template<class Base > libMesh::UniquePtr< Base > GRINS::FactoryAbstract< Base >::build (const std::string & name) inline static
Use this method to build objects of type Base.
Definition at line 86 of file factory_abstract.h.
References GRINS::FactoryAbstract< Base >::create().
   {
     FactoryAbstract<Base>& factory = get_factory(name);
     return factory.create();
   }
template<typename Base> virtual libMesh::UniquePtr<Base> GRINS::FactoryAbstract< Base >::create () pure virtual
Subclasses implement the actual construction of the Base object in create().
Implemented in GRINS::DirichletBCFactoryFunctionBase< FunctionType >, GRINS::DirichletBCFactoryFunctionBase< libMesh::FEMFunctionBase< libMesh::Number > >, GRINS::DirichletBCFactoryFunctionBase< libMesh::FunctionBase< libMesh::Number > >, GRINS::ErrorEstimatorFactoryBase, GRINS::NeumannBCFactoryAbstract, GRINS::CatalycityFactoryAbstract, GRINS::PhysicsFactoryBase, GRINS::SolverFactoryAbstract, and GRINS::VariableFactoryAbstract.
Referenced by GRINS::FactoryAbstract< Base >::build().
template<> std::map< std::string, FactoryAbstract< Physics > * > & GRINS::FactoryAbstract< Physics >::factory_map () protected
Definition at line 33 of file physics_factory_base.C.
   {
     static std::map<std::string, FactoryAbstract<Physics>*> _map;
     return _map;
   }
template<> std::map< std::string, FactoryAbstract< libMesh::ErrorEstimator > * > & GRINS::FactoryAbstract< libMesh::ErrorEstimator >::factory_map () protected
Definition at line 33 of file error_estimator_factory_base.C.
   {
     static std::map<std::string, FactoryAbstract<libMesh::ErrorEstimator>*> _map;
     return _map;
   }
template<> std::map< std::string, FactoryAbstract< libMesh::DirichletBoundary > * > & GRINS::FactoryAbstract< libMesh::DirichletBoundary >::factory_map () protected
Definition at line 33 of file dirichlet_bc_factory_abstract.C.
   {
     static std::map<std::string, FactoryAbstract<libMesh::DirichletBoundary>*> _map;
     return _map;
   }
template<> std::map< std::string, FactoryAbstract< CatalycityBase > * > & GRINS::FactoryAbstract< CatalycityBase >::factory_map () protected
Definition at line 34 of file catalycity_factory_abstract.C.
   {
     static std::map<std::string, FactoryAbstract<CatalycityBase>*> _map;
     return _map;
   }
template<> std::map< std::string, FactoryAbstract< Solver > * > & GRINS::FactoryAbstract< Solver >::factory_map () protected
Definition at line 41 of file solver_factory_abstract.C.
   {
     static std::map<std::string, FactoryAbstract<Solver>*> _map;
     return _map;
   }
template<typename Base> static std::map<std::string, FactoryAbstract<Base>*>& GRINS::FactoryAbstract< Base >::factory_map () static protected
Referenced by GRINS::BCFactoryAbstract< Base >::have_bc_type().
template<> std::map< std::string, FactoryAbstract< NeumannBCContainer > * > & GRINS::FactoryAbstract< NeumannBCContainer >::factory_map () protected
Definition at line 77 of file neumann_bc_factory_abstract.C.
   {
     static std::map<std::string, FactoryAbstract<NeumannBCContainer>*> _map;
     return _map;
   }
template<> std::map< std::string, FactoryAbstract< FEVariablesBase > * > & GRINS::FactoryAbstract< FEVariablesBase >::factory_map () protected
Definition at line 125 of file variable_factory.C.
   {
     static std::map<std::string, FactoryAbstract<FEVariablesBase>*> _map;
     return _map;
   }
template<class Base > FactoryAbstract< Base > & GRINS::FactoryAbstract< Base >::get_factory (const std::string & name) inline static protected
Helper method that looks up the factory and returns it if present, or error if it's not.
Definition at line 94 of file factory_abstract.h.
   {
     if (!factory_map().count(name))
       {
         std::stringstream ss;
         ss << "ERROR: Tried to build an unknown FactoryAbstract type: "
            << name << std::endl
            << "valid options are:" << std::endl;
         for( typename std::map<std::string,FactoryAbstract<Base>*>::const_iterator
                it = factory_map().begin(); it != factory_map().end(); ++it )
           ss << "  " << it->first << std::endl;
         libmesh_error_msg(ss.str());
       }
     FactoryAbstract<Base>* factory = factory_map()[name];
     return *factory;
   }
template<class Base > template<typename DerivedType > DerivedType & GRINS::FactoryAbstract< Base >::get_factory_subclass (const std::string & name) inline static protected
Like get_factory, but will downcast to DerivedType.
Definition at line 117 of file factory_abstract.h.
   {
     FactoryAbstract<Base>& raw_factory = get_factory(name);
     DerivedType& factory = libMesh::cast_ref<DerivedType&>(raw_factory);
     return factory;
   }
The documentation for this class was generated from the following file:
src/common/include/grins/factory_abstract.h