GRINS-0.6.0: TurbulentBCFactory Class Reference
TurbulentBCFactory Class Reference
Public Member Functions
TurbulentBCFactory (libMesh::MeshFunction *_turbulent_bc_values)
~TurbulentBCFactory ()
std::multimap< GRINS::PhysicsName, GRINS::DBCContainer > build_dirichlet ()
Builds all required libMesh::DirichletBoundary objects and adds them to DofMap.
virtual std::map< GRINS::PhysicsName, GRINS::NBCContainer > build_neumann (libMesh::EquationSystems &equation_system)
Builds all Neumann boundary condition function objects needed.
Private Attributes
libMesh::MeshFunction * turbulent_bc_values
Detailed Description
Definition at line 62 of file test_turbulent_channel.C.
Constructor & Destructor Documentation
TurbulentBCFactory::TurbulentBCFactory (libMesh::MeshFunction * _turbulent_bc_values) inline
Definition at line 66 of file test_turbulent_channel.C.
     : GRINS::BoundaryConditionsFactory(),
       turbulent_bc_values(_turbulent_bc_values)
   { return; };
TurbulentBCFactory::~TurbulentBCFactory () inline
Definition at line 71 of file test_turbulent_channel.C.
 {return;};
Member Function Documentation
std::multimap< GRINS::PhysicsName, GRINS::DBCContainer > TurbulentBCFactory::build_dirichlet () virtual
Builds all required libMesh::DirichletBoundary objects and adds them to DofMap.
This needs to be done for all the physics in the simulation, for all "special" dirichlet boundary conditions.
Reimplemented from GRINS::BoundaryConditionsFactory.
Definition at line 385 of file test_turbulent_channel.C.
References GRINS::DBCContainer::add_bc_id(), GRINS::DBCContainer::add_var_name(), GRINS::incompressible_navier_stokes, GRINS::DBCContainer::set_func(), GRINS::spalart_allmaras, and turbulent_bc_values.
 {
   std::tr1::shared_ptr<libMesh::FunctionBase<libMesh::Number> > turbulent_inlet_u( new TurbulentBdyFunctionU(this->turbulent_bc_values) );
   std::tr1::shared_ptr<libMesh::FunctionBase<libMesh::Number> > turbulent_inlet_nu( new TurbulentBdyFunctionNu(this->turbulent_bc_values) );
   GRINS::DBCContainer cont_u;
   cont_u.add_var_name( "u" );
   cont_u.add_bc_id( 3 );
   cont_u.set_func( turbulent_inlet_u );
   GRINS::DBCContainer cont_nu;
   cont_nu.add_var_name( "nu" );
   cont_nu.add_bc_id( 3 );
   cont_nu.set_func( turbulent_inlet_nu );
   std::multimap< GRINS::PhysicsName, GRINS::DBCContainer > mymap;
   mymap.insert( std::pair<GRINS::PhysicsName, GRINS::DBCContainer >(GRINS::incompressible_navier_stokes,  cont_u) );
   mymap.insert( std::pair<GRINS::PhysicsName, GRINS::DBCContainer >(GRINS::spalart_allmaras,  cont_nu) );
   return mymap;
 }
std::map< PhysicsName, NBCContainer > GRINS::BoundaryConditionsFactory::build_neumann (libMesh::EquationSystems & equation_system) virtual inherited
Builds all Neumann boundary condition function objects needed.
This is done for each physics. Thus, the container returned maps between each physics and set of Neumann boundary conditions for that physics.
Reimplemented in GRINS::ThermallyDrivenFlowTestBCFactory.
Definition at line 47 of file bc_factory.C.
   {
     return std::map< PhysicsName, NBCContainer >();
   }
Member Data Documentation
libMesh::MeshFunction* TurbulentBCFactory::turbulent_bc_values private
Definition at line 77 of file test_turbulent_channel.C.
Referenced by build_dirichlet().
The documentation for this class was generated from the following file:
test/test_turbulent_channel.C