GRINS-0.8.0: GRINS::NeumannBCOldStyleFactoryAbstract Class Reference
GRINS::NeumannBCOldStyleFactoryAbstract Class Reference
#include <neumann_bc_old_style_factory_abstract.h>
Public Member Functions
NeumannBCOldStyleFactoryAbstract (const std::string &bc_type_name)
~NeumannBCOldStyleFactoryAbstract ()
Public Member Functions inherited from GRINS::NeumannBCFactoryAbstract
NeumannBCFactoryAbstract (const std::string &bc_type_name)
~NeumannBCFactoryAbstract ()
virtual libMesh::UniquePtr< NeumannBCContainer > create ()
Creates NeumannBCContainer for this Factory object.
Public Member Functions inherited from GRINS::BCFactoryAbstract< NeumannBCContainer >
BCFactoryAbstract (const std::string &bc_type_name)
~BCFactoryAbstract ()
Public Member Functions inherited from GRINS::FactoryWithGetPot< NeumannBCContainer >
FactoryWithGetPot (const std::string &name)
~FactoryWithGetPot ()
Public Member Functions inherited from GRINS::FactoryAbstract< NeumannBCContainer >
virtual ~FactoryAbstract ()
Static Public Member Functions
static void set_value_var_old_style (const std::string &value_var)
Input variable for parsing old style.
static void set_value_index_old_style (unsigned int idx)
Input variable index for parsing old style.
Static Public Member Functions inherited from GRINS::BCFactoryAbstract< NeumannBCContainer >
static void set_system (MultiphysicsSystem &system)
static void set_bc_ids (const std::set< BoundaryID > &bc_ids)
Boundary id for the current boundary condition section.
static void set_fe_var (const FEVariablesBase &fe_var)
Active variable for the current boundary condition.
static void set_section (const std::string &section)
Sets the current section of the input file.
static bool have_bc_type (const std::string &bc_type)
Static Public Member Functions inherited from GRINS::FactoryWithGetPot< NeumannBCContainer >
static void set_getpot (const GetPot &input)
Static Public Member Functions inherited from GRINS::FactoryAbstract< NeumannBCContainer >
static libMesh::UniquePtr< NeumannBCContainer > build (const std::string &name)
Use this method to build objects of type Base.
Protected Member Functions
virtual void check_state () const
Helper function to reduce code duplication.
virtual void reset_state ()
Helper function to reduce code duplication.
Protected Member Functions inherited from GRINS::NeumannBCFactoryAbstract
virtual SharedPtr< NeumannBCAbstract > build_neumann_func (const GetPot &input, MultiphysicsSystem &system, const FEVariablesBase &fe_var, const std::string &section)=0
Builds the NeumannBCAbstract object for Neumann boundary conditions.
void check_for_flux (const GetPot &input, const std::string &section, const std::vector< std::string > &var_names)
Checks that the flux variable has been set.
Protected Member Functions inherited from GRINS::BCFactoryAbstract< NeumannBCContainer >
void check_for_multiple_expressions (const GetPot &input, const std::string &section, const std::string &var_name) const
Ensure that there is only one expression for the [Section/var_name] variable.
void build_var_indices (const MultiphysicsSystem &system, const std::vector< std::string > &var_names, std::vector< VariableIndex > &var_indices) const
Protected Member Functions inherited from GRINS::FactoryAbstract< NeumannBCContainer >
FactoryAbstract (const std::string &name)
Constructor is protected. Use the build() method to construct Base objects.
Static Protected Attributes
static std::string _value_var_old_style = std::string("DIE!")
static unsigned int _value_idx_old_style = libMesh::invalid_uint
Static Protected Attributes inherited from GRINS::BCFactoryAbstract< NeumannBCContainer >
static MultiphysicsSystem * _system
We store only a raw pointer here because we can't make a copy.
static const std::set< BoundaryID > * _bc_ids
BoundaryID for constructing a particular boundary condition.
static const FEVariablesBase * _fe_var
The FEVariablesBase class associated with the boundary condition being built.
static std::string _section
Static Protected Attributes inherited from GRINS::FactoryWithGetPot< NeumannBCContainer >
static const GetPot * _input
We store only a raw pointer here because we can't make a copy.
Additional Inherited Members
Static Protected Member Functions inherited from GRINS::FactoryAbstract< NeumannBCContainer >
static FactoryAbstract< NeumannBCContainer > & get_factory (const std::string &name)
Helper method that looks up the factory and returns it if present, or error if it's not.
static DerivedType & get_factory_subclass (const std::string &name)
Like get_factory, but will downcast to DerivedType.
static std::map< std::string, FactoryAbstract< NeumannBCContainer > * > & factory_map ()
Protected Attributes inherited from GRINS::NeumannBCFactoryAbstract
bool _is_homogeneous
Track if this is a homogeneous Neumann boundary condition.
Detailed Description
Definition at line 33 of file neumann_bc_old_style_factory_abstract.h.
Constructor & Destructor Documentation
GRINS::NeumannBCOldStyleFactoryAbstract::NeumannBCOldStyleFactoryAbstract (const std::string & bc_type_name) inline
Definition at line 36 of file neumann_bc_old_style_factory_abstract.h.
       : NeumannBCFactoryAbstract(bc_type_name)
     {}
GRINS::NeumannBCOldStyleFactoryAbstract::~NeumannBCOldStyleFactoryAbstract () inline
Definition at line 40 of file neumann_bc_old_style_factory_abstract.h.
 {};
Member Function Documentation
void GRINS::NeumannBCOldStyleFactoryAbstract::check_state () const protected virtual
Helper function to reduce code duplication.
Reimplemented from GRINS::BCFactoryAbstract< NeumannBCContainer >.
Definition at line 34 of file neumann_bc_old_style_factory_abstract.C.
References _value_idx_old_style, _value_var_old_style, and GRINS::BCFactoryAbstract< NeumannBCContainer >::check_state().
   {
     NeumannBCFactoryAbstract::check_state();
     if( this->_value_var_old_style == std::string("DIE!") )
       libmesh_error_msg("ERROR: must call set_value_var_old_style() before building boundary condition!");
     if( this->_value_idx_old_style == libMesh::invalid_uint )
       libmesh_error_msg("ERROR: must call set_value_index_old_style() before building boundary condition!");
   }
void GRINS::NeumannBCOldStyleFactoryAbstract::reset_state () protected virtual
Helper function to reduce code duplication.
Reimplemented from GRINS::BCFactoryAbstract< NeumannBCContainer >.
Definition at line 45 of file neumann_bc_old_style_factory_abstract.C.
References _value_idx_old_style, _value_var_old_style, and GRINS::BCFactoryAbstract< NeumannBCContainer >::reset_state().
   {
     NeumannBCFactoryAbstract::reset_state();
     this->_value_var_old_style = std::string("DIE!");
     this->_value_idx_old_style = libMesh::invalid_uint;
   }
static void GRINS::NeumannBCOldStyleFactoryAbstract::set_value_index_old_style (unsigned int idx) inline static
Input variable index for parsing old style.
Deprecated, only used for backward compatibility.
Definition at line 49 of file neumann_bc_old_style_factory_abstract.h.
References _value_idx_old_style.
Referenced by GRINS::OldStyleBCBuilder::set_neumann_bc_factory_old_style_quantities().
     { _value_idx_old_style = idx; }
static void GRINS::NeumannBCOldStyleFactoryAbstract::set_value_var_old_style (const std::string & value_var) inline static
Input variable for parsing old style.
Deprecated, only used for backward compatibility.
Definition at line 44 of file neumann_bc_old_style_factory_abstract.h.
References _value_var_old_style.
Referenced by GRINS::OldStyleBCBuilder::set_neumann_bc_factory_old_style_quantities().
     { _value_var_old_style = value_var; }
Member Data Documentation
unsigned int GRINS::NeumannBCOldStyleFactoryAbstract::_value_idx_old_style = libMesh::invalid_uint static protected
Definition at line 62 of file neumann_bc_old_style_factory_abstract.h.
Referenced by check_state(), reset_state(), and set_value_index_old_style().
std::string GRINS::NeumannBCOldStyleFactoryAbstract::_value_var_old_style = std::string("DIE!") static protected
Definition at line 60 of file neumann_bc_old_style_factory_abstract.h.
Referenced by check_state(), reset_state(), and set_value_var_old_style().
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/neumann_bc_old_style_factory_abstract.h
src/boundary_conditions/src/neumann_bc_old_style_factory_abstract.C