GRINS-0.8.0: GRINSTesting::RegressionHelper Class Reference
GRINSTesting::RegressionHelper Class Reference
#include <regression_helper.h>
Protected Member Functions
libMesh::Real linear_slope (std::vector< libMesh::Real > x, std::vector< libMesh::Real > y, unsigned int start_index, unsigned int end_index)
Slope for linear regression.
libMesh::Real linear_intercept (std::vector< libMesh::Real > x, std::vector< libMesh::Real > y, unsigned int start_index, unsigned int end_index)
y-intercept for linear regression
void check_convergence_rate (std::vector< libMesh::Real > x, std::vector< libMesh::Real > y, unsigned int start_index, unsigned int end_index, libMesh::Real convergence_rate, libMesh::Real tol)
Check the convergence rate of the supplied data to within the given absolute tolerance.
Detailed Description
Provides helper functions for fitting data to a curve.
Currently supports linear regression
Definition at line 46 of file regression_helper.h.
Member Function Documentation
void GRINSTesting::RegressionHelper::check_convergence_rate (std::vector< libMesh::Real > x, std::vector< libMesh::Real > y, unsigned int start_index, unsigned int end_index, libMesh::Real convergence_rate, libMesh::Real tol) inline protected
Check the convergence rate of the supplied data to within the given absolute tolerance.
Definition at line 110 of file regression_helper.h.
References linear_slope().
Referenced by GRINSTesting::IntegratedFunctionTest::test_convergence().
     {
       libmesh_assert(tol > 0.0);
       libmesh_assert(x.size() == y.size());
       libmesh_assert(start_index < end_index);
       libmesh_assert(end_index < x.size());
       libMesh::Real calculated_rate = linear_slope(x,y,start_index,end_index);
 #ifdef GRINS_HAVE_CPPUNIT
       CPPUNIT_ASSERT_DOUBLES_EQUAL(convergence_rate,calculated_rate,tol);
 #else
       if (std::abs(convergence_rate - calculated_rate) > tol)
         {
           std::stringstream ss;
           ss <<"ERROR" <<std::endl
              <<"calculated convergence rate: " <<calculated_rate <<std::endl
              <<"desired convergence rate: " <<convergence_rate <<std::endl
              <<"tolerance: " <<tol <<std::endl;
           libmesh_error_msg(ss.str());
         }
 #endif // GRINS_HAVE_CPPUNIT
     }
libMesh::Real GRINSTesting::RegressionHelper::linear_intercept (std::vector< libMesh::Real > x, std::vector< libMesh::Real > y, unsigned int start_index, unsigned int end_index) inline protected
y-intercept for linear regression
Definition at line 81 of file regression_helper.h.
     {
       libmesh_assert(x.size() == y.size());
       libmesh_assert(start_index < end_index);
       unsigned int n = x.size();
       libmesh_assert(end_index < n);
       libMesh::Real sum_y = 0.0,
         sum_x2 = 0.0,
         sum_x = 0.0,
         sum_xy = 0.0;
       for (unsigned int i=start_index; i<=end_index; i++)
         {
           libMesh::Real xi = x[i];
           libMesh::Real yi = y[i];
           sum_y  += yi;
           sum_x2 += xi*xi;
           sum_x  += xi;
           sum_xy += xi*yi;
         }
       libMesh::Real intercept = ( sum_y*sum_x2 - sum_x*sum_xy )/( n*sum_x2 - (sum_x*sum_x) );
       return intercept;
     }
libMesh::Real GRINSTesting::RegressionHelper::linear_slope (std::vector< libMesh::Real > x, std::vector< libMesh::Real > y, unsigned int start_index, unsigned int end_index) inline protected
Slope for linear regression.
Definition at line 51 of file regression_helper.h.
Referenced by check_convergence_rate().
     {
       libmesh_assert(x.size() == y.size());
       libmesh_assert(start_index < end_index);
       unsigned int n = x.size();
       libmesh_assert(end_index < n);
       libMesh::Real sum_y = 0.0,
         sum_x2 = 0.0,
         sum_x = 0.0,
         sum_xy = 0.0;
       for (unsigned int i=start_index; i<=end_index; i++)
         {
           libMesh::Real xi = x[i];
           libMesh::Real yi = y[i];
           sum_y  += yi;
           sum_x2 += xi*xi;
           sum_x  += xi;
           sum_xy += xi*yi;
         }
       libMesh::Real slope = ( n*sum_xy - sum_x*sum_y )/( n*sum_x2 - (sum_x*sum_x) );
       return slope;
     }
The documentation for this class was generated from the following file:
test/common/regression_helper.h