GRINS-0.6.0: GRINS::AntiochWilkeTransportEvaluator< Thermo, Viscosity, Conductivity, Diffusivity > Class Template Reference
GRINS::AntiochWilkeTransportEvaluator< Thermo, Viscosity, Conductivity, Diffusivity > Class Template Reference
Wrapper class for evaluating Wilke transport properties using Antioch.
#include <antioch_wilke_transport_evaluator.h>
Public Member Functions
AntiochWilkeTransportEvaluator (const AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity > &mixture)
virtual ~AntiochWilkeTransportEvaluator ()
libMesh::Real mu (const CachedValues &cache, unsigned int qp)
libMesh::Real k (const CachedValues &cache, unsigned int qp)
void mu_and_k (const CachedValues &cache, unsigned int qp, libMesh::Real &mu, libMesh::Real &k)
void D (const CachedValues &cache, unsigned int qp, std::vector< libMesh::Real > &D)
libMesh::Real mu (const libMesh::Real T, const std::vector< libMesh::Real > &Y)
libMesh::Real k (const libMesh::Real T, const std::vector< libMesh::Real > &Y)
void D (const libMesh::Real rho, const libMesh::Real cp, const libMesh::Real k, std::vector< libMesh::Real > &D)
libMesh::Real M (unsigned int species) const
libMesh::Real M_mix (const std::vector< libMesh::Real > &mass_fractions) const
libMesh::Real R (unsigned int species) const
libMesh::Real R_mix (const std::vector< libMesh::Real > &mass_fractions) const
libMesh::Real X (unsigned int species, libMesh::Real M, libMesh::Real mass_fraction) const
void X (libMesh::Real M, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &mole_fractions) const
unsigned int species_index (const std::string &species_name) const
std::string species_name (unsigned int species_index) const
libMesh::Real cp (const CachedValues &cache, unsigned int qp)
libMesh::Real cp (const libMesh::Real &T, const std::vector< libMesh::Real > &Y)
template<>
libMesh::Real cp (const CachedValues &cache, unsigned int qp)
template<>
libMesh::Real cp (const CachedValues &cache, unsigned int qp)
template<>
libMesh::Real cp (const libMesh::Real &T, const std::vector< libMesh::Real > &Y)
template<>
libMesh::Real cp (const libMesh::Real &T, const std::vector< libMesh::Real > &Y)
libMesh::Real cv (const CachedValues &cache, unsigned int qp)
template<>
libMesh::Real cv (const CachedValues &cache, unsigned int qp)
template<>
libMesh::Real cv (const CachedValues &cache, unsigned int qp)
libMesh::Real h_s (const CachedValues &cache, unsigned int qp, unsigned int species)
void h_s (const CachedValues &cache, unsigned int qp, std::vector< libMesh::Real > &h_s)
libMesh::Real h_s (const libMesh::Real &T, unsigned int species)
template<>
libMesh::Real h_s (const libMesh::Real &T, unsigned int species)
template<>
libMesh::Real h_s (const libMesh::Real &T, unsigned int species)
template<>
libMesh::Real h_s (const CachedValues &cache, unsigned int qp, unsigned int species)
template<>
libMesh::Real h_s (const CachedValues &cache, unsigned int qp, unsigned int species)
template<>
void h_s (const CachedValues &cache, unsigned int qp, std::vector< libMesh::Real > &h_s)
template<>
void h_s (const CachedValues &cache, unsigned int qp, std::vector< libMesh::Real > &h_s)
void omega_dot (const CachedValues &cache, unsigned int qp, std::vector< libMesh::Real > &omega_dot)
void omega_dot (const libMesh::Real &T, libMesh::Real rho, const std::vector< libMesh::Real > mass_fractions, std::vector< libMesh::Real > &omega_dot)
Protected Member Functions
void check_and_reset_temp_cache (const libMesh::Real &T)
Helper method for managing _temp_cache.
void build_thermo (const AntiochMixture &mixture)
Protected Attributes
boost::scoped_ptr< Antioch::WilkeEvaluator< Viscosity, Conductivity > > _wilke_evaluator
const Diffusivity & _diffusivity
const AntiochMixture & _chem
boost::scoped_ptr< Thermo > _thermo
boost::scoped_ptr< AntiochKinetics > _kinetics
boost::scoped_ptr< Antioch::TempCache< libMesh::Real > > _temp_cache
Private Member Functions
AntiochWilkeTransportEvaluator ()
Detailed Description
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity>
class GRINS::AntiochWilkeTransportEvaluator< Thermo, Viscosity, Conductivity, Diffusivity >
Wrapper class for evaluating Wilke transport properties using Antioch.
This class is expected to be constructed after threads have been forked and will only live during the lifetime of the thread. By default, Antioch is working in SI units. Note that this documentation will always be built regardless if Antioch is included in the GRINS build or not. Check configure output to confirm that Antioch was included in the build.
Definition at line 54 of file antioch_wilke_transport_evaluator.h.
Constructor & Destructor Documentation
template<typename Thermo , typename Viscosity , typename Conductivity , typename Diffusivity > GRINS::AntiochWilkeTransportEvaluator< Thermo, Viscosity, Conductivity, Diffusivity >::AntiochWilkeTransportEvaluator (const AntiochWilkeTransportMixture< Thermo, Viscosity, Conductivity, Diffusivity > & mixture)
Definition at line 39 of file antioch_wilke_transport_evaluator.C.
     : AntiochEvaluator<Thermo>( mixture ),
       _wilke_evaluator( new Antioch::WilkeEvaluator<Viscosity,Conductivity>( mixture.wilke_mixture(), mixture.viscosity(), mixture.conductivity() ) ),
       _diffusivity( mixture.diffusivity() )
   {
     return;
   }
template<typename T , typename V , typename C , typename D > GRINS::AntiochWilkeTransportEvaluator< T, V, C, D >::~AntiochWilkeTransportEvaluator () virtual
Definition at line 48 of file antioch_wilke_transport_evaluator.C.
   {
     return;
   }
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> GRINS::AntiochWilkeTransportEvaluator< Thermo, Viscosity, Conductivity, Diffusivity >::AntiochWilkeTransportEvaluator () private
Member Function Documentation
template<typename Thermo> void GRINS::AntiochEvaluator< Thermo >::build_thermo (const AntiochMixture & mixture) inline protected inherited
Definition at line 126 of file antioch_evaluator.h.
References GRINS::AntiochEvaluator< Thermo >::specialized_build_thermo().
Referenced by GRINS::AntiochEvaluator< Thermo >::AntiochEvaluator().
     { specialized_build_thermo( mixture, _thermo, thermo_type<Thermo>() ); }
template<typename Thermo > void GRINS::AntiochEvaluator< Thermo >::check_and_reset_temp_cache (const libMesh::Real & T) protected inherited
Helper method for managing _temp_cache.
T MUST be pass-by-reference because of the structure of Antioch::TempCache!
Definition at line 85 of file antioch_evaluator.C.
   {
     if( _temp_cache->T != T )
       {
         _temp_cache.reset( new Antioch::TempCache<libMesh::Real>(T) );
       }
     return;
   }
template<typename Thermo> libMesh::Real GRINS::AntiochEvaluator< Thermo >::cp (const CachedValues & cache, unsigned int qp) inherited
Referenced by GRINS::AntiochEvaluator< Thermo >::cp(), do_transport_eval(), and test_evaluator().
template<typename Thermo> libMesh::Real GRINS::AntiochEvaluator< Thermo >::cp (const libMesh::Real & T, const std::vector< libMesh::Real > & Y) inherited
template<> libMesh::Real GRINS::AntiochEvaluator< Antioch::CEAEvaluator< libMesh::Real > >::cp (const CachedValues & cache, unsigned int qp) inherited
Definition at line 96 of file antioch_evaluator.C.
References GRINS::CachedValues::get_cached_values(), GRINS::CachedValues::get_cached_vector_values(), GRINS::Cache::MASS_FRACTIONS, and GRINS::Cache::TEMPERATURE.
   {
     const libMesh::Real& T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     const std::vector<libMesh::Real>& Y = cache.get_cached_vector_values(Cache::MASS_FRACTIONS)[qp];
     this->check_and_reset_temp_cache(T);
     return _thermo->cp( *(_temp_cache.get()), Y );
   }
template<> libMesh::Real GRINS::AntiochEvaluator< Antioch::StatMechThermodynamics< libMesh::Real > >::cp (const CachedValues & cache, unsigned int qp) inherited
Definition at line 108 of file antioch_evaluator.C.
References GRINS::CachedValues::get_cached_values(), GRINS::CachedValues::get_cached_vector_values(), GRINS::Cache::MASS_FRACTIONS, and GRINS::Cache::TEMPERATURE.
   {
     const libMesh::Real T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     const std::vector<libMesh::Real>& Y = cache.get_cached_vector_values(Cache::MASS_FRACTIONS)[qp];
     return _thermo->cp( T, T, Y );
   }
template<> libMesh::Real GRINS::AntiochEvaluator< Antioch::CEAEvaluator< libMesh::Real > >::cp (const libMesh::Real & T, const std::vector< libMesh::Real > & Y) inherited
Definition at line 118 of file antioch_evaluator.C.
   {
     this->check_and_reset_temp_cache(T);
     return _thermo->cp( *(_temp_cache.get()), Y );
   }
template<> libMesh::Real GRINS::AntiochEvaluator< Antioch::StatMechThermodynamics< libMesh::Real > >::cp (const libMesh::Real & T, const std::vector< libMesh::Real > & Y) inherited
Definition at line 127 of file antioch_evaluator.C.
References GRINS::AntiochEvaluator< Thermo >::cp().
   {
     return _thermo->cp( T, T, Y );
   }
template<typename Thermo> libMesh::Real GRINS::AntiochEvaluator< Thermo >::cv (const CachedValues & cache, unsigned int qp) inherited
Referenced by test_evaluator().
template<> libMesh::Real GRINS::AntiochEvaluator< Antioch::CEAEvaluator< libMesh::Real > >::cv (const CachedValues & cache, unsigned int qp) inherited
Definition at line 134 of file antioch_evaluator.C.
References GRINS::CachedValues::get_cached_values(), GRINS::CachedValues::get_cached_vector_values(), GRINS::Cache::MASS_FRACTIONS, and GRINS::Cache::TEMPERATURE.
   {
     const libMesh::Real& T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     const std::vector<libMesh::Real>& Y = cache.get_cached_vector_values(Cache::MASS_FRACTIONS)[qp];
     this->check_and_reset_temp_cache(T);
     return _thermo->cv( *(_temp_cache.get()), Y );
   }
template<> libMesh::Real GRINS::AntiochEvaluator< Antioch::StatMechThermodynamics< libMesh::Real > >::cv (const CachedValues & cache, unsigned int qp) inherited
Definition at line 160 of file antioch_evaluator.C.
References GRINS::CachedValues::get_cached_values(), GRINS::CachedValues::get_cached_vector_values(), GRINS::Cache::MASS_FRACTIONS, and GRINS::Cache::TEMPERATURE.
   {
     const libMesh::Real T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     const std::vector<libMesh::Real>& Y = cache.get_cached_vector_values(Cache::MASS_FRACTIONS)[qp];
     return _thermo->cv( T, T, Y );
   }
template<typename Th , typename V , typename C , typename D > void GRINS::AntiochWilkeTransportEvaluator< Th, V, C, D >::D (const CachedValues & cache, unsigned int qp, std::vector< libMesh::Real > & D)
Todo:
Find a way to cache these so we don't have to recompute them
Definition at line 83 of file antioch_wilke_transport_evaluator.C.
References GRINS::CachedValues::get_cached_values(), and GRINS::Cache::MIXTURE_DENSITY.
Referenced by do_transport_eval(), and test_evaluator().
   {
     const libMesh::Real rho = cache.get_cached_values(Cache::MIXTURE_DENSITY)[qp];
     const libMesh::Real cp = this->cp(cache,qp);
     const libMesh::Real k = this->k(cache,qp);
     this->D(rho,cp,k,D);
     return;
   }
template<typename Th , typename V , typename C , typename D > void GRINS::AntiochWilkeTransportEvaluator< Th, V, C, D >::D (const libMesh::Real rho, const libMesh::Real cp, const libMesh::Real k, std::vector< libMesh::Real > & D)
Definition at line 112 of file antioch_wilke_transport_evaluator.C.
   {
     std::fill( D.begin(), D.end(), _diffusivity.D(rho,cp,k) );
     return;
   }
template<typename Thermo> libMesh::Real GRINS::AntiochEvaluator< Thermo >::h_s (const CachedValues & cache, unsigned int qp, unsigned int species) inherited
Referenced by test_evaluator().
template<typename Thermo> void GRINS::AntiochEvaluator< Thermo >::h_s (const CachedValues & cache, unsigned int qp, std::vector< libMesh::Real > & h_s) inherited
template<typename Thermo> libMesh::Real GRINS::AntiochEvaluator< Thermo >::h_s (const libMesh::Real & T, unsigned int species) inherited
template<> libMesh::Real GRINS::AntiochEvaluator< Antioch::CEAEvaluator< libMesh::Real > >::h_s (const libMesh::Real & T, unsigned int species) inherited
Definition at line 146 of file antioch_evaluator.C.
   {
     this->check_and_reset_temp_cache(T);
     return _thermo->h( *(_temp_cache.get()), species );;
   }
template<> libMesh::Real GRINS::AntiochEvaluator< Antioch::StatMechThermodynamics< libMesh::Real > >::h_s (const libMesh::Real & T, unsigned int species) inherited
Definition at line 154 of file antioch_evaluator.C.
   {
     return _thermo->h_tot( species, T ) + _chem.h_stat_mech_ref_correction(species);
   }
template<> libMesh::Real GRINS::AntiochEvaluator< Antioch::CEAEvaluator< libMesh::Real > >::h_s (const CachedValues & cache, unsigned int qp, unsigned int species) inherited
Definition at line 170 of file antioch_evaluator.C.
References GRINS::CachedValues::get_cached_values(), and GRINS::Cache::TEMPERATURE.
   {
     const libMesh::Real& T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     return this->h_s( T, species );
   }
template<> libMesh::Real GRINS::AntiochEvaluator< Antioch::StatMechThermodynamics< libMesh::Real > >::h_s (const CachedValues & cache, unsigned int qp, unsigned int species) inherited
Definition at line 180 of file antioch_evaluator.C.
References GRINS::CachedValues::get_cached_values(), and GRINS::Cache::TEMPERATURE.
   {
     const libMesh::Real T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     return this->h_s(T, species);
   }
template<> void GRINS::AntiochEvaluator< Antioch::CEAEvaluator< libMesh::Real > >::h_s (const CachedValues & cache, unsigned int qp, std::vector< libMesh::Real > & h_s) inherited
Definition at line 190 of file antioch_evaluator.C.
References GRINS::CachedValues::get_cached_values(), and GRINS::Cache::TEMPERATURE.
   {
     const libMesh::Real& T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     this->check_and_reset_temp_cache(T);
     _thermo->h( *(_temp_cache.get()), h_s );
     return;
   }
template<> void GRINS::AntiochEvaluator< Antioch::StatMechThermodynamics< libMesh::Real > >::h_s (const CachedValues & cache, unsigned int qp, std::vector< libMesh::Real > & h_s) inherited
Definition at line 204 of file antioch_evaluator.C.
   {
     for( unsigned int s = 0; s < _chem.n_species(); s++ )
       {
         h_s[s] = this->h_s(cache,qp,s);
       }
     return;
   }
template<typename Th , typename V , typename C , typename D > libMesh::Real GRINS::AntiochWilkeTransportEvaluator< Th, V, C, D >::k (const CachedValues & cache, unsigned int qp)
Definition at line 63 of file antioch_wilke_transport_evaluator.C.
References GRINS::CachedValues::get_cached_values(), GRINS::CachedValues::get_cached_vector_values(), GRINS::Cache::MASS_FRACTIONS, and GRINS::Cache::TEMPERATURE.
Referenced by do_transport_eval(), and test_evaluator().
   {
     const libMesh::Real T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     const std::vector<libMesh::Real>& Y = cache.get_cached_vector_values(Cache::MASS_FRACTIONS)[qp];
     return this->k( T, Y );
   }
template<typename Th , typename V , typename C , typename D > libMesh::Real GRINS::AntiochWilkeTransportEvaluator< Th, V, C, D >::k (const libMesh::Real T, const std::vector< libMesh::Real > & Y)
Definition at line 105 of file antioch_wilke_transport_evaluator.C.
   {
     return _wilke_evaluator->k( T, Y );
   }
template<typename Thermo > libMesh::Real GRINS::AntiochEvaluator< Thermo >::M (unsigned int species) const inline inherited
Definition at line 154 of file antioch_evaluator.h.
   {
     return _chem.M(species);
   }
template<typename Thermo > libMesh::Real GRINS::AntiochEvaluator< Thermo >::M_mix (const std::vector< libMesh::Real > & mass_fractions) const inline inherited
Definition at line 161 of file antioch_evaluator.h.
   {
     return _chem.M_mix(mass_fractions);
   }
template<typename Th , typename V , typename C , typename D > libMesh::Real GRINS::AntiochWilkeTransportEvaluator< Th, V, C, D >::mu (const CachedValues & cache, unsigned int qp)
Definition at line 54 of file antioch_wilke_transport_evaluator.C.
References GRINS::CachedValues::get_cached_values(), GRINS::CachedValues::get_cached_vector_values(), GRINS::Cache::MASS_FRACTIONS, and GRINS::Cache::TEMPERATURE.
Referenced by do_transport_eval(), and test_evaluator().
   {
     const libMesh::Real T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     const std::vector<libMesh::Real>& Y = cache.get_cached_vector_values(Cache::MASS_FRACTIONS)[qp];
     return this->mu( T, Y );
   }
template<typename Th , typename V , typename C , typename D > libMesh::Real GRINS::AntiochWilkeTransportEvaluator< Th, V, C, D >::mu (const libMesh::Real T, const std::vector< libMesh::Real > & Y)
Definition at line 98 of file antioch_wilke_transport_evaluator.C.
   {
     return _wilke_evaluator->mu( T, Y );
   }
template<typename Th , typename V , typename C , typename D > void GRINS::AntiochWilkeTransportEvaluator< Th, V, C, D >::mu_and_k (const CachedValues & cache, unsigned int qp, libMesh::Real & mu, libMesh::Real & k)
Definition at line 72 of file antioch_wilke_transport_evaluator.C.
References GRINS::CachedValues::get_cached_values(), GRINS::CachedValues::get_cached_vector_values(), GRINS::Cache::MASS_FRACTIONS, and GRINS::Cache::TEMPERATURE.
Referenced by test_evaluator().
   {
     const libMesh::Real T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     const std::vector<libMesh::Real>& Y = cache.get_cached_vector_values(Cache::MASS_FRACTIONS)[qp];
     _wilke_evaluator->mu_and_k( T, Y, mu, k );
     return;
   }
template<typename Thermo > void GRINS::AntiochEvaluator< Thermo >::omega_dot (const CachedValues & cache, unsigned int qp, std::vector< libMesh::Real > & omega_dot) inherited
Definition at line 60 of file antioch_evaluator.C.
References GRINS::CachedValues::get_cached_values(), GRINS::CachedValues::get_cached_vector_values(), GRINS::Cache::MASS_FRACTIONS, GRINS::Cache::MIXTURE_DENSITY, and GRINS::Cache::TEMPERATURE.
Referenced by test_evaluator().
   {
     const libMesh::Real& T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     const libMesh::Real rho = cache.get_cached_values(Cache::MIXTURE_DENSITY)[qp];
     const std::vector<libMesh::Real>& Y = cache.get_cached_vector_values(Cache::MASS_FRACTIONS)[qp];
     this->omega_dot( T, rho, Y, omega_dot );
     return;
   }
template<typename Thermo > void GRINS::AntiochEvaluator< Thermo >::omega_dot (const libMesh::Real & T, libMesh::Real rho, const std::vector< libMesh::Real > mass_fractions, std::vector< libMesh::Real > & omega_dot) inherited
Definition at line 73 of file antioch_evaluator.C.
   {
     this->check_and_reset_temp_cache(T);
     _kinetics->omega_dot( *(_temp_cache.get()), rho, mass_fractions, omega_dot );
     return;
   }
template<typename Thermo > libMesh::Real GRINS::AntiochEvaluator< Thermo >::R (unsigned int species) const inline inherited
Definition at line 168 of file antioch_evaluator.h.
   {
     return _chem.R(species);
   }
template<typename Thermo > libMesh::Real GRINS::AntiochEvaluator< Thermo >::R_mix (const std::vector< libMesh::Real > & mass_fractions) const inline inherited
Definition at line 175 of file antioch_evaluator.h.
   {
     return _chem.R_mix(mass_fractions);
   }
template<typename Thermo > unsigned int GRINS::AntiochEvaluator< Thermo >::species_index (const std::string & species_name) const inline inherited
Definition at line 198 of file antioch_evaluator.h.
   {
     return _chem.species_index(species_name);
   }
template<typename Thermo > std::string GRINS::AntiochEvaluator< Thermo >::species_name (unsigned int species_index) const inline inherited
Definition at line 205 of file antioch_evaluator.h.
   {
     return _chem.species_name(species_index);
   }
template<typename Thermo > libMesh::Real GRINS::AntiochEvaluator< Thermo >::X (unsigned int species, libMesh::Real M, libMesh::Real mass_fraction) const inline inherited
Definition at line 182 of file antioch_evaluator.h.
   {
     return _chem.X(species,M,mass_fraction);
   }
template<typename Thermo > void GRINS::AntiochEvaluator< Thermo >::X (libMesh::Real M, const std::vector< libMesh::Real > & mass_fractions, std::vector< libMesh::Real > & mole_fractions) const inline inherited
Definition at line 189 of file antioch_evaluator.h.
   {
     _chem.X(M,mass_fractions,mole_fractions);
     return;
   }
Member Data Documentation
template<typename Thermo> const AntiochMixture& GRINS::AntiochEvaluator< Thermo >::_chem protected inherited
Definition at line 108 of file antioch_evaluator.h.
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> const Diffusivity& GRINS::AntiochWilkeTransportEvaluator< Thermo, Viscosity, Conductivity, Diffusivity >::_diffusivity protected
Definition at line 86 of file antioch_wilke_transport_evaluator.h.
template<typename Thermo> boost::scoped_ptr<AntiochKinetics> GRINS::AntiochEvaluator< Thermo >::_kinetics protected inherited
Definition at line 113 of file antioch_evaluator.h.
template<typename Thermo> boost::scoped_ptr<Antioch::TempCache<libMesh::Real> > GRINS::AntiochEvaluator< Thermo >::_temp_cache protected inherited
Definition at line 115 of file antioch_evaluator.h.
template<typename Thermo> boost::scoped_ptr<Thermo> GRINS::AntiochEvaluator< Thermo >::_thermo protected inherited
Definition at line 111 of file antioch_evaluator.h.
template<typename Thermo, typename Viscosity, typename Conductivity, typename Diffusivity> boost::scoped_ptr<Antioch::WilkeEvaluator<Viscosity,Conductivity> > GRINS::AntiochWilkeTransportEvaluator< Thermo, Viscosity, Conductivity, Diffusivity >::_wilke_evaluator protected
Definition at line 84 of file antioch_wilke_transport_evaluator.h.
The documentation for this class was generated from the following files:
src/properties/include/grins/antioch_wilke_transport_evaluator.h
src/properties/src/antioch_wilke_transport_evaluator.C