GRINS-0.7.0: GRINS::GenericFETypeVariable Class Reference
GRINS::GenericFETypeVariable Class Reference
Generic FE variable for generic physics.
#include <generic_fe_type_variable.h>
Public Member Functions
GenericFETypeVariable (const GetPot &input, const std::string &physics_name, bool _is_constraint_var=false)
~GenericFETypeVariable ()
VariableIndex var () const
std::string section_name (const std::string &physics_name) const
Public Member Functions inherited from GRINS::SingleVarSingleFETypeVariable
SingleVarSingleFETypeVariable (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &old_var_name, const std::string &default_name, const std::string &subsection, const std::string &default_family, const std::string &default_order, bool is_constraint_var)
Deprecated, old style constructor.
SingleVarSingleFETypeVariable (const GetPot &input, const std::string &subsection, const std::string &default_name, bool is_constraint_var)
Primary constructor.
~SingleVarSingleFETypeVariable ()
Public Member Functions inherited from GRINS::SingleFETypeVariable
SingleFETypeVariable (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &subsection, const std::string &default_family, const std::string &default_order, bool is_constraint_var)
Deprecated, old style constructor.
SingleFETypeVariable (const GetPot &input, const std::string &subsection, bool is_constraint_var)
Primary constructor.
~SingleFETypeVariable ()
virtual void init (libMesh::FEMSystem *system)
Add variables to the system.
Public Member Functions inherited from GRINS::FEVariablesBase
FEVariablesBase (bool is_constraint_var)
~FEVariablesBase ()
bool is_constraint_var () const
void set_neumann_bc_is_positive (bool is_positive)
Reset whetever Neumann bc is postive or not.
libMesh::Real neumann_bc_sign () const
const std::vector< std::string > & active_var_names () const
Return the var names that are active from this class.
const std::vector< VariableIndex > & var_indices () const
Protected Member Functions
GenericFETypeVariable ()
std::string default_name () const
Protected Member Functions inherited from GRINS::SingleFETypeVariable
void parse_family_and_order (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &subsection, std::vector< GRINSEnums::FEFamily > &family, std::vector< GRINSEnums::Order > &order, const std::string &default_family, const std::string &default_order)
Helper function to parse FEFamily and Order.
void dup_family_order_check (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix) const
Check (and error if true) for old and new style FEFamily/Order input.
bool have_family_or_order (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &subsection) const
Check for no presence of FEFamily/Order input.
void parse_old_style_with_warning (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &default_family, const std::string &default_order, const std::string &subsection, GRINSEnums::FEFamily &family, GRINSEnums::Order &order)
void parse_new_style (const GetPot &input, const std::string &subsection, GRINSEnums::FEFamily &family, GRINSEnums::Order &order)
Protected Member Functions inherited from GRINS::FEVariablesBase
void parse_names_from_input (const GetPot &input, const std::string &subsection, std::vector< std::string > &var_names, const std::vector< std::string > &default_names)
Method to parse variable names from input.
void duplicate_name_section_check (const GetPot &input) const
Check for old name style and new name style. If both present, error.
bool check_dep_name_input (const GetPot &input, const std::string &new_subsection) const
Check for deprecated variable name input style.
Additional Inherited Members
Protected Attributes inherited from GRINS::FEVariablesBase
std::vector< VariableIndex > _vars
std::vector< std::string > _var_names
std::vector< GRINSEnums::FEFamily > _family
std::vector< GRINSEnums::Order > _order
bool _is_constraint_var
Tracks whether this is a constraint variable.
libMesh::Real _neumann_bc_sign
Track the sign of the Neumann BC term. Defaults to 1.0.
Detailed Description
Generic FE variable for generic physics.
The variable inputs, e.g. fe_family, will be tied to the input physics_name. Thus, the input specification will be [Variables/GenericVariable:<physics_name>/fe_family], etc.
Definition at line 41 of file generic_fe_type_variable.h.
Constructor & Destructor Documentation
GRINS::GenericFETypeVariable::GenericFETypeVariable (const GetPot & input, const std::string & physics_name, bool _is_constraint_var = false) inline
Definition at line 45 of file generic_fe_type_variable.h.
       : SingleVarSingleFETypeVariable(input,this->section_name(physics_name),this->default_name(),_is_constraint_var)
     {}
GRINS::GenericFETypeVariable::~GenericFETypeVariable () inline
Definition at line 51 of file generic_fe_type_variable.h.
 {};
GRINS::GenericFETypeVariable::GenericFETypeVariable () protected
Member Function Documentation
std::string GRINS::GenericFETypeVariable::default_name () const inline protected
Definition at line 62 of file generic_fe_type_variable.h.
     { return "u"; }
std::string GRINS::GenericFETypeVariable::section_name (const std::string & physics_name) const inline
Definition at line 55 of file generic_fe_type_variable.h.
References GRINS::VariablesParsing::generic_section().
Referenced by GRINS::ConvectionDiffusion::ConvectionDiffusion().
     { return VariablesParsing::generic_section()+":"+physics_name; }
VariableIndex GRINS::GenericFETypeVariable::var () const inline
Definition at line 68 of file generic_fe_type_variable.h.
References GRINS::FEVariablesBase::_vars.
Referenced by GRINS::ConvectionDiffusion::element_time_derivative(), GRINS::ConvectionDiffusion::init_context(), GRINS::ConvectionDiffusion::mass_residual(), and GRINS::ConvectionDiffusion::set_time_evolving_vars().
   {
     return _vars[0];
   }
The documentation for this class was generated from the following file:
src/variables/include/grins/generic_fe_type_variable.h