GRINS-0.7.0: GRINS::SolverNames Class Reference
GRINS::SolverNames Class Reference
#include <solver_names.h>
Static Public Member Functions
static const std::string steady_solver ()
static const std::string unsteady_solver ()
static const std::string steady_mesh_adaptive_solver ()
static const std::string unsteady_mesh_adaptive_solver ()
static const std::string libmesh_euler_solver ()
static const std::string libmesh_euler2_solver ()
static const std::string libmesh_newmark_solver ()
Detailed Description
Definition at line 30 of file solver_names.h.
Member Function Documentation
static const std::string GRINS::SolverNames::libmesh_euler2_solver () inline static
Definition at line 49 of file solver_names.h.
Referenced by GRINS::UnsteadySolver::init_time_solver().
     { return "libmesh_euler2_solver"; }
static const std::string GRINS::SolverNames::libmesh_euler_solver () inline static
Definition at line 46 of file solver_names.h.
Referenced by GRINS::UnsteadySolver::init_time_solver(), and GRINS::TimeSteppingParsing::parse_time_stepper_name().
     { return "libmesh_euler_solver"; }
static const std::string GRINS::SolverNames::libmesh_newmark_solver () inline static
Definition at line 52 of file solver_names.h.
Referenced by GRINS::UnsteadySolver::init_time_solver().
     { return "libmesh_newmark"; }
static const std::string GRINS::SolverNames::steady_mesh_adaptive_solver () inline static
Definition at line 40 of file solver_names.h.
Referenced by GRINS::SolverFactory::build(), and GRINS::SolverParsing::solver_type().
     { return "grins_steady_mesh_adaptive_solver"; }
static const std::string GRINS::SolverNames::steady_solver () inline static
Definition at line 34 of file solver_names.h.
Referenced by GRINS::SolverFactory::build(), and GRINS::SolverParsing::solver_type().
     { return "grins_steady_solver"; }
static const std::string GRINS::SolverNames::unsteady_mesh_adaptive_solver () inline static
Definition at line 43 of file solver_names.h.
Referenced by GRINS::SolverFactory::build(), and GRINS::SolverParsing::solver_type().
     { return "grins_unsteady_mesh_adaptive_solver"; }
static const std::string GRINS::SolverNames::unsteady_solver () inline static
Definition at line 37 of file solver_names.h.
Referenced by GRINS::SolverFactory::build(), and GRINS::SolverParsing::solver_type().
     { return "grins_unsteady_solver"; }
The documentation for this class was generated from the following file:
src/solver/include/grins/solver_names.h