GRINS-0.7.0: GRINS::HookesLaw1D Class Reference
GRINS::HookesLaw1D Class Reference
Hooke's law specialized for one-dimensional problems.
#include <hookes_law_1d.h>
Public Member Functions
HookesLaw1D (const GetPot &input)
HookesLaw1D (const GetPot &input, const std::string &material)
virtual ~HookesLaw1D ()
Public Member Functions inherited from GRINS::StressStrainLaw< HookesLaw1D >
StressStrainLaw ()
virtual ~StressStrainLaw ()
void compute_stress (unsigned int dim, const libMesh::TensorValue< libMesh::Real > &g_contra, const libMesh::TensorValue< libMesh::Real > &g_cov, const libMesh::TensorValue< libMesh::Real > &G_contra, const libMesh::TensorValue< libMesh::Real > &G_cov, libMesh::TensorValue< libMesh::Real > &stress)
void compute_stress_and_elasticity (unsigned int dim, const libMesh::TensorValue< libMesh::Real > &g_contra, const libMesh::TensorValue< libMesh::Real > &g_cov, const libMesh::TensorValue< libMesh::Real > &G_contra, const libMesh::TensorValue< libMesh::Real > &G_cov, libMesh::TensorValue< libMesh::Real > &stress, ElasticityTensor &C)
libMesh::Real compute_33_stress (const libMesh::TensorValue< libMesh::Real > &g_contra, const libMesh::TensorValue< libMesh::Real > &g_cov, const libMesh::TensorValue< libMesh::Real > &G_contra, const libMesh::TensorValue< libMesh::Real > &G_cov)
This is primarily a helper function for the plane stress cases.
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Private Member Functions
HookesLaw1D ()
void read_input_options (const GetPot &input)
Parse properties from input.
void compute_stress_imp (unsigned int dim, const libMesh::TensorValue< libMesh::Real > &g_contra, const libMesh::TensorValue< libMesh::Real > &g_cov, const libMesh::TensorValue< libMesh::Real > &G_contra, const libMesh::TensorValue< libMesh::Real > &G_cov, libMesh::TensorValue< libMesh::Real > &stress)
void compute_stress_and_elasticity_imp (unsigned int dim, const libMesh::TensorValue< libMesh::Real > &g_contra, const libMesh::TensorValue< libMesh::Real > &g_cov, const libMesh::TensorValue< libMesh::Real > &G_contra, const libMesh::TensorValue< libMesh::Real > &G_cov, libMesh::TensorValue< libMesh::Real > &stress, ElasticityTensor &C)
libMesh::Real compute_33_stress_imp (const libMesh::TensorValue< libMesh::Real > &g_contra, const libMesh::TensorValue< libMesh::Real > &g_cov, const libMesh::TensorValue< libMesh::Real > &G_contra, const libMesh::TensorValue< libMesh::Real > &G_cov)
Private Attributes
libMesh::Real _E
Lam\'{e} constant.
libMesh::Real _nu
Lam\'{e} constant.
Friends
class StressStrainLaw< HookesLaw1D >
Additional Inherited Members
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Detailed Description
Hooke's law specialized for one-dimensional problems.
General form is not conducive to one-dimensional problems so this should be used in those cases.
Definition at line 43 of file hookes_law_1d.h.
Constructor & Destructor Documentation
GRINS::HookesLaw1D::HookesLaw1D (const GetPot & input)
Definition at line 39 of file hookes_law_1d.C.
References grins_warning, and read_input_options().
     : StressStrainLaw<HookesLaw1D>(),
     ParameterUser("HookesLaw1D"),
     _E(0.0),
     _nu(0.0)
   {
     // Warning about this constructor being deprecated
     {
       std::string warning = "WARNING: Use of this constructor is DEPRECATED.\n";
       warning += "         Please update to use constructor with input material name.\n";
       grins_warning(warning);
     }
     this->read_input_options(input);
     return;
   }
GRINS::HookesLaw1D::HookesLaw1D (const GetPot & input, const std::string & material)
Todo:
we'll need a special accessor to give ParameterUser access to these
Definition at line 57 of file hookes_law_1d.C.
References _E, _nu, GRINS::MaterialsParsing::dep_input_warning(), GRINS::MaterialsParsing::duplicate_input_test(), grins_warning, and GRINS::ParameterUser::set_parameter().
     : StressStrainLaw<HookesLaw1D>(),
     ParameterUser("HookesLaw1D"),
     _E(0.0),
     _nu(0.0)
   {
     MaterialsParsing::duplicate_input_test(input,
                                            "Materials/"+material+"/StressStrainLaw/HookesLaw/lambda",
                                            "Physics/HookesLaw/lambda");
     MaterialsParsing::duplicate_input_test(input,
                                            "Materials/"+material+"/StressStrainLaw/HookesLaw/mu",
                                            "Physics/HookesLaw/mu");
     MaterialsParsing::duplicate_input_test(input,
                                            "Materials/"+material+"/StressStrainLaw/HookesLaw/E",
                                            "Physics/HookesLaw/E");
     MaterialsParsing::duplicate_input_test(input,
                                            "Materials/"+material+"/StressStrainLaw/HookesLaw/nu",
                                            "Physics/HookesLaw/nu");
     // Parse the new version
     if( input.have_variable("Materials/"+material+"/StressStrainLaw/HookesLaw/lambda") &&
         input.have_variable("Materials/"+material+"/StressStrainLaw/HookesLaw/mu") )
       {
         // FIXME - we'll need a special accessor to give parameter
         // access to these
         libMesh::Real lambda  = input("Physics/HookesLaw/lambda", 0.0);
         libMesh::Real mu = input("Physics/HookesLaw/mu", 0.0);
         _E  = mu*(3*lambda + 2*mu)/(lambda+mu);
         _nu = lambda/(2*(lambda+mu));
       }
     else if( input.have_variable("Materials/"+material+"/StressStrainLaw/HookesLaw/E") &&
              input.have_variable("Materials/"+material+"/StressStrainLaw/HookesLaw/nu") )
       {
         this->set_parameter
           (_E, input, "Materials/"+material+"/StressStrainLaw/HookesLaw/E", 0.0);
         this->set_parameter
           (_nu, input, "Materials/"+material+"/StressStrainLaw/HookesLaw/nu", 0.0);
       }
     // Parse the old version
     else if( input.have_variable("Physics/HookesLaw/lambda") &&
              input.have_variable("Physics/HookesLaw/mu") )
       {
         MaterialsParsing::dep_input_warning( "Physics/HookesLaw/lambda",
                                              "StressStrainLaw/HookesLaw/lambda" );
         MaterialsParsing::dep_input_warning( "Physics/HookesLaw/mu",
                                              "StressStrainLaw/HookesLaw/mu" );
         libMesh::Real lambda  = input("Physics/HookesLaw/lambda", 0.0);
         libMesh::Real mu = input("Physics/HookesLaw/mu", 0.0);
         _E  = mu*(3*lambda + 2*mu)/(lambda+mu);
         _nu = lambda/(2*(lambda+mu));
       }
     else if( input.have_variable("Physics/HookesLaw/E") &&
              input.have_variable("Physics/HookesLaw/nu") )
       {
         MaterialsParsing::dep_input_warning( "Physics/HookesLaw/E",
                                              "StressStrainLaw/HookesLaw/E" );
         MaterialsParsing::dep_input_warning( "Physics/HookesLaw/nu",
                                              "StressStrainLaw/HookesLaw/nu" );
         this->set_parameter(_E, input, "Physics/HookesLaw/E", 0.0);
         this->set_parameter(_nu, input, "Physics/HookesLaw/nu", 0.0);
       }
     else
       {
         libmesh_error_msg("ERROR: Could not find consistent HookesLaw input!");
       }
     // mu should be positive
     if( _E <= 0.0 )
       libmesh_error_msg("ERROR: Detected non-positive Young's modulus!");
     // Technically, Poisson's ratio can be negative, but it's weird. Let's warn about it.
     if( _nu < 0.0 )
       {
         std::string warning = "WARNING: Detected non-positive Poisson's ratio";
         grins_warning(warning);
       }
   }
GRINS::HookesLaw1D::~HookesLaw1D () virtual
Definition at line 138 of file hookes_law_1d.C.
   {
     return;
   }
GRINS::HookesLaw1D::HookesLaw1D () private
Member Function Documentation
libMesh::Real GRINS::HookesLaw1D::compute_33_stress_imp (const libMesh::TensorValue< libMesh::Real > & g_contra, const libMesh::TensorValue< libMesh::Real > & g_cov, const libMesh::TensorValue< libMesh::Real > & G_contra, const libMesh::TensorValue< libMesh::Real > & G_cov) private
Definition at line 209 of file hookes_law_1d.C.
   {
     libmesh_not_implemented();
     return 0.0;
   }
void GRINS::HookesLaw1D::compute_stress_and_elasticity_imp (unsigned int dim, const libMesh::TensorValue< libMesh::Real > & g_contra, const libMesh::TensorValue< libMesh::Real > & g_cov, const libMesh::TensorValue< libMesh::Real > & G_contra, const libMesh::TensorValue< libMesh::Real > & G_cov, libMesh::TensorValue< libMesh::Real > & stress, ElasticityTensor & C) private
Definition at line 194 of file hookes_law_1d.C.
References _E, and compute_stress_imp().
   {
     this->compute_stress_imp(dim,g_contra,g_cov,G_contra,G_cov,stress);
     C(0,0,0,0) = this->_E*g_contra(0,0)*g_contra(0,0);
     return;
   }
void GRINS::HookesLaw1D::compute_stress_imp (unsigned int dim, const libMesh::TensorValue< libMesh::Real > & g_contra, const libMesh::TensorValue< libMesh::Real > & g_cov, const libMesh::TensorValue< libMesh::Real > & G_contra, const libMesh::TensorValue< libMesh::Real > & G_cov, libMesh::TensorValue< libMesh::Real > & stress) private
Definition at line 178 of file hookes_law_1d.C.
References _E.
Referenced by compute_stress_and_elasticity_imp().
   {
     stress.zero();
     libMesh::Real strain = 0.5*(G_cov(0,0) - g_cov(0,0));
     stress(0,0) = (this->_E)*g_contra(0,0)*g_contra(0,0)*strain;
     return;
   }
void GRINS::HookesLaw1D::read_input_options (const GetPot & input) private
Parse properties from input.
Definition at line 143 of file hookes_law_1d.C.
References _E, _nu, and GRINS::ParameterUser::set_parameter().
Referenced by HookesLaw1D().
   {
     // We'd better have either Lam\'{e} constants or E and nu
     if( ( !input.have_variable("Physics/HookesLaw/lambda") ||
           !input.have_variable("Physics/HookesLaw/mu") ) &&
         ( !input.have_variable("Physics/HookesLaw/E") ||
           !input.have_variable("Physics/HookesLaw/nu") ) )
       {
         std::cerr << "Error: Must specify either Lame constants lambda and mu or" << std::endl
                   << "       Young's modulus and Poisson's ratio." << std::endl;
         libmesh_error();
       }
     if( input.have_variable("Physics/HookesLaw/lambda") &&
         input.have_variable("Physics/HookesLaw/mu") )
       {
         // FIXME - we'll need a special accessor to give parameter
         // access to these
         libMesh::Real lambda  = input("Physics/HookesLaw/lambda", 0.0);
         libMesh::Real mu = input("Physics/HookesLaw/mu", 0.0);
         _E  = mu*(3*lambda + 2*mu)/(lambda+mu);
         _nu = lambda/(2*(lambda+mu));
       }
     else
       {
         if( input.have_variable("Physics/HookesLaw/E") )
           this->set_parameter
             (_E, input, "Physics/HookesLaw/E", 0.0);
         if( input.have_variable("Physics/HookesLaw/nu") )
           this->set_parameter
             (_nu, input, "Physics/HookesLaw/nu", 0.0);
       }
   }
Friends And Related Function Documentation
friend class StressStrainLaw< HookesLaw1D > friend
Definition at line 55 of file hookes_law_1d.h.
Member Data Documentation
libMesh::Real GRINS::HookesLaw1D::_E private
Lam\'{e} constant.
Definition at line 85 of file hookes_law_1d.h.
Referenced by compute_stress_and_elasticity_imp(), compute_stress_imp(), HookesLaw1D(), and read_input_options().
libMesh::Real GRINS::HookesLaw1D::_nu private
Lam\'{e} constant.
Definition at line 88 of file hookes_law_1d.h.
Referenced by HookesLaw1D(), and read_input_options().
The documentation for this class was generated from the following files:
src/properties/include/grins/hookes_law_1d.h
src/properties/src/hookes_law_1d.C