GRINS-0.8.0: GRINS::GRINSPrivate::VariableWarehouse Class Reference
GRINS::GRINSPrivate::VariableWarehouse Class Reference
Track what FEVariablesBase objects have been created.
#include <variable_warehouse.h>
Public Member Functions
VariableWarehouse ()
~VariableWarehouse ()
Static Public Member Functions
static bool is_registered (const std::string &var_name)
Check if variable is registered.
static void check_and_register_variable (const std::string &var_name, SharedPtr< FEVariablesBase > &variable)
First check if var_name is registered and then register.
static void register_variable (const std::string &var_name, SharedPtr< FEVariablesBase > &variable)
static SharedPtr< FEVariablesBase > get_variable_ptr (const std::string &var_name)
static FEVariablesBase & get_variable (const std::string &var_name)
template<typename DerivedType >
static DerivedType & get_variable_subclass (const std::string &var_name)
static void clear ()
Clears the var_map()
Static Protected Member Functions
static std::map< std::string, SharedPtr< FEVariablesBase > > & var_map ()
Detailed Description
Track what FEVariablesBase objects have been created.
Several modules need to interact with the Variables in use. So, this object creates a place to register a Variable class.
Todo:
Currently, we only allow only unique variable types. This will change in the future once we allow per-subdomain variables. Hence, we have this in GRINSPrivate since the API may change in the future.
Definition at line 49 of file variable_warehouse.h.
Constructor & Destructor Documentation
GRINS::GRINSPrivate::VariableWarehouse::VariableWarehouse () inline
Definition at line 52 of file variable_warehouse.h.
 {};
GRINS::GRINSPrivate::VariableWarehouse::~VariableWarehouse () inline
Definition at line 54 of file variable_warehouse.h.
 {};
Member Function Documentation
void GRINS::GRINSPrivate::VariableWarehouse::check_and_register_variable (const std::string & var_name, SharedPtr< FEVariablesBase > & variable) inline static
First check if var_name is registered and then register.
Use this API if you may be attempting to register the same variable more than once.
Definition at line 93 of file variable_warehouse.h.
References is_registered(), and register_variable().
     {
       if( !VariableWarehouse::is_registered(var_name) )
         VariableWarehouse::register_variable(var_name,variable);
     }
static void GRINS::GRINSPrivate::VariableWarehouse::clear () inline static
Clears the var_map()
Definition at line 76 of file variable_warehouse.h.
References var_map().
Referenced by GRINSTesting::SpectroscopicAbsorptionTest::tearDown(), GRINSTesting::IntegratedFunctionTest::tearDown(), GRINSTesting::VariablesTest::test_var_constraint(), GRINSTesting::VariablesTest::test_variable_arbitrary_names(), and GRINSTesting::VariablesTest::test_variable_builder().
       { var_map().clear(); }
FEVariablesBase & GRINS::GRINSPrivate::VariableWarehouse::get_variable (const std::string & var_name) inline static
Definition at line 111 of file variable_warehouse.h.
References get_variable_ptr().
Referenced by GRINS::DefaultBCBuilder::build_axisymmetric_bcs(), GRINS::DefaultBCBuilder::build_bcs_by_var_section(), GRINS::OldStyleBCBuilder::determine_variable_group(), GRINS::CatalyticWallNeumannBCFactoryCommon< ImplType >::extract_temp_var(), get_variable_subclass(), GRINSTesting::VariablesTest::test_all_variables(), and GRINSTesting::VariablesTest::test_var_constraint().
     {
       SharedPtr<FEVariablesBase> var_ptr = VariableWarehouse::get_variable_ptr(var_name);
       return *var_ptr;
     }
SharedPtr< FEVariablesBase > GRINS::GRINSPrivate::VariableWarehouse::get_variable_ptr (const std::string & var_name) static
Definition at line 38 of file variable_warehouse.C.
References is_registered(), and var_map().
Referenced by get_variable().
     {
       if( !VariableWarehouse::is_registered(var_name) )
         {
           const std::map<std::string,SharedPtr<FEVariablesBase> >& map = var_map();
           std::stringstream error_msg;
           error_msg << "ERROR: Could not find Variable "+var_name+" in the VariableWarehouse!"
                     << std::endl
                     << "       Variables currently the VariableWarehouse are: "
                     << (map.begin())->first << std::endl;
           std::map<std::string,SharedPtr<FEVariablesBase> >::const_iterator it = map.begin();
           it++;
           for( ; it != map.end(); ++it )
             error_msg << std::string(54,' ') << it->first << std::endl;
           libmesh_error_msg(error_msg.str());
         }
       SharedPtr<FEVariablesBase> var_ptr = var_map()[var_name];
       if( !var_ptr )
         libmesh_error_msg("ERROR: Variable "+var_name+" is an invalid pointer!");
       return var_ptr;
     }
template<typename DerivedType > DerivedType & GRINS::GRINSPrivate::VariableWarehouse::get_variable_subclass (const std::string & var_name) inline static
Definition at line 119 of file variable_warehouse.h.
References get_variable().
     {
       FEVariablesBase& var_base = VariableWarehouse::get_variable(var_name);
       DerivedType& derived_var = libMesh::cast_ref<DerivedType&>(var_base);
       return derived_var;
     }
bool GRINS::GRINSPrivate::VariableWarehouse::is_registered (const std::string & var_name) inline static
Check if variable is registered.
Definition at line 86 of file variable_warehouse.h.
References var_map().
Referenced by check_and_register_variable(), get_variable_ptr(), and register_variable().
     {
       bool var_found = (var_map().find(var_name) != var_map().end() );
       return var_found;
     }
void GRINS::GRINSPrivate::VariableWarehouse::register_variable (const std::string & var_name, SharedPtr< FEVariablesBase > & variable) inline static
Definition at line 101 of file variable_warehouse.h.
References is_registered(), and var_map().
Referenced by GRINS::VariableBuilder::add_variable_to_warehouse(), and check_and_register_variable().
     {
       if( VariableWarehouse::is_registered(var_name) )
         libmesh_error_msg("ERROR: Duplicate FEVariable registration not allowed!");
       var_map()[var_name] = variable;
     }
std::map< std::string, SharedPtr< FEVariablesBase > > & GRINS::GRINSPrivate::VariableWarehouse::var_map () static protected
Definition at line 32 of file variable_warehouse.C.
Referenced by clear(), get_variable_ptr(), is_registered(), and register_variable().
     {
       static std::map<std::string,SharedPtr<FEVariablesBase> > _var_map;
       return _var_map;
     }
The documentation for this class was generated from the following files:
src/variables/include/grins/variable_warehouse.h
src/variables/src/variable_warehouse.C