GRINS-0.7.0: GRINS::VelocityFEVariables Class Reference
GRINS::VelocityFEVariables Class Reference
#include <velocity_fe_variables.h>
Public Member Functions
VelocityFEVariables (const GetPot &input, const std::string &physics_name, bool is_constraint_var=false)
~VelocityFEVariables ()
virtual void init (libMesh::FEMSystem *system)
Add variables to the system.
VariableIndex u () const
VariableIndex v () const
VariableIndex w () const
Public Member Functions inherited from GRINS::MultiVarSingleFETypeVariable
MultiVarSingleFETypeVariable (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::vector< std::string > &old_var_names, const std::vector< std::string > &default_names, const std::string &subsection, const std::string &default_family, const std::string &default_order, bool is_constraint_var)
Deprecated, old style constructor.
MultiVarSingleFETypeVariable (const GetPot &input, const std::string &subsection, const std::vector< std::string > &default_names, bool is_constraint_var)
Primary constructor.
~MultiVarSingleFETypeVariable ()
Public Member Functions inherited from GRINS::SingleFETypeVariable
SingleFETypeVariable (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &subsection, const std::string &default_family, const std::string &default_order, bool is_constraint_var)
Deprecated, old style constructor.
SingleFETypeVariable (const GetPot &input, const std::string &subsection, bool is_constraint_var)
Primary constructor.
~SingleFETypeVariable ()
Public Member Functions inherited from GRINS::FEVariablesBase
FEVariablesBase (bool is_constraint_var)
~FEVariablesBase ()
bool is_constraint_var () const
void set_neumann_bc_is_positive (bool is_positive)
Reset whetever Neumann bc is postive or not.
libMesh::Real neumann_bc_sign () const
const std::vector< std::string > & active_var_names () const
Return the var names that are active from this class.
const std::vector< VariableIndex > & var_indices () const
Private Member Functions
VelocityFEVariables ()
std::string subsection () const
std::vector< std::string > old_var_names ()
std::vector< std::string > default_names ()
Private Attributes
unsigned int _u_idx
unsigned int _v_idx
unsigned int _w_idx
Additional Inherited Members
Protected Member Functions inherited from GRINS::SingleFETypeVariable
void parse_family_and_order (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &subsection, std::vector< GRINSEnums::FEFamily > &family, std::vector< GRINSEnums::Order > &order, const std::string &default_family, const std::string &default_order)
Helper function to parse FEFamily and Order.
void dup_family_order_check (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix) const
Check (and error if true) for old and new style FEFamily/Order input.
bool have_family_or_order (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &subsection) const
Check for no presence of FEFamily/Order input.
void parse_old_style_with_warning (const GetPot &input, const std::string &physics_name, const std::string &old_var_prefix, const std::string &default_family, const std::string &default_order, const std::string &subsection, GRINSEnums::FEFamily &family, GRINSEnums::Order &order)
void parse_new_style (const GetPot &input, const std::string &subsection, GRINSEnums::FEFamily &family, GRINSEnums::Order &order)
Protected Member Functions inherited from GRINS::FEVariablesBase
void parse_names_from_input (const GetPot &input, const std::string &subsection, std::vector< std::string > &var_names, const std::vector< std::string > &default_names)
Method to parse variable names from input.
void duplicate_name_section_check (const GetPot &input) const
Check for old name style and new name style. If both present, error.
bool check_dep_name_input (const GetPot &input, const std::string &new_subsection) const
Check for deprecated variable name input style.
Protected Attributes inherited from GRINS::FEVariablesBase
std::vector< VariableIndex > _vars
std::vector< std::string > _var_names
std::vector< GRINSEnums::FEFamily > _family
std::vector< GRINSEnums::Order > _order
bool _is_constraint_var
Tracks whether this is a constraint variable.
libMesh::Real _neumann_bc_sign
Track the sign of the Neumann BC term. Defaults to 1.0.
Detailed Description
Definition at line 36 of file velocity_fe_variables.h.
Constructor & Destructor Documentation
GRINS::VelocityFEVariables::VelocityFEVariables (const GetPot & input, const std::string & physics_name, bool is_constraint_var = false)
Definition at line 35 of file velocity_fe_variables.C.
     :  MultiVarSingleFETypeVariable(input,physics_name,"V_",this->old_var_names(),this->default_names(),
                                     this->subsection(),"LAGRANGE","SECOND",is_constraint_var),
        _u_idx(0),
        _v_idx(1),
        _w_idx(2)
   {}
GRINS::VelocityFEVariables::~VelocityFEVariables () inline
Definition at line 42 of file velocity_fe_variables.h.
 {};
GRINS::VelocityFEVariables::VelocityFEVariables () private
Member Function Documentation
std::vector<std::string> GRINS::VelocityFEVariables::default_names () inline private
Definition at line 66 of file velocity_fe_variables.h.
     {
       std::vector<std::string> var_names(3);
       var_names[0] = "u";
       var_names[1] = "v";
       var_names[2] = "w";
       return var_names;
     }
void GRINS::VelocityFEVariables::init (libMesh::FEMSystem * system) virtual
Add variables to the system.
This expects that _var_names has been setup during construction time by the subclasses.
Reimplemented from GRINS::SingleFETypeVariable.
Definition at line 44 of file velocity_fe_variables.C.
References GRINS::FEVariablesBase::_var_names, and GRINS::SingleFETypeVariable::init().
Referenced by GRINS::BoussinesqBuoyancyBase::init_variables(), GRINS::ReactingLowMachNavierStokesAbstract::init_variables(), GRINS::AxisymmetricBoussinesqBuoyancy::init_variables(), GRINSTesting::VariablesTest::test_var_constraint_and_warehouse(), GRINSTesting::VariablesTest::test_velocity_2d(), and GRINSTesting::VariablesTest::test_velocity_3d().
   {
     libmesh_assert_greater_equal(system->get_mesh().mesh_dimension(), 2);
     if ( system->get_mesh().mesh_dimension() < 3)
       _var_names.pop_back();
     SingleFETypeVariable::init(system);
   }
std::vector<std::string> GRINS::VelocityFEVariables::old_var_names () inline private
Definition at line 57 of file velocity_fe_variables.h.
     {
       std::vector<std::string> var_names(3);
       var_names[0] = "u_velocity";
       var_names[1] = "v_velocity";
       var_names[2] = "w_velocity";
       return var_names;
     }
std::string GRINS::VelocityFEVariables::subsection () const inline private
Definition at line 54 of file velocity_fe_variables.h.
References GRINS::VariablesParsing::velocity_section().
     { return VariablesParsing::velocity_section(); }
VariableIndex GRINS::VelocityFEVariables::u () const inline
Definition at line 80 of file velocity_fe_variables.h.
References _u_idx, and GRINS::FEVariablesBase::_vars.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_continuity(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_transient(), GRINS::SpalartAllmarasStabilizationHelper::compute_res_spalart_steady(), GRINS::BoussinesqBuoyancy::element_time_derivative(), GRINS::AxisymmetricBoussinesqBuoyancy::element_time_derivative(), GRINS::ReactingLowMachNavierStokesAbstract::init_context(), GRINS::AxisymmetricBoussinesqBuoyancy::init_context(), GRINS::ReactingLowMachNavierStokesAbstract::set_time_evolving_vars(), and GRINS::SpalartAllmarasHelper::vorticity().
   {
     return this->_vars[_u_idx];
   }
VariableIndex GRINS::VelocityFEVariables::v () const inline
Definition at line 86 of file velocity_fe_variables.h.
References _v_idx, and GRINS::FEVariablesBase::_vars.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_continuity(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_transient(), GRINS::SpalartAllmarasStabilizationHelper::compute_res_spalart_steady(), GRINS::BoussinesqBuoyancy::element_time_derivative(), GRINS::AxisymmetricBoussinesqBuoyancy::element_time_derivative(), GRINS::ReactingLowMachNavierStokesAbstract::set_time_evolving_vars(), and GRINS::SpalartAllmarasHelper::vorticity().
   {
     return this->_vars[_v_idx];
   }
VariableIndex GRINS::VelocityFEVariables::w () const inline
Definition at line 92 of file velocity_fe_variables.h.
References GRINS::FEVariablesBase::_vars, and _w_idx.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_continuity(), GRINS::HeatTransferStabilizationHelper::compute_res_energy_steady(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady(), GRINS::SpalartAllmarasStabilizationHelper::compute_res_spalart_steady(), GRINS::BoussinesqBuoyancy::element_time_derivative(), GRINS::ReactingLowMachNavierStokesAbstract::set_time_evolving_vars(), and GRINS::SpalartAllmarasHelper::vorticity().
   {
     return this->_vars[_w_idx];
   }
Member Data Documentation
unsigned int GRINS::VelocityFEVariables::_u_idx private
Definition at line 75 of file velocity_fe_variables.h.
Referenced by u().
unsigned int GRINS::VelocityFEVariables::_v_idx private
Definition at line 75 of file velocity_fe_variables.h.
Referenced by v().
unsigned int GRINS::VelocityFEVariables::_w_idx private
Definition at line 75 of file velocity_fe_variables.h.
Referenced by w().
The documentation for this class was generated from the following files:
src/variables/include/grins/velocity_fe_variables.h
src/variables/src/velocity_fe_variables.C