GRINS-0.6.0: GRINS::PBCContainer Class Reference
GRINS::PBCContainer Class Reference
Simple helper class to setup periodic boundary conditions.
#include <pbc_container.h>
Public Member Functions
PBCContainer ()
~PBCContainer ()
void set_master_bcid (const GRINS::BoundaryID bc_id)
Add variables that are constrained by the Dirichlet bc.
void set_slave_bcid (const GRINS::BoundaryID bc_id)
void set_offset_vector (const libMesh::RealVectorValue &offset_vector)
GRINS::BoundaryID get_master_bcid () const
GRINS::BoundaryID get_slave_bcid () const
const libMesh::RealVectorValue & get_offset_vector () const
Private Attributes
GRINS::BoundaryID _master_id
GRINS::BoundaryID _slave_id
libMesh::RealVectorValue _offset_vector
Detailed Description
Simple helper class to setup periodic boundary conditions.
This class is to temporarily stash data necessary for setting up libMesh::PeriodicBoundary objects. Actually instantiation of libMesh::DirichletBoundary object is handled internally by GRINS::BCHandlingBase::init_periodic_bcs. For each periodic bc pair there is a unique PBCContainer object.
Definition at line 43 of file pbc_container.h.
Constructor & Destructor Documentation
GRINS::PBCContainer::PBCContainer ()
Definition at line 31 of file pbc_container.C.
     : _master_id( -1 ),
       _slave_id( -1 ),
       _offset_vector( 0.0, 0.0, 0.0 )
   {
     return;
   }
GRINS::PBCContainer::~PBCContainer ()
Definition at line 39 of file pbc_container.C.
   {
     return;
   }
Member Function Documentation
BoundaryID GRINS::PBCContainer::get_master_bcid () const
Definition at line 62 of file pbc_container.C.
References _master_id.
   {
     return _master_id;
   }
const libMesh::RealVectorValue & GRINS::PBCContainer::get_offset_vector () const
Definition at line 72 of file pbc_container.C.
References _offset_vector.
   {
     return _offset_vector;
   }
BoundaryID GRINS::PBCContainer::get_slave_bcid () const
Definition at line 67 of file pbc_container.C.
References _slave_id.
   {
     return _slave_id;
   }
void GRINS::PBCContainer::set_master_bcid (const GRINS::BoundaryID bc_id)
Add variables that are constrained by the Dirichlet bc.
Definition at line 44 of file pbc_container.C.
References _master_id.
Referenced by GRINS::BCHandlingBase::init_bc_types().
   {
     _master_id = bc_id;
     return;
   }
void GRINS::PBCContainer::set_offset_vector (const libMesh::RealVectorValue & offset_vector)
Definition at line 56 of file pbc_container.C.
References _offset_vector.
Referenced by GRINS::BCHandlingBase::init_bc_types().
   {
     _offset_vector = offset_vector;
     return;
   }
void GRINS::PBCContainer::set_slave_bcid (const GRINS::BoundaryID bc_id)
Definition at line 50 of file pbc_container.C.
References _slave_id.
Referenced by GRINS::BCHandlingBase::init_bc_types().
   {
     _slave_id = bc_id;
     return;
   }
Member Data Documentation
GRINS::BoundaryID GRINS::PBCContainer::_master_id private
Definition at line 62 of file pbc_container.h.
Referenced by get_master_bcid(), and set_master_bcid().
libMesh::RealVectorValue GRINS::PBCContainer::_offset_vector private
Definition at line 63 of file pbc_container.h.
Referenced by get_offset_vector(), and set_offset_vector().
GRINS::BoundaryID GRINS::PBCContainer::_slave_id private
Definition at line 62 of file pbc_container.h.
Referenced by get_slave_bcid(), and set_slave_bcid().
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/pbc_container.h
src/boundary_conditions/src/pbc_container.C