GRINS-0.8.0: GRINS::SolverFactoryInitializer Class Reference
GRINS::SolverFactoryInitializer Class Reference
Initialize all Factory objects related to Solvers.
#include <solver_factory_initializer.h>
Public Member Functions
SolverFactoryInitializer ()
~SolverFactoryInitializer ()
Detailed Description
Initialize all Factory objects related to Solvers.
To avoid symbol stripping from static linking, we use this class to initialize/register the Solvers factory objects.
Relevant discussion: http://stackoverflow.com/questions/5202142/static-variable-initialization-over-a-library
Definition at line 35 of file solver_factory_initializer.h.
Constructor & Destructor Documentation
GRINS::SolverFactoryInitializer::SolverFactoryInitializer ()
Definition at line 40 of file solver_factory_initializer.C.
References GRINS::SolverNames::steady_mesh_adaptive_solver(), GRINS::SolverNames::steady_solver(), GRINS::SolverNames::unsteady_mesh_adaptive_solver(), and GRINS::SolverNames::unsteady_solver().
   {
     static SolverFactoryBasic<UnsteadySolver>
       grins_factory_unsteady_solver(SolverNames::unsteady_solver());
     static SolverFactoryBasic<SteadySolver>
       grins_factory_steady_solver(SolverNames::steady_solver());
     static SolverFactoryBasic<UnsteadyMeshAdaptiveSolver>
       grins_factory_unsteady_mesh_adapt_solver(SolverNames::unsteady_mesh_adaptive_solver());
     static SolverFactoryBasic<SteadyMeshAdaptiveSolver>
       grins_factory_steady_mesh_adapt_solver(SolverNames::steady_mesh_adaptive_solver());
   }
GRINS::SolverFactoryInitializer::~SolverFactoryInitializer () inline
Definition at line 39 of file solver_factory_initializer.h.
 {}
The documentation for this class was generated from the following files:
src/solver/include/grins/solver_factory_initializer.h
src/solver/src/solver_factory_initializer.C