GRINS-0.6.0: GRINS::CanteraThermodynamics Class Reference
GRINS::CanteraThermodynamics Class Reference
Wrapper class for evaluating thermo properties using Cantera.
#include <cantera_thermo.h>
Public Member Functions
CanteraThermodynamics (CanteraMixture &mixture)
~CanteraThermodynamics ()
libMesh::Real cp (const CachedValues &cache, unsigned int qp) const
libMesh::Real cv (const CachedValues &cache, unsigned int qp) const
libMesh::Real h (const CachedValues &cache, unsigned int qp, unsigned int species) const
void h (const CachedValues &cache, unsigned int qp, std::vector< libMesh::Real > &h) const
libMesh::Real h (const libMesh::Real &T, unsigned int species) const
Protected Attributes
CanteraMixture & _cantera_mixture
Cantera::IdealGasMix & _cantera_gas
Private Member Functions
CanteraThermodynamics ()
Detailed Description
Wrapper class for evaluating thermo properties using Cantera.
This class is expected to be constructed after threads have been forked and will only live during the lifetime of the thread. Note that this documentation will always be built regardless if Cantera is included in the GRINS build or not. Check configure output to confirm that Cantera was included in the build if you wish to use it.
Definition at line 61 of file cantera_thermo.h.
Constructor & Destructor Documentation
GRINS::CanteraThermodynamics::CanteraThermodynamics (CanteraMixture & mixture)
Definition at line 43 of file cantera_thermo.C.
     : _cantera_mixture(mixture),
       _cantera_gas(mixture.get_chemistry())
   {
     return;
   }
GRINS::CanteraThermodynamics::~CanteraThermodynamics ()
Definition at line 50 of file cantera_thermo.C.
   {
     return;
   }
GRINS::CanteraThermodynamics::CanteraThermodynamics () private
Member Function Documentation
libMesh::Real GRINS::CanteraThermodynamics::cp (const CachedValues & cache, unsigned int qp) const
Todo:
Need to make sure this will work in a threaded environment. Not sure if we will get thread lock here or not.
Definition at line 55 of file cantera_thermo.C.
References _cantera_gas, GRINS::CachedValues::get_cached_values(), GRINS::CachedValues::get_cached_vector_values(), GRINS::Cache::MASS_FRACTIONS, GRINS::Cache::TEMPERATURE, and GRINS::Cache::THERMO_PRESSURE.
Referenced by GRINS::CanteraEvaluator::cp(), and main().
   {
     const libMesh::Real T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     const libMesh::Real P = cache.get_cached_values(Cache::THERMO_PRESSURE)[qp];
     const std::vector<libMesh::Real>& Y = cache.get_cached_vector_values(Cache::MASS_FRACTIONS)[qp];
     libmesh_assert_equal_to( Y.size(), _cantera_gas.nSpecies() );
     libMesh::Real cp = 0.0;
     {
       libMesh::Threads::spin_mutex::scoped_lock lock(cantera_mutex);
       try
         {
           _cantera_gas.setState_TPY( T, P, &Y[0] );
           cp = _cantera_gas.cp_mass();
         }
       catch(Cantera::CanteraError)
         {
           Cantera::showErrors(std::cerr);
           libmesh_error();
         }
     }
     return cp;
   }
libMesh::Real GRINS::CanteraThermodynamics::cv (const CachedValues & cache, unsigned int qp) const
Todo:
Need to make sure this will work in a threaded environment. Not sure if we will get thread lock here or not.
Definition at line 87 of file cantera_thermo.C.
References _cantera_gas, GRINS::CachedValues::get_cached_values(), GRINS::CachedValues::get_cached_vector_values(), GRINS::Cache::MASS_FRACTIONS, GRINS::Cache::TEMPERATURE, and GRINS::Cache::THERMO_PRESSURE.
Referenced by GRINS::CanteraEvaluator::cv(), and main().
   {
     const libMesh::Real T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     const libMesh::Real P = cache.get_cached_values(Cache::THERMO_PRESSURE)[qp];
     const std::vector<libMesh::Real>& Y = cache.get_cached_vector_values(Cache::MASS_FRACTIONS)[qp];
     libmesh_assert_equal_to( Y.size(), _cantera_gas.nSpecies() );
     libMesh::Real cv = 0.0;
     {
       libMesh::Threads::spin_mutex::scoped_lock lock(cantera_mutex);
       try
         {
           _cantera_gas.setState_TPY( T, P, &Y[0] );
           cv = _cantera_gas.cv_mass();
         }
       catch(Cantera::CanteraError)
         {
           Cantera::showErrors(std::cerr);
           libmesh_error();
         }
     }
     return cv;
   }
libMesh::Real GRINS::CanteraThermodynamics::h (const CachedValues & cache, unsigned int qp, unsigned int species) const
Todo:
Need to make sure this will work in a threaded environment. Not sure if we will get thread lock here or not.
Definition at line 119 of file cantera_thermo.C.
References _cantera_gas, _cantera_mixture, GRINS::CachedValues::get_cached_values(), GRINS::CachedValues::get_cached_vector_values(), GRINS::Cache::MASS_FRACTIONS, GRINS::CanteraMixture::R(), GRINS::Cache::TEMPERATURE, and GRINS::Cache::THERMO_PRESSURE.
Referenced by GRINS::CanteraEvaluator::h_s(), and main().
   {
     const libMesh::Real T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     const libMesh::Real P = cache.get_cached_values(Cache::THERMO_PRESSURE)[qp];
     const std::vector<libMesh::Real>& Y = cache.get_cached_vector_values(Cache::MASS_FRACTIONS)[qp];
     libmesh_assert_equal_to( Y.size(), _cantera_gas.nSpecies() );
     std::vector<libMesh::Real> h_RT( Y.size(), 0.0 );
     {
       libMesh::Threads::spin_mutex::scoped_lock lock(cantera_mutex);
       try
         {
           _cantera_gas.setState_TPY( T, P, &Y[0] );
           _cantera_gas.getEnthalpy_RT( &h_RT[0] );
         }
       catch(Cantera::CanteraError)
         {
           Cantera::showErrors(std::cerr);
           libmesh_error();
         }
     }
     return h_RT[species]*_cantera_mixture.R(species)*T;
   }
void GRINS::CanteraThermodynamics::h (const CachedValues & cache, unsigned int qp, std::vector< libMesh::Real > & h) const
Todo:
Need to make sure this will work in a threaded environment. Not sure if we will get thread lock here or not.
Definition at line 152 of file cantera_thermo.C.
References _cantera_gas, _cantera_mixture, GRINS::CachedValues::get_cached_values(), GRINS::CachedValues::get_cached_vector_values(), GRINS::Cache::MASS_FRACTIONS, GRINS::CanteraMixture::R(), GRINS::Cache::TEMPERATURE, and GRINS::Cache::THERMO_PRESSURE.
   {
     const libMesh::Real T = cache.get_cached_values(Cache::TEMPERATURE)[qp];
     const libMesh::Real P = cache.get_cached_values(Cache::THERMO_PRESSURE)[qp];
     const std::vector<libMesh::Real>& Y = cache.get_cached_vector_values(Cache::MASS_FRACTIONS)[qp];
     libmesh_assert_equal_to( Y.size(), h.size() );
     libmesh_assert_equal_to( Y.size(), _cantera_gas.nSpecies() );
     {
       libMesh::Threads::spin_mutex::scoped_lock lock(cantera_mutex);
       try
         {
           _cantera_gas.setState_TPY( T, P, &Y[0] );
           _cantera_gas.getEnthalpy_RT( &h[0] );
         }
       catch(Cantera::CanteraError)
         {
           Cantera::showErrors(std::cerr);
           libmesh_error();
         }
     for( unsigned int s = 0; s < h.size(); s++ )
       {
         h[s] *= _cantera_mixture.R(s)*T;
       }
     }
     return;
   }
libMesh::Real GRINS::CanteraThermodynamics::h (const libMesh::Real & T, unsigned int species) const
Definition at line 189 of file cantera_thermo.C.
References _cantera_gas, _cantera_mixture, and GRINS::CanteraMixture::R().
   {
     std::vector<libMesh::Real> h_RT( _cantera_gas.nSpecies(), 0.0 );
     try
       {
         _cantera_gas.setTemperature( T );
         _cantera_gas.getEnthalpy_RT( &h_RT[0] );
       }
     catch(Cantera::CanteraError)
       {
         Cantera::showErrors(std::cerr);
         libmesh_error();
       }
     return h_RT[species]*_cantera_mixture.R(species)*T;
   }
Member Data Documentation
Cantera::IdealGasMix& GRINS::CanteraThermodynamics::_cantera_gas protected
Definition at line 82 of file cantera_thermo.h.
Referenced by cp(), cv(), and h().
CanteraMixture& GRINS::CanteraThermodynamics::_cantera_mixture protected
Definition at line 80 of file cantera_thermo.h.
Referenced by h().
The documentation for this class was generated from the following files:
src/properties/include/grins/cantera_thermo.h
src/properties/src/cantera_thermo.C