GRINS-0.7.0: GRINS::ConstantPrandtlConductivity Class Reference
GRINS::ConstantPrandtlConductivity Class Reference
#include <constant_prandtl_conductivity.h>
Public Member Functions
ConstantPrandtlConductivity (const GetPot &input, const std::string &material)
Constructor with specified material.
ConstantPrandtlConductivity (const GetPot &input)
Deprecated constructor.
~ConstantPrandtlConductivity ()
libMesh::Real operator() (const libMesh::Real mu, const libMesh::Real cp) const
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Private Attributes
libMesh::Real _Pr
Additional Inherited Members
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Detailed Description
Definition at line 39 of file constant_prandtl_conductivity.h.
Constructor & Destructor Documentation
GRINS::ConstantPrandtlConductivity::ConstantPrandtlConductivity (const GetPot & input, const std::string & material)
Constructor with specified material.
Will look in the input file for [Materials/material/ThermalConductivity/Pr] for the value of viscosity.
Definition at line 59 of file constant_prandtl_conductivity.C.
References _Pr, GRINS::MaterialsParsing::dep_input_warning(), GRINS::MaterialsParsing::duplicate_input_test(), and GRINS::ParameterUser::set_parameter().
     : ParameterUser("ConstantPrandtlConductivity"),
       _Pr(0.0)
   {
     // We can't have both the materials version and the old versions
     MaterialsParsing::duplicate_input_test(input,
                                            "Materials/"+material+"/PrandtlNumber/value",
                                            "Materials/Conductivity/Pr" );
     // If we have the "new" version, then parse it
     if( input.have_variable("Materials/"+material+"/PrandtlNumber/value") )
       {
         this->set_parameter
           (_Pr, input, "Materials/"+material+"/PrandtlNumber/value", _Pr);
       }
     // If instead we have the old version, use that.
     else if( input.have_variable("Materials/Conductivity/Pr") )
       {
         MaterialsParsing::dep_input_warning( "Materials/Conductivity/Pr",
                                              "PrandtlNumber/value" );
         this->set_parameter
           (_Pr, input, "Materials/Conductivity/Pr", _Pr);
       }
   }
GRINS::ConstantPrandtlConductivity::ConstantPrandtlConductivity (const GetPot & input)
Deprecated constructor.
Definition at line 39 of file constant_prandtl_conductivity.C.
References _Pr, grins_warning, and GRINS::ParameterUser::set_parameter().
     : ParameterUser("ConstantPrandtlConductivity"),
       _Pr(0.0)
   {
     // Warning about this constructor being deprecated
     {
       std::string warning = "WARNING: Use of this constructor is DEPRECATED.\n";
       warning += "         Please update to use constructor with input material name.\n";
       grins_warning(warning);
     }
     if( !input.have_variable("Materials/Conductivity/Pr") )
       {
         libmesh_error_msg("Error: Must specify Prandtl number for constant_prandtl conductivity model!");
       }
     this->set_parameter
       (_Pr, input, "Materials/Conductivity/Pr", _Pr);
   }
GRINS::ConstantPrandtlConductivity::~ConstantPrandtlConductivity ()
Definition at line 85 of file constant_prandtl_conductivity.C.
   {
     return;
   }
Member Function Documentation
libMesh::Real GRINS::ConstantPrandtlConductivity::operator() (const libMesh::Real mu, const libMesh::Real cp) const inline
Definition at line 62 of file constant_prandtl_conductivity.h.
References _Pr.
   {
     return mu*cp/_Pr;
   }
Member Data Documentation
libMesh::Real GRINS::ConstantPrandtlConductivity::_Pr private
Definition at line 56 of file constant_prandtl_conductivity.h.
Referenced by ConstantPrandtlConductivity(), and operator()().
The documentation for this class was generated from the following files:
src/properties/include/grins/constant_prandtl_conductivity.h
src/properties/src/constant_prandtl_conductivity.C