GRINS-0.7.0: GRINS::PrescribedVectorValueDirichletOldStyleBCFactory Class Reference
GRINS::PrescribedVectorValueDirichletOldStyleBCFactory Class Reference abstract
#include <prescribed_vector_value_dirichlet_old_style_bc_factory.h>
Public Member Functions
PrescribedVectorValueDirichletOldStyleBCFactory (const std::string &bc_type_name)
~PrescribedVectorValueDirichletOldStyleBCFactory ()
Public Member Functions inherited from GRINS::DirichletBCFactoryFunctionOldStyleBase< libMesh::FunctionBase< libMesh::Number > >
DirichletBCFactoryFunctionOldStyleBase (const std::string &bc_type_name)
~DirichletBCFactoryFunctionOldStyleBase ()
Public Member Functions inherited from GRINS::DirichletBCFactoryFunctionBase< libMesh::FunctionBase< libMesh::Number > >
DirichletBCFactoryFunctionBase (const std::string &bc_type_name)
~DirichletBCFactoryFunctionBase ()
Public Member Functions inherited from GRINS::DirichletBCFactoryAbstract
DirichletBCFactoryAbstract (const std::string &bc_type_name)
~DirichletBCFactoryAbstract ()
Public Member Functions inherited from GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >
BCFactoryAbstract (const std::string &bc_type_name)
~BCFactoryAbstract ()
Public Member Functions inherited from GRINS::FactoryWithGetPot< libMesh::DirichletBoundary >
FactoryWithGetPot (const std::string &name)
~FactoryWithGetPot ()
Protected Member Functions
virtual std::string var_input_string ()=0
virtual libMesh::UniquePtr< libMesh::FunctionBase< libMesh::Number > > build_func (const GetPot &input, MultiphysicsSystem &system, std::vector< std::string > &var_names, const std::string &section)
Builds the FunctionBase object for boundary condition.
virtual void add_funcs (const GetPot &input, MultiphysicsSystem &system, const std::string &input_string, const std::vector< std::string > &var_names, libMesh::CompositeFunction< libMesh::Number > &composite_func) const
Protected Member Functions inherited from GRINS::DirichletBCFactoryFunctionOldStyleBase< libMesh::FunctionBase< libMesh::Number > >
virtual void check_state () const
Helper function.
virtual void reset_state ()
Helper function.
virtual const std::vector< std::string > & get_var_names () const
Helper function that can be overridded in subclasses.
Protected Member Functions inherited from GRINS::DirichletBCFactoryFunctionBase< libMesh::FunctionBase< libMesh::Number > >
libMesh::UniquePtr< libMesh::DirichletBoundary > make_dirichlet_boundary (const std::set< BoundaryID > &bc_ids, const libMesh::System &system, libMesh::UniquePtr< libMesh::FunctionBase< libMesh::Number > > &func, const std::vector< VariableIndex > &var_indices)
Dispatch, based on FunctionType, to the correct DirchletBoundary construction.
Protected Member Functions inherited from GRINS::DirichletBCFactoryAbstract
void check_for_vars (const GetPot &input, const std::string &section, const std::vector< std::string > &var_names, std::set< std::string > *vars_found=NULL)
Helper function.
Protected Member Functions inherited from GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >
void check_for_multiple_expressions (const GetPot &input, const std::string &section, const std::string &var_name) const
Ensure that there is only one expression for the [Section/var_name] variable.
void build_var_indices (const MultiphysicsSystem &system, const std::vector< std::string > &var_names, std::vector< VariableIndex > &var_indices) const
Additional Inherited Members
Static Public Member Functions inherited from GRINS::DirichletBCFactoryFunctionOldStyleBase< libMesh::FunctionBase< libMesh::Number > >
static void set_value_var_old_style (const std::string &value_var)
Input variable for parsing old style.
static void set_value_index_old_style (unsigned int idx)
Input variable index for parsing old style.
static void set_var_names_old_style (const std::vector< std::string > &var_names)
Static Public Member Functions inherited from GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >
static void set_system (MultiphysicsSystem &system)
static void set_bc_ids (const std::set< BoundaryID > &bc_ids)
Boundary id for the current boundary condition section.
static void set_fe_var (const FEVariablesBase &fe_var)
Active variable for the current boundary condition.
static void set_section (const std::string &section)
Sets the current section of the input file.
static bool have_bc_type (const std::string &bc_type)
Static Public Member Functions inherited from GRINS::FactoryWithGetPot< libMesh::DirichletBoundary >
static void set_getpot (const GetPot &input)
Static Protected Attributes inherited from GRINS::DirichletBCFactoryFunctionOldStyleBase< libMesh::FunctionBase< libMesh::Number > >
static std::string _value_var_old_style
static unsigned int _value_idx_old_style
static const std::vector< std::string > * _var_names_old_style
Static Protected Attributes inherited from GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >
static MultiphysicsSystem * _system
We store only a raw pointer here because we can't make a copy.
static const std::set< BoundaryID > * _bc_ids
BoundaryID for constructing a particular boundary condition.
static const FEVariablesBase * _fe_var
The FEVariablesBase class associated with the boundary condition being built.
static std::string _section
Static Protected Attributes inherited from GRINS::FactoryWithGetPot< libMesh::DirichletBoundary >
static const GetPot * _input
We store only a raw pointer here because we can't make a copy.
Detailed Description
Definition at line 36 of file prescribed_vector_value_dirichlet_old_style_bc_factory.h.
Constructor & Destructor Documentation
GRINS::PrescribedVectorValueDirichletOldStyleBCFactory::PrescribedVectorValueDirichletOldStyleBCFactory (const std::string & bc_type_name) inline
Definition at line 40 of file prescribed_vector_value_dirichlet_old_style_bc_factory.h.
       : DirichletBCFactoryFunctionOldStyleBase<libMesh::FunctionBase<libMesh::Number> >(bc_type_name)
     {}
GRINS::PrescribedVectorValueDirichletOldStyleBCFactory::~PrescribedVectorValueDirichletOldStyleBCFactory () inline
Definition at line 44 of file prescribed_vector_value_dirichlet_old_style_bc_factory.h.
 {};
Member Function Documentation
void GRINS::PrescribedVectorValueDirichletOldStyleBCFactory::add_funcs (const GetPot & input, MultiphysicsSystem & system, const std::string & input_string, const std::vector< std::string > & var_names, libMesh::CompositeFunction< libMesh::Number > & composite_func) const protected virtual
Reimplemented in GRINS::PrescribedMoleFractionsDirichletOldStyleBCFactory.
Definition at line 76 of file prescribed_vector_value_dirichlet_old_style_bc_factory.C.
Referenced by build_func().
   {
     for( unsigned int n = 0; n < var_names.size(); n++ )
       {
         std::vector<VariableIndex> dbc_vars(1,system.variable_number(var_names[n]));
         libMesh::Number value = input(input_string, 0.0, n);
         libMesh::ConstFunction<libMesh::Number> const_func(value);
         composite_func.attach_subfunction(const_func, dbc_vars);
       }
   }
libMesh::UniquePtr< libMesh::FunctionBase< libMesh::Number > > GRINS::PrescribedVectorValueDirichletOldStyleBCFactory::build_func (const GetPot & input, MultiphysicsSystem & system, std::vector< std::string > & var_names, const std::string & section) protected virtual
Builds the FunctionBase object for boundary condition.
Subclasses should override this function to build the FunctionBase object that corresponds to the variables passed in var_names. The variable names passed in will correspond to only a single VariableBase object, e.g. Velocity. The section arguments corresponds to the section to parse for the variables in the input file, e.g. input(section+"/"+var_names[0]).
The variable names passed in correspond to all the active variable names for a Variable group. The variable names present in var_names after this function is called will correspond to those variables. Note that var_names is NOT const. This is because one of the behaviors of subclasses may be to remove variables from the list. For example, for some symmetry conditions, we only want to enforce zero on certain components of the solution while leaving others untouched.
Implements GRINS::DirichletBCFactoryFunctionBase< libMesh::FunctionBase< libMesh::Number > >.
Definition at line 50 of file prescribed_vector_value_dirichlet_old_style_bc_factory.C.
References GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >::_bc_ids, add_funcs(), and var_input_string().
   {
     libmesh_assert_equal_to(DirichletBCFactoryAbstract::_bc_ids->size(), 1 );
     std::string bc_id_string = StringUtilities::T_to_string<BoundaryID>( *(_bc_ids->begin()) );
     std::string var_input_string = this->var_input_string();
     std::string input_string = section+"/"+var_input_string+"_"+bc_id_string;
     unsigned int n_comps = input.vector_variable_size(input_string);
     if( var_names.size() > n_comps )
       libmesh_error_msg("ERROR: Insufficient number of variable components in "+input_string+"!");
     libMesh::UniquePtr<libMesh::CompositeFunction<libMesh::Number> >
       remapped_func( new libMesh::CompositeFunction<libMesh::Number> );
     this->add_funcs(input,system,input_string,var_names,*(remapped_func.get()));
     return libMesh::UniquePtr<libMesh::FunctionBase<libMesh::Number> >(remapped_func.release());
   }
virtual std::string GRINS::PrescribedVectorValueDirichletOldStyleBCFactory::var_input_string () protected pure virtual
Implemented in GRINS::PrescribedSpeciesDirichletOldStyleBCFactory, GRINS::PrescribedDispDirichletOldStyleBCFactory, and GRINS::PrescribedVelDirichletOldStyleBCFactory.
Referenced by build_func().
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/prescribed_vector_value_dirichlet_old_style_bc_factory.h
src/boundary_conditions/src/prescribed_vector_value_dirichlet_old_style_bc_factory.C