GRINS-0.8.0: GRINS::GasSolidCatalyticWallNeumannBCFactoryImpl Class Reference
GRINS::GasSolidCatalyticWallNeumannBCFactoryImpl Class Reference
#include <gas_solid_catalytic_wall_neumann_bc_factory_impl.h>
Public Member Functions
GasSolidCatalyticWallNeumannBCFactoryImpl ()
~GasSolidCatalyticWallNeumannBCFactoryImpl ()
SharedPtr< NeumannBCAbstract > build_catalytic_wall (const GetPot &input, const std::string &reaction, SharedPtr< CatalycityBase > &gamma_ptr, const std::vector< VariableIndex > &species_vars, const std::string &material, VariableIndex T_var, libMesh::Real p0, const std::string &thermochem_lib)
void parse_reactants_and_product (const std::string &reaction, std::string &gas_reactant, std::string &solid_reactant, std::string &product) const
Protected Member Functions
template<typename ChemistryType >
void build_wall_ptr (SharedPtr< ChemistryType > &chem_ptr, SharedPtr< CatalycityBase > &gamma_ptr, const std::string &gas_reactant, const std::string &solid_reactant, const std::string &product, const std::vector< VariableIndex > &species_vars, VariableIndex T_var, libMesh::Real p0, SharedPtr< NeumannBCAbstract > &catalytic_wall)
Detailed Description
Definition at line 37 of file gas_solid_catalytic_wall_neumann_bc_factory_impl.h.
Constructor & Destructor Documentation
GRINS::GasSolidCatalyticWallNeumannBCFactoryImpl::GasSolidCatalyticWallNeumannBCFactoryImpl () inline
Definition at line 41 of file gas_solid_catalytic_wall_neumann_bc_factory_impl.h.
 {}
GRINS::GasSolidCatalyticWallNeumannBCFactoryImpl::~GasSolidCatalyticWallNeumannBCFactoryImpl () inline
Definition at line 43 of file gas_solid_catalytic_wall_neumann_bc_factory_impl.h.
 {}
Member Function Documentation
SharedPtr< NeumannBCAbstract > GRINS::GasSolidCatalyticWallNeumannBCFactoryImpl::build_catalytic_wall (const GetPot & input, const std::string & reaction, SharedPtr< CatalycityBase > & gamma_ptr, const std::vector< VariableIndex > & species_vars, const std::string & material, VariableIndex T_var, libMesh::Real p0, const std::string & thermochem_lib)
Todo:
Update the API for the catalytic walls to take a unique_ptr to avoid this garbage.
Todo:
Update the API for the catalytic walls to take a unique_ptr to avoid this garbage.
Definition at line 46 of file gas_solid_catalytic_wall_neumann_bc_factory_impl.C.
References GRINS::ChemistryBuilder::build_chemistry().
   {
     std::string gas_reactant;
     std::string solid_reactant;
     std::string product;
     this->parse_reactants_and_product(reaction,gas_reactant,solid_reactant,product);
     // Now construct the Neumann BC
     SharedPtr<NeumannBCAbstract> catalytic_wall;
     ChemistryBuilder chem_builder;
     if( thermochem_lib == "cantera" )
       {
 #ifdef GRINS_HAVE_CANTERA
         libMesh::UniquePtr<CanteraMixture> chem_uptr;
         chem_builder.build_chemistry(input,material,chem_uptr);
         SharedPtr<CanteraMixture> chem_ptr(chem_uptr.release());
         this->build_wall_ptr<CanteraMixture>(chem_ptr,gamma_ptr,gas_reactant,solid_reactant,
                                              product,species_vars,T_var,p0,catalytic_wall);
 #else
         libmesh_error_msg("Error: Cantera not enabled in this configuration. Reconfigure using --with-cantera option.");
 #endif
       }
     else if( thermochem_lib == "antioch" )
       {
 #ifdef GRINS_HAVE_ANTIOCH
         libMesh::UniquePtr<AntiochChemistry> chem_uptr;
         chem_builder.build_chemistry(input,material,chem_uptr);
         SharedPtr<AntiochChemistry> chem_ptr(chem_uptr.release());
         this->build_wall_ptr<AntiochChemistry>(chem_ptr,gamma_ptr,gas_reactant,solid_reactant,
                                                product,species_vars,T_var,p0,catalytic_wall);
 #else
         libmesh_error_msg("Error: Antioch not enabled in this configuration. Reconfigure using --with-antioch option.");
 #endif
       }
     else
       libmesh_error_msg("ERROR: Invalid thermochemistry library "+thermochem_lib+"!");
     return catalytic_wall;
   }
template<typename ChemistryType > void GRINS::GasSolidCatalyticWallNeumannBCFactoryImpl::build_wall_ptr (SharedPtr< ChemistryType > & chem_ptr, SharedPtr< CatalycityBase > & gamma_ptr, const std::string & gas_reactant, const std::string & solid_reactant, const std::string & product, const std::vector< VariableIndex > & species_vars, VariableIndex T_var, libMesh::Real p0, SharedPtr< NeumannBCAbstract > & catalytic_wall) inline protected
Definition at line 63 of file gas_solid_catalytic_wall_neumann_bc_factory_impl.h.
     {
       catalytic_wall.reset( new GasSolidCatalyticWall<ChemistryType>
                             ( chem_ptr,
                               gamma_ptr,
                               species_vars,
                               T_var,
                               p0,
                               chem_ptr->species_index(gas_reactant),
                               chem_ptr->species_index(solid_reactant),
                               chem_ptr->species_index(product) ) );
     }
void GRINS::GasSolidCatalyticWallNeumannBCFactoryImpl::parse_reactants_and_product (const std::string & reaction, std::string & gas_reactant, std::string & solid_reactant, std::string & product) const
Definition at line 103 of file gas_solid_catalytic_wall_neumann_bc_factory_impl.C.
References GRINS::StringUtilities::split_string().
Referenced by GRINS::GasSolidCatalyticWallNeumannBCOldStyleFactory::reactant_for_catalycity().
   {
     /* We are expecting reactions of the form
        X+Y(s)->Z  or
        Y(s)+X->X
        So, first we'll split on the "->", then split the reactants up and
        figure out which is the gas species and which is the solid species. */
     std::vector<std::string> partners;
     StringUtilities::split_string(reaction, "->", partners);
     const std::string pre_split_reactants = partners[0];
     product = partners[1];
     std::vector<std::string> split_reactants;
     StringUtilities::split_string(pre_split_reactants, "+", split_reactants);
     // We can only handle two reactants currently
     if( split_reactants.size() != 2 )
       {
         std::string error_msg = "ERROR: Currently, GasSolidCatalyticWall boundary condition only supports\n";
         error_msg += "       reactions of the form X+Y(s)->Z or Y(s)+X->X. Found ";
         error_msg += StringUtilities::T_to_string<unsigned int>(split_reactants.size())+" reactants.\n";
         libmesh_error_msg(error_msg);
       }
     // Check if the first reactant is the solid one
     if( split_reactants[0].find("(s)") == split_reactants[0].npos )
       {
         // If not found, check the second reactant and error out if not found.
         if( split_reactants[1].find("(s)") == split_reactants[1].npos )
           {
             std::string error_msg = "ERROR: could not find solid reactant for GasSolidCatalyticWall!\n";
             error_msg += "       Found reactants "+split_reactants[0]+", "+split_reactants[1]+"\n";
             libmesh_error_msg(error_msg);
           }
         else
           {
             gas_reactant = split_reactants[0];
             solid_reactant = split_reactants[1].substr(0,split_reactants[1].find("(s)"));
           }
       }
     // Found (s) in the first reactant
     else
       {
         // Check that there's not 2 solid reactants
         if( split_reactants[1].find("(s)") != split_reactants[1].npos )
           {
             std::string error_msg = "ERROR: can have only one solid reactant for GasSolidCatalyticWall!\n";
             error_msg += "       Found reactants "+split_reactants[0]+", "+split_reactants[1]+"\n";
             libmesh_error_msg(error_msg);
           }
         gas_reactant = split_reactants[1];
         solid_reactant = split_reactants[0].substr(0,split_reactants[0].find("(s)"));
       }
   }
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/gas_solid_catalytic_wall_neumann_bc_factory_impl.h
src/boundary_conditions/src/gas_solid_catalytic_wall_neumann_bc_factory_impl.C