GRINS-0.8.0: GRINS::ErrorEstimatorOptions Class Reference
GRINS::ErrorEstimatorOptions Class Reference
Container for ErrorEstimator options.
#include <error_estimator_options.h>
Public Member Functions
ErrorEstimatorOptions (const GetPot &input)
~ErrorEstimatorOptions ()
const std::string & estimator_type () const
bool patch_reuse () const
unsigned char n_adjoint_h_refinements () const
unsigned char n_adjoint_p_refinements () const
bool compute_qoi_error_estimate () const
bool estimator_requires_adjoint () const
Private Member Functions
void check_dup_input_style (const GetPot &input) const
bool is_old_style (const GetPot &input) const
void parse_old_style (const GetPot &input)
void parse_new_style (const GetPot &input)
Private Attributes
std::string _estimator_type
bool _patch_reuse
unsigned char _n_adjoint_h_refinements
unsigned char _n_adjoint_p_refinements
bool _compute_qoi_error_estimate
Detailed Description
Container for ErrorEstimator options.
Definition at line 37 of file error_estimator_options.h.
Constructor & Destructor Documentation
GRINS::ErrorEstimatorOptions::ErrorEstimatorOptions (const GetPot & input)
Definition at line 37 of file error_estimator_options.C.
References check_dup_input_style(), is_old_style(), parse_new_style(), and parse_old_style().
     : _estimator_type("none"),
       _patch_reuse(false),
       _n_adjoint_h_refinements(1),
       _n_adjoint_p_refinements(0),
       _compute_qoi_error_estimate(false)
   {
     this->check_dup_input_style(input);
     if( this->is_old_style(input) )
       this->parse_old_style(input);
     else
       this->parse_new_style(input);
   }
GRINS::ErrorEstimatorOptions::~ErrorEstimatorOptions () inline
Definition at line 42 of file error_estimator_options.h.
 {};
Member Function Documentation
void GRINS::ErrorEstimatorOptions::check_dup_input_style (const GetPot & input) const private
Definition at line 52 of file error_estimator_options.C.
Referenced by ErrorEstimatorOptions().
   {
     if( input.have_section("MeshAdaptivity") &&
         input.have_section("Strategies/ErrorEstimation") )
       libmesh_error_msg("ERROR: Cannot use both old and new style of options for ErrorEstimator!");
   }
bool GRINS::ErrorEstimatorOptions::compute_qoi_error_estimate () const inline
Definition at line 56 of file error_estimator_options.h.
References _compute_qoi_error_estimate.
Referenced by GRINS::SteadyMeshAdaptiveSolver::check_qoi_error_option_consistency(), and GRINS::SteadyMeshAdaptiveSolver::solve().
     { return _compute_qoi_error_estimate; }
bool GRINS::ErrorEstimatorOptions::estimator_requires_adjoint () const
Definition at line 89 of file error_estimator_options.C.
References _estimator_type, and GRINS::StrategiesParsing::adjoint_residual_error_estimator().
Referenced by GRINS::Simulation::check_for_adjoint_solve().
   {
     bool requires_adjoint = false;
     if( _estimator_type == StrategiesParsing::adjoint_residual_error_estimator() ||
         _estimator_type == StrategiesParsing::adjoint_residual_error_estimator() )
       requires_adjoint = true;
     return requires_adjoint;
   }
const std::string& GRINS::ErrorEstimatorOptions::estimator_type () const inline
Definition at line 44 of file error_estimator_options.h.
References _estimator_type.
Referenced by GRINS::Simulation::build_error_estimator(), and GRINS::Simulation::check_for_adjoint_solve().
     { return _estimator_type; }
bool GRINS::ErrorEstimatorOptions::is_old_style (const GetPot & input) const private
Definition at line 59 of file error_estimator_options.C.
Referenced by ErrorEstimatorOptions().
   {
     return input.have_section("MeshAdaptivity");
   }
unsigned char GRINS::ErrorEstimatorOptions::n_adjoint_h_refinements () const inline
Definition at line 50 of file error_estimator_options.h.
References _n_adjoint_h_refinements.
Referenced by GRINS::AdjointRefinementErrorEstimatorFactory::set_adjoint_estimator_options().
     { return _n_adjoint_h_refinements; }
unsigned char GRINS::ErrorEstimatorOptions::n_adjoint_p_refinements () const inline
Definition at line 53 of file error_estimator_options.h.
References _n_adjoint_p_refinements.
Referenced by GRINS::AdjointRefinementErrorEstimatorFactory::set_adjoint_estimator_options().
     { return _n_adjoint_p_refinements; }
void GRINS::ErrorEstimatorOptions::parse_new_style (const GetPot & input) private
Definition at line 80 of file error_estimator_options.C.
References _compute_qoi_error_estimate, _estimator_type, _n_adjoint_h_refinements, _n_adjoint_p_refinements, and _patch_reuse.
Referenced by ErrorEstimatorOptions().
   {
     _estimator_type = input("Strategies/ErrorEstimation/estimator_type", "none");
     _patch_reuse = input("Strategies/ErrorEstimation/patch_reuse", false);
     _n_adjoint_h_refinements = input("Strategies/ErrorEstimation/n_adjoint_h_refinements", 1);
     _n_adjoint_p_refinements = input("Strategies/ErrorEstimation/n_adjoint_p_refinements", 0);
     _compute_qoi_error_estimate = input("Strategies/ErrorEstimation/compute_qoi_error_estimate", false);
   }
void GRINS::ErrorEstimatorOptions::parse_old_style (const GetPot & input) private
Definition at line 64 of file error_estimator_options.C.
References _compute_qoi_error_estimate, _estimator_type, _n_adjoint_h_refinements, _n_adjoint_p_refinements, _patch_reuse, and grins_warning.
Referenced by ErrorEstimatorOptions().
   {
     {
       std::string warning = "WARNING: Using [MeshAdaptivity/<options>] is a DEPRECATED\n";
       warning += "         style of input for ErrorEstimator options. Please\n";
       warning += "         update to use the [Strategies/ErrorEstimation/<options> style.\n";
       grins_warning(warning);
     }
     _estimator_type = input("MeshAdaptivity/estimator_type", "none");
     _patch_reuse = input("MeshAdaptivity/patch_reuse", false);
     _n_adjoint_h_refinements = input("MeshAdaptivity/n_adjoint_h_refinements", 1);
     _n_adjoint_p_refinements = input("MeshAdaptivity/n_adjoint_p_refinements", 0);
     _compute_qoi_error_estimate = input("MeshAdaptivity/compute_qoi_error_estimate", false);
   }
bool GRINS::ErrorEstimatorOptions::patch_reuse () const inline
Definition at line 47 of file error_estimator_options.h.
References _patch_reuse.
Referenced by GRINS::AdjointResidualErrorEstimatorFactory::set_adjoint_estimator_options().
     { return _patch_reuse; }
Member Data Documentation
bool GRINS::ErrorEstimatorOptions::_compute_qoi_error_estimate private
Definition at line 75 of file error_estimator_options.h.
Referenced by compute_qoi_error_estimate(), parse_new_style(), and parse_old_style().
std::string GRINS::ErrorEstimatorOptions::_estimator_type private
Definition at line 71 of file error_estimator_options.h.
Referenced by estimator_requires_adjoint(), estimator_type(), parse_new_style(), and parse_old_style().
unsigned char GRINS::ErrorEstimatorOptions::_n_adjoint_h_refinements private
Definition at line 73 of file error_estimator_options.h.
Referenced by n_adjoint_h_refinements(), parse_new_style(), and parse_old_style().
unsigned char GRINS::ErrorEstimatorOptions::_n_adjoint_p_refinements private
Definition at line 74 of file error_estimator_options.h.
Referenced by n_adjoint_p_refinements(), parse_new_style(), and parse_old_style().
bool GRINS::ErrorEstimatorOptions::_patch_reuse private
Definition at line 72 of file error_estimator_options.h.
Referenced by parse_new_style(), parse_old_style(), and patch_reuse().
The documentation for this class was generated from the following files:
src/strategies/include/grins/error_estimator_options.h
src/strategies/src/error_estimator_options.C