GRINS-0.7.0: GRINS::SolidMechanicsAbstract Class Reference
GRINS::SolidMechanicsAbstract Class Reference
#include <solid_mechanics_abstract.h>
Public Member Functions
SolidMechanicsAbstract (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~SolidMechanicsAbstract ()
virtual void init_variables (libMesh::FEMSystem *system)
Initialize variables for this physics.
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Set which variables are time evolving.
Public Member Functions inherited from GRINS::Physics
Physics (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~Physics ()
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for element interiors.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void damping_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Damping matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_damping_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
ICHandlingBase * get_ic_handler ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Types
typedef const libMesh::DenseSubVector< libMesh::Number > &(libMesh::DiffContext::* VarFuncType) (unsigned int) const
typedef void(libMesh::FEMContext::* InteriorFuncType) (unsigned int, unsigned int, libMesh::Real &) const
typedef libMesh::Real(libMesh::DiffContext::* VarDerivType) () const
Protected Attributes
DisplacementFEVariables _disp_vars
Protected Attributes inherited from GRINS::Physics
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
Private Member Functions
SolidMechanicsAbstract ()
void register_variables ()
Additional Inherited Members
Static Public Member Functions inherited from GRINS::Physics
static void set_is_axisymmetric (bool is_axisymmetric)
Set whether we should treat the problem as axisymmetric.
static bool is_axisymmetric ()
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Member Functions inherited from GRINS::Physics
libMesh::UniquePtr< libMesh::FEGenericBase< libMesh::Real > > build_new_fe (const libMesh::Elem *elem, const libMesh::FEGenericBase< libMesh::Real > *fe, const libMesh::Point p)
void parse_enabled_subdomains (const GetPot &input, const std::string &physics_name)
Static Protected Attributes inherited from GRINS::Physics
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
static bool _is_axisymmetric = false
Caches whether we are solving an axisymmetric problem or not.
Detailed Description
Definition at line 37 of file solid_mechanics_abstract.h.
Member Typedef Documentation
typedef void(libMesh::FEMContext::* GRINS::SolidMechanicsAbstract::InteriorFuncType) (unsigned int, unsigned int, libMesh::Real &) const protected
Definition at line 57 of file solid_mechanics_abstract.h.
typedef libMesh::Real(libMesh::DiffContext::* GRINS::SolidMechanicsAbstract::VarDerivType) () const protected
Definition at line 59 of file solid_mechanics_abstract.h.
typedef const libMesh::DenseSubVector<libMesh::Number>&(libMesh::DiffContext::* GRINS::SolidMechanicsAbstract::VarFuncType) (unsigned int) const protected
Definition at line 55 of file solid_mechanics_abstract.h.
Constructor & Destructor Documentation
GRINS::SolidMechanicsAbstract::SolidMechanicsAbstract (const GRINS::PhysicsName & physics_name, const GetPot & input)
Definition at line 39 of file solid_mechanics_abstract.C.
References _disp_vars, register_variables(), and GRINS::FEVariablesBase::set_neumann_bc_is_positive().
     : Physics(physics_name,input),
       _disp_vars(input,physics_name,false,true)// is_2D = false, is_3D = true
   {
     this->register_variables();
     // For solid mechanics problems, we need to set the sign for tractions
     // to '-' since the second order time solvers use a Newton residual of the form
     // M(u)\ddot{u} + C(u)\dot{u} + F(u) + G(u) = 0
     // In this case, then, the natural boundary conditions for the weak form
     // will all have a '-', so we need to set that so the input tractions are
     // positive.
     _disp_vars.set_neumann_bc_is_positive(false);
   }
virtual GRINS::SolidMechanicsAbstract::~SolidMechanicsAbstract () inline virtual
Definition at line 44 of file solid_mechanics_abstract.h.
 {};
GRINS::SolidMechanicsAbstract::SolidMechanicsAbstract () private
Member Function Documentation
void GRINS::SolidMechanicsAbstract::init_variables (libMesh::FEMSystem * system) virtual
Initialize variables for this physics.
Implements GRINS::Physics.
Reimplemented in GRINS::ElasticMembraneBase< StressStrainLaw >.
Definition at line 55 of file solid_mechanics_abstract.C.
References _disp_vars, and GRINS::DisplacementFEVariables::init().
Referenced by GRINS::ElasticMembraneBase< StressStrainLaw >::init_variables().
   {
     _disp_vars.init(system);
   }
void GRINS::SolidMechanicsAbstract::register_variables () private
Definition at line 68 of file solid_mechanics_abstract.C.
References _disp_vars, GRINS::GRINSPrivate::VariableWarehouse::check_and_register_variable(), and GRINS::VariablesParsing::displacement_section().
Referenced by SolidMechanicsAbstract().
   {
     GRINSPrivate::VariableWarehouse::check_and_register_variable(VariablesParsing::displacement_section(),
                                                                  this->_disp_vars);
   }
void GRINS::SolidMechanicsAbstract::set_time_evolving_vars (libMesh::FEMSystem * system) virtual
Set which variables are time evolving.
Set those variables which evolve in time (as opposed to variables that behave like constraints). This is done separately from init_variables() because the MultiphysicsSystem must initialize its base class before time_evolving variables can be set. Default implementation is no time evolving variables.
Reimplemented from GRINS::Physics.
Definition at line 60 of file solid_mechanics_abstract.C.
References _disp_vars, GRINS::DisplacementFEVariables::u(), GRINS::DisplacementFEVariables::v(), and GRINS::DisplacementFEVariables::w().
   {
     // Tell the system to march temperature forward in time
     system->time_evolving(_disp_vars.u());
     system->time_evolving(_disp_vars.v());
     system->time_evolving(_disp_vars.w());
   }
Member Data Documentation
DisplacementFEVariables GRINS::SolidMechanicsAbstract::_disp_vars protected
Definition at line 53 of file solid_mechanics_abstract.h.
Referenced by GRINS::ElasticCableConstantGravity::element_time_derivative(), GRINS::ElasticMembraneConstantPressure::element_time_derivative(), GRINS::ElasticMembraneAbstract::get_fe(), GRINS::ElasticCableAbstract::get_fe(), init_variables(), register_variables(), set_time_evolving_vars(), and SolidMechanicsAbstract().
The documentation for this class was generated from the following files:
src/physics/include/grins/solid_mechanics_abstract.h
src/physics/src/solid_mechanics_abstract.C