GRINS-0.8.0: GRINS::PhysicsFactoryHelper Class Reference
GRINS::PhysicsFactoryHelper Class Reference
Helper functions for PhysicsFactory.
#include <physics_factory_helper.h>
Public Member Functions
PhysicsFactoryHelper ()
~PhysicsFactoryHelper ()
Static Public Member Functions
static void parse_viscosity_model (const GetPot &input, const std::string &physics, std::string &model)
Determine viscosity model based on given physics name.
static void parse_conductivity_model (const GetPot &input, const std::string &physics, std::string &model)
Determine conductivity model based on given physics name.
static void parse_specific_heat_model (const GetPot &input, const std::string &physics, std::string &model)
Determine specific heat model based on given physics name.
static void parse_turb_viscosity_model (const GetPot &input, const std::string &physics, std::string &model)
Determine viscosity model used by turblence classes.
static void parse_stress_strain_model (const GetPot &input, const std::string &physics, std::string &model, std::string &strain_energy)
Determine stress-strain law used by solid mechanics classes.
static void parse_thermochemistry_model (const GetPot &input, const std::string &physics, std::string &model)
Determine thermochemistry model type.
static void parse_antioch_models (const GetPot &input, const std::string &physics, std::string &transport_model, std::string &thermo_model, std::string &viscosity_model, std::string &conductivity_model, std::string &diffusivity_model)
Static Private Member Functions
static void deprecated_visc_model_parsing (bool have_viscosity_model, bool have_material, const GetPot &input, const std::string &physics, std::string &model)
Detailed Description
Helper functions for PhysicsFactory.
Definition at line 38 of file physics_factory_helper.h.
Constructor & Destructor Documentation
GRINS::PhysicsFactoryHelper::PhysicsFactoryHelper () inline
Definition at line 41 of file physics_factory_helper.h.
 {};
GRINS::PhysicsFactoryHelper::~PhysicsFactoryHelper () inline
Definition at line 42 of file physics_factory_helper.h.
 {};
Member Function Documentation
void GRINS::PhysicsFactoryHelper::deprecated_visc_model_parsing (bool have_viscosity_model, bool have_material, const GetPot & input, const std::string & physics, std::string & model) static private
Definition at line 407 of file physics_factory_helper.C.
References grins_warning, and GRINS::PhysicsNaming::incompressible_navier_stokes().
Referenced by parse_turb_viscosity_model(), and parse_viscosity_model().
   {
     bool have_viscosity_model = input.have_variable( "Physics/"+physics+"/viscosity_model");
     if( (have_material && have_ins_viscosity_model) ||
         (have_material && have_viscosity_model) )
       {
         libmesh_error_msg("Error: Cannot specify both viscosity_model and material.");
       }
     /* If the user hasn't specified the material or the viscosity_model,
        we're assuming they're using the old version. */
     if( !have_ins_viscosity_model && !have_material && !have_viscosity_model )
       {
         std::string warning = "Warning: Neither viscosity_model nor material were specified.\n";
         warning += "      We are assuming a constant viscosity model.\n";
         warning += "      This case is DEPRECATED.\n";
         warning += "      Please update and specify Physics/"+physics+"/material.\n";
         grins_warning(warning);
         model = "constant";
       }
     if( have_ins_viscosity_model )
       {
         std::string warning = "Warning: Option Physics/"+PhysicsNaming::incompressible_navier_stokes()+"/viscosity_model is DEPRECATED.\n";
         warning += "         Please update to use Physics/"+physics+"/material.\n";
         grins_warning(warning);
         model = input( "Physics/"+PhysicsNaming::incompressible_navier_stokes()+"/viscosity_model", "constant" );
       }
     if( have_viscosity_model )
       {
         std::string warning = "Warning: Option Physics/"+physics+"/viscosity_model is DEPRECATED.\n";
         warning += "         Please update to use Physics/"+physics+"/material.\n";
         grins_warning(warning);
         model = input( "Physics/"+physics+"/viscosity_model", "constant" );
       }
   }
void GRINS::PhysicsFactoryHelper::parse_antioch_models (const GetPot & input, const std::string & physics, std::string & transport_model, std::string & thermo_model, std::string & viscosity_model, std::string & conductivity_model, std::string & diffusivity_model) static
Definition at line 296 of file physics_factory_helper.C.
References GRINS::MaterialsParsing::check_for_input_option(), grins_warning, and GRINS::MaterialsParsing::material_name().
Referenced by GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_physics().
   {
     // Newer, preferred version
     std::string material = MaterialsParsing::material_name( input, physics );
     bool have_transport_model = input.have_variable( "Physics/Antioch/transport_model" );
     // It's an error to specify both the old and the new version
     if( have_transport_model &&
         input.have_variable("Materials/"+material+"/GasMixture/Antioch/transport_model") )
       {
         libmesh_error_msg("ERROR: Cannot specify both Materials/"+material+"/GasMixture/Antioch/transport_model and Physics/Antioch/transport_model!");
       }
     //Deprecated
     if( have_transport_model )
       {
         std::string warning = "Warning: Option Physics/Antioch/transport_model is DEPRECATED.\n";
         warning += "         Please update to use Use Materials/MATERIAL_NAME/GasMixture/Antioch/transport_model.\n";
         grins_warning(warning);
         transport_model = input( "Physics/Antioch/transport_model", "mixture_averaged" );
       }
     // mixing_model option is now deprecated in favor of transport_model
     else if( input.have_variable("Physics/Antioch/mixing_model") )
       {
         std::string warning = "Warning: Option Physics/Antioch/mixing_model is DEPRECATED.\n";
         warning += "         Please update to use Use Materials/MATERIAL_NAME/GasMixture/Antioch/transport_model.\n";
         grins_warning(warning);
         transport_model = input( "Physics/Antioch/mixing_model" , "mixture_averaged" );
       }
     // Preferred
     else if( input.have_variable("Materials/"+material+"/GasMixture/Antioch/transport_model") )
       {
         transport_model = input("Materials/"+material+"/GasMixture/Antioch/transport_model", "DIE!");
       }
     // Fail
     else
       {
         libmesh_error_msg("ERROR! Could not find valid transport_model input!");
       }
     // transport_model = wilke is deprecated
     if( transport_model == std::string("wilke") )
       {
         libMesh::err << "WARNING: Physics/Antioch/transport_model value of 'wilke' is deprecated!" << std::endl
                      << "         Replace Physics/Antioch/transport_model value with 'mixture_averaged'"
                      << std::endl;
         transport_model = "mixture_averaged";
       }
     // Now parse the remaining models
     //Deprecated
     if( have_transport_model || input.have_variable("Physics/Antioch/mixing_model") )
       {
         // We're tying all the other option specifications to transport_model.
         thermo_model = input( "Physics/Antioch/thermo_model", "stat_mech");
         viscosity_model = input( "Physics/Antioch/viscosity_model", "blottner");
         conductivity_model = input( "Physics/Antioch/conductivity_model", "eucken");
         diffusivity_model = input( "Physics/Antioch/diffusivity_model", "constant_lewis");
         // So they'd better not have the other version specified.
         if( input.have_variable("Materials/"+material+"/GasMixture/Antioch/thermo_model")       ||
             input.have_variable("Materials/"+material+"/GasMixture/Antioch/viscosity_model")    ||
             input.have_variable("Materials/"+material+"/GasMixture/Antioch/thermal_conductivity_model") ||
             input.have_variable("Materials/"+material+"/GasMixture/Antioch/mass_diffusivity_model") )
           {
             libmesh_error_msg("ERROR: Cannot specifiy Physics/Antioch/transport_model and then specify Materials/"+material+"/GasMixture/Antioch/<thermo,viscosity,conductivity,diffusivity>_model!");
           }
       }
     // Preferred
     else if( input.have_variable("Materials/"+material+"/GasMixture/Antioch/transport_model") )
       {
         // We're tying all the other option specifications to transport_model.
         // For the newer cases, we don't support a default, the user must specify
         // We're tying all the other option specifications to transport_model.
         MaterialsParsing::check_for_input_option(input,"Materials/"+material+"/GasMixture/Antioch/thermo_model");
         MaterialsParsing::check_for_input_option(input,"Materials/"+material+"/GasMixture/Antioch/viscosity_model");
         MaterialsParsing::check_for_input_option(input,"Materials/"+material+"/GasMixture/Antioch/thermal_conductivity_model");
         MaterialsParsing::check_for_input_option(input,"Materials/"+material+"/GasMixture/Antioch/mass_diffusivity_model");
         thermo_model = input( "Materials/"+material+"/GasMixture/Antioch/thermo_model", "DIE!");
         viscosity_model = input( "Materials/"+material+"/GasMixture/Antioch/viscosity_model", "DIE!");
         conductivity_model = input( "Materials/"+material+"/GasMixture/Antioch/thermal_conductivity_model", "DIE!");
         diffusivity_model = input( "Materials/"+material+"/GasMixture/Antioch/mass_diffusivity_model", "DIE!");
         // So they'd better not have the other version specified.
         if( input.have_variable("Physics/Antioch/thermo_model")       ||
             input.have_variable("Physics/Antioch/viscosity_model")    ||
             input.have_variable("Physics/Antioch/conductivity_model") ||
             input.have_variable("Physics/Antioch/diffusivity_model") )
           {
             libmesh_error_msg("ERROR: Cannot specifiy Materials/"+material+"/GasMixture/Antioch/transport_model and then specify Physics/Antioch/<thermo,viscosity,conductivity,diffusivity>_model!");
           }
       }
     // Fail
     else
       {
         libmesh_error_msg("ERROR! Could not find valid transport_model input!");
       }
   }
void GRINS::PhysicsFactoryHelper::parse_conductivity_model (const GetPot & input, const std::string & physics, std::string & model) static
Determine conductivity model based on given physics name.
Definition at line 61 of file physics_factory_helper.C.
References grins_warning, GRINS::MaterialsParsing::have_material(), GRINS::PhysicsNaming::heat_transfer(), GRINS::MaterialsParsing::material_name(), and GRINS::MaterialsParsing::thermal_conductivity_model().
Referenced by GRINS::PhysicsFactoryHeatTransfer< DerivedPhysics >::build_physics(), and GRINS::PhysicsFactoryVariableDensityFlow< DerivedPhysics >::build_physics().
   {
     // Newer, preferred version
     bool have_material = MaterialsParsing::have_material(input,physics);
     // Old deprecated versions
     bool have_ht_conductivity_model = input.have_variable("Physics/"+PhysicsNaming::heat_transfer()+"/conductivity_model");
     bool have_conductivity_model = input.have_variable("Physics/"+physics+"/conductivity_model");
     if( (have_material && have_conductivity_model) ||
         (have_material && have_ht_conductivity_model) )
       {
         libmesh_error_msg("Error: Cannot specify both conductivity_model and material.");
       }
     /* If the user hasn't specified the material or the conductivity_model,
        we're assuming they're using the old version.
        This is deprecated.*/
     if( !have_conductivity_model && !have_material && !have_ht_conductivity_model )
       {
         std::string warning = "Warning: Neither conductivity_model nor material were specified.\n";
         warning += "      We are assuming a constant conductivity model.\n";
         warning += "      This case is DEPRECATED.\n";
         warning += "      Please update and specify Physics/"+physics+"/material.\n";
         grins_warning(warning);
         model = "constant";
       }
     // Deprecated
     if( have_ht_conductivity_model )
       {
         std::string warning = "Warning: Option Physics/"+PhysicsNaming::heat_transfer()+"/conductivity_model is DEPRECATED.\n";
         warning += "         Please update to use Physics/"+physics+"/material.\n";
         grins_warning(warning);
         model = input( "Physics/"+PhysicsNaming::heat_transfer()+"/conductivity_model", "constant" );
       }
     // Deprecated
     if( have_conductivity_model )
       {
         std::string warning = "Warning: Option Physics/"+physics+"/conductivity_model is DEPRECATED.\n";
         warning += "         Please update to use Physics/"+physics+"/material.\n";
         grins_warning(warning);
         model = input( "Physics/"+physics+"/conductivity_model", "constant" );
       }
     // Preferred
     if( have_material )
       {
         std::string material = MaterialsParsing::material_name( input, physics );
         MaterialsParsing::thermal_conductivity_model( input, physics, material, model );
       }
     return;
   }
void GRINS::PhysicsFactoryHelper::parse_specific_heat_model (const GetPot & input, const std::string & physics, std::string & model) static
Determine specific heat model based on given physics name.
Definition at line 123 of file physics_factory_helper.C.
References grins_warning, GRINS::MaterialsParsing::have_material(), GRINS::PhysicsNaming::low_mach_navier_stokes(), GRINS::MaterialsParsing::material_name(), and GRINS::MaterialsParsing::specific_heat_model().
Referenced by GRINS::PhysicsFactoryVariableDensityFlow< DerivedPhysics >::build_physics().
   {
     // Newer, preferred version
     bool have_material = MaterialsParsing::have_material(input,physics);
     bool have_lmns_specific_heat_model = input.have_variable("Physics/"+PhysicsNaming::low_mach_navier_stokes()+"/specific_heat_model");
     if( have_material && have_lmns_specific_heat_model )
       {
         libmesh_error_msg("ERROR: Cannot specify both a material and Physics/"+PhysicsNaming::low_mach_navier_stokes()+"/specific_heat_model!");
       }
     // Deprecated
     if( have_lmns_specific_heat_model )
       {
         std::string warning = "Warning: Option Physics/"+PhysicsNaming::low_mach_navier_stokes()+"/specific_heat_model is DEPRECATED.\n";
         warning += "         Please update to use Physics/"+physics+"/material.\n";
         grins_warning(warning);
         model = input( "Physics/"+PhysicsNaming::low_mach_navier_stokes()+"/specific_heat_model", "constant" );
       }
     // Preferred
     if( have_material )
       {
         std::string material = MaterialsParsing::material_name( input, physics );
         MaterialsParsing::specific_heat_model( input, physics, material, model );
       }
   }
void GRINS::PhysicsFactoryHelper::parse_stress_strain_model (const GetPot & input, const std::string & physics, std::string & model, std::string & strain_energy) static
Determine stress-strain law used by solid mechanics classes.
Definition at line 195 of file physics_factory_helper.C.
References grins_warning, GRINS::MaterialsParsing::material_name(), and GRINS::MaterialsParsing::stress_strain_model().
Referenced by GRINS::PhysicsFactoryOneDStressSolids< DerivedPhysics >::build_physics(), and GRINS::PhysicsFactoryPlaneStressSolids< DerivedPhysics >::build_physics().
   {
     // Newer, preferred version
     std::string material = MaterialsParsing::material_name( input, physics );
     // Old deprecated version
     bool have_elasticity_model = input.have_variable("Physics/"+physics+"/elasticity_model");
     // It's an error to specify both the old and the new version
     if( have_elasticity_model &&
         input.have_variable("Materials/"+material+"/StressStrainLaw/model") )
       {
         libmesh_error_msg("ERROR: Cannot specify both Materials/"+material+"/StressStrainLaw/model and Physics/"+physics+"/elasticity_model!");
       }
     // It's an error if don't specify at least one of them
     if( !have_elasticity_model &&
         !input.have_variable("Materials/"+material+"/StressStrainLaw/model") )
       {
         // But since the old is deprecated, we'll just them to supply the new
         libmesh_error_msg("ERROR: Must specify Materials/"+material+"/StressStrainLaw/model!");
       }
     // Deprecated
     if( have_elasticity_model )
       {
         std::string warning = "Warning: Option Physics/"+physics+"/elasticity_model is DEPRECATED.\n";
         warning += "         Please update to use Materials/MATERIAL_NAME/StressStrainLaw/model.\n";
         grins_warning(warning);
         model = input( "Physics/"+physics+"/elasticity_model", "DIE!" );
         if( model == std::string("HookesLaw") )
           model = "hookes_law";
         if( model == std::string("MooneyRivlin") )
           {
             model = "incompressible_hyperelasticity";
             strain_energy = "mooney_rivlin";
           }
       }
     // Preferred
     else if( input.have_variable("Materials/"+material+"/StressStrainLaw/model") )
       {
         MaterialsParsing::stress_strain_model( input, physics, material,
                                                model, strain_energy );
       }
     // Wat?
     else
       {
         libmesh_error();
       }
   }
void GRINS::PhysicsFactoryHelper::parse_thermochemistry_model (const GetPot & input, const std::string & physics, std::string & model) static
Determine thermochemistry model type.
Definition at line 252 of file physics_factory_helper.C.
References GRINS::MaterialsParsing::material_name(), and GRINS::PhysicsNaming::reacting_low_mach_navier_stokes().
Referenced by GRINS::PrescribedMoleFractionsDirichletOldStyleBCFactory::add_funcs(), GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_physics(), and GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType >::parse_thermochem_model().
   {
     // Newer, preferred version
     std::string material = MaterialsParsing::material_name( input, physics );
     bool have_thermochem_lib = input.have_variable( "Physics/"+PhysicsNaming::reacting_low_mach_navier_stokes()+"/thermochemistry_library" );
     // It's an error to specify both the old and the new version
     if( have_thermochem_lib &&
         input.have_variable("Materials/"+material+"/GasMixture/thermochemistry_library") )
       {
         libmesh_error_msg("ERROR: Cannot specify both Materials/"+material+"/GasMixture/thermochemistry_library and Physics/"+PhysicsNaming::reacting_low_mach_navier_stokes()+"/thermochemistry_library!");
       }
     //Deprecated
     if( have_thermochem_lib )
       {
         model = input( "Physics/"+PhysicsNaming::reacting_low_mach_navier_stokes()+"/thermochemistry_library", "DIE!" );
       }
     // Preferred
     else if( input.have_variable("Materials/"+material+"/GasMixture/thermochemistry_library") )
       {
         model = input("Materials/"+material+"/GasMixture/thermochemistry_library", "DIE!");
       }
     // Fail
     else
       {
         libmesh_error_msg("ERROR! Could not find valid thermochemistry_library input!");
       }
     // Make sure we have a valid model
     if( model != std::string("antioch") &&
         model != std::string("cantera") )
       {
         std::string error = "ERROR! Invalid thermochemistry library value "+model+"!\n";
         error += "       Valid selections are: antioch\n";
         error += "                             cantera\n";
         libmesh_error_msg(error);
       }
   }
void GRINS::PhysicsFactoryHelper::parse_turb_viscosity_model (const GetPot & input, const std::string & physics, std::string & model) static
Determine viscosity model used by turblence classes.
Definition at line 155 of file physics_factory_helper.C.
References deprecated_visc_model_parsing(), GRINS::MaterialsParsing::have_material(), GRINS::PhysicsNaming::incompressible_navier_stokes(), GRINS::MaterialsParsing::material_name(), and GRINS::MaterialsParsing::turb_viscosity_model().
Referenced by GRINS::PhysicsFactoryIncompressibleTurbFlow< DerivedPhysics >::build_physics(), and GRINS::PhysicsFactoryIncompressibleFlow< DerivedPhysics >::build_physics().
   {
     // Newer, preferred version
     bool have_material = MaterialsParsing::have_material(input,physics);
     // Old deprecated version
     bool have_viscosity_model = input.have_variable("Physics/"+PhysicsNaming::incompressible_navier_stokes()+"/viscosity_model");
     PhysicsFactoryHelper::deprecated_visc_model_parsing(  have_viscosity_model,
                                                           have_material,
                                                           input,
                                                           physics,
                                                           model );
     // Additionally, we need to check if the turbulence Physics didn't
     // set the viscosity model, but the *non* turbulent viscosity_model
     // is set to spallartallmaras. In that case, the physical viscosity
     // model is 'constant'.
     if( !have_material &&
         input.have_variable( "Physics/"+PhysicsNaming::incompressible_navier_stokes()+"/viscosity_model") )
       {
         // If we got here, have_viscosity_model is true and might
         // be set to spallartallmaras
         if( input("Physics/"+PhysicsNaming::incompressible_navier_stokes()+"/viscosity_model", "DIE!") == std::string("spalartallmaras") )
           {
             model = "constant";
           }
       }
     if( have_material )
       {
         std::string material = MaterialsParsing::material_name( input, physics );
         MaterialsParsing::turb_viscosity_model( input, physics, material, model );
       }
     return;
   }
void GRINS::PhysicsFactoryHelper::parse_viscosity_model (const GetPot & input, const std::string & physics, std::string & model) static
Determine viscosity model based on given physics name.
Definition at line 38 of file physics_factory_helper.C.
References deprecated_visc_model_parsing(), GRINS::MaterialsParsing::have_material(), GRINS::PhysicsNaming::incompressible_navier_stokes(), GRINS::MaterialsParsing::material_name(), and GRINS::MaterialsParsing::viscosity_model().
Referenced by GRINS::PhysicsFactoryIncompressibleFlow< DerivedPhysics >::build_physics(), and GRINS::PhysicsFactoryVariableDensityFlow< DerivedPhysics >::build_physics().
   {
     // Newer, preferred version
     bool have_material = MaterialsParsing::have_material(input,physics);
     // Old deprecated version
     bool have_viscosity_model = input.have_variable("Physics/"+PhysicsNaming::incompressible_navier_stokes()+"/viscosity_model");
     PhysicsFactoryHelper::deprecated_visc_model_parsing(  have_viscosity_model,
                                                           have_material,
                                                           input,
                                                           physics,
                                                           model );
     if( have_material )
       {
         std::string material = MaterialsParsing::material_name( input, physics );
         MaterialsParsing::viscosity_model( input, physics, material, model );
       }
   }
The documentation for this class was generated from the following files:
src/physics/include/grins/physics_factory_helper.h
src/physics/src/physics_factory_helper.C