GRINS-0.7.0: GRINSTesting::SystemHelper Class Reference
GRINSTesting::SystemHelper Class Reference
Helper class for setting up basic GRINS::MultiphysicsSystem for unit testing.
#include <system_helper.h>
Protected Member Functions
void setup_multiphysics_system (const std::string &filename)
void reset_all ()
Protected Attributes
libMesh::UniquePtr< GetPot > _input
GRINS::SharedPtr< libMesh::UnstructuredMesh > _mesh
libMesh::UniquePtr< libMesh::EquationSystems > _es
GRINS::MultiphysicsSystem * _system
Detailed Description
Helper class for setting up basic GRINS::MultiphysicsSystem for unit testing.
Definition at line 38 of file system_helper.h.
Member Function Documentation
void GRINSTesting::SystemHelper::reset_all () inline protected
Definition at line 51 of file system_helper.h.
References _es, _input, and _mesh.
Referenced by GRINSTesting::DefaultBCBuilderTest::tearDown(), and GRINSTesting::VariablesTest::tearDown().
     {
       _input.reset();
       _es.reset(); // This will delete the system
       _mesh.reset();
     }
void GRINSTesting::SystemHelper::setup_multiphysics_system (const std::string & filename) inline protected
Definition at line 42 of file system_helper.h.
References _es, _input, _mesh, _system, GRINS::MeshBuilder::build(), and TestCommWorld.
Referenced by GRINSTesting::DefaultBCBuilderTest::test_parse_periodic_master_slave_ids(), GRINSTesting::DefaultBCBuilderTest::test_parse_periodic_offset(), GRINSTesting::DefaultBCBuilderTest::test_parse_var_sections(), GRINSTesting::VariablesTest::test_pressure(), GRINSTesting::VariablesTest::test_species_mass_fracs(), GRINSTesting::VariablesTest::test_temp(), GRINSTesting::VariablesTest::test_var_constraint_and_warehouse(), GRINSTesting::VariablesTest::test_velocity_2d(), GRINSTesting::VariablesTest::test_velocity_3d(), and GRINSTesting::DefaultBCBuilderTest::test_verify_bc_ids_with_mesh().
     {
       _input.reset( new GetPot(filename) );
       GRINS::MeshBuilder mesh_builder;
       _mesh = mesh_builder.build( *_input, *TestCommWorld );
       _es.reset( new libMesh::EquationSystems(*_mesh) );
       _system = &_es->add_system<GRINS::MultiphysicsSystem>( "GRINS-TEST" );
     }
Member Data Documentation
libMesh::UniquePtr<libMesh::EquationSystems> GRINSTesting::SystemHelper::_es protected
Definition at line 60 of file system_helper.h.
Referenced by reset_all(), and setup_multiphysics_system().
libMesh::UniquePtr<GetPot> GRINSTesting::SystemHelper::_input protected
Definition at line 58 of file system_helper.h.
Referenced by reset_all(), setup_multiphysics_system(), GRINSTesting::DefaultBCBuilderTest::test_parse_periodic_master_slave_ids(), GRINSTesting::DefaultBCBuilderTest::test_parse_periodic_offset(), GRINSTesting::DefaultBCBuilderTest::test_parse_var_sections(), GRINSTesting::VariablesTest::test_pressure(), GRINSTesting::VariablesTest::test_species_mass_fracs(), GRINSTesting::VariablesTest::test_temp(), GRINSTesting::VariablesTest::test_var_constraint_and_warehouse(), GRINSTesting::VariablesTest::test_velocity_2d(), GRINSTesting::VariablesTest::test_velocity_3d(), and GRINSTesting::DefaultBCBuilderTest::test_verify_bc_ids_with_mesh().
GRINS::SharedPtr<libMesh::UnstructuredMesh> GRINSTesting::SystemHelper::_mesh protected
Definition at line 59 of file system_helper.h.
Referenced by reset_all(), and setup_multiphysics_system().
GRINS::MultiphysicsSystem* GRINSTesting::SystemHelper::_system protected
Definition at line 63 of file system_helper.h.
Referenced by setup_multiphysics_system(), GRINSTesting::VariablesTest::test_pressure(), GRINSTesting::VariablesTest::test_species_mass_fracs(), GRINSTesting::VariablesTest::test_temp(), GRINSTesting::VariablesTest::test_var_constraint_and_warehouse(), GRINSTesting::VariablesTest::test_velocity_2d(), GRINSTesting::VariablesTest::test_velocity_3d(), and GRINSTesting::DefaultBCBuilderTest::test_verify_bc_ids_with_mesh().
The documentation for this class was generated from the following file:
test/common/system_helper.h