GRINS-0.8.0: GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo > Class Template Reference
GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo > Class Template Reference
Wrapper class for evaluating chemistry and thermo properties using Antioch.
#include <antioch_evaluator.h>
Public Member Functions
AntiochEvaluator (const AntiochMixture< KineticsThermoCurveFit > &mixture)
virtual ~AntiochEvaluator ()
libMesh::Real M (unsigned int species) const
libMesh::Real M_mix (const std::vector< libMesh::Real > &mass_fractions) const
libMesh::Real R (unsigned int species) const
libMesh::Real R_mix (const std::vector< libMesh::Real > &mass_fractions) const
libMesh::Real X (unsigned int species, libMesh::Real M, libMesh::Real mass_fraction) const
void X (libMesh::Real M, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &mole_fractions) const
unsigned int species_index (const std::string &species_name) const
std::string species_name (unsigned int species_index) const
libMesh::Real cp (const libMesh::Real &T, const libMesh::Real P, const std::vector< libMesh::Real > &Y)
libMesh::Real cv (const libMesh::Real &T, const libMesh::Real P, const std::vector< libMesh::Real > &Y)
libMesh::Real h_s (const libMesh::Real &T, unsigned int species)
void omega_dot (const libMesh::Real &T, libMesh::Real rho, const std::vector< libMesh::Real > mass_fractions, std::vector< libMesh::Real > &omega_dot)
template<>
libMesh::Real cp (const libMesh::Real &T, const libMesh::Real, const std::vector< libMesh::Real > &Y)
template<>
libMesh::Real cv (const libMesh::Real &T, const libMesh::Real, const std::vector< libMesh::Real > &Y)
template<>
libMesh::Real h_s (const libMesh::Real &T, unsigned int species)
template<>
libMesh::Real cp (const libMesh::Real &T, const libMesh::Real, const std::vector< libMesh::Real > &Y)
template<>
libMesh::Real cv (const libMesh::Real &T, const libMesh::Real, const std::vector< libMesh::Real > &Y)
template<>
libMesh::Real h_s (const libMesh::Real &T, unsigned int species)
Protected Member Functions
void check_and_reset_temp_cache (const libMesh::Real &T)
Helper method for managing _temp_cache.
void build_thermo (const AntiochMixture< KineticsThermoCurveFit > &mixture)
Protected Attributes
const AntiochMixture< KineticsThermoCurveFit > & _chem
libMesh::UniquePtr< Thermo > _thermo
Primary thermo object.
libMesh::UniquePtr< Antioch::NASAEvaluator< libMesh::Real, KineticsThermoCurveFit > > _nasa_evaluator
For some Thermo types, we also need to cache a NASAEvaluator.
libMesh::UniquePtr< AntiochKinetics< KineticsThermoCurveFit > > _kinetics
libMesh::Real _clipped_T
const libMesh::Real _minimum_T
libMesh::UniquePtr< Antioch::TempCache< libMesh::Real > > _temp_cache
Private Member Functions
AntiochEvaluator ()
void specialized_build_thermo (const AntiochMixture< KineticsThermoCurveFit > &mixture, libMesh::UniquePtr< Antioch::StatMechThermodynamics< libMesh::Real > > &thermo, thermo_type< Antioch::StatMechThermodynamics< libMesh::Real > >)
void specialized_build_thermo (const AntiochMixture< KineticsThermoCurveFit > &mixture, libMesh::UniquePtr< Antioch::IdealGasMicroThermo< Antioch::NASAEvaluator< libMesh::Real, KineticsThermoCurveFit >, libMesh::Real > > &thermo, thermo_type< Antioch::IdealGasMicroThermo< Antioch::NASAEvaluator< libMesh::Real, KineticsThermoCurveFit >, libMesh::Real > >)
Detailed Description
template<typename KineticsThermoCurveFit, typename Thermo>
class GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >
Wrapper class for evaluating chemistry and thermo properties using Antioch.
This class is expected to be constructed after threads have been forked and will only live during the lifetime of the thread. By default, Antioch is working in SI units. Note that this documentation will always be built regardless if Antioch is included in the GRINS build or not. Check configure output to confirm that Antioch was included in the build.
Definition at line 56 of file antioch_evaluator.h.
Constructor & Destructor Documentation
template<typename KineticsThermoCurveFit, typename Thermo > GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::AntiochEvaluator (const AntiochMixture< KineticsThermoCurveFit > & mixture)
Definition at line 44 of file antioch_evaluator.C.
References GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::build_thermo().
     : _chem( mixture ),
       _kinetics( new AntiochKinetics<KineticsThermoCurveFit>(mixture) ),
       _minimum_T( mixture.minimum_T() ),
       _temp_cache( new Antioch::TempCache<libMesh::Real>(1.0) )
   {
     this->build_thermo( mixture );
   }
template<typename KineticsThermoCurveFit, typename Thermo> virtual GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::~AntiochEvaluator () inline virtual
Definition at line 62 of file antioch_evaluator.h.
 {};
template<typename KineticsThermoCurveFit, typename Thermo> GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::AntiochEvaluator () private
Member Function Documentation
template<typename KineticsThermoCurveFit, typename Thermo> void GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::build_thermo (const AntiochMixture< KineticsThermoCurveFit > & mixture) inline protected
Definition at line 125 of file antioch_evaluator.h.
Referenced by GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::AntiochEvaluator().
     { specialized_build_thermo( mixture, _thermo, thermo_type<Thermo>() ); }
template<typename KineticsThermoCurveFit , typename Thermo > void GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::check_and_reset_temp_cache (const libMesh::Real & T) inline protected
Helper method for managing _temp_cache.
T MUST be pass-by-reference because of the structure of Antioch::TempCache!
Definition at line 220 of file antioch_evaluator.h.
   {
     _clipped_T = std::max(_minimum_T, T);
     // We can't compare T because it's a reference, so we may have already
     // changed it upstream. So, we compare the next cheapest thing.
     if( _temp_cache->T2 != _clipped_T*_clipped_T )
       _temp_cache.reset( new Antioch::TempCache<libMesh::Real>(_clipped_T) );
   }
template<> libMesh::Real GRINS::AntiochEvaluator< Antioch::CEACurveFit< libMesh::Real >, Antioch::IdealGasMicroThermo< Antioch::NASAEvaluator< libMesh::Real, Antioch::CEACurveFit< libMesh::Real > >, libMesh::Real > >::cp (const libMesh::Real & T, const libMesh::Real , const std::vector< libMesh::Real > & Y)
Definition at line 67 of file antioch_evaluator.C.
   {
     this->check_and_reset_temp_cache(T);
     return this->_nasa_evaluator->cp( *(_temp_cache.get()), Y );
   }
template<typename KineticsThermoCurveFit, typename Thermo> libMesh::Real GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::cp (const libMesh::Real & T, const libMesh::Real P, const std::vector< libMesh::Real > & Y)
Referenced by GRINS::AntiochConstantTransportEvaluator< KineticsThermoCurveFit, Thermo, Conductivity >::k().
template<> libMesh::Real GRINS::AntiochEvaluator< Antioch::CEACurveFit< libMesh::Real >, Antioch::StatMechThermodynamics< libMesh::Real > >::cp (const libMesh::Real & T, const libMesh::Real , const std::vector< libMesh::Real > & Y)
Definition at line 95 of file antioch_evaluator.C.
   {
     return this->_thermo->cp( T, T, Y );
   }
template<> libMesh::Real GRINS::AntiochEvaluator< Antioch::CEACurveFit< libMesh::Real >, Antioch::IdealGasMicroThermo< Antioch::NASAEvaluator< libMesh::Real, Antioch::CEACurveFit< libMesh::Real > >, libMesh::Real > >::cv (const libMesh::Real & T, const libMesh::Real , const std::vector< libMesh::Real > & Y)
Definition at line 77 of file antioch_evaluator.C.
   {
     this->check_and_reset_temp_cache(T);
     return this->_nasa_evaluator->cv( *(_temp_cache.get()), Y );
   }
template<typename KineticsThermoCurveFit, typename Thermo> libMesh::Real GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::cv (const libMesh::Real & T, const libMesh::Real P, const std::vector< libMesh::Real > & Y)
template<> libMesh::Real GRINS::AntiochEvaluator< Antioch::CEACurveFit< libMesh::Real >, Antioch::StatMechThermodynamics< libMesh::Real > >::cv (const libMesh::Real & T, const libMesh::Real , const std::vector< libMesh::Real > & Y)
Definition at line 103 of file antioch_evaluator.C.
   {
     return this->_thermo->cv( T, T, Y );
   }
template<> libMesh::Real GRINS::AntiochEvaluator< Antioch::CEACurveFit< libMesh::Real >, Antioch::IdealGasMicroThermo< Antioch::NASAEvaluator< libMesh::Real, Antioch::CEACurveFit< libMesh::Real > >, libMesh::Real > >::h_s (const libMesh::Real & T, unsigned int species)
Definition at line 87 of file antioch_evaluator.C.
   {
     this->check_and_reset_temp_cache(T);
     return this->_nasa_evaluator->h( *(_temp_cache.get()), species );;
   }
template<typename KineticsThermoCurveFit, typename Thermo> libMesh::Real GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::h_s (const libMesh::Real & T, unsigned int species)
template<> libMesh::Real GRINS::AntiochEvaluator< Antioch::CEACurveFit< libMesh::Real >, Antioch::StatMechThermodynamics< libMesh::Real > >::h_s (const libMesh::Real & T, unsigned int species)
Definition at line 111 of file antioch_evaluator.C.
   {
     return this->_thermo->h_tot( species, T ) + _chem.h_stat_mech_ref_correction(species);
   }
template<typename KineticsThermoCurveFit , typename Thermo > libMesh::Real GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::M (unsigned int species) const inline
Definition at line 153 of file antioch_evaluator.h.
   {
     return _chem.M(species);
   }
template<typename KineticsThermoCurveFit , typename Thermo > libMesh::Real GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::M_mix (const std::vector< libMesh::Real > & mass_fractions) const inline
Definition at line 162 of file antioch_evaluator.h.
   {
     return _chem.M_mix(mass_fractions);
   }
template<typename KineticsThermoCurveFit , typename Thermo > void GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::omega_dot (const libMesh::Real & T, libMesh::Real rho, const std::vector< libMesh::Real > mass_fractions, std::vector< libMesh::Real > & omega_dot)
Definition at line 55 of file antioch_evaluator.C.
   {
     this->check_and_reset_temp_cache(T);
     _kinetics->omega_dot( *(_temp_cache.get()), rho, mass_fractions, omega_dot );
   }
template<typename KineticsThermoCurveFit , typename Thermo > libMesh::Real GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::R (unsigned int species) const inline
Definition at line 170 of file antioch_evaluator.h.
   {
     return _chem.R(species);
   }
template<typename KineticsThermoCurveFit , typename Thermo > libMesh::Real GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::R_mix (const std::vector< libMesh::Real > & mass_fractions) const inline
Definition at line 179 of file antioch_evaluator.h.
   {
     return _chem.R_mix(mass_fractions);
   }
template<typename KineticsThermoCurveFit, typename Thermo> void GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::specialized_build_thermo (const AntiochMixture< KineticsThermoCurveFit > & mixture, libMesh::UniquePtr< Antioch::StatMechThermodynamics< libMesh::Real > > & thermo, thermo_type< Antioch::StatMechThermodynamics< libMesh::Real > >) inline private
Definition at line 132 of file antioch_evaluator.h.
Referenced by GRINS::AntiochEvaluator< Antioch::CEACurveFit< libMesh::Real >, Thermo >::build_thermo().
     {
       thermo.reset( new Antioch::StatMechThermodynamics<libMesh::Real>( mixture.chemical_mixture() ) );
     }
template<typename KineticsThermoCurveFit, typename Thermo> void GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::specialized_build_thermo (const AntiochMixture< KineticsThermoCurveFit > & mixture, libMesh::UniquePtr< Antioch::IdealGasMicroThermo< Antioch::NASAEvaluator< libMesh::Real, KineticsThermoCurveFit >, libMesh::Real > > & thermo, thermo_type< Antioch::IdealGasMicroThermo< Antioch::NASAEvaluator< libMesh::Real, KineticsThermoCurveFit >, libMesh::Real > >) inline private
Definition at line 139 of file antioch_evaluator.h.
     {
       _nasa_evaluator.reset( new Antioch::NASAEvaluator<libMesh::Real,KineticsThermoCurveFit>( mixture.nasa_mixture() ) );
       thermo.reset( new Antioch::IdealGasMicroThermo<Antioch::NASAEvaluator<libMesh::Real,KineticsThermoCurveFit>,libMesh::Real>( *_nasa_evaluator, mixture.chemical_mixture() ) );
     }
template<typename KineticsThermoCurveFit , typename Thermo > unsigned int GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::species_index (const std::string & species_name) const inline
Definition at line 205 of file antioch_evaluator.h.
   {
     return _chem.species_index(species_name);
   }
template<typename KineticsThermoCurveFit , typename Thermo > std::string GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::species_name (unsigned int species_index) const inline
Definition at line 213 of file antioch_evaluator.h.
   {
     return _chem.species_name(species_index);
   }
template<typename KineticsThermoCurveFit , typename Thermo > libMesh::Real GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::X (unsigned int species, libMesh::Real M, libMesh::Real mass_fraction) const inline
Definition at line 186 of file antioch_evaluator.h.
   {
     return _chem.X(species,M,mass_fraction);
   }
template<typename KineticsThermoCurveFit , typename Thermo > void GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::X (libMesh::Real M, const std::vector< libMesh::Real > & mass_fractions, std::vector< libMesh::Real > & mole_fractions) const inline
Definition at line 195 of file antioch_evaluator.h.
   {
     _chem.X(M,mass_fractions,mole_fractions);
   }
Member Data Documentation
template<typename KineticsThermoCurveFit, typename Thermo> const AntiochMixture<KineticsThermoCurveFit>& GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::_chem protected
Definition at line 96 of file antioch_evaluator.h.
template<typename KineticsThermoCurveFit, typename Thermo> libMesh::Real GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::_clipped_T protected
Definition at line 108 of file antioch_evaluator.h.
template<typename KineticsThermoCurveFit, typename Thermo> libMesh::UniquePtr<AntiochKinetics<KineticsThermoCurveFit> > GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::_kinetics protected
Definition at line 104 of file antioch_evaluator.h.
template<typename KineticsThermoCurveFit, typename Thermo> const libMesh::Real GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::_minimum_T protected
Definition at line 112 of file antioch_evaluator.h.
template<typename KineticsThermoCurveFit, typename Thermo> libMesh::UniquePtr<Antioch::NASAEvaluator<libMesh::Real,KineticsThermoCurveFit> > GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::_nasa_evaluator protected
For some Thermo types, we also need to cache a NASAEvaluator.
Definition at line 102 of file antioch_evaluator.h.
template<typename KineticsThermoCurveFit, typename Thermo> libMesh::UniquePtr<Antioch::TempCache<libMesh::Real> > GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::_temp_cache protected
Definition at line 114 of file antioch_evaluator.h.
template<typename KineticsThermoCurveFit, typename Thermo> libMesh::UniquePtr<Thermo> GRINS::AntiochEvaluator< KineticsThermoCurveFit, Thermo >::_thermo protected
Primary thermo object.
Definition at line 99 of file antioch_evaluator.h.
The documentation for this class was generated from the following files:
src/properties/include/grins/antioch_evaluator.h
src/properties/src/antioch_evaluator.C