GRINS-0.7.0: GRINSTesting::StringUtilitiesTest Class Reference
GRINSTesting::StringUtilitiesTest Class Reference
Public Member Functions
CPPUNIT_TEST_SUITE (StringUtilitiesTest)
CPPUNIT_TEST (test_split_string)
CPPUNIT_TEST (test_string_to_T)
CPPUNIT_TEST (test_T_to_string)
CPPUNIT_TEST_SUITE_END ()
void test_split_string ()
void test_string_to_T ()
void test_T_to_string ()
Private Member Functions
void test_string (const std::vector< std::string > &test, const std::vector< std::string > &exact)
Detailed Description
Definition at line 41 of file string_utils.C.
Member Function Documentation
GRINSTesting::StringUtilitiesTest::CPPUNIT_TEST (test_split_string)
GRINSTesting::StringUtilitiesTest::CPPUNIT_TEST (test_string_to_T)
GRINSTesting::StringUtilitiesTest::CPPUNIT_TEST (test_T_to_string)
GRINSTesting::StringUtilitiesTest::CPPUNIT_TEST_SUITE (StringUtilitiesTest)
GRINSTesting::StringUtilitiesTest::CPPUNIT_TEST_SUITE_END ()
void GRINSTesting::StringUtilitiesTest::test_split_string () inline
Definition at line 54 of file string_utils.C.
References GRINS::StringUtilities::split_string(), and test_string().
     {
       {
         std::string str_1("N->N2");
         std::vector<std::string> test_1_split_exact(2);
         test_1_split_exact[0] = std::string("N");
         test_1_split_exact[1] = std::string("N2");
         std::vector<std::string> str_1_split;
         GRINS::StringUtilities::split_string( str_1, "->", str_1_split);
         this->test_string( str_1_split, test_1_split_exact );
       }
       {
         std::string str_2("N+C(s)->CN");
         std::vector<std::string> test_2_split_exact(2);
         test_2_split_exact[0] = std::string("N+C(s)");
         test_2_split_exact[1] = std::string("CN");
         std::vector<std::string> str_2_split;
         GRINS::StringUtilities::split_string( str_2, "->", str_2_split);
         this->test_string( str_2_split, test_2_split_exact );
       }
       {
         std::string str_3("u:v:w:T:p:w_N:w_N2:p0");
         std::vector<std::string> test_3_split_exact(8);
         test_3_split_exact[0] = std::string("u");
         test_3_split_exact[1] = std::string("v");
         test_3_split_exact[2] = std::string("w");
         test_3_split_exact[3] = std::string("T");
         test_3_split_exact[4] = std::string("p");
         test_3_split_exact[5] = std::string("w_N");
         test_3_split_exact[6] = std::string("w_N2");
         test_3_split_exact[7] = std::string("p0");
         std::vector<std::string> str_3_split;
         GRINS::StringUtilities::split_string( str_3, ":", str_3_split);
         this->test_string( str_3_split, test_3_split_exact );
       }
       {
         std::string str_4("u v w T p w_N w_N2 p0");
         std::vector<std::string> test_4_split_exact(8);
         test_4_split_exact[0] = std::string("u");
         test_4_split_exact[1] = std::string("v");
         test_4_split_exact[2] = std::string("w");
         test_4_split_exact[3] = std::string("T");
         test_4_split_exact[4] = std::string("p");
         test_4_split_exact[5] = std::string("w_N");
         test_4_split_exact[6] = std::string("w_N2");
         test_4_split_exact[7] = std::string("p0");
         std::vector<std::string> str_4_split;
         GRINS::StringUtilities::split_string( str_4, " ", str_4_split);
         this->test_string( str_4_split, test_4_split_exact );
       }
     }
void GRINSTesting::StringUtilitiesTest::test_string (const std::vector< std::string > & test, const std::vector< std::string > & exact) inline private
Definition at line 151 of file string_utils.C.
Referenced by test_split_string().
     {
       CPPUNIT_ASSERT_EQUAL(test.size(), exact.size() );
       for( unsigned int s = 0; s < test.size(); s++ )
         CPPUNIT_ASSERT_EQUAL( test[s], exact[s] );
     }
void GRINSTesting::StringUtilitiesTest::test_string_to_T () inline
Definition at line 113 of file string_utils.C.
     {
       std::string one = "1";
       int ione = GRINS::StringUtilities::string_to_T<int>(one);
       unsigned int uione = GRINS::StringUtilities::string_to_T<unsigned int>(one);
       CPPUNIT_ASSERT_EQUAL(1,ione);
       CPPUNIT_ASSERT_EQUAL((unsigned int)1,uione);
       std::string tenp1 = "10.1";
       double dtenp1 = GRINS::StringUtilities::string_to_T<double>(tenp1);
       CPPUNIT_ASSERT_DOUBLES_EQUAL(10.1,
                                    dtenp1,
                                    std::numeric_limits<double>::epsilon());
     }
void GRINSTesting::StringUtilitiesTest::test_T_to_string () inline
Definition at line 128 of file string_utils.C.
     {
       std::string one_exact = "1";
       std::string tenp1_exact = "10.1";
       {
         std::string one_test =  GRINS::StringUtilities::T_to_string<int>(1);
         CPPUNIT_ASSERT_EQUAL(one_exact,one_test);
       }
       {
         std::string one_test =  GRINS::StringUtilities::T_to_string<unsigned int>(1);
         CPPUNIT_ASSERT_EQUAL(one_exact,one_test);
       }
       {
         std::string tenp1_test =  GRINS::StringUtilities::T_to_string<double>(10.1);
         CPPUNIT_ASSERT_EQUAL(tenp1_exact,tenp1_test);
       }
     }
The documentation for this class was generated from the following file:
test/unit/string_utils.C