GRINS-0.8.0: GRINS::SingleVariable Class Reference
GRINS::SingleVariable Class Reference
Variables with a single component.
#include <single_variable.h>
Public Member Functions
SingleVariable (const std::vector< std::string > &var_names, const std::vector< VariableIndex > &var_indices, const std::set< libMesh::subdomain_id_type > &subdomain_ids)
~SingleVariable ()
VariableIndex var () const
Public Member Functions inherited from GRINS::FEVariablesBase
FEVariablesBase (const std::vector< std::string > &var_names, const std::vector< VariableIndex > &var_indices, const std::set< libMesh::subdomain_id_type > &subdomain_ids)
virtual ~FEVariablesBase ()
void set_is_constraint_var (bool is_constraint_var)
Set whether or not this is a "constraint" variable.
bool is_constraint_var () const
void set_neumann_bc_is_positive (bool is_positive)
Reset whetever Neumann bc is postive or not.
libMesh::Real neumann_bc_sign () const
const std::vector< std::string > & active_var_names () const
Return the var names that are active from this class.
const std::vector< VariableIndex > & var_indices () const
const std::set< libMesh::subdomain_id_type > & subdomain_ids () const
Private Member Functions
SingleVariable ()
Additional Inherited Members
Protected Attributes inherited from GRINS::FEVariablesBase
std::vector< VariableIndex > _vars
std::vector< std::string > _var_names
bool _is_constraint_var
Tracks whether this is a constraint variable.
libMesh::Real _neumann_bc_sign
Track the sign of the Neumann BC term. Defaults to 1.0.
std::set< libMesh::subdomain_id_type > _subdomain_ids
Detailed Description
Variables with a single component.
Subclasses can add syntatic sugar, but this class can provide the sanity check on there actually being one component.
Definition at line 37 of file single_variable.h.
Constructor & Destructor Documentation
GRINS::SingleVariable::SingleVariable (const std::vector< std::string > & var_names, const std::vector< VariableIndex > & var_indices, const std::set< libMesh::subdomain_id_type > & subdomain_ids) inline
Definition at line 41 of file single_variable.h.
       : FEVariablesBase(var_names,var_indices, subdomain_ids )
     {
       if( var_names.size() != 1 )
         libmesh_error_msg("ERROR: SingleVariable must only have a single name!");
       if(var_indices.size() != 1)
         libmesh_error_msg("ERROR: SingleVariable must only have a single index!");
     }
GRINS::SingleVariable::~SingleVariable () inline
Definition at line 53 of file single_variable.h.
 {}
GRINS::SingleVariable::SingleVariable () private
Member Function Documentation
VariableIndex GRINS::SingleVariable::var () const inline
Definition at line 55 of file single_variable.h.
References GRINS::FEVariablesBase::_vars.
Referenced by GRINS::AveragedTurbineBase< Viscosity >::fan_speed_var(), GRINS::ConvectionDiffusion::init_context(), GRINS::TurbulenceFEVariables::nu(), GRINS::PressureFEVariable::p(), GRINS::ThermoPressureVariable::p0(), GRINS::ScalarODE::scalar_ode_var(), GRINS::ConvectionDiffusion::set_time_evolving_vars(), and GRINS::PrimitiveTempFEVariables::T().
     { libmesh_assert_equal_to( _vars.size(), 1 );
       return this->_vars[0]; }
The documentation for this class was generated from the following file:
src/variables/include/grins/single_variable.h