GRINS-0.7.0: GRINS::SpalartAllmaras< Viscosity > Class Template Reference
GRINS::SpalartAllmaras< Viscosity > Class Template Reference
Physics class for Incompressible Navier-Stokes.
#include <spalart_allmaras.h>
Public Member Functions
SpalartAllmaras (const std::string &physics_name, const GetPot &input)
~SpalartAllmaras ()
virtual void init_variables (libMesh::FEMSystem *system)
Initialize variables for this physics.
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Sets velocity variables to be time-evolving.
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &)
Time dependent part(s) of physics for element interiors.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Public Member Functions inherited from GRINS::TurbulenceModelsBase< Viscosity >
TurbulenceModelsBase (const std::string &physics_name, const GetPot &input)
~TurbulenceModelsBase ()
Public Member Functions inherited from GRINS::Physics
Physics (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~Physics ()
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void damping_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Damping matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_damping_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
ICHandlingBase * get_ic_handler ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
Public Attributes
libMesh::UniquePtr< DistanceFunction > distance_function
libMesh::UniquePtr< libMesh::SerialMesh > boundary_mesh
Protected Attributes
VelocityFEVariables _flow_vars
PressureFEVariable _press_var
TurbulenceFEVariables _turbulence_vars
SpalartAllmarasHelper _spalart_allmaras_helper
SpalartAllmarasParameters _sa_params
Object handling the plethora of parameters.
std::set< libMesh::boundary_id_type > _wall_ids
unsigned int _no_of_walls
bool _infinite_distance
Protected Attributes inherited from GRINS::TurbulenceModelsBase< Viscosity >
unsigned int _dim
Physical dimension of problem.
libMesh::Number _rho
Material parameters, read from input.
Viscosity _mu
Viscosity object.
Protected Attributes inherited from GRINS::Physics
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
Private Member Functions
SpalartAllmaras ()
void register_variables ()
Additional Inherited Members
Static Public Member Functions inherited from GRINS::Physics
static void set_is_axisymmetric (bool is_axisymmetric)
Set whether we should treat the problem as axisymmetric.
static bool is_axisymmetric ()
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Member Functions inherited from GRINS::Physics
libMesh::UniquePtr< libMesh::FEGenericBase< libMesh::Real > > build_new_fe (const libMesh::Elem *elem, const libMesh::FEGenericBase< libMesh::Real > *fe, const libMesh::Point p)
void parse_enabled_subdomains (const GetPot &input, const std::string &physics_name)
Static Protected Attributes inherited from GRINS::Physics
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
static bool _is_axisymmetric = false
Caches whether we are solving an axisymmetric problem or not.
Detailed Description
template<class Viscosity>
class GRINS::SpalartAllmaras< Viscosity >
Physics class for Incompressible Navier-Stokes.
This physics class implements the classical Incompressible Navier-Stokes equations. This is a templated class, the class Viscosity can be instantiated as a specific type (right now:ConstantViscosity or SpatiallyVaryingViscosity) to allow the user to specify a constant or spatially varying viscosity in the input file
Definition at line 58 of file spalart_allmaras.h.
Constructor & Destructor Documentation
template<class Mu > GRINS::SpalartAllmaras< Mu >::SpalartAllmaras (const std::string & physics_name, const GetPot & input)
Definition at line 48 of file spalart_allmaras.C.
References GRINS::Physics::_ic_handler, GRINS::SpalartAllmaras< Viscosity >::_no_of_walls, GRINS::SpalartAllmaras< Viscosity >::_wall_ids, GRINS::SpalartAllmaras< Viscosity >::register_variables(), and GRINS::PhysicsNaming::spalart_allmaras().
     : TurbulenceModelsBase<Mu>(physics_name, input), // Define class variables
     _flow_vars(input,PhysicsNaming::incompressible_navier_stokes()),
     _press_var(input,PhysicsNaming::incompressible_navier_stokes(), true /*is_constraint_var*/),
     _turbulence_vars(input, PhysicsNaming::spalart_allmaras()),
     _spalart_allmaras_helper(input),
     _sa_params(input),
     _no_of_walls(input("Physics/"+PhysicsNaming::spalart_allmaras()+"/no_of_walls", 0)),
     _infinite_distance(input("Physics/"+PhysicsNaming::spalart_allmaras()+"/infinite_distance", false))
   {
     // Loop over the _no_of_walls and fill the wall_ids set
     for(unsigned int i = 0; i != _no_of_walls; i++)
       {
         _wall_ids.insert(input("Physics/"+PhysicsNaming::spalart_allmaras()+"/wall_ids", 0, i ));
       }
     std::cout<<"No of walls: "<<_no_of_walls<<std::endl;
     for( std::set<libMesh::boundary_id_type>::iterator b_id = _wall_ids.begin(); b_id != _wall_ids.end(); ++b_id )
       {
         std::cout<<"Boundary Id: "<<*b_id<<std::endl;
       }
     this->register_variables();
     this->_ic_handler = new GenericICHandler( physics_name, input );
   }
template<class Mu > GRINS::SpalartAllmaras< Mu >::~SpalartAllmaras ()
Definition at line 77 of file spalart_allmaras.C.
   {
     return;
   }
template<class Viscosity > GRINS::SpalartAllmaras< Viscosity >::SpalartAllmaras () private
Member Function Documentation
template<class Mu > void GRINS::SpalartAllmaras< Mu >::element_time_derivative (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Time dependent part(s) of physics for element interiors.
Reimplemented from GRINS::Physics.
Reimplemented in GRINS::SpalartAllmarasSPGSMStabilization< Viscosity >.
Definition at line 156 of file spalart_allmaras.C.
   {
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->BeginTimer("SpalartAllmaras::element_time_derivative");
 #endif
     // Get a pointer to the current element, we need this for computing
     // the distance to wall for the  quadrature points
     libMesh::Elem &elem_pointer = context.get_elem();
     // We get some references to cell-specific data that
     // will be used to assemble the linear system.
     // Element Jacobian * quadrature weights for interior integration.
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(this->_turbulence_vars.nu())->get_JxW();
     // The viscosity shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& nu_phi =
       context.get_element_fe(this->_turbulence_vars.nu())->get_phi();
     // The viscosity shape function gradients (in global coords.)
     // at interior quadrature points.
     const std::vector<std::vector<libMesh::RealGradient> >& nu_gradphi =
       context.get_element_fe(this->_turbulence_vars.nu())->get_dphi();
     // The number of local degrees of freedom in each variable.
     const unsigned int n_nu_dofs = context.get_dof_indices(this->_turbulence_vars.nu()).size();
     // The subvectors and submatrices we need to fill:
     //
     // K_{\alpha \beta} = R_{\alpha},{\beta} = \partial{ R_{\alpha} } / \partial{ {\beta} } (where R denotes residual)
     // e.g., for \alpha = v and \beta = u we get: K{vu} = R_{v},{u}
     // Note that Kpu, Kpv, Kpw and Fp comes as constraint.
     //libMesh::DenseSubMatrix<libMesh::Number> &Knunu = context.get_elem_jacobian(this->_turbulence_vars.nu(), this->_turbulence_vars.nu()); // R_{nu},{nu}
     libMesh::DenseSubVector<libMesh::Number> &Fnu = context.get_elem_residual(this->_turbulence_vars.nu()); // R_{nu}
     // Now we will build the element Jacobian and residual.
     // Constructing the residual requires the solution and its
     // gradient from the previous timestep.  This must be
     // calculated at each quadrature point by summing the
     // solution degree-of-freedom values by the appropriate
     // weight functions.
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     // Auto pointer to distance fcn evaluated at quad points
     libMesh::UniquePtr< libMesh::DenseVector<libMesh::Real> > distance_qp;
     // Fill the vector of distances to quadrature points
     distance_qp = this->distance_function->interpolate(&elem_pointer, context.get_element_qrule().get_points());
     for (unsigned int qp=0; qp != n_qpoints; qp++)
       {
         // Compute the solution & its gradient at the old Newton iterate.
         libMesh::Number nu;
         nu = context.interior_value(this->_turbulence_vars.nu(), qp);
         libMesh::Gradient grad_nu;
         grad_nu = context.interior_gradient(this->_turbulence_vars.nu(), qp);
         libMesh::Real jac = JxW[qp];
         // The physical viscosity
         libMesh::Real mu_qp = this->_mu(context, qp);
         // The vorticity value
         libMesh::Real vorticity_value_qp = this->_spalart_allmaras_helper.vorticity(context, qp);
         // The flow velocity
         libMesh::Number u,v;
         u = context.interior_value(this->_flow_vars.u(), qp);
         v = context.interior_value(this->_flow_vars.v(), qp);
         libMesh::NumberVectorValue U(u,v);
         if (this->_dim == 3)
           U(2) = context.interior_value(this->_flow_vars.w(), qp);
         //The source term
         libMesh::Real S_tilde = this->_sa_params.source_fn(nu, mu_qp, (*distance_qp)(qp), vorticity_value_qp, _infinite_distance);
         // The ft2 function needed for the negative S-A model
         libMesh::Real chi = nu/mu_qp;
         libMesh::Real f_t2 = this->_sa_params.get_c_t3()*exp(-this->_sa_params.get_c_t4()*chi*chi);
         libMesh::Real source_term = this->_sa_params.get_cb1()*(1 - f_t2)*S_tilde*nu;
         // For a negative turbulent viscosity nu < 0.0 we need to use a different production function
         if(nu < 0.0)
           {
             source_term = this->_sa_params.get_cb1()*(1 - this->_sa_params.get_c_t3())*vorticity_value_qp*nu;
           }
         // The wall destruction term
         libMesh::Real fw = this->_sa_params.destruction_fn(nu, (*distance_qp)(qp), S_tilde, _infinite_distance);
         libMesh::Real nud = 0.0;
         if(_infinite_distance)
         {
           nud = 0.0;
         }
         else
         {
           nud = nu/(*distance_qp)(qp);
         }
         libMesh::Real nud2 = nud*nud;
         libMesh::Real kappa2 = (this->_sa_params.get_kappa())*(this->_sa_params.get_kappa());
         libMesh::Real cw1 = this->_sa_params.get_cb1()/kappa2 + (1.0 + this->_sa_params.get_cb2())/this->_sa_params.get_sigma();
         libMesh::Real destruction_term = (cw1*fw - (this->_sa_params.get_cb1()/kappa2)*f_t2)*nud2;
         // For a negative turbulent viscosity nu < 0.0 we need to use a different production function
         if(nu < 0.0)
           {
             destruction_term = -cw1*nud2;
           }
         libMesh::Real fn1 = 1.0;
         // For a negative turbulent viscosity, fn1 needs to be calculated
         if(nu < 0.0)
           {
             libMesh::Real chi3 = chi*chi*chi;
             fn1 = (this->_sa_params.get_c_n1() + chi3)/(this->_sa_params.get_c_n1() - chi3);
           }
         // First, an i-loop over the viscosity degrees of freedom.
         for (unsigned int i=0; i != n_nu_dofs; i++)
           {
             Fnu(i) += jac *
               ( -this->_rho*(U*grad_nu)*nu_phi[i][qp]  // convection term (assumes incompressibility)
                 +source_term*nu_phi[i][qp] // source term
                 + (1./this->_sa_params.get_sigma())*(-(mu_qp+(fn1*nu))*grad_nu*nu_gradphi[i][qp] + this->_sa_params.get_cb2()*grad_nu*grad_nu*nu_phi[i][qp]) // diffusion term
                 - destruction_term*nu_phi[i][qp]); // destruction term
             // Compute the jacobian if not using numerical jacobians
             if (compute_jacobian)
               {
                 libmesh_not_implemented();
               } // end - if (compute_jacobian)
           } // end of the outer dof (i) loop
       } // end of the quadrature point (qp) loop
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->EndTimer("SpalartAllmaras::element_time_derivative");
 #endif
     return;
   }
template<class Mu > void GRINS::SpalartAllmaras< Mu >::init_context (AssemblyContext & context) virtual
Initialize context for added physics variables.
Reimplemented from GRINS::Physics.
Reimplemented in GRINS::SpalartAllmarasStabilizationBase< Viscosity >.
Definition at line 124 of file spalart_allmaras.C.
Referenced by GRINS::SpalartAllmarasStabilizationBase< Viscosity >::init_context().
   {
     // We should prerequest all the data
     // we will need to build the linear system
     // or evaluate a quantity of interest.
     context.get_element_fe(_turbulence_vars.nu())->get_JxW();
     context.get_element_fe(_turbulence_vars.nu())->get_phi();
     context.get_element_fe(_turbulence_vars.nu())->get_dphi();
     context.get_element_fe(_turbulence_vars.nu())->get_xyz();
     context.get_element_fe(_turbulence_vars.nu())->get_phi();
     context.get_element_fe(_turbulence_vars.nu())->get_xyz();
     context.get_side_fe(_turbulence_vars.nu())->get_JxW();
     context.get_side_fe(_turbulence_vars.nu())->get_phi();
     context.get_side_fe(_turbulence_vars.nu())->get_dphi();
     context.get_side_fe(_turbulence_vars.nu())->get_xyz();
     return;
   }
template<class Mu > void GRINS::SpalartAllmaras< Mu >::init_variables (libMesh::FEMSystem * system) virtual
Initialize variables for this physics.
Reimplemented from GRINS::TurbulenceModelsBase< Viscosity >.
Reimplemented in GRINS::SpalartAllmarasStabilizationBase< Viscosity >, and GRINS::SpalartAllmarasSPGSMStabilization< Viscosity >.
Definition at line 94 of file spalart_allmaras.C.
References GRINS::TurbulenceModelsBase< Viscosity >::init_variables().
Referenced by GRINS::SpalartAllmarasStabilizationBase< Viscosity >::init_variables().
   {
     // Init base class.
     TurbulenceModelsBase<Mu>::init_variables(system);
     this->_turbulence_vars.init(system);
     this->_flow_vars.init(system);
     this->_press_var.init(system);
     // Init the variables belonging to SA helper
     _spalart_allmaras_helper.init_variables(system);
     // Initialize Boundary Mesh
     this->boundary_mesh.reset(new libMesh::SerialMesh(system->get_mesh().comm() , this->_dim));
     // Use the _wall_ids set to build the boundary mesh object
     (system->get_mesh()).boundary_info->sync(_wall_ids, *boundary_mesh);
     //this->distance_function.reset(new DistanceFunction(system->get_equation_systems(), dynamic_cast<libMesh::UnstructuredMesh&>(system->get_mesh()) ));
     this->distance_function.reset(new DistanceFunction(system->get_equation_systems(), *boundary_mesh));
     // For now, we are hacking this. Without this initialize function being called
     // the distance variable will just be zero. For the channel flow, we are just
     // going to analytically compute the wall distance
     //this->distance_function->initialize();
     return;
   }
template<class K > void GRINS::SpalartAllmaras< K >::mass_residual (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
Reimplemented from GRINS::Physics.
Reimplemented in GRINS::SpalartAllmarasSPGSMStabilization< Viscosity >.
Definition at line 308 of file spalart_allmaras.C.
   {
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->BeginTimer("SpalartAllmaras::mass_residual");
 #endif
     // First we get some references to cell-specific data that
     // will be used to assemble the linear system.
     // Element Jacobian * quadrature weights for interior integration.
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(this->_turbulence_vars.nu())->get_JxW();
     // The viscosity shape functions at interior quadrature points.
     const std::vector<std::vector<libMesh::Real> >& nu_phi =
       context.get_element_fe(this->_turbulence_vars.nu())->get_phi();
     // The number of local degrees of freedom in each variable.
     const unsigned int n_nu_dofs = context.get_dof_indices(this->_turbulence_vars.nu()).size();
     // The subvectors and submatrices we need to fill:
     libMesh::DenseSubVector<libMesh::Real> &F = context.get_elem_residual(this->_turbulence_vars.nu());
     //libMesh::DenseSubMatrix<libMesh::Real> &M = context.get_elem_jacobian(this->_turbulence_vars.nu(), this->_turbulence_vars.nu());
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     for (unsigned int qp = 0; qp != n_qpoints; ++qp)
       {
         // For the mass residual, we need to be a little careful.
         // The time integrator is handling the time-discretization
         // for us so we need to supply M(u_fixed)*u' for the residual.
         // u_fixed will be given by the fixed_interior_value function
         // while u' will be given by the interior_rate function.
         libMesh::Real nu_dot;
         context.interior_rate(this->_turbulence_vars.nu(), qp, nu_dot);
         for (unsigned int i = 0; i != n_nu_dofs; ++i)
           {
             F(i) += -JxW[qp]*this->_rho*nu_dot*nu_phi[i][qp];
             if( compute_jacobian )
               {
                 libmesh_not_implemented();
               }// End of check on Jacobian
           } // End of element dof loop
       } // End of the quadrature point loop
 #ifdef GRINS_USE_GRVY_TIMERS
     this->_timer->EndTimer("SpalartAllmaras::mass_residual");
 #endif
     return;
   }
template<class Mu > void GRINS::SpalartAllmaras< Mu >::register_parameter (const std::string & param_name, libMesh::ParameterMultiAccessor< libMesh::Number > & param_pointer) const virtual
Each subclass will register its copy of an independent.
Reimplemented from GRINS::TurbulenceModelsBase< Viscosity >.
Reimplemented in GRINS::SpalartAllmarasSPGSMStabilization< Viscosity >, and GRINS::SpalartAllmarasStabilizationBase< Viscosity >.
Definition at line 369 of file spalart_allmaras.C.
References GRINS::ParameterUser::register_parameter().
Referenced by GRINS::SpalartAllmarasStabilizationBase< Viscosity >::register_parameter().
   {
     ParameterUser::register_parameter(param_name, param_pointer);
     this->_mu.register_parameter(param_name, param_pointer);
     this->_sa_params.register_parameter(param_name, param_pointer);
   }
template<class Mu > void GRINS::SpalartAllmaras< Mu >::register_variables () private
Definition at line 83 of file spalart_allmaras.C.
References GRINS::GRINSPrivate::VariableWarehouse::check_and_register_variable(), GRINS::VariablesParsing::pressure_section(), GRINS::VariablesParsing::turbulence_section(), and GRINS::VariablesParsing::velocity_section().
Referenced by GRINS::SpalartAllmaras< Viscosity >::SpalartAllmaras().
   {
     GRINSPrivate::VariableWarehouse::check_and_register_variable(VariablesParsing::pressure_section(),
                                                                  this->_press_var);
     GRINSPrivate::VariableWarehouse::check_and_register_variable(VariablesParsing::velocity_section(),
                                                                  this->_flow_vars);
     GRINSPrivate::VariableWarehouse::check_and_register_variable(VariablesParsing::turbulence_section(),
                                                                  this->_turbulence_vars);
   }
template<class Mu > void GRINS::SpalartAllmaras< Mu >::set_time_evolving_vars (libMesh::FEMSystem * system) virtual
Sets velocity variables to be time-evolving.
Reimplemented from GRINS::Physics.
Definition at line 146 of file spalart_allmaras.C.
   {
     // Tell the system to march velocity forward in time, but
     // leave p as a constraint only
     system->time_evolving(this->_turbulence_vars.nu());
     return;
   }
Member Data Documentation
template<class Viscosity > VelocityFEVariables GRINS::SpalartAllmaras< Viscosity >::_flow_vars protected
Definition at line 98 of file spalart_allmaras.h.
template<class Viscosity > bool GRINS::SpalartAllmaras< Viscosity >::_infinite_distance protected
Definition at line 116 of file spalart_allmaras.h.
template<class Viscosity > unsigned int GRINS::SpalartAllmaras< Viscosity >::_no_of_walls protected
Definition at line 113 of file spalart_allmaras.h.
Referenced by GRINS::SpalartAllmaras< Viscosity >::SpalartAllmaras().
template<class Viscosity > PressureFEVariable GRINS::SpalartAllmaras< Viscosity >::_press_var protected
Definition at line 99 of file spalart_allmaras.h.
template<class Viscosity > SpalartAllmarasParameters GRINS::SpalartAllmaras< Viscosity >::_sa_params protected
Object handling the plethora of parameters.
Definition at line 107 of file spalart_allmaras.h.
template<class Viscosity > SpalartAllmarasHelper GRINS::SpalartAllmaras< Viscosity >::_spalart_allmaras_helper protected
Definition at line 104 of file spalart_allmaras.h.
template<class Viscosity > TurbulenceFEVariables GRINS::SpalartAllmaras< Viscosity >::_turbulence_vars protected
Definition at line 101 of file spalart_allmaras.h.
template<class Viscosity > std::set<libMesh::boundary_id_type> GRINS::SpalartAllmaras< Viscosity >::_wall_ids protected
Definition at line 110 of file spalart_allmaras.h.
Referenced by GRINS::SpalartAllmaras< Viscosity >::SpalartAllmaras().
template<class Viscosity > libMesh::UniquePtr<libMesh::SerialMesh> GRINS::SpalartAllmaras< Viscosity >::boundary_mesh
Definition at line 86 of file spalart_allmaras.h.
template<class Viscosity > libMesh::UniquePtr<DistanceFunction> GRINS::SpalartAllmaras< Viscosity >::distance_function
Definition at line 83 of file spalart_allmaras.h.
The documentation for this class was generated from the following files:
src/physics/include/grins/spalart_allmaras.h
src/physics/src/spalart_allmaras.C