GRINS-0.8.0: GRINS::ParameterUser Class Reference
GRINS::ParameterUser Class Reference
ParameterUser base class. Utility methods for subclasses.
#include <parameter_user.h>
Public Member Functions
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Static Public Attributes
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Private Attributes
std::map< std::string, libMesh::Number * > _my_parameters
std::map< std::string, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > * > _my_parsed_functions
std::map< std::string, libMesh::ParsedFEMFunction< libMesh::Number > * > _my_parsed_fem_functions
std::string _my_name
Detailed Description
ParameterUser base class. Utility methods for subclasses.
This base class defines utility methods with which a subclass can simultaneously set a parameter from an input file and register that parameter (by input file variable name) for later parameter sensitivity studies.
Definition at line 68 of file parameter_user.h.
Constructor & Destructor Documentation
GRINS::ParameterUser::ParameterUser (const std::string & user_name) inline
Definition at line 73 of file parameter_user.h.
 : _my_name(user_name) {}
virtual GRINS::ParameterUser::~ParameterUser () inline virtual
Definition at line 74 of file parameter_user.h.
 {}
Member Function Documentation
void GRINS::ParameterUser::move_parameter (const libMesh::Number & old_parameter, libMesh::Number & new_parameter) virtual
When cloning an object, we need to update parameter pointers.
Definition at line 113 of file parameter_user.C.
Referenced by GRINS::AverageNusseltNumber::clone(), GRINS::ParsedBoundaryQoI::ParsedBoundaryQoI(), and GRINS::ParsedInteriorQoI::ParsedInteriorQoI().
   {
     std::map<std::string, libMesh::Number*>::iterator it =
       _my_parameters.begin();
     const std::map<std::string, libMesh::Number*>::iterator end =
       _my_parameters.end();
     for (; it != end; ++it)
       if (it->second == &old_parameter)
         {
           it->second = &new_parameter;
           break;
         }
   }
void GRINS::ParameterUser::move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > & old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > & new_func) virtual
When cloning an object, we need to update parameter pointers.
Definition at line 129 of file parameter_user.C.
   {
     std::map
       <std::string,
        libMesh::ParsedFunction<libMesh::Number,libMesh::Gradient> *
        >::iterator it = _my_parsed_functions.begin();
     const std::map
       <std::string,
        libMesh::ParsedFunction<libMesh::Number,libMesh::Gradient> *
        >::iterator end = _my_parsed_functions.end();
     for (; it != end; ++it)
       if (it->second == &old_func)
         {
           it->second = &new_func;
           break;
         }
   }
void GRINS::ParameterUser::move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > & old_func, libMesh::ParsedFEMFunction< libMesh::Number > & new_func) virtual
When cloning an object, we need to update parameter pointers.
Definition at line 149 of file parameter_user.C.
   {
     std::map
       <std::string,
        libMesh::ParsedFEMFunction<libMesh::Number> *
        >::iterator it = _my_parsed_fem_functions.begin();
     const std::map
       <std::string,
        libMesh::ParsedFEMFunction<libMesh::Number> *
        >::iterator end = _my_parsed_fem_functions.end();
     for (; it != end; ++it)
       if (it->second == &old_func)
         {
           it->second = &new_func;
           break;
         }
   }
void GRINS::ParameterUser::register_parameter (const std::string & param_name, libMesh::ParameterMultiAccessor< libMesh::Number > & param_pointer) const virtual
Each subclass will register its copy of an independent.
Reimplemented in GRINS::SpalartAllmarasStabilizationHelper, GRINS::SpalartAllmaras< Viscosity >, GRINS::CatalyticWallBase< Chemistry >, GRINS::AntiochMixture< KineticsThermoCurveFit >, GRINS::AntiochMixture< Antioch::CEACurveFit< libMesh::Real > >, GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::AxisymmetricHeatTransfer< Conductivity >, GRINS::SpalartAllmarasViscosity< Viscosity >, GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >, GRINS::IncompressibleNavierStokesBase< Viscosity >, GRINS::HeatConduction< Conductivity >, GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >, GRINS::HeatTransferBase< Conductivity >, GRINS::TurbulenceModelsBase< Viscosity >, GRINS::SpalartAllmarasSPGSMStabilization< Viscosity >, GRINS::ReactingLowMachNavierStokesBase< Mixture >, and GRINS::SpalartAllmarasStabilizationBase< Viscosity >.
Definition at line 170 of file parameter_user.C.
Referenced by GRINS::ReactingLowMachNavierStokesBase< Mixture >::register_parameter(), GRINS::TurbulenceModelsBase< Viscosity >::register_parameter(), GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::register_parameter(), GRINS::HeatTransferBase< Conductivity >::register_parameter(), GRINS::HeatConduction< Conductivity >::register_parameter(), GRINS::IncompressibleNavierStokesBase< Viscosity >::register_parameter(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::register_parameter(), GRINS::SpalartAllmarasViscosity< Viscosity >::register_parameter(), GRINS::AxisymmetricHeatTransfer< Conductivity >::register_parameter(), GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::register_parameter(), GRINS::AntiochMixture< KineticsThermoCurveFit >::register_parameter(), GRINS::SpalartAllmaras< Viscosity >::register_parameter(), and GRINS::SpalartAllmarasStabilizationHelper::register_parameter().
   {
     std::map<std::string, libMesh::Number*>::const_iterator it =
       _my_parameters.find(param_name);
     // Make sure we don't find duplicate parameters - a Number
     // parameter shouldn't have the same name as a ParsedFunction or
     // ParsedFEMFunction parameter.
 #ifndef NDEBUG
     bool found_parameter = false;
 #endif
     // First search for simple Number parameters
     if (it != _my_parameters.end())
       {
         std::cout << _my_name << " has Number parameter " << param_name
                   << std::endl;
         param_pointer.push_back
           (libMesh::ParameterPointer<libMesh::Number>(it->second));
 #ifndef NDEBUG
         found_parameter = true;
 #else
         return;
 #endif
       }
     // Next search for inline variable parameters in parsed functions
     std::size_t last_slash_i = param_name.rfind('/');
     if (last_slash_i != std::string::npos)
       {
         std::string search_name = param_name.substr(0, last_slash_i);
         std::string var_name = param_name.substr(last_slash_i+1);
         std::map
           <std::string, libMesh::ParsedFunction
            <libMesh::Number,libMesh::Gradient>*>::const_iterator
           pf_it = _my_parsed_functions.find(search_name);
         if (pf_it != _my_parsed_functions.end())
           {
             std::cout << _my_name << " has ParsedFunction for " <<
               search_name << " / " << var_name << std::endl;
             param_pointer.push_back
               (libMesh::ParsedFunctionParameter<libMesh::Number>
                (*pf_it->second, var_name));
 #ifndef NDEBUG
             libmesh_assert(!found_parameter);
             found_parameter = true;
 #else
             return;
 #endif
           }
         std::map
           <std::string, libMesh::ParsedFEMFunction
            <libMesh::Number>*>::const_iterator
           pff_it = _my_parsed_fem_functions.find(search_name);
         if (pff_it != _my_parsed_fem_functions.end())
           {
             std::cout << _my_name << " has ParsedFEMFunction for " <<
               search_name << " / " << var_name << std::endl;
             param_pointer.push_back
               (libMesh::ParsedFEMFunctionParameter<libMesh::Number>
                (*pff_it->second, var_name));
 #ifndef NDEBUG
             libmesh_assert(!found_parameter);
 #endif
           }
       }
   }
void GRINS::ParameterUser::set_parameter (libMesh::Number & param_variable, const GetPot & input, const std::string & param_name, libMesh::Number param_default) virtual
Each subclass can simultaneously read a parameter value from.
Definition at line 50 of file parameter_user.C.
References _my_name, and _my_parameters.
Referenced by GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::BoussinesqBuoyancySPGSMStabilization(), GRINS::ConstantConductivity::ConstantConductivity(), GRINS::ConstantPrandtlConductivity::ConstantPrandtlConductivity(), GRINS::ConstantSourceFunction::ConstantSourceFunction(), GRINS::ConstantSourceTerm::ConstantSourceTerm(), GRINS::ConstantSpecificHeat::ConstantSpecificHeat(), GRINS::ConstantViscosity::ConstantViscosity(), GRINS::ConvectionDiffusion::ConvectionDiffusion(), GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure(), GRINS::HookesLaw::HookesLaw(), GRINS::HookesLaw1D::HookesLaw1D(), GRINS::ParsedBoundaryQoI::init(), GRINS::MooneyRivlin::MooneyRivlin(), GRINS::AverageNusseltNumber::parse_thermal_conductivity(), GRINS::ParsedConductivity::ParsedConductivity(), GRINS::ParsedSourceTerm::ParsedSourceTerm(), GRINS::ParsedViscosity::ParsedViscosity(), GRINS::ReactingLowMachNavierStokesAbstract::ReactingLowMachNavierStokesAbstract(), GRINS::MaterialsParsing::read_density(), GRINS::HookesLaw1D::read_input_options(), GRINS::HookesLaw::read_input_options(), GRINS::AxisymmetricBoussinesqBuoyancy::read_input_options(), GRINS::BoussinesqBuoyancyBase::read_property(), GRINS::MaterialsParsing::read_property(), GRINS::MaterialsParsing::read_specific_heat(), GRINS::PowerLawCatalycity::set_parameters(), GRINS::ArrheniusCatalycity::set_parameters(), GRINS::ConstantCatalycity::set_parameters(), GRINS::ScalarODE::set_time_evolving_vars(), GRINS::SpalartAllmarasParameters::SpalartAllmarasParameters(), GRINS::SpalartAllmarasStabilizationHelper::SpalartAllmarasStabilizationHelper(), and GRINS::TurbulenceModelsBase< Viscosity >::TurbulenceModelsBase().
   {
     param_variable = input(param_name, param_default);
     libmesh_assert_msg(!_my_parameters.count(param_name),
                        "ERROR: " << _my_name << " double-registered parameter " <<
                        param_name);
     _my_parameters[param_name] = &param_variable;
   }
void GRINS::ParameterUser::set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > & func, const GetPot & input, const std::string & func_param_name, const std::string & param_default) virtual
Each subclass can simultaneously read a parsed function from.
Definition at line 65 of file parameter_user.C.
   {
     if((param_default == "DIE!") &&
        (!input.have_variable(func_param_name)))
       {
         libMesh::err << "Error: Must specify parsed function for " <<
           _my_name << std::endl
                      << "       Please specify " << func_param_name << std::endl;
         libmesh_error();
       }
     func.reparse(input(func_param_name, param_default));
     libmesh_assert_msg(!_my_parsed_functions.count(func_param_name),
                        "ERROR: " << _my_name << " double-registered parameter " <<
                        func_param_name);
     _my_parsed_functions[func_param_name] = &func;
   }
void GRINS::ParameterUser::set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > & func, const GetPot & input, const std::string & func_param_name, const std::string & param_default) virtual
Each subclass can simultaneously read a parsed function from.
Definition at line 89 of file parameter_user.C.
   {
     if((param_default == "DIE!") &&
        (!input.have_variable(func_param_name)))
       {
         libMesh::err << "Error: Must specify parsed (fem) function for " <<
           _my_name << std::endl
                      << "       Please specify " << func_param_name << std::endl;
         libmesh_error();
       }
     func.reparse(input(func_param_name, param_default));
     libmesh_assert_msg(!_my_parsed_fem_functions.count(func_param_name),
                        "ERROR: " << _my_name << " double-registered parameter " <<
                        func_param_name);
     _my_parsed_fem_functions[func_param_name] = &func;
   }
Member Data Documentation
std::string GRINS::ParameterUser::_my_name private
Definition at line 152 of file parameter_user.h.
Referenced by set_parameter().
std::map<std::string, libMesh::Number*> GRINS::ParameterUser::_my_parameters private
Definition at line 140 of file parameter_user.h.
Referenced by set_parameter().
std::map<std::string, libMesh::ParsedFEMFunction<libMesh::Number>*> GRINS::ParameterUser::_my_parsed_fem_functions private
Definition at line 148 of file parameter_user.h.
std::map<std::string, libMesh::ParsedFunction<libMesh::Number,libMesh::Gradient>*> GRINS::ParameterUser::_my_parsed_functions private
Definition at line 144 of file parameter_user.h.
std::string GRINS::ParameterUser::zero_vector_function = std::string("{0}") static
A parseable function string with LIBMESH_DIM components, all 0.
Definition at line 125 of file parameter_user.h.
The documentation for this class was generated from the following files:
src/solver/include/grins/parameter_user.h
src/solver/src/parameter_user.C