GRINS-0.8.0: GRINS::BCFactoryAbstract< Base > Class Template Reference
GRINS::BCFactoryAbstract< Base > Class Template Reference
#include <bc_factory_abstract.h>
Public Member Functions
BCFactoryAbstract (const std::string &bc_type_name)
~BCFactoryAbstract ()
Public Member Functions inherited from GRINS::FactoryWithGetPot< Base >
FactoryWithGetPot (const std::string &name)
~FactoryWithGetPot ()
Public Member Functions inherited from GRINS::FactoryAbstract< Base >
virtual ~FactoryAbstract ()
virtual libMesh::UniquePtr< Base > create ()=0
Subclasses implement the actual construction of the Base object in create().
Static Public Member Functions
static void set_system (MultiphysicsSystem &system)
static void set_bc_ids (const std::set< BoundaryID > &bc_ids)
Boundary id for the current boundary condition section.
static void set_fe_var (const FEVariablesBase &fe_var)
Active variable for the current boundary condition.
static void set_section (const std::string &section)
Sets the current section of the input file.
static bool have_bc_type (const std::string &bc_type)
Static Public Member Functions inherited from GRINS::FactoryWithGetPot< Base >
static void set_getpot (const GetPot &input)
Static Public Member Functions inherited from GRINS::FactoryAbstract< Base >
static libMesh::UniquePtr< Base > build (const std::string &name)
Use this method to build objects of type Base.
Protected Member Functions
void check_for_multiple_expressions (const GetPot &input, const std::string &section, const std::string &var_name) const
Ensure that there is only one expression for the [Section/var_name] variable.
void build_var_indices (const MultiphysicsSystem &system, const std::vector< std::string > &var_names, std::vector< VariableIndex > &var_indices) const
virtual void check_state () const
Helper function to reduce code duplication.
virtual void reset_state ()
Helper function to redue code duplication.
template<>
MultiphysicsSystem * _system
template<>
const std::set< BoundaryID > * _bc_ids
template<>
const FEVariablesBase * _fe_var
template<>
std::string _section
template<>
MultiphysicsSystem * _system
template<>
const std::set< BoundaryID > * _bc_ids
template<>
const FEVariablesBase * _fe_var
template<>
std::string _section
template<>
MultiphysicsSystem * _system
template<>
const std::set< BoundaryID > * _bc_ids
template<>
const FEVariablesBase * _fe_var
template<>
std::string _section
Protected Member Functions inherited from GRINS::FactoryWithGetPot< Base >
template<>
const GetPot * _input
template<>
const GetPot * _input
template<>
const GetPot * _input
template<>
const GetPot * _input
template<>
const GetPot * _input
template<>
const GetPot * _input
template<>
const GetPot * _input
template<>
const GetPot * _input
template<>
const GetPot * _input
template<>
const GetPot * _input
template<>
const GetPot * _input
template<>
const GetPot * _input
template<>
const GetPot * _input
Protected Member Functions inherited from GRINS::FactoryAbstract< Base >
FactoryAbstract (const std::string &name)
Constructor is protected. Use the build() method to construct Base objects.
template<>
std::map< std::string, FactoryAbstract< CatalycityBase > * > & factory_map ()
template<>
std::map< std::string, FactoryAbstract< libMesh::DirichletBoundary > * > & factory_map ()
template<>
std::map< std::string, FactoryAbstract< NeumannBCContainer > * > & factory_map ()
template<>
std::map< std::string, FactoryAbstract< Physics > * > & factory_map ()
template<>
std::map< std::string, FactoryAbstract< Solver > * > & factory_map ()
template<>
std::map< std::string, FactoryAbstract< libMesh::ErrorEstimator > * > & factory_map ()
template<>
std::map< std::string, FactoryAbstract< FEVariablesBase > * > & factory_map ()
Static Protected Attributes
static MultiphysicsSystem * _system
We store only a raw pointer here because we can't make a copy.
static const std::set< BoundaryID > * _bc_ids
BoundaryID for constructing a particular boundary condition.
static const FEVariablesBase * _fe_var
The FEVariablesBase class associated with the boundary condition being built.
static std::string _section
Static Protected Attributes inherited from GRINS::FactoryWithGetPot< Base >
static const GetPot * _input
We store only a raw pointer here because we can't make a copy.
Additional Inherited Members
Static Protected Member Functions inherited from GRINS::FactoryAbstract< Base >
static FactoryAbstract< Base > & get_factory (const std::string &name)
Helper method that looks up the factory and returns it if present, or error if it's not.
template<typename DerivedType >
static DerivedType & get_factory_subclass (const std::string &name)
Like get_factory, but will downcast to DerivedType.
static std::map< std::string, FactoryAbstract< Base > * > & factory_map ()
Detailed Description
template<typename Base>
class GRINS::BCFactoryAbstract< Base >
Definition at line 44 of file bc_factory_abstract.h.
Constructor & Destructor Documentation
template<typename Base> GRINS::BCFactoryAbstract< Base >::BCFactoryAbstract (const std::string & bc_type_name) inline
Definition at line 47 of file bc_factory_abstract.h.
       : FactoryWithGetPot<Base>(bc_type_name)
     {}
template<typename Base> GRINS::BCFactoryAbstract< Base >::~BCFactoryAbstract () inline
Definition at line 51 of file bc_factory_abstract.h.
 {};
Member Function Documentation
template<> const std::set< BoundaryID > * GRINS::BCFactoryAbstract< NeumannBCContainer >::_bc_ids () protected
Definition at line 38 of file neumann_bc_factory_abstract.h.
Referenced by GRINS::BCFactoryAbstract< NeumannBCContainer >::set_bc_ids().
template<> const std::set< BoundaryID > * GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >::_bc_ids () protected
Definition at line 47 of file dirichlet_bc_factory_abstract.C.
template<> const std::set< BoundaryID > * GRINS::BCFactoryAbstract< NeumannBCContainer >::_bc_ids () protected
Definition at line 91 of file neumann_bc_factory_abstract.C.
template<> const FEVariablesBase * GRINS::BCFactoryAbstract< NeumannBCContainer >::_fe_var () protected
Definition at line 39 of file neumann_bc_factory_abstract.h.
Referenced by GRINS::BCFactoryAbstract< NeumannBCContainer >::set_fe_var().
template<> const FEVariablesBase * GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >::_fe_var () protected
Definition at line 50 of file dirichlet_bc_factory_abstract.C.
template<> const FEVariablesBase * GRINS::BCFactoryAbstract< NeumannBCContainer >::_fe_var () protected
Definition at line 94 of file neumann_bc_factory_abstract.C.
template<> std::string GRINS::BCFactoryAbstract< NeumannBCContainer >::_section () protected
Definition at line 40 of file neumann_bc_factory_abstract.h.
Referenced by GRINS::BCFactoryAbstract< NeumannBCContainer >::set_section().
template<> std::string GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >::_section () protected
Definition at line 53 of file dirichlet_bc_factory_abstract.C.
template<> std::string GRINS::BCFactoryAbstract< NeumannBCContainer >::_section () protected
Definition at line 97 of file neumann_bc_factory_abstract.C.
template<> MultiphysicsSystem * GRINS::BCFactoryAbstract< NeumannBCContainer >::_system () protected
Definition at line 37 of file neumann_bc_factory_abstract.h.
Referenced by GRINS::BCFactoryAbstract< NeumannBCContainer >::set_system().
template<> MultiphysicsSystem * GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >::_system () protected
Definition at line 44 of file dirichlet_bc_factory_abstract.C.
template<> MultiphysicsSystem * GRINS::BCFactoryAbstract< NeumannBCContainer >::_system () protected
Definition at line 88 of file neumann_bc_factory_abstract.C.
template<typename Base > void GRINS::BCFactoryAbstract< Base >::build_var_indices (const MultiphysicsSystem & system, const std::vector< std::string > & var_names, std::vector< VariableIndex > & var_indices) const inline protected
Definition at line 125 of file bc_factory_abstract.h.
   {
     var_indices.resize(var_names.size(),libMesh::invalid_uint);
     for( unsigned int i = 0; i < var_names.size(); i++ )
       var_indices[i] = system.variable_number( var_names[i] );
   }
template<typename Base > void GRINS::BCFactoryAbstract< Base >::check_for_multiple_expressions (const GetPot & input, const std::string & section, const std::string & var_name) const inline protected
Ensure that there is only one expression for the [Section/var_name] variable.
When parsing expressions to give to Parsed(FEM)Function, this function checks that there's only one expression for the given [Section/var_name] in the input file. This also helps protect against white space in the expression, which we don't currently support.
Definition at line 114 of file bc_factory_abstract.h.
   {
     std::string input_var = section+"/"+var_name;
     if( input.vector_variable_size(input_var) > 1 )
       libmesh_error_msg("ERROR: expression size in input ["+input_var+"] is greater than 1!");
   }
template<typename Base > void GRINS::BCFactoryAbstract< Base >::check_state () const inline protected virtual
Helper function to reduce code duplication.
Reimplemented in GRINS::DirichletBCFactoryFunctionOldStyleBase< FunctionType >, GRINS::DirichletBCFactoryFunctionOldStyleBase< libMesh::FEMFunctionBase< libMesh::Number > >, GRINS::DirichletBCFactoryFunctionOldStyleBase< libMesh::FunctionBase< libMesh::Number > >, and GRINS::NeumannBCOldStyleFactoryAbstract.
Definition at line 137 of file bc_factory_abstract.h.
   {
     if( !this->_input )
       libmesh_error_msg("ERROR: must call set_getpot() before building boundary condition!");
     if( !_system )
       libmesh_error_msg("ERROR: must call set_system() before building boundary condition!");
     if( !_bc_ids )
       libmesh_error_msg("ERROR: must call set_bc_ids() before building boundary condition!");
     if( !_fe_var )
       libmesh_error_msg("ERROR: must call set_fe_var() before building boundary condition!");
     if( _section == std::string("DIE!") )
       libmesh_error_msg("ERROR: must call set_section() before building boundary condition!");
   }
template<typename Base > bool GRINS::BCFactoryAbstract< Base >::have_bc_type (const std::string & bc_type) inline static
Definition at line 166 of file bc_factory_abstract.h.
References GRINS::FactoryAbstract< Base >::factory_map().
   {
     const std::map<std::string, FactoryAbstract<Base>*>& map =
       FactoryAbstract<Base>::factory_map();
     bool have_bc = false;
     if( map.find(bc_type) != map.end() )
       have_bc = true;
     return have_bc;
   }
template<typename Base > void GRINS::BCFactoryAbstract< Base >::reset_state () inline protected virtual
Helper function to redue code duplication.
Reimplemented in GRINS::DirichletBCFactoryFunctionOldStyleBase< FunctionType >, GRINS::DirichletBCFactoryFunctionOldStyleBase< libMesh::FEMFunctionBase< libMesh::Number > >, GRINS::DirichletBCFactoryFunctionOldStyleBase< libMesh::FunctionBase< libMesh::Number > >, and GRINS::NeumannBCOldStyleFactoryAbstract.
Definition at line 157 of file bc_factory_abstract.h.
   {
     _bc_ids = NULL;
     _fe_var = NULL;
     _section = std::string("DIE!");
   }
template<typename Base> static void GRINS::BCFactoryAbstract< Base >::set_bc_ids (const std::set< BoundaryID > & bc_ids) inline static
Boundary id for the current boundary condition section.
Definition at line 57 of file bc_factory_abstract.h.
     { _bc_ids = &bc_ids; }
template<typename Base> static void GRINS::BCFactoryAbstract< Base >::set_fe_var (const FEVariablesBase & fe_var) inline static
Active variable for the current boundary condition.
Definition at line 61 of file bc_factory_abstract.h.
     { _fe_var = &fe_var; }
template<typename Base> static void GRINS::BCFactoryAbstract< Base >::set_section (const std::string & section) inline static
Sets the current section of the input file.
The section here corresponds to the section in the GetPot input file, e.g. if we're wanting to parse functions from [Variables/SideWall/Velocity/u], then section will be "Variables/SideWall/Velocity".
Definition at line 69 of file bc_factory_abstract.h.
     { _section = section; }
template<typename Base> static void GRINS::BCFactoryAbstract< Base >::set_system (MultiphysicsSystem & system) inline static
Definition at line 53 of file bc_factory_abstract.h.
     { _system = &system; }
Member Data Documentation
template<typename Base> const std::set<BoundaryID>* GRINS::BCFactoryAbstract< Base >::_bc_ids static protected
BoundaryID for constructing a particular boundary condition.
Definition at line 100 of file bc_factory_abstract.h.
template<typename Base> const FEVariablesBase* GRINS::BCFactoryAbstract< Base >::_fe_var static protected
The FEVariablesBase class associated with the boundary condition being built.
We only build one boundary condition at a time, so this pointer will change with each boundary condition construction. We store a raw pointer here because we don't own this. Do not delete!
Definition at line 106 of file bc_factory_abstract.h.
template<typename Base> std::string GRINS::BCFactoryAbstract< Base >::_section static protected
Definition at line 108 of file bc_factory_abstract.h.
template<typename Base> MultiphysicsSystem* GRINS::BCFactoryAbstract< Base >::_system static protected
We store only a raw pointer here because we can't make a copy.
Otherwise, bad things will happen. We are not taking ownership of this, so we need to not delete this.
Definition at line 97 of file bc_factory_abstract.h.
The documentation for this class was generated from the following file:
src/boundary_conditions/include/grins/bc_factory_abstract.h