GRINS-0.8.0: GRINSTesting::AntiochAirNASA9ThermoTest Class Reference
GRINSTesting::AntiochAirNASA9ThermoTest Class Reference
Public Member Functions
CPPUNIT_TEST_SUITE (AntiochAirNASA9ThermoTest)
CPPUNIT_TEST (test_cp)
CPPUNIT_TEST (test_hs)
CPPUNIT_TEST_SUITE_END ()
void setUp ()
void test_cp ()
void test_hs ()
Public Member Functions inherited from GRINSTesting::AntiochTestBase
void init_antioch (const std::string &input_file, const std::string &material_name)
Public Member Functions inherited from GRINSTesting::AirTestBase
void init_air_test (unsigned int &N2_idx, unsigned int &O2_idx, unsigned int &N_idx, unsigned int &O_idx, unsigned int &NO_idx, std::vector< unsigned int > &active_species)
Public Member Functions inherited from GRINSTesting::NASA9ThermoTestBase
NASA9ThermoTestBase ()
virtual libMesh::Real cp_exact (unsigned int species_idx, libMesh::Real T)
virtual libMesh::Real h_exact (unsigned int species_idx, libMesh::Real T)
virtual libMesh::Real s_R_exact (unsigned int species_idx, libMesh::Real T)
virtual libMesh::Real h_RT_exact (unsigned int species_idx, libMesh::Real T)
Public Member Functions inherited from GRINSTesting::NASAThermoTestBase
template<typename ThermoMixture , typename ThermoEvaluator >
void test_cp_common (ThermoMixture &mixture, const std::vector< libMesh::Real > &Y, libMesh::Real rel_tol)
template<typename ThermoMixture , typename ThermoEvaluator >
void test_h_common (ThermoMixture &mixture, libMesh::Real rel_tol)
Public Member Functions inherited from GRINSTesting::SpeciesTestBase
SpeciesTestBase ()
libMesh::Real molar_mass (unsigned int idx)
libMesh::Real R_species (unsigned int idx)
Additional Inherited Members
Protected Member Functions inherited from GRINSTesting::NASAThermoTestBase
const std::vector< libMesh::Real > & nasa_coeffs (unsigned int idx)
Protected Attributes inherited from GRINSTesting::AntiochTestBase
libMesh::UniquePtr< GRINS::AntiochMixture< Antioch::CEACurveFit< libMesh::Real > > > _antioch_mixture
Protected Attributes inherited from GRINSTesting::NASAThermoTestBase
std::vector< libMesh::Real > _N2_200_1000_coeffs
std::vector< libMesh::Real > _O2_200_1000_coeffs
std::vector< libMesh::Real > _O_200_1000_coeffs
std::vector< libMesh::Real > _NO_200_1000_coeffs
std::vector< libMesh::Real > _N_200_1000_coeffs
Protected Attributes inherited from GRINSTesting::SpeciesTestBase
unsigned int _N2_idx
unsigned int _O2_idx
unsigned int _O_idx
unsigned int _N_idx
unsigned int _NO_idx
std::vector< unsigned int > _active_species
Detailed Description
Definition at line 185 of file air_5sp.C.
Member Function Documentation
GRINSTesting::AntiochAirNASA9ThermoTest::CPPUNIT_TEST (test_cp)
GRINSTesting::AntiochAirNASA9ThermoTest::CPPUNIT_TEST (test_hs)
GRINSTesting::AntiochAirNASA9ThermoTest::CPPUNIT_TEST_SUITE (AntiochAirNASA9ThermoTest)
GRINSTesting::AntiochAirNASA9ThermoTest::CPPUNIT_TEST_SUITE_END ()
void GRINSTesting::AntiochAirNASA9ThermoTest::setUp () inline
Definition at line 200 of file air_5sp.C.
References GRINSTesting::SpeciesTestBase::_active_species, GRINSTesting::SpeciesTestBase::_N2_idx, GRINSTesting::SpeciesTestBase::_N_idx, GRINSTesting::SpeciesTestBase::_NO_idx, GRINSTesting::SpeciesTestBase::_O2_idx, GRINSTesting::SpeciesTestBase::_O_idx, GRINSTesting::AirTestBase::init_air_test(), and GRINSTesting::AntiochTestBase::init_antioch().
     {
       std::string input_file = std::string(GRINS_TEST_SRCDIR)+"/input_files/antioch.in";
       this->init_antioch(input_file, "TestMaterial");
       this->init_air_test( _N2_idx, _O2_idx, _N_idx, _O_idx, _NO_idx,
                            _active_species );
       //this->check_indices(*_antioch_mixture);
     }
void GRINSTesting::AntiochAirNASA9ThermoTest::test_cp () inline
Definition at line 211 of file air_5sp.C.
References GRINSTesting::AntiochTestBase::_antioch_mixture, GRINSTesting::SpeciesTestBase::_N2_idx, GRINSTesting::SpeciesTestBase::_N_idx, GRINSTesting::SpeciesTestBase::_NO_idx, GRINSTesting::SpeciesTestBase::_O2_idx, GRINSTesting::SpeciesTestBase::_O_idx, and GRINSTesting::TestingUtils::epsilon().
     {
       std::vector<libMesh::Real> Y(5);
       Y[_N2_idx] = 0.15;
       Y[_O2_idx] = 0.35;
       Y[_NO_idx] = 0.25;
       Y[_O_idx] = 0.2;
       Y[_N_idx] = 0.05;
       this->test_cp_common<GRINS::AntiochMixture<Antioch::CEACurveFit<libMesh::Real> >,GRINS::AntiochEvaluator<Antioch::CEACurveFit<libMesh::Real>,Antioch::IdealGasMicroThermo<Antioch::NASAEvaluator<libMesh::Real,Antioch::CEACurveFit<libMesh::Real> >, libMesh::Real> > >
         ( *_antioch_mixture, Y, TestingUtils::epsilon()*100 );
     }
void GRINSTesting::AntiochAirNASA9ThermoTest::test_hs () inline
Definition at line 224 of file air_5sp.C.
References GRINSTesting::AntiochTestBase::_antioch_mixture, and GRINSTesting::TestingUtils::epsilon().
     {
       this->test_h_common<GRINS::AntiochMixture<Antioch::CEACurveFit<libMesh::Real> >,GRINS::AntiochEvaluator<Antioch::CEACurveFit<libMesh::Real>,Antioch::IdealGasMicroThermo<Antioch::NASAEvaluator<libMesh::Real,Antioch::CEACurveFit<libMesh::Real> >, libMesh::Real> > >
         ( *_antioch_mixture, TestingUtils::epsilon()*100 );
     }
The documentation for this class was generated from the following file:
test/interface/air_5sp.C