GRINS-0.8.0: GRINS::ReactingLowMachNavierStokesAbstract Class Reference
GRINS::ReactingLowMachNavierStokesAbstract Class Reference
#include <reacting_low_mach_navier_stokes_abstract.h>
Public Member Functions
ReactingLowMachNavierStokesAbstract (const PhysicsName &physics_name, const GetPot &input)
virtual ~ReactingLowMachNavierStokesAbstract ()
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Sets velocity variables to be time-evolving.
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
unsigned int n_species () const
libMesh::Real T (const libMesh::Point &p, const AssemblyContext &c) const
void mass_fractions (const libMesh::Point &p, const AssemblyContext &c, std::vector< libMesh::Real > &mass_fracs) const
libMesh::Real rho (libMesh::Real T, libMesh::Real p0, libMesh::Real R_mix) const
libMesh::Real get_p0_steady (const AssemblyContext &c, unsigned int qp) const
libMesh::Real get_p0_steady_side (const AssemblyContext &c, unsigned int qp) const
libMesh::Real get_p0_steady (const AssemblyContext &c, const libMesh::Point &p) const
libMesh::Real get_p0_transient (const AssemblyContext &c, unsigned int qp) const
Public Member Functions inherited from GRINS::Physics
Physics (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~Physics ()
virtual void init_variables (libMesh::FEMSystem *)
Initialize variables for this physics.
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void preassembly (MultiphysicsSystem &)
Perform any necessary setup before element assembly begins.
virtual void reinit (MultiphysicsSystem &)
Any reinitialization that needs to be done.
virtual void element_time_derivative (bool, AssemblyContext &)
Time dependent part(s) of physics for element interiors.
virtual void side_time_derivative (bool, AssemblyContext &)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool, AssemblyContext &)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool, AssemblyContext &)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool, AssemblyContext &)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool, AssemblyContext &)
Constraint part(s) of physics for scalar variables.
virtual void damping_residual (bool, AssemblyContext &)
Damping matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void mass_residual (bool, AssemblyContext &)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool, AssemblyContext &)
Mass matrix part(s) for scalar variables.
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
virtual void compute_element_time_derivative_cache (AssemblyContext &)
virtual void compute_side_time_derivative_cache (AssemblyContext &)
virtual void compute_nonlocal_time_derivative_cache (AssemblyContext &)
virtual void compute_element_constraint_cache (AssemblyContext &)
virtual void compute_side_constraint_cache (AssemblyContext &)
virtual void compute_nonlocal_constraint_cache (AssemblyContext &)
virtual void compute_damping_residual_cache (AssemblyContext &)
virtual void compute_mass_residual_cache (AssemblyContext &)
virtual void compute_nonlocal_mass_residual_cache (AssemblyContext &)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
ICHandlingBase * get_ic_handler ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Attributes
libMesh::Number _p0
VelocityVariable & _flow_vars
PressureFEVariable & _press_var
PrimitiveTempFEVariables & _temp_vars
SpeciesMassFractionsVariable & _species_vars
ThermoPressureVariable * _p0_var
unsigned int _n_species
Number of species.
libMesh::Point _g
Gravity vector.
bool _enable_thermo_press_calc
Flag to enable thermodynamic pressure calculation.
bool _fixed_density
libMesh::Real _fixed_rho_value
Protected Attributes inherited from GRINS::Physics
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
Private Member Functions
ReactingLowMachNavierStokesAbstract ()
void read_input_options (const GetPot &input)
Read options from GetPot input file.
Additional Inherited Members
Static Public Member Functions inherited from GRINS::Physics
static void set_is_axisymmetric (bool is_axisymmetric)
Set whether we should treat the problem as axisymmetric.
static bool is_axisymmetric ()
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Member Functions inherited from GRINS::Physics
libMesh::UniquePtr< libMesh::FEGenericBase< libMesh::Real > > build_new_fe (const libMesh::Elem *elem, const libMesh::FEGenericBase< libMesh::Real > *fe, const libMesh::Point p)
void parse_enabled_subdomains (const GetPot &input, const std::string &physics_name)
void check_var_subdomain_consistency (const FEVariablesBase &var) const
Check that var is enabled on at least the subdomains this Physics is.
Static Protected Attributes inherited from GRINS::Physics
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
static bool _is_axisymmetric = false
Caches whether we are solving an axisymmetric problem or not.
Detailed Description
Definition at line 42 of file reacting_low_mach_navier_stokes_abstract.h.
Constructor & Destructor Documentation
GRINS::ReactingLowMachNavierStokesAbstract::ReactingLowMachNavierStokesAbstract (const PhysicsName & physics_name, const GetPot & input)
Definition at line 49 of file reacting_low_mach_navier_stokes_abstract.C.
References _enable_thermo_press_calc, _fixed_rho_value, _flow_vars, _p0_var, _press_var, _species_vars, _temp_vars, GRINS::Physics::check_var_subdomain_consistency(), GRINS::VariablesParsing::PHYSICS, GRINS::PhysicsNaming::reacting_low_mach_navier_stokes(), read_input_options(), GRINS::FEVariablesBase::set_is_constraint_var(), GRINS::ParameterUser::set_parameter(), and GRINS::VariablesParsing::thermo_press_variable_name().
     : Physics(physics_name, input),
       _flow_vars(GRINSPrivate::VariableWarehouse::get_variable_subclass<VelocityVariable>(VariablesParsing::velocity_variable_name(input,physics_name,VariablesParsing::PHYSICS))),
       _press_var(GRINSPrivate::VariableWarehouse::get_variable_subclass<PressureFEVariable>(VariablesParsing::press_variable_name(input,physics_name,VariablesParsing::PHYSICS))),
       _temp_vars(GRINSPrivate::VariableWarehouse::get_variable_subclass<PrimitiveTempFEVariables>(VariablesParsing::temp_variable_name(input,physics_name,VariablesParsing::PHYSICS))),
       _species_vars(GRINSPrivate::VariableWarehouse::get_variable_subclass<SpeciesMassFractionsVariable>(VariablesParsing::species_mass_frac_variable_name(input,physics_name,VariablesParsing::PHYSICS))),
       _p0_var(NULL),
       _n_species(_species_vars.n_species()),
       _fixed_density( input("Physics/"+PhysicsNaming::reacting_low_mach_navier_stokes()+"/fixed_density", false ) ),
       _fixed_rho_value(0.0)
   {
     _press_var.set_is_constraint_var(true);
     this->set_parameter
       (_fixed_rho_value, input,
        "Physics/"+PhysicsNaming::reacting_low_mach_navier_stokes()+"/fixed_rho_value", 0.0 );
     _enable_thermo_press_calc = input("Physics/"+PhysicsNaming::reacting_low_mach_navier_stokes()+"/enable_thermo_press_calc", false );
     if( _enable_thermo_press_calc )
       {
         _p0_var = &GRINSPrivate::VariableWarehouse::get_variable_subclass<ThermoPressureVariable>(VariablesParsing::thermo_press_variable_name(input,physics_name,VariablesParsing::PHYSICS));
         _p0_var->set_is_constraint_var(true);
       }
     this->read_input_options(input);
     this->check_var_subdomain_consistency(_flow_vars);
     this->check_var_subdomain_consistency(_press_var);
     this->check_var_subdomain_consistency(_temp_vars);
     this->check_var_subdomain_consistency(_species_vars);
   }
virtual GRINS::ReactingLowMachNavierStokesAbstract::~ReactingLowMachNavierStokesAbstract () inline virtual
Definition at line 48 of file reacting_low_mach_navier_stokes_abstract.h.
 {};
GRINS::ReactingLowMachNavierStokesAbstract::ReactingLowMachNavierStokesAbstract () private
Member Function Documentation
libMesh::Real GRINS::ReactingLowMachNavierStokesAbstract::get_p0_steady (const AssemblyContext & c, unsigned int qp) const inline
Definition at line 147 of file reacting_low_mach_navier_stokes_abstract.h.
References _enable_thermo_press_calc, _p0, _p0_var, and GRINS::ThermoPressureVariable::p0().
   {
     libMesh::Real p0;
     if( this->_enable_thermo_press_calc )
       {
         p0 = c.interior_value( _p0_var->p0(), qp );
       }
     else
       {
         p0 = _p0;
       }
     return p0;
   }
libMesh::Real GRINS::ReactingLowMachNavierStokesAbstract::get_p0_steady (const AssemblyContext & c, const libMesh::Point & p) const inline
Definition at line 179 of file reacting_low_mach_navier_stokes_abstract.h.
References _enable_thermo_press_calc, _p0, _p0_var, and GRINS::ThermoPressureVariable::p0().
   {
     libMesh::Real p0;
     if( this->_enable_thermo_press_calc )
       {
         p0 = c.point_value( _p0_var->p0(), p );
       }
     else
       {
         p0 = _p0;
       }
     return p0;
   }
libMesh::Real GRINS::ReactingLowMachNavierStokesAbstract::get_p0_steady_side (const AssemblyContext & c, unsigned int qp) const inline
Definition at line 163 of file reacting_low_mach_navier_stokes_abstract.h.
References _enable_thermo_press_calc, _p0, _p0_var, and GRINS::ThermoPressureVariable::p0().
   {
     libMesh::Real p0;
     if( this->_enable_thermo_press_calc )
       {
         p0 = c.side_value( _p0_var->p0(), qp );
       }
     else
       {
         p0 = _p0;
       }
     return p0;
   }
libMesh::Real GRINS::ReactingLowMachNavierStokesAbstract::get_p0_transient (const AssemblyContext & c, unsigned int qp) const inline
Definition at line 195 of file reacting_low_mach_navier_stokes_abstract.h.
References _enable_thermo_press_calc, _p0, _p0_var, and GRINS::ThermoPressureVariable::p0().
   {
     libMesh::Real p0;
     if( this->_enable_thermo_press_calc )
       {
         p0 = c.fixed_interior_value( _p0_var->p0(), qp );
       }
     else
       {
         p0 = _p0;
       }
     return p0;
   }
void GRINS::ReactingLowMachNavierStokesAbstract::init_context (AssemblyContext & context) virtual
Initialize context for added physics variables.
Reimplemented from GRINS::Physics.
Reimplemented in GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >, and GRINS::ReactingLowMachNavierStokesStabilizationBase< Mixture, Evaluator >.
Definition at line 129 of file reacting_low_mach_navier_stokes_abstract.C.
References _flow_vars, _press_var, _species_vars, _temp_vars, GRINS::PressureFEVariable::p(), GRINS::SpeciesMassFractionsVariable::species(), GRINS::PrimitiveTempFEVariables::T(), and GRINS::MultcomponentVectorVariable::u().
Referenced by GRINS::ReactingLowMachNavierStokesStabilizationBase< Mixture, Evaluator >::init_context(), and GRINS::ReactingLowMachNavierStokes< Mixture, Evaluator >::init_context().
   {
     // We should prerequest all the data
     // we will need to build the linear system
     // or evaluate a quantity of interest.
     context.get_element_fe(_species_vars.species(0))->get_JxW();
     context.get_element_fe(_species_vars.species(0))->get_phi();
     context.get_element_fe(_species_vars.species(0))->get_dphi();
     context.get_element_fe(_species_vars.species(0))->get_xyz();
     context.get_element_fe(_flow_vars.u())->get_JxW();
     context.get_element_fe(_flow_vars.u())->get_phi();
     context.get_element_fe(_flow_vars.u())->get_dphi();
     context.get_element_fe(_flow_vars.u())->get_xyz();
     context.get_element_fe(_temp_vars.T())->get_JxW();
     context.get_element_fe(_temp_vars.T())->get_phi();
     context.get_element_fe(_temp_vars.T())->get_dphi();
     context.get_element_fe(_temp_vars.T())->get_xyz();
     context.get_element_fe(_press_var.p())->get_phi();
     context.get_element_fe(_press_var.p())->get_xyz();
   }
void GRINS::ReactingLowMachNavierStokesAbstract::mass_fractions (const libMesh::Point & p, const AssemblyContext & c, std::vector< libMesh::Real > & mass_fracs) const inline
Definition at line 120 of file reacting_low_mach_navier_stokes_abstract.h.
References _n_species, _species_vars, and GRINS::SpeciesMassFractionsVariable::species().
   {
     libmesh_assert_equal_to(mass_fracs.size(), this->_n_species);
     for( unsigned int var = 0; var < this->_n_species; var++ )
       {
         mass_fracs[var] = c.point_value(_species_vars.species(var),p);
       }
   }
unsigned int GRINS::ReactingLowMachNavierStokesAbstract::n_species () const inline
Definition at line 111 of file reacting_low_mach_navier_stokes_abstract.h.
References _n_species.
   { return _n_species; }
void GRINS::ReactingLowMachNavierStokesAbstract::read_input_options (const GetPot & input) private
Read options from GetPot input file.
Definition at line 82 of file reacting_low_mach_navier_stokes_abstract.C.
References _g, _p0, GRINS::PhysicsNaming::reacting_low_mach_navier_stokes(), and GRINS::MaterialsParsing::read_property().
Referenced by ReactingLowMachNavierStokesAbstract().
   {
     // Read thermodynamic pressure info
     MaterialsParsing::read_property( input,
                                      "Physics/"+PhysicsNaming::reacting_low_mach_navier_stokes()+"/p0",
                                      "ThermodynamicPressure",
                                      PhysicsNaming::reacting_low_mach_navier_stokes(),
                                      (*this),
                                      _p0 );
     // Read gravity vector
     unsigned int g_dim = input.vector_variable_size("Physics/"+PhysicsNaming::reacting_low_mach_navier_stokes()+"/g");
     _g(0) = input("Physics/"+PhysicsNaming::reacting_low_mach_navier_stokes()+"/g", 0.0, 0 );
     if( g_dim > 1)
       _g(1) = input("Physics/"+PhysicsNaming::reacting_low_mach_navier_stokes()+"/g", 0.0, 1 );
     if( g_dim == 3)
       _g(2) = input("Physics/"+PhysicsNaming::reacting_low_mach_navier_stokes()+"/g", 0.0, 2 );
   }
libMesh::Real GRINS::ReactingLowMachNavierStokesAbstract::rho (libMesh::Real T, libMesh::Real p0, libMesh::Real R_mix) const inline
Definition at line 133 of file reacting_low_mach_navier_stokes_abstract.h.
References _fixed_density, _fixed_rho_value, and T().
   {
     libMesh::Real value = 0;
     if( this->_fixed_density )
       value = this->_fixed_rho_value;
     else
       value = p0/(R_mix*T);
     return value;
   }
void GRINS::ReactingLowMachNavierStokesAbstract::set_time_evolving_vars (libMesh::FEMSystem * system) virtual
Sets velocity variables to be time-evolving.
Reimplemented from GRINS::Physics.
Definition at line 105 of file reacting_low_mach_navier_stokes_abstract.C.
References _enable_thermo_press_calc, _flow_vars, _n_species, _p0_var, _press_var, _species_vars, _temp_vars, GRINS::PressureFEVariable::p(), GRINS::ThermoPressureVariable::p0(), GRINS::SpeciesMassFractionsVariable::species(), GRINS::PrimitiveTempFEVariables::T(), GRINS::MultcomponentVectorVariable::u(), GRINS::MultcomponentVectorVariable::v(), and GRINS::MultcomponentVectorVariable::w().
   {
     const unsigned int dim = system->get_mesh().mesh_dimension();
     for( unsigned int i = 0; i < this->_n_species; i++ )
       {
         system->time_evolving( _species_vars.species(i), 1 );
       }
     system->time_evolving(_flow_vars.u(), 1);
     if (dim > 1)
       system->time_evolving(_flow_vars.v(), 1);
     if (dim == 3)
       system->time_evolving(_flow_vars.w(), 1);
     system->time_evolving(_temp_vars.T(), 1);
     system->time_evolving(_press_var.p(), 1);
     if( _enable_thermo_press_calc )
       system->time_evolving(_p0_var->p0(), 1);
   }
libMesh::Real GRINS::ReactingLowMachNavierStokesAbstract::T (const libMesh::Point & p, const AssemblyContext & c) const inline
Definition at line 115 of file reacting_low_mach_navier_stokes_abstract.h.
References _temp_vars, and GRINS::PrimitiveTempFEVariables::T().
Referenced by rho().
   { return c.point_value(_temp_vars.T(),p); }
Member Data Documentation
bool GRINS::ReactingLowMachNavierStokesAbstract::_enable_thermo_press_calc protected
Flag to enable thermodynamic pressure calculation.
Definition at line 94 of file reacting_low_mach_navier_stokes_abstract.h.
Referenced by get_p0_steady(), get_p0_steady_side(), get_p0_transient(), ReactingLowMachNavierStokesAbstract(), and set_time_evolving_vars().
bool GRINS::ReactingLowMachNavierStokesAbstract::_fixed_density protected
Definition at line 96 of file reacting_low_mach_navier_stokes_abstract.h.
Referenced by rho().
libMesh::Real GRINS::ReactingLowMachNavierStokesAbstract::_fixed_rho_value protected
Definition at line 98 of file reacting_low_mach_navier_stokes_abstract.h.
Referenced by ReactingLowMachNavierStokesAbstract(), and rho().
VelocityVariable& GRINS::ReactingLowMachNavierStokesAbstract::_flow_vars protected
Definition at line 77 of file reacting_low_mach_navier_stokes_abstract.h.
Referenced by init_context(), ReactingLowMachNavierStokesAbstract(), and set_time_evolving_vars().
libMesh::Point GRINS::ReactingLowMachNavierStokesAbstract::_g protected
Gravity vector.
Definition at line 91 of file reacting_low_mach_navier_stokes_abstract.h.
Referenced by read_input_options().
unsigned int GRINS::ReactingLowMachNavierStokesAbstract::_n_species protected
Number of species.
Definition at line 88 of file reacting_low_mach_navier_stokes_abstract.h.
Referenced by mass_fractions(), n_species(), and set_time_evolving_vars().
libMesh::Number GRINS::ReactingLowMachNavierStokesAbstract::_p0 protected
Definition at line 75 of file reacting_low_mach_navier_stokes_abstract.h.
Referenced by get_p0_steady(), get_p0_steady_side(), get_p0_transient(), and read_input_options().
ThermoPressureVariable* GRINS::ReactingLowMachNavierStokesAbstract::_p0_var protected
Todo:
When we mandate C++11, switch this to a SharedPtr.
Then, in the VariableWarhouse, we can use dynamic_pointer_cast to get a SharedPtr.
Definition at line 85 of file reacting_low_mach_navier_stokes_abstract.h.
Referenced by get_p0_steady(), get_p0_steady_side(), get_p0_transient(), ReactingLowMachNavierStokesAbstract(), and set_time_evolving_vars().
PressureFEVariable& GRINS::ReactingLowMachNavierStokesAbstract::_press_var protected
Definition at line 78 of file reacting_low_mach_navier_stokes_abstract.h.
Referenced by init_context(), ReactingLowMachNavierStokesAbstract(), and set_time_evolving_vars().
SpeciesMassFractionsVariable& GRINS::ReactingLowMachNavierStokesAbstract::_species_vars protected
Definition at line 81 of file reacting_low_mach_navier_stokes_abstract.h.
Referenced by init_context(), mass_fractions(), ReactingLowMachNavierStokesAbstract(), and set_time_evolving_vars().
PrimitiveTempFEVariables& GRINS::ReactingLowMachNavierStokesAbstract::_temp_vars protected
Definition at line 79 of file reacting_low_mach_navier_stokes_abstract.h.
Referenced by init_context(), ReactingLowMachNavierStokesAbstract(), set_time_evolving_vars(), and T().
The documentation for this class was generated from the following files:
src/physics/include/grins/reacting_low_mach_navier_stokes_abstract.h
src/physics/src/reacting_low_mach_navier_stokes_abstract.C