GRINS-0.7.0: GRINS::ConvectionDiffusion Class Reference
GRINS::ConvectionDiffusion Class Reference
#include <convection_diffusion.h>
Public Member Functions
ConvectionDiffusion (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~ConvectionDiffusion ()
virtual void init_variables (libMesh::FEMSystem *system)
Initialize variables for this physics.
virtual void set_time_evolving_vars (libMesh::FEMSystem *system)
Set which variables are time evolving.
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
virtual void element_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for element interiors.
virtual void mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
Public Member Functions inherited from GRINS::Physics
Physics (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~Physics ()
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void side_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Constraint part(s) of physics for scalar variables.
virtual void damping_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Damping matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool compute_jacobian, AssemblyContext &context, CachedValues &cache)
Mass matrix part(s) for scalar variables.
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
virtual void compute_element_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_time_derivative_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_element_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_side_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_constraint_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_damping_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_nonlocal_mass_residual_cache (const AssemblyContext &context, CachedValues &cache)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
ICHandlingBase * get_ic_handler ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Attributes
std::vector< libMesh::ParsedFunction< libMesh::Number > > _v
Velocity field, ;.
libMesh::ParsedFunction< libMesh::Number > _kappa
Diffusivity, .
GenericFETypeVariable _var
Protected Attributes inherited from GRINS::Physics
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
Private Member Functions
ConvectionDiffusion ()
Additional Inherited Members
Static Public Member Functions inherited from GRINS::Physics
static void set_is_axisymmetric (bool is_axisymmetric)
Set whether we should treat the problem as axisymmetric.
static bool is_axisymmetric ()
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Member Functions inherited from GRINS::Physics
libMesh::UniquePtr< libMesh::FEGenericBase< libMesh::Real > > build_new_fe (const libMesh::Elem *elem, const libMesh::FEGenericBase< libMesh::Real > *fe, const libMesh::Point p)
void parse_enabled_subdomains (const GetPot &input, const std::string &physics_name)
Static Protected Attributes inherited from GRINS::Physics
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
static bool _is_axisymmetric = false
Caches whether we are solving an axisymmetric problem or not.
Detailed Description
Definition at line 37 of file convection_diffusion.h.
Constructor & Destructor Documentation
GRINS::ConvectionDiffusion::ConvectionDiffusion (const GRINS::PhysicsName & physics_name, const GetPot & input)
Definition at line 44 of file convection_diffusion.C.
References GRINS::Physics::_ic_handler, _kappa, _v, _var, GRINS::GRINSPrivate::VariableWarehouse::check_and_register_variable(), GRINS::MaterialsParsing::material_name(), GRINS::GenericFETypeVariable::section_name(), and GRINS::ParameterUser::set_parameter().
     : Physics(physics_name,input),
       _v(3,libMesh::ParsedFunction<libMesh::Number>("0.0") ),
       _kappa("0.0"),
       _var(input,physics_name)
   {
     unsigned int n_v_comps = input.vector_variable_size("Physics/"+physics_name+"/velocity_field");
     for( unsigned int v = 0; v < n_v_comps; v++ )
       _v[v].reparse( input("Physics/"+physics_name+"/velocity_field", "0.0", v) );
     std::string material_name = MaterialsParsing::material_name(input,physics_name);
     this->set_parameter(this->_kappa, input,
                         "Materials/"+material_name+"/Diffusivity/value",
                         "DIE!");
     GRINSPrivate::VariableWarehouse::check_and_register_variable(this->_var.section_name(physics_name), this->_var);
     _ic_handler = new GenericICHandler(physics_name,input);
   }
virtual GRINS::ConvectionDiffusion::~ConvectionDiffusion () inline virtual
Definition at line 43 of file convection_diffusion.h.
 {};
GRINS::ConvectionDiffusion::ConvectionDiffusion () private
Member Function Documentation
void GRINS::ConvectionDiffusion::element_time_derivative (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Time dependent part(s) of physics for element interiors.
Reimplemented from GRINS::Physics.
Definition at line 85 of file convection_diffusion.C.
References _kappa, _v, _var, and GRINS::GenericFETypeVariable::var().
   {
     const unsigned int n_dofs = context.get_dof_indices(_var.var()).size();
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(_var.var())->get_JxW();
     const std::vector<std::vector<libMesh::Real> >& phi =
       context.get_element_fe(_var.var())->get_phi();
     const std::vector<std::vector<libMesh::RealGradient> >& grad_phi =
       context.get_element_fe(_var.var())->get_dphi();
     const std::vector<libMesh::Point>& x =
       context.get_element_fe(_var.var())->get_xyz();
     libMesh::DenseSubVector<libMesh::Number> &F = context.get_elem_residual(_var.var());
     libMesh::DenseSubMatrix<libMesh::Number> &K = context.get_elem_jacobian(_var.var(), _var.var());
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     for (unsigned int qp=0; qp != n_qpoints; qp++)
       {
         libMesh::Number c = context.interior_value(_var.var(), qp);
         libMesh::Gradient grad_c;
         context.interior_gradient(_var.var(), qp, grad_c);
         libMesh::RealGradient v_qp;
         v_qp(0) = this->_v[0](x[qp], context.get_time());
         v_qp(1) = this->_v[1](x[qp], context.get_time());
         v_qp(2) = this->_v[2](x[qp], context.get_time());
         libMesh::Real kappa_qp = this->_kappa(x[qp], context.time);
         for (unsigned int i=0; i != n_dofs; i++)
           {
             F(i) += JxW[qp]*( c*(v_qp*grad_phi[i][qp])
                               - kappa_qp*(grad_c*grad_phi[i][qp]) );
             if (compute_jacobian)
               {
                 for (unsigned int j=0; j != n_dofs; j++)
                   {
                     K(i,j) += context.get_elem_solution_derivative()*
                               JxW[qp]*( phi[j][qp]*(v_qp*grad_phi[i][qp])
                                       - kappa_qp*(grad_phi[j][qp]*grad_phi[i][qp]) );
                   }
               }
           }
       }
   }
void GRINS::ConvectionDiffusion::init_context (AssemblyContext & context) virtual
Initialize context for added physics variables.
Reimplemented from GRINS::Physics.
Definition at line 77 of file convection_diffusion.C.
References _var, and GRINS::GenericFETypeVariable::var().
   {
     context.get_element_fe(_var.var())->get_JxW();
     context.get_element_fe(_var.var())->get_phi();
     context.get_element_fe(_var.var())->get_dphi();
     context.get_element_fe(_var.var())->get_xyz();
   }
void GRINS::ConvectionDiffusion::init_variables (libMesh::FEMSystem * system) virtual
Initialize variables for this physics.
Implements GRINS::Physics.
Definition at line 67 of file convection_diffusion.C.
References _var, and GRINS::SingleFETypeVariable::init().
   {
     _var.init(system);
   }
void GRINS::ConvectionDiffusion::mass_residual (bool compute_jacobian, AssemblyContext & context, CachedValues & cache) virtual
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
Reimplemented from GRINS::Physics.
Definition at line 141 of file convection_diffusion.C.
References _var, and GRINS::GenericFETypeVariable::var().
   {
     const unsigned int n_dofs = context.get_dof_indices(_var.var()).size();
     const std::vector<libMesh::Real> &JxW =
       context.get_element_fe(_var.var())->get_JxW();
     const std::vector<std::vector<libMesh::Real> >& phi =
       context.get_element_fe(_var.var())->get_phi();
     libMesh::DenseSubVector<libMesh::Number> &F = context.get_elem_residual(_var.var());
     libMesh::DenseSubMatrix<libMesh::Number> &M = context.get_elem_jacobian(_var.var(), _var.var());
     unsigned int n_qpoints = context.get_element_qrule().n_points();
     for (unsigned int qp=0; qp != n_qpoints; qp++)
       {
         libMesh::Real c_dot;
         context.interior_rate(_var.var(), qp, c_dot);
         for (unsigned int i=0; i != n_dofs; i++)
           {
             F(i) -= JxW[qp]*( c_dot*phi[i][qp] );
             if (compute_jacobian)
               {
                 for (unsigned int j=0; j != n_dofs; j++)
                   {
                     M(i,j) -=
                       context.get_elem_solution_rate_derivative()*
                       JxW[qp]*( phi[j][qp]*phi[i][qp] );
                   }
               }
           }
       }
   }
void GRINS::ConvectionDiffusion::set_time_evolving_vars (libMesh::FEMSystem * system) virtual
Set which variables are time evolving.
Set those variables which evolve in time (as opposed to variables that behave like constraints). This is done separately from init_variables() because the MultiphysicsSystem must initialize its base class before time_evolving variables can be set. Default implementation is no time evolving variables.
Reimplemented from GRINS::Physics.
Definition at line 72 of file convection_diffusion.C.
References _var, and GRINS::GenericFETypeVariable::var().
   {
     system->time_evolving(_var.var());
   }
Member Data Documentation
libMesh::ParsedFunction<libMesh::Number> GRINS::ConvectionDiffusion::_kappa protected
Diffusivity, .
Definition at line 67 of file convection_diffusion.h.
Referenced by ConvectionDiffusion(), and element_time_derivative().
std::vector<libMesh::ParsedFunction<libMesh::Number> > GRINS::ConvectionDiffusion::_v protected
Velocity field, ;.
Definition at line 64 of file convection_diffusion.h.
Referenced by ConvectionDiffusion(), and element_time_derivative().
GenericFETypeVariable GRINS::ConvectionDiffusion::_var protected
Definition at line 69 of file convection_diffusion.h.
Referenced by ConvectionDiffusion(), element_time_derivative(), init_context(), init_variables(), mass_residual(), and set_time_evolving_vars().
The documentation for this class was generated from the following files:
src/physics/include/grins/convection_diffusion.h
src/physics/src/convection_diffusion.C