GRINS-0.8.0: GRINS::PowerLawCatalycity Class Reference
GRINS::PowerLawCatalycity Class Reference
#include <power_law_catalycity.h>
Public Member Functions
PowerLawCatalycity (const libMesh::Real gamma0, const libMesh::Real Ta, const libMesh::Real alpha)
virtual ~PowerLawCatalycity ()
virtual libMesh::Real operator() (const libMesh::Real T) const
virtual libMesh::Real dT (const libMesh::Real T) const
virtual void set_params (const std::vector< libMesh::Real > &params)
virtual CatalycityBase * clone () const
Creates a new copy of the current class.
virtual void set_parameters (const GetPot &input, const std::string &param_base)
Sets parameters for use in sensitivity analysis.
Public Member Functions inherited from GRINS::CatalycityBase
CatalycityBase ()
virtual ~CatalycityBase ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Attributes
libMesh::Real _gamma0
libMesh::Real _Tref
libMesh::Real _alpha
Private Member Functions
PowerLawCatalycity ()
Additional Inherited Members
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Detailed Description
Definition at line 33 of file power_law_catalycity.h.
Constructor & Destructor Documentation
GRINS::PowerLawCatalycity::PowerLawCatalycity (const libMesh::Real gamma0, const libMesh::Real Ta, const libMesh::Real alpha)
Definition at line 33 of file power_law_catalycity.C.
     : _gamma0(gamma0),
       _Tref(Tref),
       _alpha(alpha)
   {
     return;
   }
GRINS::PowerLawCatalycity::~PowerLawCatalycity () virtual
Definition at line 43 of file power_law_catalycity.C.
   {
     return;
   }
GRINS::PowerLawCatalycity::PowerLawCatalycity () private
Referenced by clone().
Member Function Documentation
CatalycityBase * GRINS::PowerLawCatalycity::clone () const virtual
Creates a new copy of the current class.
A raw pointer is returned and it is assumed the user will take ownership and worry about memory management.
Implements GRINS::CatalycityBase.
Definition at line 71 of file power_law_catalycity.C.
References PowerLawCatalycity().
   {
     return new PowerLawCatalycity( *this );
   }
libMesh::Real GRINS::PowerLawCatalycity::dT (const libMesh::Real T) const virtual
Implements GRINS::CatalycityBase.
Definition at line 53 of file power_law_catalycity.C.
References _alpha.
Referenced by main().
   {
     return (*this)(T)*_alpha/T;
   }
libMesh::Real GRINS::PowerLawCatalycity::operator() (const libMesh::Real T) const virtual
Implements GRINS::CatalycityBase.
Definition at line 48 of file power_law_catalycity.C.
References _alpha, _gamma0, and _Tref.
   {
     return _gamma0*std::pow( T/_Tref, _alpha);
   }
void GRINS::PowerLawCatalycity::set_parameters (const GetPot & input, const std::string & param_base) virtual
Sets parameters for use in sensitivity analysis.
Implements GRINS::CatalycityBase.
Definition at line 76 of file power_law_catalycity.C.
References _alpha, _gamma0, _Tref, and GRINS::ParameterUser::set_parameter().
   {
     std::string gamma0_str = param_base+"gamma0";
     this->set_parameter(_gamma0,input,gamma0_str,_gamma0);
     std::string Tref_str = param_base+"Tref";
     this->set_parameter(_Tref,input,Tref_str,_Tref);
     std::string alpha_str = param_base+"alpha";
     this->set_parameter(_alpha,input,alpha_str,_alpha);
   }
void GRINS::PowerLawCatalycity::set_params (const std::vector< libMesh::Real > & params) virtual
Implements GRINS::CatalycityBase.
Definition at line 58 of file power_law_catalycity.C.
References _alpha, _gamma0, and _Tref.
Referenced by main().
   {
     libmesh_assert_equal_to( params.size(), 3 );
     _gamma0 = params[0];
     _Tref = params[1];
     _alpha = params[2];
     return;
   }
Member Data Documentation
libMesh::Real GRINS::PowerLawCatalycity::_alpha protected
Definition at line 60 of file power_law_catalycity.h.
Referenced by dT(), operator()(), set_parameters(), and set_params().
libMesh::Real GRINS::PowerLawCatalycity::_gamma0 protected
Definition at line 56 of file power_law_catalycity.h.
Referenced by operator()(), set_parameters(), and set_params().
libMesh::Real GRINS::PowerLawCatalycity::_Tref protected
Definition at line 58 of file power_law_catalycity.h.
Referenced by operator()(), set_parameters(), and set_params().
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/power_law_catalycity.h
src/boundary_conditions/src/power_law_catalycity.C