GRINS-0.8.0: GRINSTesting::KineticsTestBase Class Reference
GRINSTesting::KineticsTestBase Class Reference
#include <kinetics_test_base.h>
Public Member Functions
template<typename ThermoMixture , typename ThermoEvaluator >
void test_omega_dot_common (ThermoMixture &mixture, NASAThermoTestBase &thermo_funcs, const std::vector< libMesh::Real > &Y, libMesh::Real rel_tol)
Public Member Functions inherited from GRINSTesting::SpeciesTestBase
SpeciesTestBase ()
libMesh::Real molar_mass (unsigned int idx)
libMesh::Real R_species (unsigned int idx)
Protected Attributes
unsigned int _n_reactions
std::vector< libMesh::Real > _Ea_coeffs
std::vector< libMesh::Real > _preexp_coeffs
std::vector< libMesh::Real > _temp_exp_coeffs
std::vector< std::vector< libMesh::Real > > _three_body_coeffs
std::vector< bool > _is_three_body_rxn
std::vector< std::vector< libMesh::Real > > _reactant_stoich_coeffs
std::vector< std::vector< libMesh::Real > > _product_stoich_coeffs
Protected Attributes inherited from GRINSTesting::SpeciesTestBase
unsigned int _N2_idx
unsigned int _O2_idx
unsigned int _O_idx
unsigned int _N_idx
unsigned int _NO_idx
std::vector< unsigned int > _active_species
Private Member Functions
void compute_reaction_rates (libMesh::Real T, const std::vector< libMesh::Real > &molar_densities, NASAThermoTestBase &thermo_funcs, std::vector< libMesh::Real > &forward_rates, std::vector< libMesh::Real > &backward_rates)
libMesh::Real eq_constant (libMesh::Real T, std::vector< libMesh::Real > &reactant_stoich_coeffs, std::vector< libMesh::Real > &product_stoich_coeffs, NASAThermoTestBase &thermo_funcs)
Detailed Description
Definition at line 42 of file kinetics_test_base.h.
Member Function Documentation
void GRINSTesting::KineticsTestBase::compute_reaction_rates (libMesh::Real T, const std::vector< libMesh::Real > & molar_densities, NASAThermoTestBase & thermo_funcs, std::vector< libMesh::Real > & forward_rates, std::vector< libMesh::Real > & backward_rates) inline private
Definition at line 126 of file kinetics_test_base.h.
References GRINSTesting::SpeciesTestBase::_active_species, _n_reactions, GRINSTesting::ThermochemTestCommon::arrhenius_rate(), GRINSTesting::ThermochemTestCommon::compute_third_body_molar_density(), and eq_constant().
Referenced by test_omega_dot_common().
     {
       forward_rates.resize(_n_reactions,1.0);
       backward_rates.resize(_n_reactions,1.0);
       for( unsigned int r = 0; r < _n_reactions; r++ )
         {
           libMesh::Real fwd_rate_coeff = ThermochemTestCommon::arrhenius_rate( _preexp_coeffs[r],
                                                                                _temp_exp_coeffs[r],
                                                                                _Ea_coeffs[r],
                                                                                T );
           libMesh::Real Keq = this->eq_constant(T,
                                                 _reactant_stoich_coeffs[r],
                                                 _product_stoich_coeffs[r],
                                                 thermo_funcs);
           libMesh::Real bkwd_rate_coeff = fwd_rate_coeff/Keq;
           forward_rates[r] *= fwd_rate_coeff;
           backward_rates[r] *= bkwd_rate_coeff;
           for( unsigned int s = 0; s < _active_species.size(); s++ )
             {
               forward_rates[r] *= std::pow(molar_densities[s],_reactant_stoich_coeffs[r][s]);
               backward_rates[r] *= std::pow(molar_densities[s],_product_stoich_coeffs[r][s]);
             }
           if( _is_three_body_rxn[r] )
             {
               libMesh::Real M = ThermochemTestCommon::compute_third_body_molar_density( molar_densities,
                                                                                         _three_body_coeffs[r] );
               forward_rates[r] *= M;
               backward_rates[r] *= M;
             }
         }
     }
libMesh::Real GRINSTesting::KineticsTestBase::eq_constant (libMesh::Real T, std::vector< libMesh::Real > & reactant_stoich_coeffs, std::vector< libMesh::Real > & product_stoich_coeffs, NASAThermoTestBase & thermo_funcs) inline private
Definition at line 169 of file kinetics_test_base.h.
References GRINSTesting::NASAThermoTestBase::h_RT_exact(), GRINS::Constants::R_universal, and GRINSTesting::NASAThermoTestBase::s_R_exact().
Referenced by compute_reaction_rates().
     {
       CPPUNIT_ASSERT_EQUAL( reactant_stoich_coeffs.size(), product_stoich_coeffs.size() );
       libMesh::Real coeff_sum = 0.0;
       libMesh::Real exp_sum = 0.0;
       for( unsigned int s = 0; s < reactant_stoich_coeffs.size(); s++ )
         {
           libMesh::Real stoich = (product_stoich_coeffs[s] - reactant_stoich_coeffs[s]);
           coeff_sum += stoich;
           exp_sum += stoich*( thermo_funcs.h_RT_exact(s,T) - thermo_funcs.s_R_exact(s,T) );
         }
       libMesh::Real P_RT = 1e5/(GRINS::Constants::R_universal*T);
       return std::pow(P_RT,coeff_sum)*std::exp(-exp_sum);
     }
template<typename ThermoMixture , typename ThermoEvaluator > void GRINSTesting::KineticsTestBase::test_omega_dot_common (ThermoMixture & mixture, NASAThermoTestBase & thermo_funcs, const std::vector< libMesh::Real > & Y, libMesh::Real rel_tol) inline
Definition at line 47 of file kinetics_test_base.h.
References GRINSTesting::SpeciesTestBase::_active_species, _n_reactions, _product_stoich_coeffs, _reactant_stoich_coeffs, GRINSTesting::TestingUtils::abs_tol_from_rel_tol(), compute_reaction_rates(), and GRINSTesting::SpeciesTestBase::molar_mass().
     {
       CPPUNIT_ASSERT_EQUAL(_active_species.size(), Y.size() );
       ThermoEvaluator evaluator( mixture );
       libMesh::Real rho = 1.0e-3;
       std::vector<libMesh::Real> molar_densities(_active_species.size(),0.0);
       for( unsigned int s = 0; s < _active_species.size(); s++ )
         molar_densities[s] = rho*Y[s]/this->molar_mass(s);
       libMesh::Real T = 300;
       while( T <= 1000 )
         {
           std::vector<libMesh::Real> forward_rates, backward_rates;
           this->compute_reaction_rates( T, molar_densities, thermo_funcs, forward_rates, backward_rates );
           std::vector<libMesh::Real> omega_dot_exact(_active_species.size(), 0.0);
           std::vector<libMesh::Real> omega_dot_computed(_active_species.size());
           evaluator.omega_dot( T, rho, Y, omega_dot_computed );
           for( unsigned int s = 0; s < _active_species.size(); s++ )
             for( unsigned int r = 0; r < _n_reactions; r++ )
               {
                 unsigned int species = _active_species[s];
                 libMesh::Real stoich = _product_stoich_coeffs[r][species] - _reactant_stoich_coeffs[r][species];
                 omega_dot_exact[s] += this->molar_mass(species)*stoich*( forward_rates[r] - backward_rates[r] );
               }
           for( unsigned int s = 0; s < _active_species.size(); s++ )
             {
               unsigned int species = _active_species[s];
               std::stringstream ss;
               ss << T;
               std::string message = "T = "+ss.str();
               ss.str(std::string());
               ss << s;
               message += ", species = "+mixture.species_name(species);
               /*
                 std::cout << message
                 << ", omega_dot_exact = " << omega_dot_exact[s]
                 << ", omega_dot_computed = " << omega_dot_computed[s]
                 << std::endl;
               */
               libMesh::Real tol = TestingUtils::abs_tol_from_rel_tol( omega_dot_exact[s], rel_tol );
               CPPUNIT_ASSERT_DOUBLES_EQUAL_MESSAGE( message,
                                                     omega_dot_exact[s],
                                                     omega_dot_computed[s],
                                                     tol );
             }
           T += 100.0;
         }
     }
Member Data Documentation
std::vector<libMesh::Real> GRINSTesting::KineticsTestBase::_Ea_coeffs protected
Definition at line 114 of file kinetics_test_base.h.
Referenced by GRINSTesting::AirKineticsTestBase::init_air_kinetics().
std::vector<bool> GRINSTesting::KineticsTestBase::_is_three_body_rxn protected
Definition at line 119 of file kinetics_test_base.h.
Referenced by GRINSTesting::AirKineticsTestBase::init_air_kinetics().
unsigned int GRINSTesting::KineticsTestBase::_n_reactions protected
Definition at line 112 of file kinetics_test_base.h.
Referenced by compute_reaction_rates(), GRINSTesting::AirKineticsTestBase::init_air_kinetics(), and test_omega_dot_common().
std::vector<libMesh::Real> GRINSTesting::KineticsTestBase::_preexp_coeffs protected
Definition at line 115 of file kinetics_test_base.h.
Referenced by GRINSTesting::AirKineticsTestBase::init_air_kinetics().
std::vector<std::vector<libMesh::Real> > GRINSTesting::KineticsTestBase::_product_stoich_coeffs protected
Definition at line 122 of file kinetics_test_base.h.
Referenced by GRINSTesting::AirKineticsTestBase::init_air_kinetics(), and test_omega_dot_common().
std::vector<std::vector<libMesh::Real> > GRINSTesting::KineticsTestBase::_reactant_stoich_coeffs protected
Definition at line 121 of file kinetics_test_base.h.
Referenced by GRINSTesting::AirKineticsTestBase::init_air_kinetics(), and test_omega_dot_common().
std::vector<libMesh::Real> GRINSTesting::KineticsTestBase::_temp_exp_coeffs protected
Definition at line 116 of file kinetics_test_base.h.
Referenced by GRINSTesting::AirKineticsTestBase::init_air_kinetics().
std::vector<std::vector<libMesh::Real> > GRINSTesting::KineticsTestBase::_three_body_coeffs protected
Definition at line 118 of file kinetics_test_base.h.
Referenced by GRINSTesting::AirKineticsTestBase::init_air_kinetics().
The documentation for this class was generated from the following file:
test/interface/kinetics_test_base.h