GRINS-0.7.0: GRINSTesting::AntiochAirNASA9KineticsTest Class Reference
GRINSTesting::AntiochAirNASA9KineticsTest Class Reference
Public Member Functions
CPPUNIT_TEST_SUITE (AntiochAirNASA9KineticsTest)
CPPUNIT_TEST (test_omega_dot)
CPPUNIT_TEST_SUITE_END ()
void setUp ()
void test_omega_dot ()
Public Member Functions inherited from GRINSTesting::AntiochTestBase
void init_antioch (const std::string &input_file, const std::string &material_name)
Public Member Functions inherited from GRINSTesting::AirKineticsTestBase
void init_air_kinetics ()
Public Member Functions inherited from GRINSTesting::KineticsTestBase
template<typename ThermoMixture , typename ThermoEvaluator >
void test_omega_dot_common (ThermoMixture &mixture, NASAThermoTestBase &thermo_funcs, const std::vector< libMesh::Real > &Y, libMesh::Real rel_tol)
Public Member Functions inherited from GRINSTesting::SpeciesTestBase
SpeciesTestBase ()
libMesh::Real molar_mass (unsigned int idx)
libMesh::Real R_species (unsigned int idx)
Public Member Functions inherited from GRINSTesting::AirTestBase
void init_air_test (unsigned int &N2_idx, unsigned int &O2_idx, unsigned int &N_idx, unsigned int &O_idx, unsigned int &NO_idx, std::vector< unsigned int > &active_species)
Additional Inherited Members
Protected Attributes inherited from GRINSTesting::AntiochTestBase
libMesh::UniquePtr< GRINS::AntiochMixture > _antioch_mixture
Protected Attributes inherited from GRINSTesting::KineticsTestBase
unsigned int _n_reactions
std::vector< libMesh::Real > _Ea_coeffs
std::vector< libMesh::Real > _preexp_coeffs
std::vector< libMesh::Real > _temp_exp_coeffs
std::vector< std::vector< libMesh::Real > > _three_body_coeffs
std::vector< bool > _is_three_body_rxn
std::vector< std::vector< libMesh::Real > > _reactant_stoich_coeffs
std::vector< std::vector< libMesh::Real > > _product_stoich_coeffs
Protected Attributes inherited from GRINSTesting::SpeciesTestBase
unsigned int _N2_idx
unsigned int _O2_idx
unsigned int _O_idx
unsigned int _N_idx
unsigned int _NO_idx
std::vector< unsigned int > _active_species
Detailed Description
Definition at line 231 of file air_5sp.C.
Member Function Documentation
GRINSTesting::AntiochAirNASA9KineticsTest::CPPUNIT_TEST (test_omega_dot)
GRINSTesting::AntiochAirNASA9KineticsTest::CPPUNIT_TEST_SUITE (AntiochAirNASA9KineticsTest)
GRINSTesting::AntiochAirNASA9KineticsTest::CPPUNIT_TEST_SUITE_END ()
void GRINSTesting::AntiochAirNASA9KineticsTest::setUp () inline
Definition at line 244 of file air_5sp.C.
References GRINSTesting::AirKineticsTestBase::init_air_kinetics(), and GRINSTesting::AntiochTestBase::init_antioch().
     {
       std::string input_file = std::string(GRINS_TEST_SRCDIR)+"/input_files/antioch.in";
       this->init_antioch(input_file, "TestMaterial");
       this->init_air_kinetics();
       //this->check_indices(*_antioch_mixture);
     }
void GRINSTesting::AntiochAirNASA9KineticsTest::test_omega_dot () inline
Definition at line 254 of file air_5sp.C.
References GRINSTesting::AntiochTestBase::_antioch_mixture, GRINSTesting::SpeciesTestBase::_N2_idx, GRINSTesting::SpeciesTestBase::_N_idx, GRINSTesting::SpeciesTestBase::_NO_idx, GRINSTesting::SpeciesTestBase::_O2_idx, GRINSTesting::SpeciesTestBase::_O_idx, and GRINSTesting::TestingUtils::epsilon().
     {
       std::vector<libMesh::Real> Y(5);
       Y[_N2_idx] = 0.15;
       Y[_O2_idx] = 0.35;
       Y[_NO_idx] = 0.25;
       Y[_O_idx] = 0.2;
       Y[_N_idx] = 0.05;
       AirNASA9Thermo thermo;
       this->test_omega_dot_common<GRINS::AntiochMixture,GRINS::AntiochEvaluator<Antioch::CEAEvaluator<libMesh::Real> > >
         ( *_antioch_mixture, thermo, Y, TestingUtils::epsilon()*1e3 );
     }
The documentation for this class was generated from the following file:
test/interface/air_5sp.C