GRINS-0.8.0: GRINS::ParsedFunctionNeumannBCFactory< FunctionType > Class Template Reference
GRINS::ParsedFunctionNeumannBCFactory< FunctionType > Class Template Reference
#include <parsed_function_neumann_bc_factory.h>
Public Member Functions
ParsedFunctionNeumannBCFactory (const std::string &bc_type_name)
~ParsedFunctionNeumannBCFactory ()
Public Member Functions inherited from GRINS::NeumannBCFactoryAbstract
NeumannBCFactoryAbstract (const std::string &bc_type_name)
~NeumannBCFactoryAbstract ()
virtual libMesh::UniquePtr< NeumannBCContainer > create ()
Creates NeumannBCContainer for this Factory object.
Public Member Functions inherited from GRINS::BCFactoryAbstract< NeumannBCContainer >
BCFactoryAbstract (const std::string &bc_type_name)
~BCFactoryAbstract ()
Public Member Functions inherited from GRINS::FactoryWithGetPot< NeumannBCContainer >
FactoryWithGetPot (const std::string &name)
~FactoryWithGetPot ()
Public Member Functions inherited from GRINS::FactoryAbstract< NeumannBCContainer >
virtual ~FactoryAbstract ()
Public Member Functions inherited from GRINS::ParsedFunctionNeumannBCFactoryHelper< FunctionType >
ParsedFunctionNeumannBCFactoryHelper ()
~ParsedFunctionNeumannBCFactoryHelper ()
Protected Member Functions
virtual SharedPtr< NeumannBCAbstract > build_neumann_func (const GetPot &input, MultiphysicsSystem &system, const FEVariablesBase &fe_var, const std::string &section)
Builds the NeumannBCAbstract object for Neumann boundary conditions.
virtual std::string flux_input (const std::string &section) const
Protected Member Functions inherited from GRINS::NeumannBCFactoryAbstract
void check_for_flux (const GetPot &input, const std::string &section, const std::vector< std::string > &var_names)
Checks that the flux variable has been set.
Protected Member Functions inherited from GRINS::BCFactoryAbstract< NeumannBCContainer >
void check_for_multiple_expressions (const GetPot &input, const std::string &section, const std::string &var_name) const
Ensure that there is only one expression for the [Section/var_name] variable.
void build_var_indices (const MultiphysicsSystem &system, const std::vector< std::string > &var_names, std::vector< VariableIndex > &var_indices) const
virtual void check_state () const
Helper function to reduce code duplication.
virtual void reset_state ()
Helper function to redue code duplication.
Protected Member Functions inherited from GRINS::FactoryAbstract< NeumannBCContainer >
FactoryAbstract (const std::string &name)
Constructor is protected. Use the build() method to construct Base objects.
Protected Member Functions inherited from GRINS::ParsedFunctionNeumannBCFactoryHelper< FunctionType >
SharedPtr< NeumannBCAbstract > build_neumman_func_common (const GetPot &input, MultiphysicsSystem &system, const FEVariablesBase &fe_var, const std::string &flux_input)
Helper function containing common code.
SharedPtr< NeumannBCAbstract > build_parsed_neumann_func (MultiphysicsSystem &system, const std::string &expression, VariableIndex var_idx)
Helper function that builds the right BC object depending on the FunctionType.
SharedPtr< NeumannBCAbstract > build_composite_parsed_neumann_func (MultiphysicsSystem &system, const std::vector< std::string > &expressions, const std::vector< VariableIndex > &var_indices)
Helper function that builds the right CompositeBC object depending on the FunctionType.
template<>
SharedPtr< NeumannBCAbstract > build_parsed_neumann_func (MultiphysicsSystem &, const std::string &expression, VariableIndex var_idx)
template<>
SharedPtr< NeumannBCAbstract > build_parsed_neumann_func (MultiphysicsSystem &system, const std::string &expression, VariableIndex var_idx)
template<>
SharedPtr< NeumannBCAbstract > build_composite_parsed_neumann_func (MultiphysicsSystem &, const std::vector< std::string > &expressions, const std::vector< VariableIndex > &var_indices)
template<>
SharedPtr< NeumannBCAbstract > build_composite_parsed_neumann_func (MultiphysicsSystem &system, const std::vector< std::string > &expressions, const std::vector< VariableIndex > &var_indices)
Additional Inherited Members
Static Public Member Functions inherited from GRINS::BCFactoryAbstract< NeumannBCContainer >
static void set_system (MultiphysicsSystem &system)
static void set_bc_ids (const std::set< BoundaryID > &bc_ids)
Boundary id for the current boundary condition section.
static void set_fe_var (const FEVariablesBase &fe_var)
Active variable for the current boundary condition.
static void set_section (const std::string &section)
Sets the current section of the input file.
static bool have_bc_type (const std::string &bc_type)
Static Public Member Functions inherited from GRINS::FactoryWithGetPot< NeumannBCContainer >
static void set_getpot (const GetPot &input)
Static Public Member Functions inherited from GRINS::FactoryAbstract< NeumannBCContainer >
static libMesh::UniquePtr< NeumannBCContainer > build (const std::string &name)
Use this method to build objects of type Base.
Static Protected Member Functions inherited from GRINS::FactoryAbstract< NeumannBCContainer >
static FactoryAbstract< NeumannBCContainer > & get_factory (const std::string &name)
Helper method that looks up the factory and returns it if present, or error if it's not.
static DerivedType & get_factory_subclass (const std::string &name)
Like get_factory, but will downcast to DerivedType.
static std::map< std::string, FactoryAbstract< NeumannBCContainer > * > & factory_map ()
Protected Attributes inherited from GRINS::NeumannBCFactoryAbstract
bool _is_homogeneous
Track if this is a homogeneous Neumann boundary condition.
Static Protected Attributes inherited from GRINS::BCFactoryAbstract< NeumannBCContainer >
static MultiphysicsSystem * _system
We store only a raw pointer here because we can't make a copy.
static const std::set< BoundaryID > * _bc_ids
BoundaryID for constructing a particular boundary condition.
static const FEVariablesBase * _fe_var
The FEVariablesBase class associated with the boundary condition being built.
static std::string _section
Static Protected Attributes inherited from GRINS::FactoryWithGetPot< NeumannBCContainer >
static const GetPot * _input
We store only a raw pointer here because we can't make a copy.
Detailed Description
template<typename FunctionType>
class GRINS::ParsedFunctionNeumannBCFactory< FunctionType >
Definition at line 36 of file parsed_function_neumann_bc_factory.h.
Constructor & Destructor Documentation
template<typename FunctionType> GRINS::ParsedFunctionNeumannBCFactory< FunctionType >::ParsedFunctionNeumannBCFactory (const std::string & bc_type_name) inline
Definition at line 41 of file parsed_function_neumann_bc_factory.h.
       : NeumannBCFactoryAbstract(bc_type_name),
         ParsedFunctionNeumannBCFactoryHelper<FunctionType>()
     {}
template<typename FunctionType> GRINS::ParsedFunctionNeumannBCFactory< FunctionType >::~ParsedFunctionNeumannBCFactory () inline
Definition at line 46 of file parsed_function_neumann_bc_factory.h.
 {};
Member Function Documentation
template<typename FunctionType> virtual SharedPtr<NeumannBCAbstract> GRINS::ParsedFunctionNeumannBCFactory< FunctionType >::build_neumann_func (const GetPot & input, MultiphysicsSystem & system, const FEVariablesBase & fe_var, const std::string & section) inline protected virtual
Builds the NeumannBCAbstract object for Neumann boundary conditions.
Subclasses should override this function to build the NeumannBCAbstract object that corresponds to the variables passed in var_names. The FEVariableBase object corresponds to the variable associated with this boundary condition, e.g. Velocity. The section arguments corresponds to the section to parse for the flux in the input file, e.g. input(section+"/"+flux). Note that for Variables with more than one component, the flux input should be a vector the size of the var_names object, even if one of the components is zero.
Implements GRINS::NeumannBCFactoryAbstract.
Definition at line 51 of file parsed_function_neumann_bc_factory.h.
References GRINS::FEVariablesBase::active_var_names(), GRINS::ParsedFunctionNeumannBCFactoryHelper< FunctionType >::build_neumman_func_common(), GRINS::NeumannBCFactoryAbstract::check_for_flux(), and GRINS::ParsedFunctionNeumannBCFactory< FunctionType >::flux_input().
     {
       std::string flux_input = this->flux_input(section);
       // Make sure flux input specified and consistent with var_names size
       this->check_for_flux(input,flux_input,fe_var.active_var_names());
       return this->build_neumman_func_common( input, system, fe_var, flux_input );
     }
template<typename FunctionType> virtual std::string GRINS::ParsedFunctionNeumannBCFactory< FunctionType >::flux_input (const std::string & section) const inline protected virtual
Reimplemented in GRINS::ParsedTractionBCFactory< FunctionType >.
Definition at line 64 of file parsed_function_neumann_bc_factory.h.
References GRINS::BoundaryConditionNames::bc_flux_var().
Referenced by GRINS::ParsedFunctionNeumannBCFactory< FunctionType >::build_neumann_func().
     { return section+"/"+BoundaryConditionNames::bc_flux_var(); }
The documentation for this class was generated from the following file:
src/boundary_conditions/include/grins/parsed_function_neumann_bc_factory.h