GRINS-0.8.0: GRINS::BoundaryConditionNames Class Reference
GRINS::BoundaryConditionNames Class Reference
Class to contain names of sections and types of boundary conditions.
#include <boundary_condition_names.h>
Static Public Member Functions
static std::string bc_section ()
Outer section name for boundary conditions section in input file.
static std::string bc_ids_var ()
Variable for list boundary ids to correspond with bc_id_name_map.
static std::string bc_id_name_map_var ()
Names of boundaries to correspond with bc_ids.
static std::string bc_flux_var ()
"Standard" input variable for Neumann flux in input file
static std::string traction_var ()
Input variable for tractions in input file.
static std::string bc_name_prefix_default ()
Default boundary name prefix if bc_id_name_map/bc_ids are not used.
static std::string axisymmetric ()
static std::string periodic ()
Detailed Description
Class to contain names of sections and types of boundary conditions.
Definition at line 31 of file boundary_condition_names.h.
Member Function Documentation
static std::string GRINS::BoundaryConditionNames::axisymmetric () inline static
Definition at line 64 of file boundary_condition_names.h.
Referenced by GRINS::DefaultBCBuilder::build_type_based_bcs().
     { return "axisymmetric"; }
static std::string GRINS::BoundaryConditionNames::bc_flux_var () inline static
"Standard" input variable for Neumann flux in input file
Definition at line 50 of file boundary_condition_names.h.
Referenced by GRINS::ParsedFunctionNeumannBCFactory< FunctionType >::flux_input().
     { return "normal_flux"; }
static std::string GRINS::BoundaryConditionNames::bc_id_name_map_var () inline static
Names of boundaries to correspond with bc_ids.
These will be the subsections of bc_section() that are parsed for the boundary condition types and values for each variable
Definition at line 46 of file boundary_condition_names.h.
References bc_section().
Referenced by GRINS::DefaultBCBuilder::parse_and_build_bc_id_map().
     { return BoundaryConditionNames::bc_section()+"/bc_id_name_map"; }
static std::string GRINS::BoundaryConditionNames::bc_ids_var () inline static
Variable for list boundary ids to correspond with bc_id_name_map.
Definition at line 40 of file boundary_condition_names.h.
References bc_section().
Referenced by GRINS::DefaultBCBuilder::parse_and_build_bc_id_map().
     { return BoundaryConditionNames::bc_section()+"/bc_ids"; }
static std::string GRINS::BoundaryConditionNames::bc_name_prefix_default () inline static
Default boundary name prefix if bc_id_name_map/bc_ids are not used.
If the user opts to not provide bc_id_name_map/bc_ids, then we'll parse for this prefix appened with the boundary id from the mesh.
Definition at line 61 of file boundary_condition_names.h.
     { return "Boundary"; }
static std::string GRINS::BoundaryConditionNames::bc_section () inline static
Outer section name for boundary conditions section in input file.
Definition at line 36 of file boundary_condition_names.h.
Referenced by bc_id_name_map_var(), bc_ids_var(), GRINS::DefaultBCBuilder::build_bcs(), GRINS::DefaultBCBuilder::build_bcs_by_var_section(), GRINS::BCBuilder::is_new_bc_input_style(), GRINSTesting::DefaultBCBuilderTest::test_parse_periodic_master_slave_ids(), and GRINSTesting::DefaultBCBuilderTest::test_parse_periodic_offset().
     { return "BoundaryConditions"; }
static std::string GRINS::BoundaryConditionNames::periodic () inline static
Definition at line 67 of file boundary_condition_names.h.
Referenced by GRINS::DefaultBCBuilder::build_type_based_bcs().
     { return "periodic"; }
static std::string GRINS::BoundaryConditionNames::traction_var () inline static
Input variable for tractions in input file.
Effectively synonomous with normal_flux, just syntax sugar.
Definition at line 55 of file boundary_condition_names.h.
Referenced by GRINS::ParsedTractionBCFactory< FunctionType >::flux_input().
     { return "traction"; }
The documentation for this class was generated from the following file:
src/boundary_conditions/include/grins/boundary_condition_names.h