GRINS-0.8.0: GRINS::CatalycityFactoryOldStyleBase Class Reference
GRINS::CatalycityFactoryOldStyleBase Class Reference abstract
#include <catalycity_factory_old_style_base.h>
Public Member Functions
CatalycityFactoryOldStyleBase (const std::string &physics_name)
~CatalycityFactoryOldStyleBase ()
Public Member Functions inherited from GRINS::CatalycityFactoryAbstract
CatalycityFactoryAbstract (const std::string &physics_name)
~CatalycityFactoryAbstract ()
Public Member Functions inherited from GRINS::FactoryWithGetPot< CatalycityBase >
FactoryWithGetPot (const std::string &name)
~FactoryWithGetPot ()
Public Member Functions inherited from GRINS::FactoryAbstract< CatalycityBase >
virtual ~FactoryAbstract ()
Static Public Member Functions
static void set_reactant (const std::string &reactant)
static void set_bc_id (const std::string &bc_id)
Static Public Member Functions inherited from GRINS::CatalycityFactoryAbstract
static void set_section (const std::string &section)
Static Public Member Functions inherited from GRINS::FactoryWithGetPot< CatalycityBase >
static void set_getpot (const GetPot &input)
Static Public Member Functions inherited from GRINS::FactoryAbstract< CatalycityBase >
static libMesh::UniquePtr< CatalycityBase > build (const std::string &name)
Use this method to build objects of type Base.
Protected Member Functions
virtual libMesh::UniquePtr< CatalycityBase > build_catalycity (const GetPot &input, const std::string &section)
virtual libMesh::UniquePtr< CatalycityBase > build_catalycity_old_style (const GetPot &input, const std::string &section, const std::string &reactant_str, const std::string &bc_id_string)=0
virtual void check_state () const
Helper function to reduce code duplication.
virtual void reset_state ()
Helper function to reduce code duplication.
Protected Member Functions inherited from GRINS::FactoryAbstract< CatalycityBase >
FactoryAbstract (const std::string &name)
Constructor is protected. Use the build() method to construct Base objects.
Static Protected Attributes
static std::string _reactant_str = std::string("DIE!")
static std::string _bc_id_str = std::string("DIE!")
Static Protected Attributes inherited from GRINS::CatalycityFactoryAbstract
static std::string _section = std::string("DIE!")
Static Protected Attributes inherited from GRINS::FactoryWithGetPot< CatalycityBase >
static const GetPot * _input
We store only a raw pointer here because we can't make a copy.
Additional Inherited Members
Static Protected Member Functions inherited from GRINS::FactoryAbstract< CatalycityBase >
static FactoryAbstract< CatalycityBase > & get_factory (const std::string &name)
Helper method that looks up the factory and returns it if present, or error if it's not.
static DerivedType & get_factory_subclass (const std::string &name)
Like get_factory, but will downcast to DerivedType.
static std::map< std::string, FactoryAbstract< CatalycityBase > * > & factory_map ()
Detailed Description
Definition at line 33 of file catalycity_factory_old_style_base.h.
Constructor & Destructor Documentation
GRINS::CatalycityFactoryOldStyleBase::CatalycityFactoryOldStyleBase (const std::string & physics_name) inline
Definition at line 37 of file catalycity_factory_old_style_base.h.
       : CatalycityFactoryAbstract(physics_name)
     {}
GRINS::CatalycityFactoryOldStyleBase::~CatalycityFactoryOldStyleBase () inline
Definition at line 41 of file catalycity_factory_old_style_base.h.
 {};
Member Function Documentation
libMesh::UniquePtr< CatalycityBase > GRINS::CatalycityFactoryOldStyleBase::build_catalycity (const GetPot & input, const std::string & section) protected virtual
Implements GRINS::CatalycityFactoryAbstract.
Definition at line 30 of file catalycity_factory_old_style_base.C.
References _bc_id_str, _reactant_str, and build_catalycity_old_style().
   {
     // State of _reactant_str, _bc_id_str verified in check_state() call in create()
     return this->build_catalycity_old_style( input, section, _reactant_str, _bc_id_str );
   }
virtual libMesh::UniquePtr<CatalycityBase> GRINS::CatalycityFactoryOldStyleBase::build_catalycity_old_style (const GetPot & input, const std::string & section, const std::string & reactant_str, const std::string & bc_id_string) protected pure virtual
Implemented in GRINS::PowerLawCatalycityFactoryOldStyle, GRINS::ArrheniusCatalycityFactoryOldStyle, and GRINS::ConstantCatalycityFactoryOldStyle.
Referenced by build_catalycity().
void GRINS::CatalycityFactoryOldStyleBase::check_state () const protected virtual
Helper function to reduce code duplication.
Reimplemented from GRINS::CatalycityFactoryAbstract.
Definition at line 37 of file catalycity_factory_old_style_base.C.
References _bc_id_str, _reactant_str, and GRINS::CatalycityFactoryAbstract::check_state().
   {
     CatalycityFactoryAbstract::check_state();
     if( _reactant_str == std::string("DIE!") )
       libmesh_error_msg("ERROR: must call set_reactant() before building Catalycity!");
     if( _bc_id_str == std::string("DIE!") )
       libmesh_error_msg("ERROR: must call set_bc_id() before building Catalycity!");
   }
void GRINS::CatalycityFactoryOldStyleBase::reset_state () protected virtual
Helper function to reduce code duplication.
Reimplemented from GRINS::CatalycityFactoryAbstract.
Definition at line 48 of file catalycity_factory_old_style_base.C.
References _bc_id_str, _reactant_str, and GRINS::CatalycityFactoryAbstract::reset_state().
   {
     CatalycityFactoryAbstract::reset_state();
     _reactant_str = std::string("DIE!");
     _bc_id_str = std::string("DIE!");
   }
static void GRINS::CatalycityFactoryOldStyleBase::set_bc_id (const std::string & bc_id) inline static
Definition at line 46 of file catalycity_factory_old_style_base.h.
References _bc_id_str.
Referenced by GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType >::build_catalycity().
     { _bc_id_str = bc_id; }
static void GRINS::CatalycityFactoryOldStyleBase::set_reactant (const std::string & reactant) inline static
Definition at line 43 of file catalycity_factory_old_style_base.h.
References _reactant_str.
Referenced by GRINS::CatalyticWallNeumannBCOldStyleFactoryBase< ImplType >::build_catalycity().
     { _reactant_str = reactant; }
Member Data Documentation
std::string GRINS::CatalycityFactoryOldStyleBase::_bc_id_str = std::string("DIE!") static protected
Definition at line 64 of file catalycity_factory_old_style_base.h.
Referenced by build_catalycity(), check_state(), reset_state(), and set_bc_id().
std::string GRINS::CatalycityFactoryOldStyleBase::_reactant_str = std::string("DIE!") static protected
Definition at line 62 of file catalycity_factory_old_style_base.h.
Referenced by build_catalycity(), check_state(), reset_state(), and set_reactant().
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/catalycity_factory_old_style_base.h
src/boundary_conditions/src/catalycity_factory_old_style_base.C