GRINS-0.8.0: GRINS::ErrorEstimatorFactoryBase Class Reference
GRINS::ErrorEstimatorFactoryBase Class Reference abstract
Builds VariableBase objects.
#include <error_estimator_factory_base.h>
Public Member Functions
ErrorEstimatorFactoryBase (const std::string &estimator_name)
~ErrorEstimatorFactoryBase ()
Public Member Functions inherited from GRINS::FactoryWithGetPot< libMesh::ErrorEstimator >
FactoryWithGetPot (const std::string &name)
~FactoryWithGetPot ()
Public Member Functions inherited from GRINS::FactoryAbstract< libMesh::ErrorEstimator >
virtual ~FactoryAbstract ()
Static Public Member Functions
static void set_system (MultiphysicsSystem &system)
static void set_estimator_options (const ErrorEstimatorOptions &estimator_options)
Static Public Member Functions inherited from GRINS::FactoryWithGetPot< libMesh::ErrorEstimator >
static void set_getpot (const GetPot &input)
Static Public Member Functions inherited from GRINS::FactoryAbstract< libMesh::ErrorEstimator >
static libMesh::UniquePtr< libMesh::ErrorEstimator > build (const std::string &name)
Use this method to build objects of type Base.
Protected Member Functions
virtual libMesh::UniquePtr< libMesh::ErrorEstimator > build_error_estimator (const GetPot &input, MultiphysicsSystem &system, const ErrorEstimatorOptions &estimator_options)=0
Subclasses implement this method for building the ErrorEstimator object.
Protected Member Functions inherited from GRINS::FactoryAbstract< libMesh::ErrorEstimator >
FactoryAbstract (const std::string &name)
Constructor is protected. Use the build() method to construct Base objects.
Static Protected Attributes
static MultiphysicsSystem * _system = NULL
Cache pointer to system.
static const ErrorEstimatorOptions * _estimator_options = NULL
Cache pointer to system.
Static Protected Attributes inherited from GRINS::FactoryWithGetPot< libMesh::ErrorEstimator >
static const GetPot * _input
We store only a raw pointer here because we can't make a copy.
Private Member Functions
virtual libMesh::UniquePtr< libMesh::ErrorEstimator > create ()
Subclasses implement the actual construction of the Base object in create().
Additional Inherited Members
Static Protected Member Functions inherited from GRINS::FactoryAbstract< libMesh::ErrorEstimator >
static FactoryAbstract< libMesh::ErrorEstimator > & get_factory (const std::string &name)
Helper method that looks up the factory and returns it if present, or error if it's not.
static DerivedType & get_factory_subclass (const std::string &name)
Like get_factory, but will downcast to DerivedType.
static std::map< std::string, FactoryAbstract< libMesh::ErrorEstimator > * > & factory_map ()
Detailed Description
Builds VariableBase objects.
Most variable classes only require a GetPot object to the constructor, but others may require more information. Subclasses can dictate the necessary behavior.
Definition at line 46 of file error_estimator_factory_base.h.
Constructor & Destructor Documentation
GRINS::ErrorEstimatorFactoryBase::ErrorEstimatorFactoryBase (const std::string & estimator_name) inline
Definition at line 49 of file error_estimator_factory_base.h.
       : FactoryWithGetPot<libMesh::ErrorEstimator>(estimator_name)
     {}
GRINS::ErrorEstimatorFactoryBase::~ErrorEstimatorFactoryBase () inline
Definition at line 53 of file error_estimator_factory_base.h.
 {};
Member Function Documentation
virtual libMesh::UniquePtr<libMesh::ErrorEstimator> GRINS::ErrorEstimatorFactoryBase::build_error_estimator (const GetPot & input, MultiphysicsSystem & system, const ErrorEstimatorOptions & estimator_options) protected pure virtual
Subclasses implement this method for building the ErrorEstimator object.
Implemented in GRINS::AdjointErrorEstimatorFactoryBase< EstimatorType >, GRINS::AdjointErrorEstimatorFactoryBase< libMesh::AdjointRefinementEstimator >, GRINS::AdjointErrorEstimatorFactoryBase< libMesh::AdjointResidualErrorEstimator >, and GRINS::ErrorEstimatorFactoryBasic< EstimatorType >.
Referenced by create().
libMesh::UniquePtr< libMesh::ErrorEstimator > GRINS::ErrorEstimatorFactoryBase::create () inline private virtual
Subclasses implement the actual construction of the Base object in create().
Implements GRINS::FactoryAbstract< libMesh::ErrorEstimator >.
Definition at line 84 of file error_estimator_factory_base.h.
References _estimator_options, GRINS::FactoryWithGetPot< libMesh::ErrorEstimator >::_input, _system, and build_error_estimator().
   {
     if( !_input )
       libmesh_error_msg("ERROR: must call set_getpot() before building ErrorEstimator!");
     if( !_system )
       libmesh_error_msg("ERROR: must call set_system() before building ErrorEstimator!");
     if( !_estimator_options )
       libmesh_error_msg("ERROR: must call set_estimator_options() before building ErrorEstimator!");
     libMesh::UniquePtr<libMesh::ErrorEstimator>
       new_estimator = this->build_error_estimator( *_input, *_system, *_estimator_options );
     libmesh_assert(new_estimator);
     return new_estimator;
   }
static void GRINS::ErrorEstimatorFactoryBase::set_estimator_options (const ErrorEstimatorOptions & estimator_options) inline static
Definition at line 58 of file error_estimator_factory_base.h.
References _estimator_options.
Referenced by GRINS::Simulation::build_error_estimator().
     { _estimator_options = &estimator_options; }
static void GRINS::ErrorEstimatorFactoryBase::set_system (MultiphysicsSystem & system) inline static
Definition at line 55 of file error_estimator_factory_base.h.
References _system.
Referenced by GRINS::Simulation::build_error_estimator().
     { _system = &system; }
Member Data Documentation
const ErrorEstimatorOptions * GRINS::ErrorEstimatorFactoryBase::_estimator_options = NULL static protected
Cache pointer to system.
We do not own this so do not delete!
Definition at line 75 of file error_estimator_factory_base.h.
Referenced by create(), and set_estimator_options().
MultiphysicsSystem * GRINS::ErrorEstimatorFactoryBase::_system = NULL static protected
Cache pointer to system.
We can't copy this so it must be a pointer. We do not own this so do not delete!
Definition at line 71 of file error_estimator_factory_base.h.
Referenced by create(), and set_system().
The documentation for this class was generated from the following files:
src/strategies/include/grins/error_estimator_factory_base.h
src/strategies/src/error_estimator_factory_base.C