GRINS-0.7.0: GRINS::ParsedViscosity Class Reference
GRINS::ParsedViscosity Class Reference
#include <parsed_viscosity.h>
Public Member Functions
ParsedViscosity (const GetPot &input, const std::string &material)
Constructor with specified material.
ParsedViscosity (const GetPot &input)
Deprecated constructor.
virtual ~ParsedViscosity ()
Public Member Functions inherited from GRINS::ParsedPropertyBase
ParsedPropertyBase ()
virtual ~ParsedPropertyBase ()
libMesh::Real operator() (AssemblyContext &context, unsigned int qp) const
libMesh::Real operator() (const libMesh::Point &p, const libMesh::Real time)
virtual void init (libMesh::FEMSystem *)
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Public Member Functions inherited from GRINS::ViscosityBase
ViscosityBase ()
virtual ~ViscosityBase ()
Private Member Functions
ParsedViscosity ()
Additional Inherited Members
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Member Functions inherited from GRINS::ParsedPropertyBase
bool check_func_nonzero (const std::string &function) const
Returns true if function string is nonzero.
Protected Member Functions inherited from GRINS::ViscosityBase
void check_input_consistency (const GetPot &input, const std::string &material) const
void old_mu_warning () const
Protected Attributes inherited from GRINS::ParsedPropertyBase
libMesh::ParsedFunction< libMesh::Number > _func
Detailed Description
Definition at line 39 of file parsed_viscosity.h.
Constructor & Destructor Documentation
GRINS::ParsedViscosity::ParsedViscosity (const GetPot & input, const std::string & material)
Constructor with specified material.
Will look in the input file for [Materials/material/Viscosity/value] for the value of viscosity.
Definition at line 64 of file parsed_viscosity.C.
References GRINS::ParsedPropertyBase::_func, GRINS::ParsedPropertyBase::check_func_nonzero(), GRINS::ViscosityBase::check_input_consistency(), GRINS::ViscosityBase::old_mu_warning(), and GRINS::ParameterUser::set_parameter().
     : ParameterUser("ParsedViscosity"),
       ViscosityBase()
   {
     this->check_input_consistency(input,material);
     std::string viscosity_function = "0";
     // If we have the new version, we parse that
     if( input.have_variable("Materials/"+material+"/Viscosity/value") )
       {
         this->set_parameter(this->_func, input,
                             "Materials/"+material+"/Viscosity/value",
                             "DIE!");
         viscosity_function = input("Materials/"+material+"/Viscosity/value",std::string("0"));
       }
     // If we have the old DEPRECATED version, use that
     else if( input.have_variable("Materials/Viscosity/mu") )
       {
         this->old_mu_warning();
         this->set_parameter(this->_func, input,
                             "Materials/Viscosity/mu",
                             "DIE!");
         viscosity_function = input("Materials/Viscosity/mu",std::string("0"));
       }
     // If we don't have either, that's an error
     else
       {
         libmesh_error_msg("Error: Could not find either Materials/"+material+"/Viscosity/value or Materials/Viscosity/mu");
       }
     if( !this->check_func_nonzero(viscosity_function) )
       {
         libmesh_error_msg("ERROR: Detected '0' function for ParsedConductivity!");
       }
   }
GRINS::ParsedViscosity::ParsedViscosity (const GetPot & input)
Deprecated constructor.
Definition at line 39 of file parsed_viscosity.C.
References GRINS::ParsedPropertyBase::_func, GRINS::ParsedPropertyBase::check_func_nonzero(), grins_warning, and GRINS::ParameterUser::set_parameter().
      : ParsedPropertyBase(),
        ParameterUser("ParsedViscosity"),
        ViscosityBase()
    {
      // Warning about this constructor being deprecated
      {
        std::string warning = "WARNING: Use of this constructor is DEPRECATED.\n";
        warning += "         Please update to use constructor with input material name.\n";
        grins_warning(warning);
      }
     this->set_parameter(this->_func, input,
                         "Materials/Viscosity/mu",
                         "DIE!");
     std::string viscosity_function = input("Materials/Viscosity/mu",std::string("0"));
     if( !this->check_func_nonzero(viscosity_function) )
       {
         libmesh_error_msg("ERROR: Detected '0' function for ParsedConductivity!");
       }
   }
GRINS::ParsedViscosity::~ParsedViscosity () virtual
Definition at line 104 of file parsed_viscosity.C.
   {
     return;
   }
GRINS::ParsedViscosity::ParsedViscosity () private
The documentation for this class was generated from the following files:
src/properties/include/grins/parsed_viscosity.h
src/properties/src/parsed_viscosity.C