GRINS-0.8.0: GRINS::DirichletBCFactoryFunctionOldStyleBase< FunctionType > Class Template Reference
GRINS::DirichletBCFactoryFunctionOldStyleBase< FunctionType > Class Template Reference
#include <dirichlet_bc_factory_function_old_style_base.h>
Public Member Functions
DirichletBCFactoryFunctionOldStyleBase (const std::string &bc_type_name)
~DirichletBCFactoryFunctionOldStyleBase ()
Public Member Functions inherited from GRINS::DirichletBCFactoryFunctionBase< FunctionType >
DirichletBCFactoryFunctionBase (const std::string &bc_type_name)
~DirichletBCFactoryFunctionBase ()
Public Member Functions inherited from GRINS::DirichletBCFactoryAbstract
DirichletBCFactoryAbstract (const std::string &bc_type_name)
~DirichletBCFactoryAbstract ()
Public Member Functions inherited from GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >
BCFactoryAbstract (const std::string &bc_type_name)
~BCFactoryAbstract ()
Public Member Functions inherited from GRINS::FactoryWithGetPot< libMesh::DirichletBoundary >
FactoryWithGetPot (const std::string &name)
~FactoryWithGetPot ()
Public Member Functions inherited from GRINS::FactoryAbstract< libMesh::DirichletBoundary >
virtual ~FactoryAbstract ()
Static Public Member Functions
static void set_value_var_old_style (const std::string &value_var)
Input variable for parsing old style.
static void set_value_index_old_style (unsigned int idx)
Input variable index for parsing old style.
static void set_var_names_old_style (const std::vector< std::string > &var_names)
Static Public Member Functions inherited from GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >
static void set_system (MultiphysicsSystem &system)
static void set_bc_ids (const std::set< BoundaryID > &bc_ids)
Boundary id for the current boundary condition section.
static void set_fe_var (const FEVariablesBase &fe_var)
Active variable for the current boundary condition.
static void set_section (const std::string &section)
Sets the current section of the input file.
static bool have_bc_type (const std::string &bc_type)
Static Public Member Functions inherited from GRINS::FactoryWithGetPot< libMesh::DirichletBoundary >
static void set_getpot (const GetPot &input)
Static Public Member Functions inherited from GRINS::FactoryAbstract< libMesh::DirichletBoundary >
static libMesh::UniquePtr< libMesh::DirichletBoundary > build (const std::string &name)
Use this method to build objects of type Base.
Protected Member Functions
virtual void check_state () const
Helper function.
virtual void reset_state ()
Helper function.
virtual const std::vector< std::string > & get_var_names () const
Helper function that can be overridded in subclasses.
Protected Member Functions inherited from GRINS::DirichletBCFactoryFunctionBase< FunctionType >
virtual libMesh::UniquePtr< FunctionType > build_func (const GetPot &input, MultiphysicsSystem &system, std::vector< std::string > &var_names, const std::string &section)=0
Builds the FunctionBase object for boundary condition.
libMesh::UniquePtr< libMesh::DirichletBoundary > make_dirichlet_boundary (const std::set< BoundaryID > &bc_ids, const libMesh::System &system, libMesh::UniquePtr< FunctionType > &func, const std::vector< VariableIndex > &var_indices)
Dispatch, based on FunctionType, to the correct DirchletBoundary construction.
template<>
libMesh::UniquePtr< libMesh::DirichletBoundary > make_dirichlet_boundary (const std::set< BoundaryID > &bc_ids, const libMesh::System &, libMesh::UniquePtr< libMesh::FunctionBase< libMesh::Number > > &func, const std::vector< VariableIndex > &var_indices)
template<>
libMesh::UniquePtr< libMesh::DirichletBoundary > make_dirichlet_boundary (const std::set< BoundaryID > &bc_ids, const libMesh::System &system, libMesh::UniquePtr< libMesh::FEMFunctionBase< libMesh::Number > > &func, const std::vector< VariableIndex > &var_indices)
Protected Member Functions inherited from GRINS::DirichletBCFactoryAbstract
void check_for_vars (const GetPot &input, const std::string &section, const std::vector< std::string > &var_names, std::set< std::string > *vars_found=NULL)
Helper function.
Protected Member Functions inherited from GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >
void check_for_multiple_expressions (const GetPot &input, const std::string &section, const std::string &var_name) const
Ensure that there is only one expression for the [Section/var_name] variable.
void build_var_indices (const MultiphysicsSystem &system, const std::vector< std::string > &var_names, std::vector< VariableIndex > &var_indices) const
Protected Member Functions inherited from GRINS::FactoryAbstract< libMesh::DirichletBoundary >
FactoryAbstract (const std::string &name)
Constructor is protected. Use the build() method to construct Base objects.
Static Protected Attributes
static std::string _value_var_old_style = std::string("DIE!")
static unsigned int _value_idx_old_style = libMesh::invalid_uint
static const std::vector< std::string > * _var_names_old_style = NULL
Static Protected Attributes inherited from GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >
static MultiphysicsSystem * _system
We store only a raw pointer here because we can't make a copy.
static const std::set< BoundaryID > * _bc_ids
BoundaryID for constructing a particular boundary condition.
static const FEVariablesBase * _fe_var
The FEVariablesBase class associated with the boundary condition being built.
static std::string _section
Static Protected Attributes inherited from GRINS::FactoryWithGetPot< libMesh::DirichletBoundary >
static const GetPot * _input
We store only a raw pointer here because we can't make a copy.
Additional Inherited Members
Static Protected Member Functions inherited from GRINS::FactoryAbstract< libMesh::DirichletBoundary >
static FactoryAbstract< libMesh::DirichletBoundary > & get_factory (const std::string &name)
Helper method that looks up the factory and returns it if present, or error if it's not.
static DerivedType & get_factory_subclass (const std::string &name)
Like get_factory, but will downcast to DerivedType.
static std::map< std::string, FactoryAbstract< libMesh::DirichletBoundary > * > & factory_map ()
Detailed Description
template<typename FunctionType>
class GRINS::DirichletBCFactoryFunctionOldStyleBase< FunctionType >
Definition at line 34 of file dirichlet_bc_factory_function_old_style_base.h.
Constructor & Destructor Documentation
template<typename FunctionType> GRINS::DirichletBCFactoryFunctionOldStyleBase< FunctionType >::DirichletBCFactoryFunctionOldStyleBase (const std::string & bc_type_name) inline
Definition at line 38 of file dirichlet_bc_factory_function_old_style_base.h.
       : DirichletBCFactoryFunctionBase<FunctionType>(bc_type_name)
     {}
template<typename FunctionType> GRINS::DirichletBCFactoryFunctionOldStyleBase< FunctionType >::~DirichletBCFactoryFunctionOldStyleBase () inline
Definition at line 42 of file dirichlet_bc_factory_function_old_style_base.h.
 {};
Member Function Documentation
template<typename FunctionType > void GRINS::DirichletBCFactoryFunctionOldStyleBase< FunctionType >::check_state () const inline protected virtual
Helper function.
Reimplemented from GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >.
Definition at line 78 of file dirichlet_bc_factory_function_old_style_base.h.
References GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >::check_state().
   {
     DirichletBCFactoryAbstract::check_state();
     if( this->_value_var_old_style == std::string("DIE!") )
       libmesh_error_msg("ERROR: must call set_value_var_old_style() before building boundary condition!");
     if( this->_value_idx_old_style == libMesh::invalid_uint )
       libmesh_error_msg("ERROR: must call set_value_index_old_style() before building boundary condition!");
     if( !this->_var_names_old_style )
       libmesh_error_msg("ERROR: must call set_var_names_old_style() before building boundary condition!");
   }
template<typename FunctionType> virtual const std::vector<std::string>& GRINS::DirichletBCFactoryFunctionOldStyleBase< FunctionType >::get_var_names () const inline protected virtual
Helper function that can be overridded in subclasses.
Mainly for backward compatibility with OldStyle parsing.
Reimplemented from GRINS::DirichletBCFactoryFunctionBase< FunctionType >.
Definition at line 65 of file dirichlet_bc_factory_function_old_style_base.h.
     { return *(this->_var_names_old_style); }
template<typename FunctionType > void GRINS::DirichletBCFactoryFunctionOldStyleBase< FunctionType >::reset_state () inline protected virtual
Helper function.
Reimplemented from GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >.
Definition at line 94 of file dirichlet_bc_factory_function_old_style_base.h.
References GRINS::BCFactoryAbstract< libMesh::DirichletBoundary >::reset_state().
   {
     DirichletBCFactoryAbstract::reset_state();
     this->_value_var_old_style = std::string("DIE!");
     this->_value_idx_old_style = libMesh::invalid_uint;
     this->_var_names_old_style = NULL;
   }
template<typename FunctionType> static void GRINS::DirichletBCFactoryFunctionOldStyleBase< FunctionType >::set_value_index_old_style (unsigned int idx) inline static
Input variable index for parsing old style.
Deprecated, only used for backward compatibility.
Definition at line 51 of file dirichlet_bc_factory_function_old_style_base.h.
Referenced by GRINS::OldStyleBCBuilder::set_dirichlet_bc_factory_old_style_quantities().
     { _value_idx_old_style = idx; }
template<typename FunctionType> static void GRINS::DirichletBCFactoryFunctionOldStyleBase< FunctionType >::set_value_var_old_style (const std::string & value_var) inline static
Input variable for parsing old style.
Deprecated, only used for backward compatibility.
Definition at line 46 of file dirichlet_bc_factory_function_old_style_base.h.
Referenced by GRINS::OldStyleBCBuilder::set_dirichlet_bc_factory_old_style_quantities().
     { _value_var_old_style = value_var; }
template<typename FunctionType> static void GRINS::DirichletBCFactoryFunctionOldStyleBase< FunctionType >::set_var_names_old_style (const std::vector< std::string > & var_names) inline static
Definition at line 54 of file dirichlet_bc_factory_function_old_style_base.h.
Referenced by GRINS::OldStyleBCBuilder::set_dirichlet_bc_factory_old_style_quantities().
     { _var_names_old_style = &var_names; }
Member Data Documentation
template<typename FunctionType> unsigned int GRINS::DirichletBCFactoryFunctionOldStyleBase< FunctionType >::_value_idx_old_style = libMesh::invalid_uint static protected
Definition at line 70 of file dirichlet_bc_factory_function_old_style_base.h.
Referenced by GRINS::DirichletBCFactoryFunctionOldStyleBase< libMesh::FunctionBase< libMesh::Number > >::set_value_index_old_style().
template<typename FunctionType> std::string GRINS::DirichletBCFactoryFunctionOldStyleBase< FunctionType >::_value_var_old_style = std::string("DIE!") static protected
Definition at line 68 of file dirichlet_bc_factory_function_old_style_base.h.
Referenced by GRINS::DirichletBCFactoryFunctionOldStyleBase< libMesh::FunctionBase< libMesh::Number > >::set_value_var_old_style().
template<typename FunctionType> const std::vector< std::string > * GRINS::DirichletBCFactoryFunctionOldStyleBase< FunctionType >::_var_names_old_style = NULL static protected
Definition at line 72 of file dirichlet_bc_factory_function_old_style_base.h.
Referenced by GRINS::DirichletBCFactoryFunctionOldStyleBase< libMesh::FunctionBase< libMesh::Number > >::get_var_names(), and GRINS::DirichletBCFactoryFunctionOldStyleBase< libMesh::FunctionBase< libMesh::Number > >::set_var_names_old_style().
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/dirichlet_bc_factory_function_old_style_base.h
src/boundary_conditions/src/dirichlet_bc_factory_function_old_style_base.C