GRINS-0.8.0: GRINS::SpeciesMassFractionsVariable Class Reference
GRINS::SpeciesMassFractionsVariable Class Reference
#include <multicomponent_variable.h>
Public Member Functions
SpeciesMassFractionsVariable (const std::vector< std::string > &var_names, const std::vector< VariableIndex > &var_indices, const std::string &prefix, const std::string &material, const std::set< libMesh::subdomain_id_type > &subdomain_ids)
virtual ~SpeciesMassFractionsVariable ()
unsigned int n_species () const
VariableIndex species (unsigned int species) const
const std::string & material () const
const std::string & prefix () const
Public Member Functions inherited from GRINS::MulticomponentVariable
MulticomponentVariable (const std::vector< std::string > &var_names, const std::vector< VariableIndex > &var_indices, const std::set< libMesh::subdomain_id_type > &subdomain_ids)
virtual ~MulticomponentVariable ()
unsigned int dim () const
Number of components.
VariableIndex idx_from_component (unsigned int component) const
Public Member Functions inherited from GRINS::FEVariablesBase
FEVariablesBase (const std::vector< std::string > &var_names, const std::vector< VariableIndex > &var_indices, const std::set< libMesh::subdomain_id_type > &subdomain_ids)
virtual ~FEVariablesBase ()
void set_is_constraint_var (bool is_constraint_var)
Set whether or not this is a "constraint" variable.
bool is_constraint_var () const
void set_neumann_bc_is_positive (bool is_positive)
Reset whetever Neumann bc is postive or not.
libMesh::Real neumann_bc_sign () const
const std::vector< std::string > & active_var_names () const
Return the var names that are active from this class.
const std::vector< VariableIndex > & var_indices () const
const std::set< libMesh::subdomain_id_type > & subdomain_ids () const
Private Member Functions
SpeciesMassFractionsVariable ()
Private Attributes
std::string _prefix
std::string _material
Additional Inherited Members
Protected Attributes inherited from GRINS::FEVariablesBase
std::vector< VariableIndex > _vars
std::vector< std::string > _var_names
bool _is_constraint_var
Tracks whether this is a constraint variable.
libMesh::Real _neumann_bc_sign
Track the sign of the Neumann BC term. Defaults to 1.0.
std::set< libMesh::subdomain_id_type > _subdomain_ids
Detailed Description
Definition at line 60 of file multicomponent_variable.h.
Constructor & Destructor Documentation
GRINS::SpeciesMassFractionsVariable::SpeciesMassFractionsVariable (const std::vector< std::string > & var_names, const std::vector< VariableIndex > & var_indices, const std::string & prefix, const std::string & material, const std::set< libMesh::subdomain_id_type > & subdomain_ids) inline
Definition at line 64 of file multicomponent_variable.h.
       : MulticomponentVariable(var_names,var_indices,subdomain_ids),
         _prefix(prefix),
         _material(material)
     {}
virtual GRINS::SpeciesMassFractionsVariable::~SpeciesMassFractionsVariable () inline virtual
Definition at line 74 of file multicomponent_variable.h.
 {}
GRINS::SpeciesMassFractionsVariable::SpeciesMassFractionsVariable () private
Member Function Documentation
const std::string& GRINS::SpeciesMassFractionsVariable::material () const inline
Definition at line 82 of file multicomponent_variable.h.
References _material.
Referenced by GRINS::MoleFractionsDirichletBCFactory::add_found_vars(), GRINS::PrescribedMoleFractionsDirichletOldStyleBCFactory::convert_mole_fracs_and_add_to_func(), and GRINS::CatalyticWallNeumannBCFactoryCommon< ImplType >::extract_material().
     { return _material; }
unsigned int GRINS::SpeciesMassFractionsVariable::n_species () const inline
Definition at line 76 of file multicomponent_variable.h.
References GRINS::MulticomponentVariable::dim().
     { return this->dim(); }
const std::string& GRINS::SpeciesMassFractionsVariable::prefix () const inline
Definition at line 85 of file multicomponent_variable.h.
References _prefix.
Referenced by GRINS::MoleFractionsDirichletBCFactory::add_mole_frac_to_mass_frac(), and GRINS::MoleFractionsDirichletBCFactory::set_vars_to_search_for().
     { return _prefix; }
VariableIndex GRINS::SpeciesMassFractionsVariable::species (unsigned int species) const inline
Definition at line 79 of file multicomponent_variable.h.
References GRINS::MulticomponentVariable::idx_from_component().
Referenced by GRINS::MoleFractionsDirichletBCFactory::add_mole_frac_to_mass_frac(), GRINS::PrescribedMoleFractionsDirichletOldStyleBCFactory::convert_mole_fracs_and_add_to_func(), GRINS::ReactingLowMachNavierStokesAbstract::init_context(), GRINS::ReactingLowMachNavierStokesAbstract::mass_fractions(), GRINS::ReactingLowMachNavierStokesAbstract::set_time_evolving_vars(), and GRINSTesting::SpectroscopicAbsorptionTest::Y_elem_derivative().
     { return this->idx_from_component(species); }
Member Data Documentation
std::string GRINS::SpeciesMassFractionsVariable::_material private
Definition at line 94 of file multicomponent_variable.h.
Referenced by material().
std::string GRINS::SpeciesMassFractionsVariable::_prefix private
Definition at line 92 of file multicomponent_variable.h.
Referenced by prefix().
The documentation for this class was generated from the following file:
src/variables/include/grins/multicomponent_variable.h