GRINS-0.8.0: GRINSTesting::AirTestBase Class Reference
GRINSTesting::AirTestBase Class Reference
Public Member Functions
void init_air_test (unsigned int &N2_idx, unsigned int &O2_idx, unsigned int &N_idx, unsigned int &O_idx, unsigned int &NO_idx, std::vector< unsigned int > &active_species)
Detailed Description
Definition at line 44 of file air_5sp.C.
Member Function Documentation
void GRINSTesting::AirTestBase::init_air_test (unsigned int & N2_idx, unsigned int & O2_idx, unsigned int & N_idx, unsigned int & O_idx, unsigned int & NO_idx, std::vector< unsigned int > & active_species) inline
Definition at line 48 of file air_5sp.C.
Referenced by GRINSTesting::AirNASA9Thermo::AirNASA9Thermo(), GRINSTesting::AirKineticsTestBase::init_air_kinetics(), GRINSTesting::AntiochAirNASA9ThermoTest::setUp(), and GRINSTesting::CanteraAirNASA9ThermoTest::setUp().
     {
       N2_idx = 0;
       O2_idx = 1;
       O_idx  = 4;
       N_idx  = 3;
       NO_idx = 2;
       active_species.resize(5);
       active_species[0] = N2_idx;
       active_species[1] = O2_idx;
       active_species[2] = NO_idx;
       active_species[3] = N_idx;
       active_species[4] = O_idx;
     }
The documentation for this class was generated from the following file:
test/interface/air_5sp.C