GRINS-0.8.0: GRINS::QoIOutput Class Reference
GRINS::QoIOutput Class Reference
Encapsulate QoI output flags and functionality.
#include <qoi_output.h>
Public Member Functions
QoIOutput (const GetPot &input)
~QoIOutput ()
bool output_qoi_set () const
Function to query whether any input options set to output qoi.
void output_qois (const CompositeQoI &qois, const libMesh::Parallel::Communicator &comm) const
Output the QoI values for all triggered output modes.
Protected Attributes
bool _output_to_display
bool _output_to_file
std::string _file_prefix
Detailed Description
Encapsulate QoI output flags and functionality.
This class handles both the parsing of the options for triggering QoI output and implements the functionality for outputting the QoIs (which is really just a wrapper around calling output from QoI classes). Currently, the user can enable printing the QoI info to the display (std::cout) and to a file by specifing the filename in the corresponding input option.
Definition at line 52 of file qoi_output.h.
Constructor & Destructor Documentation
GRINS::QoIOutput::QoIOutput (const GetPot & input)
Definition at line 43 of file qoi_output.C.
References _output_to_display, GRINS::OutputParsing::display_section(), grins_warning, GRINS::OutputParsing::output_section(), and GRINS::QoIOptions::output_to_display().
     : _output_to_display( input(OutputParsing::output_section()+"/"+OutputParsing::display_section()+"/"+QoIOptions::output_to_display(), false) ),
       _output_to_file( input.have_variable(OutputParsing::output_section()+"/"+QoIOptions::qoi_section()+"/"+QoIOptions::default_file_prefix()) ),
       _file_prefix( input(OutputParsing::output_section()+"/"+QoIOptions::qoi_section()+"/"+QoIOptions::default_file_prefix(), "nofile") )
   {
     if( input.have_variable("screen-options/print_qoi") )
       {
         std::string warning;
         warning = "WARNING: Option screen-options/print_qoi is DEPRECATED!\n";
         warning += "         Please update input to use ";
         warning += OutputParsing::output_section()+"/"+OutputParsing::display_section()+"/"+QoIOptions::output_to_display()+"\n";
         grins_warning(warning);
         _output_to_display = input("screen-options/print_qoi", false);
       }
   }
GRINS::QoIOutput::~QoIOutput () inline
Definition at line 58 of file qoi_output.h.
 {}
Member Function Documentation
bool GRINS::QoIOutput::output_qoi_set () const inline
Function to query whether any input options set to output qoi.
Returns true if user requested to output QoI in any one of the avaiable modes, false otherwise.
Definition at line 63 of file qoi_output.h.
References _output_to_display, and _output_to_file.
     { return (_output_to_display || _output_to_file ); }
void GRINS::QoIOutput::output_qois (const CompositeQoI & qois, const libMesh::Parallel::Communicator & comm) const
Output the QoI values for all triggered output modes.
This function assumes that the qoi values have been assembled by the System.
Definition at line 60 of file qoi_output.C.
References _file_prefix, _output_to_display, _output_to_file, and GRINS::CompositeQoI::output_qoi().
   {
     if( _output_to_display )
       {
         std::cout << "==========================================================" << std::endl;
         qois.output_qoi( std::cout );
         std::cout << "==========================================================" << std::endl;
       }
     if( _output_to_file )
       {
         if( comm.rank() == 0 )
           {
             std::ofstream output;
             output.open( _file_prefix+".dat" );
             qois.output_qoi(output);
             output.close();
           }
       }
   }
Member Data Documentation
std::string GRINS::QoIOutput::_file_prefix protected
Definition at line 77 of file qoi_output.h.
Referenced by output_qois().
bool GRINS::QoIOutput::_output_to_display protected
Definition at line 73 of file qoi_output.h.
Referenced by output_qoi_set(), output_qois(), and QoIOutput().
bool GRINS::QoIOutput::_output_to_file protected
Definition at line 75 of file qoi_output.h.
Referenced by output_qoi_set(), and output_qois().
The documentation for this class was generated from the following files:
src/qoi/include/grins/qoi_output.h
src/qoi/src/qoi_output.C