GRINS-0.8.0: GRINS::ArrheniusCatalycity Class Reference
GRINS::ArrheniusCatalycity Class Reference
#include <arrhenius_catalycity.h>
Public Member Functions
ArrheniusCatalycity (const libMesh::Real gamma0, const libMesh::Real Ta)
virtual ~ArrheniusCatalycity ()
virtual libMesh::Real operator() (const libMesh::Real T) const
virtual libMesh::Real dT (const libMesh::Real T) const
virtual void set_params (const std::vector< libMesh::Real > &params)
virtual CatalycityBase * clone () const
Creates a new copy of the current class.
virtual void set_parameters (const GetPot &input, const std::string &param_base)
Sets parameters for use in sensitivity analysis.
Public Member Functions inherited from GRINS::CatalycityBase
CatalycityBase ()
virtual ~CatalycityBase ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Attributes
libMesh::Real _gamma0
libMesh::Real _Ta
Private Member Functions
ArrheniusCatalycity ()
Additional Inherited Members
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Detailed Description
Definition at line 33 of file arrhenius_catalycity.h.
Constructor & Destructor Documentation
GRINS::ArrheniusCatalycity::ArrheniusCatalycity (const libMesh::Real gamma0, const libMesh::Real Ta)
Definition at line 33 of file arrhenius_catalycity.C.
     : _gamma0(gamma0),
       _Ta(Ta)
   {
     return;
   }
GRINS::ArrheniusCatalycity::~ArrheniusCatalycity () virtual
Definition at line 41 of file arrhenius_catalycity.C.
   {
     return;
   }
GRINS::ArrheniusCatalycity::ArrheniusCatalycity () private
Referenced by clone().
Member Function Documentation
CatalycityBase * GRINS::ArrheniusCatalycity::clone () const virtual
Creates a new copy of the current class.
A raw pointer is returned and it is assumed the user will take ownership and worry about memory management.
Implements GRINS::CatalycityBase.
Definition at line 67 of file arrhenius_catalycity.C.
References ArrheniusCatalycity().
   {
     return new ArrheniusCatalycity( *this );
   }
libMesh::Real GRINS::ArrheniusCatalycity::dT (const libMesh::Real T) const virtual
Implements GRINS::CatalycityBase.
Definition at line 51 of file arrhenius_catalycity.C.
References _gamma0, and _Ta.
Referenced by main().
   {
     return _gamma0*_Ta/(T*T)*std::exp(-_Ta/T);
   }
libMesh::Real GRINS::ArrheniusCatalycity::operator() (const libMesh::Real T) const virtual
Implements GRINS::CatalycityBase.
Definition at line 46 of file arrhenius_catalycity.C.
References _gamma0, and _Ta.
   {
     return _gamma0*std::exp(-_Ta/T);
   }
void GRINS::ArrheniusCatalycity::set_parameters (const GetPot & input, const std::string & param_base) virtual
Sets parameters for use in sensitivity analysis.
Implements GRINS::CatalycityBase.
Definition at line 72 of file arrhenius_catalycity.C.
References _gamma0, _Ta, and GRINS::ParameterUser::set_parameter().
   {
     std::string gamma0_str = param_base+"gamma0";
     this->set_parameter(_gamma0,input,gamma0_str,_gamma0);
     std::string Ta_str = param_base+"Ta";
     this->set_parameter(_Ta,input,Ta_str,_Ta);
   }
void GRINS::ArrheniusCatalycity::set_params (const std::vector< libMesh::Real > & params) virtual
Implements GRINS::CatalycityBase.
Definition at line 56 of file arrhenius_catalycity.C.
References _gamma0, and _Ta.
Referenced by main().
   {
     libmesh_assert_equal_to( params.size(), 2 );
     _gamma0 = params[0];
     _Ta = params[1];
     return;
   }
Member Data Documentation
libMesh::Real GRINS::ArrheniusCatalycity::_gamma0 protected
Definition at line 56 of file arrhenius_catalycity.h.
Referenced by dT(), operator()(), set_parameters(), and set_params().
libMesh::Real GRINS::ArrheniusCatalycity::_Ta protected
Definition at line 58 of file arrhenius_catalycity.h.
Referenced by dT(), operator()(), set_parameters(), and set_params().
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/arrhenius_catalycity.h
src/boundary_conditions/src/arrhenius_catalycity.C