GRINS-0.8.0: GRINSTesting::AntiochMixtureBuilderBaseTest Class Reference
GRINSTesting::AntiochMixtureBuilderBaseTest Class Reference
Public Member Functions
CPPUNIT_TEST_SUITE (AntiochMixtureBuilderBaseTest)
CPPUNIT_TEST (test_build_chem_mix)
CPPUNIT_TEST (test_build_reaction_set)
CPPUNIT_TEST (test_build_nasa_thermo_mix_cea)
CPPUNIT_TEST (test_parse_min_T)
CPPUNIT_TEST (test_parse_clip_negative_rho)
CPPUNIT_TEST_SUITE_END ()
void setUp ()
void test_build_chem_mix ()
void test_build_reaction_set ()
void test_build_nasa_thermo_mix_cea ()
void test_parse_min_T ()
void test_parse_clip_negative_rho ()
Private Attributes
libMesh::UniquePtr< GetPot > _input
Detailed Description
Definition at line 42 of file antioch_mixture_builder_test.C.
Member Function Documentation
GRINSTesting::AntiochMixtureBuilderBaseTest::CPPUNIT_TEST (test_build_chem_mix)
GRINSTesting::AntiochMixtureBuilderBaseTest::CPPUNIT_TEST (test_build_reaction_set)
GRINSTesting::AntiochMixtureBuilderBaseTest::CPPUNIT_TEST (test_build_nasa_thermo_mix_cea)
GRINSTesting::AntiochMixtureBuilderBaseTest::CPPUNIT_TEST (test_parse_min_T)
GRINSTesting::AntiochMixtureBuilderBaseTest::CPPUNIT_TEST (test_parse_clip_negative_rho)
GRINSTesting::AntiochMixtureBuilderBaseTest::CPPUNIT_TEST_SUITE (AntiochMixtureBuilderBaseTest)
GRINSTesting::AntiochMixtureBuilderBaseTest::CPPUNIT_TEST_SUITE_END ()
void GRINSTesting::AntiochMixtureBuilderBaseTest::setUp () inline
Definition at line 57 of file antioch_mixture_builder_test.C.
References _input.
     {
       std::string input_file = std::string(GRINS_TEST_SRCDIR)+"/input_files/antioch.in";
       _input.reset( new GetPot(input_file) );
     }
void GRINSTesting::AntiochMixtureBuilderBaseTest::test_build_chem_mix () inline
Definition at line 63 of file antioch_mixture_builder_test.C.
References _input, and GRINS::AntiochMixtureBuilderBase::build_chem_mix().
     {
       GRINS::AntiochMixtureBuilderBase builder;
       libMesh::UniquePtr<Antioch::ChemicalMixture<libMesh::Real> > chem_mix
         = builder.build_chem_mix(*_input, "TestMaterial");
       // Just a couple of basic tests for the parsed ChemicalMixture
       CPPUNIT_ASSERT_EQUAL( 5, (int)chem_mix->n_species() );
       const std::vector<Antioch::ChemicalSpecies<libMesh::Real>*> & all_species =
         chem_mix->chemical_species();
       CPPUNIT_ASSERT_EQUAL( 5, (int)all_species.size() );
     }
void GRINSTesting::AntiochMixtureBuilderBaseTest::test_build_nasa_thermo_mix_cea () inline
Definition at line 93 of file antioch_mixture_builder_test.C.
References _input, GRINS::AntiochMixtureBuilderBase::build_chem_mix(), and GRINS::AntiochMixtureBuilderBase::build_nasa_thermo_mix().
     {
       GRINS::AntiochMixtureBuilderBase builder;
       libMesh::UniquePtr<Antioch::ChemicalMixture<libMesh::Real> > chem_mix
         = builder.build_chem_mix(*_input, "TestMaterial");
       libMesh::UniquePtr<Antioch::NASAThermoMixture<libMesh::Real,Antioch::CEACurveFit<libMesh::Real> > >
         nasa_mix =
         builder.build_nasa_thermo_mix<Antioch::CEACurveFit<libMesh::Real> >(*_input, "TestMaterial", *chem_mix);
       CPPUNIT_ASSERT(nasa_mix->check());
     }
void GRINSTesting::AntiochMixtureBuilderBaseTest::test_build_reaction_set () inline
Definition at line 79 of file antioch_mixture_builder_test.C.
References _input, GRINS::AntiochMixtureBuilderBase::build_chem_mix(), and GRINS::AntiochMixtureBuilderBase::build_reaction_set().
     {
       GRINS::AntiochMixtureBuilderBase builder;
       libMesh::UniquePtr<Antioch::ChemicalMixture<libMesh::Real> > chem_mix
         = builder.build_chem_mix(*_input, "TestMaterial");
       libMesh::UniquePtr<Antioch::ReactionSet<libMesh::Real> > reaction_set
         = builder.build_reaction_set(*_input, "TestMaterial", *chem_mix);
       CPPUNIT_ASSERT_EQUAL( 5, (int)reaction_set->n_species() );
       CPPUNIT_ASSERT_EQUAL( 5, (int)reaction_set->n_reactions() );
     }
void GRINSTesting::AntiochMixtureBuilderBaseTest::test_parse_clip_negative_rho () inline
Definition at line 117 of file antioch_mixture_builder_test.C.
References _input, and GRINS::AntiochMixtureBuilderBase::parse_clip_negative_rho().
     {
       GRINS::AntiochMixtureBuilderBase builder;
       bool clip_negative_rho_exact = true;
       bool clip_negative_rho = builder.parse_clip_negative_rho( *_input, "TestMaterial" );
       CPPUNIT_ASSERT_EQUAL( clip_negative_rho_exact, clip_negative_rho );
     }
void GRINSTesting::AntiochMixtureBuilderBaseTest::test_parse_min_T () inline
Definition at line 107 of file antioch_mixture_builder_test.C.
References _input, and GRINS::AntiochMixtureBuilderBase::parse_min_T().
     {
       GRINS::AntiochMixtureBuilderBase builder;
       libMesh::Real min_T_exact = 114.15;
       libMesh::Real min_T = builder.parse_min_T( *_input, "TestMaterial" );
       CPPUNIT_ASSERT_DOUBLES_EQUAL( min_T_exact, min_T, std::numeric_limits<libMesh::Real>::epsilon() );
     }
Member Data Documentation
libMesh::UniquePtr<GetPot> GRINSTesting::AntiochMixtureBuilderBaseTest::_input private
Definition at line 129 of file antioch_mixture_builder_test.C.
Referenced by setUp(), test_build_chem_mix(), test_build_nasa_thermo_mix_cea(), test_build_reaction_set(), test_parse_clip_negative_rho(), and test_parse_min_T().
The documentation for this class was generated from the following file:
test/interface/antioch_mixture_builder_test.C