GRINS-0.8.0: GRINS::AntiochOptions Class Reference
GRINS::AntiochOptions Class Reference
#include <antioch_options_naming.h>
Public Member Functions
AntiochOptions ()
~AntiochOptions ()
Static Public Member Functions
static std::string stat_mech_thermo_model ()
static std::string ideal_gas_thermo_model ()
static std::string cea_nasa_model ()
static std::string nasa7_nasa_model ()
static std::string nasa9_nasa_model ()
static std::string constant_transport_model ()
static std::string mix_avged_transport_model ()
static std::string constant_conductivity_model ()
static std::string constant_prandtl_conductivity_model ()
static std::string eucken_conductivity_model ()
static std::string kinetic_theory_conductivity_model ()
static std::string constant_viscosity_model ()
static std::string sutherland_viscosity_model ()
static std::string blottner_viscosity_model ()
static std::string kinetic_theory_viscosity_model ()
static std::string constant_lewis_diffusivity_model ()
static std::string kinetic_theory_diffusivity_model ()
Detailed Description
Definition at line 30 of file antioch_options_naming.h.
Constructor & Destructor Documentation
GRINS::AntiochOptions::AntiochOptions () inline
Definition at line 33 of file antioch_options_naming.h.
 {}
GRINS::AntiochOptions::~AntiochOptions () inline
Definition at line 34 of file antioch_options_naming.h.
 {}
Member Function Documentation
static std::string GRINS::AntiochOptions::blottner_viscosity_model () inline static
Definition at line 75 of file antioch_options_naming.h.
Referenced by GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_mix_avged_physics_with_thermo().
     { return "blottner";}
static std::string GRINS::AntiochOptions::cea_nasa_model () inline static
Definition at line 42 of file antioch_options_naming.h.
Referenced by GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_const_physics(), and GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_mix_avged_physics().
     { return "cea";}
static std::string GRINS::AntiochOptions::constant_conductivity_model () inline static
Definition at line 57 of file antioch_options_naming.h.
Referenced by GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_const_physics_with_thermo().
     { return "constant";}
static std::string GRINS::AntiochOptions::constant_lewis_diffusivity_model () inline static
Definition at line 81 of file antioch_options_naming.h.
Referenced by GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_const_physics(), and GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_mix_avged_physics_with_thermo().
     { return "constant_lewis";}
static std::string GRINS::AntiochOptions::constant_prandtl_conductivity_model () inline static
Definition at line 60 of file antioch_options_naming.h.
Referenced by GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_const_physics_with_thermo().
     { return "constant_prandtl";}
static std::string GRINS::AntiochOptions::constant_transport_model () inline static
Definition at line 51 of file antioch_options_naming.h.
Referenced by GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_physics().
     { return "constant";}
static std::string GRINS::AntiochOptions::constant_viscosity_model () inline static
Definition at line 69 of file antioch_options_naming.h.
Referenced by GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_const_physics().
     { return "constant";}
static std::string GRINS::AntiochOptions::eucken_conductivity_model () inline static
Definition at line 63 of file antioch_options_naming.h.
Referenced by GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_mix_avged_physics_with_thermo().
     { return "eucken";}
static std::string GRINS::AntiochOptions::ideal_gas_thermo_model () inline static
Definition at line 39 of file antioch_options_naming.h.
     { return "ideal_gas";}
static std::string GRINS::AntiochOptions::kinetic_theory_conductivity_model () inline static
Definition at line 66 of file antioch_options_naming.h.
Referenced by GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_mix_avged_physics_with_thermo().
     { return "kinetics_theory";}
static std::string GRINS::AntiochOptions::kinetic_theory_diffusivity_model () inline static
Definition at line 84 of file antioch_options_naming.h.
Referenced by GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_mix_avged_physics_with_thermo().
     { return "kinetics_theory";}
static std::string GRINS::AntiochOptions::kinetic_theory_viscosity_model () inline static
Definition at line 78 of file antioch_options_naming.h.
Referenced by GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_mix_avged_physics_with_thermo().
     { return "kinetics_theory";}
static std::string GRINS::AntiochOptions::mix_avged_transport_model () inline static
Definition at line 54 of file antioch_options_naming.h.
Referenced by GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_physics().
     { return "mixture_averaged";}
static std::string GRINS::AntiochOptions::nasa7_nasa_model () inline static
Definition at line 45 of file antioch_options_naming.h.
     { return "nasa7";}
static std::string GRINS::AntiochOptions::nasa9_nasa_model () inline static
Definition at line 48 of file antioch_options_naming.h.
     { return "nasa9";}
static std::string GRINS::AntiochOptions::stat_mech_thermo_model () inline static
Definition at line 36 of file antioch_options_naming.h.
Referenced by GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_const_physics(), and GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_mix_avged_physics().
     { return "stat_mech";}
static std::string GRINS::AntiochOptions::sutherland_viscosity_model () inline static
Definition at line 72 of file antioch_options_naming.h.
Referenced by GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_mix_avged_physics_with_thermo().
     { return "sutherland";}
The documentation for this class was generated from the following file:
src/properties/include/grins/antioch_options_naming.h