GRINS-0.8.0: GRINS::AntiochMixtureAveragedTransportMixtureBuilder Class Reference
GRINS::AntiochMixtureAveragedTransportMixtureBuilder Class Reference
#include <antioch_mixture_averaged_transport_mixture_builder.h>
Public Member Functions
AntiochMixtureAveragedTransportMixtureBuilder ()
~AntiochMixtureAveragedTransportMixtureBuilder ()
template<typename KineticsThermoCurveFit , typename Thermo , typename Viscosity , typename Conductivity , typename Diffusivity >
libMesh::UniquePtr< AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity > > build_mixture (const GetPot &input, const std::string &material)
template<typename KT , typename T , typename V , typename C , typename D >
libMesh::UniquePtr< AntiochMixtureAveragedTransportMixture< KT, T, V, C, D > > build_mixture (const GetPot &input, const std::string &material)
Public Member Functions inherited from GRINS::AntiochMixtureBuilderBase
AntiochMixtureBuilderBase ()
~AntiochMixtureBuilderBase ()
libMesh::UniquePtr< Antioch::ChemicalMixture< libMesh::Real > > build_chem_mix (const GetPot &input, const std::string &material)
libMesh::UniquePtr< Antioch::ReactionSet< libMesh::Real > > build_reaction_set (const GetPot &input, const std::string &material, const Antioch::ChemicalMixture< libMesh::Real > &chem_mix)
template<typename KineticsThermoCurveFit >
libMesh::UniquePtr< Antioch::NASAThermoMixture< libMesh::Real, KineticsThermoCurveFit > > build_nasa_thermo_mix (const GetPot &input, const std::string &material, const Antioch::ChemicalMixture< libMesh::Real > &chem_mix)
template<typename KineticsThermoCurveFit >
libMesh::UniquePtr< AntiochMixture< KineticsThermoCurveFit > > build_antioch_mixture (const GetPot &input, const std::string &material)
libMesh::Real parse_min_T (const GetPot &input, const std::string &material)
bool parse_clip_negative_rho (const GetPot &input, const std::string &material)
Private Member Functions
libMesh::UniquePtr< Antioch::TransportMixture< libMesh::Real > > build_transport_mixture (const GetPot &input, const std::string &material, const Antioch::ChemicalMixture< libMesh::Real > &chem_mix)
libMesh::UniquePtr< Antioch::MixtureAveragedTransportMixture< libMesh::Real > > build_mix_avg_trans_mixture (const Antioch::TransportMixture< libMesh::Real > &trans_mix)
template<typename Viscosity >
libMesh::UniquePtr< Antioch::MixtureViscosity< Viscosity, libMesh::Real > > build_viscosity (const GetPot &input, const std::string &material, const Antioch::TransportMixture< libMesh::Real > &trans_mix)
template<typename Diffusivity >
libMesh::UniquePtr< Antioch::MixtureDiffusion< Diffusivity, libMesh::Real > > build_diffusivity (const GetPot &input, const std::string &material, const Antioch::TransportMixture< libMesh::Real > &trans_mix)
libMesh::UniquePtr< Antioch::MixtureViscosity< Antioch::SutherlandViscosity< libMesh::Real >, libMesh::Real > > specialized_build_viscosity (const GetPot &input, const std::string &material, const Antioch::TransportMixture< libMesh::Real > &trans_mix, viscosity_type< Antioch::SutherlandViscosity< libMesh::Real > >)
libMesh::UniquePtr< Antioch::MixtureViscosity< Antioch::BlottnerViscosity< libMesh::Real >, libMesh::Real > > specialized_build_viscosity (const GetPot &input, const std::string &material, const Antioch::TransportMixture< libMesh::Real > &trans_mix, viscosity_type< Antioch::BlottnerViscosity< libMesh::Real > >)
libMesh::UniquePtr< Antioch::MixtureDiffusion< Antioch::ConstantLewisDiffusivity< libMesh::Real >, libMesh::Real > > specialized_build_diffusivity (const GetPot &input, const std::string &material, const Antioch::TransportMixture< libMesh::Real > &trans_mix, diffusivity_type< Antioch::ConstantLewisDiffusivity< libMesh::Real > >)
Additional Inherited Members
Protected Member Functions inherited from GRINS::AntiochMixtureBuilderBase
void parse_nasa_data (Antioch::NASAThermoMixture< libMesh::Real, Antioch::CEACurveFit< libMesh::Real > > &nasa_mixture, const GetPot &input, const std::string &material)
Detailed Description
Definition at line 39 of file antioch_mixture_averaged_transport_mixture_builder.h.
Constructor & Destructor Documentation
GRINS::AntiochMixtureAveragedTransportMixtureBuilder::AntiochMixtureAveragedTransportMixtureBuilder () inline
Definition at line 42 of file antioch_mixture_averaged_transport_mixture_builder.h.
 {}
GRINS::AntiochMixtureAveragedTransportMixtureBuilder::~AntiochMixtureAveragedTransportMixtureBuilder () inline
Definition at line 43 of file antioch_mixture_averaged_transport_mixture_builder.h.
 {}
Member Function Documentation
template<typename Diffusivity > libMesh::UniquePtr<Antioch::MixtureDiffusion<Diffusivity,libMesh::Real> > GRINS::AntiochMixtureAveragedTransportMixtureBuilder::build_diffusivity (const GetPot & input, const std::string & material, const Antioch::TransportMixture< libMesh::Real > & trans_mix) inline private
Definition at line 68 of file antioch_mixture_averaged_transport_mixture_builder.h.
References specialized_build_diffusivity().
     { return specialized_build_diffusivity( input, material, trans_mix, diffusivity_type<Diffusivity>() ); }
libMesh::UniquePtr<Antioch::MixtureAveragedTransportMixture<libMesh::Real> > GRINS::AntiochMixtureAveragedTransportMixtureBuilder::build_mix_avg_trans_mixture (const Antioch::TransportMixture< libMesh::Real > & trans_mix) inline private
Definition at line 56 of file antioch_mixture_averaged_transport_mixture_builder.h.
Referenced by build_mixture().
     { return libMesh::UniquePtr<Antioch::MixtureAveragedTransportMixture<libMesh::Real> >
         ( new Antioch::MixtureAveragedTransportMixture<libMesh::Real>(trans_mix) ); }
template<typename KineticsThermoCurveFit , typename Thermo , typename Viscosity , typename Conductivity , typename Diffusivity > libMesh::UniquePtr<AntiochMixtureAveragedTransportMixture<KineticsThermoCurveFit,Thermo,Viscosity,Conductivity,Diffusivity> > GRINS::AntiochMixtureAveragedTransportMixtureBuilder::build_mixture (const GetPot & input, const std::string & material)
Referenced by GRINS::PhysicsFactoryReactingFlows< DerivedPhysics >::build_mix_avged_physics_ptr(), GRINSTesting::AntiochMixtureAveragedTransportMixtureBuilderTest::test_build_cea_statmech_sutherland_eucken_constlewis_mix(), GRINSTesting::AntiochMixtureAveragedTransportMixtureBuilderTest::test_build_cea_sutherland_eucken_constlewis_mix(), and test_evaluator().
template<typename KT , typename T , typename V , typename C , typename D > libMesh::UniquePtr<AntiochMixtureAveragedTransportMixture<KT,T,V,C,D> > GRINS::AntiochMixtureAveragedTransportMixtureBuilder::build_mixture (const GetPot & input, const std::string & material) inline
Definition at line 160 of file antioch_mixture_averaged_transport_mixture_builder.h.
References GRINS::AntiochMixtureBuilderBase::build_chem_mix(), build_mix_avg_trans_mixture(), GRINS::AntiochMixtureBuilderBase::build_reaction_set(), build_transport_mixture(), GRINS::AntiochMixtureBuilderBase::parse_clip_negative_rho(), and GRINS::AntiochMixtureBuilderBase::parse_min_T().
   {
     libMesh::UniquePtr<Antioch::ChemicalMixture<libMesh::Real> > chem_mix =
       this->build_chem_mix(input,material);
     libMesh::UniquePtr<Antioch::ReactionSet<libMesh::Real> > reaction_set =
       this->build_reaction_set(input,material,*chem_mix);
     libMesh::UniquePtr<Antioch::NASAThermoMixture<libMesh::Real,KT> > kinetics_thermo =
       this->build_nasa_thermo_mix<KT>(input,material,*chem_mix);
     libMesh::UniquePtr<Antioch::TransportMixture<libMesh::Real> > trans_mix =
       this->build_transport_mixture(input,material,*chem_mix);
     libMesh::UniquePtr<Antioch::MixtureAveragedTransportMixture<libMesh::Real> > wilke_mix =
       this->build_mix_avg_trans_mixture(*trans_mix);
     libMesh::UniquePtr<Antioch::MixtureViscosity<V,libMesh::Real> > visc =
       this->build_viscosity<V>(input,material,*trans_mix);
     libMesh::UniquePtr<Antioch::MixtureDiffusion<D,libMesh::Real> > diff =
       this->build_diffusivity<D>(input,material,*trans_mix);
     libMesh::Real min_T = this->parse_min_T(input,material);
     bool clip_negative_rho = this->parse_clip_negative_rho(input,material);
     return libMesh::UniquePtr<AntiochMixtureAveragedTransportMixture<KT,T,V,C,D> >
       ( new AntiochMixtureAveragedTransportMixture<KT,T,V,C,D>
         (chem_mix, reaction_set, kinetics_thermo, trans_mix, wilke_mix, visc, diff, min_T, clip_negative_rho) );
   }
libMesh::UniquePtr< Antioch::TransportMixture< libMesh::Real > > GRINS::AntiochMixtureAveragedTransportMixtureBuilder::build_transport_mixture (const GetPot & input, const std::string & material, const Antioch::ChemicalMixture< libMesh::Real > & chem_mix) private
Definition at line 36 of file antioch_mixture_averaged_transport_mixture_builder.C.
Referenced by build_mixture().
   {
     std::string transport_data_filename =
       input( "Materials/"+material+"/GasMixture/Antioch/transport_data", "default" );
     if( transport_data_filename == std::string("default") )
       transport_data_filename = Antioch::DefaultInstallFilename::transport_mixture();
     bool verbose_transport_read =
       input( "Materials/"+material+"/GasMixture/Antioch/verbose_transport_read", false );
     return libMesh::UniquePtr<Antioch::TransportMixture<libMesh::Real> >
       ( new Antioch::TransportMixture<libMesh::Real>( chem_mix,
                                                       transport_data_filename,
                                                       verbose_transport_read,
                                                       Antioch::ParsingType::ASCII ) );
   }
template<typename Viscosity > libMesh::UniquePtr<Antioch::MixtureViscosity<Viscosity,libMesh::Real> > GRINS::AntiochMixtureAveragedTransportMixtureBuilder::build_viscosity (const GetPot & input, const std::string & material, const Antioch::TransportMixture< libMesh::Real > & trans_mix) inline private
Definition at line 62 of file antioch_mixture_averaged_transport_mixture_builder.h.
References specialized_build_viscosity().
     { return specialized_build_viscosity( input, material, trans_mix, viscosity_type<Viscosity>() ); }
libMesh::UniquePtr<Antioch::MixtureDiffusion<Antioch::ConstantLewisDiffusivity<libMesh::Real>,libMesh::Real> > GRINS::AntiochMixtureAveragedTransportMixtureBuilder::specialized_build_diffusivity (const GetPot & input, const std::string & material, const Antioch::TransportMixture< libMesh::Real > & trans_mix, diffusivity_type< Antioch::ConstantLewisDiffusivity< libMesh::Real > >) inline private
Definition at line 126 of file antioch_mixture_averaged_transport_mixture_builder.h.
References GRINS::MaterialsParsing::parse_lewis_number().
Referenced by build_diffusivity().
     {
       libMesh::Real Le = MaterialsParsing::parse_lewis_number(input,material);
       libMesh::UniquePtr<Antioch::MixtureDiffusion<Antioch::ConstantLewisDiffusivity<libMesh::Real>,libMesh::Real> >
         diffusivity( new Antioch::MixtureDiffusion<Antioch::ConstantLewisDiffusivity<libMesh::Real>,libMesh::Real>(trans_mix) );
       Antioch::build_constant_lewis_diffusivity<libMesh::Real>( *(diffusivity.get()), Le);
       return diffusivity;
     }
libMesh::UniquePtr<Antioch::MixtureViscosity<Antioch::SutherlandViscosity<libMesh::Real>,libMesh::Real> > GRINS::AntiochMixtureAveragedTransportMixtureBuilder::specialized_build_viscosity (const GetPot & input, const std::string & material, const Antioch::TransportMixture< libMesh::Real > & trans_mix, viscosity_type< Antioch::SutherlandViscosity< libMesh::Real > >) inline private
Definition at line 73 of file antioch_mixture_averaged_transport_mixture_builder.h.
Referenced by build_viscosity().
     {
       libMesh::UniquePtr<Antioch::MixtureViscosity<Antioch::SutherlandViscosity<libMesh::Real>,libMesh::Real> >
         viscosity( new Antioch::MixtureViscosity<Antioch::SutherlandViscosity<libMesh::Real>,libMesh::Real>(trans_mix) );
       std::string sutherland_data = input("Materials/"+material+"/GasMixture/Antioch/sutherland_data", "default");
       if( sutherland_data == "default" )
         sutherland_data = Antioch::DefaultInstallFilename::sutherland_data();
       Antioch::read_sutherland_data_ascii( *(viscosity.get()), sutherland_data );
       return viscosity;
     }
libMesh::UniquePtr<Antioch::MixtureViscosity<Antioch::BlottnerViscosity<libMesh::Real>,libMesh::Real> > GRINS::AntiochMixtureAveragedTransportMixtureBuilder::specialized_build_viscosity (const GetPot & input, const std::string & material, const Antioch::TransportMixture< libMesh::Real > & trans_mix, viscosity_type< Antioch::BlottnerViscosity< libMesh::Real > >) inline private
Definition at line 91 of file antioch_mixture_averaged_transport_mixture_builder.h.
     {
       libMesh::UniquePtr<Antioch::MixtureViscosity<Antioch::BlottnerViscosity<libMesh::Real>,libMesh::Real> >
         viscosity( new Antioch::MixtureViscosity<Antioch::BlottnerViscosity<libMesh::Real>,libMesh::Real>(trans_mix) );
       std::string blottner_data = input("Materials/"+material+"/GasMixture/Antioch/blottner_data", "default");
       if( blottner_data == "default" )
         blottner_data = Antioch::DefaultInstallFilename::blottner_data();
       Antioch::read_blottner_data_ascii( *(viscosity.get()), blottner_data );
       return viscosity;
     }
The documentation for this class was generated from the following files:
src/properties/include/grins/antioch_mixture_averaged_transport_mixture_builder.h
src/properties/src/antioch_mixture_averaged_transport_mixture_builder.C