GRINS-0.6.0: GRINS::Visualization Class Reference
GRINS::Visualization Class Reference abstract
#include <visualization.h>
Public Member Functions
Visualization (const GetPot &input, const libMesh::Parallel::Communicator &comm LIBMESH_CAN_DEFAULT_TO_COMMWORLD)
virtual ~Visualization ()
void output (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system)
void output (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, const unsigned int time_step, const libMesh::Real time)
void output_residual (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, GRINS::MultiphysicsSystem *system)
virtual void output_residual (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, GRINS::MultiphysicsSystem *system, const unsigned int time_step, const libMesh::Real time)=0
void output_residual_sensitivities (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, GRINS::MultiphysicsSystem *system, const libMesh::ParameterVector &params)
virtual void output_residual_sensitivities (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, GRINS::MultiphysicsSystem *system, const libMesh::ParameterVector &params, const unsigned int time_step, const libMesh::Real time)=0
void output_adjoint (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, GRINS::MultiphysicsSystem *system)
virtual void output_adjoint (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, GRINS::MultiphysicsSystem *system, const unsigned int time_step, const libMesh::Real time)=0
void output_solution_sensitivities (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, GRINS::MultiphysicsSystem *system, const libMesh::ParameterVector &params)
virtual void output_solution_sensitivities (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, GRINS::MultiphysicsSystem *system, const libMesh::ParameterVector &params, const unsigned int time_step, const libMesh::Real time)=0
void dump_visualization (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, const std::string &filename_prefix, const libMesh::Real time)
Protected Attributes
std::string _vis_output_file_prefix
std::vector< std::string > _output_format
Detailed Description
Definition at line 49 of file visualization.h.
Constructor & Destructor Documentation
GRINS::Visualization::Visualization (const GetPot & input, const libMesh::Parallel::Communicator &comm LIBMESH_CAN_DEFAULT_TO_COMMWORLD)
Definition at line 50 of file visualization.C.
References _output_format.
     : _vis_output_file_prefix( input("vis-options/vis_output_file_prefix", "unknown" ) )
   {
     unsigned int num_formats = input.vector_variable_size("vis-options/output_format");
     // If no format specified, default to ExodusII only
     if( num_formats == 0 )
       {
         // Were we specifically asked to use a ParallelMesh or SerialMesh?
         std::string mesh_class = input("mesh-options/mesh_class", "default");
         if (mesh_class == "parallel")
           _output_format.push_back("Nemesis");
         else if (mesh_class == "serial")
           _output_format.push_back("ExodusII");
         else if (mesh_class == "default")
           {
             // Is our default Mesh distributable?
             libMesh::Mesh testdefault(comm);
             testdefault.delete_remote_elements();
             if (testdefault.is_serial())
               _output_format.push_back("ExodusII");
             else
               _output_format.push_back("Nemesis");
           }
         else
           {
             std::cerr << " Visualization::Visualization:"
                       << " mesh-options/mesh_class had invalid value " << mesh_class
                       << std::endl;
             libmesh_error();
           }
       }
     for( unsigned int i = 0; i < num_formats; i++ )
       {
         _output_format.push_back( input("vis-options/output_format", "DIE", i ) );
       }
     return;
   }
GRINS::Visualization::~Visualization () virtual
Definition at line 93 of file visualization.C.
   {
     return;
   }
Member Function Documentation
void GRINS::Visualization::dump_visualization (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, const std::string & filename_prefix, const libMesh::Real time)
Definition at line 154 of file visualization.C.
Referenced by output(), GRINS::SteadyVisualization::output_adjoint(), and GRINS::SteadyVisualization::output_residual().
   {
     libMesh::MeshBase& mesh = equation_system->get_mesh();
     if( this->_vis_output_file_prefix == "unknown" )
       {
         // TODO: Need consisent way to print warning messages.
         std::cout << " WARNING in Visualization::dump_visualization :"
                   << " using 'unknown' as file prefix since it was not set "
                   << std::endl;
       }
     // If we're asked to put files in a subdirectory, let's make sure
     // it exists
     if (!mesh.comm().rank())
       for (std::size_t pos = this->_vis_output_file_prefix.find('/');
            pos != std::string::npos;
            pos = this->_vis_output_file_prefix.find('/',++pos))
         if (mkdir(this->_vis_output_file_prefix.substr(0,pos).c_str(),
                   0777) != 0 && errno != EEXIST)
           libmesh_file_error(this->_vis_output_file_prefix.substr(0,pos));
     for( std::vector<std::string>::const_iterator format = _output_format.begin();
          format != _output_format.end();
          format ++ )
       {
         // The following is a modifed copy from the FIN-S code.
         if ((*format) == "tecplot" ||
             (*format) == "dat")
           {
             std::string filename = filename_prefix+".dat";
             libMesh::TecplotIO(mesh,false).write_equation_systems( filename,
                                                                    *equation_system );
           }
         else if ((*format) == "tecplot_binary" ||
                  (*format) == "plt")
           {
             std::string filename = filename_prefix+".plt";
             libMesh::TecplotIO(mesh,true).write_equation_systems( filename,
                                                                   *equation_system );
           }
         else if ((*format) == "gmv")
           {
             std::string filename = filename_prefix+".gmv";
             libMesh::GMVIO(mesh).write_equation_systems( filename,
                                                 *equation_system );
           }
         else if ((*format) == "pvtu")
           {
             std::string filename = filename_prefix+".pvtu";
             libMesh::VTKIO(mesh).write_equation_systems( filename,
                                                 *equation_system );
           }
         else if ((*format) == "ExodusII")
           {
             std::string filename = filename_prefix+".exo";
             // The "1" is hardcoded for the number of time steps because the ExodusII manual states that
             // it should be the number of timesteps within the file. Here, we are explicitly only doing
             // one timestep per file.
             libMesh::ExodusII_IO(mesh).write_timestep
               ( filename, *equation_system, 1, time );
           }
         else if ((*format) == "Nemesis")
           {
             std::string filename = filename_prefix+".nem";
             // The "1" is hardcoded for the number of time steps because the ExodusII manual states that
             // it should be the number of timesteps within the file. Here, we are explicitly only doing
             // one timestep per file.
             libMesh::Nemesis_IO(mesh).write_timestep
               ( filename, *equation_system, 1, time );
           }
         else if ((*format).find("xda") != std::string::npos ||
                  (*format).find("xdr") != std::string::npos)
           {
             std::string filename = filename_prefix+"."+(*format);
             const bool binary = ((*format).find("xdr") != std::string::npos);
             equation_system->write( filename,
                                     binary ? GRINSEnums::ENCODE : GRINSEnums::WRITE,
                                     libMesh::EquationSystems::WRITE_DATA |
                                     libMesh::EquationSystems::WRITE_ADDITIONAL_DATA );
           }
         else if ((*format) == "mesh_only" )
           {
             std::string filename = filename_prefix+"_mesh.xda";
             equation_system->get_mesh().write( filename );
           }
         else
           {
             // TODO: Do we want to use this to error throughout the code?
             // TODO: (at least need to pass/print some message/string) - sahni
             libmesh_error();
           }
       } // End loop over formats
     return;
   }
void GRINS::Visualization::output (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system)
Definition at line 98 of file visualization.C.
References _vis_output_file_prefix, and dump_visualization().
   {
     this->dump_visualization( equation_system, _vis_output_file_prefix, 0.0 );
     return;
   }
void GRINS::Visualization::output (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, const unsigned int time_step, const libMesh::Real time)
Definition at line 106 of file visualization.C.
   {
     std::stringstream suffix;
     suffix << time_step;
     std::string filename = this->_vis_output_file_prefix;
     filename+="."+suffix.str();
     this->dump_visualization( equation_system, filename, time );
     return;
   }
void GRINS::Visualization::output_adjoint (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, GRINS::MultiphysicsSystem * system)
Definition at line 138 of file visualization.C.
   {
     this->output_adjoint( equation_system, system, 0, 0.0 );
   }
virtual void GRINS::Visualization::output_adjoint (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, GRINS::MultiphysicsSystem * system, const unsigned int time_step, const libMesh::Real time) pure virtual
Implemented in GRINS::UnsteadyVisualization, and GRINS::SteadyVisualization.
void GRINS::Visualization::output_residual (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, GRINS::MultiphysicsSystem * system)
Definition at line 122 of file visualization.C.
   {
     this->output_residual( equation_system, system, 0, 0.0 );
     return;
   }
virtual void GRINS::Visualization::output_residual (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, GRINS::MultiphysicsSystem * system, const unsigned int time_step, const libMesh::Real time) pure virtual
Implemented in GRINS::UnsteadyVisualization, and GRINS::SteadyVisualization.
void GRINS::Visualization::output_residual_sensitivities (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, GRINS::MultiphysicsSystem * system, const libMesh::ParameterVector & params)
Definition at line 130 of file visualization.C.
   {
     this->output_residual_sensitivities
       ( equation_system, system, params, 0, 0.0 );
   }
virtual void GRINS::Visualization::output_residual_sensitivities (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, GRINS::MultiphysicsSystem * system, const libMesh::ParameterVector & params, const unsigned int time_step, const libMesh::Real time) pure virtual
Implemented in GRINS::UnsteadyVisualization, and GRINS::SteadyVisualization.
void GRINS::Visualization::output_solution_sensitivities (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, GRINS::MultiphysicsSystem * system, const libMesh::ParameterVector & params)
Definition at line 145 of file visualization.C.
   {
     this->output_solution_sensitivities
       ( equation_system, system, params, 0, 0.0 );
   }
virtual void GRINS::Visualization::output_solution_sensitivities (std::tr1::shared_ptr< libMesh::EquationSystems > equation_system, GRINS::MultiphysicsSystem * system, const libMesh::ParameterVector & params, const unsigned int time_step, const libMesh::Real time) pure virtual
Implemented in GRINS::UnsteadyVisualization, and GRINS::SteadyVisualization.
Member Data Documentation
std::vector<std::string> GRINS::Visualization::_output_format protected
Definition at line 106 of file visualization.h.
Referenced by Visualization().
std::string GRINS::Visualization::_vis_output_file_prefix protected
Definition at line 105 of file visualization.h.
Referenced by output(), GRINS::SteadyVisualization::output_adjoint(), and GRINS::SteadyVisualization::output_residual().
The documentation for this class was generated from the following files:
src/visualization/include/grins/visualization.h
src/visualization/src/visualization.C