GRINS-0.8.0: GRINS::CatalyticWallNeumannBCFactoryCommon< ImplType > Class Template Reference
GRINS::CatalyticWallNeumannBCFactoryCommon< ImplType > Class Template Reference
Factory helper class for building catalytic wall Neumann boundary conditions.
#include <catalytic_wall_neumann_bc_factory_common.h>
Public Member Functions
CatalyticWallNeumannBCFactoryCommon ()
~CatalyticWallNeumannBCFactoryCommon ()
Protected Member Functions
SharedPtr< NeumannBCAbstract > build_catalytic_wall_common (const GetPot &input, const FEVariablesBase &fe_var, const std::string &material, const std::string &reaction, SharedPtr< CatalycityBase > &gamma_ptr, libMesh::Real p0, std::string &thermochem_lib)
void extract_species_vars (const FEVariablesBase &fe_var, std::vector< VariableIndex > &species_vars) const
void extract_material (const FEVariablesBase &fe_var, std::string &material) const
VariableIndex extract_temp_var () const
Protected Attributes
ImplType _wall_impl
Detailed Description
template<typename ImplType>
class GRINS::CatalyticWallNeumannBCFactoryCommon< ImplType >
Factory helper class for building catalytic wall Neumann boundary conditions.
Note for catalytic walls, we're currently assuming that both SpeciesMassFractions and Temperature FEVariables are in the system.
Definition at line 45 of file catalytic_wall_neumann_bc_factory_common.h.
Constructor & Destructor Documentation
template<typename ImplType> GRINS::CatalyticWallNeumannBCFactoryCommon< ImplType >::CatalyticWallNeumannBCFactoryCommon () inline
Definition at line 49 of file catalytic_wall_neumann_bc_factory_common.h.
 {};
template<typename ImplType> GRINS::CatalyticWallNeumannBCFactoryCommon< ImplType >::~CatalyticWallNeumannBCFactoryCommon () inline
Definition at line 51 of file catalytic_wall_neumann_bc_factory_common.h.
 {};
Member Function Documentation
template<typename ImpType > SharedPtr< NeumannBCAbstract > GRINS::CatalyticWallNeumannBCFactoryCommon< ImpType >::build_catalytic_wall_common (const GetPot & input, const FEVariablesBase & fe_var, const std::string & material, const std::string & reaction, SharedPtr< CatalycityBase > & gamma_ptr, libMesh::Real p0, std::string & thermochem_lib) protected
Definition at line 44 of file catalytic_wall_neumann_bc_factory_common.C.
References GRINS::FEVariablesBase::active_var_names().
   {
     // Extract species variables and material
     std::vector<VariableIndex> species_vars;
     this->extract_species_vars( fe_var, species_vars );
     libmesh_assert_equal_to( fe_var.active_var_names().size(), species_vars.size() );
     // Extract Temperature variable index.
     VariableIndex T_var = this->extract_temp_var();
     return _wall_impl.build_catalytic_wall(input,reaction,gamma_ptr,species_vars,
                                            material,T_var,p0,thermochem_lib);
   }
template<typename ImpType > void GRINS::CatalyticWallNeumannBCFactoryCommon< ImpType >::extract_material (const FEVariablesBase & fe_var, std::string & material) const protected
Definition at line 73 of file catalytic_wall_neumann_bc_factory_common.C.
References GRINS::SpeciesMassFractionsVariable::material().
   {
     const SpeciesMassFractionsVariable& species_fe_var =
       libMesh::cast_ref<const SpeciesMassFractionsVariable&>(fe_var);
     material = species_fe_var.material();
   }
template<typename ImpType > void GRINS::CatalyticWallNeumannBCFactoryCommon< ImpType >::extract_species_vars (const FEVariablesBase & fe_var, std::vector< VariableIndex > & species_vars) const protected
Definition at line 67 of file catalytic_wall_neumann_bc_factory_common.C.
References GRINS::FEVariablesBase::var_indices().
   {
     species_vars = fe_var.var_indices();
   }
template<typename ImpType > VariableIndex GRINS::CatalyticWallNeumannBCFactoryCommon< ImpType >::extract_temp_var () const protected
Definition at line 83 of file catalytic_wall_neumann_bc_factory_common.C.
References GRINS::GRINSPrivate::VariableWarehouse::get_variable(), GRINS::VariablesParsing::temperature_section(), and GRINS::FEVariablesBase::var_indices().
   {
     // This will throw an error is the temperature variables are not there
     const FEVariablesBase& temp_fe_var_base =
       GRINS::GRINSPrivate::VariableWarehouse::get_variable(VariablesParsing::temperature_section());
     const PrimitiveTempFEVariables& temp_fe_var =
       libMesh::cast_ref<const PrimitiveTempFEVariables&>(temp_fe_var_base);
     std::vector<VariableIndex> temp_var = temp_fe_var.var_indices();
     libmesh_assert_equal_to( temp_var.size(), 1 );
     return temp_var[0];
   }
Member Data Documentation
template<typename ImplType> ImplType GRINS::CatalyticWallNeumannBCFactoryCommon< ImplType >::_wall_impl protected
Definition at line 64 of file catalytic_wall_neumann_bc_factory_common.h.
The documentation for this class was generated from the following files:
src/boundary_conditions/include/grins/catalytic_wall_neumann_bc_factory_common.h
src/boundary_conditions/src/catalytic_wall_neumann_bc_factory_common.C