GRINS-0.7.0: GRINSTesting::NASA7ThermoTestBase Class Reference
GRINSTesting::NASA7ThermoTestBase Class Reference
#include <nasa_thermo_test_base.h>
Public Member Functions
NASA7ThermoTestBase ()
virtual libMesh::Real cp_exact (unsigned int species_idx, libMesh::Real T)
virtual libMesh::Real h_exact (unsigned int species_idx, libMesh::Real T)
virtual libMesh::Real s_R_exact (unsigned int species_idx, libMesh::Real T)
virtual libMesh::Real h_RT_exact (unsigned int species_idx, libMesh::Real T)
Public Member Functions inherited from GRINSTesting::NASAThermoTestBase
template<typename ThermoMixture , typename ThermoEvaluator >
void test_cp_common (ThermoMixture &mixture, const std::vector< libMesh::Real > &Y, libMesh::Real rel_tol)
template<typename ThermoMixture , typename ThermoEvaluator >
void test_h_common (ThermoMixture &mixture, libMesh::Real rel_tol)
Public Member Functions inherited from GRINSTesting::SpeciesTestBase
SpeciesTestBase ()
libMesh::Real molar_mass (unsigned int idx)
libMesh::Real R_species (unsigned int idx)
Private Member Functions
void init_N2_coeffs ()
void init_O2_coeffs ()
void init_O_coeffs ()
void init_NO_coeffs ()
void init_N_coeffs ()
Additional Inherited Members
Protected Member Functions inherited from GRINSTesting::NASAThermoTestBase
const std::vector< libMesh::Real > & nasa_coeffs (unsigned int idx)
Protected Attributes inherited from GRINSTesting::NASAThermoTestBase
std::vector< libMesh::Real > _N2_200_1000_coeffs
std::vector< libMesh::Real > _O2_200_1000_coeffs
std::vector< libMesh::Real > _O_200_1000_coeffs
std::vector< libMesh::Real > _NO_200_1000_coeffs
std::vector< libMesh::Real > _N_200_1000_coeffs
Protected Attributes inherited from GRINSTesting::SpeciesTestBase
unsigned int _N2_idx
unsigned int _O2_idx
unsigned int _O_idx
unsigned int _N_idx
unsigned int _NO_idx
std::vector< unsigned int > _active_species
Detailed Description
Definition at line 153 of file nasa_thermo_test_base.h.
Constructor & Destructor Documentation
GRINSTesting::NASA7ThermoTestBase::NASA7ThermoTestBase () inline
Definition at line 157 of file nasa_thermo_test_base.h.
References init_N2_coeffs(), init_N_coeffs(), init_NO_coeffs(), init_O2_coeffs(), and init_O_coeffs().
     {
       this->init_N2_coeffs();
       this->init_O2_coeffs();
       this->init_O_coeffs();
       this->init_NO_coeffs();
       this->init_N_coeffs();
     }
Member Function Documentation
virtual libMesh::Real GRINSTesting::NASA7ThermoTestBase::cp_exact (unsigned int species_idx, libMesh::Real T) inline virtual
Implements GRINSTesting::NASAThermoTestBase.
Definition at line 166 of file nasa_thermo_test_base.h.
References GRINSTesting::ThermochemTestCommon::nasa7_cp_R_exact(), GRINSTesting::NASAThermoTestBase::nasa_coeffs(), and GRINSTesting::SpeciesTestBase::R_species().
     {
       const std::vector<libMesh::Real> coeffs = this->nasa_coeffs(species_idx);
       return ThermochemTestCommon::nasa7_cp_R_exact(T,
                                                     coeffs[0],
                                                     coeffs[1],
                                                     coeffs[2],
                                                     coeffs[3],
                                                     coeffs[4])*this->R_species(species_idx);
     }
virtual libMesh::Real GRINSTesting::NASA7ThermoTestBase::h_exact (unsigned int species_idx, libMesh::Real T) inline virtual
Implements GRINSTesting::NASAThermoTestBase.
Definition at line 177 of file nasa_thermo_test_base.h.
References GRINSTesting::ThermochemTestCommon::nasa7_h_RT_exact(), GRINSTesting::NASAThermoTestBase::nasa_coeffs(), and GRINSTesting::SpeciesTestBase::R_species().
     {
       const std::vector<libMesh::Real> coeffs = this->nasa_coeffs(species_idx);
       return ThermochemTestCommon::nasa7_h_RT_exact(T,
                                                     coeffs[0],
                                                     coeffs[1],
                                                     coeffs[2],
                                                     coeffs[3],
                                                     coeffs[4],
                                                     coeffs[5])*this->R_species(species_idx)*T;
     }
virtual libMesh::Real GRINSTesting::NASA7ThermoTestBase::h_RT_exact (unsigned int species_idx, libMesh::Real T) inline virtual
Implements GRINSTesting::NASAThermoTestBase.
Definition at line 201 of file nasa_thermo_test_base.h.
References GRINSTesting::ThermochemTestCommon::nasa7_h_RT_exact(), and GRINSTesting::NASAThermoTestBase::nasa_coeffs().
     {
       const std::vector<libMesh::Real> coeffs = this->nasa_coeffs(species_idx);
       return ThermochemTestCommon::nasa7_h_RT_exact(T,
                                                     coeffs[0],
                                                     coeffs[1],
                                                     coeffs[2],
                                                     coeffs[3],
                                                     coeffs[4],
                                                     coeffs[5]);
     }
void GRINSTesting::NASA7ThermoTestBase::init_N2_coeffs () inline private
Definition at line 215 of file nasa_thermo_test_base.h.
References GRINSTesting::NASAThermoTestBase::_N2_200_1000_coeffs.
Referenced by NASA7ThermoTestBase().
     {
       _N2_200_1000_coeffs.resize(7);
       _N2_200_1000_coeffs[0] =  3.53100528E+00;
       _N2_200_1000_coeffs[1] = -1.23660987E-04;
       _N2_200_1000_coeffs[2] = -5.02999437E-07;
       _N2_200_1000_coeffs[3] =  2.43530612E-09;
       _N2_200_1000_coeffs[4] = -1.40881235E-12;
       _N2_200_1000_coeffs[5] = -1.04697628E+03;
       _N2_200_1000_coeffs[6] =  2.96747468E+00;
     }
void GRINSTesting::NASA7ThermoTestBase::init_N_coeffs () inline private
Definition at line 267 of file nasa_thermo_test_base.h.
References GRINSTesting::NASAThermoTestBase::_N_200_1000_coeffs.
Referenced by NASA7ThermoTestBase().
     {
       _N_200_1000_coeffs.resize(7);
       _N_200_1000_coeffs[0] =  2.50000000E+00;
       _N_200_1000_coeffs[1] =  0.0;
       _N_200_1000_coeffs[2] =  0.0;
       _N_200_1000_coeffs[3] =  0.0;
       _N_200_1000_coeffs[4] =  0.0;
       _N_200_1000_coeffs[5] =  5.61046378E+04;
       _N_200_1000_coeffs[6] =  4.19390932E+00;
     }
void GRINSTesting::NASA7ThermoTestBase::init_NO_coeffs () inline private
Definition at line 254 of file nasa_thermo_test_base.h.
References GRINSTesting::NASAThermoTestBase::_NO_200_1000_coeffs.
Referenced by NASA7ThermoTestBase().
     {
       _NO_200_1000_coeffs.resize(7);
       _NO_200_1000_coeffs[0] =  4.21859896E+00;
       _NO_200_1000_coeffs[1] = -4.63988124E-03;
       _NO_200_1000_coeffs[2] =  1.10443049E-05;
       _NO_200_1000_coeffs[3] = -9.34055507E-09;
       _NO_200_1000_coeffs[4] =  2.80554874E-12;
       _NO_200_1000_coeffs[5] =  9.84509964E+03;
       _NO_200_1000_coeffs[6] =  2.28061001E+00;
     }
void GRINSTesting::NASA7ThermoTestBase::init_O2_coeffs () inline private
Definition at line 228 of file nasa_thermo_test_base.h.
References GRINSTesting::NASAThermoTestBase::_O2_200_1000_coeffs.
Referenced by NASA7ThermoTestBase().
     {
       _O2_200_1000_coeffs.resize(7);
       _O2_200_1000_coeffs[0] =  3.78245636E+00;
       _O2_200_1000_coeffs[1] = -2.99673415E-03;
       _O2_200_1000_coeffs[2] =  9.84730200E-06;
       _O2_200_1000_coeffs[3] = -9.68129508E-09;
       _O2_200_1000_coeffs[4] =  3.24372836E-12;
       _O2_200_1000_coeffs[5] = -1.06394356E+03;
       _O2_200_1000_coeffs[6] =  3.65767573E+00;
     }
void GRINSTesting::NASA7ThermoTestBase::init_O_coeffs () inline private
Definition at line 241 of file nasa_thermo_test_base.h.
References GRINSTesting::NASAThermoTestBase::_O_200_1000_coeffs.
Referenced by NASA7ThermoTestBase().
     {
       _O_200_1000_coeffs.resize(7);
       _O_200_1000_coeffs[0] =  3.16826710E+00;
       _O_200_1000_coeffs[1] = -3.27931884E-03;
       _O_200_1000_coeffs[2] =  6.64306396E-06;
       _O_200_1000_coeffs[3] = -6.12806624E-09;
       _O_200_1000_coeffs[4] =  2.11265971E-12;
       _O_200_1000_coeffs[5] =  2.91222592E+04;
       _O_200_1000_coeffs[6] =  2.05193346E+00;
     }
virtual libMesh::Real GRINSTesting::NASA7ThermoTestBase::s_R_exact (unsigned int species_idx, libMesh::Real T) inline virtual
Implements GRINSTesting::NASAThermoTestBase.
Definition at line 189 of file nasa_thermo_test_base.h.
References GRINSTesting::ThermochemTestCommon::nasa7_s_R_exact(), and GRINSTesting::NASAThermoTestBase::nasa_coeffs().
     {
       const std::vector<libMesh::Real> coeffs = this->nasa_coeffs(species_idx);
       return ThermochemTestCommon::nasa7_s_R_exact(T,
                                                    coeffs[0],
                                                    coeffs[1],
                                                    coeffs[2],
                                                    coeffs[3],
                                                    coeffs[4],
                                                    coeffs[6]);
     }
The documentation for this class was generated from the following file:
test/interface/nasa_thermo_test_base.h