GRINS-0.8.0: GRINS::ParsedBoundaryQoI Class Reference
GRINS::ParsedBoundaryQoI Class Reference
Parsed Boundary QoI.
#include <parsed_boundary_qoi.h>
Public Member Functions
ParsedBoundaryQoI (const std::string &qoi_name)
Constructor.
virtual ~ParsedBoundaryQoI ()
virtual QoIBase * clone () const
Required to provide clone (deep-copy) for adding QoI object to libMesh objects.
virtual bool assemble_on_interior () const
Does the QoI need an element interior assembly loop?
virtual bool assemble_on_sides () const
Does the QoI need a domain boundary assembly loop?
virtual void init (const GetPot &input, const MultiphysicsSystem &system, unsigned int qoi_num)
Initialize local variables.
virtual void init_context (AssemblyContext &context)
virtual void side_qoi (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi value.
virtual void side_qoi_derivative (AssemblyContext &context, const unsigned int qoi_index)
Compute the qoi derivative with respect to the solution.
Public Member Functions inherited from GRINS::QoIBase
QoIBase (const std::string &qoi_name)
virtual ~QoIBase ()
virtual void reinit (MultiphysicsSystem &)
Reinitialize QoI.
virtual void element_qoi (AssemblyContext &, const unsigned int)
Compute the qoi value for element interiors.
virtual void element_qoi_derivative (AssemblyContext &, const unsigned int)
Compute the qoi derivative with respect to the solution on element interiors.
virtual void parallel_op (const libMesh::Parallel::Communicator &communicator, libMesh::Number &sys_qoi, libMesh::Number &local_qoi)
Call the parallel operation for this QoI and cache the value.
virtual void thread_join (libMesh::Number &qoi, const libMesh::Number &other_qoi)
Call the operation to accumulate this QoI from multiple threads.
virtual void output_qoi (std::ostream &out) const
Basic output for computed QoI's.
libMesh::Number value () const
Returns the current QoI value.
const std::string & name () const
Returns the name of this QoI.
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Member Functions
ParsedBoundaryQoI (const ParsedBoundaryQoI &original)
Manual copy constructor due to the UniquePtr.
Protected Attributes
libMesh::UniquePtr< libMesh::FEMFunctionBase< libMesh::Number > > qoi_functional
std::set< libMesh::boundary_id_type > _bc_ids
List of boundary ids on which we want to compute this QoI.
Protected Attributes inherited from GRINS::QoIBase
std::string _qoi_name
libMesh::Number _qoi_value
Private Member Functions
ParsedBoundaryQoI ()
User never call default constructor.
Additional Inherited Members
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Detailed Description
Parsed Boundary QoI.
This class implements a QoI that is an arbitrary integral of a parsed function on the boundary of the domain.
Definition at line 44 of file parsed_boundary_qoi.h.
Constructor & Destructor Documentation
GRINS::ParsedBoundaryQoI::ParsedBoundaryQoI (const std::string & qoi_name)
Constructor.
Constructor takes GetPot object to read any input options associated with this QoI
Definition at line 42 of file parsed_boundary_qoi.C.
     : QoIBase(qoi_name) {}
GRINS::ParsedBoundaryQoI::~ParsedBoundaryQoI () virtual
Definition at line 61 of file parsed_boundary_qoi.C.
 {}
GRINS::ParsedBoundaryQoI::ParsedBoundaryQoI (const ParsedBoundaryQoI & original) protected
Manual copy constructor due to the UniquePtr.
Definition at line 45 of file parsed_boundary_qoi.C.
References _bc_ids, GRINS::ParameterUser::move_parameter(), and qoi_functional.
     : QoIBase(original)
   {
     if (original.qoi_functional.get())
       {
         this->qoi_functional = original.qoi_functional->clone();
         this->move_parameter
           (*libMesh::cast_ptr<libMesh::ParsedFEMFunction<libMesh::Number>*>
            (original.qoi_functional.get()),
            *libMesh::cast_ptr<libMesh::ParsedFEMFunction<libMesh::Number>*>
            (this->qoi_functional.get()));
       }
     this->_bc_ids = original._bc_ids;
   }
GRINS::ParsedBoundaryQoI::ParsedBoundaryQoI () private
User never call default constructor.
Referenced by clone().
Member Function Documentation
bool GRINS::ParsedBoundaryQoI::assemble_on_interior () const inline virtual
Does the QoI need an element interior assembly loop?
This is pure virtual to force to user to specify.
Implements GRINS::QoIBase.
Definition at line 96 of file parsed_boundary_qoi.h.
   {
     return false;
   }
bool GRINS::ParsedBoundaryQoI::assemble_on_sides () const inline virtual
Does the QoI need a domain boundary assembly loop?
This is pure virtual to force to user to specify.
Implements GRINS::QoIBase.
Definition at line 102 of file parsed_boundary_qoi.h.
   {
     return true;
   }
QoIBase * GRINS::ParsedBoundaryQoI::clone () const virtual
Required to provide clone (deep-copy) for adding QoI object to libMesh objects.
Implements GRINS::QoIBase.
Definition at line 63 of file parsed_boundary_qoi.C.
References ParsedBoundaryQoI().
   {
     return new ParsedBoundaryQoI( *this );
   }
void GRINS::ParsedBoundaryQoI::init (const GetPot & input, const MultiphysicsSystem & system, unsigned int qoi_num) virtual
Initialize local variables.
Reimplemented from GRINS::QoIBase.
Definition at line 68 of file parsed_boundary_qoi.C.
References _bc_ids, qoi_functional, and GRINS::ParameterUser::set_parameter().
   {
     // Read boundary ids on which we want to compute qoi
     int num_bcs =  input.vector_variable_size("QoI/ParsedBoundary/bc_ids");
     if( num_bcs <= 0 )
       {
         std::cerr << "Error: Must specify at least one boundary id to compute"
                   << " parsed boundary QoI." << std::endl
                   << "Found: " << num_bcs << std::endl;
         libmesh_error();
       }
     for( int i = 0; i < num_bcs; i++ )
       {
         _bc_ids.insert( input("QoI/ParsedBoundary/bc_ids", -1, i ) );
       }
     libMesh::ParsedFEMFunction<libMesh::Number> *qf
       (new libMesh::ParsedFEMFunction<libMesh::Number>
        (system, ""));
     this->qoi_functional.reset(qf);
     this->set_parameter(*qf, input,
                         "QoI/ParsedBoundary/qoi_functional", "DIE!");
   }
void GRINS::ParsedBoundaryQoI::init_context (AssemblyContext & context) virtual
Reimplemented from GRINS::QoIBase.
Definition at line 97 of file parsed_boundary_qoi.C.
References qoi_functional.
   {
     libMesh::FEBase* side_fe;
     context.get_side_fe<libMesh::Real>(0, side_fe);
     side_fe->get_JxW();
     side_fe->get_xyz();
     qoi_functional->init_context(context);
   }
void GRINS::ParsedBoundaryQoI::side_qoi (AssemblyContext & context, const unsigned int qoi_index) virtual
Compute the qoi value.
Todo:
Need to generalize this to the multiple QoI case
Reimplemented from GRINS::QoIBase.
Definition at line 107 of file parsed_boundary_qoi.C.
References _bc_ids.
   {
     bool on_correct_side = false;
     for (std::set<libMesh::boundary_id_type>::const_iterator id =
            _bc_ids.begin(); id != _bc_ids.end(); id++ )
       if( context.has_side_boundary_id( (*id) ) )
         {
           on_correct_side = true;
           break;
         }
     if (!on_correct_side)
       return;
     libMesh::FEBase* side_fe;
     context.get_side_fe<libMesh::Real>(0, side_fe);
     const std::vector<libMesh::Real> &JxW = side_fe->get_JxW();
     const std::vector<libMesh::Point>& x_qp = side_fe->get_xyz();
     unsigned int n_qpoints = context.get_side_qrule().n_points();
     libMesh::Number& qoi = context.get_qois()[qoi_index];
     for( unsigned int qp = 0; qp != n_qpoints; qp++ )
       {
         const libMesh::Number func_val =
           (*qoi_functional)(context, x_qp[qp], context.get_time());
         qoi += func_val * JxW[qp];
       }
   }
void GRINS::ParsedBoundaryQoI::side_qoi_derivative (AssemblyContext & context, const unsigned int qoi_index) virtual
Compute the qoi derivative with respect to the solution.
Todo:
Need to generalize this to the multiple QoI case
Reimplemented from GRINS::QoIBase.
Definition at line 143 of file parsed_boundary_qoi.C.
References _bc_ids.
   {
     bool on_correct_side = false;
     for (std::set<libMesh::boundary_id_type>::const_iterator id =
            _bc_ids.begin(); id != _bc_ids.end(); id++ )
       if( context.has_side_boundary_id( (*id) ) )
         {
           on_correct_side = true;
           break;
         }
     if (!on_correct_side)
       return;
     libMesh::FEBase* side_fe;
     context.get_side_fe<libMesh::Real>(0, side_fe);
     const std::vector<libMesh::Real> &JxW = side_fe->get_JxW();
     const std::vector<libMesh::Point>& x_qp = side_fe->get_xyz();
     // Local DOF count and quadrature point count
     const unsigned int n_u_dofs = context.get_dof_indices().size();
     unsigned int n_qpoints = context.get_side_qrule().n_points();
     // Local solution vector - non-const version for finite
     // differenting purposes
     libMesh::DenseVector<libMesh::Number>& elem_solution =
       const_cast<libMesh::DenseVector<libMesh::Number>&>
       (context.get_elem_solution());
     libMesh::DenseVector<libMesh::Number> &Qu =
       context.get_qoi_derivatives()[qoi_index];
     for( unsigned int qp = 0; qp != n_qpoints; qp++ )
       {
         // Central finite differencing to approximate derivatives.
         // FIXME - we should hook the FParserAD stuff into
         // ParsedFEMFunction
         for( unsigned int i = 0; i != n_u_dofs; ++i )
           {
             libMesh::Number &current_solution = elem_solution(i);
             const libMesh::Number original_solution = current_solution;
             current_solution = original_solution + libMesh::TOLERANCE;
             const libMesh::Number plus_val =
               (*qoi_functional)(context, x_qp[qp], context.get_time());
             current_solution = original_solution - libMesh::TOLERANCE;
             const libMesh::Number minus_val =
               (*qoi_functional)(context, x_qp[qp], context.get_time());
             Qu(i) += (plus_val - minus_val) *
               (0.5 / libMesh::TOLERANCE) * JxW[qp];
             // Don't forget to restore the correct solution...
             current_solution = original_solution;
           }
       }
   }
Member Data Documentation
std::set<libMesh::boundary_id_type> GRINS::ParsedBoundaryQoI::_bc_ids protected
List of boundary ids on which we want to compute this QoI.
Definition at line 84 of file parsed_boundary_qoi.h.
Referenced by init(), ParsedBoundaryQoI(), side_qoi(), and side_qoi_derivative().
libMesh::UniquePtr<libMesh::FEMFunctionBase<libMesh::Number> > GRINS::ParsedBoundaryQoI::qoi_functional protected
Definition at line 80 of file parsed_boundary_qoi.h.
Referenced by init(), init_context(), and ParsedBoundaryQoI().
The documentation for this class was generated from the following files:
src/qoi/include/grins/parsed_boundary_qoi.h
src/qoi/src/parsed_boundary_qoi.C