GRINS-0.8.0: GRINS::StrategiesParsing Class Reference
GRINS::StrategiesParsing Class Reference
#include <strategies_parsing.h>
Public Member Functions
StrategiesParsing ()
~StrategiesParsing ()
Static Public Member Functions
static int extra_quadrature_order (const GetPot &input)
static std::string adjoint_residual_error_estimator ()
static std::string adjoint_refinement_error_estimator ()
static std::string kelly_error_estimator ()
static std::string patch_recovery_error_estimator ()
static bool do_adjoint_solve (const GetPot &input)
Option to let user manually trigger adjoint solve.
Detailed Description
Definition at line 39 of file strategies_parsing.h.
Constructor & Destructor Documentation
GRINS::StrategiesParsing::StrategiesParsing () inline
Definition at line 43 of file strategies_parsing.h.
 {};
GRINS::StrategiesParsing::~StrategiesParsing () inline
Definition at line 45 of file strategies_parsing.h.
 {};
Member Function Documentation
static std::string GRINS::StrategiesParsing::adjoint_refinement_error_estimator () inline static
Definition at line 52 of file strategies_parsing.h.
Referenced by GRINS::ErrorEstimatorFactoryInitializer::ErrorEstimatorFactoryInitializer().
     { return "adjoint_refinement"; }
static std::string GRINS::StrategiesParsing::adjoint_residual_error_estimator () inline static
Definition at line 49 of file strategies_parsing.h.
Referenced by GRINS::ErrorEstimatorFactoryInitializer::ErrorEstimatorFactoryInitializer(), and GRINS::ErrorEstimatorOptions::estimator_requires_adjoint().
     { return "adjoint_residual"; }
bool GRINS::StrategiesParsing::do_adjoint_solve (const GetPot & input) static
Option to let user manually trigger adjoint solve.
Definition at line 45 of file strategies_parsing.C.
References do_adjoint_solve().
Referenced by GRINS::Simulation::check_for_adjoint_solve(), and do_adjoint_solve().
   {
     bool do_adjoint_solve = false;
     std::string old_option = "linear-nonlinear-solver/do_adjoint_solve";
     std::string new_option = "Strategies/Adjoint/do_adjoint_solve";
     bool have_old_option = input.have_variable(old_option);
     bool have_new_option = input.have_variable(new_option);
     if( have_old_option  &&  have_new_option )
       libmesh_error_msg("ERROR: Cannot specify both "+old_option+" and "+new_option+"!");
     if( have_old_option )
       do_adjoint_solve = input( old_option, false );
     if( have_new_option )
       do_adjoint_solve = input( new_option, false );
     return do_adjoint_solve;
   }
int GRINS::StrategiesParsing::extra_quadrature_order (const GetPot & input) static
Definition at line 35 of file strategies_parsing.C.
Referenced by GRINS::Simulation::init_multiphysics_system().
   {
     int extra_order = input("Strategies/Assembly/extra_quadrature_order", 0);
     if( extra_order < 0 )
       libmesh_error_msg("ERROR: extra_quadrature_order must be non-negative!");
     return extra_order;
   }
static std::string GRINS::StrategiesParsing::kelly_error_estimator () inline static
Definition at line 55 of file strategies_parsing.h.
Referenced by GRINS::ErrorEstimatorFactoryInitializer::ErrorEstimatorFactoryInitializer().
     { return "kelly"; }
static std::string GRINS::StrategiesParsing::patch_recovery_error_estimator () inline static
Definition at line 58 of file strategies_parsing.h.
Referenced by GRINS::ErrorEstimatorFactoryInitializer::ErrorEstimatorFactoryInitializer().
     { return "patch_recovery"; }
The documentation for this class was generated from the following files:
src/strategies/include/grins/strategies_parsing.h
src/strategies/src/strategies_parsing.C