GRINS-0.7.0: GRINS::FEVariablesBase Class Reference
GRINS::FEVariablesBase Class Reference abstract
#include <fe_variables_base.h>
Public Member Functions
FEVariablesBase (bool is_constraint_var)
~FEVariablesBase ()
virtual void init (libMesh::FEMSystem *system)=0
Add variables to the system.
bool is_constraint_var () const
void set_neumann_bc_is_positive (bool is_positive)
Reset whetever Neumann bc is postive or not.
libMesh::Real neumann_bc_sign () const
const std::vector< std::string > & active_var_names () const
Return the var names that are active from this class.
const std::vector< VariableIndex > & var_indices () const
Protected Member Functions
void parse_names_from_input (const GetPot &input, const std::string &subsection, std::vector< std::string > &var_names, const std::vector< std::string > &default_names)
Method to parse variable names from input.
void duplicate_name_section_check (const GetPot &input) const
Check for old name style and new name style. If both present, error.
bool check_dep_name_input (const GetPot &input, const std::string &new_subsection) const
Check for deprecated variable name input style.
Protected Attributes
std::vector< VariableIndex > _vars
std::vector< std::string > _var_names
std::vector< GRINSEnums::FEFamily > _family
std::vector< GRINSEnums::Order > _order
bool _is_constraint_var
Tracks whether this is a constraint variable.
libMesh::Real _neumann_bc_sign
Track the sign of the Neumann BC term. Defaults to 1.0.
Detailed Description
Definition at line 53 of file fe_variables_base.h.
Constructor & Destructor Documentation
GRINS::FEVariablesBase::FEVariablesBase (bool is_constraint_var) inline
Definition at line 57 of file fe_variables_base.h.
       : _is_constraint_var(is_constraint_var),
         _neumann_bc_sign(1.0)
     {}
GRINS::FEVariablesBase::~FEVariablesBase () inline
Definition at line 62 of file fe_variables_base.h.
 {};
Member Function Documentation
const std::vector<std::string>& GRINS::FEVariablesBase::active_var_names () const inline
Return the var names that are active from this class.
This must not be called until init_vars has been called.
Definition at line 84 of file fe_variables_base.h.
References _var_names.
Referenced by GRINS::CatalyticWallNeumannBCFactoryCommon< ImplType >::build_catalytic_wall_common(), GRINS::ParsedFunctionNeumannBCFactory< FunctionType >::build_neumann_func(), GRINS::ParsedFunctionNeumannOldStyleBCFactory< FunctionType >::build_neumann_func(), GRINS::ParsedFunctionNeumannBCFactoryHelper< FunctionType >::build_neumman_func_common(), GRINS::OldStyleBCBuilder::construct_bcs_old_style(), GRINS::DirichletBCFactoryFunctionBase< libMesh::FunctionBase< libMesh::Number > >::get_var_names(), GRINSTesting::VariablesTest::test_pressure(), GRINSTesting::VariablesTest::test_species_mass_fracs(), GRINSTesting::VariablesTest::test_temp(), GRINSTesting::VariablesTest::test_velocity_2d(), and GRINSTesting::VariablesTest::test_velocity_3d().
     { return _var_names; }
bool GRINS::FEVariablesBase::check_dep_name_input (const GetPot & input, const std::string & new_subsection) const protected
Check for deprecated variable name input style.
If found, this returns true and emits a deprecated warning. Otherwise, this returns false. The string argument is supplied by each variable class for the warning message. E.g. if the variable class is going to look in "Displacement", i.e. [Variables/Displacement/names], then "Displacement" should be passed.
Definition at line 59 of file fe_variables_base.C.
References duplicate_name_section_check(), grins_warning, and GRINS::VariablesParsing::varnames_input_name().
Referenced by GRINS::MultiVarSingleFETypeVariable::MultiVarSingleFETypeVariable(), and GRINS::SingleVarSingleFETypeVariable::SingleVarSingleFETypeVariable().
   {
     this->duplicate_name_section_check(input);
     bool is_old_input_style = false;
     if( input.have_section("Physics/VariableNames") )
       {
         is_old_input_style = true;
         std::string warning = "WARNING: Specifying variable names with Physics/VariableNames is DEPRECATED!\n";
         warning += "         Please update to use ["+VariablesParsing::varnames_input_name(subsection)+"].\n";
         grins_warning(warning);
       }
     return is_old_input_style;
   }
void GRINS::FEVariablesBase::duplicate_name_section_check (const GetPot & input) const protected
Check for old name style and new name style. If both present, error.
Old name style: [Physics/VariableNames] New name style: [Variables/<variable type>="">] Here, we just check for the presence of the sections [Physics/VariableNames] and [Variables].
Definition at line 51 of file fe_variables_base.C.
References GRINS::VariablesParsing::variables_section().
Referenced by check_dep_name_input().
   {
     if( input.have_section("Physics/VariableNames") &&
         input.have_section(VariablesParsing::variables_section()) )
       libmesh_error_msg("ERROR: Cannot have both Physics/VariableNames and "
                         +VariablesParsing::variables_section()+" in input!");
   }
virtual void GRINS::FEVariablesBase::init (libMesh::FEMSystem * system) pure virtual
Add variables to the system.
This expects that _var_names has been setup during construction time. Most subclasses should be able to use default_fe_init, once they subclass this and VariablesBase.
Implemented in GRINS::SingleFETypeVariable, GRINS::DisplacementFEVariables, and GRINS::VelocityFEVariables.
bool GRINS::FEVariablesBase::is_constraint_var () const inline
Definition at line 70 of file fe_variables_base.h.
References _is_constraint_var.
Referenced by GRINS::DefaultBCBuilder::build_axisymmetric_bcs(), GRINS::DefaultBCBuilder::build_bcs_by_var_section(), and GRINSTesting::VariablesTest::test_var_constraint_and_warehouse().
     { return _is_constraint_var; }
libMesh::Real GRINS::FEVariablesBase::neumann_bc_sign () const inline
Definition at line 79 of file fe_variables_base.h.
References _neumann_bc_sign.
Referenced by GRINS::MultiphysicsSystem::apply_neumann_bcs().
     { return _neumann_bc_sign; }
void GRINS::FEVariablesBase::parse_names_from_input (const GetPot & input, const std::string & subsection, std::vector< std::string > & var_names, const std::vector< std::string > & default_names) protected
Method to parse variable names from input.
Names parsed from: [Variables/<subsection>/names] and then populated into the supplied var_names vector. It is assumed that var_names has been properly sized, that default_names and var_names have the same size, and that default_names has been populated with unique strings.
Definition at line 38 of file fe_variables_base.C.
References GRINS::VariablesParsing::varnames_input_name().
Referenced by GRINS::MultiVarSingleFETypeVariable::MultiVarSingleFETypeVariable(), and GRINS::SingleVarSingleFETypeVariable::SingleVarSingleFETypeVariable().
   {
     libmesh_assert_equal_to( var_names.size(), default_names.size() );
     unsigned int n_names = default_names.size();
     for( unsigned int n = 0; n < n_names; n++ )
       var_names[n] = input(VariablesParsing::varnames_input_name(subsection), default_names[n], n);
   }
void GRINS::FEVariablesBase::set_neumann_bc_is_positive (bool is_positive) inline
Reset whetever Neumann bc is postive or not.
Postive means a value of 1.0 will be used in front of NeumannBC terms while is_positive = false indicates a value of -1.0 should be used.
Definition at line 145 of file fe_variables_base.h.
References _neumann_bc_sign.
Referenced by GRINS::SolidMechanicsAbstract::SolidMechanicsAbstract().
   {
     if(is_positive)
       _neumann_bc_sign = 1.0;
     else
       _neumann_bc_sign = -1.0;
   }
const std::vector<VariableIndex>& GRINS::FEVariablesBase::var_indices () const inline
Definition at line 87 of file fe_variables_base.h.
References _vars.
Referenced by GRINS::ParsedFunctionNeumannBCFactoryHelper< FunctionType >::build_neumman_func_common(), GRINS::CatalyticWallNeumannBCFactoryCommon< ImplType >::extract_species_vars(), and GRINS::CatalyticWallNeumannBCFactoryCommon< ImplType >::extract_temp_var().
     { return _vars; }
Member Data Documentation
std::vector<GRINSEnums::FEFamily> GRINS::FEVariablesBase::_family protected
Definition at line 125 of file fe_variables_base.h.
Referenced by GRINS::SingleFETypeVariable::init(), GRINS::SingleFETypeVariable::SingleFETypeVariable(), and GRINS::ThermoPressureFEVariable::ThermoPressureFEVariable().
bool GRINS::FEVariablesBase::_is_constraint_var protected
Tracks whether this is a constraint variable.
By constraint variable, we mean a variable that is effectively a Lagrange multiplier. The intended use case is to determine whether this variable requires boundary conditions to be specified (constraint variables do not).
Definition at line 135 of file fe_variables_base.h.
Referenced by is_constraint_var().
libMesh::Real GRINS::FEVariablesBase::_neumann_bc_sign protected
Track the sign of the Neumann BC term. Defaults to 1.0.
Depending on the Physics/Variable combination, the sign in front of the Neumann boundary term can change.
Definition at line 140 of file fe_variables_base.h.
Referenced by neumann_bc_sign(), and set_neumann_bc_is_positive().
std::vector<GRINSEnums::Order> GRINS::FEVariablesBase::_order protected
Definition at line 127 of file fe_variables_base.h.
Referenced by GRINS::SingleFETypeVariable::init(), GRINS::SingleFETypeVariable::SingleFETypeVariable(), and GRINS::ThermoPressureFEVariable::ThermoPressureFEVariable().
std::vector<std::string> GRINS::FEVariablesBase::_var_names protected
Definition at line 123 of file fe_variables_base.h.
Referenced by active_var_names(), GRINS::VelocityFEVariables::init(), GRINS::DisplacementFEVariables::init(), GRINS::SingleFETypeVariable::init(), GRINS::MultiVarSingleFETypeVariable::MultiVarSingleFETypeVariable(), GRINS::SpeciesMassFractionsFEVariables::n_species(), GRINS::SingleVarSingleFETypeVariable::SingleVarSingleFETypeVariable(), GRINS::SpeciesMassFractionsFEVariables::SpeciesMassFractionsFEVariables(), GRINS::DisplacementFEVariables::u_name(), GRINS::DisplacementFEVariables::v_name(), and GRINS::DisplacementFEVariables::w_name().
std::vector<VariableIndex> GRINS::FEVariablesBase::_vars protected
Definition at line 121 of file fe_variables_base.h.
Referenced by GRINS::SingleFETypeVariable::init(), GRINS::TurbulenceFEVariables::nu(), GRINS::PressureFEVariable::p(), GRINS::ThermoPressureFEVariable::p0(), GRINS::SpeciesMassFractionsFEVariables::species(), GRINS::PrimitiveTempFEVariables::T(), GRINS::VelocityFEVariables::u(), GRINS::DisplacementFEVariables::u(), GRINS::VelocityFEVariables::v(), GRINS::DisplacementFEVariables::v(), GRINS::GenericFETypeVariable::var(), var_indices(), GRINS::VelocityFEVariables::w(), and GRINS::DisplacementFEVariables::w().
The documentation for this class was generated from the following files:
src/variables/include/grins/fe_variables_base.h
src/variables/src/fe_variables_base.C