GRINS-0.8.0: GRINSTesting::MeshBuilderTest Class Reference
GRINSTesting::MeshBuilderTest Class Reference
Public Member Functions
CPPUNIT_TEST_SUITE (MeshBuilderTest)
CPPUNIT_TEST (test_build_1d_mesh)
CPPUNIT_TEST (test_build_2d_mesh)
CPPUNIT_TEST (test_build_3d_mesh)
CPPUNIT_TEST_SUITE_END ()
void test_build_1d_mesh ()
void test_build_2d_mesh ()
void test_build_3d_mesh ()
Private Member Functions
GRINS::SharedPtr< libMesh::UnstructuredMesh > build_mesh (const GetPot &input)
void test_elem_type (const libMesh::MeshBase &mesh, GRINSEnums::ElemType elem_type_expected)
Detailed Description
Definition at line 49 of file mesh_builder.C.
Member Function Documentation
GRINS::SharedPtr<libMesh::UnstructuredMesh> GRINSTesting::MeshBuilderTest::build_mesh (const GetPot & input) inline private
Definition at line 92 of file mesh_builder.C.
References GRINS::MeshBuilder::build(), and TestCommWorld.
Referenced by test_build_1d_mesh(), test_build_2d_mesh(), and test_build_3d_mesh().
     {
       GRINS::MeshBuilder mesh_builder;
       return mesh_builder.build( input, *TestCommWorld );
     }
GRINSTesting::MeshBuilderTest::CPPUNIT_TEST (test_build_1d_mesh)
GRINSTesting::MeshBuilderTest::CPPUNIT_TEST (test_build_2d_mesh)
GRINSTesting::MeshBuilderTest::CPPUNIT_TEST (test_build_3d_mesh)
GRINSTesting::MeshBuilderTest::CPPUNIT_TEST_SUITE (MeshBuilderTest)
GRINSTesting::MeshBuilderTest::CPPUNIT_TEST_SUITE_END ()
void GRINSTesting::MeshBuilderTest::test_build_1d_mesh () inline
Definition at line 62 of file mesh_builder.C.
References build_mesh(), and test_elem_type().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/mesh_build_1d.in";
       GetPot input(filename);
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = this->build_mesh(input);
       CPPUNIT_ASSERT_EQUAL((libMesh::dof_id_type)22,mesh->n_elem());
       this->test_elem_type(*mesh,GRINSEnums::EDGE2);
     }
void GRINSTesting::MeshBuilderTest::test_build_2d_mesh () inline
Definition at line 71 of file mesh_builder.C.
References build_mesh(), and test_elem_type().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/mesh_build_2d.in";
       GetPot input(filename);
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = this->build_mesh(input);
       CPPUNIT_ASSERT_EQUAL((libMesh::dof_id_type)100,mesh->n_elem());
       this->test_elem_type(*mesh,GRINSEnums::QUAD9);
     }
void GRINSTesting::MeshBuilderTest::test_build_3d_mesh () inline
Definition at line 81 of file mesh_builder.C.
References build_mesh(), and test_elem_type().
     {
       std::string filename = std::string(GRINS_TEST_UNIT_INPUT_SRCDIR)+"/mesh_build_3d.in";
       GetPot input(filename);
       GRINS::SharedPtr<libMesh::UnstructuredMesh> mesh = this->build_mesh(input);
       CPPUNIT_ASSERT_EQUAL((libMesh::dof_id_type)125,mesh->n_elem());
       this->test_elem_type(*mesh,GRINSEnums::HEX8);
     }
void GRINSTesting::MeshBuilderTest::test_elem_type (const libMesh::MeshBase & mesh, GRINSEnums::ElemType elem_type_expected) inline private
Definition at line 98 of file mesh_builder.C.
Referenced by test_build_1d_mesh(), test_build_2d_mesh(), and test_build_3d_mesh().
     {
       for( libMesh::MeshBase::const_element_iterator e = mesh.active_elements_begin();
            e != mesh.active_elements_end(); ++ e )
         {
           const libMesh::Elem* elem = *e;
           GRINSEnums::ElemType elem_type_computed = elem->type();
           CPPUNIT_ASSERT_EQUAL( elem_type_expected, elem_type_computed);
         }
     }
The documentation for this class was generated from the following file:
test/unit/mesh_builder.C