GRINS-0.8.0: GRINS::ConstantViscosity Class Reference
GRINS::ConstantViscosity Class Reference
#include <constant_viscosity.h>
Public Member Functions
ConstantViscosity (const GetPot &input, const std::string &material)
Constructor with specified material.
ConstantViscosity (const GetPot &input)
Deprecated constructor.
virtual ~ConstantViscosity ()
libMesh::Real operator() () const
libMesh::Real operator() (AssemblyContext &context, unsigned int qp) const
libMesh::Real operator() (const libMesh::Point &p, const libMesh::Real time)
libMesh::Real operator() (const libMesh::Real T) const
libMesh::Real deriv (const libMesh::Real T) const
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Public Member Functions inherited from GRINS::ViscosityBase
ViscosityBase ()
virtual ~ViscosityBase ()
Private Member Functions
ConstantViscosity ()
Private Attributes
libMesh::Real _mu
Additional Inherited Members
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Member Functions inherited from GRINS::ViscosityBase
void check_input_consistency (const GetPot &input, const std::string &material) const
void old_mu_warning () const
Detailed Description
Definition at line 43 of file constant_viscosity.h.
Constructor & Destructor Documentation
GRINS::ConstantViscosity::ConstantViscosity (const GetPot & input, const std::string & material)
Constructor with specified material.
Will look in the input file for [Materials/material/Viscosity/value] for the value of viscosity.
Definition at line 65 of file constant_viscosity.C.
References _mu, GRINS::ViscosityBase::check_input_consistency(), grins_warning, GRINS::PhysicsNaming::incompressible_navier_stokes(), GRINS::ViscosityBase::old_mu_warning(), and GRINS::ParameterUser::set_parameter().
     : ParameterUser("ConstantViscosity"),
       ViscosityBase(),
       _mu( 0.0 ) // Initialize to nonsense value
   {
     this->check_input_consistency(input,material);
     if( input.have_variable("Materials/"+material+"/Viscosity/value") &&
         input.have_variable("Physics/"+PhysicsNaming::incompressible_navier_stokes()+"/mu") )
       {
         libmesh_error_msg("Error: Cannot specify both Materials/"+material+"/Viscosity/value and Physics/"+PhysicsNaming::incompressible_navier_stokes()+"/mu");
       }
     // If we have the "new" version, then parse it
     if( input.have_variable("Materials/"+material+"/Viscosity/value") )
       {
         this->set_parameter
           (_mu, input, "Materials/"+material+"/Viscosity/value", _mu);
       }
     // If instead we have the old version, use that.
     else if( input.have_variable("Materials/Viscosity/mu") )
       {
         this->old_mu_warning();
         this->set_parameter
           (_mu, input, "Materials/Viscosity/mu", _mu);
       }
     /* If we don't have the new version of materials parsing or
        explicitly have the old version, we're assuming an even older
        version. Both of the older versions are deprecated. */
     else if( !input.have_variable("Materials/Viscosity/mu") &&
              !input.have_variable("Materials/"+material+"/Viscosity/value") )
       {
         std::string warning = "WARNING: No Materials/Viscosity/mu or\n";
         warning += "       Materials/"+material+"/Viscosity/value specified!\n";
         warning += "       We are assuming then that you want to specify through\n";
         warning += "       Physics/"+PhysicsNaming::incompressible_navier_stokes()+"/mu.\n";
         warning += "       This is DEPRECATED. Please updated to use Materials/"+material+"/Viscosity/value.\n";
         grins_warning(warning);
         // Try and get the viscosity from other specifications
         this->set_parameter
           (_mu, input, "Physics/"+PhysicsNaming::incompressible_navier_stokes()+"/mu", _mu);
       }
     else
       {
         // This shouldn't happen
         libmesh_error();
       }
     // We'd better have postive viscosity when we're all done.
     libmesh_assert_greater( _mu, 0.0 );
   }
GRINS::ConstantViscosity::ConstantViscosity (const GetPot & input)
Deprecated constructor.
Definition at line 39 of file constant_viscosity.C.
References _mu, grins_warning, GRINS::PhysicsNaming::incompressible_navier_stokes(), and GRINS::ParameterUser::set_parameter().
     : ParameterUser("ConstantViscosity"),
       ViscosityBase(),
       _mu(1.0)
   {
     // Warning about this constructor being deprecated
     {
       std::string warning = "WARNING: Use of this constructor is DEPRECATED.\n";
       warning += "         Please update to use constructor with input material name.\n";
       grins_warning(warning);
     }
     if( !input.have_variable("Materials/Viscosity/mu") )
       {
         libmesh_warning("No Materials/Viscosity/mu specified!\n");
         // Try and get the viscosity from other specifications
         this->set_parameter
           (_mu, input, "Physics/"+PhysicsNaming::incompressible_navier_stokes()+"/mu", _mu);
       }
     else
       {
         this->set_parameter
           (_mu, input, "Materials/Viscosity/mu", _mu);
       }
   }
GRINS::ConstantViscosity::~ConstantViscosity () virtual
Definition at line 119 of file constant_viscosity.C.
   {
     return;
   }
GRINS::ConstantViscosity::ConstantViscosity () private
Member Function Documentation
libMesh::Real GRINS::ConstantViscosity::deriv (const libMesh::Real T) const inline
Definition at line 102 of file constant_viscosity.h.
   {
     return 0.0;
   }
libMesh::Real GRINS::ConstantViscosity::operator() () const inline
Definition at line 77 of file constant_viscosity.h.
References _mu.
   {
     return _mu;
   }
libMesh::Real GRINS::ConstantViscosity::operator() (AssemblyContext & context, unsigned int qp) const inline
Definition at line 83 of file constant_viscosity.h.
References _mu.
   {
     return _mu;
   }
libMesh::Real GRINS::ConstantViscosity::operator() (const libMesh::Point & p, const libMesh::Real time) inline
Definition at line 89 of file constant_viscosity.h.
References _mu.
   {
     return _mu;
   }
libMesh::Real GRINS::ConstantViscosity::operator() (const libMesh::Real T) const inline
Definition at line 96 of file constant_viscosity.h.
   {
     return (*this)();
   }
Member Data Documentation
libMesh::Real GRINS::ConstantViscosity::_mu private
Definition at line 71 of file constant_viscosity.h.
Referenced by ConstantViscosity(), and operator()().
The documentation for this class was generated from the following files:
src/properties/include/grins/constant_viscosity.h
src/properties/src/constant_viscosity.C