GRINS-0.8.0: GRINS::HITRAN Class Reference
GRINS::HITRAN Class Reference
HITRAN interface object.
#include <hitran.h>
Public Member Functions
HITRAN (const std::string &data_file, const std::string &partition_function_file, libMesh::Real T_min, libMesh::Real T_max, libMesh::Real T_step)
Constructor.
unsigned int isotopologue (unsigned int index)
Isotopologue ID.
libMesh::Real nu0 (unsigned int index)
Linecenter wavenumber [ ].
libMesh::Real sw (unsigned int index)
Linestrength [ ].
libMesh::Real gamma_air (unsigned int index)
Air-broadening half-width [ ].
libMesh::Real gamma_self (unsigned int index)
Self-broadening half-wdith [ ].
libMesh::Real elower (unsigned int index)
Lower state energy of transition [ ].
libMesh::Real n_air (unsigned int index)
Temperature coefficient [].
libMesh::Real delta_air (unsigned int index)
Air pressure-induced line shift [ ].
libMesh::Real partition_function (libMesh::Real T, unsigned int iso)
unsigned int get_data_size ()
Return the data size.
libMesh::Real partition_function_derivative (libMesh::Real T, unsigned int iso)
Finite difference derivative for partition function.
Protected Member Functions
int T_index (libMesh::Real T)
Find the index into _T corresponding to the given temperature.
libMesh::Real get_partition_function_value (libMesh::Real T, unsigned int iso)
Search through the partition function data to get value for given temperature.
libMesh::Real interpolate_values (int index_r, libMesh::Real T_star, const std::vector< libMesh::Real > &y) const
Linear interpolation helper function.
HITRAN ()
User should not call empty constructor.
Protected Attributes
libMesh::Real _Tmin
libMesh::Real _Tmax
libMesh::Real _Tstep
int _data_size
Size of spectroscopic data.
int _q_size
Size of partition function data.
libMesh::Real _T0
Reference temperature (296K)
std::vector< libMesh::Real > _qT0
std::vector< unsigned int > _isotop
std::vector< libMesh::Real > _nu
std::vector< libMesh::Real > _sw
std::vector< libMesh::Real > _gamma_air
std::vector< libMesh::Real > _gamma_self
std::vector< libMesh::Real > _elower
std::vector< libMesh::Real > _n
std::vector< libMesh::Real > _delta_air
std::vector< std::vector< libMesh::Real > > _qT
Vector for partition function values for all isotopologues.
Detailed Description
HITRAN interface object.
This class provides an interface to utilize data from the HITRAN Spectroscopic Database. Data can be pulled directly from the HITRAN website, or through the HITRAN python API, HAPI.
Two files must be provided to this class, one with various data members, and one with values of the partition function at various temperatures.
The data file must contain comma-separated values for individual spectrscopic lines in the following format:
Isotopologue,Linecenter,Linestrength,Air-broadened Half Width,Self-Broadened Half Width,Lower State Energy,Temperature Coefficient,Air-Pressure Shift
The partition function file must contain comma-separated values for each isotopologue at the same temperature values. The temperature limits themselves are specified as inputs to the constructor.
Note the partition function data must explicitly include a value at the given reference temperature, which is currently 296K for HITRAN.
The basic units for values are those given by HITRAN, which currently are [cm] and [atm]
Definition at line 58 of file hitran.h.
Constructor & Destructor Documentation
GRINS::HITRAN::HITRAN (const std::string & data_file, const std::string & partition_function_file, libMesh::Real T_min, libMesh::Real T_max, libMesh::Real T_step)
Constructor.
Parameters
data_file A file containing values for the required quantities, formatted as described above
partition_function_file A file containing partition function values, formatted as described above
T_min The minimum temperature for the partition function values, inclusive
T_max The maximum temperature for the partition function values, inclusive
T_step The step between successive temperature values
Definition at line 40 of file hitran.C.
References _data_size, _delta_air, _elower, _gamma_air, _gamma_self, _isotop, _n, _nu, _q_size, _qT, _qT0, _sw, _T0, and GRINS::StringUtilities::split_string_real().
     : _Tmin(T_min),
       _Tmax(T_max),
       _Tstep(T_step),
       _T0(296.0)
   {
     // sanity checks on temperature range specification
     if ( (T_min<0.0) || (T_min>=T_max) || (T_step<=0.0) || (T_min>_T0) || (T_max<_T0) )
       {
         std::stringstream ss;
         ss <<"Invalid specification of temperature range:" <<std::endl;
         ss <<"T_min: " <<T_min <<std::endl;
         ss <<"T_max: " <<T_max <<std::endl;
         ss <<"T_step: " <<T_step <<std::endl;
         libmesh_error_msg(ss.str());
       }
     // open data file
     std::ifstream hitran_file;
     hitran_file.open(data_file);
     if (!hitran_file.is_open())
       {
         std::stringstream ss;
         ss <<"Unable to open provided hitran_file: " <<data_file <<std::endl;
         libmesh_error_msg(ss.str());
       }
     while(!hitran_file.eof())
       {
         std::string line;
         getline(hitran_file,line);
         if (line == "")
           continue;
         std::vector<libMesh::Real> vals;
         GRINS::StringUtilities::split_string_real(line,",",vals);
         libmesh_assert_equal_to(vals.size(),8);
         // HITRAN gives isotopologue numbers starting at 1
         // shift to zero-based to make indexing easier
         _isotop.push_back(static_cast<unsigned int>(vals[0]-1));
         _nu.push_back(vals[1]);
         _sw.push_back(vals[2]);
         _gamma_air.push_back(vals[3]);
         _gamma_self.push_back(vals[4]);
         _elower.push_back(vals[5]);
         _n.push_back(vals[6]);
         _delta_air.push_back(vals[7]);
       }
     // sanity checks
     libmesh_assert_equal_to( _isotop.size(), _nu.size() );
     libmesh_assert_equal_to( _nu.size(), _sw.size() );
     libmesh_assert_equal_to( _sw.size(), _gamma_air.size() );
     libmesh_assert_equal_to( _gamma_air.size(), _gamma_self.size() );
     libmesh_assert_equal_to( _gamma_self.size(), _elower.size() );
     libmesh_assert_equal_to( _elower.size(), _n.size() );
     libmesh_assert_equal_to( _n.size(), _delta_air.size() );
     // save data length and close HITRAN data file
     _data_size = _isotop.size(); // all data vectors are the same length
     hitran_file.close();
     // file with partition function values
     std::ifstream qT_file;
     qT_file.open(partition_function_file);
     if (!qT_file.is_open())
       {
         std::stringstream ss;
         ss <<"Unable to open provided partition_function_file: " <<partition_function_file <<std::endl;
         libmesh_error_msg(ss.str());
       }
     // number of temperature values
     unsigned int num_T = (T_max-T_min)/T_step + 1;
     // read the partition function values
     unsigned int counter = 0;
     while(!qT_file.eof())
       {
         std::string line;
         getline(qT_file,line);
         if (line == "")
           continue;
         _qT.push_back(std::vector<libMesh::Real>());
         GRINS::StringUtilities::split_string_real(line,",",_qT[counter]);
         // we should have a partition function value for each temperature
         libmesh_assert_equal_to(num_T,_qT[counter].size());
         counter++;
       }
     // save length and close partition sum file
     _q_size = num_T;
     qT_file.close();
     // cache the partition function values at the referece temperature
     for(unsigned int i=0; i<_qT.size(); i++)
       _qT0.push_back(this->get_partition_function_value(_T0,i));
     return;
   }
GRINS::HITRAN::HITRAN () protected
User should not call empty constructor.
Member Function Documentation
libMesh::Real GRINS::HITRAN::delta_air (unsigned int index)
Air pressure-induced line shift [ ].
Definition at line 228 of file hitran.C.
References _delta_air.
Referenced by GRINSTesting::HITRANtest::parse_from_file().
   {
     libmesh_assert_less(index,_delta_air.size());
     return _delta_air[index];
   }
libMesh::Real GRINS::HITRAN::elower (unsigned int index)
Lower state energy of transition [ ].
Definition at line 216 of file hitran.C.
References _elower.
Referenced by GRINSTesting::HITRANtest::parse_from_file().
   {
     libmesh_assert_less(index,_elower.size());
     return _elower[index];
   }
libMesh::Real GRINS::HITRAN::gamma_air (unsigned int index)
Air-broadening half-width [ ].
Definition at line 204 of file hitran.C.
References _gamma_air.
Referenced by GRINSTesting::HITRANtest::parse_from_file().
   {
     libmesh_assert_less(index,_gamma_air.size());
     return _gamma_air[index];
   }
libMesh::Real GRINS::HITRAN::gamma_self (unsigned int index)
Self-broadening half-wdith [ ].
Definition at line 210 of file hitran.C.
References _gamma_self.
Referenced by GRINSTesting::HITRANtest::parse_from_file().
   {
     libmesh_assert_less(index,_gamma_self.size());
     return _gamma_self[index];
   }
unsigned int GRINS::HITRAN::get_data_size ()
Return the data size.
Definition at line 153 of file hitran.C.
References _data_size.
   {
     return _data_size;
   }
libMesh::Real GRINS::HITRAN::get_partition_function_value (libMesh::Real T, unsigned int iso) protected
Search through the partition function data to get value for given temperature.
Definition at line 246 of file hitran.C.
References _qT, interpolate_values(), and T_index().
Referenced by partition_function().
   {
     libMesh::Real retval = -1.0;
     int i = T_index(T);
     if (i >= 0)
       retval = this->interpolate_values(i,T,_qT[iso]);
     else
       {
         std::stringstream ss;
         ss <<"Error: Temperature " <<T <<"K does not exist in the given partition sum data" <<std::endl;
         libmesh_error_msg(ss.str());
       }
     return retval;
   }
libMesh::Real GRINS::HITRAN::interpolate_values (int index_r, libMesh::Real T_star, const std::vector< libMesh::Real > & y) const protected
Linear interpolation helper function.
Definition at line 271 of file hitran.C.
References _Tmax, _Tmin, and _Tstep.
Referenced by get_partition_function_value().
   {
     if ( (T_star>_Tmax) || (T_star<_Tmin) )
       {
         std::stringstream ss;
         ss <<"Error, temperature T=" <<T_star <<" is outside the specified range of provided partition function values" <<std::endl;
         libmesh_error_msg(ss.str());
       }
     libMesh::Real T = _Tmin + (_Tstep*index_r);
     return y[index_r-1] + ( (T_star-(T-_Tstep))*(y[index_r]-y[index_r-1]) )/(T-(T-_Tstep));
   }
unsigned int GRINS::HITRAN::isotopologue (unsigned int index)
Isotopologue ID.
Definition at line 186 of file hitran.C.
References _isotop.
Referenced by GRINSTesting::HITRANtest::parse_from_file().
   {
     libmesh_assert_less(index,_isotop.size());
     return _isotop[index];
   }
libMesh::Real GRINS::HITRAN::n_air (unsigned int index)
Temperature coefficient [].
Definition at line 222 of file hitran.C.
References _n.
Referenced by GRINSTesting::HITRANtest::parse_from_file().
   {
     libmesh_assert_less(index,_n.size());
     return _n[index];
   }
libMesh::Real GRINS::HITRAN::nu0 (unsigned int index)
Linecenter wavenumber [ ].
Definition at line 192 of file hitran.C.
References _nu.
Referenced by GRINSTesting::HITRANtest::parse_from_file().
   {
     libmesh_assert_less(index,_nu.size());
     return _nu[index];
   }
libMesh::Real GRINS::HITRAN::partition_function (libMesh::Real T, unsigned int iso)
Returns the value of the partition function of the given isotopologue at the given temperature
Definition at line 234 of file hitran.C.
References _qT0, _T0, and get_partition_function_value().
Referenced by GRINSTesting::HITRANtest::parse_from_file(), and partition_function_derivative().
   {
     libMesh::Real qt;
     if (T==_T0)
       qt = _qT0[iso];
     else
       qt = this->get_partition_function_value(T,iso);
     return qt;
   }
libMesh::Real GRINS::HITRAN::partition_function_derivative (libMesh::Real T, unsigned int iso)
Finite difference derivative for partition function.
Definition at line 158 of file hitran.C.
References _Tmax, _Tmin, _Tstep, and partition_function().
   {
     libMesh::Real deriv = -1.0;
     if (std::abs(T-_Tmin)<libMesh::TOLERANCE) // 1st order forward difference
       {
         libMesh::Real QT0 = this->partition_function(_Tmin,iso);
         libMesh::Real QT1 = this->partition_function(_Tmin+_Tstep,iso);
         deriv  = (QT1-QT0)/_Tstep;
       }
     else if (std::abs(T-_Tmax)<libMesh::TOLERANCE) // 1st order backward difference
       {
         libMesh::Real QT0 = this->partition_function(_Tmax-_Tstep,iso);
         libMesh::Real QT1 = this->partition_function(_Tmax,iso);
         deriv = (QT1-QT0)/_Tstep;
       }
     else // 2nd order central difference
       {
         libMesh::Real QT1 = this->partition_function(T+_Tstep,iso);
         libMesh::Real QT0 = this->partition_function(T-_Tstep,iso);
         deriv = (QT1-QT0)/(2.0*_Tstep);
       }
     return deriv;
   }
libMesh::Real GRINS::HITRAN::sw (unsigned int index)
Linestrength [ ].
Definition at line 198 of file hitran.C.
References _sw.
Referenced by GRINSTesting::HITRANtest::parse_from_file().
   {
     libmesh_assert_less(index,_sw.size());
     return _sw[index];
   }
int GRINS::HITRAN::T_index (libMesh::Real T) protected
Find the index into _T corresponding to the given temperature.
Definition at line 264 of file hitran.C.
References _Tmin, and _Tstep.
Referenced by get_partition_function_value().
   {
     unsigned int index = std::ceil((T-_Tmin)/_Tstep);
     index = std::max(index,(unsigned int)1);
     return index;
   }
Member Data Documentation
int GRINS::HITRAN::_data_size protected
Size of spectroscopic data.
Definition at line 110 of file hitran.h.
Referenced by get_data_size(), and HITRAN().
std::vector<libMesh::Real> GRINS::HITRAN::_delta_air protected
Definition at line 130 of file hitran.h.
Referenced by delta_air(), and HITRAN().
std::vector<libMesh::Real> GRINS::HITRAN::_elower protected
Definition at line 128 of file hitran.h.
Referenced by elower(), and HITRAN().
std::vector<libMesh::Real> GRINS::HITRAN::_gamma_air protected
Definition at line 126 of file hitran.h.
Referenced by gamma_air(), and HITRAN().
std::vector<libMesh::Real> GRINS::HITRAN::_gamma_self protected
Definition at line 127 of file hitran.h.
Referenced by gamma_self(), and HITRAN().
std::vector<unsigned int> GRINS::HITRAN::_isotop protected
Definition at line 123 of file hitran.h.
Referenced by HITRAN(), and isotopologue().
std::vector<libMesh::Real> GRINS::HITRAN::_n protected
Definition at line 129 of file hitran.h.
Referenced by HITRAN(), and n_air().
std::vector<libMesh::Real> GRINS::HITRAN::_nu protected
Definition at line 124 of file hitran.h.
Referenced by HITRAN(), and nu0().
int GRINS::HITRAN::_q_size protected
Size of partition function data.
Definition at line 113 of file hitran.h.
Referenced by HITRAN().
std::vector<std::vector<libMesh::Real> > GRINS::HITRAN::_qT protected
Vector for partition function values for all isotopologues.
Definition at line 133 of file hitran.h.
Referenced by get_partition_function_value(), and HITRAN().
std::vector<libMesh::Real> GRINS::HITRAN::_qT0 protected
Value of partition function at reference temperature for all isotopologues. Cached since it is used frequently
Definition at line 120 of file hitran.h.
Referenced by HITRAN(), and partition_function().
std::vector<libMesh::Real> GRINS::HITRAN::_sw protected
Definition at line 125 of file hitran.h.
Referenced by HITRAN(), and sw().
libMesh::Real GRINS::HITRAN::_T0 protected
Reference temperature (296K)
Definition at line 116 of file hitran.h.
Referenced by HITRAN(), and partition_function().
libMesh::Real GRINS::HITRAN::_Tmax protected
Definition at line 107 of file hitran.h.
Referenced by interpolate_values(), and partition_function_derivative().
libMesh::Real GRINS::HITRAN::_Tmin protected
Definition at line 107 of file hitran.h.
Referenced by interpolate_values(), partition_function_derivative(), and T_index().
libMesh::Real GRINS::HITRAN::_Tstep protected
Definition at line 107 of file hitran.h.
Referenced by interpolate_values(), partition_function_derivative(), and T_index().
The documentation for this class was generated from the following files:
src/qoi/include/grins/hitran.h
src/qoi/src/hitran.C