GRINS-0.7.0: GRINS::SpalartAllmarasHelper Class Reference
GRINS::SpalartAllmarasHelper Class Reference
#include <spalart_allmaras_helper.h>
Public Member Functions
SpalartAllmarasHelper (const GetPot &input)
virtual ~SpalartAllmarasHelper ()
void init_variables (libMesh::FEMSystem *system)
libMesh::Real vorticity (AssemblyContext &context, unsigned int qp) const
Protected Attributes
unsigned int _dim
const VelocityFEVariables & _flow_vars
const PressureFEVariable & _press_var
Private Member Functions
SpalartAllmarasHelper ()
Detailed Description
Definition at line 41 of file spalart_allmaras_helper.h.
Constructor & Destructor Documentation
GRINS::SpalartAllmarasHelper::SpalartAllmarasHelper (const GetPot & input)
Definition at line 47 of file spalart_allmaras_helper.C.
     : _flow_vars(GRINSPrivate::VariableWarehouse::get_variable_subclass<VelocityFEVariables>(VariablesParsing::velocity_section())),
       _press_var(GRINSPrivate::VariableWarehouse::get_variable_subclass<PressureFEVariable>(VariablesParsing::pressure_section()))
   {}
virtual GRINS::SpalartAllmarasHelper::~SpalartAllmarasHelper () inline virtual
Definition at line 47 of file spalart_allmaras_helper.h.
 {};
GRINS::SpalartAllmarasHelper::SpalartAllmarasHelper () private
Member Function Documentation
void GRINS::SpalartAllmarasHelper::init_variables (libMesh::FEMSystem * system)
Definition at line 52 of file spalart_allmaras_helper.C.
References _dim.
Referenced by GRINS::SpalartAllmarasStabilizationHelper::init().
   {
     this->_dim = system->get_mesh().mesh_dimension();
   }
libMesh::Real GRINS::SpalartAllmarasHelper::vorticity (AssemblyContext & context, unsigned int qp) const
Definition at line 57 of file spalart_allmaras_helper.C.
References _dim, _flow_vars, GRINS::VelocityFEVariables::u(), GRINS::VelocityFEVariables::v(), and GRINS::VelocityFEVariables::w().
Referenced by GRINS::SpalartAllmarasStabilizationHelper::compute_res_spalart_steady().
   {
     libMesh::Gradient grad_u, grad_v;
     grad_u = context.interior_gradient(this->_flow_vars.u(), qp);
     grad_v = context.interior_gradient(this->_flow_vars.v(), qp);
     libMesh::Real vorticity_value;
     vorticity_value = fabs(grad_v(0) - grad_u(1));
     if(this->_dim == 3)
       {
         libMesh::Gradient grad_w;
         grad_w = context.interior_gradient(this->_flow_vars.w(), qp);
         libMesh::Real vorticity_component_0 = grad_w(1) - grad_v(2);
         libMesh::Real vorticity_component_1 = grad_u(2) - grad_v(0);
         libMesh::Real term = vorticity_component_0*vorticity_component_0
           + vorticity_component_1*vorticity_component_1
           + vorticity_value*vorticity_value;
         vorticity_value += std::sqrt(term);
       }
     return vorticity_value;
   }
Member Data Documentation
unsigned int GRINS::SpalartAllmarasHelper::_dim protected
Definition at line 57 of file spalart_allmaras_helper.h.
Referenced by init_variables(), and vorticity().
const VelocityFEVariables& GRINS::SpalartAllmarasHelper::_flow_vars protected
Definition at line 60 of file spalart_allmaras_helper.h.
Referenced by vorticity().
const PressureFEVariable& GRINS::SpalartAllmarasHelper::_press_var protected
Definition at line 61 of file spalart_allmaras_helper.h.
The documentation for this class was generated from the following files:
src/physics/include/grins/spalart_allmaras_helper.h
src/physics/src/spalart_allmaras_helper.C