GRINS-0.8.0: GRINS::AntiochChemistry Class Reference
GRINS::AntiochChemistry Class Reference
Wrapper class for Antioch::ChemicalMixture.
#include <antioch_chemistry.h>
Public Member Functions
AntiochChemistry (const GetPot &input, const std::string &material)
Deprecated Constructor.
AntiochChemistry (libMesh::UniquePtr< Antioch::ChemicalMixture< libMesh::Real > > &chem_mixture)
User passes in built ChemicalMixture and this class takes ownership.
virtual ~AntiochChemistry ()
libMesh::Real M (unsigned int species) const
Species molar mass (molecular weight), [kg/mol].
libMesh::Real M_mix (const std::vector< libMesh::Real > &mass_fractions) const
Mixture molar mass (molecular weight), [kg/mol].
libMesh::Real R (unsigned int species) const
Species gas constant, [J/kg-K].
libMesh::Real R_mix (const std::vector< libMesh::Real > &mass_fractions) const
Mixture gas constant, [J/kg-K].
libMesh::Real X (unsigned int species, libMesh::Real M, libMesh::Real mass_fraction) const
Species mole fraction, unitless.
void X (libMesh::Real M, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &mole_fractions) const
Mole fraction for all species, unitless.
libMesh::Real molar_density (const unsigned int species, const libMesh::Real rho, const libMesh::Real mass_fraction) const
Species molar density, [mol/m^3].
void molar_densities (const libMesh::Real rho, const std::vector< libMesh::Real > &mass_fractions, std::vector< libMesh::Real > &molar_densities) const
Molar density for all species, [mol/m^3].
unsigned int n_species () const
unsigned int species_index (const std::string &species_name) const
std::string species_name (unsigned int species_index) const
const Antioch::ChemicalMixture< libMesh::Real > & chemical_mixture () const
Accessor to underlying Antioch object.
const AntiochChemistry & chemistry () const
Accessor for this class.
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Protected Attributes
libMesh::UniquePtr< Antioch::ChemicalMixture< libMesh::Real > > _antioch_gas
Private Member Functions
AntiochChemistry ()
Additional Inherited Members
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Detailed Description
Wrapper class for Antioch::ChemicalMixture.
This class is expected to be constructed before threads have been forked and will live during the whole program. By default, Antioch is working in SI units. Note that this documentation will always be built regardless if Antioch is included in the GRINS build or not. Check configure output to confirm that Antioch was included in the build.
Definition at line 59 of file antioch_chemistry.h.
Constructor & Destructor Documentation
GRINS::AntiochChemistry::AntiochChemistry (const GetPot & input, const std::string & material)
Deprecated Constructor.
Definition at line 44 of file antioch_chemistry.C.
References _antioch_gas, and GRINS::MaterialsParsing::parse_chemical_species().
     : ParameterUser("AntiochChemistry")
   {
     {
       std::string warning = "==============================================\n";
       warning += "WARNING: This AntiochChemistry constructor is DEPREACTED!\n";
       warning += "         Prefer alternate constructor where parsing\n";
       warning += "         is done outside this class.\n";
       warning += "==============================================\n";
       libmesh_warning(warning);
     }
     std::vector<std::string> species_list;
     MaterialsParsing::parse_chemical_species(input,material,species_list);
     bool verbose_antioch_read = input("Materials/"+material+"/GasMixture/Antioch/verbose_read",false);
     std::string species_data_filename = input("Materials/"+material+"/GasMixture/Antioch/species_data", "default" );
     if( species_data_filename == std::string("default") )
       species_data_filename = Antioch::DefaultInstallFilename::chemical_mixture();
     std::string vibration_data_filename = input("Materials/"+material+"/GasMixture/Antioch/vibration_data", "default" );
     if( vibration_data_filename == std::string("default") )
       vibration_data_filename = Antioch::DefaultInstallFilename::vibrational_data();
     std::string electronic_data_filename = input("Materials/"+material+"/GasMixture/Antioch/electronic_data", "default" );
     if( electronic_data_filename == std::string("default") )
       electronic_data_filename = Antioch::DefaultInstallFilename::electronic_data();
     // By default, Antioch is using its ASCII parser. We haven't added more options yet.
     _antioch_gas.reset( new Antioch::ChemicalMixture<libMesh::Real>( species_list,
                                                                      verbose_antioch_read,
                                                                      species_data_filename,
                                                                      vibration_data_filename,
                                                                      electronic_data_filename ) );
   }
GRINS::AntiochChemistry::AntiochChemistry (libMesh::UniquePtr< Antioch::ChemicalMixture< libMesh::Real > > & chem_mixture)
User passes in built ChemicalMixture and this class takes ownership.
Todo:
Use std::move when we have C++11
Definition at line 83 of file antioch_chemistry.C.
     : ParameterUser("AntiochChemistry")
   {
     _antioch_gas.reset( chem_mixture.release() );
   }
virtual GRINS::AntiochChemistry::~AntiochChemistry () inline virtual
Definition at line 69 of file antioch_chemistry.h.
 {}
GRINS::AntiochChemistry::AntiochChemistry () private
Member Function Documentation
const Antioch::ChemicalMixture< libMesh::Real > & GRINS::AntiochChemistry::chemical_mixture () const inline
Accessor to underlying Antioch object.
Definition at line 177 of file antioch_chemistry.h.
References _antioch_gas.
Referenced by GRINS::AntiochEvaluator< Antioch::CEACurveFit< libMesh::Real >, Thermo >::specialized_build_thermo().
   {
     return *_antioch_gas.get();
   }
const AntiochChemistry & GRINS::AntiochChemistry::chemistry () const inline
Accessor for this class.
Definition at line 200 of file antioch_chemistry.h.
   {
     return *this;
   }
libMesh::Real GRINS::AntiochChemistry::M (unsigned int species) const inline
Species molar mass (molecular weight), [kg/mol].
Definition at line 125 of file antioch_chemistry.h.
References _antioch_gas.
   {
     return _antioch_gas->M(species);
   }
libMesh::Real GRINS::AntiochChemistry::M_mix (const std::vector< libMesh::Real > & mass_fractions) const inline
Mixture molar mass (molecular weight), [kg/mol].
Definition at line 131 of file antioch_chemistry.h.
References _antioch_gas.
   {
     return _antioch_gas->M(mass_fractions);
   }
void GRINS::AntiochChemistry::molar_densities (const libMesh::Real rho, const std::vector< libMesh::Real > & mass_fractions, std::vector< libMesh::Real > & molar_densities) const inline
Molar density for all species, [mol/m^3].
Definition at line 191 of file antioch_chemistry.h.
References _antioch_gas.
   {
     _antioch_gas->molar_densities( rho, mass_fractions, molar_densities );
     return;
   }
libMesh::Real GRINS::AntiochChemistry::molar_density (const unsigned int species, const libMesh::Real rho, const libMesh::Real mass_fraction) const inline
Species molar density, [mol/m^3].
Definition at line 183 of file antioch_chemistry.h.
References _antioch_gas.
   {
     return _antioch_gas->molar_density( species, rho, mass_fraction );
   }
unsigned int GRINS::AntiochChemistry::n_species () const inline
Definition at line 165 of file antioch_chemistry.h.
References _antioch_gas.
Referenced by do_transport_eval(), and main().
   {
     return _antioch_gas->n_species();
   }
libMesh::Real GRINS::AntiochChemistry::R (unsigned int species) const inline
Species gas constant, [J/kg-K].
R_universal/M(species)
Definition at line 137 of file antioch_chemistry.h.
References _antioch_gas.
   {
     return _antioch_gas->R(species);
   }
libMesh::Real GRINS::AntiochChemistry::R_mix (const std::vector< libMesh::Real > & mass_fractions) const inline
Mixture gas constant, [J/kg-K].
Definition at line 143 of file antioch_chemistry.h.
References _antioch_gas.
Referenced by main().
   {
     return _antioch_gas->R(mass_fractions);
   }
unsigned int GRINS::AntiochChemistry::species_index (const std::string & species_name) const inline
Definition at line 171 of file antioch_chemistry.h.
References _antioch_gas.
   {
     return _antioch_gas->species_name_map().find(species_name)->second;
   }
std::string GRINS::AntiochChemistry::species_name (unsigned int species_index) const
Definition at line 90 of file antioch_chemistry.C.
References _antioch_gas.
Referenced by do_transport_eval(), and main().
   {
     libmesh_assert_less(species_index, _antioch_gas->n_species());
     return _antioch_gas->species_inverse_name_map().find(species_index)->second;
   }
libMesh::Real GRINS::AntiochChemistry::X (unsigned int species, libMesh::Real M, libMesh::Real mass_fraction) const inline
Species mole fraction, unitless.
Definition at line 149 of file antioch_chemistry.h.
References _antioch_gas.
   {
     return _antioch_gas->X(species,M,mass_fraction);
   }
void GRINS::AntiochChemistry::X (libMesh::Real M, const std::vector< libMesh::Real > & mass_fractions, std::vector< libMesh::Real > & mole_fractions) const inline
Mole fraction for all species, unitless.
Definition at line 156 of file antioch_chemistry.h.
References _antioch_gas.
   {
     _antioch_gas->X(M,mass_fractions,mole_fractions);
     return;
   }
Member Data Documentation
libMesh::UniquePtr<Antioch::ChemicalMixture<libMesh::Real> > GRINS::AntiochChemistry::_antioch_gas protected
Definition at line 115 of file antioch_chemistry.h.
Referenced by AntiochChemistry(), chemical_mixture(), M(), M_mix(), molar_densities(), molar_density(), n_species(), R(), R_mix(), GRINS::AntiochMixtureAveragedTransportMixture< KineticsThermoCurveFit, Thermo, Viscosity, Conductivity, Diffusivity >::specialized_build_thermo(), species_index(), species_name(), and X().
The documentation for this class was generated from the following files:
src/properties/include/grins/antioch_chemistry.h
src/properties/src/antioch_chemistry.C