GRINS-0.8.0: GRINS::Runner Class Reference
GRINS::Runner Class Reference
Class to encapsulate initializing and running GRINS Simulation.
#include <runner.h>
Public Member Functions
Runner (int argc, char *argv[])
Setup input objects.
~Runner ()
const GetPot & get_input_file () const
const GetPot & get_command_line () const
Simulation & get_simulation ()
const Simulation & get_simulation () const
const libMesh::LibMeshInit & get_libmesh_init () const
void init ()
Initialize the Simulation objects.
void run ()
Runs the simulation that was setup at construction time.
Protected Member Functions
void echo_version_info (std::ostream &out, int argc, char *argv[])
Echo GRINS, libMesh version info as well as command line.
std::string check_and_get_inputfile (int argc, char *argv[], GetPot &command_line)
Check (and error if not found) and then return GetPot input file name.
void check_for_unused_vars (const GetPot &input, bool warning_only)
Check for any unused variables in GetPot input file.
Protected Attributes
SimulationInitializer _initializer
SimulationBuilder _sim_builder
GetPot _command_line
libMesh::UniquePtr< libMesh::LibMeshInit > _libmesh_init
libMesh::UniquePtr< GetPot > _inputfile
libMesh::UniquePtr< Simulation > _simulation
Private Member Functions
Runner ()
Detailed Description
Class to encapsulate initializing and running GRINS Simulation.
This class encapsulates all of the construction, initialization, etc. libMesh and GRINS objects to facilitate easy construction of a GRINS-based program. The user only needs to construct this object, init(), and then run(). Accessors are provided to perform auxillary functions as needed beyond a single Simulation run.
Definition at line 47 of file runner.h.
Constructor & Destructor Documentation
GRINS::Runner::Runner (int argc, char * argv[])
Setup input objects.
The constructor will only setup input parsing objects and LibMeshInit. The user must call init() to initialize the Simulation objects. This allows the user to use the underlying command line and input file objects to do steps that may be needed before Simulation initialization.
Definition at line 37 of file runner.C.
References _command_line, _inputfile, check_and_get_inputfile(), and echo_version_info().
     : _initializer(),
       _sim_builder(),
       _command_line(argc,argv),
       _libmesh_init( new libMesh::LibMeshInit(argc,argv) )
   {
     this->echo_version_info( libMesh::out, argc, argv );
     // Grab inputfile name and setup GetPot input file
     std::string inputfile_name = this->check_and_get_inputfile(argc,argv,_command_line);
     _inputfile.reset( new GetPot(inputfile_name) );
     // Allow command line options to override the inputfile
     _inputfile->parse_command_line(argc,argv);
   }
GRINS::Runner::~Runner () inline
Definition at line 58 of file runner.h.
 {}
GRINS::Runner::Runner () private
Member Function Documentation
std::string GRINS::Runner::check_and_get_inputfile (int argc, char * argv[], GetPot & command_line) protected
Check (and error if not found) and then return GetPot input file name.
Definition at line 76 of file runner.C.
Referenced by Runner().
   {
     if( argc < 2 )
       {
         std::stringstream error_msg;
         error_msg << "ERROR: Found only 1 command line argument, but was expecting an inputfile name!"
                   << std::endl
                   << "       Please specify the name of the input file on the command line as the first" << std::endl
                   << "       command line argument or using the '--input <filename>' option." << std::endl;
         libmesh_error_msg(error_msg.str());
       }
     std::string inputfile_name;
     if( command_line.search("--input") )
       inputfile_name = command_line.next(std::string("DIE!"));
     else
       inputfile_name = argv[1];
     std::ifstream i(inputfile_name.c_str());
     if (!i)
       {
         std::string error_msg = "Error: Could not read from input file "+inputfile_name+"!\n";
         libmesh_error_msg(error_msg);
       }
     return inputfile_name;
   }
void GRINS::Runner::check_for_unused_vars (const GetPot & input, bool warning_only) protected
Check for any unused variables in GetPot input file.
Definition at line 114 of file runner.C.
Referenced by run().
   {
     /* Everything should be set up now, so check if there's any unused variables
        in the input file. If so, then tell the user what they were and error out. */
     std::vector<std::string> unused_vars = input.unidentified_variables();
     bool unused_vars_detected = false;
     // String we use to check if there is a variable in the Materials section
     std::string mat_string = "Materials/";
     // If we do have unused variables, make sure they are in the Materials
     // section since we're allowing those to be present and not used.
     if( !unused_vars.empty() )
       {
         int n_total = unused_vars.size();
         int n_mats = 0;
         for( int v = 0; v < n_total; v++ )
           if( (unused_vars[v]).find(mat_string) != std::string::npos )
             n_mats += 1;
         libmesh_assert_greater_equal( n_total, n_mats );
         if( n_mats < n_total )
           unused_vars_detected = true;
       }
     if( unused_vars_detected )
       {
         libMesh::err << "==========================================================" << std::endl;
         if( warning_only )
           libMesh::err << "Warning: ";
         else
           libMesh::err << "Error: ";
         libMesh::err << "Found unused variables!" << std::endl;
         for( std::vector<std::string>::const_iterator it = unused_vars.begin();
              it != unused_vars.end(); ++it )
           {
             // Don't print out any unused Material variables, since we allow these
             if( (*it).find(mat_string) != std::string::npos )
               continue;
             libMesh::err << *it << std::endl;
           }
         libMesh::err << "==========================================================" << std::endl;
         if( !warning_only )
           libmesh_error();
       }
   }
void GRINS::Runner::echo_version_info (std::ostream & out, int argc, char * argv[]) protected
Echo GRINS, libMesh version info as well as command line.
Definition at line 62 of file runner.C.
Referenced by Runner().
   {
     out << "==========================================================" << std::endl;
     out << "GRINS Version: " << GRINS_BUILD_VERSION << std::endl
         << "libMesh Version: " << LIBMESH_BUILD_VERSION << std::endl
         << "Running with command:\n";
     for (int i=0; i != argc; ++i)
       out << argv[i] << ' ';
     out << std::endl
         << "==========================================================" << std::endl;
   }
const GetPot& GRINS::Runner::get_command_line () const inline
Definition at line 63 of file runner.h.
References _command_line.
Referenced by main().
     { return _command_line; }
const GetPot& GRINS::Runner::get_input_file () const inline
Definition at line 60 of file runner.h.
References _inputfile.
Referenced by main().
     { return *_inputfile; }
const libMesh::LibMeshInit& GRINS::Runner::get_libmesh_init () const inline
Definition at line 74 of file runner.h.
References _libmesh_init.
Referenced by main().
     { return *_libmesh_init; }
Simulation& GRINS::Runner::get_simulation () inline
Definition at line 66 of file runner.h.
References _simulation.
Referenced by main(), and run().
     { libmesh_assert(_simulation);
       return *_simulation; }
const Simulation& GRINS::Runner::get_simulation () const inline
Definition at line 70 of file runner.h.
References _simulation.
     { libmesh_assert(_simulation);
       return *_simulation; }
void GRINS::Runner::init ()
Initialize the Simulation objects.
Definition at line 53 of file runner.C.
References _command_line, _inputfile, _libmesh_init, _sim_builder, and _simulation.
Referenced by main(), and run().
   {
     // Initialize Simulation
     _simulation.reset( new Simulation( *_inputfile,
                                        _command_line,
                                        _sim_builder,
                                        _libmesh_init->comm() ) );
   }
void GRINS::Runner::run ()
Runs the simulation that was setup at construction time.
Definition at line 104 of file runner.C.
References _command_line, _inputfile, _simulation, and check_for_unused_vars().
Referenced by main(), and run().
   {
     // First check for any unused variables
     bool warning_only = _command_line.search("--warn-only-unused-var");
     this->check_for_unused_vars(*_inputfile, warning_only );
     _simulation->run();
   }
Member Data Documentation
GetPot GRINS::Runner::_command_line protected
Definition at line 98 of file runner.h.
Referenced by get_command_line(), init(), run(), and Runner().
SimulationInitializer GRINS::Runner::_initializer protected
Definition at line 94 of file runner.h.
libMesh::UniquePtr<GetPot> GRINS::Runner::_inputfile protected
Definition at line 102 of file runner.h.
Referenced by get_input_file(), init(), run(), and Runner().
libMesh::UniquePtr<libMesh::LibMeshInit> GRINS::Runner::_libmesh_init protected
Definition at line 100 of file runner.h.
Referenced by get_libmesh_init(), and init().
SimulationBuilder GRINS::Runner::_sim_builder protected
Definition at line 96 of file runner.h.
Referenced by init().
libMesh::UniquePtr<Simulation> GRINS::Runner::_simulation protected
Definition at line 104 of file runner.h.
Referenced by get_simulation(), init(), and run().
The documentation for this class was generated from the following files:
src/solver/include/grins/runner.h
src/solver/src/runner.C