GRINS-0.6.0: GRINS::MooneyRivlin Class Reference
GRINS::MooneyRivlin Class Reference
#include <mooney_rivlin.h>
Public Member Functions
MooneyRivlin (const GetPot &input)
virtual ~MooneyRivlin ()
libMesh::Real dI1 (libMesh::Real I1, libMesh::Real I2, libMesh::Real I3) const
libMesh::Real dI2 (libMesh::Real I1, libMesh::Real I2, libMesh::Real I3) const
libMesh::Real dI3 (libMesh::Real I1, libMesh::Real I2, libMesh::Real I3) const
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiPointer< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
Private Member Functions
MooneyRivlin ()
libMesh::Real dI1_imp (libMesh::Real I1, libMesh::Real I2, libMesh::Real I3) const
libMesh::Real dI2_imp (libMesh::Real I1, libMesh::Real I2, libMesh::Real I3) const
libMesh::Real dI3_imp (libMesh::Real I1, libMesh::Real I2, libMesh::Real I3) const
Private Attributes
libMesh::Real _C1
libMesh::Real _C2
Friends
class HyperelasticStrainEnergy< MooneyRivlin >
Detailed Description
Definition at line 37 of file mooney_rivlin.h.
Constructor & Destructor Documentation
GRINS::MooneyRivlin::MooneyRivlin (const GetPot & input)
Definition at line 33 of file mooney_rivlin.C.
References _C1, _C2, and GRINS::ParameterUser::set_parameter().
     : HyperelasticStrainEnergy<MooneyRivlin>(),
       ParameterUser("MooneyRivlin"),
       _C1(-1),
       _C2(-1)
   {
     //Force the user to specify C1 and C2
     if( !input.have_variable("Physics/MooneyRivlin/C1") ||
         !input.have_variable("Physics/MooneyRivlin/C2")    )
       {
         std::cerr << "Error: Must specify both C1 and C2 for Mooney-Rivlin material." << std::endl
                   << "       They can be specified in Physics/MooneyRivlin/C1 and Physics/MooneyRivlin/C2" << std::endl;
         libmesh_error();
       }
     this->set_parameter
       (_C1, input, "Physics/MooneyRivlin/C1", _C1);
     this->set_parameter
       (_C2, input, "Physics/MooneyRivlin/C2", _C2);
     return;
   }
GRINS::MooneyRivlin::~MooneyRivlin () virtual
Definition at line 56 of file mooney_rivlin.C.
   {
     return;
   }
GRINS::MooneyRivlin::MooneyRivlin () private
Member Function Documentation
libMesh::Real GRINS::HyperelasticStrainEnergy< MooneyRivlin >::dI1 (libMesh::Real I1, libMesh::Real I2, libMesh::Real I3) const inherited
libMesh::Real GRINS::MooneyRivlin::dI1_imp (libMesh::Real I1, libMesh::Real I2, libMesh::Real I3) const inline private
Definition at line 62 of file mooney_rivlin.h.
References _C1.
   {
     return _C1;
   }
libMesh::Real GRINS::HyperelasticStrainEnergy< MooneyRivlin >::dI2 (libMesh::Real I1, libMesh::Real I2, libMesh::Real I3) const inherited
libMesh::Real GRINS::MooneyRivlin::dI2_imp (libMesh::Real I1, libMesh::Real I2, libMesh::Real I3) const inline private
Definition at line 68 of file mooney_rivlin.h.
References _C2.
   {
     return _C2;
   }
libMesh::Real GRINS::HyperelasticStrainEnergy< MooneyRivlin >::dI3 (libMesh::Real I1, libMesh::Real I2, libMesh::Real I3) const inherited
libMesh::Real GRINS::MooneyRivlin::dI3_imp (libMesh::Real I1, libMesh::Real I2, libMesh::Real I3) const inline private
Definition at line 74 of file mooney_rivlin.h.
   {
     return 0.0;
   }
void GRINS::ParameterUser::register_parameter (const std::string & param_name, libMesh::ParameterMultiPointer< libMesh::Number > & param_pointer) const virtual inherited
Each subclass will register its copy of an independent.
Reimplemented in GRINS::AxisymmetricHeatTransfer< Conductivity >, GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >, GRINS::IncompressibleNavierStokesBase< Viscosity >, GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >, GRINS::HeatConduction< Conductivity >, GRINS::HeatTransferBase< Conductivity >, and GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >.
Definition at line 50 of file parameter_user.C.
Referenced by GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::register_parameter(), GRINS::HeatTransferBase< Conductivity >::register_parameter(), GRINS::HeatConduction< Conductivity >::register_parameter(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::register_parameter(), GRINS::IncompressibleNavierStokesBase< Viscosity >::register_parameter(), GRINS::LowMachNavierStokesBase< Viscosity, SpecificHeat, ThermalConductivity >::register_parameter(), and GRINS::AxisymmetricHeatTransfer< Conductivity >::register_parameter().
   {
     std::map<std::string, libMesh::Number*>::const_iterator it =
       _my_parameters.find(param_name);
     if (it != _my_parameters.end())
       {
         std::cout << _my_name << " uses parameter " << param_name
                   << std::endl;
         param_pointer.push_back(it->second);
       }
   }
void GRINS::ParameterUser::set_parameter (libMesh::Number & param_variable, const GetPot & input, const std::string & param_name, libMesh::Number param_default) virtual inherited
Each subclass can simultaneously read a parameter value from.
Definition at line 35 of file parameter_user.C.
References GRINS::ParameterUser::_my_name, and GRINS::ParameterUser::_my_parameters.
Referenced by GRINS::AveragedFanAdjointStabilization< Viscosity >::AveragedFanAdjointStabilization(), GRINS::AveragedTurbineAdjointStabilization< Viscosity >::AveragedTurbineAdjointStabilization(), GRINS::BoussinesqBuoyancyAdjointStabilization< Viscosity >::BoussinesqBuoyancyAdjointStabilization(), GRINS::BoussinesqBuoyancyBase::BoussinesqBuoyancyBase(), GRINS::BoussinesqBuoyancySPGSMStabilization< Viscosity >::BoussinesqBuoyancySPGSMStabilization(), GRINS::ConstantConductivity::ConstantConductivity(), GRINS::ConstantPrandtlConductivity::ConstantPrandtlConductivity(), GRINS::ConstantSourceFunction::ConstantSourceFunction(), GRINS::ConstantSourceTerm::ConstantSourceTerm(), GRINS::ConstantSpecificHeat::ConstantSpecificHeat(), GRINS::ConstantViscosity::ConstantViscosity(), GRINS::ElasticCable< StressStrainLaw >::ElasticCable(), GRINS::ElasticCableConstantGravity::ElasticCableConstantGravity(), GRINS::ElasticMembrane< StressStrainLaw >::ElasticMembrane(), GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure(), GRINS::HeatConduction< Conductivity >::HeatConduction(), GRINS::HeatTransferBase< Conductivity >::HeatTransferBase(), GRINS::IncompressibleNavierStokesBase< Viscosity >::IncompressibleNavierStokesBase(), GRINS::AverageNusseltNumber::init(), MooneyRivlin(), GRINS::ReactingLowMachNavierStokesBase< Mixture, Evaluator >::ReactingLowMachNavierStokesBase(), GRINS::HookesLaw1D::read_input_options(), GRINS::HookesLaw::read_input_options(), GRINS::AxisymmetricBoussinesqBuoyancy::read_input_options(), and GRINS::VelocityDragAdjointStabilization< Viscosity >::VelocityDragAdjointStabilization().
   {
     param_variable = input(param_name, param_default);
     libmesh_assert_msg(!_my_parameters.count(param_name),
       "ERROR: " << _my_name << " double-registered parameter " <<
       param_name);
     _my_parameters[param_name] = &param_variable;
   }
Friends And Related Function Documentation
friend class HyperelasticStrainEnergy< MooneyRivlin > friend
Definition at line 46 of file mooney_rivlin.h.
Member Data Documentation
libMesh::Real GRINS::MooneyRivlin::_C1 private
Definition at line 56 of file mooney_rivlin.h.
Referenced by dI1_imp(), and MooneyRivlin().
libMesh::Real GRINS::MooneyRivlin::_C2 private
Definition at line 57 of file mooney_rivlin.h.
Referenced by dI2_imp(), and MooneyRivlin().
The documentation for this class was generated from the following files:
src/properties/include/grins/mooney_rivlin.h
src/properties/src/mooney_rivlin.C