GRINS-0.8.0: GRINS::MultcomponentVectorVariable Class Reference
GRINS::MultcomponentVectorVariable Class Reference
Variables that are effectively vectors.
#include <multi_component_vector_variable.h>
Public Member Functions
MultcomponentVectorVariable (const std::vector< std::string > &var_names, const std::vector< VariableIndex > &var_indices, const std::set< libMesh::subdomain_id_type > &subdomain_ids)
~MultcomponentVectorVariable ()
unsigned int dim () const
Number of components.
VariableIndex u () const
VariableIndex v () const
VariableIndex w () const
Public Member Functions inherited from GRINS::FEVariablesBase
FEVariablesBase (const std::vector< std::string > &var_names, const std::vector< VariableIndex > &var_indices, const std::set< libMesh::subdomain_id_type > &subdomain_ids)
virtual ~FEVariablesBase ()
void set_is_constraint_var (bool is_constraint_var)
Set whether or not this is a "constraint" variable.
bool is_constraint_var () const
void set_neumann_bc_is_positive (bool is_positive)
Reset whetever Neumann bc is postive or not.
libMesh::Real neumann_bc_sign () const
const std::vector< std::string > & active_var_names () const
Return the var names that are active from this class.
const std::vector< VariableIndex > & var_indices () const
const std::set< libMesh::subdomain_id_type > & subdomain_ids () const
Protected Attributes
unsigned int _u_idx
unsigned int _v_idx
unsigned int _w_idx
Protected Attributes inherited from GRINS::FEVariablesBase
std::vector< VariableIndex > _vars
std::vector< std::string > _var_names
bool _is_constraint_var
Tracks whether this is a constraint variable.
libMesh::Real _neumann_bc_sign
Track the sign of the Neumann BC term. Defaults to 1.0.
std::set< libMesh::subdomain_id_type > _subdomain_ids
Private Member Functions
MultcomponentVectorVariable ()
Detailed Description
Variables that are effectively vectors.
The variables are effectively vector-valued, but we treat each component as a separate variable. This is in contrast to vector-valued FE types, e.g. LAGRANGE_VEC, or NEDELEC_ONE.
Definition at line 37 of file multi_component_vector_variable.h.
Constructor & Destructor Documentation
GRINS::MultcomponentVectorVariable::MultcomponentVectorVariable (const std::vector< std::string > & var_names, const std::vector< VariableIndex > & var_indices, const std::set< libMesh::subdomain_id_type > & subdomain_ids) inline
Definition at line 41 of file multi_component_vector_variable.h.
       : FEVariablesBase(var_names,var_indices,subdomain_ids),
         _u_idx(0),
         _v_idx(1),
         _w_idx(2)
     {}
GRINS::MultcomponentVectorVariable::~MultcomponentVectorVariable () inline
Definition at line 50 of file multi_component_vector_variable.h.
 {}
GRINS::MultcomponentVectorVariable::MultcomponentVectorVariable () private
Member Function Documentation
unsigned int GRINS::MultcomponentVectorVariable::dim () const inline
Number of components.
Definition at line 53 of file multi_component_vector_variable.h.
References GRINS::FEVariablesBase::_vars.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_continuity(), GRINS::HeatTransferStabilizationHelper::compute_res_energy_steady(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_transient(), GRINS::SpalartAllmarasStabilizationHelper::compute_res_spalart_steady(), GRINS::ElasticMembraneBase< StressStrainLaw >::ElasticMembraneBase(), GRINS::ElasticMembraneConstantPressure::ElasticMembraneConstantPressure(), GRINS::IncompressibleNavierStokes< Viscosity >::IncompressibleNavierStokes(), GRINS::LowMachNavierStokes< Viscosity, SpecificHeat, ThermalConductivity >::LowMachNavierStokes(), and GRINS::SolidMechanicsAbstract::set_time_evolving_vars().
     { return _vars.size(); }
VariableIndex GRINS::MultcomponentVectorVariable::u () const inline
Definition at line 56 of file multi_component_vector_variable.h.
References _u_idx, and GRINS::FEVariablesBase::_vars.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_continuity(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_transient(), GRINS::SpalartAllmarasStabilizationHelper::compute_res_spalart_steady(), GRINS::Vorticity::element_qoi(), GRINS::Vorticity::element_qoi_derivative(), GRINS::ElasticMembraneAbstract::get_fe(), GRINS::ElasticCableAbstract::get_fe(), GRINS::ReactingLowMachNavierStokesAbstract::init_context(), GRINS::AxisymmetricBoussinesqBuoyancy::init_context(), GRINS::Vorticity::init_context(), GRINS::SolidMechanicsAbstract::set_time_evolving_vars(), GRINS::ReactingLowMachNavierStokesAbstract::set_time_evolving_vars(), and GRINS::SpalartAllmarasHelper::vorticity().
     { return this->_vars[_u_idx]; }
VariableIndex GRINS::MultcomponentVectorVariable::v () const inline
Definition at line 59 of file multi_component_vector_variable.h.
References _v_idx, and GRINS::FEVariablesBase::_vars.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_continuity(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady(), GRINS::SpalartAllmarasStabilizationHelper::compute_res_spalart_steady(), GRINS::Vorticity::element_qoi(), GRINS::Vorticity::element_qoi_derivative(), GRINS::Vorticity::init_context(), GRINS::SolidMechanicsAbstract::set_time_evolving_vars(), GRINS::ReactingLowMachNavierStokesAbstract::set_time_evolving_vars(), and GRINS::SpalartAllmarasHelper::vorticity().
     { return this->_vars[_v_idx]; }
VariableIndex GRINS::MultcomponentVectorVariable::w () const inline
Definition at line 62 of file multi_component_vector_variable.h.
References GRINS::FEVariablesBase::_vars, and _w_idx.
Referenced by GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_continuity(), GRINS::HeatTransferStabilizationHelper::compute_res_energy_steady(), GRINS::IncompressibleNavierStokesStabilizationHelper::compute_res_momentum_steady(), GRINS::SpalartAllmarasStabilizationHelper::compute_res_spalart_steady(), GRINS::SolidMechanicsAbstract::set_time_evolving_vars(), GRINS::ReactingLowMachNavierStokesAbstract::set_time_evolving_vars(), and GRINS::SpalartAllmarasHelper::vorticity().
     { return this->_vars[_w_idx]; }
Member Data Documentation
unsigned int GRINS::MultcomponentVectorVariable::_u_idx protected
Definition at line 67 of file multi_component_vector_variable.h.
Referenced by u().
unsigned int GRINS::MultcomponentVectorVariable::_v_idx protected
Definition at line 67 of file multi_component_vector_variable.h.
Referenced by v().
unsigned int GRINS::MultcomponentVectorVariable::_w_idx protected
Definition at line 67 of file multi_component_vector_variable.h.
Referenced by w().
The documentation for this class was generated from the following file:
src/variables/include/grins/multi_component_vector_variable.h