GRINS-0.8.0: GRINS::VelocityPenaltyBase< Viscosity > Class Template Reference
GRINS::VelocityPenaltyBase< Viscosity > Class Template Reference
#include <velocity_penalty_base.h>
Public Member Functions
VelocityPenaltyBase (const std::string &physics_name, const GetPot &input)
~VelocityPenaltyBase ()
void set_time_evolving_vars (libMesh::FEMSystem *system)
Sets velocity variables to be time-evolving.
bool compute_force (const libMesh::Point &point, const AssemblyContext &context, const libMesh::NumberVectorValue &U, libMesh::NumberVectorValue &F, libMesh::NumberTensorValue *dFdU=NULL)
Public Member Functions inherited from GRINS::IncompressibleNavierStokesBase< Viscosity >
IncompressibleNavierStokesBase (const std::string &my_physics_name, const std::string &core_physics_name, const GetPot &input)
~IncompressibleNavierStokesBase ()
virtual void init_context (AssemblyContext &context)
Initialize context for added physics variables.
virtual void register_parameter (const std::string &param_name, libMesh::ParameterMultiAccessor< libMesh::Number > &param_pointer) const
Each subclass will register its copy of an independent.
libMesh::Real get_viscosity_value (AssemblyContext &context, unsigned int qp) const
Public Member Functions inherited from GRINS::Physics
Physics (const GRINS::PhysicsName &physics_name, const GetPot &input)
virtual ~Physics ()
virtual void init_variables (libMesh::FEMSystem *)
Initialize variables for this physics.
virtual bool enabled_on_elem (const libMesh::Elem *elem)
Find if current physics is active on supplied element.
void set_is_steady (bool is_steady)
Sets whether this physics is to be solved with a steady solver or not.
bool is_steady () const
Returns whether or not this physics is being solved with a steady solver.
virtual void auxiliary_init (MultiphysicsSystem &system)
Any auxillary initialization a Physics class may need.
virtual void register_postprocessing_vars (const GetPot &input, PostProcessedQuantities< libMesh::Real > &postprocessing)
Register name of postprocessed quantity with PostProcessedQuantities.
virtual void preassembly (MultiphysicsSystem &)
Perform any necessary setup before element assembly begins.
virtual void reinit (MultiphysicsSystem &)
Any reinitialization that needs to be done.
virtual void element_time_derivative (bool, AssemblyContext &)
Time dependent part(s) of physics for element interiors.
virtual void side_time_derivative (bool, AssemblyContext &)
Time dependent part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_time_derivative (bool, AssemblyContext &)
Time dependent part(s) of physics for scalar variables.
virtual void element_constraint (bool, AssemblyContext &)
Constraint part(s) of physics for element interiors.
virtual void side_constraint (bool, AssemblyContext &)
Constraint part(s) of physics for boundaries of elements on the domain boundary.
virtual void nonlocal_constraint (bool, AssemblyContext &)
Constraint part(s) of physics for scalar variables.
virtual void damping_residual (bool, AssemblyContext &)
Damping matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void mass_residual (bool, AssemblyContext &)
Mass matrix part(s) for element interiors. All boundary terms lie within the time_derivative part.
virtual void nonlocal_mass_residual (bool, AssemblyContext &)
Mass matrix part(s) for scalar variables.
void init_ics (libMesh::FEMSystem *system, libMesh::CompositeFunction< libMesh::Number > &all_ics)
virtual void compute_element_time_derivative_cache (AssemblyContext &)
virtual void compute_side_time_derivative_cache (AssemblyContext &)
virtual void compute_nonlocal_time_derivative_cache (AssemblyContext &)
virtual void compute_element_constraint_cache (AssemblyContext &)
virtual void compute_side_constraint_cache (AssemblyContext &)
virtual void compute_nonlocal_constraint_cache (AssemblyContext &)
virtual void compute_damping_residual_cache (AssemblyContext &)
virtual void compute_mass_residual_cache (AssemblyContext &)
virtual void compute_nonlocal_mass_residual_cache (AssemblyContext &)
virtual void compute_postprocessed_quantity (unsigned int quantity_index, const AssemblyContext &context, const libMesh::Point &point, libMesh::Real &value)
ICHandlingBase * get_ic_handler ()
Public Member Functions inherited from GRINS::ParameterUser
ParameterUser (const std::string &user_name)
virtual ~ParameterUser ()
virtual void set_parameter (libMesh::Number &param_variable, const GetPot &input, const std::string &param_name, libMesh::Number param_default)
Each subclass can simultaneously read a parameter value from.
virtual void set_parameter (libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void set_parameter (libMesh::ParsedFEMFunction< libMesh::Number > &func, const GetPot &input, const std::string &func_param_name, const std::string &param_default)
Each subclass can simultaneously read a parsed function from.
virtual void move_parameter (const libMesh::Number &old_parameter, libMesh::Number &new_parameter)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &old_func, libMesh::ParsedFunction< libMesh::Number, libMesh::Gradient > &new_func)
When cloning an object, we need to update parameter pointers.
virtual void move_parameter (const libMesh::ParsedFEMFunction< libMesh::Number > &old_func, libMesh::ParsedFEMFunction< libMesh::Number > &new_func)
When cloning an object, we need to update parameter pointers.
Protected Attributes
std::string base_physics_name
bool _quadratic_scaling
libMesh::UniquePtr< libMesh::FEMFunctionBase< libMesh::Number > > normal_vector_function
libMesh::UniquePtr< libMesh::FEMFunctionBase< libMesh::Number > > base_velocity_function
Protected Attributes inherited from GRINS::IncompressibleNavierStokesBase< Viscosity >
VelocityVariable & _flow_vars
PressureFEVariable & _press_var
libMesh::Number _rho
Material parameters, read from input.
Viscosity _mu
Viscosity object.
Protected Attributes inherited from GRINS::Physics
const PhysicsName _physics_name
Name of the physics object. Used for reading physics specific inputs.
GRINS::ICHandlingBase * _ic_handler
std::set< libMesh::subdomain_id_type > _enabled_subdomains
Subdomains on which the current Physics class is enabled.
Private Member Functions
VelocityPenaltyBase ()
void read_input_options (const GetPot &input)
Read options from GetPot input file.
Private Attributes
const GetPot & _input
Additional Inherited Members
Static Public Member Functions inherited from GRINS::Physics
static void set_is_axisymmetric (bool is_axisymmetric)
Set whether we should treat the problem as axisymmetric.
static bool is_axisymmetric ()
Static Public Attributes inherited from GRINS::ParameterUser
static std::string zero_vector_function = std::string("{0}")
A parseable function string with LIBMESH_DIM components, all 0.
Protected Member Functions inherited from GRINS::Physics
libMesh::UniquePtr< libMesh::FEGenericBase< libMesh::Real > > build_new_fe (const libMesh::Elem *elem, const libMesh::FEGenericBase< libMesh::Real > *fe, const libMesh::Point p)
void parse_enabled_subdomains (const GetPot &input, const std::string &physics_name)
void check_var_subdomain_consistency (const FEVariablesBase &var) const
Check that var is enabled on at least the subdomains this Physics is.
Static Protected Attributes inherited from GRINS::Physics
static bool _is_steady = false
Caches whether or not the solver that's being used is steady or not.
static bool _is_axisymmetric = false
Caches whether we are solving an axisymmetric problem or not.
Detailed Description
template<class Viscosity>
class GRINS::VelocityPenaltyBase< Viscosity >
Definition at line 45 of file velocity_penalty_base.h.
Constructor & Destructor Documentation
template<class Mu > GRINS::VelocityPenaltyBase< Mu >::VelocityPenaltyBase (const std::string & physics_name, const GetPot & input)
Definition at line 39 of file velocity_penalty_base.C.
References GRINS::Physics::_physics_name, GRINS::VelocityPenaltyBase< Viscosity >::base_physics_name, GRINS::VelocityPenaltyBase< Viscosity >::read_input_options(), GRINS::PhysicsNaming::velocity_penalty2(), GRINS::PhysicsNaming::velocity_penalty2_adjoint_stab(), GRINS::PhysicsNaming::velocity_penalty3(), and GRINS::PhysicsNaming::velocity_penalty3_adjoint_stab().
     : IncompressibleNavierStokesBase<Mu>(physics_name,
                                          PhysicsNaming::incompressible_navier_stokes(), /* "core" Physics name */
                                          input),
     base_physics_name("VelocityPenalty"),
     _quadratic_scaling(false),
     _input(input)
   {
     if (this->_physics_name == PhysicsNaming::velocity_penalty2() ||
         this->_physics_name == PhysicsNaming::velocity_penalty2_adjoint_stab())
       base_physics_name.push_back('2');
     if (this->_physics_name == PhysicsNaming::velocity_penalty3() ||
         this->_physics_name == PhysicsNaming::velocity_penalty3_adjoint_stab())
       base_physics_name.push_back('3');
     this->read_input_options(input);
   }
template<class Viscosity > GRINS::VelocityPenaltyBase< Viscosity >::~VelocityPenaltyBase () inline
Definition at line 51 of file velocity_penalty_base.h.
 {};
template<class Viscosity > GRINS::VelocityPenaltyBase< Viscosity >::VelocityPenaltyBase () private
Member Function Documentation
template<class Mu > bool GRINS::VelocityPenaltyBase< Mu >::compute_force (const libMesh::Point & point, const AssemblyContext & context, const libMesh::NumberVectorValue & U, libMesh::NumberVectorValue & F, libMesh::NumberTensorValue * dFdU = NULL)
Definition at line 92 of file velocity_penalty_base.C.
   {
     // Velocity discrepancy (current velocity minus base velocity)
     // normal to constraint plane, scaled by constraint penalty
     // value
     libMesh::DenseVector<libMesh::Number> output_vec(3);
     (*this->normal_vector_function)(context, point, context.time, output_vec);
     libMesh::NumberVectorValue U_N(output_vec(0),
                                    output_vec(1),
                                    output_vec(2));
     (*this->base_velocity_function)(context, point, context.time, output_vec);
     const libMesh::NumberVectorValue U_B(output_vec(0),
                                          output_vec(1),
                                          output_vec(2));
     const libMesh::NumberVectorValue U_Rel = U-U_B;
     // Old code
     // const libMesh::NumberVectorValue F1 = (U_Rel*U_N)*U_N; //
     // With correct sign and more natural normalization
     const libMesh::Number U_N_mag = std::sqrt(U_N*U_N);
     if (!U_N_mag)
       return false;
     const libMesh::NumberVectorValue U_N_unit = U_N/U_N_mag;
     F = -(U_Rel*U_N)*U_N_unit;
     if (dFdU)
       for (unsigned int i=0; i != 3; ++i)
         for (unsigned int j=0; j != 3; ++j)
           (*dFdU)(i,j) = -(U_N(j))*U_N_unit(i);
     // With quadratic scaling
     if (_quadratic_scaling)
       {
         const libMesh::Number U_Rel_mag = std::sqrt(U_Rel * U_Rel);
         // Modify dFdU first so as to reuse the old value of F
         if (dFdU)
           {
             // dU_Rel/dU = I
             // d(U_Rel*U_Rel)/dU = 2*U_Rel
             // d|U_Rel|/dU = U_Rel/|U_Rel|
             const libMesh::NumberVectorValue U_Rel_unit = U_Rel/U_Rel_mag;
             (*dFdU) *= U_Rel_mag;
             if (U_Rel_mag)
               for (unsigned int i=0; i != 3; ++i)
                 for (unsigned int j=0; j != 3; ++j)
                   (*dFdU)(i,j) += F(i)*U_Rel_unit(j);
           }
         F *= U_Rel_mag;
       }
     // With correction term to avoid doing work on flow
     bool do_correction = false;
     if (do_correction)
       {
         if (dFdU)
           libmesh_not_implemented();
         const libMesh::Number U_Rel_mag_sq = U_Rel * U_Rel;
         if (U_Rel_mag_sq)
           {
             F -= (U_Rel*F)*U_Rel/U_Rel_mag_sq;
           }
       }
     return true;
   }
template<class Mu > void GRINS::VelocityPenaltyBase< Mu >::read_input_options (const GetPot & input) private
Read options from GetPot input file.
Definition at line 59 of file velocity_penalty_base.C.
Referenced by GRINS::VelocityPenaltyBase< Viscosity >::VelocityPenaltyBase().
   {
     _quadratic_scaling =
       input("Physics/"+base_physics_name+"/quadratic_scaling", false);
   }
template<class Mu > void GRINS::VelocityPenaltyBase< Mu >::set_time_evolving_vars (libMesh::FEMSystem * system) virtual
Sets velocity variables to be time-evolving.
Reimplemented from GRINS::IncompressibleNavierStokesBase< Viscosity >.
Definition at line 66 of file velocity_penalty_base.C.
   {
     libMesh::ParsedFEMFunction<libMesh::Number> *nvf
       (new libMesh::ParsedFEMFunction<libMesh::Number> (*system, ""));
     this->normal_vector_function.reset(nvf);
     this->set_parameter(*nvf, _input,
                         "Physics/"+base_physics_name+"/penalty_function",
                         this->zero_vector_function);
     libMesh::ParsedFEMFunction<libMesh::Number> *bvf
       (new libMesh::ParsedFEMFunction<libMesh::Number> (*system, ""));
     this->base_velocity_function.reset(bvf);
     this->set_parameter(*bvf, _input,
                         "Physics/"+base_physics_name+"/base_velocity",
                         this->zero_vector_function);
     if ((nvf->expression() == this->zero_vector_function) &&
         (bvf->expression() == this->zero_vector_function))
       std::cout << "Warning! Zero VelocityPenalty specified!" << std::endl;
   }
Member Data Documentation
template<class Viscosity > const GetPot& GRINS::VelocityPenaltyBase< Viscosity >::_input private
Definition at line 76 of file velocity_penalty_base.h.
template<class Viscosity > bool GRINS::VelocityPenaltyBase< Viscosity >::_quadratic_scaling protected
Definition at line 66 of file velocity_penalty_base.h.
template<class Viscosity > std::string GRINS::VelocityPenaltyBase< Viscosity >::base_physics_name protected
Definition at line 64 of file velocity_penalty_base.h.
Referenced by GRINS::VelocityPenaltyBase< Viscosity >::VelocityPenaltyBase().
template<class Viscosity > libMesh::UniquePtr<libMesh::FEMFunctionBase<libMesh::Number> > GRINS::VelocityPenaltyBase< Viscosity >::base_velocity_function protected
Definition at line 72 of file velocity_penalty_base.h.
template<class Viscosity > libMesh::UniquePtr<libMesh::FEMFunctionBase<libMesh::Number> > GRINS::VelocityPenaltyBase< Viscosity >::normal_vector_function protected
Definition at line 69 of file velocity_penalty_base.h.
The documentation for this class was generated from the following files:
src/physics/include/grins/velocity_penalty_base.h
src/physics/src/velocity_penalty_base.C