GRINS-0.7.0: test/regression/generic_solution_regression.C File Reference
generic_solution_regression.C File Reference
#include "grins_config.h"
#include "grins/mesh_builder.h"
#include "grins/simulation.h"
#include "grins/simulation_builder.h"
#include "grins/multiphysics_sys.h"
#include "libmesh/exact_solution.h"
Functions
void test_error_norm (libMesh::ExactSolution &exact_sol, const std::string &system_name, const std::string &var, const std::string &norm, const double tol, int &return_flag)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 43 of file generic_solution_regression.C.
References GRINS::Simulation::run(), and test_error_norm().
 {
   GetPot command_line(argc,argv);
   if( !command_line.have_variable("input") )
     {
       std::cerr << "ERROR: Must specify input file on command line with input=<file>." << std::endl;
       exit(1);
     }
   if( !command_line.have_variable("soln-data") )
     {
       std::cerr << "ERROR: Must specify solution data on command line with soln-data=<file>." << std::endl;
       exit(1);
     }
   if( !command_line.have_variable("vars") )
     {
       std::cerr << "ERROR: Must specify variables on command line with vars='var1 var2'" << std::endl;
       exit(1);
     }
   if( !command_line.have_variable("norms") )
     {
       std::cerr << "ERROR: Must specify error norms on command line with norms='L2 H1'" << std::endl;
       exit(1);
     }
   if( !command_line.have_variable("tol") )
     {
       std::cerr << "ERROR: Must specify test tolerance on command line with tol=<tol>" << std::endl;
       exit(1);
     }
   // libMesh input file should be first argument
   std::string libMesh_input_filename = command_line("input", "DIE!");
   {
     std::ifstream i(libMesh_input_filename.c_str());
     if (!i)
       {
         std::cerr << "Error: Could not read from libMesh input file "
                 << libMesh_input_filename << std::endl;
         exit(1);
       }
   }
   // Create our GetPot object.
   GetPot libMesh_inputfile( libMesh_input_filename );
   // Initialize libMesh library.
   libMesh::LibMeshInit libmesh_init(argc, argv);
   GRINS::SimulationBuilder sim_builder;
   GRINS::Simulation grins( libMesh_inputfile,
                            command_line,
                            sim_builder,
                            libmesh_init.comm() );
   // Do solve here
   grins.run();
   // Get equation systems to create ExactSolution object
   GRINS::SharedPtr<libMesh::EquationSystems> es = grins.get_equation_system();
    // Create Exact solution object and attach exact solution quantities
   libMesh::ExactSolution exact_sol(*es);
   libMesh::EquationSystems es_ref( es->get_mesh() );
   // Filename of file where comparison solution is stashed
   std::string solution_file = command_line("soln-data", "DIE!");
   es_ref.read( solution_file );
   exact_sol.attach_reference_solution( &es_ref );
   // Now grab the variables for which we want to compare
   unsigned int n_vars = command_line.vector_variable_size("vars");
   std::vector<std::string> vars(n_vars);
   for( unsigned int v = 0; v < n_vars; v++ )
     {
       vars[v] = command_line("vars", "DIE!", v);
     }
   // Now grab the norms to compute for each variable error
   unsigned int n_norms = command_line.vector_variable_size("norms");
   std::vector<std::string> norms(n_norms);
   for( unsigned int n = 0; n < n_norms; n++ )
     {
       norms[n] = command_line("norms", "DIE!", n);
       if( norms[n] != std::string("L2") &&
           norms[n] != std::string("H1") )
         {
           std::cerr << "ERROR: Invalid norm input " << norms[n] << std::endl
                     << "       Valid values are: L2" << std::endl
                     << "                         H1" << std::endl;
         }
     }
   const std::string& system_name = grins.get_multiphysics_system_name();
   // Now compute error for each variable
   for( unsigned int v = 0; v < n_vars; v++ )
     {
       exact_sol.compute_error(system_name, vars[v]);
     }
   int return_flag = 0;
   double tol = command_line("tol", 1.0e-10);
   // Now test error for each variable, for each norm
   for( unsigned int v = 0; v < n_vars; v++ )
     {
       for( unsigned int n = 0; n < n_norms; n++ )
         {
           test_error_norm( exact_sol, system_name, vars[v], norms[n], tol, return_flag );
         }
     }
   // Now grab any "gold" QoI values
   unsigned int n_qoi_vals = command_line.vector_variable_size("qois");
   for( unsigned int n = 0; n < n_qoi_vals; n++ )
     {
       std::cout << "==========================================================" << std::endl
                 << "Checking qoi " << n << " with tol " << tol << "...";
       libMesh::Number gold_qoi = command_line("qois", libMesh::Number(0), n);
       libMesh::Number computed_qoi =
         grins.get_multiphysics_system()->qoi[n];
       double error = computed_qoi - gold_qoi;
       if (std::abs(error) > tol)
         {
           std::cerr << "Tolerance exceeded for generic regression test!" << std::endl
                     << "tolerance     = " << tol << std::endl
                     << "error         = " << error << std::endl
                     << "qoi index     = " << n << std::endl;
           return_flag = 1;
         }
       else
         std::cout << "PASSED!" << std::endl
                   << "==========================================================" << std::endl;
     }
   return return_flag;
 }
void test_error_norm (libMesh::ExactSolution & exact_sol, const std::string & system_name, const std::string & var, const std::string & norm, const double tol, int & return_flag)
Definition at line 197 of file generic_solution_regression.C.
Referenced by main().
 {
   // We don't set return_flag unless we are setting it 1
   // since this function gets called multiple times and we don't
   // want to overwrite a previous "fail" (return_flag = 1) with
   // a "pass" (return_flag = 0)
   double error = 0.0;
   std::cout << "==========================================================" << std::endl
             << "Checking variable " << var << " using error norm " << norm << " with tol " << tol << "...";
   if( norm == std::string("L2") )
     {
       error = exact_sol.l2_error(system_name, var);
     }
   else if( norm == std::string("H1") )
     {
       error = exact_sol.h1_error(system_name, var);
     }
   else
     {
       std::cerr << "ERROR: Invalid norm " << norm << std::endl;
       exit(1);
     }
   if( error > tol )
     {
       return_flag = 1;
       std::cerr << "Tolerance exceeded for generic regression test!" << std::endl
                 << "tolerance     = " << tol << std::endl
                 << "norm of error = " << error << std::endl
                 << "norm type     = " << norm << std::endl
                 << "var           = " << var << std::endl;
     }
   else
     {
       std::cout << "PASSED!" << std::endl
                 << "==========================================================" << std::endl;
     }
   return;
 }