GRINS-0.8.0: GRINS::StringUtilities Namespace Reference
GRINS::StringUtilities Namespace Reference
Functions
template<typename T >
T string_to_T (const std::string &input)
template<typename T >
std::string T_to_string (const T input)
std::pair< std::string, int > split_string_int_on_colon (const std::string &token)
Split on colon, and return name, int value pair.
std::pair< std::string, double > split_string_double_on_colon (const std::string &token)
Split on colon, and return name, double value pair.
void split_string (const std::string &input, const std::string &delimiter, std::vector< std::string > &results)
void split_string_real (const std::string &input, const std::string &delimiter, std::vector< libMesh::Real > &results)
Function Documentation
void GRINS::StringUtilities::split_string (const std::string & input, const std::string & delimiter, std::vector< std::string > & results)
Definition at line 31 of file string_utils.C.
Referenced by GRINS::MoleFractionsDirichletBCFactory::add_mole_frac_to_mass_frac(), GRINS::QoIFactory::build(), GRINS::MoleFractionsDirichletBCFactory::extract_species_name(), GRINS::MoleFractionsDirichletBCFactory::extract_var_section(), GRINS::ICHandlingBase::init_ic_types(), GRINS::DefaultBCBuilder::parse_and_build_bc_id_map(), parse_qoi_data(), GRINS::GasRecombinationCatalyticWallNeumannBCFactoryImpl::parse_reactant_and_product(), GRINS::GasSolidCatalyticWallNeumannBCFactoryImpl::parse_reactants_and_product(), split_string_real(), and GRINSTesting::StringUtilitiesTest::test_split_string().
     {
       // Skip delimiters at beginning.
       std::string::size_type first_pos = input.find_first_not_of(delimiter, 0);
       std::string::size_type pos     = input.find(delimiter, first_pos);
       while (std::string::npos != pos || std::string::npos != first_pos)
         {
           // Found a token, add it to the vector.
           results.push_back(input.substr(first_pos, pos - first_pos));
           // Skip delimiters.  Note the "not_of"
           first_pos = input.find_first_not_of(delimiter, pos);
           // Find next delimiter
           pos = input.find(delimiter, first_pos);
         }
     }
std::pair<std::string, double> GRINS::StringUtilities::split_string_double_on_colon (const std::string & token) inline
Split on colon, and return name, double value pair.
Taken from FIN-S for XML parsing.
Definition at line 85 of file string_utils.h.
     {
       std::pair<std::string, double> ret = std::make_pair(std::string(), 0.0);
       std::string::size_type colon_position = token.find(":");
       libmesh_assert (colon_position != std::string::npos);
       ret.first  = token.substr(0, colon_position);
       ret.second = std::atof(token.substr(colon_position + 1).c_str());
       return ret;
     }
std::pair<std::string, int> GRINS::StringUtilities::split_string_int_on_colon (const std::string & token) inline
Split on colon, and return name, int value pair.
Taken from FIN-S for XML parsing.
Definition at line 69 of file string_utils.h.
     {
       std::pair<std::string, int> ret = std::make_pair(std::string(), 0);
       std::string::size_type colon_position = token.find(":");
       libmesh_assert (colon_position != std::string::npos);
       ret.first  = token.substr(0, colon_position);
       ret.second = std::atoi(token.substr(colon_position + 1).c_str());
       return ret;
     }
void GRINS::StringUtilities::split_string_real (const std::string & input, const std::string & delimiter, std::vector< libMesh::Real > & results)
Definition at line 53 of file string_utils.C.
References split_string().
Referenced by GRINS::HITRAN::HITRAN().
     {
       std::vector<std::string> string_vec;
       split_string(input,delimiter,string_vec);
       results.resize(string_vec.size());
       for (unsigned int i=0; i<string_vec.size(); i++)
         results[i] = string_to_T<libMesh::Real>(string_vec[i]);
     }
template<typename T > T GRINS::StringUtilities::string_to_T (const std::string & input) inline
Definition at line 43 of file string_utils.h.
     {
       std::istringstream converter(input);
       T returnval;
       converter >> returnval;
       if (converter.fail())
         libmesh_error();
       return returnval;
     }
template<typename T > std::string GRINS::StringUtilities::T_to_string (const T input) inline
Definition at line 55 of file string_utils.h.
     {
       std::stringstream converter;
       converter << input;
       if (converter.fail())
         libmesh_error();
       return converter.str();
     }