GRINS-0.6.0: test/test_ns_poiseuille_flow.C File Reference
test_ns_poiseuille_flow.C File Reference
#include "grins_config.h"
#include <iostream>
#include "grins/mesh_builder.h"
#include "grins/simulation.h"
#include "grins/simulation_builder.h"
#include "grins/multiphysics_sys.h"
#include "grins/parabolic_profile.h"
#include "libmesh/exact_solution.h"
Classes
class ParabolicBCFactory
Functions
libMesh::Number exact_solution (const libMesh::Point &p, const libMesh::Parameters &, const std::string &, const std::string &)
libMesh::Gradient exact_derivative (const libMesh::Point &p, const libMesh::Parameters &, const std::string &, const std::string &)
int main (int argc, char *argv[])
Function Documentation
libMesh::Gradient exact_derivative (const libMesh::Point & p, const libMesh::Parameters & , const std::string & , const std::string & var)
Definition at line 200 of file test_ns_poiseuille_flow.C.
Referenced by main().
 {
   const double y = p(1);
   libMesh::Gradient g;
   // Hardcoded to velocity in input file.
   if( var == "u" )
     {
       g(0) = 0.0;
       g(1) = 4*(1-y) - 4*y;
 #if LIBMESH_DIM > 2
       g(2) = 0.0;
 #endif
     }
   if( var == "p" )
     {
       g(0) = (80.0-120.0)/5.0;
       g(1) = 0.0;
 #if LIBMESH_DIM > 2
       g(2) = 0.0;
 #endif
     }
   return g;
 }
libMesh::Number exact_solution (const libMesh::Point & p, const libMesh::Parameters & , const std::string & , const std::string & var)
Definition at line 182 of file test_ns_poiseuille_flow.C.
Referenced by main().
 {
   const double x = p(0);
   const double y = p(1);
   libMesh::Number f = 0;
   // Hardcoded to velocity in input file.
   if( var == "u" ) f = 4*y*(1-y);
   else if( var == "p" ) f = 120.0 + (80.0-120.0)/5.0*x;
   else libmesh_assert(false);
   return f;
 }
int main (int argc, char * argv[])
Definition at line 70 of file test_ns_poiseuille_flow.C.
References GRINS::SimulationBuilder::attach_bc_factory(), exact_derivative(), exact_solution(), and GRINS::Simulation::run().
 {
 #ifdef GRINS_USE_GRVY_TIMERS
   GRVY::GRVY_Timer_Class grvy_timer;
   grvy_timer.Init("GRINS Timer");
 #endif
   // Check command line count.
   if( argc < 2 )
     {
       // TODO: Need more consistent error handling.
       std::cerr << "Error: Must specify libMesh input file." << std::endl;
       exit(1); // TODO: something more sophisticated for parallel runs?
     }
   // libMesh input file should be first argument
   std::string libMesh_input_filename = argv[1];
   // Create our GetPot object.
   GetPot libMesh_inputfile( libMesh_input_filename );
 #ifdef GRINS_USE_GRVY_TIMERS
   grvy_timer.BeginTimer("Initialize Solver");
 #endif
   // Initialize libMesh library.
   libMesh::LibMeshInit libmesh_init(argc, argv);
   GRINS::SimulationBuilder sim_builder;
   std::tr1::shared_ptr<ParabolicBCFactory> bc_factory( new ParabolicBCFactory );
   sim_builder.attach_bc_factory(bc_factory);
   GRINS::Simulation grins( libMesh_inputfile,
                            sim_builder,
                            libmesh_init.comm() );
 #ifdef GRINS_USE_GRVY_TIMERS
   grvy_timer.EndTimer("Initialize Solver");
   // Attach GRVY timer to solver
   grins.attach_grvy_timer( &grvy_timer );
 #endif
   // Solve
   grins.run();
   // Get equation systems to create ExactSolution object
   std::tr1::shared_ptr<libMesh::EquationSystems> es = grins.get_equation_system();
   // Create Exact solution object and attach exact solution quantities
   libMesh::ExactSolution exact_sol(*es);
   exact_sol.attach_exact_value(&exact_solution);
   exact_sol.attach_exact_deriv(&exact_derivative);
   // Compute error and get it in various norms
   exact_sol.compute_error("GRINS", "u");
   double l2error = exact_sol.l2_error("GRINS", "u");
   double h1error = exact_sol.h1_error("GRINS", "u");
   int return_flag = 0;
   if( l2error > 1.0e-9 || h1error > 1.0e-9 )
     {
       return_flag = 1;
       std::cout << "Tolerance exceeded for velocity in Poiseuille test." << std::endl
                 << "l2 error = " << l2error << std::endl
                 << "h1 error = " << h1error << std::endl;
     }
   // Compute error and get it in various norms
   exact_sol.compute_error("GRINS", "p");
   l2error = exact_sol.l2_error("GRINS", "p");
   h1error = exact_sol.h1_error("GRINS", "p");
   if( l2error > 2.0e-9 || h1error > 2.0e-9 )
     {
       return_flag = 1;
       std::cout << "Tolerance exceeded for pressure in Poiseuille test." << std::endl
                 << "l2 error = " << l2error << std::endl
                 << "h1 error = " << h1error << std::endl;
     }
   return return_flag;
 }