GRINS-0.8.0: test/regression/test_turbulent_channel.C File Reference
test_turbulent_channel.C File Reference
#include "grins_config.h"
#include <iostream>
#include "grins/runner.h"
#include "grins/mesh_builder.h"
#include "grins/multiphysics_sys.h"
#include "grins/dirichlet_bc_factory_function_old_style_base.h"
#include "grins/var_typedefs.h"
#include "libmesh/dirichlet_boundaries.h"
#include "libmesh/dof_map.h"
#include "libmesh/fe_base.h"
#include "libmesh/fe_interface.h"
#include "libmesh/mesh_function.h"
#include "libmesh/serial_mesh.h"
#include "libmesh/edge_edge2.h"
#include "libmesh/mesh_generation.h"
#include "libmesh/linear_implicit_system.h"
#include "libmesh/gmv_io.h"
#include "libmesh/exact_solution.h"
#include "libmesh/zero_function.h"
#include "libmesh/composite_function.h"
Classes
class GRINSTesting::TurbBoundFuncBase
class GRINSTesting::TurbulentBdyFunctionU
class GRINSTesting::TurbulentBdyFunctionNu
class GRINSTesting::SATurbBCFactoryBase
class GRINSTesting::SATurbUBCFactory
class GRINSTesting::SATurbNuBCFactory
Namespaces
GRINS
GRINS namespace.
GRINSTesting
Functions
void test_error_norm (libMesh::ExactSolution &exact_sol, const std::string &system_name, const std::string &var, const std::string &norm, const double tol, int &return_flag)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 232 of file test_turbulent_channel.C.
References GRINS::Runner::get_command_line(), GRINS::Simulation::get_equation_system(), GRINS::Runner::get_input_file(), GRINS::Runner::get_libmesh_init(), GRINS::Simulation::get_multiphysics_system_name(), GRINS::Runner::get_simulation(), GRINS::Runner::init(), GRINS::Runner::run(), GRINSTesting::SATurbBCFactoryBase::set_turb_bc_values(), and test_error_norm().
 {
   // Factories needed for run
   GRINSTesting::SATurbUBCFactory grins_factory_testing_turb_u_bc("testing_turb_u");
   GRINSTesting::SATurbNuBCFactory grins_factory_testing_turb_nu_bc("testing_turb_nu");
   // Need only
   GRINS::Runner grins(argc,argv);
   const GetPot & command_line = grins.get_command_line();
   const GetPot & inputfile = grins.get_input_file();
   // Don't flag our command-line-specific variables as UFOs later
   inputfile.have_variable("mesh-1d");
   inputfile.have_variable("data-1d");
   inputfile.have_variable("soln-data");
   inputfile.have_variable("vars");
   inputfile.have_variable("norms");
   inputfile.have_variable("tol");
   const libMesh::LibMeshInit & libmesh_init = grins.get_libmesh_init();
   // Build a 1-d turbulent_bc_system to get the bc data from files
   libMesh::SerialMesh mesh(libmesh_init.comm());
   std::string oned_mesh = command_line("mesh-1d", "DIE!");
   mesh.read(oned_mesh);
   // And an EquationSystems to run on it
   libMesh::EquationSystems equation_systems (mesh);
   std::string oned_data = command_line("data-1d", "DIE!");
   equation_systems.read(oned_data, libMesh::XdrMODE::READ,
                         libMesh::EquationSystems::READ_HEADER |
                         libMesh::EquationSystems::READ_DATA |
                         libMesh::EquationSystems::READ_ADDITIONAL_DATA);
   // Get a reference to the system so that we can call update() on it
   libMesh::System & turbulent_bc_system = equation_systems.get_system<libMesh::System>("flow");
   // We need to call update to put system in a consistent state
   // with the solution that was read in
   turbulent_bc_system.update();
   // Print information about the system to the screen.
   equation_systems.print_info();
   // Prepare a global solution and a MeshFunction of the Turbulent system
   libMesh::UniquePtr<libMesh::MeshFunction> turbulent_bc_values;
   libMesh::UniquePtr<libMesh::NumericVector<libMesh::Number> > turbulent_bc_soln = libMesh::NumericVector<libMesh::Number>::build(equation_systems.comm());
   std::vector<libMesh::Number> flow_soln;
   turbulent_bc_system.update_global_solution(flow_soln);
   turbulent_bc_soln->init(turbulent_bc_system.solution->size(), true, libMesh::SERIAL);
   (*turbulent_bc_soln) = flow_soln;
   std::vector<unsigned int>turbulent_bc_system_variables;
   turbulent_bc_system_variables.push_back(0);
   turbulent_bc_system_variables.push_back(1);
   turbulent_bc_values = libMesh::UniquePtr<libMesh::MeshFunction>
     (new libMesh::MeshFunction(equation_systems,
                                *turbulent_bc_soln,
                                turbulent_bc_system.get_dof_map(),
                                turbulent_bc_system_variables ));
   turbulent_bc_values->init();
   GRINSTesting::SATurbBCFactoryBase::set_turb_bc_values( turbulent_bc_values.get() );
   // Initialize
   grins.init();
   // Solve
   grins.run();
   GRINS::Simulation & sim = grins.get_simulation();
   // Get equation systems to create ExactSolution object
   GRINS::SharedPtr<libMesh::EquationSystems> es = sim.get_equation_system();
   // Create Exact solution object and attach exact solution quantities
   //libMesh::ExactSolution exact_sol(*es);
   // Create Exact solution object and attach exact solution quantities
   libMesh::ExactSolution exact_sol(*es);
   libMesh::EquationSystems es_ref( es->get_mesh() );
   // Filename of file where comparison solution is stashed
   std::string solution_file = command_line("soln-data", "DIE!");
   es_ref.read( solution_file, libMesh::XdrMODE::DECODE,
                libMesh::EquationSystems::READ_HEADER |
                libMesh::EquationSystems::READ_DATA |
                libMesh::EquationSystems::READ_ADDITIONAL_DATA);
   exact_sol.attach_reference_solution( &es_ref );
   // Now grab the variables for which we want to compare
   unsigned int n_vars = command_line.vector_variable_size("vars");
   std::vector<std::string> vars(n_vars);
   for( unsigned int v = 0; v < n_vars; v++ )
     {
       vars[v] = command_line("vars", "DIE!", v);
     }
   // Now grab the norms to compute for each variable error
   unsigned int n_norms = command_line.vector_variable_size("norms");
   std::vector<std::string> norms(n_norms);
   for( unsigned int n = 0; n < n_norms; n++ )
     {
       norms[n] = command_line("norms", "DIE!", n);
       if( norms[n] != std::string("L2") &&
           norms[n] != std::string("H1") )
         {
           std::cerr << "ERROR: Invalid norm input " << norms[n] << std::endl
                     << "       Valid values are: L2" << std::endl
                     << "                         H1" << std::endl;
         }
     }
   const std::string& system_name = sim.get_multiphysics_system_name();
   // Now compute error for each variable
   for( unsigned int v = 0; v < n_vars; v++ )
     {
       exact_sol.compute_error(system_name, vars[v]);
     }
   int return_flag = 0;
   double tol = command_line("tol", 1.0e-10);
   // Now test error for each variable, for each norm
   for( unsigned int v = 0; v < n_vars; v++ )
     {
       for( unsigned int n = 0; n < n_norms; n++ )
         {
           test_error_norm( exact_sol, system_name, vars[v], norms[n], tol, return_flag );
         }
     }
   return return_flag;
 }
void test_error_norm (libMesh::ExactSolution & exact_sol, const std::string & system_name, const std::string & var, const std::string & norm, const double tol, int & return_flag)
Definition at line 382 of file test_turbulent_channel.C.
Referenced by main().
 {
   // We don't set return_flag unless we are setting it 1
   // since this function gets called multiple times and we don't
   // want to overwrite a previous "fail" (return_flag = 1) with
   // a "pass" (return_flag = 0)
   double error = 0.0;
   std::cout << "==========================================================" << std::endl
             << "Checking variable " << var << " using error norm " << norm << " with tol " << tol << "...";
   if( norm == std::string("L2") )
     {
       error = exact_sol.l2_error(system_name, var);
     }
   else if( norm == std::string("H1") )
     {
       error = exact_sol.h1_error(system_name, var);
     }
   else
     {
       std::cerr << "ERROR: Invalid norm " << norm << std::endl;
       exit(1);
     }
   if( error > tol )
     {
       return_flag = 1;
       std::cerr << "Tolerance exceeded for generic regression test!" << std::endl
                 << "tolerance     = " << tol << std::endl
                 << "norm of error = " << error << std::endl
                 << "norm type     = " << norm << std::endl
                 << "var           = " << var << std::endl;
     }
   else
     {
       std::cout << "PASSED!" << std::endl
                 << "==========================================================" << std::endl;
     }
   return;
 }