GRINS-0.8.0: test/exact_soln/vorticity_qoi.C File Reference
vorticity_qoi.C File Reference
#include "grins_config.h"
#include <iostream>
#include "grins/runner.h"
#include "libmesh/exact_solution.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 36 of file vorticity_qoi.C.
References GRINS::Simulation::get_qoi_value(), GRINS::Runner::get_simulation(), GRINS::Runner::init(), and GRINS::Runner::run().
 {
   GRINS::Runner grins(argc,argv);
   grins.init();
   // Solve
   grins.run();
   GRINS::Simulation & sim = grins.get_simulation();
   libMesh::Number qoi = sim.get_qoi_value( 0 );
   int return_flag = 0;
   const libMesh::Number exact_value = -0.5;
   const libMesh::Number rel_error = std::fabs( (qoi - exact_value )/exact_value );
   const libMesh::Number tol = 1.0e-11;
   if( rel_error > tol )
     {
       std::cerr << "Computed voriticity QoI mismatch greater than tolerance." << std::endl
                 << "Computed value = " << qoi << std::endl
                 << "Exact value = " << exact_value << std::endl
                 << "Relative error = " << rel_error << std::endl
                 << "Tolerance = " << tol << std::endl;
       return_flag = 1;
     }
   return return_flag;
 }